### ISSUE TITLE
Normalization of Force parameter incomplete, ConfirmAction defaulting to false

### ISSUE THREAD

**Issue by begoldsm** [Azure/azure-powershell#2821] opened 2016-08-24 01:54 UTC
From this commit: 0e95237c24ffd5103b1e48af46f0353139c03051
Force parameters were removed from cmdlets, however they were not removed from all cmdlets (for example, Remove-AzureRMDataLakeStoreItem still has a force, as does Remove-AzureRMResourceGroup). Additionally, the change to ConfirmAction resulted in the default value being used, which is false. This means that, by default, no prompt is given for potentially destructive operations (such as Remove-AzureRMDataLakeStoreItemAclEntry). This needs to be re-examined and we need to ensure that the default behavior for ConfirmAction is to prompt, and only skip prompting if the user passes in -Confirm:$false

From this commit: 2158bb81fcadcf05341fc3aa7f3f3a196aab5ceb
Force parameters were removed from cmdlets without also update the cmdlet help.xml files. This is resulting in the help incorrectly showing "Force" parameters as available for cmdlets that no longer have them.

**Comment by markcowl** [comment] 2016-08-24 02:30
@begoldsm Normalization is complete.  The previous implementation did not use ShouldProcess correctly and now does, so that users can use -Confirm and -WhatIf as intended with these cmdlets.  Please see:  https://gist.github.com/markcowl/338e16fe5c8bbf195aff9f8af0db585d as we sent out for review with the original PR for complete details.

ConfirmImpact should not be changed for actions that are not exceedingly destructive.  Force parameters were left on cmdlets that either have special circumstances that can require additional authentcation (container not empty, file overwrtite)

Good catch on the Fporce parameters in help.  Will you be updating this?

**Comment by markcowl** [comment] 2016-08-24 17:11
Filed this issue for the force parameters here: https://github.com/Azure/azure-powershell/issues/2826 Closing this for now in favor of the more targeted bug

**Closed by markcowl** 2016-08-24 17:11 UTC
