### ISSUE TITLE
Get-AzureKeyVaultSecret does not error out when the secret is not found

### ISSUE THREAD

**Issue by blueelvis** [Azure/azure-powershell#8609] opened 2019-02-24 21:34 UTC
## Description
`Get-AzureKeyVaultSecret` commandlet does not error out when a secret is not found. It should error out because the secret was not found.

## Steps to reproduce
1. Create a Key Vault
2. Ensure that your user has the proper access policies for managing the secrets.
```powershell
Get-AzureKeyVaultSecret -VaultName ssw3sTL01 -Name testSecre -Debug
```

## Module versions
```powershell
PS C:\Windows\system32> Get-Module -Name AzureRM* -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                                                             
---------- -------    ----                                ----------------                                                                             
Script     6.13.1     AzureRM                                                                                                                          
Script     0.6.14     AzureRM.AnalysisServices            {Resume-AzureRmAnalysisServicesServer, Suspend-AzureRmAnalysisServicesServer, Get-AzureRmA...
Script     6.1.7      AzureRM.ApiManagement               {Add-AzureRmApiManagementRegion, Get-AzureRmApiManagementSsoToken, New-AzureRmApiManagemen...
Script     0.1.8      AzureRM.ApplicationInsights         {Get-AzureRmApplicationInsights, New-AzureRmApplicationInsights, Remove-AzureRmApplication...
Script     6.1.1      AzureRM.Automation                  {Get-AzureRMAutomationHybridWorkerGroup, Remove-AzureRmAutomationHybridWorkerGroup, Get-Az...
Script     4.0.11     AzureRM.Backup                      {Backup-AzureRmBackupItem, Enable-AzureRmBackupContainerReregistration, Get-AzureRmBackupC...
Script     4.1.5      AzureRM.Batch                       {Remove-AzureRmBatchAccount, Get-AzureRmBatchAccount, Get-AzureRmBatchAccountKeys, New-Azu...
Script     0.14.6     AzureRM.Billing                     {Get-AzureRmBillingInvoice, Get-AzureRmBillingPeriod, Get-AzureRmEnrollmentAccount}          
Script     5.0.6      AzureRM.Cdn                         {Get-AzureRmCdnProfile, Get-AzureRmCdnProfileSsoUrl, New-AzureRmCdnProfile, Remove-AzureRm...
Script     0.9.12     AzureRM.CognitiveServices           {Get-AzureRmCognitiveServicesAccount, Get-AzureRmCognitiveServicesAccountKey, Get-AzureRmC...
Script     5.9.1      AzureRM.Compute                     {Remove-AzureRmAvailabilitySet, Get-AzureRmAvailabilitySet, New-AzureRmAvailabilitySet, Up...
Script     0.3.7      AzureRM.Consumption                 {Get-AzureRmConsumptionBudget, Get-AzureRmConsumptionMarketplace, Get-AzureRmConsumptionPr...
Script     0.2.12     AzureRM.ContainerInstance           {New-AzureRmContainerGroup, Get-AzureRmContainerGroup, Remove-AzureRmContainerGroup, Get-A...
Script     1.0.10     AzureRM.ContainerRegistry           {New-AzureRmContainerRegistry, Get-AzureRmContainerRegistry, Update-AzureRmContainerRegist...
Script     5.0.3      AzureRM.DataFactories               {Remove-AzureRmDataFactory, Get-AzureRmDataFactoryRun, Get-AzureRmDataFactorySlice, Save-A...
Script     0.5.11     AzureRM.DataFactoryV2               {Set-AzureRmDataFactoryV2, Update-AzureRmDataFactoryV2, Get-AzureRmDataFactoryV2, Remove-A...
Script     5.1.4      AzureRM.DataLakeAnalytics           {Get-AzureRmDataLakeAnalyticsDataSource, New-AzureRmDataLakeAnalyticsCatalogCredential, Re...
Script     6.2.1      AzureRM.DataLakeStore               {Get-AzureRmDataLakeStoreTrustedIdProvider, Remove-AzureRmDataLakeStoreTrustedIdProvider, ...
Script     4.0.9      AzureRM.DevTestLabs                 {Get-AzureRmDtlAllowedVMSizesPolicy, Get-AzureRmDtlAutoShutdownPolicy, Get-AzureRmDtlAutoS...
Script     5.1.0      AzureRM.Dns                         {Get-AzureRmDnsRecordSet, New-AzureRmDnsRecordConfig, Remove-AzureRmDnsRecordSet, Set-Azur...
Script     0.3.7      AzureRM.EventGrid                   {New-AzureRmEventGridTopic, Get-AzureRmEventGridTopic, Set-AzureRmEventGridTopic, New-Azur...
Script     0.7.0      AzureRM.EventHub                    {New-AzureRmEventHubNamespace, Get-AzureRmEventHubNamespace, Set-AzureRmEventHubNamespace,...
Script     4.1.8      AzureRM.HDInsight                   {Get-AzureRmHDInsightJob, New-AzureRmHDInsightSqoopJobDefinition, Wait-AzureRmHDInsightJob...
Script     5.1.5      AzureRM.Insights                    {Get-AzureRmMetricDefinition, Get-AzureRmMetric, Remove-AzureRmLogProfile, Get-AzureRmLogP...
Script     3.1.8      AzureRM.IotHub                      {Add-AzureRmIotHubKey, Get-AzureRmIotHubEventHubConsumerGroup, Get-AzureRmIotHubConnection...
Script     5.2.1      AzureRM.KeyVault                    {Add-AzureKeyVaultCertificate, Update-AzureKeyVaultCertificate, Stop-AzureKeyVaultCertific...
Script     4.1.4      AzureRM.LogicApp                    {Get-AzureRmIntegrationAccountAgreement, Get-AzureRmIntegrationAccountCallbackUrl, Get-Azu...
Script     0.18.5     AzureRM.MachineLearning             {Move-AzureRmMlCommitmentAssociation, Get-AzureRmMlCommitmentAssociation, Get-AzureRmMlCom...
Script     0.4.8      AzureRM.MachineLearningCompute      {Get-AzureRmMlOpCluster, Get-AzureRmMlOpClusterKey, Test-AzureRmMlOpClusterSystemServicesU...
Script     0.2.7      AzureRM.MarketplaceOrdering         {Get-AzureRmMarketplaceTerms, Set-AzureRmMarketplaceTerms}                                   
Script     0.10.4     AzureRM.Media                       {Sync-AzureRmMediaServiceStorageKeys, Set-AzureRmMediaServiceKey, Get-AzureRmMediaServiceK...
Script     6.11.1     AzureRM.Network                     {Add-AzureRmApplicationGatewayAuthenticationCertificate, Get-AzureRmApplicationGatewayAuth...
Script     5.0.3      AzureRM.NotificationHubs            {Get-AzureRmNotificationHub, Get-AzureRmNotificationHubAuthorizationRules, Get-AzureRmNoti...
Script     5.0.6      AzureRM.OperationalInsights         {New-AzureRmOperationalInsightsAzureActivityLogDataSource, New-AzureRmOperationalInsightsC...
Script     1.1.0      AzureRM.PolicyInsights              {Get-AzureRmPolicyEvent, Get-AzureRmPolicyState, Get-AzureRmPolicyStateSummary, Get-AzureR...
Script     4.1.10     AzureRM.PowerBIEmbedded             {Remove-AzureRmPowerBIWorkspaceCollection, Get-AzureRmPowerBIWorkspaceCollection, Get-Azur...
Script     5.8.2      AzureRM.Profile                     {Disable-AzureRmDataCollection, Disable-AzureRmContextAutosave, Enable-AzureRmDataCollecti...
Script     4.1.9      AzureRM.RecoveryServices            {Get-AzureRmRecoveryServicesBackupProperty, Get-AzureRmRecoveryServicesVault, Get-AzureRmR...
Script     4.5.2      AzureRM.RecoveryServices.Backup     {Backup-AzureRmRecoveryServicesBackupItem, Get-AzureRmRecoveryServicesBackupManagementServ...
Script     0.2.12     AzureRM.RecoveryServices.SiteRec... {Edit-AzureRmRecoveryServicesAsrRecoveryPlan, Get-AzureRmRecoveryServicesAsrAlertSetting, ...
Script     5.1.0      AzureRM.RedisCache                  {Remove-AzureRmRedisCachePatchSchedule, New-AzureRmRedisCacheScheduleEntry, Get-AzureRmRed...
Script     0.3.12     AzureRM.Relay                       {New-AzureRmRelayNamespace, Get-AzureRmRelayNamespace, Set-AzureRmRelayNamespace, Remove-A...
Script     6.7.3      AzureRM.Resources                   {Get-AzureRmProviderOperation, Remove-AzureRmRoleAssignment, Get-AzureRmRoleAssignment, Ne...
Script     0.16.10    AzureRM.Scheduler                   {Disable-AzureRmSchedulerJobCollection, Enable-AzureRmSchedulerJobCollection, Get-AzureRmS...
Script     0.6.13     AzureRM.ServiceBus                  {New-AzureRmServiceBusNamespace, Get-AzureRmServiceBusNamespace, Set-AzureRmServiceBusName...
Script     0.3.15     AzureRM.ServiceFabric               {Add-AzureRmServiceFabricApplicationCertificate, Add-AzureRmServiceFabricClientCertificate...
Script     1.0.0      AzureRM.SignalR                     {New-AzureRmSignalR, Get-AzureRmSignalR, Get-AzureRmSignalRKey, New-AzureRmSignalRKey...}    
Script     4.12.1     AzureRM.Sql                         {Get-AzureRmSqlDatabaseTransparentDataEncryption, Get-AzureRmSqlDatabaseTransparentDataEnc...
Script     5.2.0      AzureRM.Storage                     {Get-AzureRmStorageAccount, Get-AzureRmStorageAccountKey, New-AzureRmStorageAccount, New-A...
Script     4.0.10     AzureRM.StreamAnalytics             {Get-AzureRmStreamAnalyticsFunction, Get-AzureRmStreamAnalyticsDefaultFunctionDefinition, ...
Script     4.0.5      AzureRM.Tags                        {Remove-AzureRmTag, Get-AzureRmTag, New-AzureRmTag}                                          
Script     4.1.3      AzureRM.TrafficManager              {Add-AzureRmTrafficManagerCustomHeaderToEndpoint, Remove-AzureRmTrafficManagerCustomHeader...
Script     4.0.5      AzureRM.UsageAggregates             Get-UsageAggregates                                                                          
Script     5.2.0      AzureRM.Websites                    {Get-AzureRmAppServicePlan, Set-AzureRmAppServicePlan, New-AzureRmAppServicePlan, Remove-A...
```

## Debug output
```
DEBUG: 02:58:11 - GetAzureKeyVaultSecret begin processing with ParameterSet 'ByVaultName'.
DEBUG: 02:58:13 - using account id 'aaa@aaa.com'...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 02/24/2019 21:28:13:  - TokenCache: Serializing token cache with 18 items.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 02/24/2019 21:28:13:  - TokenCache: Serializing token cache with 18 items.

DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: '2dfc6a32-d03c-4504-8d69-f08da326f294', Endpoint: 'https://login.micr
osoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://vault.azur
e.net', ValidateAuthrity: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/2dfc6a32-d03c-4504-8d69-f08da326f294/', 
CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: '2dfc6a32-d03c-4504-8d69-f08da326f294', AdEndpoint: 'https://login.
microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 02/24/2019 21:28:13: d09e99b2-cbd0-4cab-a80a-78c468715587 - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/2dfc6a32-d03c-4504-8d69-f08da326f294/
	Resource: https://vault.azure.net
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (18 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 02/24/2019 21:28:13:  - TokenCache: Deserialized 18 items to token cache.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 02/24/2019 21:28:13: d09e99b2-cbd0-4cab-a80a-78c468715587 - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 02/24/2019 21:28:13: d09e99b2-cbd0-4cab-a80a-78c468715587 - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 02/24/2019 21:28:13: d09e99b2-cbd0-4cab-a80a-78c468715587 - TokenCache: 46.5966478933333 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 02/24/2019 21:28:13: d09e99b2-cbd0-4cab-a80a-78c468715587 - TokenCache: A matching item (access token or refresh token or both) was found in the 
cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 02/24/2019 21:28:13: d09e99b2-cbd0-4cab-a80a-78c468715587 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token
 was retuned:
	Access Token Hash: S6gd7QvN7MthDh1GLs=
	Refresh Token Hash: TNC6VoMUPTQd3RfMIo=
	Expiration Time: 02/24/2019 22:14:48 +00:00
	User Hash: +nMs9cFQb/7j7XmTr72ZzC9Sw=
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 02/24/2019 21:28:13:  - TokenCache: Serializing token cache with 18 items.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 02/24/2019 21:28:13:  - TokenCache: Serializing token cache with 18 items.

DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '02/24/2019 22:14:48 +00:00', MultipleResource? 'True', Tenant: 'bbbbbb-d0
3c-4504-8d69-f08da326f294', UserId: 'aaa@aaa.com'
DEBUG: [Common.Authentication]: User info for token DisplayId: 'aaa@aaa.com', Name:  , IdProvider: 'https://sts.windows.net/f32b97f0-efb
8-4bc3-91ee-18a6e5f635c9/', Uid: '6e2d74e3-8ec9-4a53-9463-53bf6cf36596'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '02/24/2019 22:14:48 +00:00' Comparing to '02/24/2019 21:28:13 +00:00' With thr
eshold '00:05:00', calculated time until token expiry: '00:46:35.7954844'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://aaaa.vault.azure.net/secrets/testSecre/?api-version=7.0

Headers:
x-ms-client-request-id        : fe066688-465b-47c9-998b-9e571d29519b
accept-language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Pragma                        : no-cache
x-ms-keyvault-region          : eastus
x-ms-request-id               : 67a7ce47-676a-4d11-9752-6a2c12f282f5
x-ms-keyvault-service-version : 1.1.0.861
x-ms-keyvault-network-info    : addr=223.230.24.71;act_addr_fam=InterNetwork;
Strict-Transport-Security     : max-age=31536000;includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Sun, 24 Feb 2019 21:28:14 GMT
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "error": {
    "code": "SecretNotFound",
    "message": "Secret not found: testSecre"
  }
}


DEBUG: AzureQoSEvent: CommandName - Get-AzureKeyVaultSecret; IsSuccess - True; Duration - 00:00:02.7193575; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 02:58:14 - GetAzureKeyVaultSecret end processing.
DEBUG: 02:58:14 - GetAzureKeyVaultSecret end processing.
```

## Error output
```
PS C:\Windows\system32> Resolve-AzureRmError


   HistoryId: 2


Message        : Could not find a part of the path 'C:\Users\aaaa\.Azure\AzInstallationChecks.json'.
StackTrace     :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
                    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, 
                 Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean 
                 checkHost)
                    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
                    at Microsoft.PowerShell.Commands.FileSystemProvider.NewItem(String path, String type, Object value)
Exception      : System.IO.DirectoryNotFoundException
InvocationInfo : {New-Item}
Line           :         New-Item -Path $pathToInstallationChecks -ErrorAction Stop -ItemType File -Value ($installationchecks | ConvertTo-Json 
                 -ErrorAction Stop)
                 
Position       : At C:\Program Files\WindowsPowerShell\Modules\AzureRM.KeyVault\5.2.1\StartupScripts\AzureRmError.ps1:17 char:9
                 +         New-Item -Path $pathToInstallationChecks -ErrorAction Stop -I ...
                 +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2



   HistoryId: 1


Message        : Could not find a part of the path 'C:\Users\aaaa\.Azure\AzInstallationChecks.json'.
StackTrace     :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
                    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, 
                 Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean 
                 checkHost)
                    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
                    at Microsoft.PowerShell.Commands.FileSystemProvider.NewItem(String path, String type, Object value)
Exception      : System.IO.DirectoryNotFoundException
InvocationInfo : {New-Item}
Line           :         New-Item -Path $pathToInstallationChecks -ErrorAction Stop -ItemType File -Value ($installationchecks | ConvertTo-Json 
                 -ErrorAction Stop)
                 
Position       : At C:\Program Files\WindowsPowerShell\Modules\AzureRM.Profile\5.8.2\StartupScripts\AzureRmError.ps1:17 char:9
                 +         New-Item -Path $pathToInstallationChecks -ErrorAction Stop -I ...
                 +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1
```

**Comment by markcowl** [comment] 2019-02-25 18:08
It seems appropriate for a ```Get``` cmdlet to return nothing if no matching value is found.  Unfortunately, this is not universally applied across the cmdlets (as it should be).

Why would throwing an exception in this case work better than returning nothing for your scenario?

**Comment by lwajswaj** [comment] 2019-02-25 19:15
Agree with @markcowl as, in general, for cmdlets not behaving like this, you force this behavior by using -ErrorAction SilentlyContinue.

**Comment by maddieclayton** [comment] 2019-03-05 01:34
Closing as by design.

**Closed by maddieclayton** 2019-03-05 01:34 UTC
Labels: More Info :label:

**Comment by blueelvis** [comment] 2019-03-06 09:57
@markcowl Yea, this type of behavior should be applicable across all types of `Get` commandlets for Azure PowerShell. But thanks! I will not write few more lines of code to catch this.

@lwajswaj - Thanks!
