### ISSUE TITLE
Import-AzureRmAutomationDscConfiguration Exception: "Invalid argument specified"

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2196] opened 2016-05-02 20:20 UTC
> Import-AzureRmAutomationDscConfiguration : BadRequest: {"Message":"Invalid argument specified. Argument script cannot be null."}

```
$ImportDsc = @{
    ResourceGroupName = $AutomationAccount.ResourceGroupName;
    AutomationAccountName = $AutomationAccount.AutomationAccountName;
    SourcePath = '{0}\03-DSC Configuration.ps1';
    Description = 'This DSC Configuration contains the infrastructure configuration for the Art of Shell organization.';
    Published = $true;
    };
Import-AzureRmAutomationDscConfiguration @ImportDsc;
```

**NOTE**: Needs better validation and error handling when invalid path specified for `-SourcePath` parameter.

Cheers,
**Trevor Sullivan**
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by trevor-schmidt** [comment] 2018-10-12 16:41
Trying to use a blob within a storage account as the -SourcePath but receiving the BadRequest: {"Message":"Invalid argument specified. Argument script cannot be null."}

**Comment by nitinbps** [comment] 2019-06-14 01:36
Duplicate of https://github.com/Azure/azure-powershell/issues/1804

**Closed by nitinbps** 2019-06-14 01:36 UTC
Labels: Automation, Service Attention, automation-dsc
