### ISSUE TITLE
Get-AzStorageBlobContent command fails to download blob containing folders in the path due to error <folder> doesn't exist

### ISSUE THREAD

**Issue by nayakshweta** [Azure/azure-powershell#12623] opened 2020-08-10 10:52 UTC
## Description
Issue is seen with storage accounts with HNS disabled.

**Repro result with Az.Storage version 2.3.0** 
Get-AzStorageBlobContent -Container "testcontainer" -Blob "test/blob/Azure.Storage.Blob.SDK (1).PNG" -Context $ctx -Destination "."
Get-AzStorageBlobContent : Directory 'C:\WINDOWS\system32\test\blob' doesn't exist.
At line:1 char:1
+ Get-AzStorageBlobContent -Container "testcontainer" -Blob "test/blob/ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-AzStorageBlobContent], ArgumentException
    + FullyQualifiedErrorId : ArgumentException,Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobCont 
   entCommand

## Steps to reproduce

```
We should have a blob path consisting of folders as seen below in the storage account
![image](https://user-images.githubusercontent.com/16984456/89774688-f640c680-db23-11ea-8d7d-7b375f644649.png)

The blob path folder structure should be present on the destination.

We can reproduce the issue by running these commands.
Get storage context :
$ctx = New-AzStorageContext -StorageAccountName "stgragrs" -StorageAccountKey "<key>"

Then Get blob content 
Get-AzStorageBlobContent -Container "testcontainer" -Blob "test/blob/Azure.Storage.Blob.SDK (1).PNG" -Context $ctx -Destination "."

The command is unable to create the parent folder path while copying the blob.

```

## Environment data

```
Issue is reproducible in latest PS Version too

$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```
Issue is reproducible with **az 4.4.0**, **4.5.0** , **az.storage 2.3.0** and **2.3.1-preview** versions.

Issue is NOT reproducible with az.storage 2.2.0 and older
This version gives the expected result

**Get-AzStorageBlobContent -Container "testcontainer" -Blob "test/blob/Azure.Storage.Blob.SDK (1).PNG" -Context $ctx -Destination "."**

Container Uri: https://stgragrs.blob.core.windows.net/testcontainer

Name                 BlobType  Length          ContentType                    LastModified         AccessTier SnapshotTime  
----                 --------  ------          -----------                    ------------         ---------- ------------  
test/blob/Azure.S... BlockBlob 25404           image/png                      2020-08-10 08:19:24Z Unknown                  


**dir test/blob**
    Directory: C:\WINDOWS\system32\test\blob

Mode                 LastWriteTime         Length Name                                                                      
----                 -------------         ------ ----                                                                      
-a----         8/10/2020   3:02 PM          25404 Azure.Storage.Blob.SDK (1).PNG      

```

## Debug output

```
Get-AzStorageBlobContent -Container "testcontainer" -Blob "test/blob/Azure.Storage.Blob.SDK (1).PNG" -Context $ctx -Destination "."
DEBUG: 4:19:07 PM - Init Operation Context for 'GetAzureStorageBlobContentCommand' with client request id  Azure-Storage-PowerShell-e6a008e7-d958-4f2a-ba74-7baa2c3b6ae7. If you want to get more details, please add "-Debug" to your command.
DEBUG: 4:19:07 PM - Use storage account 'stgragrs' from storage context.
Get-AzStorageBlobContent: Directory 'C:\Windows\test\blob' doesn't exist.
DEBUG: 4:19:09 PM - GetAzureStorageBlobContentCommand end processing, Start 4 remote calls. Finish 4 remote calls. Elapsed time 4843253.27 ms. Client operation id: Azure-Storage-PowerShell-e6a008e7-d958-4f2a-ba74-7baa2c3b6ae7.
DEBUG: 4:19:09 PM - GetAzureStorageBlobContentCommand end processing.

```

## Error output

```
Resolve-AzError output

Message        : Directory 'C:\Windows\test\blob' doesn't exist.
StackTrace     :    at Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobContentCommand.GetFullRec
                 eiveFilePath(String fileName, String blobName, Nullable`1 snapshotTime)
                    at Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobContentCommand.GetBlobCon
                 tent(CloudBlob blob, String fileName, Boolean isValidBlob)
                    at Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobContentCommand.GetBlobCon
                 tent(CloudBlobContainer container, String blobName, String fileName)
                    at Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobContentCommand.GetBlobCon
                 tent(String containerName, String blobName, String fileName)
                    at
                 Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobContentCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronously
                 OrAsJob>b__3_0(T c)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet, Action`1 executor)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet)
                    at
                 Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobContentCommand.ProcessRecord()
Exception      : System.ArgumentException
InvocationInfo : {Get-AzStorageBlobContent}
Line           : Get-AzStorageBlobContent -Container "testcontainer" -Blob "test/blob/Azure.Storage.Blob.SDK (1).PNG"
                 -Context $ctx -Destination "."
Position       : At line:1 char:1
                 + Get-AzStorageBlobContent -Container "testcontainer" -Blob "test/blob/ …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 11

```

**Comment by DOMZE** [comment] 2020-08-10 20:36
I come across the same problem with Az.Storage 2.4.0. Issue does not occur with Az.Storage 2.2.0

**Comment by blueww** [comment] 2020-08-11 02:25
@nayakshweta , @DOMZE 

Thanks for raising this issue!

This is the same issue as https://github.com/Azure/azure-powershell/issues/12592.
We will fix it in the next release.
Before the issue is fixed, you can find the workaround in https://github.com/Azure/azure-powershell/issues/12592.

**Comment by blueww** [comment] 2020-08-11 08:03
The fix PR for the issue is already merged. https://github.com/Azure/azure-powershell/pull/12617

**Comment by blueww** [comment] 2020-08-24 02:36
As the PR is merged, and the GA is ready for release, close this issue.
The fix will be out in 8/25 release. (Az.Storage 2.5.0)

**Closed** 2020-08-24 02:37 UTC
Labels: Service Attention, Storage
