### ISSUE TITLE
Add-AzWebtestAlertRule stopped working

### ISSUE THREAD

**Issue by aorlenko83** [Azure/azure-powershell#10907] opened 2020-01-15 20:35 UTC
I have a following script that we use for creating pingtest alert rule. It used to work fine until recent time.

```
param(
    [string]$resourceGroupName = 'rg',
    [string]$emails = 'some@email.com',
    [string]$webTestName = 'PingTestName',
    [string]$alertRuleName = 'WebtestAlertName'
)

$emailAction = New-AzAlertRuleEmail -CustomEmail $emails

$webTestResource = Get-AzResource -ResourceGroupName $resourceGroupName -Name $webTestName `
	-ResourceType "Microsoft.Insights/webtests"

Add-AzWebtestAlertRule -Name $alertRuleName -Location "East US" `
	-ResourceGroupName $resourceGroupName -WindowSize 00:05:00 -MetricName "metric" `
	-TargetResourceUri $webTestResource.ResourceId `
	-Description "Webtest Alert" -FailedLocationCount 3 -Action $emailAction
```
So before executing the script, the AppInsights and PingTest must exist. This script is used for creating alert for existing PingTest.

When I run it though, I have following exception message:

> Add-AzWebtestAlertRule : Exception type: ErrorResponseException, Message: You cannot create or modify classic metric alerts for this
> subscription as this subscription 8680d0a6-00ad-48a8-9716-ca1dcd3e1296 is being migrated or has been migrated to use new metric alerts. Learn
> more - aka.ms/alertclassicretirement, Code: BadRequest, Status code:BadRequest, Reason phrase: Bad Request

But this message along with the provided link don't seem to help fix the issue.
I'm not sure when exactly this script became invalid, however it worked fine few month ago.

Can you help understand what the issue can be? Where exactly is this "classic" metric alert (or anything else) that is not allowed?

**Comment by dingmeng-xue** [comment] 2020-01-17 10:34
Microsoft.Insights/webtests cannot be added as rule. The issue can be reproduced. We need to check if service API is changed.

**Comment by VeryEarly** [comment] 2020-03-04 14:10
@dingmeng-xue 

Both Azure-PowerShell and Azure-Cli are using API [2016-03-01](https://docs.microsoft.com/en-us/rest/api/monitor/alertrules/createorupdate) for add alert rule.

In Azure Portal, add rule was done by calling:
https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Insights/metricalerts/{ruleName}?api-version=2017-09-01-preview

while delete was called through API [2018-03-01](https://docs.microsoft.com/en-us/rest/api/monitor/metricalerts/delete)

Shall we upgrade the SDK version for this cmdlet since it was broken?

**Comment by harelbr** [comment] 2022-11-06 07:33
Just to close this thread:
The Add-AzWebtestAlertRule cmdlet is relevant for the classic alerts feature, which is already retired on public cloud, and will be fully retired on other national clouds by Feb 2024.

To set up a metric alert rule on a webtest, please use the [Add-AzMetricAlertRuleV2](https://learn.microsoft.com/en-us/powershell/module/az.monitor/add-azmetricalertrulev2?view=azps-9.1.0) cmdlet.

**Closed by harelbr** 2022-11-06 07:33 UTC
Labels: Monitor, Azure PS Team, feature-request, Monitor - Alerts, customer-reported
