### ISSUE TITLE
No Powershell Command-let for AzureBatch to sync Keys for the Attached Storage Account 

### ISSUE THREAD

**Issue by MonikaReddy-MSFT** [Azure/azure-powershell#12263] opened 2020-06-25 13:00 UTC
Moving this to PowerShell Repo from azure docs since this is a product question and not a docs question. 

 From Customer - 
Could not find any PowerShell commandlet for the SyncKeys option which syncs the Azure storage accounts keys in Batch.

https://docs.microsoft.com/en-us/rest/api/batchmanagement/batchaccount/synchronizeautostoragekeys#code-try-0

https://docs.microsoft.com/en-us/cli/azure/batch/account/autostorage-keys?view=azure-cli-latest

Rest API call and CLI commands are present.
Was wondering why PS commands are not added in the AzureRm.Batch module.

Need this for Auto Secret Rotation for storage account.

https://github.com/MicrosoftDocs/azure-docs-powershell/issues/1276

**Comment by bgklein** [comment] 2020-06-25 22:06
Duplicate of #10704

**Closed by bgklein** 2020-06-25 22:06 UTC
Labels: Batch, Service Attention, customer-reported, question
