### ISSUE TITLE
Issue Get-AzureVM status same VM but different status

### ISSUE THREAD

**Issue by cloudmelon** [Azure/azure-powershell#6466] opened 2018-06-14 19:28 UTC
### Description
Issue Get Azure VM status same commands but different status
The commands :
$vms = Get-AzureVM ( here have some information of Azure VM , the status of VM is : StoppedDeallocated )

But while foreach it

Foreach ($vm in $vms) {

// here I am printing the $vm with Vm status ( it displays stopped )
}

### Script/Steps for Reproduction

```
$vms = Get-AzureVM```

### Module Version

<!-- Please run (Get-Module -Name AzureRM -ListAvailable) to get the version(s) of AzureRM installed on your machine -->

```powershell
Get-Module -Name AzureRM -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

![image](https://user-images.githubusercontent.com/4621560/41505813-ef18a518-7210-11e8-8d03-11cc3540ae88.png)

```

```

**Comment by praries880** [comment] 2018-06-15 22:44
@cloudmelon 
Can you provide us with the output of the following command : `gmo -ListAvailable`

and the output of the cmdlets after you set ` $DebugPreference="Continue"`

Thanks

**Comment by cloudmelon** [comment] 2018-06-17 07:34
Hi here are the outputs:
![image](https://user-images.githubusercontent.com/4621560/41505821-4c30391e-7211-11e8-9cdd-5e8f7368375a.png)

![image](https://user-images.githubusercontent.com/4621560/41505826-65a5e358-7211-11e8-8715-778c69708a3f.png)

![image](https://user-images.githubusercontent.com/4621560/41505831-76b36efe-7211-11e8-932e-c004171e042d.png)

![image](https://user-images.githubusercontent.com/4621560/41505837-85ee9538-7211-11e8-9773-b67ce300a3ea.png)

![image](https://user-images.githubusercontent.com/4621560/41505841-945eb2d8-7211-11e8-8cbd-7b76313c61a5.png)

**Comment by cloudmelon** [comment] 2018-06-17 07:38
After $DebugPreference="Continue" the same command with the following output : 

![image](https://user-images.githubusercontent.com/4621560/41505849-c54d2744-7211-11e8-88c4-f43877f41592.png)

![image](https://user-images.githubusercontent.com/4621560/41505852-ec17d338-7211-11e8-8157-67f8eac3cd1e.png)

![image](https://user-images.githubusercontent.com/4621560/41505856-02f18ae0-7212-11e8-91bc-a1e942011a41.png)



![image](https://user-images.githubusercontent.com/4621560/41505859-12a85932-7212-11e8-8827-3f3a32a688bc.png)

![image](https://user-images.githubusercontent.com/4621560/41505866-22ceff50-7212-11e8-8f0a-c631d65393ff.png)

**Comment by praries880** [comment] 2018-06-18 17:03
@hyonholee Can you take a look at the issue?

**Comment by hyonholee** [comment] 2018-06-18 17:58
Can you check the following values?

$vms[0].Status
$vms[0].PowerState

The fist one returns the instance status, and the second returns the power state.

**Comment by praries880** [comment] 2018-06-18 18:03
@cloudmelon can you paste the output for @hyonholee suggestions?

**Comment by cloudmelon** [comment] 2018-06-19 10:00
I see it seems that Status and PowerState is not the same value ( as shown in the following )
![image](https://user-images.githubusercontent.com/4621560/41590733-ff7abb32-73b7-11e8-872a-6e627e906185.png)

**Comment by cormacpayne** [comment] 2018-07-03 15:22
@hyonholee @praries880 would you mind taking a look at the output returned from @cloudmelon ?

**Comment by cloudmelon** [comment] 2018-07-31 08:28
Hi @huangpf thanks for your answer. I take ' powerstate' into account in my case. But I really would like to propose a update in documentation where will mention the difference between ' powerstate and status'.

**Comment by maddieclayton** [comment] 2018-11-13 23:20
Closing as by design.

**Closed by maddieclayton** 2018-11-13 23:20 UTC
Labels: Compute, Compute - VM, Service Attention, Triaged
