### ISSUE TITLE
Add-AzureRmAccount throws error in centos 7 

### ISSUE THREAD

**Issue by safrazhanas** [Azure/azure-powershell#4509] opened 2017-08-26 01:34 UTC
### PowerShell Version
Name                           Value                                                                                                                                                                              
----                           -----                                                                                                                                                                              
PSVersion                      6.0.0-beta                                                                                                                                                                         
PSEdition                      Core                                                                                                                                                                               
GitCommitId                    v6.0.0-beta.5                                                                                                                                                                      
OS                             Linux 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017                                                                                                               
Platform                       Unix                                                                                                                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                                                                                
SerializationVersion           1.1.0.1                                                                                                                                                                            
WSManStackVersion              3.0 

### Module Version

PS /home/safraz> Get-Module PowerShellGet -list | Select-Object Name,Version,Path                                                                                                                                  

Name          Version Path                                                                                   
----          ------- ----                                                                                   
PowerShellGet 1.1.3.1 /opt/microsoft/powershell/6.0.0-beta.5/Modules/PowerShellGet/1.1.3.1/PowerShellGet.psd1

PS /home/safraz> get-module AzureRM.Profile.Netcore -list | Select-Object Name,Version,Path                                                                                                                        

Name                    Version Path                                                                                                     
----                    ------- ----                                                                                                     
AzureRM.Profile.Netcore 0.9.1   /opt/microsoft/powershell/6.0.0-beta.5/Modules/AzureRM.Profile.Netcore/0.9.1/AzureRM.Profile.Netcore.psd1

### Description

When i try to issue below command by replacing correct placeholders.

Add-AzureRmAccount -Credential $cred -ServicePrincipal -TenantId $tenantId -Environment $environment -SubscriptionId $subscriptionId

I get following error (i have removed application id)

Add-AzureRmAccount : AADSTS50001: The application named https://login.microsoftonline.com/XXXXXX/ was not found in the tenant named XXXXXX.  This can 
happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant.  You might have sent your authentication request to the wrong tenant.

My question is the same command is working in windows environment. What am i doing wrong here?

**Comment by twsouthwick** [comment] 2017-08-29 22:57
This is probably related (or a duplicate) to #4476. `Login-AzureRmAccount` is an alias for `Add-AzureRmAccount`. When you tried in windows, did you do it in Powershell 5 (the built in one), or install Powershell 6 and use the AzureRm.Netcore module?

**Comment by TechnologyAnimal** [comment] 2017-08-30 04:37
I have the same problem using dotnetcore 2.0 on PSv6 with OSX 10.12.3.

Name                           Value                                           
----                           -----                                           
PSVersion                      6.0.0-beta                                      
PSEdition                      Core                                            
GitCommitId                    v6.0.0-beta.4                                   
OS                             Darwin 16.4.0 Darwin Kernel Version 16.4.0: T...
Platform                       Unix                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1                                         
WSManStackVersion              3.0

**Comment by twitchax** [comment] 2017-10-25 07:08
Closing as duplicate of #4476.

**Closed by twitchax** 2017-10-25 07:08 UTC
Labels: Azure PS Team
