### ISSUE TITLE
Error in TypeData when importing multiple versions of AzureRM.Profile

### ISSUE THREAD

**Issue by cormacpayne** [Azure/azure-powershell#4835] opened 2017-10-23 17:12 UTC
On a machine with the latest version of `AzureRM` installed (4.4.1) and a "spoofed" later version installed (5.0.0),

```powershell
PS C:\> Get-Module -ListAvailable -Name AzureRM.Profile,AzureRM.Compute


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     4.0.0      AzureRM.Compute                     {Remove-AzureRmAvailabilitySet, Get-AzureRmAvailabilitySet, New-AzureRmAvailabilitySet, Update-AzureRmAvailabilitySet...}
Script     3.4.1      AzureRM.Compute                     {Remove-AzureRmAvailabilitySet, Get-AzureRmAvailabilitySet, New-AzureRmAvailabilitySet, Update-AzureRmAvailabilitySet...}
Script     4.0.0      AzureRM.Profile                     {Disable-AzureRmDataCollection, Disable-AzureRmContextAutosave, Enable-AzureRmDataCollection, Enable-AzureRmContextAutosave...}
Script     3.4.1      AzureRM.Profile                     {Disable-AzureRmDataCollection, Disable-AzureRmContextAutosave, Enable-AzureRmDataCollection, Enable-AzureRmContextAutosave...}
```

if the older version of `AzureRM.Profile` is imported with any version of `AzureRM.Compute`,

```powershell
PS C:\> Get-Command Get-AzureRmContext,Get-AzureRmVM

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Get-AzureRmContext                                 3.4.1      AzureRM.Profile
Cmdlet          Get-AzureRmVM                                      4.0.0      AzureRM.Compute
```

trying to import _any_ version of `AzureRM.Compute` will result in the following error:

```powershell
PS C:\> Remove-Module AzureRM.Compute

PS C:\> Import-Module AzureRM.Compute -RequiredVersion 3.4.1
Import-Module : The following error occurred while loading the extended type data file: Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.Abstractions.IAzureContextContainer": The
TypeConverter was ignored because it already occurs.
Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.Abstractions.IAzureContextContainer": The member SerializationDepth is already present.
Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache": The member PropertySerializationSet is already present.
Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache": The member SerializationMethod is already present.
Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache": The member PropertySerializationSet is already present.
Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache": The member SerializationMethod is already present.
Error in TypeData "Microsoft.Azure.Commands.Profile.Models.PSAzureContext": The member SerializationDepth is already present.
Error in TypeData "Microsoft.Azure.Commands.Profile.Models.PSAzureProfile": The member SerializationDepth is already present.
At C:\Program Files\WindowsPowerShell\Modules\AzureRM.Compute\3.4.1\AzureRM.Compute.psm1:12 char:1
+ Import-Module AzureRM.Profile -MinimumVersion 3.4.1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], RuntimeException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
```

There needs to be a check added to see if the `TypeConverter` has been initialized in the current PowerShell session with the above extended types.

**Comment by markcowl** [comment] 2017-10-30 23:20
This is, unfortunately, by design, because the TypeData is included in a types.ps1xml file.  Because the typedata is automatically added on import, if it already exists this error is thrown.  If you remove the module, before importign the later version, thsi does not occur.

**Comment by gzaika** [comment] 2017-11-10 21:53
So, what to do if this is happened? How to remove all previous versions of the modules?

**Comment by cormacpayne** [comment] 2017-11-10 21:57
@gzaika please see our document troubleshooting module loading issues: https://aka.ms/azps-version-error

If you are still seeing the above error, would you mind providing the result of `Get-Module -ListAvailable` and pasting it as a separate comment in this thread?

**Comment by paylocity-sflanders** [comment] 2018-01-11 19:02
This problem still happens regardless of starting a new session or unloading the module.   It appears to happen consistently when i have AzureRM version 5.0.1 and 5.1.1 installed.   Basically you can no longer use 5.0.1 even in a new session with no other powershell instances running on the box.   In my case these are installed at the user level folders (C:\Users\user1\Documents\WindowsPowerShell\Modules).  In my case i have some of the sdk stuff installed so i have to use the -AllowClobber to install these modules successfully.

Steps
1.   kill all powershell.exe instances
2.   Manually delete all Azure* modules from admin/user level folders
3.   Install-Module AzureRM -RequiredVersion 5.0.1 -AllowClobber -Scope CurrentUser
4.   kill all powershell.exe instances
5.   Import-Module AzureRM -RequiredVersion 5.0.1  - WORKS
6.   kill all powershell.exe instances
7.   Install-Module AzureRM -RequiredVersion 5.1.1 -AllowClobber -Scope CurrentUser
8.   kill all powershell.exe instances
9.   Import-Module AzureRM -RequiredVersion 5.1.1  - WORKS
10. kill all powershell.exe instances
11. Import-Module AzureRM -RequiredVersion 5.0.1  - BREAKS with error above
12. kill all powershell.exe instances
13. Uninstall-Module AzureRM -RequiredVersion 5.1.1
14. kill all powershell.exe instances
15. Import-Module AzureRM -RequiredVersion 5.0.1  - BREAKS with error above

I did this process in reverse also and same issue happens.  Once you have both versions on the same box, the older version will no longer work even after uninstalling the newer version which makes be believe something is being overwritten somewhere.  This is super problematic since the whole point of powershell is being able to have multiple versions of modules installed at a time.

**Comment by markcowl** [comment] 2018-02-07 02:23
@gzaika @paylocity-sflanders Please provide the requested data - run Get-Module -ListAvailable and provide the module layout so we can see what the issue might be.

**Comment by paylocity-sflanders** [comment] 2018-02-11 01:54
@markcowl i ran my repo steps again and produced a debug log for each step.  Hopefully it will be helpful in resolving the issue
[Azure-Powershell-Issue-4835.txt](https://github.com/Azure/azure-powershell/files/1713962/Azure-Powershell-Issue-4835.txt)

**Comment by markcowl** [comment] 2018-02-12 01:39
@paylocity-sflanders In your initial setup, you have a very old version of AzureRM cmdlets installed from the Azure PowerShell msi before you install the latest version.  Side-by side installation is only supported for

(1) versions 4.x or greater
(2) both versions installed from the Gallery

Remove the msi-installed ckdlets before attemtpoing to install cmdlets from the gallery.

If you see another issue, please file a new issues, as this issue you have re-opened is unrelated to the issue you are reporting.

**Closed by markcowl** 2018-02-12 01:39 UTC
Labels: Azure PS Team, Investigate, More Info

**Comment by paylocity-sflanders** [comment] 2018-02-12 14:06
@markcowl 
to confirm are you saying the msi stuff can or can't be installed if using powershell modules from the gallery?   or are you just saying the msi version has to be greater than 4.x to work properly with the gallery based modules?
