### ISSUE TITLE
Document data on the Azure Powershell base classes.

### ISSUE THREAD

**Issue by vladimir-shcherbakov** [Azure/azure-powershell#8516] opened 2019-02-11 23:54 UTC
### Description

1. Create a document that describes the Azure PowerShell base classes for inheritance  and basic use cases to implement an Azure Powershell cmdlet;
2. Implement a base class for "offline cmdlets";

**Comment by cormacpayne** [comment] 2019-02-12 23:38
@MiYanni to clarify, the issue is that if a cmdlet inherits from `AzurePSCmdlet` (or `AzureRMCmdlet`, as most do), they are given a `-DefaultProfile` parameter, which allows users to provide a different context to run the cmdlet in. If the cmdlet should work offline (_e.g.,_ the cmdlet just creates an in-memory object), then ideally it wouldn't have this parameter, but since it more than likely inherits from a base class of `AzurePSCmdlet`, it will have this parameter. The idea is to have a separate base cmdlet that offline cmdlets can inherit from that avoid having these types of universal context parameters, but also allows us to send telemetry information that would usually be built into the `AzurePSCmdlet` class and it's subclasses.

**Comment by markcowl** [comment] 2019-03-25 21:34
Closing in favor of similar documentation for the generated cmdlets

**Closed by markcowl** 2019-03-25 21:34 UTC
Labels: Azure PS Team, Doc - Internal, Generator
