### ISSUE TITLE
New-AzStorageContainer : Method not found: 

### ISSUE THREAD

**Issue by Jackldam** [Azure/azure-powershell#17005] opened 2022-02-03 16:06 UTC
### Description

When creating new container in Powershell 5.1 using New-AzStorageContainer an error is thrown.

Command used
New-AzStorageContainer -Name "test"

### Issue script & Debug output

```PowerShell
DEBUG: 17:01:39 - Init Operation Context for 'NewAzureStorageContainerCommand' with client request id  Azure-Storage-PowerShell-b78ea1b0-. If you want to get more details, please add "-Debug" to your command.
DEBUG: 17:01:39 - NewAzureStorageContainerCommand begin processing with ParameterSet 'ContainerName'.
DEBUG: 17:01:39 - Get storage account from environment variable 'AZURE_STORAGE_CONNECTION_STRING'.

CancellationToken)'.
At line:1 char:1
+ New-AzStorageContainer -Name "test"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzStorageContainer], MissingMethodException
    + FullyQualifiedErrorId : MissingMethodException,Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.NewAzureStorageContainerCommand
 
DEBUG: 17:01:40 - NewAzureStorageContainerCommand end processing, Start 0 remote calls. Finish 0 remote calls. Elapsed time 202975,84 ms. Client operation id: Azure-Storage-PowerShell-b78ea1b0.
DEBUG: AzureQoSEvent: Module: Az.Storage:4.1.1; CommandName: New-AzStorageContainer; PSVersion: 5.1.19041.1320; IsSuccess: False; Duration: 00:00:00.0524008; Exception: Method not found: 'System.Threading.Tasks.ValueTask Azure.Core.Pipeline.HttpPipeline.SendAsync(Azure.Core.HttpMessage, System.Threading.CancellationToken)'.;
DEBUG: Finish sending metric.
DEBUG: 17:01:40 - NewAzureStorageContainerCommand end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.7.1      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount...}
Script     4.1.1      Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAccount...
```

### Error output

```PowerShell
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 5


Message        : Method not found: 'System.Threading.Tasks.ValueTask Azure.Core.Pipeline.HttpPipeline.SendAsync(Azure.Core.HttpMessage, System.Threading.Cancella 
                 tionToken)'.
StackTrace     :    at Azure.Storage.Blobs.ContainerRestClient.<CreateAsync>d__6.MoveNext()
                    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
                    at Azure.Storage.Blobs.ContainerRestClient.CreateAsync(Nullable`1 timeout, IDictionary`2 metadata, Nullable`1 access, String defaultEncryptio 
                 nScope, Nullable`1 preventEncryptionScopeOverride, CancellationToken cancellationToken)
                    at Azure.Storage.Blobs.BlobContainerClient.<CreateInternal>d__53.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Azure.Storage.Blobs.BlobContainerClient.<CreateIfNotExistsInternal>d__52.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Azure.Storage.Blobs.BlobContainerClient.<CreateIfNotExistsAsync>d__50.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.NewAzureStorageContainerCommand.<CreateAzureContainer>d__24.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.WindowsAzure.Commands.Storage.Common.LimitedConcurrencyTaskScheduler.<RunConcurrentTask>d__26.MoveNext()
Exception      : System.MissingMethodException
InvocationInfo : {New-AzStorageContainer}
Line           : New-AzStorageContainer -Name "test"
Position       : At line:6 char:1
                 + New-AzStorageContainer -Name "test"
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 5



   HistoryId: 4


Message        : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
StackTrace     :    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
                    at System.Reflection.Assembly.GetTypes()
                    at Microsoft.PowerShell.Commands.AddTypeCommand.LoadAssemblyFromPathOrName(List`1 generatedTypes)
                    at Microsoft.PowerShell.Commands.AddTypeCommand.EndProcessing()
                    at System.Management.Automation.CommandProcessorBase.Complete()
Exception      : System.Reflection.ReflectionTypeLoadException
InvocationInfo : {Add-Type}
Line           :                     Add-Type -Path $_.FullName -ErrorAction Ignore | Out-Null

Position       : At C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.7.1\Az.Accounts.psm1:39 char:21
                 + ...                Add-Type -Path $_.FullName -ErrorAction Ignore | Out-N ...
                 +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 4


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.
```

**Comment by blueww** [comment] 2022-02-07 02:16
@Jackldam
I can't repro this issue on my  machine with same Powershell version, same module version, and same command.
Following is my repro script:

```powershell
PS C:\> $env:AZURE_STORAGE_CONNECTION_STRING="AccountName=[hidden];AccountKey=[hidden]"

PS C:\> New-AzStorageContainer -Name "test"

   Storage Account Name: [hidden]

Name                 PublicAccess         LastModified                   IsDeleted  VersionId        
----                 ------------         ------------                   ---------  ---------        
test                 Off                  2/7/2022 2:12:06 AM +00:00                                 

PS C:\> Get-Module

ModuleType Version    Name                                ExportedCommands                                                                                                                                                                                                                                                               
---------- -------    ----                                ----------------                                                                                                                                                                                                                                                               
Script     2.7.1      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount...}                                                                                                                                                                                                    
Script     4.1.1      az.storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAccountNetworkRule, Close-AzStorageFileHandle...}                                                                                                                                 
Script     1.0.0.0    ISE                                 {Get-IseSnippet, Import-IseSnippet, New-IseSnippet}                                                                                                                                                                                                                            
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}                                                                                                                                                                                                             
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl, Get-AuthenticodeSignature...}                                                                                                                                                                                      
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}                                                                                                                                                                                                                      
Manifest   3.0.0.0    Microsoft.WSMan.Management          {Connect-WSMan, Disable-WSManCredSSP, Disconnect-WSMan, Enable-WSManCredSSP...}                                                                                                                                                                                             

PS C:\> $PSVersionTable

Name                           Value                                                                                                                                                                                                                                                                                                     
----                           -----                                                                                                                                                                                                                                                                                                     
PSVersion                      5.1.19041.1320                                                                                                                                                                                                                                                                                            
PSEdition                      Desktop                                                                                                                                                                                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                                                                                                                                   
BuildVersion                   10.0.19041.1320                                                                                                                                                                                                                                                                                           
CLRVersion                     4.0.30319.42000                                                                                                                                                                                                                                                                                           
WSManStackVersion              3.0                                                                                                                                                                                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                                                                                                                       
SerializationVersion           1.1.0.1     
```

Would you please:
1. Share more details about how you repro this issue? like the connection string you use (hide credentail), the full module list, OS version ...
2. As the missing method is in Azure.Core, would you please share the Azure.Core assembly information loaded in the Powershell session, with following command
```powershell
PS C:\> [appdomain]::currentdomain.getassemblies() | Where-Object {$_.location -like "*Azure.Core*"} |fl


CodeBase               : file:///C:/Program Files/WindowsPowerShell/Modules/Az.Accounts/2.7.1/PreloadAssemblies/Azure.Core.dll
EntryPoint             : 
EscapedCodeBase        : file:///C:/Program%20Files/WindowsPowerShell/Modules/Az.Accounts/2.7.1/PreloadAssemblies/Azure.Core.dll
FullName               : Azure.Core, Version=1.21.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8
GlobalAssemblyCache    : False
HostContext            : 0
ImageFileMachine       : 
ImageRuntimeVersion    : v4.0.30319
Location               : C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.7.1\PreloadAssemblies\Azure.Core.dll
ManifestModule         : Azure.Core.dll
MetadataToken          : 
PortableExecutableKind : 
ReflectionOnly         : False
```

**Comment by blueww** [comment] 2022-02-07 02:18
@dingmeng-xue 
It looks the error from customer is orginally from Az.Accounts.psm1, like following error from customer.
Would you please help to look?

```
Message        : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
StackTrace     :    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
                    at System.Reflection.Assembly.GetTypes()
                    at Microsoft.PowerShell.Commands.AddTypeCommand.LoadAssemblyFromPathOrName(List`1 generatedTypes)
                    at Microsoft.PowerShell.Commands.AddTypeCommand.EndProcessing()
                    at System.Management.Automation.CommandProcessorBase.Complete()
Exception      : System.Reflection.ReflectionTypeLoadException
InvocationInfo : {Add-Type}
Line           :                     Add-Type -Path $_.FullName -ErrorAction Ignore | Out-Null

Position       : At C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.7.1\Az.Accounts.psm1:39 char:21
                 + ...                Add-Type -Path $_.FullName -ErrorAction Ignore | Out-N ...
                 +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 4
```

**Comment by dingmeng-xue** [comment] 2022-02-07 14:42
I cannot reproduce this issue but I recollect there was an issue due to Azure.Core. Its dependency is changed and cannot work with old version of Az.Storage. Please try to use the latest version of Az.Storage 4.2.0

**Comment by Jackldam** [comment] 2022-02-09 14:53
@dingmeng-xue 
> I cannot reproduce this issue but I recollect there was an issue due to Azure.Core. Its dependency is changed and cannot work with old version of Az.Storage. Please try to use the latest version of Az.Storage 4.2.0

I have performed an module update but even with 4.20 i am getting this error.
```
Update-Module "AZ" -Force
```

**Comment by Jackldam** [comment] 2022-02-09 14:56
@blueww 
> ```powershell
> [appdomain]::currentdomain.getassemblies() | Where-Object {$_.location -like "*Azure.Core*"} |fl
> ```

as requested 

```
CodeBase               : file:///C:/Program Files/WindowsPowerShell/Modules/Az.Accounts/2.7.2/PreloadAssemblies/Azure.Core.dll
EntryPoint             :
EscapedCodeBase        : file:///C:/Program%20Files/WindowsPowerShell/Modules/Az.Accounts/2.7.2/PreloadAssemblies/Azure.Core.dll
FullName               : Azure.Core, Version=1.21.0.0, Culture=neutral, PublicKeyToken=<removed>
GlobalAssemblyCache    : False
HostContext            : 0
ImageFileMachine       : 
ImageRuntimeVersion    : v4.0.30319
Location               : C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.7.2\PreloadAssemblies\Azure.Core.dll
ManifestModule         : Azure.Core.dll
MetadataToken          :
PortableExecutableKind :
ReflectionOnly         : False
```

**Comment by blueww** [comment] 2022-02-10 03:32
@Jackldam 
 Would you please give the result of "Get-Module" after the issue repro?
And is the error detail is same as before.

@dingmeng-xue  Would you please help to look? Per the customer, has upgrade to Az.Storage 4.2.0 & Az.Account 2.7.2, but still meet the issue. And it looks the issue is from Az.Accounts.psm1.

**Comment by Jackldam** [comment] 2022-02-10 13:25
@dingmeng-xue  as requested my output below.

```
CodeBase               : file:///C:/Users/jackdenouden/.vscode/extensions/ms-vscode.powershell-2021.12.0/modules/PowerShellEditorServices/bin/Common/System.Threading.Tasks.Extensions.dll
EntryPoint             :
EscapedCodeBase        : file:///C:/Users/jackdenouden/.vscode/extensions/ms-vscode.powershell-2021.12.0/modules/PowerShellEditorServices/bin/Common/System.Threading.Tasks.Extensions.dll
FullName               : System.Threading.Tasks.Extensions, Version=4.2.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
GlobalAssemblyCache    : False
HostContext            : 0
ImageFileMachine       :
ImageRuntimeVersion    : v4.0.30319
Location               : C:\Users\jackdenouden\.vscode\extensions\ms-vscode.powershell-2021.12.0\modules\PowerShellEditorServices\bin\Common\System.Threading.Tasks.Extensions.dll
ManifestModule         : System.Threading.Tasks.Extensions.dll
MetadataToken          :
PortableExecutableKind :
ReflectionOnly         : False

CodeBase               : file:///C:/Program Files/WindowsPowerShell/Modules/Az.Accounts/2.7.2/PreloadAssemblies/System.Threading.Tasks.Extensions.DLL
EntryPoint             :
EscapedCodeBase        : file:///C:/Program%20Files/WindowsPowerShell/Modules/Az.Accounts/2.7.2/PreloadAssemblies/System.Threading.Tasks.Extensions.DLL
FullName               : System.Threading.Tasks.Extensions, Version=4.2.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
GlobalAssemblyCache    : False
HostContext            : 0
ImageFileMachine       : 
ImageRuntimeVersion    : v4.0.30319
Location               : C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.7.2\PreloadAssemblies\System.Threading.Tasks.Extensions.dll
ManifestModule         : System.Threading.Tasks.Extensions.dll
MetadataToken          :
PortableExecutableKind :
ReflectionOnly         : False




ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.7.2      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount...}
Script     4.2.0      Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAccountNetworkRule, Close-AzStorageFileHandle...}
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl, Get-AuthenticodeSignature...}
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Manifest   3.0.0.0    Microsoft.WSMan.Management          {Connect-WSMan, Disable-WSManCredSSP, Disconnect-WSMan, Enable-WSManCredSSP...}
Script     0.2.0      PowerShellEditorServices.Commands   {Clear-Host, ConvertFrom-ScriptExtent, ConvertTo-ScriptExtent, Find-Ast...}
Binary     0.2.0      PowerShellEditorServices.VSCode     {Close-VSCodeHtmlContentView, New-VSCodeHtmlContentView, Set-VSCodeHtmlContentView, Show-VSCodeHtmlContentView...}
Script     2.1.0      PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler, Set-PSReadLineKeyHandler...}
```

**Comment by satsuk81** [comment] 2022-03-02 13:30
I have the same issue and can confirm that the issue only exists when using VS Code.

**Comment by ojintoad** [comment] 2022-03-08 12:24
Confused because from what I can tell they are the same version based on dll metadata?

The "original" is what's included with vscode.
The "azaccounts273" is what's included with a module install.

![image](https://user-images.githubusercontent.com/3084796/157237468-253defcf-1430-45a5-991b-c92894aa28f6.png)

**Comment by ojintoad** [comment] 2022-06-17 17:09
I hit this again and remembered. What is the expectation here of who will change their code to fix this? Is this waiting on VSCode to make a change or on PowerShell AZ?

**Comment by blueww** [comment] 2022-06-20 03:11
@dingmeng-xue 
Would you please help to look at this assembly load issue?

@ojintoad 
I just test on VS code 1.67.1 ([release on Apr, 2022](https://code.visualstudio.com/updates/v1_67) )
New-AzStorageContainer runs successfully.

following is the Az.* module load on my machine (by "get-module" after run New-AzStoragecontainer)
```
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.8.0                 Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     4.6.0                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAccountNetworkRule, Close-AzStorageFileHandle…}  
```

**Comment by ojintoad** [comment] 2022-06-20 15:20
@blueww will try when back at work, thanks for responding

**Comment by dingmeng-xue** [comment] 2022-06-22 02:21
@ojintoad , integrated console in vs code can be configured by user. Please check which version you are using.

**Comment by blueww** [comment] 2022-08-04 02:47
@ojintoad

I will close this issue as not see your responds for a long time.
Feel free to contact us again if you need any further assistance on Azure Powershell.

**Closed** 2022-08-04 02:47 UTC
Labels: Storage, Service Attention, bug, question, customer-reported, needs-team-attention
