### ISSUE TITLE
Get-AzDataLakeStoreItemAclEntry errors out

### ISSUE THREAD

**Issue by abhaydaga** [Azure/azure-powershell#8931] opened 2019-04-03 12:36 UTC
## Description

Get-AzDataLakeStoreItemAclEntry cmd errors out.

## Steps to reproduce

```powershell
Get-AzDataLakeStoreItemAclEntry -Account 'adlforarm2adls' -Path "/" -ErrorAction Stop
```

## Environment data

```
Name                           Value                                                                                      
----                           -----                                                                                      
PSVersion                      5.1.17763.316                                                                              
PSEdition                      Desktop                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                    
BuildVersion                   10.0.17763.316                                                                             
CLRVersion                     4.0.30319.42000                                                                            
WSManStackVersion              3.0                                                                                        
PSRemotingProtocolVersion      2.3                                                                                        
SerializationVersion           1.1.0.1            
```

## Module versions

```powershell
ModuleType Version    Name                                ExportedCommands                                                
---------- -------    ----                                ----------------                                                
Script     1.2.1      Az.Accounts                         {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-...
Script     1.0.0      Az.AnalysisServices                 {Resume-AzAnalysisServicesServer, Suspend-AzAnalysisServicesS...
Script     1.0.0      Az.ApiManagement                    {Add-AzApiManagementRegion, Get-AzApiManagementSsoToken, New-...
Script     1.0.0      Az.ApplicationInsights              {Get-AzApplicationInsights, New-AzApplicationInsights, Remove...
Script     1.0.0      Az.Automation                       {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHybrid...
Script     1.0.0      Az.Batch                            {Remove-AzBatchAccount, Get-AzBatchAccount, Get-AzBatchAccoun...
Script     1.0.0      Az.Cdn                              {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-AzCdnProfile, ...
Script     1.1.0      Az.Compute                          {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAvail...
Script     1.0.0      Az.ContainerInstance                {New-AzContainerGroup, Get-AzContainerGroup, Remove-AzContain...
Script     1.0.0      Az.ContainerRegistry                {New-AzContainerRegistry, Get-AzContainerRegistry, Update-AzC...
Script     1.0.0      Az.DataFactory                      {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get-AzDataFacto...
Script     1.0.0      Az.DataLakeAnalytics                {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeAnalyticsCa...
Script     1.0.1      Az.DataLakeStore                    {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStore...
Script     1.0.0      Az.EventHub                         {New-AzEventHubNamespace, Get-AzEventHubNamespace, Set-AzEven...
Script     1.0.0      Az.HDInsight                        {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefinition, Wait-...
Script     1.0.0      Az.KeyVault                         {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertificate, Sto...
Script     1.1.0      Az.LogicApp                         {Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccountC...
Script     1.0.0      Az.Monitor                          {Get-AzMetricDefinition, Get-AzMetric, Remove-AzLogProfile, G...
Script     1.0.0      Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Get-AzApp...
Script     1.0.0      Az.NotificationHubs                 {Get-AzNotificationHub, Get-AzNotificationHubAuthorizationRul...
Script     1.0.0      Az.OperationalInsights              {New-AzOperationalInsightsAzureActivityLogDataSource, New-AzO...
Script     1.0.0      Az.PolicyInsights                   {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPolicyStateSumma...
Script     1.0.0      Az.RedisCache                       {Remove-AzRedisCachePatchSchedule, New-AzRedisCacheScheduleEn...
Script     1.1.0      Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRole...
Script     1.0.0      Az.ServiceBus                       {New-AzServiceBusNamespace, Get-AzServiceBusNamespace, Set-Az...
Script     1.0.0      Az.ServiceFabric                    {Add-AzServiceFabricApplicationCertificate, Add-AzServiceFabr...
Script     1.0.1      Az.Sql                              {Get-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabas...
Script     1.0.1      Az.Storage                          {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStorage...
Script     1.0.0      Az.StreamAnalytics                  {Get-AzStreamAnalyticsFunction, Get-AzStreamAnalyticsDefaultF...
Script     1.0.0      Az.TrafficManager                   {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove-AzTraffic...
Script     1.0.1      Az.Websites                         {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppService...
```

## Debug output

```
DEBUG: 6:03:08 PM - GetAzureDataLakeStoreItemAclEntry begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 6:03:08 PM - using account id 'xxxxx@yyyyyyyyy.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'xxxxx@yyyyyyyyy.com', environment: 'AzureCloud', tenant: '72f988bf-86f1-41af-91ab-2d7cd011db47'
DEBUG: 2019-04-03 18:03:09.1397|DEBUG|adls.dotnet.WebTransport|HTTPRequest,failed,cReqId:f93f67a1-3350-4270-8d8d-dd582cf82252.0,lat:47,err:The 'User-Agent' header must be modified using the
 appropriate property or method.
Parameter name: name,Reqlen:0,Resplen:0,token_ns:6,sReqId:,path:/,qp:op=GETACLSTATUS&tooid=True&api-version=2018-08-01
DEBUG: 2019-04-03 18:03:10.1591|DEBUG|adls.dotnet.WebTransport|HTTPRequest,failed,cReqId:f93f67a1-3350-4270-8d8d-dd582cf82252.1,lat:3,err:The 'User-Agent' header must be modified using the 
appropriate property or method.
Parameter name: name,Reqlen:0,Resplen:0,token_ns:2,sReqId:,path:/,qp:op=GETACLSTATUS&tooid=True&api-version=2018-08-01
DEBUG: 2019-04-03 18:03:14.1716|DEBUG|adls.dotnet.WebTransport|HTTPRequest,failed,cReqId:f93f67a1-3350-4270-8d8d-dd582cf82252.2,lat:14,err:The 'User-Agent' header must be modified using the
 appropriate property or method.
Parameter name: name,Reqlen:0,Resplen:0,token_ns:14,sReqId:,path:/,qp:op=GETACLSTATUS&tooid=True&api-version=2018-08-01
DEBUG: 2019-04-03 18:03:30.2021|DEBUG|adls.dotnet.WebTransport|HTTPRequest,failed,cReqId:f93f67a1-3350-4270-8d8d-dd582cf82252.3,lat:8,err:The 'User-Agent' header must be modified using the 
appropriate property or method.
Parameter name: name,Reqlen:0,Resplen:0,token_ns:7,sReqId:,path:/,qp:op=GETACLSTATUS&tooid=True&api-version=2018-08-01
DEBUG: 2019-04-03 18:04:34.2161|DEBUG|adls.dotnet.WebTransport|HTTPRequest,failed,cReqId:f93f67a1-3350-4270-8d8d-dd582cf82252.4,lat:2,err:The 'User-Agent' header must be modified using the 
appropriate property or method.
Parameter name: name,Reqlen:0,Resplen:0,token_ns:2,sReqId:,path:/,qp:op=GETACLSTATUS&tooid=True&api-version=2018-08-01
Get-AzDataLakeStoreItemAclEntry : Error in getting ACL entries for path /.
Operation: GETACLSTATUS failed with   Unknown Error: The 'User-Agent' header must be modified using the appropriate property or method.
Parameter name: name Source: System StackTrace:    at System.Net.WebHeaderCollection.ThrowOnRestrictedHeader(String headerName)
   at System.Net.WebHeaderCollection.Set(String name, String value)
   at Microsoft.Azure.DataLake.Store.WebTransport.AssignCommonHttpHeaders(HttpWebRequest webReq, AdlsClient client, RequestOptions req, String token, String opMethod, IDictionary`2 
customHeaders, Int32 postRequestLength)
   at Microsoft.Azure.DataLake.Store.WebTransport.<MakeSingleCallAsync>d__22.MoveNext().
Last encountered exception thrown after 5 tries. [The 'User-Agent' header must be modified using the appropriate property or method.
Parameter name: name,The 'User-Agent' header must be modified using the appropriate property or method.
Parameter name: name,The 'User-Agent' header must be modified using the appropriate property or method.
Parameter name: name,The 'User-Agent' header must be modified using the appropriate property or method.
Parameter name: name,The 'User-Agent' header must be modified using the appropriate property or method.
Parameter name: name]
[ServerRequestId:]
At line:1 char:1
+ Get-AzDataLakeStoreItemAclEntry -Account 'adlforarm2adls' -Path "/" - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzDataLakeStoreItemAclEntry], AdlsException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.DataLakeStore.GetAzureDataLakeStoreItemAclEntry
 
```

## Error output

```
Get-AzDataLakeStoreItemAclEntry : Error in getting ACL entries for path /.
Operation: GETACLSTATUS failed with   Unknown Error: The 'User-Agent' header must be modified using the appropriate 
property or method.
Parameter name: name Source: System StackTrace:    at System.Net.WebHeaderCollection.ThrowOnRestrictedHeader(String 
headerName)
   at System.Net.WebHeaderCollection.Set(String name, String value)
   at Microsoft.Azure.DataLake.Store.WebTransport.AssignCommonHttpHeaders(HttpWebRequest webReq, AdlsClient client, 
RequestOptions req, String token, String opMethod, IDictionary`2 customHeaders, Int32 postRequestLength)
   at Microsoft.Azure.DataLake.Store.WebTransport.<MakeSingleCallAsync>d__22.MoveNext().
Last encountered exception thrown after 5 tries. [The 'User-Agent' header must be modified using the appropriate property 
or method.
Parameter name: name,The 'User-Agent' header must be modified using the appropriate property or method.
Parameter name: name,The 'User-Agent' header must be modified using the appropriate property or method.
Parameter name: name,The 'User-Agent' header must be modified using the appropriate property or method.
Parameter name: name,The 'User-Agent' header must be modified using the appropriate property or method.
Parameter name: name]
[ServerRequestId:]
At line:1 char:1
+ Get-AzDataLakeStoreItemAclEntry -Account 'adlforarm2adls' -Path "/" - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzDataLakeStoreItemAclEntry], AdlsException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.DataLakeStore.GetAzureDataLakeStoreItemAclEntry
```

**Comment by cormacpayne** [comment] 2019-04-03 15:40
@abhaydaga Hey Abhay, I believe this is a duplicate of issue https://github.com/Azure/azure-powershell/issues/8352 -- @rahuldutta90 would you mind confirming this is a duplicate?

**Comment by rahuldutta90** [comment] 2019-04-03 16:14
@cormacpayne  this is a duplicate. @abhaydaga we are trying to resolve the issue. Till then can you please run these on net core?

**Closed** 2019-04-03 16:21 UTC
Labels: Data Lake Store, Service Attention
