### ISSUE TITLE
Sql folder path name causing warnings when Azure and SqlPs modules installed

### ISSUE THREAD

**Issue by Matticusau** [Azure/azure-powershell#555] opened 2015-06-30 04:07 UTC
When you have both the Azure and SqlPs modules installed and try and import the SqlPs module, a number of warnings are displayed due to WMI connection failures. This is a result of the SqlPs provider path (SQLSERVER:) taking the path of \SQL to be a SQL Server instance to connect to. When you load the SqlPs module it also tries to run a Get-Module -ListAvailable which causes the Azure module to process Get-Item on it's types etc which happen to be stored in a path such as '.\Sql\Microsoft.WindowsAzure.Commands.SqlDatabase.Types.ps1xml'. This results in the SQL provider trying to connect to that file as though it is a SQL Server.
While this behavior really lives inside the SqlPs module, I believe the easiest thing to do would be to change the folder structure in the Azure modules.

The following also relate:

http://blog.matticus.net/2014/11/importing-sqlps-module-results-in.html

https://connect.microsoft.com/SQLServer/feedback/details/1420992/import-module-sqlps-may-take-longer-to-load-but-always-returns-warnings-when-the-azure-powershell-module-is-also-installed#

**Comment by markcowl** [comment] 2015-06-30 16:42
@Matticusau Thanks for reporting this.  Assigning to the Sql team for investigation.  I *think* that you should file this issue with the SqlPS cmdlets, however, as the assumption they are making about the directory path seems like an unsafe assumption.

**Comment by djohnst10** [comment] 2015-11-17 22:40
I've had this issue as well.

I agree that this is primarily something caused by the way the SQLPS provider handles things when loading itself or when Get-Module -ListAvailable is called when the drive is SQLSERVER:. 

Despite that I discovered that the way the Azure\Azure.psd1 manifest specifies TypesToProcess, FormatsToProcess, and NestedModules, is part of the problem and is something that can be easily fixed without changing the names or layout of directories in the Azure module.

For each of the TypesToProcess, FormatsToProcess, and NestedModules properties, the path is specified starting with '.\' like so:

```PowerShell
TypesToProcess = @(
    '.\Services\Microsoft.WindowsAzure.Commands.Websites.Types.ps1xml',
    '.\Sql\Microsoft.WindowsAzure.Commands.SqlDatabase.Types.ps1xml'
    '.\Storage\Microsoft.WindowsAzure.Commands.Storage.Types.ps1xml',
    '.\StorSimple\Microsoft.WindowsAzure.Commands.StorSimple.Types.ps1xml'
)
```

This is unnecessary since PowerShell looks for the dependent files starting in the same directory as the manifest.

Not only is it unnecessary, I found that when I removed the '.\' characters, I no longer got the errors described by @Matticusau.

I did a lot more research on this issue and can provide more details if desired.

**Closed** 2017-06-09 19:24 UTC
Labels: Sql
