### ISSUE TITLE
Get-AzureRmStorageAccountKey always returns "A task was canceled"

### ISSUE THREAD

**Issue by julioct** [Azure/azure-powershell#3637] opened 2017-03-15 22:45 UTC
### Cmdlet(s)
Get-AzureRmStorageAccountKey

### PowerShell Version
5.1.14393.693

### OS Version
10.0.14393.693

### Description
Calling Get-AzureRmStorageAccountKey -StorageAccountName <storageaccountname> -ResourceGroupName <resourcegroupname> consistently returns this error:

Get-AzureRmStorageAccountKey : A task was canceled.

### Debug Output
DEBUG: 3:41:48 PM - GetAzureStorageAccountKeyCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 3:41:48 PM - using account id 'myaccount@microsoft.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'myaccount@microsoft.com', environment: 'AzureCloud',
tenant: '72f988bf-86f1-41af-91ab-2d7cd011db47'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 03/15/2017 22:41:48:  - TokenCache: Deserialized 1 items to token cache.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 03/15/2017 22:41:48: 85e98a57-adfd-4fd6-b723-e5715c84a4aa - AcquireTokenHandlerBase: === Token Acquisition
started:
 Authority: https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache (1 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 03/15/2017 22:41:48: 85e98a57-adfd-4fd6-b723-e5715c84a4aa - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 03/15/2017 22:41:48: 85e98a57-adfd-4fd6-b723-e5715c84a4aa - TokenCache: An item matching the requested resource
was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 03/15/2017 22:41:48: 85e98a57-adfd-4fd6-b723-e5715c84a4aa - TokenCache: 51.309137235 minutes left until token in
 cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 03/15/2017 22:41:48: 85e98a57-adfd-4fd6-b723-e5715c84a4aa - TokenCache: A matching item (access token or refresh
 token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 03/15/2017 22:41:48: 85e98a57-adfd-4fd6-b723-e5715c84a4aa - AcquireTokenHandlerBase: === Token Acquisition
finished successfully. An access token was retuned:
 Access Token Hash: N4P+NBvlO7Yu+xDfBnapsU/keTuRNJ96T8tKr0Du8pk=
 Refresh Token Hash: hmB66h+gzi+TccBetj6bWbgKI5IB42txkO9WAGZ9WVs=
 Expiration Time: 03/15/2017 23:33:06 +00:00
 User Hash: FqbwsT1q7xlVA4T0Ewa70KkhcqrU93DemL/BG+9GNNU=

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 03/15/2017 22:41:48:  - TokenCache: Serializing token cache with 1 items.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 03/15/2017 22:41:48: 2e312842-f77c-429a-852a-0e5bfba588a9 - AcquireTokenHandlerBase: === Token Acquisition
started:
 Authority: https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache (1 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 03/15/2017 22:41:48: 2e312842-f77c-429a-852a-0e5bfba588a9 - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 03/15/2017 22:41:48: 2e312842-f77c-429a-852a-0e5bfba588a9 - TokenCache: An item matching the requested resource
was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 03/15/2017 22:41:48: 2e312842-f77c-429a-852a-0e5bfba588a9 - TokenCache: 51.309137235 minutes left until token in
 cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 03/15/2017 22:41:48: 2e312842-f77c-429a-852a-0e5bfba588a9 - TokenCache: A matching item (access token or refresh
 token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 03/15/2017 22:41:48: 2e312842-f77c-429a-852a-0e5bfba588a9 - AcquireTokenHandlerBase: === Token Acquisition
finished successfully. An access token was retuned:
 Access Token Hash: N4P+NBvlO7Yu+xDfBnapsU/keTuRNJ96T8tKr0Du8pk=
 Refresh Token Hash: hmB66h+gzi+TccBetj6bWbgKI5IB42txkO9WAGZ9WVs=
 Expiration Time: 03/15/2017 23:33:06 +00:00
 User Hash: FqbwsT1q7xlVA4T0Ewa70KkhcqrU93DemL/BG+9GNNU=

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://management.azure.com/subscriptions/1e7868be-c936-4612-b3a0-6e4c90934e45/resourceGroups/powerappsci/providers/Mi
crosoft.Storage/storageAccounts/powerappsengsys/listKeys?api-version=2016-12-01

Headers:
x-ms-client-request-id        : e191b247-2186-4fce-a9df-254a732bcb25
accept-language               : en-US

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadGateway

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : service
x-ms-request-id               : d11e8738-20a4-4256-be58-d2224f6398ed
x-ms-correlation-request-id   : d11e8738-20a4-4256-be58-d2224f6398ed
x-ms-routing-request-id       : WESTUS2:20170315T224308Z:d11e8738-20a4-4256-be58-d2224f6398ed
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Connection                    : close
Cache-Control                 : no-cache
Date                          : Wed, 15 Mar 2017 22:43:08 GMT

Body:
{
  "error": {
    "code": "BadGatewayConnection",
    "message": "The network connectivity issue encountered for 'Microsoft.Storage'; cannot fulfill the request."
  }
}

Get-AzureRmStorageAccountKey : The network connectivity issue encountered for 'Microsoft.Storage'; cannot fulfill the
request.
At line:1 char:1
+ Get-AzureRmStorageAccountKey -StorageAccountName powerappsengsys -Res ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmStorageAccountKey], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Management.Storage.GetAzureStorageAccountKeyCommand

DEBUG: AzureQoSEvent: CommandName - Get-AzureRmStorageAccountKey; IsSuccess - False; Duration - 00:01:20.9064171;
Exception - Microsoft.Rest.Azure.CloudException: The network connectivity issue encountered for 'Microsoft.Storage';
cannot fulfill the request.
   at Microsoft.Azure.Management.Storage.StorageAccountsOperations.<ListKeysWithHttpMessagesAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Storage.StorageAccountsOperationsExtensions.<ListKeysAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Storage.StorageAccountsOperationsExtensions.ListKeys(IStorageAccountsOperations
operations, String resourceGroupName, String accountName)
   at Microsoft.Azure.Commands.Management.Storage.GetAzureStorageAccountKeyCommand.ExecuteCmdlet() in
D:\workspace\powershell-sign\src\ResourceManager\Storage\Commands.Management.Storage\StorageAccount\GetAzureStorageAcco
untKey.cs:line 43
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord() in
D:\workspace\powershell-sign\src\Common\Commands.Common\AzurePSCmdlet.cs:line 642;
DEBUG: Finish sending metric.
DEBUG: 3:43:10 PM - GetAzureStorageAccountKeyCommand end processing.
DEBUG: 3:43:10 PM - GetAzureStorageAccountKeyCommand end processing.

### Script/Steps for Reproduction
Just invoke the cmdlet like this and it will repro:
Get-AzureRmStorageAccountKey -StorageAccountName thesa -ResourceGroupName therg

**Comment by cormacpayne** [comment] 2017-03-15 23:06
@blueww Hey Wei, would you mind taking a look at this issue?

**Comment by blueww** [comment] 2017-03-16 03:03
@julioct :
This issue can't repro with my own account. 

I tried to search the server log with the following request id and time in the debug information, but find nothing. (For my own request I can search out on server.)

- x-ms-request-id : d11e8738-20a4-4256-be58-d2224f6398ed
-  Date : Wed, 15 Mar 2017 22:43:08 GMT

The error message is "BadGateway". It seems there are some network issue with your network. Could you share more information : 

- Which region is your account in? 
- Can you run other cmdelts successfully in same enviroment (e.g. Get-AzureRmStorageAccount) ?
- The repro storage Account name if can share

**Comment by julioct** [comment] 2017-03-16 16:25
It looks like this was related to the recent Azure Storage outage that was resolved a few hours ago. Get-AzureRmStorageAccountKey is now working properly for me. It would be great to present a more meaningful message when this happens as opposed to **A task was canceled**, which is very confusing.

**Comment by blueww** [comment] 2017-03-17 02:58
@julioct 

Thanks for the update! It's good to know the issue is resolved.

I agree the error is not easy to understand. But PowerShell itself can't determine why the error happen, and will just report the error from Server or Client library directly.
Thanks for your understanding!

**Comment by blueww** [comment] 2017-03-17 02:59
@cormacpayne 
Could you help to close the issue and it's already resolved?
Thanks!

**Closed** 2017-03-17 04:10 UTC
Labels: Storage
