### ISSUE TITLE
Az.Blueprint is missing Cmdlet to remove Blueprint Definition Versions

### ISSUE THREAD

**Issue by russellds** [Azure/azure-powershell#9547] opened 2019-07-03 02:34 UTC
## Description of the new feature

Please add a cmdlet to Az.Blueprint to enable removing Blueprint Definition versions. Currently, you are only able to do that via the Azure Portal.

**Comment by markcowl** [comment] 2019-07-08 21:35
@filizt can you take a look?

**Comment by filizt** [comment] 2019-07-10 17:03
@alex-frankel FYI.

**Comment by filizt** [comment] 2019-07-11 20:04
@russellds we have added this as a feature request to our board. It has missed the cut off for the Blueprint module update coming in next week. That being said, it should be in the release after that.

**Comment by akshaykg** [comment] 2019-11-22 18:08
Hey Filizt, the feature still seems to be missing. if this is already done can you kindly share details and close this thread if not can you share any timelines for the fix?

**Comment by filizt** [comment] 2019-11-22 19:12
Unfortunately, this feature has been cut for the time. Please use Portal or the direct API call to delete blueprint versions.

**Comment by russellds2w** [comment] 2019-11-24 05:56
I understand that the feature has been cut for the time being, but why did you close the issue? The issue is still valid and will hopefully be addressed in the future.

**Comment by filizt** [comment] 2019-11-25 03:21
> I understand that the feature has been cut for the time being, but why did you close the issue? The issue is still valid and will hopefully be addressed in the future.

Apologies for closing the issue. Reopened it.

**Comment by stefanstranger** [comment] 2019-12-17 15:24
I create a gist on how to remove an Azure Blueprint Definition using the REST API in PowerShell. Check https://gist.github.com/stefanstranger/822e45ca6d815422dd0b756d9c71ec32

HTH
Stefan

**Comment by andrenelnz** [comment] 2020-01-13 21:39
@filizt can we please review and have the Az.Blueprint Cmdlet to remove Blueprint Definition versions added back to the backlog? Really need this feature as we running Cloud as code only so no portal modify access. Thanks

**Comment by alex-frankel** [comment] 2020-01-14 15:56
Understand the frustration here. It's not ideal, but you can use the [Remove-AzResource](https://docs.microsoft.com/powershell/module/az.resources/remove-azresource?view=azps-3.3.0) cmdlet. You can pass that cmdlet the resourceId of the blueprint version.

We can keep the issue open.

**Comment by borgewi** [comment] 2020-05-18 15:09
> Understand the frustration here. It's not ideal, but you can use the [Remove-AzResource](https://docs.microsoft.com/powershell/module/az.resources/remove-azresource?view=azps-3.3.0) cmdlet. You can pass that cmdlet the resourceId of the blueprint version.
> 
> We can keep the issue open.

@alex-frankel Thanks for an anternative way of removing the blueprint definition. However when I use the Remove-AzResource cmdlet it still leaves the blueprint definition in draft state. How do you entirely remove the blueprint definition?

Will this be added to the Az.Blueprints Cmdlets soon?

**Comment by alex-frankel** [comment] 2020-05-18 15:15
A [blueprint version](https://docs.microsoft.com/rest/api/blueprints/publishedblueprints/create) is a child resource of a [blueprint definition](https://docs.microsoft.com/rest/api/blueprints/blueprints/createorupdate) (which represents the latest "draft"). When you create a new version, you are taking a snapshot of the master/draft.

So to remove the draft, you must delete the blueprint definition which will implicitly delete all children/versions

**Comment by apclouds** [comment] 2020-09-21 16:02
Hello @borgewi, @russellds I wanted to up on this issue. Was the Remove-AzResource workaround enough to meet your scenario?

**Comment by CharbelHanna** [comment] 2020-11-03 22:46
Hello,
we still did not get an update on this, the az.blueprint module is still missing the ability to remove a blueprint definition, anything planned for the future?

**Comment by alex-frankel** [comment] 2020-11-17 22:10
Unfortunately, there are no plans to add the `Remove-AzBlueprint*` cmdlets given the upcoming plans to move Blueprint Definitions to Template Specs.

**Closed by alex-frankel** 2020-11-17 22:10 UTC
Labels: Blueprint, Service Attention, feature-request

**Comment by fluffy-cakes** [comment] 2021-06-03 16:45
For those who have Web-Searched this:

```
Remove-AzResource `
            -ResourceId "/providers/Microsoft.Management/managementGroups/${{ parameters.mgmtGroupId }}/providers/Microsoft.Blueprint/blueprints/${{ parameters.blueprintDefinitionName }}" `
            -Force
```
