### ISSUE TITLE
New-AzVM failing with VMCustomization' is not enabled for the Subscription.

### ISSUE THREAD

**Issue by zapadoody** [Azure/azure-powershell#17370] opened 2022-03-04 19:53 UTC
### Description

We are running into an issue where the New-AzVm powershell cmdlet has stopped working. This was working a week ago without any issues, however we tried to run this today and are getting the following response:

Following this basic this example produces the issue:

New-AzVM: 'VMCustomization' is not enabled for the Subscription. Please register the Subscription for 'Microsoft.Compute/VMCustomizationPreview' to use the feature.

[example-1--create-a-virtual-machine](https://docs.microsoft.com/en-us/powershell/module/az.compute/new-azvm?view=azps-7.3.0#example-1--create-a-virtual-machine)

Anybody else seeing this?

### Issue script & Debug output

```PowerShell
PS > New-AzVm -ResourceGroupName 'thisrg' -Name 'thisvm' -Location 'westus'

cmdlet New-AzVM at command pipeline position 1
Supply values for the following parameters:
Credential
User: thisuser
Password for user thisuser: blah

No Size value has been provided. The VM will be created with the default size Standard_D2s_v3.
New-AzVM: 'VMCustomization' is not enabled for the Subscription. Please register the Subscription for 'Microsoft.Compute/VMCustomizationPreview' to use the feature.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.7.3                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     4.24.0                Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent, Add-AzVMDataDisk…}
Script     5.4.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
```

**Comment by davmhelm** [comment] 2022-03-04 20:19
Seeing this in Azure Cloud Shell as well for Az.Compute module version 4.24.0. 

Seems to be working fine in module version 4.23.0, which I forcefully loaded to test using these commands:

```powershell
# This downloads the working version of the module into your cloud shell session
Install-Module -Name Az.Compute -Force -RequiredVersion 4.23.0 

# this starts a new PowerShell session that will allow the Az.Compute assembly version to be loaded
pwsh 

# you should now see version 4.23.0 as loaded
Get-Module -Name Az.Compute 

# Run your New-AzVM command as normal

# to return your cloud shell to the previous state running the latest version of Az.* modules, run these commands
# otherwise new instances of cloud shell will continue to use the older version of the module you manually installed
Uninstall-Module -Name Az.Compute -Force -RequiredVersion 4.23.0
exit
```

**Comment by Naveenn12** [comment] 2022-03-05 12:33
I got into similar issue, there seems to be some issue with powershell 7.2.1 version, I have installed PowerShell 7.3.0-preview.2 to fix the error.

**Comment by IsmaelJCarlo** [comment] 2022-03-05 22:37
This is also happening in the Microsoft Learn environment sandbox which is running PowerShell 7.2.1.

**Comment by dingmeng-xue** [comment] 2022-03-06 13:42
Compute team,

I can see reproduce this issue. I believe there is problem on new API version.

```
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/9e223dbe-3399-4e19-88eb-0975f02ac87f/resourceGroups/thisrg/providers/Microsoft.Compute/virtualMachines/thisvm?api-version=2021-11-01

Headers:
x-ms-client-request-id        : 640453d1-d4e5-4fe7-9424-c3745d90ca30
Accept-Language               : en-US

Body:
{
  "properties": {
    "hardwareProfile": {
      "vmSize": "Standard_D2s_v3",
      "vmSizeProperties": {}
    },
    "storageProfile": {
      "imageReference": {
        "publisher": "MicrosoftWindowsServer",
        "offer": "WindowsServer",
        "sku": "2016-Datacenter",
        "version": "latest"
      }
    },
    "additionalCapabilities": {},
    "osProfile": {
      "computerName": "thisvm",
      "adminUsername": "dixue",
      "adminPassword": "dixue",
      "windowsConfiguration": {}
    },
    "networkProfile": {
      "networkInterfaces": [
        {
          "id": "/subscriptions/9e223dbe-3399-4e19-88eb-0975f02ac87f/resourceGroups/thisrg/providers/Microsoft.Network/networkInterfaces/thisvm"
        }
      ]
    }
  },
  "location": "westus2"
}
```
Besides API version is changed, it contains an empty property vmSizeProperties in the latest version. Please look into it with priority.

**Comment by lowestbassnote** [comment] 2022-03-06 14:40
> This is also happening in the Microsoft Learn environment sandbox which is running PowerShell 7.2.1.

Yes - I have this same problem running in the sandbox when trying out https://docs.microsoft.com/en-us/learn/modules/automate-azure-tasks-with-powershell/6-exercise-create-resource-interactively

**Comment by aespinoza96** [comment] 2022-03-06 21:13
I tried to install the previous version mentioned above (4.23.0) but still having the same issue in sandbox when creating a new VM. Please address this issue since it is causing problems to learn about Azure

**Comment by dingmeng-xue** [comment] 2022-03-07 01:41
> I tried to install the previous version mentioned above (4.23.0) but still having the same issue in sandbox when creating a new VM. Please address this issue since it is causing problems to learn about Azure

You need to restart process of PowerShell and import module with specified version. Or, you have to remove 4.24.0 from your machine and restart PowerShell then.
```
Import-Module Az.Compute -RequiredVersion 4.23.0
```

**Comment by dingmeng-xue** [comment] 2022-03-12 09:49
This issue is fixed by the latest Az.Compute. Please use it. https://www.powershellgallery.com/packages/Az.Compute/4.24.1

**Closed** 2022-03-12 09:49 UTC
Labels: Compute - VM, Service Attention, bug, customer-reported, P0

**Comment by Bardski** [comment] 2022-03-13 23:47
Sorry DingMeng-Xue,
I had the issue today in MS Learn: https://docs.microsoft.com/en-us/learn/modules/extend-share-capacity-with-azure-file-sync/4-exercise-assess-windows-server-readiness
The suggestion to backrev by DavMHelm worked like a charm, though. 
Thanks,
-b

**Comment by dingmeng-xue** [comment] 2022-03-14 02:14
@Bardski , Thanks for your reporting. Could you help to verify the version you are using? Current fix is just for simple parameter set. If it blocks other scenarios, we need Compute team to look into further.

**Comment by shankar5885** [comment] 2022-03-15 03:04
I am also facing same issue since 4 days after my Az module upgrade, There is bug fix, try "Update-Module -Name Az" to have very latest version for Az.Compute with bug fix, it resolved my issue.

**Comment by aboyinthebox** [comment] 2022-04-05 07:40
This is now resolved for MS Learn Module

One your Active Sandbox Try Running 

> Install-Module -Name Az.Compute -RequiredVersion 4.24.1 

OR

> Install-Module -Name Az.Compute -RequiredVersion 4.25

Then

> Pwsh 

That starts a new powershell session

New-AzVm -ResourceGroupName learn-d2a8d1e3-0259-4d64-a7ec-8348a719b240 -Name "testvm-eus-01" -Credential (Get-Credential) -Location "East US" -Image UbuntuLTS -OpenPorts 22 -PublicIpAddressName "testvm-01"

will work successfully now!
