### ISSUE TITLE
Connect-AzAccount Not Working on macOS

### ISSUE THREAD

**Issue by Amethi** [Azure/azure-powershell#11499] opened 2020-04-05 09:18 UTC
Installed the latest v7 PowerShell for macOS and Connect-AzAccount does not work. I get the following error in the terminal after what looks like a successful browser experience:

```
Connect-AzAccount: AADSTS50097: Device authentication is required.
Trace ID: cf5639c2-a795-4678-9448-7e57a4070c00
Correlation ID: 43cb902c-373a-4bd3-94c1-90bb37bfabbf
Timestamp: 2020-04-05 09:13:28Z: Response status code does not indicate success: 401 (Unauthorized).
```

AAD Signin info:

```
Sign-in error code: 50097
Failure reason: Device Authentication Required - DeviceId -DeviceAltSecId claims are null OR no device corresponding to the device identifier exists.
```

**Comment by dingmeng-xue** [comment] 2020-04-06 12:33
Thanks for reporting. We will try to reproduce it on PowerShell 7.

**Comment by egilh** [comment] 2020-04-15 11:28
Just started working with Azure again from my mac.
Updated to PowerShell v7 and I am experiencing the same error.
```
Connect-AzAccount: AADSTS50097: Device authentication is required.
Trace ID: e3d89f5d-8da4-4a11-bb62-087736e66000
Correlation ID: 232cc4d6-63ce-4ffa-838d-ec0bfa075373
Timestamp: 2020-04-15 11:18:25Z: Response status code does not indicate success: 401 (Unauthorized).
```
I have tried using different browsers with same results, after entering the code I receive a successful result in browser, PowerShell reports 401 error.
This is a major blocker for me.

**Comment by egilh** [comment] 2020-04-15 11:56
Quick update: Strangely enough I just tested against a different customers AAD tenant, and that worked without issues.
I don't have admin access to AAD in either of those I have testet, so I have no idea what different settings there are. I have confirmed with colleagues using the az module on Windows and they don't experience the same problem.

**Comment by dingmeng-xue** [comment] 2020-06-23 07:26
@egilh , according to the feedback from AAD on similar case, https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1543, it seems they prefer user to use the MSAL and won't fix code in AAD.

If you want to know the root cause, one possible way is to provide HTTP traffic record. You can record it using fiddler.

**Comment by dingmeng-xue** [comment] 2020-06-29 07:19
@egilh and @Amethi , I close this issue now due to AAD team cannot investigate further without HTTP traffic record. Please share it to us if you have further information.

**Comment by dgcaron** [comment] 2020-07-06 18:47
i am actually getting this exact error on windows with Powershell 7.0.1 with *one* of my subscriptions. i can login on some of my subscriptions but with a subscription where MFA is enabled i am getting this exact error:

```powershell
Connect-AzAccount -Tenant *** -Subscription ***
WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code *** to authenticate.
Connect-AzAccount: AADSTS50097: Device authentication is required.
Trace ID: 7275ec8a-38c7-4a66-812c-cf5aedd66600
Correlation ID: 22236af3-7799-4755-85be-69ffd212b8f7
Timestamp: 2020-07-06 18:26:06Z: Response status code does not indicate success: 401 (Unauthorized).
```

**Comment by dingmeng-xue** [comment] 2020-08-03 05:12
@dgcaron , please package and send it via email. I have shared my address.

**Comment by dgcaron** [comment] 2020-08-21 08:18
hi sorry, for the late reply but i was on holiday. i am not sure where you have shared your email address?

**Comment by dgcaron** [comment] 2020-08-21 08:22
i have shared the .saz via the email. thank you for investiging this!

**Comment by brucezlata** [comment] 2020-09-29 01:24
Same issue. Cannot use az powershell.

**Comment by vitaminsafety** [comment] 2020-10-19 21:50
You get this issue when your tenant or subscription id is incorrect, correct is for example:

Connect-AzAccount -Tenant *** -Subscription ***

**Comment by CloudViking** [comment] 2021-01-22 21:46
I just upgraded my powershell to 7.1 and now I cannot connect to my Subscriptions. I get the same errors as others above:

`Connect-AzAccount: AADSTS50097: Device authentication is required.
Trace ID: 7dca9ef9-6141-4432-ba32-a467c7849e00
Correlation ID: 76337cd1-63a0-47c2-b783-74e712aa4850
Timestamp: 2021-01-22 21:33:57Z: Response status code does not indicate success: 401 (Unauthorized).`

How do I resolve this? It is a big blocker

**Comment by dingmeng-xue** [comment] 2021-01-25 03:28
@CloudViking , please create an new issue instead of reopen old one. In issue you created, please post `$PSVersionTable`, debug message and the list of imported modules (`Get-Module`). 

Close current one.

**Closed by dingmeng-xue** 2021-01-25 03:28 UTC
Labels: Azure PS Team, More Info :label:, customer-reported
