### ISSUE TITLE
Suggestion - Include the relevant cmdlet name in warning/verbose output

### ISSUE THREAD

**Issue by Blackbaud-ShaydeNofziger** [Azure/azure-powershell#4922] opened 2017-11-03 13:01 UTC
My team consumes AzureRm cmdlets as part of our daily automation. We have 20+ custom modules, most of which interact with and call AzureRm cmdlets as part of their execution.

We appreciate the effort to warn developers of future breaking changes, but it would be very helpful if the warning output included the name of the cmdlet that will be changing. Without that, we have to spend time diving deep in our cmdlet code to see which specific AzureRm call we should be addressing to prepare for the output change.

Beyond just the warning of breaking changes, I believe it would be very useful if the cmdlet name was included in *all* warning/verbose output, but I think the breaking-change warning is the bigger priority.

I'm happy to PR this improvement as well if the Azure team agrees it should be added.

**Comment by cormacpayne** [comment] 2017-11-03 15:49
@Blackbaud-ShaydeNofziger Hey Shayde, thanks for the suggestion ☺️ we actually have an item to create our own custom obsolete attribute for cmdlets, parameters and types that will make it easier to find where the deprecation message is coming from: https://github.com/Azure/azure-powershell/issues/3425#issuecomment-325462362

We are trying to get this attribute created and applied by December or January.

I agree that it would be a good idea to also include the cmdlet name in warning/verbose streams. I'm going to change the title of this issue to point to that suggestion since we have one open for the breaking changes. Thanks again!

**Comment by Blackbaud-ShaydeNofziger** [comment] 2017-11-03 17:02
@cormacpayne Great to hear there's already some planned work for standardizing obsolete/deprecation output - I hadn't come across that issue in my search prior to posting.

Including the cmdlet name in the verbose/warning streams has proved incredibly useful for our internal cmdlets, both for debugging and traceability purposes, I'm glad you agree and hope this gets picked up!

**Comment by markcowl** [comment] 2017-12-19 22:40
Closing as duplicate of: #3425

**Closed by markcowl** 2017-12-19 22:40 UTC
Labels: Azure PS Team
