### ISSUE TITLE
Get-AzExpressRouteGateway API version incorrect

### ISSUE THREAD

**Issue by hc-hchen** [Azure/azure-powershell#9060] opened 2019-04-23 15:05 UTC
## Description
When running Get-AzExpressRouteGateway, got an error with the following message "Get-AzExpressRouteGateway : The resource type could not be found in the namespace 'Microsoft.Network' for api version
'2018-12-01'."

## Steps to reproduce

```powershell
Get-AzExpressRouteGateway
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.2828
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2828
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

```powershell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.5.0      Az.Accounts                         {Disable-AzDataCollection, Disable-AzContextAutosave, Enab...
Script     1.4.0      Az.Accounts                         {Disable-AzDataCollection, Disable-AzContextAutosave, Enab...
Script     1.0.1      Az.Aks                              {Get-AzAks, New-AzAks, Remove-AzAks, Import-AzAksCredentia...
Script     1.1.0      Az.AnalysisServices                 {Resume-AzAnalysisServicesServer, Suspend-AzAnalysisServic...
Script     1.0.2      Az.AnalysisServices                 {Resume-AzAnalysisServicesServer, Suspend-AzAnalysisServic...
Script     1.0.0      Az.ApiManagement                    {Add-AzApiManagementRegion, Get-AzApiManagementSsoToken, N...
Script     1.0.0      Az.ApplicationInsights              {Get-AzApplicationInsights, New-AzApplicationInsights, Rem...
Script     1.2.1      Az.Automation                       {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHyb...
Script     1.1.2      Az.Automation                       {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHyb...
Script     1.0.0      Az.Batch                            {Remove-AzBatchAccount, Get-AzBatchAccount, Get-AzBatchAcc...
Script     1.0.0      Az.Billing                          {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzEnrollme...
Script     1.1.0      Az.Cdn                              {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-AzCdnProfil...
Script     1.0.1      Az.CognitiveServices                {Get-AzCognitiveServicesAccount, Get-AzCognitiveServicesAc...
Script     1.7.0      Az.Compute                          {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAv...
Script     1.5.0      Az.Compute                          {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAv...
Script     1.0.1      Az.ContainerInstance                {New-AzContainerGroup, Get-AzContainerGroup, Remove-AzCont...
Script     1.0.0      Az.ContainerInstance                {New-AzContainerGroup, Get-AzContainerGroup, Remove-AzCont...
Script     1.0.1      Az.ContainerRegistry                {New-AzContainerRegistry, Get-AzContainerRegistry, Update-...
Script     1.1.0      Az.DataFactory                      {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get-AzDataFa...
Script     1.0.2      Az.DataFactory                      {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get-AzDataFa...
Script     1.0.0      Az.DataLakeAnalytics                {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeAnalytic...
Script     1.1.0      Az.DataLakeStore                    {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeSt...
Script     1.0.0      Az.DevTestLabs                      {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolic...
Script     1.0.0      Az.Dns                              {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remove-AzDnsRe...
Script     1.1.0      Az.EventGrid                        {New-AzEventGridTopic, Get-AzEventGridTopic, Set-AzEventGr...
Script     1.0.1      Az.EventHub                         {New-AzEventHubNamespace, Get-AzEventHubNamespace, Set-AzE...
Script     1.0.0      Az.HDInsight                        {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefinition, Wa...
Script     1.0.2      Az.IotHub                           {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGroup, Get-A...
Script     1.1.0      Az.KeyVault                         {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertificate, ...
Script     1.0.2      Az.KeyVault                         {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertificate, ...
Script     1.2.1      Az.LogicApp                         {Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccou...
Script     1.0.0      Az.MachineLearning                  {Move-AzMlCommitmentAssociation, Get-AzMlCommitmentAssocia...
Script     1.0.0      Az.MarketplaceOrdering              {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}
Script     1.0.0      Az.Media                            {Sync-AzMediaServiceStorageKeys, Set-AzMediaServiceKey, Ge...
Script     1.0.1      Az.Monitor                          {Get-AzMetricDefinition, Get-AzMetric, Remove-AzLogProfile...
Script     1.6.0      Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Get-Az...
Script     1.3.0      Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Get-Az...
Script     1.0.0      Az.NotificationHubs                 {Get-AzNotificationHub, Get-AzNotificationHubAuthorization...
Script     1.1.0      Az.OperationalInsights              {New-AzOperationalInsightsAzureActivityLogDataSource, New-...
Script     1.0.0      Az.PolicyInsights                   {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPolicyStateSu...
Script     1.0.0      Az.PowerBIEmbedded                  {Remove-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspa...
Script     1.2.0      Az.RecoveryServices                 {Get-AzRecoveryServicesBackupProperty, Get-AzRecoveryServi...
Script     1.1.0      Az.RecoveryServices                 {Get-AzRecoveryServicesBackupProperty, Get-AzRecoveryServi...
Script     1.0.0      Az.RedisCache                       {Remove-AzRedisCachePatchSchedule, New-AzRedisCacheSchedul...
Script     1.0.0      Az.Relay                            {New-AzRelayNamespace, Get-AzRelayNamespace, Set-AzRelayNa...
Script     1.3.0      Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzR...
Script     1.2.0      Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzR...
Script     1.0.0      Az.ServiceBus                       {New-AzServiceBusNamespace, Get-AzServiceBusNamespace, Set...
Script     1.0.1      Az.ServiceFabric                    {Add-AzServiceFabricApplicationCertificate, Add-AzServiceF...
Script     1.0.2      Az.SignalR                          {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey, New-AzSig...
Script     1.8.0      Az.Sql                              {Get-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlData...
Script     1.5.0      Az.Sql                              {Get-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlData...
Script     1.2.0      Az.Storage                          {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStor...
Script     1.0.3      Az.Storage                          {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStor...
Script     1.0.0      Az.StreamAnalytics                  {Get-AzStreamAnalyticsFunction, Get-AzStreamAnalyticsDefau...
Script     1.0.1      Az.TrafficManager                   {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove-AzTraf...
Script     1.1.2      Az.Websites                         {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServ...
Script     1.1.1      Az.Websites                         {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServ...

```

## Debug output

```
DEBUG: 10:51:25 AM - GetAzureRmExpressRouteGatewayCommand begin processing with ParameterSet 'ListBySubscriptionId'.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: 10:51:28 AM - using account id 'hchen@metlife.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'xxxxx@xxxxxx.xxx', environment: 'AzureCloud', tenant:
'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
DEBUG: [ADAL]: Information: 4/23/2019 2:51:28 PM: c878b501-8e2a-495f-949e-2fd3b96ffcb3 - AcquireTokenHandlerBase.cs:
=== Token Acquisition started:
 Authority: https://login.microsoftonline.com/ca56a4a5-e300-406a-98ff-7e36a0baac5b/
 Resource: https://management.core.windows.net/
 ClientId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
 CacheType: null
 Authentication Target: User

DEBUG: [ADAL]: Information: 4/23/2019 2:51:28 PM:  - TokenCache.cs: Deserialized 2 items to token cache.
DEBUG: [ADAL]: Verbose: 4/23/2019 2:51:28 PM: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - TokenCache.cs: Looking up cache
for a token...
DEBUG: [ADAL]: Information: 4/23/2019 2:51:28 PM: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - TokenCache.cs: An item
matching the requested resource was found in the cache
DEBUG: [ADAL]: Information: 4/23/2019 2:51:28 PM: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - TokenCache.cs: 23.40353689
minutes left until token in cache expires
DEBUG: [ADAL]: Information: 4/23/2019 2:51:28 PM: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - TokenCache.cs: A matching item
 (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 4/23/2019 2:51:28 PM: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - AcquireTokenHandlerBase.cs:
=== Token Acquisition finished successfully. An access token was retuned:
 Access Token Hash: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
 Expiration Time: 4/23/2019 3:14:52 PM +00:00
 User Hash: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

DEBUG: [ADAL]: Information: 4/23/2019 2:51:28 PM: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - AcquireTokenHandlerBase.cs:
=== Token Acquisition started:
 Authority: https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/
 Resource: https://management.core.windows.net/
 ClientId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
 CacheType: null
 Authentication Target: User

DEBUG: [ADAL]: Information: 4/23/2019 2:51:28 PM:  - TokenCache.cs: Deserialized 2 items to token cache.
DEBUG: [ADAL]: Verbose: 4/23/2019 2:51:28 PM: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - TokenCache.cs: Looking up cache
for a token...
DEBUG: [ADAL]: Information: 4/23/2019 2:51:28 PM: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - TokenCache.cs: An item
matching the requested resource was found in the cache
DEBUG: [ADAL]: Information: 4/23/2019 2:51:28 PM: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - TokenCache.cs:
23.4035201766667 minutes left until token in cache expires
DEBUG: [ADAL]: Information: 4/23/2019 2:51:28 PM: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - TokenCache.cs: A matching item
 (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 4/23/2019 2:51:28 PM: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - AcquireTokenHandlerBase.cs:
=== Token Acquisition finished successfully. An access token was retuned:
 Access Token Hash: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
 Expiration Time: 4/23/2019 3:14:52 PM +00:00
 User Hash: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/Microsoft.Network/expressRout
eGateways?api-version=2018-12-01

Headers:
x-ms-client-request-id        : xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
x-ms-correlation-request-id   : xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
x-ms-routing-request-id       : SOUTHCENTRALUS:20190423T145129Z:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 23 Apr 2019 14:51:29 GMT

Body:
{
  "error": {
    "code": "InvalidResourceType",
    "message": "The resource type could not be found in the namespace 'Microsoft.Network' for api version
'2018-12-01'."
  }
}


Confirm
The resource type could not be found in the namespace 'Microsoft.Network' for api version '2018-12-01'.
StatusCode: 404
ReasonPhrase: Not Found
OperationID : 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
Get-AzExpressRouteGateway : The resource type could not be found in the namespace 'Microsoft.Network' for api version
'2018-12-01'.
StatusCode: 404
ReasonPhrase: Not Found
OperationID : 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
At line:1 char:1
+ Get-AzExpressRouteGateway -Debug
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzExpressRouteGateway], NetworkCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.GetAzureRmExpressRouteGatewayCommand

DEBUG: AzureQoSEvent: CommandName - Get-AzExpressRouteGateway; IsSuccess - False; Duration - 00:00:06.6899900;
Exception - Microsoft.Azure.Commands.Network.Common.NetworkCloudException: The resource type could not be found in the
namespace 'Microsoft.Network' for api version '2018-12-01'.
StatusCode: 404
ReasonPhrase: Not Found
OperationID : 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' ---> Microsoft.Rest.Azure.CloudException: The resource type could
not be found in the namespace 'Microsoft.Network' for api version '2018-12-01'.
   at
Microsoft.Azure.Management.Network.ExpressRouteGatewaysOperations.<ListBySubscriptionWithHttpMessagesAsync>d__5.MoveNex
t()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at
Microsoft.Azure.Management.Network.ExpressRouteGatewaysOperationsExtensions.<ListBySubscriptionAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at
Microsoft.Azure.Management.Network.ExpressRouteGatewaysOperationsExtensions.ListBySubscription(IExpressRouteGatewaysOpe
rations operations)
   at Microsoft.Azure.Commands.Network.ExpressRouteGatewayBaseCmdlet.ListExpressRouteGateways(String
resourceGroupName)
   at Microsoft.Azure.Commands.Network.GetAzureRmExpressRouteGatewayCommand.Execute()
   at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 10:51:33 AM - GetAzureRmExpressRouteGatewayCommand end processing.
DEBUG: 10:51:33 AM - GetAzureRmExpressRouteGatewayCommand end processing.

```

## Error output

```
RequestId      :
Message        : The resource type could not be found in the namespace 'Microsoft.Network' for api version
                 '2018-12-01'.
                 StatusCode: 404
                 ReasonPhrase: Not Found
                 OperationID : 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
ServerMessage  :
ServerResponse :
RequestMessage :
InvocationInfo : {Get-AzExpressRouteGateway}
Line           : Get-AzExpressRouteGateway -Debug
Position       : At line:1 char:1
                 + Get-AzExpressRouteGateway -Debug
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 17

```

**Comment by hc-hchen** [comment] 2019-04-23 15:11
This command might have been deprecated, the command can be used as a substitute is Get-AzVirtualNetworkGateway

**Comment by niander** [comment] 2019-05-02 17:59
@hc-hchen Hey, I believe the issue is that the required feature has not being enabled in your current subscription. We are following up with the Network team about which feature it is and why it has not been auto-enabled for you.

**Comment by niander** [comment] 2019-05-02 21:37
@hc-hchen, You can get access to the resources if you enable the following feature flags:

* Microsoft.Network/AllowCortexAccess
* Microsoft.Network/AllowCortexExpressRouteGateway

You could use `Register-AzProviderFeature` for that.

I will close the issue for now but feel free to comment here if you have any other question.

**Closed by niander** 2019-05-02 21:37 UTC
Labels: Investigate :mag:
