### ISSUE TITLE
[Doc]: Set-AzStorageLocalUser -PermissionScope

### ISSUE THREAD

**Issue by randomuser369** [Azure/azure-powershell#21020] opened 2023-02-23 11:52 UTC
### Description

The description of the - PermissionScope parameter is incorrect (I believe it's from -UserName)

https://learn.microsoft.com/en-us/powershell/module/az.storage/set-azstoragelocaluser?view=azps-9.4.0

![image](https://user-images.githubusercontent.com/90783201/220897782-6c90f533-a06c-4381-89dc-9048abf13ba4.png)

**Comment by yifanz0** [comment] 2023-02-28 09:18
A fix PR had been raised https://github.com/Azure/azure-powershell/pull/21027 and the fix will be included in the upcoming PSH release on 3/7 
Closing the issue as the issue is fixed

**Closed by yifanz0** 2023-02-28 09:18 UTC
Labels: Storage, customer-reported, CXP Attention
