### ISSUE TITLE
ScheduleRunTimes in Schedule Policy should be in UTC Timezone

### ISSUE THREAD

**Issue by rachaelsingleton** [Azure/azure-powershell#15769] opened 2021-08-27 14:50 UTC
## Description
The Azure Portal lets you adjust the time zone of a back up policy, but PowerShell seems to error. 

![image](https://user-images.githubusercontent.com/59619646/131146762-79f1d73b-ab1f-4904-b824-3b25c62e23c9.png)

## Steps to reproduce

```
$schPol = Get-AzRecoveryServicesBackupSchedulePolicyObject -WorkloadType "AzureVM" -erroraction stop

$BUStartTime = (get-date  -Hour 23 -Minute 0 -Second 0 -Millisecond 0).AddDays(1)
$BUStartTime = [System.TimeZoneInfo]::ConvertTimeBySystemTimeZoneId($BUStartTime, $timeZone)
$schpol.ScheduleRunTimes[0] = $BUStartTime
```

## Module versions

```

    Directory: C:\Users\RSingleton\OneDrive - Velosio\Documents\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                  
---------- -------    ----                                ----------------                                  
Script     4.5.0      Az.RecoveryServices                 {Get-AzRecoveryServicesBackupProperty, Get-AzRe...
Script     4.2.0      Az.RecoveryServices                 {Get-AzRecoveryServicesBackupProperty, Get-AzRe...


```

## Error output

```
ScheduleRunTimes in Schedule Policy should be in UTC Timezone
```

**Comment by adityabalaji-msft** [comment] 2021-08-31 11:35
Currently, the timezone in PowerShell must be specified in UTC. https://docs.microsoft.com/azure/backup/backup-azure-vms-automation#create-a-protection-policy

**Comment by adityabalaji-msft** [comment] 2021-09-29 05:59
Closing this issue as it is by design. We will add the above as a backlog item to see if we can improve the experience and track it for future semesters

**Closed by adityabalaji-msft** 2021-09-29 05:59 UTC
Labels: Recovery Services Backup, Service Attention, question, customer-reported
