### ISSUE TITLE
New-AzStorageAccount can produce HNS (ADLSG2) storage accounts of an incompatible configuration

### ISSUE THREAD

**Issue by Virepri** [Azure/azure-powershell#9032] opened 2019-04-18 17:47 UTC
## Description

While not exactly a bug, the Powershell cmdlet `New-AzStorageAccount` can produce a ADLSG2 account with an incompatible configuration, leading to a ADLSG2 account without a DFS endpoint, making it fully inoperable.

The expected behavior is to error out when an incompatible configuration is selected-- much akin to the Azure Portal.

## Steps to reproduce

```powershell
$rgname = "myresourcegroup"
$accountname = "myaccount"
$region = "westus"
New-AzStorageAccount -ResourceGroupName $rgname -AccountName $accountname -Location $region -SkuName Standard_GRS -EnableHierarchicalNamespace $true
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.17134.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

```powershell


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.4.0      Az.Accounts                         {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave...}
Script     1.0.1      Az.Aks                              {Get-AzAks, New-AzAks, Remove-AzAks, Import-AzAksCredential...}
Script     1.0.2      Az.AnalysisServices                 {Resume-AzAnalysisServicesServer, Suspend-AzAnalysisServicesServer, Get-AzAnalysisServicesServer, Remove-AzAnalysisServicesServer...}
Script     1.0.0      Az.ApiManagement                    {Add-AzApiManagementRegion, Get-AzApiManagementSsoToken, New-AzApiManagementCustomHostnameConfiguration, New-AzApiManagementSystemCertificate...}
Script     1.0.0      Az.ApplicationInsights              {Get-AzApplicationInsights, New-AzApplicationInsights, Remove-AzApplicationInsights, Set-AzApplicationInsightsPricingPlan...}
Script     1.2.0      Az.Automation                       {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHybridWorkerGroup, Get-AzAutomationJobOutputRecord, Import-AzAutomationDscNodeConfiguration...}
Script     1.0.0      Az.Batch                            {Remove-AzBatchAccount, Get-AzBatchAccount, Get-AzBatchAccountKeys, New-AzBatchAccount...}
Script     1.0.0      Az.Billing                          {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzEnrollmentAccount, Get-AzConsumptionBudget...}
Script     1.1.0      Az.Cdn                              {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-AzCdnProfile, Remove-AzCdnProfile...}
Script     1.0.1      Az.CognitiveServices                {Get-AzCognitiveServicesAccount, Get-AzCognitiveServicesAccountKey, Get-AzCognitiveServicesAccountSkus, Get-AzCognitiveServicesAccountType...}
Script     1.6.0      Az.Compute                          {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAvailabilitySet, Update-AzAvailabilitySet...}
Script     1.0.0      Az.ContainerInstance                {New-AzContainerGroup, Get-AzContainerGroup, Remove-AzContainerGroup, Get-AzContainerInstanceLog}
Script     1.0.1      Az.ContainerRegistry                {New-AzContainerRegistry, Get-AzContainerRegistry, Update-AzContainerRegistry, Remove-AzContainerRegistry...}
Script     1.0.2      Az.DataFactory                      {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get-AzDataFactoryV2, Remove-AzDataFactoryV2...}
Script     1.0.0      Az.DataLakeAnalytics                {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeAnalyticsCatalogCredential, Remove-AzDataLakeAnalyticsCatalogCredential, Set-AzDataLakeAnalyticsCatalogCredential...}
Script     1.1.0      Az.DataLakeStore                    {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreFirewallRule, Set-AzDataLakeStoreTrustedIdProvider...}
Script     1.0.0      Az.DevTestLabs                      {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolicy, Get-AzDtlAutoStartPolicy, Get-AzDtlVMsPerLabPolicy...}
Script     1.0.0      Az.Dns                              {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remove-AzDnsRecordSet, Set-AzDnsRecordSet...}
Script     1.1.0      Az.EventGrid                        {New-AzEventGridTopic, Get-AzEventGridTopic, Set-AzEventGridTopic, New-AzEventGridTopicKey...}
Script     1.0.1      Az.EventHub                         {New-AzEventHubNamespace, Get-AzEventHubNamespace, Set-AzEventHubNamespace, Remove-AzEventHubNamespace...}
Script     1.0.0      Az.HDInsight                        {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefinition, Wait-AzHDInsightJob, New-AzHDInsightStreamingMapReduceJobDefinition...}
Script     1.0.2      Az.IotHub                           {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGroup, Get-AzIotHubConnectionString, Get-AzIotHubJob...}
Script     1.1.0      Az.KeyVault                         {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertificate, Stop-AzKeyVaultCertificateOperation, Get-AzKeyVaultCertificateOperation...}
Script     1.2.1      Az.LogicApp                         {Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccountAssembly, Get-AzIntegrationAccountBatchConfiguration, Get-AzIntegrationAccountCallbackUrl...}
Script     1.0.0      Az.MachineLearning                  {Move-AzMlCommitmentAssociation, Get-AzMlCommitmentAssociation, Get-AzMlCommitmentPlanUsageHistory, Remove-AzMlCommitmentPlan...}
Script     1.0.0      Az.MarketplaceOrdering              {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}
Script     1.0.0      Az.Media                            {Sync-AzMediaServiceStorageKeys, Set-AzMediaServiceKey, Get-AzMediaServiceKeys, Get-AzMediaServiceNameAvailability...}
Script     1.0.1      Az.Monitor                          {Get-AzMetricDefinition, Get-AzMetric, Remove-AzLogProfile, Get-AzLogProfile...}
Script     1.6.0      Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Get-AzApplicationGatewayAuthenticationCertificate, New-AzApplicationGatewayAuthenticationCertificate, Remove-AzApplicationGatewayAuthenticationCertificate...}
Script     1.0.0      Az.NotificationHubs                 {Get-AzNotificationHub, Get-AzNotificationHubAuthorizationRules, Get-AzNotificationHubListKeys, Get-AzNotificationHubPNSCredentials...}
Script     1.1.0      Az.OperationalInsights              {New-AzOperationalInsightsAzureActivityLogDataSource, New-AzOperationalInsightsCustomLogDataSource, Disable-AzOperationalInsightsLinuxCustomLogCollection, Disable-AzOperationalInsightsIISLogCollection...}
Script     1.0.0      Az.PolicyInsights                   {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPolicyStateSummary, Get-AzPolicyRemediation...}
Script     1.0.0      Az.PowerBIEmbedded                  {Remove-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollectionAccessKeys, Get-AzPowerBIWorkspace...}
Script     1.2.0      Az.RecoveryServices                 {Get-AzRecoveryServicesBackupProperty, Get-AzRecoveryServicesVault, Get-AzRecoveryServicesVaultSettingsFile, New-AzRecoveryServicesVault...}
Script     1.0.0      Az.RedisCache                       {Remove-AzRedisCachePatchSchedule, New-AzRedisCacheScheduleEntry, Get-AzRedisCachePatchSchedule, New-AzRedisCachePatchSchedule...}
Script     1.0.0      Az.Relay                            {New-AzRelayNamespace, Get-AzRelayNamespace, Set-AzRelayNamespace, Remove-AzRelayNamespace...}
Script     1.2.1      Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRoleAssignment, New-AzRoleAssignment...}
Script     1.0.0      Az.ServiceBus                       {New-AzServiceBusNamespace, Get-AzServiceBusNamespace, Set-AzServiceBusNamespace, Remove-AzServiceBusNamespace...}
Script     1.0.1      Az.ServiceFabric                    {Add-AzServiceFabricApplicationCertificate, Add-AzServiceFabricClientCertificate, Add-AzServiceFabricClusterCertificate, Add-AzServiceFabricNode...}
Script     1.0.2      Az.SignalR                          {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey, New-AzSignalRKey...}
Script     1.7.0      Az.Sql                              {Get-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabaseTransparentDataEncryptionActivity, Set-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabaseUpgradeHint...}
Script     1.1.0      Az.Storage                          {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStorageAccount, New-AzStorageAccountKey...}
Script     1.0.0      Az.StreamAnalytics                  {Get-AzStreamAnalyticsFunction, Get-AzStreamAnalyticsDefaultFunctionDefinition, New-AzStreamAnalyticsFunction, Remove-AzStreamAnalyticsFunction...}
Script     1.0.1      Az.TrafficManager                   {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove-AzTrafficManagerCustomHeaderFromEndpoint, Add-AzTrafficManagerCustomHeaderToProfile, Remove-AzTrafficManagerCustomHeaderFromProfile...}
Script     1.1.2      Az.Websites                         {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServicePlan, Remove-AzAppServicePlan...}
```

## Debug output

```
DEBUG: 10:45:01 - NewAzureStorageAccountCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 10:45:01 - using account id 'REDACTED'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'REDACTED', environment: 'AzureCloud', tenant: '72f988bf-86f1-41af-91ab-2d7cd011db47'
DEBUG: [ADAL]: Information: 4/18/2019 17:45:01: df7e9561-1bfc-40b5-8789-00e58dd479b2 - AcquireTokenHandlerBase.cs: === Token Acquisition started:
 Authority: https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: null
 Authentication Target: User

DEBUG: [ADAL]: Information: 4/18/2019 17:45:01:  - TokenCache.cs: Deserialized 4 items to token cache.
DEBUG: [ADAL]: Verbose: 4/18/2019 17:45:01: df7e9561-1bfc-40b5-8789-00e58dd479b2 - TokenCache.cs: Looking up cache for a token...
DEBUG: [ADAL]: Information: 4/18/2019 17:45:01: df7e9561-1bfc-40b5-8789-00e58dd479b2 - TokenCache.cs: An item matching the requested resource was found in the cache
DEBUG: [ADAL]: Information: 4/18/2019 17:45:01: df7e9561-1bfc-40b5-8789-00e58dd479b2 - TokenCache.cs: 58.6793972483333 minutes left until token in cache expires
DEBUG: [ADAL]: Information: 4/18/2019 17:45:01: df7e9561-1bfc-40b5-8789-00e58dd479b2 - TokenCache.cs: A matching item (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 4/18/2019 17:45:01: df7e9561-1bfc-40b5-8789-00e58dd479b2 - AcquireTokenHandlerBase.cs: === Token Acquisition finished successfully. An access token was retuned:
 Access Token Hash: uQq+xjp5c6ZVlq2upDQ35TDFYUI0bVe+BoNZd+9UkI8=
 Expiration Time: 4/18/2019 18:43:42 +00:00
 User Hash: 5iQRil20ykI8Dbzh7IRYwartOFWXihgwjYLPn2Z4TPU=

DEBUG: [ADAL]: Information: 4/18/2019 17:45:01: 600d2e6d-ab4c-4870-941d-dec24edf5bf3 - AcquireTokenHandlerBase.cs: === Token Acquisition started:
 Authority: https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: null
 Authentication Target: User

DEBUG: [ADAL]: Information: 4/18/2019 17:45:01:  - TokenCache.cs: Deserialized 4 items to token cache.
DEBUG: [ADAL]: Verbose: 4/18/2019 17:45:01: 600d2e6d-ab4c-4870-941d-dec24edf5bf3 - TokenCache.cs: Looking up cache for a token...
DEBUG: [ADAL]: Information: 4/18/2019 17:45:01: 600d2e6d-ab4c-4870-941d-dec24edf5bf3 - TokenCache.cs: An item matching the requested resource was found in the cache
DEBUG: [ADAL]: Information: 4/18/2019 17:45:01: 600d2e6d-ab4c-4870-941d-dec24edf5bf3 - TokenCache.cs: 58.67871439 minutes left until token in cache expires
DEBUG: [ADAL]: Information: 4/18/2019 17:45:01: 600d2e6d-ab4c-4870-941d-dec24edf5bf3 - TokenCache.cs: A matching item (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 4/18/2019 17:45:01: 600d2e6d-ab4c-4870-941d-dec24edf5bf3 - AcquireTokenHandlerBase.cs: === Token Acquisition finished successfully. An access token was retuned:
 Access Token Hash: uQq+xjp5c6ZVlq2upDQ35TDFYUI0bVe+BoNZd+9UkI8=
 Expiration Time: 4/18/2019 18:43:42 +00:00
 User Hash: 5iQRil20ykI8Dbzh7IRYwartOFWXihgwjYLPn2Z4TPU=

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://management.azure.com/subscriptions/e8c9ad26-ca68-49cd-89af-2f2a518e65e7/providers/Microsoft.Storage/checkNameAvailability?api-version=2018-11-01

Headers:
x-ms-client-request-id        : 7b043996-2eae-4f2a-8cb1-edb35748e3bf
accept-language               : en-US

Body:
{
  "name": "trytryagain",
  "type": "Microsoft.Storage/storageAccounts"
}

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-request-id               : 56c56638-5d57-40af-a71e-9d62c1d4c4b4
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-reads: 11993
x-ms-correlation-request-id   : 652bb958-0b21-492d-b82e-a0c49bdee527
x-ms-routing-request-id       : WESTUS2:20190418T174502Z:652bb958-0b21-492d-b82e-a0c49bdee527
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Thu, 18 Apr 2019 17:45:02 GMT
Server                        : Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0

Body:
{
  "nameAvailable": true
}

DEBUG: [ADAL]: Information: 4/18/2019 17:45:02: 561af540-ec33-43c3-b5f1-d76ab64dde38 - AcquireTokenHandlerBase.cs: === Token Acquisition started:
 Authority: https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: null
 Authentication Target: User

DEBUG: [ADAL]: Information: 4/18/2019 17:45:02:  - TokenCache.cs: Deserialized 4 items to token cache.
DEBUG: [ADAL]: Verbose: 4/18/2019 17:45:02: 561af540-ec33-43c3-b5f1-d76ab64dde38 - TokenCache.cs: Looking up cache for a token...
DEBUG: [ADAL]: Information: 4/18/2019 17:45:02: 561af540-ec33-43c3-b5f1-d76ab64dde38 - TokenCache.cs: An item matching the requested resource was found in the cache
DEBUG: [ADAL]: Information: 4/18/2019 17:45:02: 561af540-ec33-43c3-b5f1-d76ab64dde38 - TokenCache.cs: 58.6665932766667 minutes left until token in cache expires
DEBUG: [ADAL]: Information: 4/18/2019 17:45:02: 561af540-ec33-43c3-b5f1-d76ab64dde38 - TokenCache.cs: A matching item (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 4/18/2019 17:45:02: 561af540-ec33-43c3-b5f1-d76ab64dde38 - AcquireTokenHandlerBase.cs: === Token Acquisition finished successfully. An access token was retuned:
 Access Token Hash: uQq+xjp5c6ZVlq2upDQ35TDFYUI0bVe+BoNZd+9UkI8=
 Expiration Time: 4/18/2019 18:43:42 +00:00
 User Hash: 5iQRil20ykI8Dbzh7IRYwartOFWXihgwjYLPn2Z4TPU=

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/e8c9ad26-ca68-49cd-89af-2f2a518e65e7/resourceGroups/TryTryAgain/providers/Microsoft.Storage/storageAccounts/trytryagain?api-version=2018-11-01

Headers:
x-ms-client-request-id        : 0176b137-17f0-487a-8527-d352c872b3d2
accept-language               : en-US

Body:
{
  "sku": {
    "name": "Standard_GRS"
  },
  "kind": "Storage",
  "location": "westus",
  "properties": {
    "isHnsEnabled": true
  }
}

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Accepted

Headers:
Pragma                        : no-cache
Retry-After                   : 17
x-ms-request-id               : a9aa71e2-4e39-4278-a914-eea4d6dea7bf
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : bbeb087a-26d9-40e6-86af-09e8c4ecf5b4
x-ms-routing-request-id       : WESTUS2:20190418T174503Z:bbeb087a-26d9-40e6-86af-09e8c4ecf5b4
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Thu, 18 Apr 2019 17:45:03 GMT
Location                      : https://management.azure.com/subscriptions/e8c9ad26-ca68-49cd-89af-2f2a518e65e7/providers/Microsoft.Storage/locations/westus/asyncoperations/a9aa71e2-4e39-4278-a914-eea4d6dea7bf?monitor=true&api-version=2018-11-01
Server                        : Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0

Body:


DEBUG: [ADAL]: Information: 4/18/2019 17:45:20: 3359a447-8e03-48a2-94f4-45639014e617 - AcquireTokenHandlerBase.cs: === Token Acquisition started:
 Authority: https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: null
 Authentication Target: User

DEBUG: [ADAL]: Information: 4/18/2019 17:45:20:  - TokenCache.cs: Deserialized 4 items to token cache.
DEBUG: [ADAL]: Verbose: 4/18/2019 17:45:20: 3359a447-8e03-48a2-94f4-45639014e617 - TokenCache.cs: Looking up cache for a token...
DEBUG: [ADAL]: Information: 4/18/2019 17:45:20: 3359a447-8e03-48a2-94f4-45639014e617 - TokenCache.cs: An item matching the requested resource was found in the cache
DEBUG: [ADAL]: Information: 4/18/2019 17:45:20: 3359a447-8e03-48a2-94f4-45639014e617 - TokenCache.cs: 58.362743465 minutes left until token in cache expires
DEBUG: [ADAL]: Information: 4/18/2019 17:45:20: 3359a447-8e03-48a2-94f4-45639014e617 - TokenCache.cs: A matching item (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 4/18/2019 17:45:20: 3359a447-8e03-48a2-94f4-45639014e617 - AcquireTokenHandlerBase.cs: === Token Acquisition finished successfully. An access token was retuned:
 Access Token Hash: uQq+xjp5c6ZVlq2upDQ35TDFYUI0bVe+BoNZd+9UkI8=
 Expiration Time: 4/18/2019 18:43:42 +00:00
 User Hash: 5iQRil20ykI8Dbzh7IRYwartOFWXihgwjYLPn2Z4TPU=

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/e8c9ad26-ca68-49cd-89af-2f2a518e65e7/providers/Microsoft.Storage/locations/westus/asyncoperations/a9aa71e2-4e39-4278-a914-eea4d6dea7bf?monitor=true&api-version=2018-11-01

Headers:

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-request-id               : 5f85e7a9-ebf2-4293-af2d-38ddd0676d3e
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-reads: 11992
x-ms-correlation-request-id   : 790018c9-c3f3-4715-add6-d77c44eb2b67
x-ms-routing-request-id       : WESTUS2:20190418T174520Z:790018c9-c3f3-4715-add6-d77c44eb2b67
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Thu, 18 Apr 2019 17:45:20 GMT
Server                        : Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0

Body:
{
  "sku": {
    "name": "Standard_GRS",
    "tier": "Standard"
  },
  "kind": "Storage",
  "id": "/subscriptions/e8c9ad26-ca68-49cd-89af-2f2a518e65e7/resourceGroups/TryTryAgain/providers/Microsoft.Storage/storageAccounts/trytryagain",
  "name": "trytryagain",
  "type": "Microsoft.Storage/storageAccounts",
  "location": "westus",
  "tags": {},
  "properties": {
    "isHnsEnabled": true,
    "networkAcls": {
      "bypass": "AzureServices",
      "virtualNetworkRules": [],
      "ipRules": [],
      "defaultAction": "Allow"
    },
    "supportsHttpsTrafficOnly": false,
    "encryption": {
      "services": {
        "file": {
          "enabled": true,
          "lastEnabledTime": "2019-04-18T17:45:03.1223768Z"
        },
        "blob": {
          "enabled": true,
          "lastEnabledTime": "2019-04-18T17:45:03.1223768Z"
        }
      },
      "keySource": "Microsoft.Storage"
    },
    "provisioningState": "Succeeded",
    "creationTime": "2019-04-18T17:45:03.0129884Z",
    "primaryEndpoints": {
      "blob": "https://trytryagain.blob.core.windows.net/",
      "queue": "https://trytryagain.queue.core.windows.net/",
      "table": "https://trytryagain.table.core.windows.net/",
      "file": "https://trytryagain.file.core.windows.net/"
    },
    "primaryLocation": "westus",
    "statusOfPrimary": "available",
    "secondaryLocation": "eastus",
    "statusOfSecondary": "available"
  }
}

DEBUG: [ADAL]: Information: 4/18/2019 17:45:20: 0c29785d-e14a-4c78-a622-354984d1d3ca - AcquireTokenHandlerBase.cs: === Token Acquisition started:
 Authority: https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: null
 Authentication Target: User

DEBUG: [ADAL]: Information: 4/18/2019 17:45:20:  - TokenCache.cs: Deserialized 4 items to token cache.
DEBUG: [ADAL]: Verbose: 4/18/2019 17:45:20: 0c29785d-e14a-4c78-a622-354984d1d3ca - TokenCache.cs: Looking up cache for a token...
DEBUG: [ADAL]: Information: 4/18/2019 17:45:20: 0c29785d-e14a-4c78-a622-354984d1d3ca - TokenCache.cs: An item matching the requested resource was found in the cache
DEBUG: [ADAL]: Information: 4/18/2019 17:45:20: 0c29785d-e14a-4c78-a622-354984d1d3ca - TokenCache.cs: 58.359560075 minutes left until token in cache expires
DEBUG: [ADAL]: Information: 4/18/2019 17:45:20: 0c29785d-e14a-4c78-a622-354984d1d3ca - TokenCache.cs: A matching item (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 4/18/2019 17:45:20: 0c29785d-e14a-4c78-a622-354984d1d3ca - AcquireTokenHandlerBase.cs: === Token Acquisition finished successfully. An access token was retuned:
 Access Token Hash: uQq+xjp5c6ZVlq2upDQ35TDFYUI0bVe+BoNZd+9UkI8=
 Expiration Time: 4/18/2019 18:43:42 +00:00
 User Hash: 5iQRil20ykI8Dbzh7IRYwartOFWXihgwjYLPn2Z4TPU=

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/e8c9ad26-ca68-49cd-89af-2f2a518e65e7/resourceGroups/TryTryAgain/providers/Microsoft.Storage/storageAccounts/trytryagain?api-version=2018-11-01

Headers:
x-ms-client-request-id        : 8e4e7fe4-bcb9-4dee-a9af-9487f4be8c3b
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-request-id               : 4a703ae2-7680-4f7a-a598-91ffc8e37ef3
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-reads: 11991
x-ms-correlation-request-id   : b53f9fed-d07b-4669-a6a2-eebbfd71aabe
x-ms-routing-request-id       : WESTUS2:20190418T174520Z:b53f9fed-d07b-4669-a6a2-eebbfd71aabe
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Thu, 18 Apr 2019 17:45:20 GMT
Server                        : Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0

Body:
{
  "sku": {
    "name": "Standard_GRS",
    "tier": "Standard"
  },
  "kind": "Storage",
  "id": "/subscriptions/e8c9ad26-ca68-49cd-89af-2f2a518e65e7/resourceGroups/TryTryAgain/providers/Microsoft.Storage/storageAccounts/trytryagain",
  "name": "trytryagain",
  "type": "Microsoft.Storage/storageAccounts",
  "location": "westus",
  "tags": {},
  "properties": {
    "isHnsEnabled": true,
    "networkAcls": {
      "bypass": "AzureServices",
      "virtualNetworkRules": [],
      "ipRules": [],
      "defaultAction": "Allow"
    },
    "supportsHttpsTrafficOnly": false,
    "encryption": {
      "services": {
        "file": {
          "enabled": true,
          "lastEnabledTime": "2019-04-18T17:45:03.1223768Z"
        },
        "blob": {
          "enabled": true,
          "lastEnabledTime": "2019-04-18T17:45:03.1223768Z"
        }
      },
      "keySource": "Microsoft.Storage"
    },
    "provisioningState": "Succeeded",
    "creationTime": "2019-04-18T17:45:03.0129884Z",
    "primaryEndpoints": {
      "blob": "https://trytryagain.blob.core.windows.net/",
      "queue": "https://trytryagain.queue.core.windows.net/",
      "table": "https://trytryagain.table.core.windows.net/",
      "file": "https://trytryagain.file.core.windows.net/"
    },
    "primaryLocation": "westus",
    "statusOfPrimary": "available",
    "secondaryLocation": "eastus",
    "statusOfSecondary": "available"
  }
}


DEBUG: AzureQoSEvent: CommandName - New-AzStorageAccount; IsSuccess - True; Duration - 00:00:20.2636985; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 10:47:02 - NewAzureStorageAccountCommand end processing.
DEBUG: 10:47:02 - NewAzureStorageAccountCommand end processing.
StorageAccountName ResourceGroupName Location SkuName     Kind    AccessTier CreationTime       ProvisioningState EnableHttpsTrafficOnly
------------------ ----------------- -------- -------     ----    ---------- ------------       ----------------- ----------------------
trytryagain        TryTryAgain       westus   StandardGRS Storage            4/18/2019 17:45:03 Succeeded         False
```

## Error output

No error occurred, however, the behavior is unexpected.

As noted above, the expected behavior is to error out when an incompatible configuration is selected-- much akin to the Azure Portal.

**Comment by blueww** [comment] 2019-04-19 04:24
@Virepri
Thanks for report this issue!
Generally, Powershell depends on server error for incompatible configuration is selected, so the issue is Server should report an error when use both Kind=Storage and EnableHierarchicalNamespace=true.

I will contact SRP team for it, and update the issue when get responds from them.

Anyway, before this is fixed on server, Would you please workaround this issue by specify "-Kind StorageV2" when create storage account?

**Comment by blueww** [comment] 2019-04-26 02:30
@huizlAzure 
Would you please help to update the issue when the server deployment for the fix is ready?
Thanks!

**Comment by blueww** [comment] 2019-05-28 09:18
The issue is currently fixed in Server.
When user try to create storage account with StorageV2+EnableHierarchicalNamespace, Server will report 400 error "The value 'True' is not allowed for property isHnsEnabled."
So no new account with incompatible configuration will be created.

**Closed by blueww** 2019-05-28 09:18 UTC
Labels: Bug, Service Attention, Storage
