### ISSUE TITLE
Set-AzureRmKeyVaultAccessPolicy prompts in VSTS pipeline

### ISSUE THREAD

**Issue by MouthOfMadness** [Azure/azure-powershell#7761] opened 2018-11-07 00:01 UTC
### Description

I'm using several powershell scripts to manage a keyvault. the first time I use Set-AzureRmKeyVaultAccessPolicy it works, then second time I use Set-AzureRmKeyVaultAccessPolicy I receive the error: 

Windows PowerShell is in NonInteractive mode. Read and Prompt functionality is not available.

### Script/Steps for Reproduction

The code that fails to add my second policy looks like this:

$keys =  "decrypt","encrypt","unwrapKey","wrapKey","verify","sign","get","list","update","create","import","delete","backup","restore","recover","purge"	

$secrets = "get","list","set","delete","backup","restore","recover","purge" 

$certs = "get","list","delete","create","import","update","managecontacts","getissuers","listissuers","setissuers","deleteissuers","manageissuers","recover","purge","backup","restore"

if ( $PSCmdlet.ShouldProcess($VaultName) )
	{
		Write-Host("Inside should process")
		$avap = Set-AzureRmKeyVaultAccessPolicy -VaultName $VaultName -ServicePrincipalName $ServicePrincipal -ResourceGroupName $ResoureGroup -PermissionsToKeys $keys -PermissionsToSecrets $secrets -PermissionsToCertificates $certs -Confirm:$false -Debug -Verbose -PassThru		
	}

```powershell

```

### Module Version
Latest version in VSTS 6.12

It's the VSTS hosted environment

```powershell
Get-Module -ListAvailable
It's the VSTS hosted environment
```

### Environment Data
It's the VSTS hosted environment

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by markcowl** [comment] 2018-11-26 17:53
@MouthOfMadness Can you please provide some additional information on the failure?

This could be occurring because you are using user authentication and a prompt was required, it could also be occurring because of a SHouldContinue prompt in the cmdlet you are running.  If you can collect debug logs (set ```$DebugPreference="Continue"``` and then run the cmdlets).  We can tell what the issue is.

Otheerwise, make sure you are using service principal credentials when executing these cmdlets.

**Comment by MouthOfMadness** [comment] 2018-11-26 19:52
I believe the root of the problem is the convergent application that resides in the Application Registration Preview (AAD) as this code works fine when I run it against other service principals.  There's an issue with Application Registration Preview, that we can't see it from the Azure Portal after we've registered an API with apps.dev.microsoft.com/
I've raised this issue with Microsoft, but they tell me there's no ETA on a fix for preview features;  I have trouble understanding how their single sign-on production strategy can be moved to a preview feature and then have no ETA on resolution.

**Comment by maddieclayton** [comment] 2018-11-27 05:35
Closing as it seems this issue is unrelated to the Azure PowerShell module so cannot be fixed in this repo.

**Closed by maddieclayton** 2018-11-27 05:35 UTC
Labels: Investigate :mag:, KeyVault, More Info :label:

**Comment by brendonthiede** [comment] 2019-03-19 13:10
I am seeing this exact same behavior. Did anyone identify where the issue resides? (I believe that it's not here, just can't find where)
