### ISSUE TITLE
Connect-AzAccount behind proxy requires Tenant flag

### ISSUE THREAD

**Issue by nmajin** [Azure/azure-powershell#13958] opened 2021-01-15 04:19 UTC
Apparently, the only way I can connect to Azure via PowerShell Core (7.1.0) on macOS (Catalina) behind a proxy is if I specify the `Tenant` flag:
```
Connect-AzAccount -Tenant '<REDACTED>'
```

I can confirm that the proxy is providing SSL intercept on the https://login.microsoftonline.com URL, but why would the `Tenant` flag change the behavior for this connection? Below are my connections ON and OFF the network, and being off the network actually works without the `Tenant` flag provided: 

On the Network Behind Proxy
```
Connect-AzAccount -Debug                                        
DEBUG: 10:15:14 PM - ConnectAzureRmAccountCommand begin processing with ParameterSet 'UserWithSubscriptionId'.
 
Confirm
Are you sure you want to perform this action?
Performing the operation "log in" on target "User account in environment 'AzureCloud'".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): 
DEBUG: 10:15:19 PM - Autosave setting from startup session: 'CurrentUser'
DEBUG: 10:15:19 PM - No autosave setting detected in environment variable 'AzContextAutoSave'. 
DEBUG: 10:15:19 PM - Using Autosave scope 'CurrentUser'
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: 'Common', Endpoint: 'https://login.microsoftonline.com/', ClientId: '<REDACTED>', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/Common/', CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: 'Common', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: '<REDACTED>', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
Connect-AzAccount: AADSTS500021: Access to 'Microsoft Services' tenant is denied.
Trace ID: 2440a0e8-1ddc-48d8-849a-4188820c1300
Correlation ID: 73e90265-2f16-4909-8559-f365a92cd7e4
Timestamp: 2021-01-15 03:15:19Z: Response status code does not indicate success: 400 (BadRequest).
DEBUG: AzureQoSEvent: CommandName - Connect-AzAccount; IsSuccess - False; Duration - 00:00:05.7707816;; Exception - Microsoft.Azure.Commands.Common.Authentication.AadAuthenticationFailedException: AADSTS500021: Access to 'Microsoft Services' tenant is denied.
Trace ID: 2440a0e8-1ddc-48d8-849a-4188820c1300
Correlation ID: 73e90265-2f16-4909-8559-f365a92cd7e4
Timestamp: 2021-01-15 03:15:19Z: Response status code does not indicate success: 400 (BadRequest).
 ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS500021: Access to 'Microsoft Services' tenant is denied.
Trace ID: 2440a0e8-1ddc-48d8-849a-4188820c1300
Correlation ID: 73e90265-2f16-4909-8559-f365a92cd7e4
Timestamp: 2021-01-15 03:15:19Z
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (BadRequest).
 ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: {"error":"invalid_request","error_description":"AADSTS500021: Access to 'Microsoft Services' tenant is denied.\r\nTrace ID: 2440a0e8-1ddc-48d8-849a-4188820c1300\r\nCorrelation ID: 73e90265-2f16-4909-8559-f365a92cd7e4\r\nTimestamp: 2021-01-15 03:15:19Z","error_codes":[500021],"timestamp":"2021-01-15 03:15:19Z","trace_id":"2440a0e8-1ddc-48d8-849a-4188820c1300","correlation_id":"73e90265-2f16-4909-8559-f365a92cd7e4","error_uri":"https://login.microsoftonline.com/error?code=500021"}: Unknown error
      ErrorCode: {"error":"invalid_request","error_description":"AADSTS500021: Access to 'Microsoft Services' tenant is denied.\r\nTrace ID: 2440a0e8-1ddc-48d8-849a-4188820c1300\r\nCorrelation ID: 73e90265-2f16-4909-8559-f365a92cd7e4\r\nTimestamp: 2021-01-15 03:15:19Z","error_codes":[500021],"timestamp":"2021-01-15 03:15:19Z","trace_id":"2440a0e8-1ddc-48d8-849a-4188820c1300","correlation_id":"73e90265-2f16-4909-8559-f365a92cd7e4","error_uri":"https://login.microsoftonline.com/error?code=500021"}
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.AdalHttpClient.GetResponseAsync[T](Boolean respondToDeviceAuthChallenge)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.AdalHttpClient.GetResponseAsync[T]()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireDeviceCodeHandler.RunHandlerAsync()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireDeviceCodeAsync(String resource, String clientId, String extraQueryParameters)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireDeviceCodeAsync(String resource, String clientId)
   at Microsoft.Azure.Commands.Common.Authentication.UserTokenProvider.DoAcquireToken(AdalConfiguration config, String userId, SecureString password, Action`1 promptAction, Boolean renew)
   at Microsoft.Azure.Commands.Common.Authentication.UserTokenProvider.SafeAquireToken(AdalConfiguration config, Action`1 promptAction, String userId, SecureString password, Exception& ex)
      ErrorCode: invalid_request
      StatusCode: 400
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Common.Authentication.UserTokenProvider.AcquireToken(AdalConfiguration config, Action`1 promptAction, String userId, SecureString password, Boolean renew)
   at Microsoft.Azure.Commands.Common.Authentication.UserTokenProvider.GetAccessToken(AdalConfiguration config, String promptBehavior, Action`1 promptAction, String userId, SecureString password, String credentialType)
   at Microsoft.Azure.Commands.Common.Authentication.AdalTokenProvider.GetAccessToken(AdalConfiguration config, String promptBehavior, Action`1 promptAction, String userId, SecureString password, String credentialType)
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account, IAzureEnvironment environment, String tenant, SecureString password, String promptBehavior, Action`1 promptAction, IAzureTokenCache tokenCache, String resourceId)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.AcquireAccessToken(IAzureAccount account, IAzureEnvironment environment, String tenantId, SecureString password, String promptBehavior, Action`1 promptAction)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.ListAccountTenants(IAzureAccount account, IAzureEnvironment environment, SecureString password, String promptBehavior, Action`1 promptAction)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName, SecureString password, Boolean skipValidation, Action`1 promptAction, String name, Boolean shouldPopulateContextList)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass92_0.<ExecuteCmdlet>b__0(AzureRmProfile localProfile, RMProfileClient profileClient, String name)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass94_0.<SetContextWithOverwritePrompt>b__0(AzureRmProfile prof, RMProfileClient client)
   at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 10:15:20 PM - ConnectAzureRmAccountCommand end processing.
```

OFF the Network
```
Connect-AzAccount -Debug
DEBUG: Sought all Az modules and got latest version 3.8.0
DEBUG: 11:08:38 PM - ConnectAzureRmAccountCommand begin processing with ParameterSet 'UserWithSubscriptionId'.

Confirm
Are you sure you want to perform this action?
Performing the operation "log in" on target "User account in environment 'AzureCloud'".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): 
DEBUG: 11:08:43 PM - Autosave setting from startup session: 'CurrentUser'
DEBUG: 11:08:43 PM - No autosave setting detected in environment variable 'AzContextAutoSave'. 
DEBUG: 11:08:43 PM - Using Autosave scope 'CurrentUser'
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: 'Common', Endpoint: 'https://login.microsoftonline.com/', ClientId: '<REDACTED>', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/Common/', CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: 'Common', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: '<REDACTED>', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code <REDACTED> to authenticate.
```

**Comment by dingmeng-xue** [comment] 2021-01-18 01:46
@erich-wang , please help to check this question.

**Comment by erich-wang** [comment] 2021-01-18 02:03
@nmajin , it seems you're using old version of Az.Accounts, could you please upgrade to latest version of Az.Accounts?

**Comment by nmajin** [comment] 2021-01-19 04:12
Thanks for the info, didn't even realize I was that out-of-date. Once I updated I now get a much better login process (similar to the Azure Portal via a Browser) and this now works.

By the way, I noticed I ended up having multiple version of Az.Accounts, even after I uninstalled the older "Az" module, but based on what I've read here (https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-5.3.0) it sounds like there could be older versions of the modules from an older "Az" module installed leftover.

So, what is the recommending way to upgrade to avoid having a mess of multiple modules installed? I ended up removing all of the installed "Az" modules, had to manually remove some leftover Az.* submodules and then finally installed the latest version of "Az" (5.3.0).

**Comment by dcaro** [comment] 2021-01-21 03:18
@nmajin currently the best way to remove older modules is to delete the corresponding folders in your Modules directory (by default in $HOME\Documents\PowerShell\Modules). 

We have a module in preview Az.Tools.Installer that helps addressing this issue amongst other. You can read more about the module and give it a try here: https://techcommunity.microsoft.com/t5/azure-tools/introduction-to-az-tools-installer/ba-p/1697622

**Comment by erich-wang** [comment] 2021-01-25 03:28
Close the issue as the issue is mitigated after upgrading to latest version of Az.Accounts.

**Closed by erich-wang** 2021-01-25 03:28 UTC
Labels: Authentication, customer-reported, question
