### ISSUE TITLE
[Feature]: Cleanup .Azure\ErrorRecords

### ISSUE THREAD

**Issue by dcaro** [Azure/azure-powershell#21732] opened 2023-05-09 00:40 UTC
### Description of the new feature

The ~/.Azure/ErrorRecords folder has a log of all failed cmdlets.
We should clean this folder on a regular basis or not use it depending how the content is used.

**Comment by alunmj** [comment] 2023-05-09 00:47
The context I encountered it in is an Azure Function in PowerShell, whose home directory is limited to 64MB (seems not to be configureable), and was running into random-seeming issues ("The term Connect-AzAccount is not recognized", auth errors related to certificates not being loaded, identity issues, unable to load modules...), which were only solved when we finally lucked on an error message telling us that there was no space left on the device. Finding _which_ device proved challenging.
On my laptop, I have 256MB of ErrorRecords going back to 2019. The Azure Function now contains a daily 'reaper' which goes through and clears this folder out, but it would be nice not to have to.

**Comment by isra-fel** [comment] 2023-05-09 01:59
Thank you @alunmj for providing the context 😀 
We need to reconsider the benefit of having the error records and decide the action to take.
- Regularly clean up the folder
- A global switch
- Remove the feature

**Comment by alunmj** [comment] 2023-05-09 16:53
Two other options come to mind, although you might immediately discard them:

- Document that it exists in the first place
- Check for available space before writing the records
- Throw an exception when the last ErrorRecord write fills the disk, so the error describes the problem, rather than causing later problems with no information

**Comment by dcaro** [comment] 2023-05-10 05:23
@Francisco-Gamino FYI

**Comment by Francisco-Gamino** [comment] 2023-05-10 20:32
Hello @dcaro -- Is Azure PowerShell the only one writing content to this location? Also, we noticed that at `~/.Azure` there are other folders, .e.g., `commands`, `ErrorRecords`, `logs`, and `telemetry`. Should these also be deleted on regular basis? 

/cc @anatolib @michaelpeng36 @shreyabatra4

**Comment by isra-fel** [comment] 2023-05-11 01:34
cc @jiasli does CLI owns any of the directories in `.Azure`?

**Comment by tylermcvaney** [comment] 2023-05-12 18:57
@alunmj, I also am encountering a similar error with ("The term Connect-AzAccount is not recognized") in my Azure Function App. After extensive troubleshooting, we discovered that the issue was related to insufficient disk space. The error message also pointed to a lack of space in the '~/.Azure' directory. Considering Azure Function Apps are a PaaS, this is very difficult for users to diagnose.

**Comment by dcaro** [comment] 2023-05-12 23:42
@alunmj I've created an issue to improve our docs.

**Comment by Alex-wdy** [comment] 2023-05-16 14:05
@tylermcvaney  When you use Azure powershell, do you monitor or use the logs in this directory to help troubleshooting, or do you never care about the logs in this directory? 
I just want to know whether you will pay attention to this log, if it is not the error of insufficient disk.

**Comment by tylermcvaney** [comment] 2023-05-16 14:12
> @tylermcvaney When you use Azure powershell, do you monitor or use the logs in this directory to help troubleshooting, or do you never care about the logs in this directory? I just want to know whether you will pay attention to this log, if it is not the error of insufficient disk.

@Alex-wdy I do not utilize the logs in this directory. I have been considering writing a script that automatically clears '~/.Azure/ErrorRecords' but the trouble is my function, by design, generates a lot of error logs. These logs are silenced in the console but I have no way of stopping them from writing to the ErrorRecords directory. This leads to it filling the  64MB disk limit very quickly.

**Comment by VeryEarly** [comment] 2023-08-16 06:03
Hi all,
we provided a new config 'DisableErrorRecordsPersistence' upon Az 10.3.0 (will be available on 2023-09-05 PST)
```
Update-AzConfig -DisableErrorRecordsPersistence $true
```
please use this to disable writing logs to your file system.

This config will be deprecated and replaced by 'EnableErrorRecordsPersistence' in next major Az release around November 2023. Writing error records to file system will be opt-in since then.

**Comment by isra-fel** [comment] 2023-11-15 06:49
We'll change this to an opt-in approach in Az 12 (around May 2024).
Closing this issue. Tracking it internally.

**Closed by isra-fel** 2023-11-15 06:49 UTC
Labels: feature-request, Tracking
