### ISSUE TITLE
[Az 4.0.1-preview] Piping any Az command to Select-Object -First doesn't return any object

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-powershell#10226] opened 2019-10-09 11:22 UTC
## Description
Piping any Az command to `Select-Object -First` doesn't return any object, unless you specify a value that is **higher** than the number of piped objects. That makes `Select-Object -First` practically unusable.

## Steps to reproduce

```powershell
PS /> Get-AzWebApp

Kind        Location    Name          Type
----        --------    ----          ----
app         West Europe demo54321    Microsoft.Web/sites
functionapp West Europe demofuncapp Microsoft.Web/sites

PS /> Get-AzWebApp | Select-Object -First 1
PS /> Get-AzWebApp | Select-Object -First 2
PS /> Get-AzWebApp | Select-Object -First 3

Kind        Location    Name          Type
----        --------    ----          ----
functionapp West Europe demofuncapp Microsoft.Web/sites
app         West Europe demo54321    Microsoft.Web/sites
```

## Environment data

```
PS /home/alek> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.3
PSEdition                      Core
GitCommitId                    7.0.0-preview.3
OS                             Linux 4.4.0-18362-Microsoft #1-Microsoft Mon Mar 18 12:02:00 PST 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module version

```powershell
PS /home/aleks> gmo az -list
    Directory: /home/aleks/.local/share/powershell/Modules

ModuleType Version    PreRelease Name                                PSEdition
---------- -------    ---------- ----                                ---------
Script     4.0.1      preview    Az                                  Core,Desk
```

## Debug output

```
DEBUG: [CmdletException]: Received Exception with message 'PipelineStoppedException - The pipeline has been stopped. :    at System.Management.Automation.CommandProcessor.ProcessRecord()
```

**Comment by msJinLei** [comment] 2019-10-10 00:53
@alexandair Thanks for reporting the issue and we will investigate it and let you know the update.

**Comment by dolauli** [comment] 2019-10-17 04:50
Proved to be an issue caused by autorest core upgrade with a break change. After the ADO job is updated, the issue should be resolved.

**Comment by dolauli** [comment] 2019-10-17 04:51
@dcaro Please verify the fix after we create new Az 4 preview release.

**Comment by dingmeng-xue** [comment] 2019-12-05 15:37
Close it due to inactivity. Please create new issue if issue occurs.

**Comment by alexandair** [comment] 2019-12-07 19:46
@dingmeng-xue Why is this issue closed? How can I test if it's fixed if there is not newer version?
"due to inactivity"? On MSFT-side or mine?

**Comment by dingmeng-xue** [comment] 2019-12-08 02:57
Closed by mistake. Open it

**Comment by dingmeng-xue** [comment] 2020-03-02 07:59
@alexandair, please use  4.0.2-preview to verify this issue. It should be fixed.

**Comment by alexandair** [comment] 2020-03-02 10:41
@dingmeng-xue 
It works in 4.0.2.-preview. Thanks.

**Comment by dingmeng-xue** [comment] 2020-03-02 11:00
Thanks alexandair. Close this issue now.

**Closed by dingmeng-xue** 2020-03-02 11:00 UTC
Labels: Az 4.x Preview, Azure PS Team, Generator
