### ISSUE TITLE
Set-AzWebApp: Expose HealthCheckPath SiteConfig

### ISSUE THREAD

**Issue by DrorOzgaon** [Azure/azure-powershell#16325] opened 2021-11-02 16:23 UTC
## Description of the new feature
The current Set-AzWebApp does not expose the SiteConfig "HealthCheckPath" parameter. We want to automate setting the "HealthCheckPath".

Note: there is a bug open because the "HealthCheckPath" remains null in the SiteConfig despite having a value:
https://github.com/Azure/azure-powershell/issues/14624

## Proposed implementation details (optional)

**Comment by dingmeng-xue** [comment] 2021-11-04 00:48
Thank you for your reporting. Tagging and routing to the team member best able to assist.

**Comment by Kotasudhakarreddy** [comment] 2022-02-28 12:41
Closing as duplicate of #14624. We will give the fix in next release **Mar 2022**

**Closed** 2022-03-09 01:45 UTC
Labels: App Services, feature-request, Service Attention, question, customer-reported
