### ISSUE TITLE
Login failed using Add-AzureAccount with service principal on azure powershell 

### ISSUE THREAD

**Issue by weiil** [Azure/azure-powershell#2165] opened 2016-04-28 09:33 UTC
** AzureEnvironment: AzureChinaCloud

I created a service principal under my subscription, and attempt to login with it using "Add-AzureAccount", scripts as below:

$ServicePrincipalClientID = "xxxxxx"
$ServicePrincipalTenantID = "xxxxxx"
$ServicePrincipalkey = "xxxxxx"
$securePasswd = ConvertTo-SecureString -String $ServicePrincipalkey -AsPlainText -Force
$cred = New-Object System.Management.Automation.PSCredential($ServicePrincipalClientID,$securePasswd)
Add-AzureAccount -ServicePrincipal -Tenant $ServicePrincipalTenantID -Credential $cred -Environment AzureChinaCloud

failed with below errors:
Add-AzureAccount : AADSTS50001: The application named https://management.core.windows.net/ was not found in the tenant named 
xxxxxxxxxxxxxxxxxxxxxxx.  This can happen if the application has not been installed by the administrator of the tenant or 
consented to by any user in the tenant.  You might have sent your authentication request to the wrong tenant.
Trace ID: 0f049f5c-39b6-4044-8ef0-210cc51e1511
Correlation ID: aa8412a1-8309-4ddb-8717-2550eba69f36
Timestamp: 2016-04-28 09:23:50Z
At line:6 char:1
+ Add-AzureAccount -ServicePrincipal -Tenant $ServicePrincipalTenantID -Credential ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Add-AzureAccount], AdalServiceException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Profile.AddAzureAccount

But I tried to login with the same service principal using Azure-Cli and Azure powershell v1.0.7(Login-AzureRmAccount) successfully.

**Comment by markcowl** [comment] 2016-05-02 23:08
### Root Cause
RDFE does not support service principal credentials. Therefore logins will fail

### Proposed Solution
Remove ServicePrincipal related parameter sets from Add-AzureAccount.  This will be a non-breaking change, because these parameter sets cannot work as is.

**Comment by markcowl** [comment] 2016-08-09 00:37
Closing as this login is not supported in RDFE and there have been no new reports of ths ieeus

**Closed by markcowl** 2016-08-09 00:37 UTC
Labels: Team
