### ISSUE TITLE
Key Vault Cmdlets need to support login type AccessToken

### ISSUE THREAD

**Issue by RandalliLama** [Azure/azure-powershell#4818] opened 2017-10-19 19:29 UTC
### Cmdlet(s)
All Key Vault Cmdlets.

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
All
### Module Version
All
### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
All
### Description
When a user signs in using Login-AzureRmAccount and passes the -AccessToken parameter Key Vault Cmdlets will throw an exception indicating that it is unsupported.

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

**Comment by bill-dall** [comment] 2017-12-05 00:22
@RandalliLama - Would this be the fix to have Azure Cloud Shell Powershell work with Key Vaults out of the box? If so, +1! Also looks related to issue #760?

**Comment by RandalliLama** [comment] 2017-12-05 01:43
@bill-dall  This is the first that I've heard Azure Cloud Shell Powershell didn't work with Key Vault.  It does appear to be related to this issue.  I will take a look at what it takes to fix that.

**Comment by bill-dall** [comment] 2017-12-05 17:10
Great! Thanks. Yeah I'm desperately working on workarounds right now...

**Comment by RandalliLama** [comment] 2017-12-05 19:27
@tiffanyachen Please take a look at this.

**Comment by mguirao** [comment] 2018-02-06 16:54
Hey, This is a big blocker for me too. 
Do you have a workaround using the Rest API ?

**Comment by bill-dall** [comment] 2018-02-06 17:25
@mguirao - I looked into REST API workarounds (fairly quickly) and didn't come up with anything obvious. There may be a way. What we ultimately did was log in as a service principal with the correct access rights and the cmdlets worked after that. However, that gives us a big issue of managing the SP credentials, so we're eagerly waiting for a fix.

**Comment by mguirao** [comment] 2018-02-06 17:32
In my scenario, i provide my access token to an azure function that perform powershell action with Login-AzureRmAccount with -AccessToken. 
So the fact that i'm using a service principal or a user is not the issue here, and i want to keep the ability to have the azure context passed as param to my function.
I'm thinking about sending the result of Save-AzureRmProfile instead, to build my azure powershell session inside the function, would you think that i would encounter the same issue ?

**Comment by RandalliLama** [comment] 2018-02-13 17:22
@markcowl Will this start working on prem as well as cloud shell, or is our fix cloud shell only?

**Comment by markcowl** [comment] 2018-02-21 22:55
@RandalliLama This should work on the desktop as well as CloudShell

**Comment by RandalliLama** [comment] 2018-02-21 23:07
@bill-dall @mguirao Can you try this with the latest Azure PowerShell release?

**Comment by mguirao** [comment] 2018-02-22 09:50
I have updated the modules to the last version but I still can't manage to get my secrets. 
here is my scenarii : 

from my desktop : 
`$username = "d323629c-cb9c-..." #Service Principal
$password = 'Pass...' | ConvertTo-SecureString -AsPlainText -Force
$cred = new-object -typename System.Management.Automation.PSCredential -argumentlist $username, $password
Add-AzureRmAccount -Credential $cred -ServicePrincipal -TenantId 3a61a091-...

$azureRmProfile = [Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureRmProfileProvider]::Instance.Profile
$profileClient = New-Object -TypeName Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient -ArgumentList ($azureRmProfile)
$context = Get-AzureRmContext
$AzureToken = $profileClient.AcquireAccessToken($context.Tenant.Id)`

At this point I have my access token that i send using POST request to my azure function, where i'm using it : 
`Add-AzureRmAccount -AccessToken $AzureToken.AccessToken -AccountId $AzureToken.UserId
Get-AzureRmKeyVault    #Works, i'm able to see the list of keyvault
Get-AzureKeyVaultSecret -VaultName anyKeyVault    #fails with following error :

Get-AzureKeyVaultSecret : Cannot retrieve access token for resource 'AzureKeyVaultServiceEndpointResourceId'.  Please ensure that you have providedthe appropriate access tokens when using access token login.
Au caractère Ligne:1 : 1
+ Get-AzureKeyVaultSecret -VaultName cnm-envdesc-kv-devint
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError : (:) [Get-AzureKeyVaultSecret], InvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.GetAzureKeyVaultSecret`

PS C:\Users\mgo> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16299.98
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.98
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS C:\Users\mgo> Get-Module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     4.1.1      AzureRM.KeyVault                    {Add-AzureKeyVaultCertificate, Add-AzureKeyVaultCertificateContact, Add-AzureKeyVaultKey, ...
Script     4.3.0      AzureRM.Profile                     {Add-AzureRmEnvironment, Clear-AzureRmContext, Clear-AzureRmDefault, Connect-AzureRmAccoun...
Manifest   3.0.0.0    Microsoft.PowerShell.Host           {Start-Transcript, Stop-Transcript}
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl, Get-AuthenticodeSignature...}
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Manifest   3.0.0.0    Microsoft.WSMan.Management          {Connect-WSMan, Disable-WSManCredSSP, Disconnect-WSMan, Enable-WSManCredSSP...}
Script     1.2        PSReadline                          {Get-PSReadlineKeyHandler, Get-PSReadlineOption, Remove-PSReadlineKeyHandler, Set-PSReadli...

**Comment by bill-dall** [comment] 2018-02-22 19:35
@RandalliLama - I'm happy to try. Note my issue was on Azure Cloud Shell so I'd like to make sure Cloud Shell has the newest installed before trying - what version should I look for?

**Comment by RandalliLama** [comment] 2018-02-23 17:26
@bill-dall The fix was merged in December '17, but I don't know for certain what release version it would have shown up in.  I would be very surprised if it wasn't in the very latest version.  @markcowl should be able to confirm.

**Comment by RandalliLama** [comment] 2018-02-23 17:26
@mguirao I will investigate and get back to the issue.

**Comment by RandalliLama** [comment] 2018-02-27 01:48
@mguirao You need to get a separate token for Key Vault and then pass it with the -KeyVaultAccessToken parameter to Add-AzureRmAccount.

You can get an access token by calling the following function with $Resource = https://vault.azure.net
```
function Get-AccessToken
(
  [string]$OAut2hUri,
  [string]$AppId,
  [string]$ClientSecret,
  [string]$Resource
)
{
  $body = 'grant_type=client_credentials'
  $body += '&client_id=' + $AppId
  $body += '&client_secret=' + [Uri]::EscapeDataString($ClientSecret)
  $body += '&resource=' + [Uri]::EscapeDataString($Resource)

  $response = Invoke-RestMethod -Method POST -Uri $OAth2Uri -Headers @{} -Body $body

  return $response.access_token
}
```

You can get the OAuth2Uri with this function:
```
function Get-OAuth2Uri
(
  [string]$SecretLocation
)
{
  $response = try { Invoke-RestMethod -Method GET -Uri $SecretLocation -Headers @{} } catch { $_.Exception.Response }
  $authHeader = $response.Headers['www-authenticate']
  $endpoint = [regex]::match($authHeader, 'authorization="(.*?)"').Groups[1].Value

  return "$endpoint/oauth2/token"
}
```

This authentication code is largely from here: https://blogs.msdn.microsoft.com/cclayton/2017/01/02/using-key-vault-secrets-in-powershell/

**Comment by bill-dall** [comment] 2018-03-01 21:23
@RandalliLama - I was able to give it a go today in cloud shell. I found if my account had access to the key vault I could get secrets (which is a definite improvement!) But I was having difficulties setting access policies. i.e., from my laptop this worked:

```
New-AzureRmResourceGroup -Name $rgname -location westus
New-AzureRmKeyVault -VaultName $kvname -ResourceGroupName $rgname -Location westus

Set-AzureRmKeyVaultAccessPolicy -VaultName $kvname -ObjectId $oid -PermissionsToSecrets Get,Set,List
```

but in cloud shell using the same user account I received this error:

```
Set-AzureRmKeyVaultAccessPolicy : Your Azure credentials have not been set up or have expired, please run Connect-AzureRmAccount to set up your Azure credentials.
At line:1 char:1
+ Set-AzureRmKeyVaultAccessPolicy -VaultName '...' -Us ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmKeyVaultAccessPolicy], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.SetAzureKeyVaultAccessPolicy
```

**Comment by RandalliLama** [comment] 2018-03-06 00:18
@markcowl I think this requires your help to debug.

**Comment by RandalliLama** [comment] 2018-03-06 00:21
@bill-dall When you made your cloud shell attempt did you retrieve the access token yourself?  If so, I don't think that will work.  You just want to rely on the shell to have you automatically signed in.  It's my understanding that should just work.

If you just relied on auto auth in cloud shell then @markcowl will need to help out as he is the expert on cloud shell auth.

**Comment by bill-dall** [comment] 2018-03-06 00:28
Hi @RandalliLama  - yes that's correct I was just relying on 'auto auth' in cloud shell and the goal for me would be to have cloud shell PowerShell operate the same as on a standard PowerShell shell after an Add-AzureRmAccount is called, for the same account.

**Comment by RandalliLama** [comment] 2018-03-08 18:48
@markcowl ping

**Comment by markcowl** [comment] 2018-03-09 22:59
@bill-dall How long was the shell open when you ran into this issue, or was it immediate?  

Can you execute with $debugpreference="Continue"  the next time this occurs?

**Comment by bill-dall** [comment] 2018-03-10 00:57
@markcowl - Sure it's really easy to reproduce in about 2 minutes using the code snippet I provided earlier. But with the debug option option I got a bunch of logs, here are the somewhat sanitized version:


DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 03/10/2018 00:48:49:  - TokenCache: Serializing token cache with 0 items.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 03/10/2018 00:48:49:  - TokenCache: Serializing token cache with 0 items.
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: 'xxxxx', Endpoint:
'https://login.microsoftonline.com/', ClientId: 'xxxxx', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri:
'https://graph.windows.net/', ValidateAuthrity: 'True'
Set-AzureRmKeyVaultAccessPolicy : Your Azure credentials have not been set up or have expired, please run Connect-AzureRmAccount to set up your Azure
credentials.
At line:1 char:1
+ Set-AzureRmKeyVaultAccessPolicy -VaultName $kvname -ObjectId $oid -Pe ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmKeyVaultAccessPolicy], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.SetAzureKeyVaultAccessPolicy

DEBUG: AzureQoSEvent: CommandName - Set-AzureRmKeyVaultAccessPolicy; IsSuccess - False; Duration - 00:00:00.4049411; Exception - System.ArgumentException: Your
 Azure credentials have not been set up or have expired, please run Connect-AzureRmAccount to set up your Azure credentials. --->
System.InvalidOperationException: Cannot retrieve access token for resource 'Graph'.  Please ensure that you have provided the appropriate access tokens when
using access token login.
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account, IAzureEnvironment environment, String
tenant, SecureString password, String promptBehavior, Action`1 promptAction, IAzureTokenCache tokenCache, String resourceId)
   at Microsoft.Azure.Commands.KeyVault.Models.DataServiceCredential.GetTokenInternal(String tenantId, IAuthenticationFactory authFactory, IAzureContext
context, String resourceIdEndpoint)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.KeyVault.Models.DataServiceCredential.GetTokenInternal(String tenantId, IAuthenticationFactory authFactory, IAzureContext
context, String resourceIdEndpoint)
   at Microsoft.Azure.Commands.KeyVault.Models.DataServiceCredential.GetToken()
   at Microsoft.Azure.Commands.KeyVault.KeyVaultManagementCmdletBase.<get_ActiveDirectoryClient>b__7_0()
   at Microsoft.Azure.ActiveDirectory.GraphClient.Extensions.DataServiceContextWrapper.<SetToken>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ActiveDirectory.GraphClient.Extensions.DataServiceContextWrapper.<ExecuteAsyncInternal>d__59`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ActiveDirectory.GraphClient.ActiveDirectoryClient.<GetObjectsByObjectIdsAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Commands.KeyVault.KeyVaultManagementCmdletBase.ValidateObjectId(String objId)
   at Microsoft.Azure.Commands.KeyVault.KeyVaultManagementCmdletBase.GetObjectId(String objectId, String upn, String email, String spn)
   at Microsoft.Azure.Commands.KeyVault.SetAzureKeyVaultAccessPolicy.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 12:48:50 AM - SetAzureKeyVaultAccessPolicy end processing.
DEBUG: 12:48:50 AM - SetAzureKeyVaultAccessPolicy end processing.

**Comment by RandalliLama** [comment] 2018-03-16 00:24
@markcowl ?

**Comment by markcowl** [comment] 2018-03-21 18:08
@bill-dall On premise, for this to work, you would need to provide tokens for Graph as well as ARM in the Connect-AzureRmAccount invocation.  This *should* be working in CloudShell, as they should be providing ARM, Graph, and KeyVault tokens as part of login.  Will take a look.

**Comment by mguirao** [comment] 2018-03-26 12:53
Using Apis and refresh token i'm able to do what i wanted to do : 

On one side : 

```
Add-AzureRmAccount
$currentAzureContext = Get-AzureRmContext
$tokenCache = $currentAzureContext.TokenCache
$cachedTokens = $tokenCache.ReadItems() | ? { $_.TenantId -eq $MyAzureTenantId }
$RefreshToken = $cachedTokens.RefreshToken
```

On the other side : 

```
$url = "https://login.windows.net/$($MyAzureTenantId)/oauth2/token"
$body = "grant_type=refresh_token&refresh_token=$($RefreshToken)"
##Retrieve Access Token
$response = Invoke-RestMethod $url -Method POST -Body $body
$AccessToken = $response.access_token
##Retrieve Access Token (for KV)
$body += "&resource=https%3A%2F%2Fvault.azure.net"
$response = Invoke-RestMethod $url -Method POST -Body $body
$KeyVaultAccessToken = $response.access_token

Add-AzureRmAccount -AccountId $requestBody.AccountId -AccessToken "$AccessToken" -KeyVaultAccessToken "$KeyVaultAccessToken"
```

This way i'm able to use all the functionnality of KeyVault powershell module.
Thank you for your help

**Comment by markcowl** [comment] 2018-04-09 01:13
Verified that these tokens are automatically provided inside CloudShell, so not sure what scenario is missing.  Closing as not repro

**Closed by markcowl** 2018-04-09 01:13 UTC
Labels: Azure PS Team, Investigate, KeyVault

**Comment by bill-dall** [comment] 2018-04-09 16:44
@markcowl - thanks for looking into this but I'm fairly sure the scenario I was tracking (and need) is not resolved.

As per this comment - https://github.com/Azure/azure-powershell/issues/4818#issuecomment-369735450 if you run those three lines of code (substituting in resource group name, key vault name, and the oid of a user in the directory) from PowerShell in a 'PowerShell ISE' session from Windows, and the Azure account has sufficient access - I expect 'owner' is required - then it succeeds and the user represented by the oid has access to the key vault secrets.

If you do exactly the same thing through CloudShell then it fails with the  'Your Azure credentials have not been set up or have expired' error. 'New-AzureRmKeyVault' succeeds but 'Set-AzureRmKeyVaultAccessPolicy' fails.

I find it 100% reproducible and just takes a minute to setup. I haven't found a workaround yet.

Are you closing as not repo because it worked for you?

Thanks,

Bill

**Comment by markcowl** [comment] 2018-07-27 17:48
@bill-dall I didn't see this until just now - for future reference, if you think an issue isn't resolved, filing a new issue is the best mechanism to bring attention to it.

In this case, it is difficult to see why this would fail for you without more information about your CloudSHell configuration.  Meanwhile, CloudShell has moved to a different paradigm for authentication, so the issue non longer applies.  If you are still seeing an issue, please let us know, and we can go through the additional details that would help pinpoint a root cause.

**Comment by bill-dall** [comment] 2018-07-27 18:01
@markcowl - thanks for the response! Yes I was considering opening a new ticket but then got busy for a while and when I got back to it perhaps the new paradigm had been rolled out by then and it was resolved. So we're all good now. - Bill
