### ISSUE TITLE
Set-AzVMBootDiagnostic should allow the use of managed storage account

### ISSUE THREAD

**Issue by JamesKQuinn** [Azure/azure-powershell#13168] opened 2020-10-09 08:49 UTC
## Description of the new feature
In the portal when creating a VM, you can select to use managed storage account for boot diagnostics, but you cannot do this in powershell with Set-AzVMBootDiagnostic, at the moment you can only use a custom storage account.

Portal options for Boot Diagnostics when creating a VM:
![image](https://user-images.githubusercontent.com/70699976/95562807-8e6c0680-0a14-11eb-8c9e-5518f822f87f.png)

## Proposed implementation details
Set-AzVMBootDiagnostic should have a switch to use managed storage account

**Comment by dingmeng-xue** [comment] 2020-10-11 14:56
Compute team, please help to evaluate this feature.

**Comment by amjads1** [comment] 2020-10-12 18:09
Looking into this issue.

**Comment by amjads1** [comment] 2020-10-12 22:12
Assigned to Avi.

**Comment by avirishuv** [comment] 2020-11-05 20:23
@bilaakpan-ms could you please add the capability in Azure PowerShell, to be allow the use of managed storage account with the Set-AzVMBootDiagnostic cmdlet ?

**Comment by aregulargithubguy** [comment] 2020-12-16 15:43
is this issue fixed? in the latest az.compute 4.7.0, not OK yet...in which build can we expect this ? thanks

**Comment by aregulargithubguy** [comment] 2021-01-06 12:33
note: az.compute 4.8.0, nothing changed ...can this be bumped up? a little bit illogic you can do it in the portal but not through posh ....

**Comment by Pwd9000-ML** [comment] 2021-01-20 17:34
yes please fix. I am writing PS functions for this to enable the managed boot diagnostics on Vms that have diag disabled.
This works:

```powershell
$objVm = Get-AzVm -ResourceGroupName $ResourceGroupName -Name $VmName -ErrorAction SilentlyContinue
If (!$objVm.DiagnosticsProfile.BootDiagnostics.Enabled) {
      Write-Output "Boot diagnostics is explicitly disabled on Virtual Machine:[$VmName]."
      $null = Set-AzVMBootDiagnostic -VM $objVm -Enable -ResourceGroupName $ResourceGroupName
      $null = Update-AzVM -VM $objVm -ResourceGroupName $ResourceGroupName
}
```
If I omit the storage account parameter completely it does enable the boot diag on (managed boot diag) but throws ugly error in code: 

Set-AzVMBootDiagnostic : Storage account name for boot diagnostics is not given.
At line:30 char:29
+ ...     $null = Set-AzVMBootDiagnostic -VM $objVm -Enable -ResourceGroupN ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-AzVMBootDiagnostic], InvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.SetAzureVMBootDiagnosticsCommand

Even if I try to $null output or erroraction silently continue I still get the ugly error. 
Please fix or recommend how we can automate this in PoSH.

Maybe make the StorageAccountName parameter of [Set-AzVMBootDiagnostic] to be omitted without throwing the error and that would work for me better.

**Comment by jaylabell** [comment] 2021-02-02 17:45
Development on this feature will begin shortly. Updates soon to come!

**Comment by PiroHiroPiro** [comment] 2021-03-23 07:51
Hi @jaylabell.
Has this feature been implemented and published?
It does not work well with -StorageAccountName set to $null, so is it implemented yet?

**Comment by james-quinn-bradyplc** [comment] 2021-04-21 11:36
Is there any update on this yet?

**Comment by jaylabell** [comment] 2021-06-24 18:58
Development is still underway

**Comment by Sandido** [comment] 2021-07-22 21:42
@JamesKQuinn , @jaylabell ,

The Managed Disks resources and Managed Storage Accounts operate differently than you expect. 

If you want to use a Managed Storage Account in the Set-AzVMBootDiagnostics cmdlet, then you should not enter anything into the StorageAccountName parameter. 
(On a side note, a Managed Storage Account is not an actual resource, it is essentially a Managed Disk). 

You cannot take one Managed Storage Account from somewhere else, and input it as the StorageAccountName parameter in Set-AzVMBootDiagnostics. This Managed Storage Account is an internal account that is on internal subscriptions and resource groups. Users cannot access them or re-use them. They are only there to be quickly setup automatically by Azure so users do not have to go through the extra steps of setting up a Storage Account or create a Blob manually. 

I will be closing this feature request as By Design. 

 @Pwd9000-ML, if you still have an error when trying to use a Managed Storage Account in Set-AzVmBootDiagnostics, I suggest opening a new Github Issue with additional debug data.

**Comment by Ayanmullick** [comment] 2021-09-01 00:43
> Development is still underway

@Sandido, So is there any documentation on how to use managed account? No example documented in link below.
[Example 1: Enable boot diagnostics](https://docs.microsoft.com/en-us/powershell/module/az.compute/set-azvmbootdiagnostic?view=azps-6.3.0#example-1--enable-boot-diagnostics)

Cc: @jaylabell, @mikefrobbins , @dingmeng-xue , @dcaro

**Comment by Ayanmullick** [comment] 2021-10-05 01:06
> Development is still underway

https://github.com/Azure/azure-powershell/pull/16011 created

**Comment by Ayanmullick** [comment] 2021-11-05 23:07
Thanks to @grizzlytheodore , one can now use the code below to `Set-AzVMBootDiagnostic` to `managed storage account` using `Az.Compute v4.19.0`.

```ps
$VM = Get-AzVM -ResourceGroupName <> -Name <>
Set-AzVMBootDiagnostic -VM $VM -Enable 
Update-AzVM -VM $VM -ResourceGroupName <>
```

I think it should be added to the [cmdlet reference](https://docs.microsoft.com/en-us/powershell/module/az.compute/set-azvmbootdiagnostic?view=azps-6.6.0#examples) too.

@mikefrobbins

**Comment by ScriptWeez** [comment] 2021-12-02 23:10
Unfortunately I still cannot run `Set-AzVMBootDiagnostic -VM $VM -Enable` without the `-ResourceGroupName` argument. It will default to the diagnostic account otherwise. This is on `Az.Compute v4.20.0`

**Comment by Ayanmullick** [comment] 2021-12-03 00:39
> Unfortunately I still cannot run `Set-AzVMBootDiagnostic -VM $VM -Enable` without the `-ResourceGroupName` argument. It will default to the diagnostic account otherwise. This is on `Az.Compute v4.20.0`
> 
> @Ayanmullick

```pwsh
Set-AzVMBootDiagnostic -VM $VM -Enable 
Update-AzVM -VM $VM -ResourceGroupName <>
```
This will work only if there is no storage account details in the `PSVirtualMachine` object.

**Comment by ScriptWeez** [comment] 2021-12-03 17:13
That is too bad. There should be an argument that allows the selection of the managed storage account. Otherwise, this cannot be automated (if a storage account exists).

**Comment by Ayanmullick** [comment] 2021-12-05 03:25
@ScriptWeez , I had requested to add a parameter set and document it in the [cmdlet reference](https://docs.microsoft.com/en-us/powershell/module/az.compute/set-azvmbootdiagnostic?view=azps-6.6.0#examples). Awaiting response.

**Comment by jaylabell** [comment] 2022-02-01 15:10
Closing out because the issue has been resolved. Customer is able to point the boot diagnostics to a Microsoft-managed account. 

The reference documentation will be updated accordingly.

**Closed by jaylabell** 2022-02-01 15:10 UTC
Labels: Compute - VM, Service Attention, bug, customer-reported
