### ISSUE TITLE
Random error from Connect-AzAccount using Azure Automation

### ISSUE THREAD

**Issue by bballpaul4work** [Azure/azure-powershell#19576] opened 2022-09-22 18:49 UTC
### Description

Currently using the latest version of Az module within Azure Automation. We have a runbook that is triggered by a webhook 10-20 times per week. About once or twice per week we receive the following error message:

UsernamePasswordCredential authentication failed: Method not found: 'Void Microsoft.Identity.Client.Extensions.Msal.MsalCacheHelper.RegisterCache(Microsoft.Identity.Client.ITokenCache)'. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/usernamepasswordcredential/troubleshoot

The account we're using is an Azure AD service account.
I've set the $debugPreference='Continue' but need to wait for the next time that it fails. We've been unable to reproduce on-demand

### Issue script & Debug output

```PowerShell
$AzDNSCred = Get-AutomationPSCredential -Name 'AzDNSCred'
Connect-AzAccount -SubscriptionId <guid> -TenantId <guid> -Credential $AzDNSCred
```

### Environment data

```PowerShell
PSVersion                      5.1.15063.726                                                                            
PSEdition                      Desktop                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                  
BuildVersion                   10.0.15063.726                                                                           
CLRVersion                     4.0.30319.42000                                                                          
WSManStackVersion              3.0                                                                                      
PSRemotingProtocolVersion      2.3                                                                                      
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
Directory: C:\Modules\User
ModuleType Version    Name                                                
---------- -------    ----                                          
Script     1.3.6      Az.Automation
Script     3.7.0      Az.Compute
Script     3.10.0     Az.Storage
Script     4.6.1      Azure.Storage
Binary     2.0.2.130  AzureAD
Script     6.1.1      AzureRM.Automation
Script     5.9.1      AzureRM.Compute
Script     5.8.2      AzureRM.profile
Script     6.7.3      AzureRM.Resources
Script     4.12.1     AzureRM.Sql
Script     5.2.0      AzureRM.Storage
    Directory: C:\Modules\Global


ModuleType Version    Name                                                
---------- -------    ----                                              
Script     2.8.0      Az.Accounts 
Script     1.1.2      Az.Advisor  
Script     4.1.0      Az.Aks 
Script     1.1.4      Az.AnalysisServices
Script     3.0.0      Az.ApiManagement   
Script     1.1.0      Az.AppConfiguration 
Script     2.0.0      Az.ApplicationInsights
Script     1.0.0      Az.Attestation
Script     3.2.0      Az.Batch
Script     2.0.0      Az.Billing
Script     2.1.0      Az.Cdn 
Script     1.1.0      Az.CloudService
Script     1.11.0     Az.CognitiveServices
Script     3.1.0      Az.ContainerInstance
Script     3.0.0      Az.ContainerRegistry
Script     1.8.0      Az.CosmosDB
Script     1.1.0      Az.DataBoxEdge
Script     1.2.0      Az.Databricks
Script     1.16.7     Az.DataFactory
Script     1.0.2      Az.DataLakeAnalytics
Script     1.3.0      Az.DataLakeStore
Script     1.0.1      Az.DataShare
Script     1.1.0      Az.DeploymentManager 
Script     3.1.0      Az.DesktopVirtualization
Script     1.0.2      Az.DevTestLabs 
Script     1.1.2      Az.Dns 
Script     1.3.0      Az.EventGrid
Script     2.0.0      Az.EventHub
Script     1.9.0      Az.FrontDoor
Script     4.0.3      Az.Functions
Script     5.0.1      Az.HDInsight
Script     2.0.0      Az.HealthcareApis
Script     2.7.4      Az.IotHub
Script     4.5.0      Az.KeyVault
Script     2.1.0      Az.Kusto
Script     1.5.0      Az.LogicApp
Script     1.1.3      Az.MachineLearning
Script     1.2.0      Az.Maintenance
Script     1.0.0      Az.ManagedServiceIdentity
Script     3.0.0      Az.ManagedServices
Script     1.0.2      Az.MarketplaceOrderin
Script     1.1.1      Az.Media 
Script     1.1.2      Az.Migrate
Script     3.0.1      Az.Monitor
Script     1.0.0      Az.MySql
Script     1.1.1      Az.NotificationHubs
Script     3.1.0      Az.OperationalInsights
Script     1.5.0      Az.PolicyInsights
Script     1.1.0      Az.PostgreSql
Script     1.1.2      Az.PowerBIEmbedded
Script     1.0.3      Az.PrivateDns
Script     5.4.0      Az.RecoveryServices
Script     1.6.0      Az.RedisCache
Script     1.0.0      Az.RedisEnterpriseCache
Script     1.0.3      Az.Relay
Script     1.1.0      Az.ResourceMover
Script     6.0.0      Az.Resources
Script     1.3.0      Az.Security
Script     1.1.0      Az.SecurityInsights
Script     1.9.0      Az.ServiceBus
Script     3.0.2      Az.ServiceFabric
Script     1.4.1      Az.SignalR
Script     1.1.0      Az.SqlVirtualMachine
Script     1.1.1      Az.StackHCI
Script     1.7.0      Az.StorageSync
Script     2.0.0      Az.StreamAnalytics
Script     1.0.0      Az.Support
Script     1.4.0      Az.Synapse
Script     1.1.0      Az.TrafficManager
Script     2.11.2     Az.Websites
```

**Comment by dingmeng-xue** [comment] 2022-09-24 02:41
@bballpaul4work , normally, Method not found is due to assembly is loaded but version is different from expected one by Az.Accounts. Please add `Get-Module` after `Connect-AzAccount` to see whether any other module is loaded before Az.Accounts. Please share the list.

**Comment by bballpaul4work** [comment] 2022-09-26 16:29
Unfortunately, when it fails, it will not get past the Connect-AzAccount cmdlet so it won't be able to return the results of Get-Module.

**Comment by dingmeng-xue** [comment] 2022-09-29 02:53
Thanks for information. You can change script into 3 lines and share us the output.
```
Import-Module Az.Accounts
Get-Module
Connect-AzAccount
```

**Comment by dingmeng-xue** [comment] 2022-10-11 14:49
@bballpaul4work , how can I get those 2 modules `Orchestrator.AssetManagement...` and `Orchestrator.GraphRunbook`?

**Comment by bballpaul4work** [comment] 2022-10-11 14:57
I'm not sure where they're coming from. We are not importing any other modules before this. We are running this in Azure Automation so they just show up.
The only other cmdlets we're running before those are these:

param(
    [string]$startstop,
    [string]$VMname,
    [object]$webhookdata
)
"*** " + $env:computername + " ***"
$DebugPreference
$PSVersionTable
#Login to Azure subscription
$O365cred = Get-AutomationPSCredential -Name 'O365Automation'
Write-Output "About to connect to Azure"

**Comment by dingmeng-xue** [comment] 2022-10-12 02:04
Let me contact Automation team to get more information.

**Comment by Jassingh819** [comment] 2022-10-12 09:48
@bballpaul4work This seems like a module version conflict issue. Could you provide us more info like the sub id, account name, runbook name, job id for successful and failed instances so that we check in my telemetry which modules are loaded for each case.?

**Comment by Jassingh819** [comment] 2022-11-04 04:52
Closing with no updates from the Cx. Hope the issue is resolved.

**Closed by Jassingh819** 2022-11-04 04:52 UTC
Labels: question, Authentication, customer-reported, needs-team-attention
