### ISSUE TITLE
Get-AzureResource: Resource does not exist?

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#223] opened 2015-03-04 01:24 UTC
# Problem

## Environment Details

* Microsoft Surface Pro 3
* Windows 8.1 Update 1
* Windows Management Framework (WMF) Core 5.0 February 2015 Preview
* Azure PowerShell module 0.8.14
* Authenticating using an Azure Active Directory (AAD) account

## Problem Description

I'm trying to use the `Get-AzureResource` command to retrieve the resource properties for an Azure Website. I currently have an Azure Resource Manager (ARM) Resource Group (RG) called `Default-Web-NorthCentralUS` that has two resources in it. The resource types are:

* `Microsoft.Web/sites`
* `Microsoft.Web/serverFarms`

![image](https://cloud.githubusercontent.com/assets/466713/6476348/888c03da-c1c9-11e4-969c-db81d036aaad.png)

Furthermore, when I use the `Get-AzureResource` command to retrieve a specific resource, it tells me that the resource does not exist!

> Get-AzureResource : Provided resource does not exist.

![image](https://cloud.githubusercontent.com/assets/466713/6476396/02b98902-c1ca-11e4-83e9-8a5e6c4dfa30.png)

# Expected Behavior

I would expect that the `Get-AzureResource` command would return strongly-typed objects that contain all of the details of each Azure resource in the Resource Group. Instead, it's simply returning some high-level metadata as a `PSCustomObject`.

![image](https://cloud.githubusercontent.com/assets/466713/6476377/d8ffc9b4-c1c9-11e4-9454-0710f1d8b261.png)

What is going on here?

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by markcowl** [comment] 2015-03-13 21:13
@pcgeek86 Hi Trevor, the plan over time is to have per-RP cmdlets which return strongly typed objects.  The *Resource cmdlets will return property bags by design - this allows for both a strongly-typed and a flexible experience with ARM.  I think the referenced bug #248 should solve the issue at hand here.  Closing fro the more specific bug, please reopen if you disagree.

**Closed by markcowl** 2015-03-13 21:13 UTC

**Comment by pcgeek86** [comment] 2015-03-14 05:21
@markcowl Yes, I eventually discovered that the incorrect `-ApiVersion` was causing this error. For customers who are new to ARM, they probably need to be better informed about how to find the correct `-ApiVersion`, and the fact that they even have to do it in the first place. The more documentation around this topic, the better. Thanks!

Thanks for the note on the strongly-typed objects. Looking forward to more full-featured cmdlets!

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by matt-gibbs** [comment] 2015-03-14 06:03
@pcgeek86 We are following up on ways to make the API versions more readily discovered, or potentially defaulted, or at least improve the error with a redirect to more info.
