### ISSUE TITLE
New-AzureStorageContext requires account context (4.0 regression)

### ISSUE THREAD

**Issue by letmaik** [Azure/azure-powershell#3956] opened 2017-05-12 13:14 UTC
### Cmdlet(s)
New-AzureStorageContext

### PowerShell Version
5.1.14393.1066

### Module Version
4.0

### OS Version
Win 10

### Description
In AzureRM < 4.0 it was possible to use this cmdlet without establishing an Azure login. You could use it just by supplying a storage account name and key, which makes sense. In 4.0, you get the error:
> New-AzureStorageContext : "There is no current context, please log in using Login-AzureRmAccount 
for Azure Resource Manager or Add-AzureAccount for Azure Service Management."

This broke one of my scripts and I had to revert to 3.8.

**Comment by cormacpayne** [comment] 2017-05-12 16:29
@letmaik Hey Maik, this is a known issue that is being tracked here: https://github.com/Azure/azure-powershell/issues/3939

We plan on releasing 4.0.1 (containing this fix) to the gallery by the end of the day.

**Comment by markcowl** [comment] 2017-05-12 17:02
@letmaik Closing as duplicate of #3939 (see the release notes for the storage module here: https://www.powershellgallery.com/packages/Azure.Storage/3.0.0, for a desciption of the bug and a workaround)

In the interim, you can work around this by adding the appropriate  -Endpoint string (```-Endpoint ".core.windows.net") for global Azure.

**Closed** 2017-05-12 17:03 UTC
