### ISSUE TITLE
webapp:Add support for Slot Traffic Routing to AzWebApp 

### ISSUE THREAD

**Issue by PlagueHO** [Azure/azure-powershell#10664] opened 2019-12-05 21:28 UTC
## Description of the new feature

Add support for configuring traffic routing percentages to AzWebApp cmdlets.

This functionality is supported in Az CLI with https://docs.microsoft.com/en-us/cli/azure/webapp/traffic-routing?view=azure-cli-latest

## Proposed implementation details (optional)

Possibly implement:
```powershell
Get-AzWebAppTrafficRouting -ResourceGroupName 'rgname' -Name 'webappname' 
Set-AzWebAppTrafficRouting -ResourceGroupName 'rgname' -Name 'webappname' -TrafficRouting @{ 'Staging' = 25; 'Experimental' = 5 }
```

**Comment by ThejaChoudary** [comment] 2020-01-22 14:49
Taking a look at this.

**Comment by panchagnula** [comment] 2020-02-20 06:28
closing as duplicate of https://github.com/Azure/azure-powershell/issues/7682

**Closed by panchagnula** 2020-02-20 06:28 UTC
Labels: App Services, Feature Request, Service Attention
