### ISSUE TITLE
Setting timeout option in Start-AzureRmVm

### ISSUE THREAD

**Issue by TeppeiIshii** [Azure/azure-powershell#4374] opened 2017-07-27 06:43 UTC
This is more a feature request.

Via Azure PowerShell, "Start-AzureRmVm" will timeout like 45 minutes in case of some issue happens (like Azure guest agent inside the guest OS does not respond.) 

---------------
// Possible error message:
Failed to start virtual machine 'VMNAME'. Error: OS Provisioning for VM 'VMNAME' did not finish in the allotted time. However, the VM guest agent was detected running. This suggests the guest OS has not been properly prepared to be used as a VM image (with CreateOption=FromImage). To resolve this issue, either use the VHD as is with CreateOption=Attach or prepare it properly for use as an image: * Instructions for Windows: https://azure.microsoft.com/documentation/articles/virtual-machines-windows-upload-image/ * Instructions for Linux: https://azure.microsoft.com/documentation/articles/virtual-machines-linux-capture-image/
---------------

This is very problematic, for example, if you have a Azure Automation PowerShell script to start multiple VM's in order, because the rest of the commands will stack until the command finally returns. 

By having timeout value, the customers can repeatedly check the VM status and retry the Start-AzureRmVm command.  Hopefully, when the customers see if the VM's actually running, proceed to the next command without waiting for the whole 45 minutes.

**Comment by cormacpayne** [comment] 2017-07-28 18:21
Closing as a duplicate of https://github.com/Azure/azure-powershell/issues/1200

**Closed by cormacpayne** 2017-07-28 18:21 UTC
