### ISSUE TITLE
 New-AzADServicePrincipal throws NullReferenceException

### ISSUE THREAD

**Issue by rvlacil** [Azure/azure-powershell#9478] opened 2019-06-20 19:02 UTC
### Description

`New-AzADServicePrincipal` throws null reference exception

```text

PS > Import-Module Az

PS > Connect-AzAccount

Account                        SubscriptionName TenantId                             Environment
-------                        ---------------- --------                             -----------
admin@redacted.onmicrosoft.com                  9331c545-8ac4-4396-9022-c4b1ad0f9a82 AzureCloud

PS > $DebugPreference="Continue"

PS > New-AzADServicePrincipal -ApplicationId <redacted guid>
DEBUG: 20:52:02 - NewAzureADServicePrincipalCommand begin processing with ParameterSet 'SimpleParameterSet'.
DEBUG: 20:52:02 - using account id 'admin@redacted.onmicrosoft.com'...
DEBUG: Caught exception, type: System.NullReferenceException
New-AzADServicePrincipal : Object reference not set to an instance of an object.
At line:1 char:1
+ New-AzADServicePrincipal -ApplicationId <redacted guid> ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzADServicePrincipal], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ActiveDirectory.NewAzureADServicePrincipalCommand

DEBUG: AzureQoSEvent: CommandName - New-AzADServicePrincipal; IsSuccess - False; Duration - 00:00:00.0491307; Exception
 - System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Commands.ActiveDirectory.ActiveDirectoryBaseCmdlet.HandleException(Exception exception)
   at Microsoft.Azure.Commands.ActiveDirectory.ActiveDirectoryBaseCmdlet.ExecutionBlock(Action execAction)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 20:52:03 - NewAzureADServicePrincipalCommand end processing.
DEBUG: 20:52:03 - NewAzureADServicePrincipalCommand end processing.
```

### Resolve-AzError
```text
PS > Resolve-AzError

   HistoryId: 5


Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.Azure.Commands.ActiveDirectory.ActiveDirectoryBaseCmdlet.HandleException(Exception exception)
                    at Microsoft.Azure.Commands.ActiveDirectory.ActiveDirectoryBaseCmdlet.ExecutionBlock(Action execAction)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.NullReferenceException
InvocationInfo : {New-AzADServicePrincipal}
Line           : New-AzADServicePrincipal -ApplicationId <redacted guid>
Position       : At line:1 char:1
                 + New-AzADServicePrincipal -ApplicationId <redacted guid> ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 5

```

### Get-Module
```text
PS C:\Users\radekv> Get-Module -Name Az

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.3.2      Az
```

**Comment by cormacpayne** [comment] 2019-06-20 21:12
@rvlacil it looks like the issue is [this line](https://github.com/Azure/azure-powershell/blob/master/src/Resources/Resources/ActiveDirectory/Cmdlets/NewAzureADServicePrincipalCommand.cs#L251) due to the fact that the context you're using to create the service principal doesn't have access to any subscriptions. This should be a pretty easy fix from our side and we can make sure it goes out in the next release (July 2nd).

Meanwhile, you should be able to work around this issue by doing the following:

```powershell
Get-AzADApplication -ApplicationId $ApplicationId | New-AzADServicePrincipal
```

**Comment by rvlacil** [comment] 2019-06-21 11:54
The application I am trying to add is a multi tenant app form a different tenant. Is there a way to use Get-AzADApplication for such apps?

**Comment by markcowl** [comment] 2019-08-03 01:20
@rvlacil No, these cmdlets are specifically for single-tenant apps used for client authentication.  The zureAD cmdlets provide a more thorough coverage of the garph API

**Comment by markcowl** [comment] 2019-08-03 01:54
### Description
To fix this issue
- [ ] Validate this issue by logging in to a tenant with no subscription access.  You can do this by adding a service principal, giving the service principal access to the graph library, and not providing any role assignments
- [ ] In the case where there is no subscription in the context, do not dereference Subscription Id and skip adding a role assignment for the Service Principal.
- [ ] Verify the fix using the manual repro from the first step

**Comment by interfacemirror** [comment] 2019-10-12 03:55
@markcowl  Can you provide sample code for your explanation?

I am getting the below error, while trying to create a service principle in my azure tenant without subscription. The reason my tenant has no subscription is that because I provisioned a Dynamics CRM instance which behind the scene created the Azure Tenant for me. I want to use this instance to provide Azure S2S authentication to CRM web api. That is why there is no subscription.

Is there a fix for this? 

New-AzADServicePrincipal : Object reference not set to an instance of an object.
At C:\Users\jandost.khoso\Desktop\CRM Azure.ps1:44 char:7
+ $sp = New-AzADServicePrincipal -DisplayName 'Power Platform S2S' -App ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzADServicePrincipal], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ActiveDirectory.NewAzureADServicePrincipalCommand

**Comment by VeryEarly** [comment] 2019-11-07 10:11
similar issue, will be fixed all together
#10270 
#10346

**Closed** 2019-11-14 01:40 UTC
Labels: Azure PS Team, Ramp Up
