### ISSUE TITLE
Allow to set SigninTenant for New-AzApiManagementIdentityProvider operation

### ISSUE THREAD

**Issue by maksym-synkevych** [Azure/azure-powershell#9783] opened 2019-08-07 13:51 UTC
## Description of the new feature
For now, we can specify "Signin tenant" for Identity provider from Api Management Service UI but we can not do the same using powershell.
## Proposed implementation details (optional)

**Comment by cormacpayne** [comment] 2019-08-22 18:13
Closing this issue as a duplicate of https://github.com/Azure/azure-powershell/issues/9784

**Closed by cormacpayne** 2019-08-22 18:13 UTC
Labels: Azure PS Team, Feature Request
