### ISSUE TITLE
Get-AzConsumptionBudget 422 error with CSP Azure Plan Subscription

### ISSUE THREAD

**Issue by miked1313** [Azure/azure-powershell#17485] opened 2022-03-15 21:03 UTC
### Description

We are not able to get Azure Budgets in a CSP Azure Plan Subscription using Get-AzConsumptionBudget and a global admin account from the client's tenant.  A 422 error is returned.

### Issue script & Debug output

```PowerShell
Get-AzConsumptionBudget

DEBUG: 4:54:16 PM - GetAzureRmConsumptionBudget begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 4:54:16 PM - using account id '<redacted>'...
DEBUG: [Common.Authentication]: Authenticating using Account: '<redacted>', environment:
'AzureCloud', tenant: '<redacted>'
DEBUG: 4:54:16 PM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync -
TenantId:'<redacted>', Scopes:'https://management.core.windows.net//.default',
AuthorityHost:'https://login.microsoftonline.com/', UserId:'<redacted>'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ]
ParentRequestId:
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [03/15/2022 20:54:16 - ] Azure region was not configured or
could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [03/15/2022 20:54:16] Found 3 cache accounts and 0 broker
accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [03/15/2022 20:54:16] Returning 3 accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [03/15/2022 20:54:16 - ] MSAL MSAL.Desktop with assembly
version '4.30.1.0'. CorrelationId(<redacted>)
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [03/15/2022 20:54:16 - ] === AcquireTokenSilent Parameters ===
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [03/15/2022 20:54:16 - ] LoginHint provided: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [03/15/2022 20:54:16 - ] Account provided: True
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [03/15/2022 20:54:16 - ] ForceRefresh: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [03/15/2022 20:54:16 - ]
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - <redacted>
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [03/15/2022 20:54:16 - ] === Token Acquisition (SilentRequest)
 started:

 Authority Host: login.microsoftonline.com
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [03/15/2022 20:54:16 - ] Azure region was not configured or
could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [03/15/2022 20:54:16 - ] Access token is not expired.
Returning the found cache entry. [Current time (03/15/2022 20:54:16) - Expiration Time (03/15/2022 21:39:52 +00:00) -
Extended Expiration Time (03/15/2022 21:39:52 +00:00)]
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [03/15/2022 20:54:16 - ] Returning access token found in
cache. RefreshOn exists ? False
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [03/15/2022 20:54:16 - ] Fetched access token from host
login.microsoftonline.com.
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [03/15/2022 20:54:16 - ] === Token Acquisition finished
successfully. An access token was returned with Expiration Time: 03/15/2022 21:39:52 +00:00 and Scopes
https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ]
ParentRequestId:  ExpiresOn: 2022-03-15T21:39:52.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: '<redacted>',
UserId: '<redacted>'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/<redacted>/providers/Microsoft.Consumption/budgets
?api-version=2018-01-31

Headers:
x-ms-client-request-id        : 596ba56c-1025-4d82-8f5e-bda825a912aa
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
422

Headers:
Pragma                        : no-cache
session-id                    : 3ada3cac-a2eb-454c-946a-fb8a66a20a56
x-ms-request-id               : 061516f1-54e6-4f5f-8914-c514096dd6b4
x-ms-correlation-request-id   : 9afe102c-64bd-4aa6-9df1-4ba04f0fd4d7
x-ms-client-request-id        : 596ba56c-1025-4d82-8f5e-bda825a912aa
x-ms-ratelimit-remaining-subscription-reads: 11999
x-ms-routing-request-id       : CANADACENTRAL:20220315T205415Z:9afe102c-64bd-4aa6-9df1-4ba04f0fd4d7
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 15 Mar 2022 20:54:14 GMT
X-Powered-By                  : ASP.NET

Body:
{
  "error": {
    "code": "422",
    "message": "This operation is not supported in the version specified in the request. Please use version
2019-10-01-preview or later. (Request ID: 061516f1-54e6-4f5f-8914-c514096dd6b4)"
  }
}

Get-AzConsumptionBudget : Operation returned an invalid status code '422'
At line:1 char:1
+ Get-AzConsumptionBudget
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzConsumptionBudget], ErrorResponseException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Consumption.Cmdlets.Budget.GetAzureRmConsumptionBudget

DEBUG: AzureQoSEvent: Module: Az.Billing:2.0.0; CommandName: Get-AzConsumptionBudget; PSVersion: 5.1.22000.282;
IsSuccess: False; Duration: 00:00:01.6884740; Exception: Operation returned an invalid status code '422';
DEBUG: Finish sending metric.
DEBUG: 4:54:19 PM - GetAzureRmConsumptionBudget end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.22000.282
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.282
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.5.2      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Conn...
Script     2.0.0      Az.Billing                          {Get-AzBillingAccount, Get-AzBillingInvoice, Get-AzBilling...
```

### Error output

```PowerShell
DEBUG: 4:57:33 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 4:57:33 PM - using account id '<redacted>'...
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use
`Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other
information on breaking changes in Azure PowerShell.


   HistoryId: 25


Message        : Operation returned an invalid status code '422'
StackTrace     :    at
                 Microsoft.Azure.Management.Consumption.BudgetsOperations.<ListWithHttpMessagesAsync>d__5.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.Consumption.BudgetsOperationsExtensions.<ListAsync>d__1.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.Consumption.BudgetsOperationsExtensions.List(IBudgetsOperations
                 operations)
                    at Microsoft.Azure.Commands.Consumption.Cmdlets.Budget.GetAzureRmConsumptionBudget.ExecuteCmdlet()
Exception      : Microsoft.Azure.Management.Consumption.Models.ErrorResponseException
InvocationInfo : {Get-AzConsumptionBudget}
Line           : Get-AzConsumptionBudget
Position       : At line:1 char:1
                 + Get-AzConsumptionBudget
                 + ~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 25

   HistoryId: 23


Message        : A positional parameter cannot be found that accepts argument 'SilentlyContinue=Continue'.
StackTrace     :    at System.Management.Automation.CmdletParameterBinderController.VerifyArgumentsProcessed(ParameterB
                 indingException originalBindingException)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidati
                 on(Collection`1 arguments)
                    at
                 System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1
                 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary
                 psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object
                 input)
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object
                 input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput,
                 CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][]
                 commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                 frame)
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {Invoke-RestMethod}
Line           : Invoke-RestMethod -Method GET -Uri 'https://management.azure.com/subscriptions/<redacted>/providers/Microsoft.Consumption/budgets?api-version=2019-10-01-preview'$DebugPreference=
                 'Continue'
Position       : At line:1 char:1
                 + Invoke-RestMethod -Method GET -Uri 'https://management.azure.com/subs ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 23
```

**Comment by RakeshMohanMSFT** [comment] 2022-03-17 10:06
@miked1313 Thank you reaching out we are looking into the issue and will help you with an update as soon as possible. Thank you for your patience and understanding.

**Comment by RakeshMohanMSFT** [comment] 2022-03-21 07:31
@miked1313 this is by-design. The SDK is quite old. It only support legacy EA customers - https://docs.microsoft.com/en-us/powershell/module/az.billing/get-azconsumptionbudget?view=azps-7.3.2#notes.

**PowerShell SDK for Consumption is using an older version of Budgets API and few backwards non-compatible items like listing Budgets with filters will not work as expected.**

**Comment by miked1313** [comment] 2022-03-22 20:34
Hi @RakeshMohanMSFT Why is the PowerShell SDK for Consumption using an older version of the Budgets API?  Shouldn't it be updated to use the budgets API version 2019-10-01-preview or later, and/or have a parameter to be able to specify the older API version 2018-01-31 or a newer one?

We as a CSP partner would like to be able to login to a customer's tenant and use the Get-AzConsumptionBudget cmdlet.

**Comment by RakeshMohanMSFT** [comment] 2022-03-23 02:00
@miked1313 Thank you for your response and I do understand your concern. But current the work around is to use the above REST API to unblock you. But i will definitely raise this as a concern and request product team to consider having/updating  powershell to achieve the same. 

Thank you once again for your patience and understanding.

**Comment by miked1313** [comment] 2022-04-05 02:08
Hi @RakeshMohanMSFT Do you know if the Rest API [https://docs.microsoft.com/en-us/rest/api/consumption/budgets/get](https://docs.microsoft.com/en-us/rest/api/consumption/budgets/get) is supported by Partner Center Delegated Administration and if there is any documentation for how to obtain a token to make that API call?

Our use case is that we are a Partner and need to check configured Budgets across hundreds of Client Tenant CSP Azure subscriptions.  We already have an App Registered in our tenant which is authorized to login to Client Tenants using a token from New-PartnerAccessToken, although I am not sure how to make that (Partner Center Delegated Administration) work with the Budgets Rest API.  Thank you.

**Comment by RakeshMohanMSFT** [comment] 2022-04-06 18:27
@miked1313 can you please confirm if you can login to the portal and create budget?

**Comment by miked1313** [comment] 2022-04-13 21:06
Hi @RakeshMohanMSFT I figured out the issue with my script and I was able to connect to a CSP Azure Plan Subscription’s Budget REST API using a token from New-PartnerAccessToken.

**Comment by RakeshMohanMSFT** [comment] 2022-04-14 06:33
@miked1313 Thank you for the confirmation, glad to hear that the issue is fixed. I will close this issue now.

**Closed by RakeshMohanMSFT** 2022-04-14 06:33 UTC
Labels: customer-reported, needs-team-attention, Consumption - Budget, CXP Attention
