### ISSUE TITLE
Installing MSI always fails

### ISSUE THREAD

**Issue by karlti** [Azure/azure-powershell#3501] opened 2017-02-14 14:38 UTC
### PowerShell Version
3.0

### Module Version
-/-

### OS Version
6.2.9200.16398

### Description
Trying to install "azure powershell" MSI via from http://aka.ms/webpi-azps it always fails with this error:

![err](https://cloud.githubusercontent.com/assets/946334/22933159/f037f406-f2ca-11e6-8814-03ea51f10bb4.png)

This occurs on a set of machines managed  at a corporate customer. at least seems the September 2016 release.

**Comment by markcowl** [comment] 2017-02-24 19:23
@karlti We do not understand the set of symptoms you are describing, can you please clarify?.  The link you provided goes to webpi, which does not match the UI you have captured.  The UI you have captured is for an old version of the standalone installer.   Can you verify:

- what link you followed
- what steps you followed after clicking the link
- what the issue you see is
- .net and powershell versions installed on the machine.
- details in the installation log for any failure
- Do you have PowerShell instances running, and were you prompted to close them during the install?

**Comment by karlti** [comment] 2017-02-27 16:07
Thank you , Marc.

Actually this is really a mystery...
Customer sent him the install-log for powershell.
the last i have at Hand, from November Shows three Errors:

1708 RPC_S_NO_ENDPOINT_FOUND
1709 RPC_S_INVALID_TIMEOUT

and then finally a ERROR_INSTALL_FAILURE.

He tries to install via webpi or by downloadingthe msi directly. it always Fails accordingto them..
I attach the zipped insatll log here.

Thank you in advance,
/*Karl
[azure-powershell.3.1.0.zip](https://github.com/Azure/azure-powershell/files/804220/azure-powershell.3.1.0.zip)

**Comment by karlti** [comment] 2017-02-27 16:07
the Close was nit intended, sorry.

**Comment by markcowl** [comment] 2017-03-11 02:37
@karlti The issue is here:

```
MSI (s) (94:78) [11:17:11:636]: Note: 1: 1722 2: RemoveGalleryModules 3: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe 4: -NoLogo -NoProfile -WindowStyle Hidden -NonInteractive -ExecutionPolicy Bypass -Command ". \"C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\RemoveGalleryModules.ps1\"" 

MSI (s) (94:78) [11:17:11:636]: Note: 1: 1722 2: RemoveGalleryModules 3: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe 4: -NoLogo -NoProfile -WindowStyle Hidden -NonInteractive -ExecutionPolicy Bypass -Command ". \"C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\RemoveGalleryModules.ps1\"" 

```

**Comment by markcowl** [comment] 2017-03-20 07:05
@karlti  Closing, as this should be the issue.  If you close all powershell windows first and still see the issue, please reopen.

**Closed by markcowl** 2017-03-20 07:05 UTC
Labels: Investigate, Team
