### ISSUE TITLE
Get-AzADSpCredential doesn't show latest password dates

### ISSUE THREAD

**Issue by rezarms** [Azure/azure-powershell#16983] opened 2022-01-31 13:03 UTC
### Description

I'm trying to check if a password for spn has expired or not.
I'm calling below method to get expiry date for the spns:
`Get-AzADSpCredential -ServicePrincipalName {name} `
or
`Get-AzADSpCredential -objectId {object id}`
I recently renewed  a password but whenever I call the above method it still shows me the old one but using azure cli it works perfectly and display latest expiry date .

I also tried it with cloud shell with latest version but no success.

### Issue script & Debug output

```PowerShell
DEBUG: 12:47:29 - GetAzureADSpCredentialCommand begin processing with ParameterSet 'ObjectIdParameterSet'.
DEBUG: 12:47:32 - using account id 'sth@sth.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'sth@sth.com', environment: 'AzureCloud', tenant: '{tenant id}'
DEBUG: 12:47:32 - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'{tenant id}', Scopes:'https://graph.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'{user id}'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://graph.windows.net//.default ] ParentRequestId: 
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [01/31/2022 12:47:32 - ] Azure region was not configured or could not be disc
overed. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [01/31/2022 12:47:32] Found 1 cache accounts and 0 broker accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [01/31/2022 12:47:32] Returning 1 accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [01/31/2022 12:47:32 - ] MSAL MSAL.Desktop with assembly version '4.30.1.0'. 
CorrelationId()
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [01/31/2022 12:47:32 - ] === AcquireTokenSilent Parameters ===
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [01/31/2022 12:47:32 - ] LoginHint provided: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [01/31/2022 12:47:32 - ] Account provided: True
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [01/31/2022 12:47:32 - ] ForceRefresh: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [01/31/2022 12:47:32 - ] 
=== Request Data ===
Authority Provided? - True
Scopes - https://graph.windows.net//.default
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - {}

DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [01/31/2022 12:47:32 - ] === Token Acquisition (SilentRequest) started:
	
	Authority Host: login.microsoftonline.com
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [01/31/2022 12:47:32 - ] Azure region was not configured or could not be disc
overed. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [01/31/2022 12:47:32 - ] Access token is not expired. Returning the found cac
he entry. [Current time (01/31/2022 12:47:32) - Expiration Time (01/31/2022 13:43:40 +00:00) - Extended Expiration Time (01/31/2022 13
:43:40 +00:00)]
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [01/31/2022 12:47:32 - ] Returning access token found in cache. RefreshOn exi
sts ? False
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [01/31/2022 12:47:32 - ] Fetched access token from host login.microsoftonline
.com. 
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [01/31/2022 12:47:32 - ] === Token Acquisition finished successfully. An acce
ss token was returned with Expiration Time: 01/31/2022 13:43:40 +00:00 and Scopes https://graph.windows.net//{id} https://graph.windows.net//.default
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://graph.windows.net//.default ] ParentRequestId:  ExpiresOn: 202
2-01-31T13:43:40.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: '{id}', UserId: 'user id'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://graph.windows.net/{id}/servicePrincipals/{spn id}/keyCredentials?a
pi-version=1.6

Headers:
x-ms-client-request-id        : {req id}
accept-language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
ocp-aad-diagnostics-server-name: {id}
request-id                    : {}
client-request-id             : {}
x-ms-dirapi-data-contract-version: 1.6
ocp-aad-session-key           : {key}
Duration                      : 594843
x-ms-resource-unit            : 1
DataServiceVersion            : 3.0;
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Access-Control-Allow-Origin   : *
Cache-Control                 : no-cache
Date                          : Mon, 31 Jan 2022 12:47:33 GMT
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "odata.metadata": "https://graph.windows.net/{id}/$metadata#Collection(Microsoft.DirectoryServices.K
eyCredential)",
  "value": []
}


DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://graph.windows.net/{id}/servicePrincipals/{spn id}/passwordCredenti
als?api-version=1.6

Headers:
x-ms-client-request-id        : {id}
accept-language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
ocp-aad-diagnostics-server-name: {}
request-id                    : {}
client-request-id             : {}
x-ms-dirapi-data-contract-version: 1.6
ocp-aad-session-key           : {}
Duration                      : 358888
x-ms-resource-unit            : 1
DataServiceVersion            : 3.0;
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Access-Control-Allow-Origin   : *
Cache-Control                 : no-cache
Date                          : Mon, 31 Jan 2022 12:47:33 GMT
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "odata.metadata": "https://graph.windows.net/{id}/$metadata#Collection(Microsoft.DirectoryServices.P
asswordCredential)",
  "value": [
    {
      "customKeyIdentifier": null,
      "endDate": "2022-01-29T13:07:44Z",
      "keyId": "id",
      "startDate": "2021-01-29T13:07:44.55754Z",
      "value": null
    }
  ]
}




StartDate           : 29/01/2021 13:07:44
EndDate             : 29/01/2022 13:07:44
KeyId               : 
Type                : Password
Usage               : 
CustomKeyIdentifier : 

DEBUG: AzureQoSEvent: CommandName - Get-AzADSpCredential; IsSuccess - True; Duration - 00:00:03.9697022
DEBUG: Finish sending metric.
DEBUG: 12:47:46 - GetAzureADSpCredentialCommand end processing.
```

### Environment data

```PowerShell
PSVersion                      5.1.19041.1320                                                                                        
PSEdition                      Desktop                                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                               
BuildVersion                   10.0.19041.1320                                                                                       
CLRVersion                     4.0.30319.42000                                                                                       
WSManStackVersion              3.0                                                                                                   
PSRemotingProtocolVersion      2.3                                                                                                   
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
Script     2.3.0      Az.Accounts                        
Script     4.8.0      Az.Network                          
Script     4.1.0      Az.Resources
```

**Comment by dingmeng-xue** [comment] 2022-02-03 12:30
Thanks for reporting. We will look into it.

**Comment by rezarms** [comment] 2022-02-03 15:56
I spotted that azure cli is using below api format
https://graph.windows.net/{tenantid}/servicePrincipals?$filter=servicePrincipalNames/any(c:c eq 'spnid')&api-version=1.6

but azure powershell is using
https://graph.windows.net/tenantid/servicePrincipals/{spnid}/keyCredentials

What's more, first time before renewing password the azure cli doesn't return anything but azure PowerShell works fine but after renewing the password azure cli works properly but powershell still returns old expired date.

At the moment I can't use neither cli nor powershell because both seem not to be stable in some situations.

**Comment by VeryEarly** [comment] 2022-02-07 07:29
Hi @rezarms ,

Thanks for reporting this, as you have already found out, the API we are using does not return the up-to-date credentials, please try "Get-AzADAppCredential -ApplicationId $appid"

**Comment by rezarms** [comment] 2022-02-07 07:49
@VeryEarly  that's another issue.
If I use  "Get-AzADAppCredential -ApplicationId $appid" doesn't show expiry date if the password hasn't been renewed. It will work after renewing password but _Get-AzAdSpCredential_ shows it correctly before renewing.
It seems the issue is actually from api itself.

**Comment by rezarms** [comment] 2022-02-15 12:25
I called the api directly in Azure AD graph and Microsoft graph and it seems it's a bug.
I already raised it to Microsoft and waiting for their confirmation.

https://docs.microsoft.com/en-us/answers/questions/730637/microsoft-graph-doesn39t-show-latest-service-princ.html

**Comment by VeryEarly** [comment] 2022-04-26 03:41
Hi @rezarms ,

Since it's caused by service itself, there are nothing we can do from Azure-PowerShell side, will close this issue for now, please feel free to re-open if you have further question.

**Closed** 2022-04-26 03:41 UTC
Labels: bug, question, customer-reported, needs-team-attention
