### ISSUE TITLE
Az.Accounts 2.11.0 may not be imported on Windows PowerShell

### ISSUE THREAD

**Issue by bniranjanbhat** [Azure/azure-powershell#20615] opened 2023-01-11 04:27 UTC
### Description

We are seeing an our PS module does not function anymore with the latest Az.Accounts version:
The latest version of Az.Accounts has broken our Powershell module.
we get this error when Az.Accounts 2.11.0 is installed :

--cut--
Get-InstalledModule Az.Accounts -AllVersions
Version    Name                                Repository           Description
-------    ----                                ----------           -----------
2.11.0     Az.Accounts                         PSGallery            Microsoft Azure PowerShell - Accounts credential...

>  Import-Module Az.Accounts

> Register-AzStackHCI  -SubscriptionId <cleaned> -TenantId <cleaned> 
**WARNING: The command Register-AzModule is part of Azure PowerShell module "Az.Accounts" and it is not installed. Run
"Install-Module Az.Accounts" to install it.
WARNING: The intelligent recommendation feature is in preview. Help us improve it by sharing your experience:
https://go.microsoft.com/fwlink/?linkid=2202436
You cannot call a method on a null-valued expression.
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull**
   
   WHen I uninstall the Az.Accounts 2.11.0 and install 2.10.2 version, I see everything works fine for us. 
    

### Issue script & Debug output

```PowerShell
nothings comes out when I enable debug
```

### Environment data

```PowerShell
$PSVersiontable

Name                           Value
----                           -----
PSVersion                      5.1.20348.1366
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.20348.1366
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
Get-module Az*

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.11.0     Az.Accounts
Script     1.4.1      Az.StackHCI                         {Add-AzStackHCIVMAttestation, Disable-AzStackHCIAttestatio.
```

### Error output

```PowerShell
[100.101.202.128]: PS C:\Users\HciDeploymentUser\Documents> Resolve-AzError
WARNING: The command Resolve-AzError is part of Azure PowerShell module "Az.Accounts" and it is not installed. Run
"Install-Module Az.Accounts" to install it.
The term 'Resolve-AzError' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    + CategoryInfo          : ObjectNotFound: (Resolve-AzError:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by isra-fel** [comment] 2023-01-11 09:07
Thanks @bniranjanbhat for reporting!

We've identified the root cause of this issue, which was we [relied on `$Host.Version` as the version of PowerShell](https://github.com/Azure/azure-powershell/blob/bb60fb40d7d06e79859978ec2bec576f7e083ce0/src/Accounts/Accounts/StartupScripts/InitializeAssemblyResolver.ps1#L2), and used it to determine which assemblies to load. But in some cases (for example a remote PS session) it's not essentially the version we want. We should have used `$PSVersionTable` instead.

For now the work-around is to uninstall Az.Accounts v2.11.0 and install v2.10.4 instead.
```powershell
Uninstall-Module Az.Accounts -RequiredVersion 2.11.0 -Force
Install-Module Az.Accounts -RequiredVersion 2.10.4
```

```powershell
# Alternatively, install both versions side by side and import v2.10.4 explicitly
Install-Module Az.Accounts -RequiredVersion 2.10.4 -Force
Import-Module Az.Accounts -RequiredVersion 2.10.4
``` 

We plan to fix it in the Feb release and will keep the thread updated.

**Comment by fajterini** [comment] 2023-01-11 12:39
Az module 9.1.1. is including version Az.Accounts 2.10.4, in this case downgrade to 9.1.1. would solve two issues until newer version is released for Az.

**Comment by HUMBERP** [comment] 2023-01-11 14:50
Install-Module Az.Accounts -RequiredVersion 2.10.4
Uninstall-Module Az.Accounts -RequiredVersion 2.11.0

Should work

**Comment by isra-fel** [comment] 2023-01-11 16:15
Sorry for the inconvenience to everyone.
When you hit the issue, could you run `$Host.Version` and share with us the result? We'd like to make sure we've identified the right root cause for everyone. Thanks.

**Comment by bretboss** [comment] 2023-01-11 20:34
Warning: At least several other AZ modules were released at the same time and depend upon v2.11.0 and will pull it in if they are referenced.

We tried explicitly referencing v2.10.4 everywhere we have a reference to Az.Accounts, but somehow we still ended up with v2.11.0 being installed.  We tried explicitly removing version 2.11.0 as part of our scripts, but we received the error: `The version '2.11.0' of module 'Az.Accounts' is currently in use. Retry the operation after closing the applications.`   We found that other AZ modules have this as a dependency, so now we have to traverse the dependency tree of the several AZ modules we use and see what their dependencies are.  Then we have to reference the prior versions of those modules.

Any advice on a simpler workaround would be appreciated.

Otherwise, Godspeed on the fix!

**Comment by chwill** [comment] 2023-01-11 22:40
I am actually seeing the issue on the same machine where when running a start-job with a script block it fails to load version 10, but correctly loads version 12 in the same session when not in the script block.

**Comment by bretboss** [comment] 2023-01-11 23:55
I am using Invoke-Command with a session and it fails.

Here is the simplest repeatable case that I've found:
`Invoke-Command -Session (New-PSSession) -ScriptBlock { Import-Module Az.Accounts } -ErrorAction Stop;`
Result: 
```
Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
or one of its dependencies. The system cannot find the file specified.
```

Version Check:
`Invoke-Command -Session (New-PSSession) -ScriptBlock { $Host.Version } -ErrorAction Stop;`
Result:
```
Major  Minor  Build  Revision PSComputerName
-----  -----  -----  -------- --------------
1      0      0      0        localhost
```

Version Check outside of session:
`$Host.Version`
Result:
```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17763  3770
```

**Comment by isra-fel** [comment] 2023-01-12 08:15
Hi all, thanks for your information (👍 specially @bretboss 's). It seems the incorrect usage of `$Host.Version` is indeed the root cause.
**We have produced a hotfix build and verified it against the PS session scenario. But there are just too many different environments that you can run PowerShell in so we'd like to invite you to verify it as well before we publish it to PSGallery.** Comments are much appreciated!

Install the hotfix build by

```powershell
# Az.Tools.Installer is a helper module dedicated in improving your experience with installing Az modules
Install-Module -Name Az.Tools.Installer -Repository PSGallery
Install-AzModule -Path https://azposhpreview.blob.core.windows.net/public/Az.Accounts.2.11.1.nupkg

# In case you don't want to or can't use Az.Tools.Installer module,
# - Download the package from the above URL.
# - Put it in your own PowerShell repository then install it with `Install-Module`.
# - Ref: Registering a local repository https://learn.microsoft.com/en-us/powershell/scripting/gallery/how-to/working-with-local-psrepositories?view=powershell-7.3#registering-a-local-repository
```

**Comment by bretboss** [comment] 2023-01-12 16:23
That fixes it for me!

Repeating the same command that failed previously:
`Invoke-Command -Session (New-PSSession) -ScriptBlock { Import-Module Az.Accounts -PassThru } -ErrorAction Stop;`
Result:
```
ModuleType Version    Name                                ExportedCommands               PSComputerName
---------- -------    ----                                ----------------               --------------
Script     2.11.1     Az.Accounts                         {Save-AzProfile, Register-A... localhost
```

I've also successfully tested this in parts of our automated scripts.

Hopefully you'll be able to release this soon.

**Comment by bretboss** [comment] 2023-01-13 19:32
Thank you @isra-fel for the quick turnaround!

**Closed** 2023-01-16 03:50 UTC
Labels: bug, P0, Accounts, Tracking
