### ISSUE TITLE
[Bug] Unable to Generate Storage Account Table in Azure; Missing Newtonsoft.JSON

### ISSUE THREAD

**Issue by theczorn** [Azure/azure-powershell#6250] opened 2018-05-17 22:50 UTC
### Description
Attempting to connect to Azure to Generate an empty Table under a Storage Account. Appears to be unable to reference Newtonsoft.JSON v10.0.0.0

I can't seem to find anything in the existing issues or across the web on this problem. Any help/guidance would be much appreciated. Thanks.

### Script/Steps for Reproduction
1. Execute below script
2. Enter Azure credentials
3. Receive failure message

Using ```Azure.Storage``` v4.2.1 this appears as an aggregate exception wrapped around an missing reference.
Using ```Azure.Storage``` v4.3.0 this appears as an missing reference exception.

```powershell

Function Set-Account-Context {
    Param (
        [Parameter(Mandatory = $True)]
        $ResourceGroupName, 
        [Parameter(Mandatory = $True)]
        $StorageAccountName
        )
    
    Set-AzureRmCurrentStorageAccount -ResourceGroupName $ResourceGroupName -Name $StorageAccountName | Out-Null

    $StorageAccountKeys = Get-AzureRmStorageAccountKey -ResourceGroupName $ResourceGroupName -Name $StorageAccountName
    $SAKey0 = $StorageAccountKeys | Select-Object -First 1 -ExpandProperty Value

    $SAContext = New-AzureStorageContext -StorageAccountName $StorageAccountName -StorageAccountKey $SAKey0
    return $SAContext
}

#EXECUTE

Connect-AzureRmAccount 

$SAContext = Set-Account-Context -ResourceGroupName "<STUB>" -StorageAccountName "<STUB>"
New-AzureStorageTable -Name "configuration" -Context $SAContext

Resolve-AzureRmError -Last
```

### Module Version
```powershell
ModuleType Version    Name                                ExportedCommands                                  
---------- -------    ----                                ----------------                                  
Script     6.0.1      AzureRM                                                                               
Script     5.7.0      AzureRM           
```

### Environment Data

```powershell
Name                           Value                                                                        
----                           -----                                                                        
PSVersion                      5.1.16299.431                                                                
PSEdition                      Desktop                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                      
BuildVersion                   10.0.16299.431                                                               
CLRVersion                     4.0.30319.42000                                                              
WSManStackVersion              3.0                                                                          
PSRemotingProtocolVersion      2.3                                                                          
SerializationVersion           1.1.0.1                                                                      

```

### Debug Output
```
DEBUG: AzureQoSEvent: CommandName - Get-AzureRmStorageAccountKey; IsSuccess - True; Duration - 00:00:00.17751
24; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 5:39:26 PM - GetAzureStorageAccountKeyCommand end processing.
DEBUG: 5:39:26 PM - GetAzureStorageAccountKeyCommand end processing.
DEBUG: 5:39:26 PM - NewAzureStorageContext begin processing with ParameterSet 'AccountNameAndKey'.
DEBUG: 5:39:26 PM - NewAzureStorageContext end processing.
DEBUG: 5:39:26 PM - Init Operation Context for 'NewAzureStorageTableCommand' with client request id  Azure-St
orage-PowerShell-53ffc562-78a0-4775-ae27-f9ed5e649ab9. If you want to get more details, please add "-Debug" t
o your command.
DEBUG: 5:39:26 PM - NewAzureStorageTableCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 5:39:26 PM - Use storage account '<TARGET_HERE>' from storage context.
New-AzureStorageTable : One or more errors occurred.
At C:\Users\curtis.zorn\Desktop\foo.ps1:26 char:1
+ New-AzureStorageTable -Name "configuration" -Context $SAContext
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureStorageTable], AggregateException
    + FullyQualifiedErrorId : AggregateException,Microsoft.WindowsAzure.Commands.Storage.Table.Cmdlet.NewAz 
   ureStorageTableCommand
 
DEBUG: 5:39:26 PM - NewAzureStorageTableCommand end processing, Start 0 remote calls. Finish 0 remote calls. 
Elapsed time 417297.00 ms. Client operation id: Azure-Storage-PowerShell-53ffc562-78a0-4775-ae27-f9ed5e649ab9
.
DEBUG: 5:39:26 PM - NewAzureStorageTableCommand end processing.
DEBUG: 5:39:26 PM - ResolveError begin processing with ParameterSet 'LastErrorParameterSet'.
DEBUG: 5:39:26 PM - using account id '<ACCOUNT_HERE>'...

InnerException   : False
Exception        : Microsoft.WindowsAzure.Storage.StorageException: Could not load file or assembly 
                   'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or 
                   one of its dependencies. The system cannot find the file specified. ---> 
                   System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, 
                   Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its 
                   dependencies. The system cannot find the file specified.
                      at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpWebRequestFactory.B
                   uildRequestForTableOperation(Uri uri, UriQueryBuilder builder, IBufferManager 
                   bufferManager, Nullable`1 timeout, TableOperation operation, Boolean useVersionHeader, 
                   OperationContext ctx, TableRequestOptions options)
                      at Microsoft.WindowsAzure.Storage.Table.TableOperation.<>c__DisplayClass4.<InsertImpl>
                   b__1(Uri uri, UriQueryBuilder builder, Nullable`1 timeout, Boolean useVersionHeader, 
                   OperationContext ctx)
                      at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ProcessStartOfRequest[T](Exec
                   utionState`1 executionState, String startLogMessage)
                      at 
                   Microsoft.WindowsAzure.Storage.Core.Executor.Executor.InitRequest[T](ExecutionState`1 
                   executionState)
                      --- End of inner exception stack trace ---
                      at 
                   Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult 
                   result)
                      at Microsoft.WindowsAzure.Storage.Table.CloudTable.EndCreateIfNotExists(IAsyncResult 
                   asyncResult)
                      at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass2`1.<Crea
                   teCallback>b__0(IAsyncResult ar)
                   Request Information
                   RequestID:
                   RequestDate:
                   StatusMessage:
                   ErrorCode:
                   
Message          : Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, 
                   PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the 
                   file specified.
StackTrace       :    at 
                   Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult 
                   result)
                      at Microsoft.WindowsAzure.Storage.Table.CloudTable.EndCreateIfNotExists(IAsyncResult 
                   asyncResult)
                      at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass2`1.<Crea
                   teCallback>b__0(IAsyncResult ar)
HelpLink         : 
ErrorDetails     : 
ErrorCategory    : CloseError: (:) [New-AzureStorageTable], AggregateException
InvocationInfo   : System.Management.Automation.InvocationInfo
ScriptStackTrace : at <ScriptBlock>, C:\Users\curtis.zorn\Desktop\foo.ps1: line 26


InnerException   : False
Exception        : System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, 
                   Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its 
                   dependencies. The system cannot find the file specified.
                   File name: 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, 
                   PublicKeyToken=30ad4fe6b2a6aeed'
                      at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpWebRequestFactory.B
                   uildRequestForTableOperation(Uri uri, UriQueryBuilder builder, IBufferManager 
                   bufferManager, Nullable`1 timeout, TableOperation operation, Boolean useVersionHeader, 
                   OperationContext ctx, TableRequestOptions options)
                      at Microsoft.WindowsAzure.Storage.Table.TableOperation.<>c__DisplayClass4.<InsertImpl>
                   b__1(Uri uri, UriQueryBuilder builder, Nullable`1 timeout, Boolean useVersionHeader, 
                   OperationContext ctx)
                      at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ProcessStartOfRequest[T](Exec
                   utionState`1 executionState, String startLogMessage)
                      at 
                   Microsoft.WindowsAzure.Storage.Core.Executor.Executor.InitRequest[T](ExecutionState`1 
                   executionState)
                   
                   WRN: Assembly binding logging is turned OFF.
                   To enable assembly bind failure logging, set the registry value 
                   [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
                   Note: There is some performance penalty associated with assembly bind failure logging.
                   To turn this feature off, remove the registry value 
                   [HKLM\Software\Microsoft\Fusion!EnableLog].
                   
Message          : Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, 
                   PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the 
                   file specified.
StackTrace       :    at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpWebRequestFactory.B
                   uildRequestForTableOperation(Uri uri, UriQueryBuilder builder, IBufferManager 
                   bufferManager, Nullable`1 timeout, TableOperation operation, Boolean useVersionHeader, 
                   OperationContext ctx, TableRequestOptions options)
                      at Microsoft.WindowsAzure.Storage.Table.TableOperation.<>c__DisplayClass4.<InsertImpl>
                   b__1(Uri uri, UriQueryBuilder builder, Nullable`1 timeout, Boolean useVersionHeader, 
                   OperationContext ctx)
                      at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ProcessStartOfRequest[T](Exec
                   utionState`1 executionState, String startLogMessage)
                      at 
                   Microsoft.WindowsAzure.Storage.Core.Executor.Executor.InitRequest[T](ExecutionState`1 
                   executionState)
HelpLink         : 
ErrorDetails     : 
ErrorCategory    : CloseError: (:) [New-AzureStorageTable], AggregateException
InvocationInfo   : System.Management.Automation.InvocationInfo
ScriptStackTrace : at <ScriptBlock>, C:\Users\curtis.zorn\Desktop\foo.ps1: line 26

DEBUG: AzureQoSEvent: CommandName - Resolve-AzureRmError; IsSuccess - True; Duration - 00:00:00.0591023; Exce
ption - ;
DEBUG: Finish sending metric.
DEBUG: 5:39:27 PM - ResolveError end processing.
DEBUG: 5:39:27 PM - ResolveError end processing.
```

NOTE: See picture attached. v10.x of ```Newtonsoft.JSON``` is within ```Azure.Storage``` locally.
![newtonsoft](https://user-images.githubusercontent.com/8892871/40207483-534046c4-59fa-11e8-8000-97905c163ef4.png)

**Comment by blueww** [comment] 2018-05-18 01:36
@thezero 

I can't repro the issue on my machine. Seems there's some problem in you machine with the module load.
Would you please run following command and show the result when get the issue reproed?
`get-module -Name Azure* | format-table name,version,path`

And would you please check if there's some dll with following name in current folder when you run the command.
Microsoft.WindowsAzure.Commands.Storage.dll
Microsoft.WindowsAzure.Storage.dll
Newtonsoft.Json.dll

Besides that, you don't need to extract the account key and create the storage context after you set the current storage account. Since after you set current storage account, all you storage dataplane cmdlets without -Context will use the current account context.
So you can simlipy the script as:

```Powershell
Connect-AzureRmAccount 
Set-AzureRmCurrentStorageAccount -ResourceGroupName $ResourceGroupName -Name $StorageAccountName
New-AzureStorageTable -Name "configuration" 
···

**Comment by andyk1989** [comment] 2018-05-18 13:34
I was able to reproduce on Windows 10 Version 1803 with AzureRM 6.0.1.

```
PS C:\git\test> Get-Module -ListAvailable *Azure*


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.5.1      Azure.AnalysisServices              {Add-AzureAnalysisServicesAccount, Restart-AzureAnalysisSe...
Script     4.3.0      Azure.Storage                       {Get-AzureStorageTable, New-AzureStorageTableSASToken, New...
Script     6.0.1      AzureRM
Script     0.6.7      AzureRM.AnalysisServices            {Resume-AzureRmAnalysisServicesServer, Suspend-AzureRmAnal...
Script     6.0.0      AzureRM.ApiManagement               {Add-AzureRmApiManagementRegion, Get-AzureRmApiManagementS...
Script     0.1.4      AzureRM.ApplicationInsights         {Get-AzureRmApplicationInsights, New-AzureRmApplicationIns...
Script     5.0.0      AzureRM.Automation                  {Get-AzureRMAutomationHybridWorkerGroup, Get-AzureRmAutoma...
Script     4.0.5      AzureRM.Backup                      {Backup-AzureRmBackupItem, Enable-AzureRmBackupContainerRe...
Script     4.0.7      AzureRM.Batch                       {Remove-AzureRmBatchAccount, Get-AzureRmBatchAccount, Get-...
Script     0.14.2     AzureRM.Billing                     {Get-AzureRmBillingInvoice, Get-AzureRmBillingPeriod, Get-...
Script     5.0.0      AzureRM.Cdn                         {Get-AzureRmCdnProfile, Get-AzureRmCdnProfileSsoUrl, New-A...
Script     0.9.5      AzureRM.CognitiveServices           {Get-AzureRmCognitiveServicesAccount, Get-AzureRmCognitive...
Script     5.0.0      AzureRM.Compute                     {Remove-AzureRmAvailabilitySet, Get-AzureRmAvailabilitySet...
Script     0.3.2      AzureRM.Consumption                 Get-AzureRmConsumptionUsageDetail
Script     0.2.6      AzureRM.ContainerInstance           {New-AzureRmContainerGroup, Get-AzureRmContainerGroup, Rem...
Script     1.0.5      AzureRM.ContainerRegistry           {New-AzureRmContainerRegistry, Get-AzureRmContainerRegistr...
Script     5.0.0      AzureRM.DataFactories               {Remove-AzureRmDataFactory, Get-AzureRmDataFactoryRun, Get...
Script     0.5.4      AzureRM.DataFactoryV2               {Set-AzureRmDataFactoryV2, Update-AzureRmDataFactoryV2, Ge...
Script     5.0.0      AzureRM.DataLakeAnalytics           {Get-AzureRmDataLakeAnalyticsDataSource, New-AzureRmDataLa...
Script     6.0.0      AzureRM.DataLakeStore               {Get-AzureRmDataLakeStoreTrustedIdProvider, Remove-AzureRm...
Script     4.0.5      AzureRM.DevTestLabs                 {Get-AzureRmDtlAllowedVMSizesPolicy, Get-AzureRmDtlAutoShu...
Script     5.0.0      AzureRM.Dns                         {Get-AzureRmDnsRecordSet, New-AzureRmDnsRecordConfig, Remo...
Script     0.3.3      AzureRM.EventGrid                   {New-AzureRmEventGridTopic, Get-AzureRmEventGridTopic, Set...
Script     0.6.4      AzureRM.EventHub                    {New-AzureRmEventHubNamespace, Get-AzureRmEventHubNamespac...
Script     4.1.3      AzureRM.HDInsight                   {Get-AzureRmHDInsightJob, New-AzureRmHDInsightSqoopJobDefi...
Script     5.0.0      AzureRM.Insights                    {Get-AzureRmMetricDefinition, Get-AzureRmMetric, Remove-Az...
Script     3.1.3      AzureRM.IotHub                      {Add-AzureRmIotHubKey, Get-AzureRmIotHubEventHubConsumerGr...
Script     5.0.0      AzureRM.KeyVault                    {Add-AzureKeyVaultCertificate, Update-AzureKeyVaultCertifi...
Script     4.0.4      AzureRM.LogicApp                    {Get-AzureRmIntegrationAccountAgreement, Get-AzureRmIntegr...
Script     0.18.0     AzureRM.MachineLearning             {Move-AzureRmMlCommitmentAssociation, Get-AzureRmMlCommitm...
Script     0.4.3      AzureRM.MachineLearningCompute      {Get-AzureRmMlOpCluster, Get-AzureRmMlOpClusterKey, Test-A...
Script     0.2.2      AzureRM.MarketplaceOrdering         {Get-AzureRmMarketplaceTerms, Set-AzureRmMarketplaceTerms}
Script     0.10.0     AzureRM.Media                       {Sync-AzureRmMediaServiceStorageKeys, Set-AzureRmMediaServ...
Script     6.0.0      AzureRM.Network                     {Add-AzureRmApplicationGatewayAuthenticationCertificate, G...
Script     5.0.0      AzureRM.NotificationHubs            {Get-AzureRmNotificationHub, Get-AzureRmNotificationHubAut...
Script     5.0.0      AzureRM.OperationalInsights         {New-AzureRmOperationalInsightsAzureActivityLogDataSource,...
Script     4.1.5      AzureRM.PowerBIEmbedded             {Remove-AzureRmPowerBIWorkspaceCollection, Get-AzureRmPowe...
Script     5.0.1      AzureRM.profile                     {Disable-AzureRmDataCollection, Disable-AzureRmContextAuto...
Script     4.1.3      AzureRM.RecoveryServices            {Get-AzureRmRecoveryServicesBackupProperty, Get-AzureRmRec...
Script     4.1.3      AzureRM.RecoveryServices.Backup     {Backup-AzureRmRecoveryServicesBackupItem, Get-AzureRmReco...
Script     0.2.5      AzureRM.RecoveryServices.SiteRec... {Edit-AzureRmRecoveryServicesAsrRecoveryPlan, Get-AzureRmR...
Script     5.0.0      AzureRM.RedisCache                  {Remove-AzureRmRedisCachePatchSchedule, New-AzureRmRedisCa...
Script     0.3.4      AzureRM.Relay                       {New-AzureRmRelayNamespace, Get-AzureRmRelayNamespace, Set...
Script     6.0.0      AzureRM.Resources                   {Get-AzureRmProviderOperation, Remove-AzureRmRoleAssignmen...
Script     0.16.4     AzureRM.Scheduler                   {Disable-AzureRmSchedulerJobCollection, Enable-AzureRmSche...
Script     0.6.5      AzureRM.ServiceBus                  {New-AzureRmServiceBusNamespace, Get-AzureRmServiceBusName...
Script     0.3.5      AzureRM.ServiceFabric               {Add-AzureRmServiceFabricApplicationCertificate, Add-Azure...
Script     4.4.1      AzureRM.Sql                         {Get-AzureRmSqlDatabaseTransparentDataEncryption, Get-Azur...
Script     5.0.0      AzureRM.Storage                     {Get-AzureRmStorageAccount, Get-AzureRmStorageAccountKey, ...
Script     4.0.5      AzureRM.StreamAnalytics             {Get-AzureRmStreamAnalyticsFunction, Get-AzureRmStreamAnal...
Script     4.0.2      AzureRM.Tags                        {Remove-AzureRmTag, Get-AzureRmTag, New-AzureRmTag}
Script     4.0.4      AzureRM.TrafficManager              {Disable-AzureRmTrafficManagerEndpoint, Enable-AzureRmTraf...
Script     4.0.3      AzureRM.UsageAggregates             Get-UsageAggregates
Script     5.0.1      AzureRM.Websites                    {Get-AzureRmAppServicePlan, Set-AzureRmAppServicePlan, New...


PS C:\git\test> Set-AzureRmCurrentStorageAccount -ResourceGroupName $rg -Name $saName
saName
PS C:\git\test> New-AzureStorageTable -Name "testTable"
New-AzureStorageTable : Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral,
PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
At line:1 char:1
+ New-AzureStorageTable -Name "testTable"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureStorageTable], StorageException
    + FullyQualifiedErrorId : StorageException,Microsoft.WindowsAzure.Commands.Storage.Table.Cmdlet.NewAzureStorageTab
   leCommand

```

This is a regression since AzureRM v5.7.0 as the command `New-AzureStorageTable -Name "testTable"` works on that version.

**Comment by theczorn** [comment] 2018-05-18 16:51
> 
    1. Remove any previous installations of Microsoft Azure PowerShell from the 'Add/Remove programs' control panel
    2. Remove all Azure* modules from %Program Files%\WindowsPowerShell\Modules
    3. Run: Install-Module -Name AzureRM -Repository PSGallery -Force

@blueww Before creating this issue report I had attempted the steps you listed above^
Not seeing any change in behaviour.

```get-module -Name Azure* | format-table name,version,path```
returns
```powershell
Name            Version Path                                                                                 
----            ------- ----                                                                                 
Azure.Storage   4.2.1   C:\Program Files\WindowsPowerShell\Modules\Azure.Storage\4.2.1\Azure.Storage.psm1    
AzureRM.profile 5.0.1   C:\Program Files\WindowsPowerShell\Modules\AzureRM.profile\5.0.1\AzureRM.Profile.psm1
AzureRM.Storage 5.0.0   C:\Program Files\WindowsPowerShell\Modules\AzureRM.Storage\5.0.0\AzureRM.Storage.psm1
```

**Comment by blueww** [comment] 2018-05-22 04:11
I tried to repro it with 6.0.1, and it really repro When open a new PowerShell Console, and run 

```powershell
Connect-AzureRmAccount 
Set-AzureRmCurrentStorageAccount -ResourceGroupName $ResourceGroupName -Name $StorageAccountName
New-AzureStorageTable -Name "configuration" 
```


After I see the module and assembly, only the json dll from AzureRm.Profile is loaded:
```
PS C:\WINDOWS\system32> [appdomain]::currentdomain.getassemblies() | Where-Object {$_.location -like "*JSON*"}

GAC    Version        Location                                                                                                                                       
---    -------        --------                                                                                                                                       
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\AzureRM.profile\5.0.1\Newtonsoft.Json.dll
```

While all 3 module are loaded:

```
PS C:\WINDOWS\system32> get-module -Name Azure* | format-table name,version,path

Name            Version Path                                                                                 
----            ------- ----                                                                                 
Azure.Storage   4.3.0   C:\Program Files\WindowsPowerShell\Modules\Azure.Storage\4.3.0\Azure.Storage.psm1    
AzureRM.profile 5.0.1   C:\Program Files\WindowsPowerShell\Modules\AzureRM.profile\5.0.1\AzureRM.Profile.psm1
AzureRM.Storage 5.0.0   C:\Program Files\WindowsPowerShell\Modules\AzureRM.Storage\5.0.0\AzureRM.Storage.psm1
```


But if I run "New-AzureStorageTable" first (althrough it will fail since no context), then run the script, it can success.
```powershell

New-AzureStorageTable -name test1 # will fail

Connect-AzureRmAccount 
Set-AzureRmCurrentStorageAccount -ResourceGroupName $ResourceGroupName -Name $StorageAccountName
New-AzureStorageTable -Name "configuration"  #will success
```

And the module not change, but the assembly will change 

```
PS C:\WINDOWS\system32>  [appdomain]::currentdomain.getassemblies() | Where-Object {$_.location -like "*JSON*"}

GAC    Version        Location                                                                                                                                       
---    -------        --------                                                                                                                                       
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\AzureRM.Profile\5.0.1\Newtonsoft.Json.dll                                                           
False  v4.0.30319     C:\Program Files\WindowsPowerShell\Modules\Azure.Storage\4.3.0\Newtonsoft.Json.dll 
```

And after I install the latest AzureRm.preview module, the issue not repro, this should be related with the Newtonsoft.Json.dll referenced by latest AzureRm.preview 5.0.2 is changed from 10.0.02 to 6.0.8.

So there are 2 workarounds (you can choose any):
1. Run a table cmdlet at begin of the session, like New-AzureStorageTable -name test1, altrhough it will fail.
2. install the latest AzureRm.Storage preview module

`Install-Module AzureRM.Storage –Repository PSGallery -RequiredVersion 5.0.2-preview –AllowPrerelease –AllowClobber –Force`


I will try to merge the fix to official PowerShell build in the next release.

**Comment by theczorn** [comment] 2018-05-22 04:58
@blueww Thank you for following up. I'll try those workarounds out and see if I can't reach a solution.

Sincerely,

CZ

**Comment by danbyrne** [comment] 2018-05-26 06:42
Hi @blueww,
I am having the same problem as originally described by @theczorn.
On the machine we are running these scripts, I am unable to use PowerShellGet, so I cannot try workaround#2.
I was able to successfully use workaround #1, although in a different order (only because we are not explicitly calling Connect-AzureRmAccount directly, as this is running within Octopus Deploy):

#(Implicitly called -> Connect-AzureRmAccount)
try {
  New-AzureStorageTable -name test1 # will fail
} catch {}
Set-AzureRmCurrentStorageAccount -ResourceGroupName $ResourceGroupName -Name $StorageAccountName
New-AzureStorageTable -Name "configuration"  #will success

Many thanks for your help on this issue - I hope it will be patched and released in a future AzureRM release soon.

**Comment by blueww** [comment] 2018-05-28 06:55
@danbyrne  Good to know that you workaround this issue.
But it seems the fix of issue not work as I expected, so I need more time to discuss the issue with OneSDK team to get a fix for it.

@markcowl , @cormacpayne 
This issue not happen on Powershell 5.7.0, but happen on Powershell 6.0.0. 
Since Storage Team don't have any code change after 5.7.0, this should be caused by some change from framework or other teams. Would you please help to look?

**Comment by markcowl** [comment] 2018-05-29 19:04
@danbyrne @cormacpayne @blueww This is unfortunately a known issue, that is due to be fixed this release #6313 . It has to do with the order of loading modules.

There are a couple of known workarounds:

- Import Azure.Storage *first* in your session (```Import-Module Azure.Storage```)
- If running in a script, use #Requires to load modules in the proper order
```powershell
#Requires -Modules Azure.Storage, AzureRM.Storage
Get-AzureRmStorageAccount | Get-AzureStorageTable
```

Closing this as a duplicate of #6313

**Closed by markcowl** 2018-05-29 19:04 UTC
Labels: Storage

**Comment by blueww** [comment] 2018-06-04 05:02
Thanks @markcowl  and @cormacpayne  help to fix this!
I have verified the RC of 6.2.0 and the issue is fixed.

**Comment by blueww** [comment] 2018-06-04 05:03
on-Demand: https://azuresdkci.westus2.cloudapp.azure.com/job/powershell-demand/904/

**Comment by anils1974** [comment] 2018-06-07 00:55
Where can I find this new release candidate of version 6.2.0. When I try to install this specific version of azureRM.storage, it throws. I checked at powershellgallery.com too and the latest version available there is 5.0.3. Please help.

**Comment by blueww** [comment] 2018-06-07 02:07
The latest PowerShell version which have this resolve can be found in https://github.com/Azure/azure-powershell/releases/tag/v6.2.1-June2018

**Comment by ThmsRynr** [comment] 2018-11-02 20:36
I'm writing a compiled cmdlet and getting the same error. Running `import-module azure.storage, azurerm.storage` after importing my module (just the path to the dll), and before running my cmdlet worked around it. Is there something more elegant you can recommend? 

Do I need to do something weird like re-order my `using` statements? Right now they read like this. 
```
using System.Configuration;
using System.Management.Automation;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Azure.KeyVault;
using Microsoft.IdentityModel.Clients.ActiveDirectory;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Auth;
using Microsoft.WindowsAzure.Storage.Blob;
```

The code uses a key from key vault to upload an encrypted blob to Azure storage.

cc @udubnate

**Comment by blueww** [comment] 2018-11-08 06:34
@ThmsRynr 
I don't have any idea how to resolve the Json issue in your cmldet. And I don't see what's the detail error  and don't quite understand the detail repro steps in your comments.

Since this might be a different issue of the original issue, you might can open a new issue for it with detail information.
