### ISSUE TITLE
Cant find Get-AzureResourceProviderLog

### ISSUE THREAD

**Issue by eosfor** [Azure/azure-powershell#2004] opened 2016-03-24 11:02 UTC
Cant find Get-AzureResourceProviderLog

[Here is the output](https://gist.github.com/eosfor/21dc8867cde7f0fe7114)

**Comment by ravbhatnagar** [comment] 2016-03-28 18:47
During the 1.0 PS release, a bunch of the log cmdlets were consolidated. So now you can use Get-AzureRmLog -ResourceProvider to get the desired results.

**Comment by ravbhatnagar** [comment] 2016-03-28 18:47
Closing (by design).

**Closed by ravbhatnagar** 2016-03-28 18:47 UTC
Labels: ResourceManager
