### ISSUE TITLE
Calling Get-AzureRmKeyVault with -Tag @{} parameter returns an object with empty Tags property

### ISSUE THREAD

**Issue by Blackbaud-ShaydeNofziger** [Azure/azure-powershell#5159] opened 2017-12-18 14:19 UTC
### Cmdlet(s)
Get-AzureRmKeyVault

### PowerShell Version
5.1.14393.1884

### Module Version
AzureRm - 5.1.1
AzureRm.KeyVault - 4.0.1

### OS Version
10.0.14393.1884

### Description
The KeyVault object returned by calling Get-AzureRmKeyVault varies based on which parameter set is used. In some cases, the Tags property is missing its tags.

### Debug Output
Lots of sensitive info in these results. I'll have to clean this up and redact data separately, for now, calls and example output are below

### Script/Steps for Reproduction
```powershell
PS > Get-AzureRmKeyVault -Name 'VAULT_NAME'

Vault Name                       : VAULT_NAME
Resource Group Name              : VAULT_RESOURCE_GROUP_NAME
Location                         : eastus2
Resource ID                      : RESOURCE_ID
Vault URI                        : https://VAULT_NAME.vault.azure.net/
Tenant ID                        : TENANT_ID
SKU                              : Standard
Access Policies                  :
                                   REDACTED


Tags                             :
                                   Name                           Value
                                   =============================  ========
                                   RoleCode                       CRD
                                   ...
                                   ProductCode                    OPS
                                   Group                          1

PS > Get-AzureRmKeyVault -Tag @{ ProductCode ='OPS' }

Vault Name          : VAULT_NAME
Resource Group Name : VAULT_RESOURCE_GROUP_NAME
Location            : eastus2
Resource ID         :  RESOURCE_ID
Tags                :

```

**Comment by maddieclayton** [comment] 2017-12-19 01:17
@RandalliLama @dragav Can you take a look?

**Comment by cormacpayne** [comment] 2018-03-22 23:01
@vivsriaus Hey Vivek, it looks like this issue stems from the underlying ARM API; I'm able to reproduce the same thing when I use `Find-AzureRmResource`:

```powershell
PS C:\> Find-AzureRmResource -Name kv-test

Name              : kv-test
ResourceId        : /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/testrg/providers/Microsoft.KeyVault/vaults/kv-test
ResourceName      : kv-test
ResourceType      : Microsoft.KeyVault/vaults
ResourceGroupName : testrg
Location          : westus
SubscriptionId    : xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Tags              : {key}

PS C:\> Find-AzureRmResource -Tag @{"key" = $null}

Name              : kv-test
ResourceId        : /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/testrg/providers/Microsoft.KeyVault/vaults/kv-test
ResourceName      : kv-test
ResourceType      : Microsoft.KeyVault/vaults
ResourceGroupName : testrg
Location          : westus
SubscriptionId    : xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

It seems that the response is different when sending a request with a filter containing "name" and a filter containing "tagname". Is this a known issue?

**Comment by cormacpayne** [comment] 2018-05-02 21:14
@maddieclayton this has been resolved in the latest changes to `Get-AzureRmResource`, so we should look into updating the ARM call that KeyVault is using to get the above information for `Get-AzureRmKeyVault`

**Comment by cormacpayne** [comment] 2018-05-21 23:31
@maddieclayton 

https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Resource/GetAzureResourceCmdlet.cs#L191-L199

**Comment by maddieclayton** [comment] 2018-06-12 17:31
Fixed.

**Closed by maddieclayton** 2018-06-12 17:31 UTC
Labels: Key Vault
