### ISSUE TITLE
Webapp:Set-AzWebApp doesn't update app settings of App service

### ISSUE THREAD

**Issue by sadomovalex** [Azure/azure-powershell#15078] opened 2021-05-21 11:31 UTC
## Description

Can't update app settings of App service via Set-AzWebApp.

## Steps to reproduce

```powershell
$app = Get-AzWebApp -Name "MyAppService" -ResourceGroupName "MyResourceGroup"

$appSettingsCurrent = $app.SiteConfig.AppSettings
# copy existing app settings
$appSettingsNew = @{}
foreach ($kvp in $appSettingsCurrent) {
	$appSettingsNew[$kvp.Name] = $kvp.Value
}
# add new settings
$appSettingsNew["foo"] = "bar"

Set-AzWebApp -Name "MyAppService" -ResourceGroupName "MyResourceGroup" -AppSettings $appSettingsNew
```

After this script we expect that app settings will contain "foo" setting with value "bar", but it doesn't - it contains only those app settings which were in place before running the script.
Earlier it worked with Set-AzWebApp from Az (reproduced with Az 5.6.0 and 5.9.0). Note that similar code but using Set-AzureRMWebApp from AzureRM (6.9.0) works and new app setting got saved to App service:

```powershell
$app = Get-AzureRMWebApp -Name "MyAppService" -ResourceGroupName "MyResourceGroup"

$appSettingsCurrent = $app.SiteConfig.AppSettings
# copy existing app settings
$appSettingsNew = @{}
foreach ($kvp in $appSettingsCurrent) {
	$appSettingsNew[$kvp.Name] = $kvp.Value
}
# add new settings
$appSettingsNew["SomeNewSetting"] = "foo"

Set-AzureRMWebApp -Name "MyAppService" -ResourceGroupName "MyResourceGroup" -AppSettings $appSettingsNew
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.18362.1474
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.1474
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

```powershell
ModuleType Version    Name
---------- -------    ----
Script     2.2.8      Az.Accounts
Script     2.2.7      Az.Accounts
Script     2.2.6      Az.Accounts
Script     1.1.1      Az.Advisor
Script     2.1.0      Az.Aks
Script     2.0.2      Az.Aks
Script     1.1.4      Az.AnalysisServices
Script     2.2.0      Az.ApiManagement
Script     1.0.0      Az.AppConfiguration
Script     1.1.0      Az.ApplicationInsights
Script     1.7.0      Az.Automation
Script     1.5.0      Az.Automation
Script     3.1.0      Az.Batch
Script     2.0.0      Az.Billing
Script     1.7.0      Az.Cdn
Script     1.6.0      Az.Cdn
Script     1.8.0      Az.CognitiveServices
Script     4.12.0     Az.Compute
Script     4.10.0     Az.Compute
Script     1.0.3      Az.ContainerInstance
Script     2.2.2      Az.ContainerRegistry
Script     2.2.1      Az.ContainerRegistry
Script     1.1.0      Az.CosmosDB
Script     1.1.0      Az.DataBoxEdge
Script     1.1.0      Az.Databricks
Script     1.12.0     Az.DataFactory
Script     1.11.4     Az.DataFactory
Script     1.0.2      Az.DataLakeAnalytics
Script     1.3.0      Az.DataLakeStore
Script     1.0.0      Az.DataShare
Script     1.1.0      Az.DeploymentManager
Script     2.1.1      Az.DesktopVirtualization
Script     1.0.2      Az.DevTestLabs
Script     1.1.2      Az.Dns
Script     1.3.0      Az.EventGrid
Script     1.7.2      Az.EventHub
Script     1.7.1      Az.EventHub
Script     1.8.0      Az.FrontDoor
Script     1.7.0      Az.FrontDoor
Script     2.0.0      Az.Functions
Script     4.2.1      Az.HDInsight
Script     4.2.0      Az.HDInsight
Script     1.3.1      Az.HealthcareApis
Script     1.2.0      Az.HealthcareApis
Script     2.7.3      Az.IotHub
Script     2.7.2      Az.IotHub
Script     3.4.3      Az.KeyVault
Script     3.4.0      Az.KeyVault
Script     1.0.1      Az.Kusto
Script     1.5.0      Az.LogicApp
Script     1.1.3      Az.MachineLearning
Script     1.1.0      Az.Maintenance
Script     2.0.0      Az.ManagedServices
Script     1.0.2      Az.MarketplaceOrdering
Script     1.1.1      Az.Media
Script     1.0.1      Az.Migrate
Script     1.0.0      Az.Migrate
Script     2.5.0      Az.Monitor
Script     2.4.0      Az.Monitor
Script     4.7.0      Az.Network
Script     4.6.0      Az.Network
Script     1.1.1      Az.NotificationHubs
Script     2.3.0      Az.OperationalInsights
Script     1.4.1      Az.PolicyInsights
Script     1.1.2      Az.PowerBIEmbedded
Script     1.0.3      Az.PrivateDns
Script     3.6.0      Az.RecoveryServices
Script     3.4.1      Az.RecoveryServices
Script     1.4.0      Az.RedisCache
Script     1.0.0      Az.RedisEnterpriseCache
Script     1.0.3      Az.Relay
Script     1.0.0      Az.ResourceMover
Script     3.5.0      Az.Resources
Script     3.3.0      Az.Resources
Script     1.5.0      Az.ServiceBus
Script     1.4.1      Az.ServiceBus
Script     2.4.0      Az.ServiceFabric
Script     2.2.2      Az.ServiceFabric
Script     1.2.0      Az.SignalR
Script     2.17.1     Az.Sql
Script     2.16.0     Az.Sql
Script     1.1.0      Az.SqlVirtualMachine
Script     3.6.0      Az.Storage
Script     3.4.0      Az.Storage
Script     1.4.0      Az.StorageSync
Script     1.1.0      Az.StreamAnalytics
Script     1.0.1      Az.StreamAnalytics
Script     1.0.0      Az.Support
Script     1.0.4      Az.TrafficManager
Script     2.5.0      Az.Websites
Script     2.4.0      Az.Websites
Manifest   2.1.0      AzTable
Script     5.1.2      Azure
Script     0.5.4      Azure.AnalysisServices
Manifest   0.5.0      Azure.AnalysisServices
Script     4.6.1      Azure.Storage
Script     4.6.0      Azure.Storage
Script     4.2.1      Azure.Storage
Binary     2.0.2.130  AzureAD
Binary     2.0.2.4    AzureAD
Binary     2.0.2.129  AzureADPreview
Script     6.13.1     AzureRM
Script     6.9.0      AzureRM
Script     5.7.0      AzureRM
Script     0.6.14     AzureRM.AnalysisServices
Script     0.6.6      AzureRM.AnalysisServices
Script     6.1.7      AzureRM.ApiManagement
Script     6.1.5      AzureRM.ApiManagement
Script     5.1.2      AzureRM.ApiManagement
Script     0.1.8      AzureRM.ApplicationInsights
Script     0.1.3      AzureRM.ApplicationInsights
Script     6.1.1      AzureRM.Automation
Script     5.1.1      AzureRM.Automation
Script     4.3.2      AzureRM.Automation
Script     4.0.11     AzureRM.Backup
Script     4.0.10     AzureRM.Backup
Script     4.0.4      AzureRM.Backup
Script     4.1.5      AzureRM.Batch
Script     4.0.6      AzureRM.Batch
Script     0.14.6     AzureRM.Billing
Script     0.14.1     AzureRM.Billing
Script     5.0.6      AzureRM.Cdn
Script     4.2.2      AzureRM.Cdn
Script     0.9.12     AzureRM.CognitiveServices
Script     0.9.10     AzureRM.CognitiveServices
Script     0.9.4      AzureRM.CognitiveServices
Script     5.9.1      AzureRM.Compute
Script     5.6.0      AzureRM.Compute
Script     4.6.0      AzureRM.Compute
Script     0.3.7      AzureRM.Consumption
Script     0.3.1      AzureRM.Consumption
Script     0.2.12     AzureRM.ContainerInstance
Script     0.2.10     AzureRM.ContainerInstance
Script     0.2.5      AzureRM.ContainerInstance
Script     1.0.10     AzureRM.ContainerRegistry
Script     1.0.4      AzureRM.ContainerRegistry
Script     5.0.3      AzureRM.DataFactories
Script     4.2.2      AzureRM.DataFactories
Script     0.5.11     AzureRM.DataFactoryV2
Script     0.5.10     AzureRM.DataFactoryV2
Script     0.5.3      AzureRM.DataFactoryV2
Script     5.1.4      AzureRM.DataLakeAnalytics
Script     4.2.3      AzureRM.DataLakeAnalytics
Script     6.2.1      AzureRM.DataLakeStore
Script     6.1.2      AzureRM.DataLakeStore
Script     5.2.0      AzureRM.DataLakeStore
Script     4.0.9      AzureRM.DevTestLabs
Script     4.0.4      AzureRM.DevTestLabs
Script     5.1.0      AzureRM.Dns
Script     4.1.2      AzureRM.Dns
Script     0.3.7      AzureRM.EventGrid
Script     0.3.2      AzureRM.EventGrid
Script     0.7.0      AzureRM.EventHub
Script     0.6.10     AzureRM.EventHub
Script     0.6.3      AzureRM.EventHub
Script     4.1.8      AzureRM.HDInsight
Script     4.1.2      AzureRM.HDInsight
Script     5.1.5      AzureRM.Insights
Script     5.1.4      AzureRM.Insights
Script     4.0.4      AzureRM.Insights
Script     3.1.8      AzureRM.IotHub
Script     3.1.2      AzureRM.IotHub
Script     5.2.1      AzureRM.KeyVault
Script     4.3.0      AzureRM.KeyVault
Script     4.1.4      AzureRM.LogicApp
Script     4.0.3      AzureRM.LogicApp
Script     0.18.5     AzureRM.MachineLearning
Script     0.17.2     AzureRM.MachineLearning
Script     0.4.8      AzureRM.MachineLearningCompute
Script     0.4.2      AzureRM.MachineLearningCompute
Script     0.2.7      AzureRM.MarketplaceOrdering
Script     0.2.5      AzureRM.MarketplaceOrdering
Script     0.2.1      AzureRM.MarketplaceOrdering
Script     0.10.4     AzureRM.Media
Script     0.9.2      AzureRM.Media
Script     6.11.1     AzureRM.Network
Script     6.8.0      AzureRM.Network
Script     5.4.2      AzureRM.Network
Script     5.0.3      AzureRM.NotificationHubs
Script     4.1.1      AzureRM.NotificationHubs
Script     5.0.6      AzureRM.OperationalInsights
Script     4.3.2      AzureRM.OperationalInsights
Script     1.1.0      AzureRM.PolicyInsights
Script     1.0.4      AzureRM.PolicyInsights
Script     4.1.10     AzureRM.PowerBIEmbedded
Script     4.1.4      AzureRM.PowerBIEmbedded
Script     5.8.2      AzureRM.Profile
Script     5.6.0      AzureRM.Profile
Script     4.6.0      AzureRM.Profile
Script     4.1.9      AzureRM.RecoveryServices
Script     4.1.8      AzureRM.RecoveryServices
Script     4.1.2      AzureRM.RecoveryServices
Script     4.5.2      AzureRM.RecoveryServices.Backup
Script     4.4.1      AzureRM.RecoveryServices.Backup
Script     4.1.2      AzureRM.RecoveryServices.Backup
Script     0.2.12     AzureRM.RecoveryServices.SiteRec...
Script     0.2.10     AzureRM.RecoveryServices.SiteRec...
Script     0.2.4      AzureRM.RecoveryServices.SiteRec...
Script     5.1.0      AzureRM.RedisCache
Script     5.0.6      AzureRM.RedisCache
Script     4.1.2      AzureRM.RedisCache
Script     0.3.12     AzureRM.Relay
Script     0.3.10     AzureRM.Relay
Script     0.3.3      AzureRM.Relay
Script     6.7.3      AzureRM.Resources
Script     6.5.0      AzureRM.Resources
Script     5.5.2      AzureRM.Resources
Script     0.16.10    AzureRM.Scheduler
Script     0.16.3     AzureRM.Scheduler
Script     4.1.2      AzureRM.ServerManagement
Script     0.6.13     AzureRM.ServiceBus
Script     0.6.12     AzureRM.ServiceBus
Script     0.6.4      AzureRM.ServiceBus
Script     0.3.15     AzureRM.ServiceFabric
Script     0.3.12     AzureRM.ServiceFabric
Script     0.3.4      AzureRM.ServiceFabric
Script     1.0.0      AzureRM.SignalR
Script     5.0.6      AzureRM.SiteRecovery
Script     4.12.1     AzureRM.Sql
Script     4.11.3     AzureRM.Sql
Script     4.4.0      AzureRM.Sql
Script     5.2.0      AzureRM.Storage
Script     5.1.0      AzureRM.Storage
Script     4.2.3      AzureRM.Storage
Script     4.0.10     AzureRM.StreamAnalytics
Script     4.0.4      AzureRM.StreamAnalytics
Script     4.0.5      AzureRM.Tags
Script     4.0.1      AzureRM.Tags
Script     4.1.3      AzureRM.TrafficManager
Script     4.1.1      AzureRM.TrafficManager
Script     4.0.3      AzureRM.TrafficManager
Script     4.0.5      AzureRM.UsageAggregates
Script     4.0.2      AzureRM.UsageAggregates
Script     5.2.0      AzureRM.Websites
Script     5.1.0      AzureRM.Websites
Script     4.2.2      AzureRM.Websites
Script     2.0.3      ExchangeOnlineManagement
Binary     16.0.21... Microsoft.Online.SharePoint.Powe...
Binary     16.0.20... Microsoft.Online.SharePoint.Powe...
Script     1.0.1      Microsoft.PowerShell.Operation.V...
Binary     1.0.0.1    PackageManagement
Script     3.4.0      Pester
Manifest   1.3.0      PnP.PowerShell
Script     1.0.0.1    PowerShellGet
Script     2.0.0      PSReadline
Binary     3.28.20... SharePointPnPPowerShellOnline
Binary     3.25.20... SharePointPnPPowerShellOnline


    Directory: C:\Windows\system32\WindowsPowerShell\v1.0\


ModuleType Version    Name
---------- -------    ----
Manifest   1.0.0.0    AppBackgroundTask
Manifest   2.0.0.0    AppLocker
Manifest   1.0.0.0    AppvClient
Manifest   2.0.1.0    Appx
Script     1.0.0.0    AssignedAccess
Manifest   1.0.0.0    BitLocker
Manifest   2.0.0.0    BitsTransfer
Manifest   1.0.0.0    BranchCache
Manifest   1.0.0.0    CimCmdlets
Manifest   1.0        ConfigCI
Manifest   1.0        Defender
Manifest   1.0.2.0    DeliveryOptimization
Manifest   1.0.0.0    DirectAccessClientComponents
Script     3.0        Dism
Manifest   1.0.0.0    DnsClient
Manifest   1.0.0.0    EventTracingManagement
Manifest   2.0.0.0    International
Manifest   1.0.0.0    iSCSI
Script     1.0.0.0    ISE
Manifest   1.0.0.0    Kds
Manifest   1.0.1.0    Microsoft.PowerShell.Archive
Manifest   3.0.0.0    Microsoft.PowerShell.Diagnostics
Manifest   3.0.0.0    Microsoft.PowerShell.Host
Manifest   1.0.0.0    Microsoft.PowerShell.LocalAccounts
Manifest   3.1.0.0    Microsoft.PowerShell.Management
Script     1.0        Microsoft.PowerShell.ODataUtils
Manifest   3.0.0.0    Microsoft.PowerShell.Security
Manifest   3.1.0.0    Microsoft.PowerShell.Utility
Manifest   3.0.0.0    Microsoft.WSMan.Management
Script     1.0        MicrosoftGraph
Manifest   1.0        MMAgent
Manifest   1.0.0.0    MsDtc
Manifest   2.0.0.0    NetAdapter
Manifest   1.0.0.0    NetConnection
Manifest   1.0.0.0    NetEventPacketCapture
Manifest   2.0.0.0    NetLbfo
Manifest   1.0.0.0    NetNat
Manifest   2.0.0.0    NetQos
Manifest   2.0.0.0    NetSecurity
Manifest   1.0.0.0    NetSwitchTeam
Manifest   1.0.0.0    NetTCPIP
Manifest   1.0.0.0    NetworkConnectivityStatus
Manifest   1.0.0.0    NetworkSwitchManager
Manifest   1.0.0.0    NetworkTransition
Manifest   1.0.0.0    PcsvDevice
Binary     1.0.0.0    PersistentMemory
Manifest   1.0.0.0    PKI
Manifest   1.0.0.0    PnpDevice
Manifest   1.1        PrintManagement
Binary     1.0.11     ProcessMitigations
Script     3.0        Provisioning
Manifest   1.1        PSDesiredStateConfiguration
Script     1.0.0.0    PSDiagnostics
Binary     1.1.0.0    PSScheduledJob
Manifest   2.0.0.0    PSWorkflow
Manifest   1.0.0.0    PSWorkflowUtility
Manifest   1.0.0.0    ScheduledTasks
Manifest   2.0.0.0    SecureBoot
Manifest   2.0.0.0    SmbShare
Manifest   2.0.0.0    SmbWitness
Manifest   1.0.0.0    StartLayout
Manifest   2.0.0.0    Storage
Manifest   1.0.0.0    StorageBusCache
Manifest   2.0.0.0    TLS
Manifest   1.0.0.0    TroubleshootingPack
Manifest   2.0.0.0    TrustedPlatformModule
Binary     2.1.639.0  UEV
Manifest   2.0.0.0    VpnClient
Manifest   1.0.0.0    Wdac
Manifest   2.0.0.0    Whea
Manifest   1.0.0.0    WindowsDeveloperLicense
Script     1.0        WindowsErrorReporting
Manifest   1.0.0.0    WindowsSearch
Manifest   1.0.0.0    WindowsUpdate
Manifest   1.0.0.2    WindowsUpdateProvider

```

**Comment by tonkon** [comment] 2021-05-21 12:25
Encountered same issue today. It can be reproduced in AZ 4.3 and 5.9.

```powershell
$appSettings = @{
    Key1 = "Value1"
}

Set-AzWebApp -ResourceGroupName "MyResourceGroup" -Name "MyAppService" -AppSettings $appSettings  -Verbose
```

**Comment by Kotasudhakarreddy** [comment] 2021-05-21 14:56
Duplicate of #14998

**Comment by Kotasudhakarreddy** [comment] 2021-05-25 17:09
Hi Fix is available in the latest `Az.websites` module. You can update your modules to latest one using `update-module -Name "Az.Websites"`. Please check and let us know the status. Thanks!

**Comment by Kotasudhakarreddy** [comment] 2021-05-26 09:40
Closing this since the deployment of the fix is complete.

**Closed by Kotasudhakarreddy** 2021-05-26 09:40 UTC
Labels: App Services, Service Attention, customer-reported, question
