### ISSUE TITLE
Get-AzureRmResource Parameter Sets broken

### ISSUE THREAD

**Issue by QuasarSE** [Azure/azure-powershell#2618] opened 2016-07-15 15:32 UTC
`Get-AzureRmResource` doesn't work for retrieving all the resources in a given RG.  e.g. 

```
       Get-AzureRmResource -ResourceGroupName anExistingRG
```

yields:

```
Get-AzureRmResource : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Get-AzureRmResource -ResourceGroupName anExistingRG
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-AzureRmResource], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet
```

Which should work as it's example 2 in the help for this cmdlet. :-)

Typo in the `Get-Help` text as well:<br/>_If you find an issue . . . with a **lable** "ResourceManager"._
vs.<br/>_If you find an issue . . . with a **label** "ResourceManager"._

**Comment by QuasarSE** [comment] 2016-07-15 15:35
Looks like #2605 -- but can't be "by design" since it's even an example from the cmdlet's help.

**Comment by gandhiniraj** [comment] 2016-07-18 18:04
@QuasarSE thanks for reporting, will investigate the parameter set issue. 
Fixed the typo (will be in next release)

**Comment by ravbhatnagar** [comment] 2016-07-18 22:47
@QuasarSE - This is currently by design and the cmdlet help would need to be updated to reflect this behavior. This scenario is supported through Find-AzureRmResource -ResourceGroupNameContains <resource-group-name>.
That said, we are also exploring some other options in this regard as well.

**Comment by QuasarSE** [comment] 2016-07-18 23:14
@ravbhatnagar - To complete this, the Find-* approach would be fine, except that it's less efficient (scanning multiple RGs) and means you need to change the single cmdlet into a pipeline to weed out the extraneous resources found.    We have customers (especially EPG customers) that use mandated naming schemes containing many common substrings, so at a minimum, `Find-AzureRmResource` should get a `-ResourceGroupName` option added to allow for exact matches.

**Comment by ravbhatnagar** [comment] 2016-07-18 23:32
@QuasarSE - Yes, I hear you. Adding a new param to Find* is one of the options under consideration.

**Comment by ravbhatnagar** [comment] 2017-01-06 02:00
This has been fixed. Find-AzureRmResource cmdlet now contains parameters for exact name matches.

**Closed by ravbhatnagar** 2017-01-06 02:00 UTC
Labels: ResourceManager
