### ISSUE TITLE
Az.RecoveryServices, specifically ASR cmdlets should have VaultId parameters

### ISSUE THREAD

**Issue by DanteNahuel** [Azure/azure-powershell#11311] opened 2020-03-12 17:00 UTC
## Description of the new feature
Several ASR Cmdlets from the Az.RecoveryServices Module like
Get-AzRecoveryServicesAsrFabric
do not support VaultID parameter.
Instead, they require to set the Vault Context in the Powershell session.
This is very slow and not efficient at all.
If you want to loop through all Vaults searching for an object, you have to make a loop that sets the Vault context for each single vault you have in your subcription. If you have more than 4 vaults and lots of objects in them, it becames a nightmare.
All these cmdlets should accept a VaultID, which is only a string and it's way more efficient when you are searching programmatically for something. 

Related to #11293, #9255, #9007

**Comment by dingmeng-xue** [comment] 2020-03-13 10:59
Include recovery service team.

**Comment by DanteNahuel** [comment] 2020-06-18 18:01
Anything new here?

**Comment by aledeniz** [comment] 2020-06-23 20:01
I think the root cause is that the team maintaining the Az.RecoveryServices module should do a bit of soul searching, and figure out among themselves what is the problem with their module. In my experience is by far the weaker point on the Az module estate.  It could be they are too few, it could be they have been given too much to do, I don't know, but something has to change.
My user experience with the Az modules is that everything more or less work fine, and in more or less the expected way, until I have to touch the Az.RecoveryServices module. There all bets are off.
Can't we give more people for this team for a few months, just to get the Az.RecoveryServices module in a better shape, on par with the rest of the Az modules?
I am a very small Microsoft shareholder myself, I wouldn't mind a iota to see the yield going down a pip or two, if those money are invested on the Az.RecoveryServices module.

**Comment by DanteNahuel** [comment] 2020-06-23 20:52
@aledeniz I agree, but I can't understand how is this so, since Disaster Recovery is a very critical and crucial part of a lot of environments in Azure. However, automating through PowerShell is a major roadblock because of this.

**Comment by glennsarti** [comment] 2020-08-27 08:14
The documentation could also be improved considerably.  For example:

```
Set the vault context by using the -VaultId parameter.

Note: To successfully execute this cmdlet in addition to -VaultId parameter -VaultLocation parameter should be used as well.
```

Why on earth then isn't the `-VaultLocation` a required parameter? Why is this piece of very important information buried in a Note in https://docs.microsoft.com/en-us/powershell/module/az.recoveryservices/restore-azrecoveryservicesbackupitem?view=azps-4.6.0#description

And the error message is horribly confusing:

```
PS> Restore-AzRecoveryServicesBackupItem -RecoveryPoint $RecoveryPoint -StorageAccountName $RestoreStorageAccount -StorageAccountResourceGroupName $RestoreStorageAccountResourceGroupName -VaultId $VaultID -TargetResourceGroupName $TargetResourceGroupName

Restore-AzRecoveryServicesBackupItem: Set vault context first using cmdlet Set-AzRecoveryServicesVaultContext
```

The error has nothing to do the context.  It's just missing the `-VaultLocation` parameter.

**Comment by Sharmistha-Rai** [comment] 2020-08-27 13:14
Adding @pvrk as the latest comment is referring to Backup Item.

**Comment by Sharmistha-Rai** [comment] 2020-10-01 05:29
We have added this issue as part of our backlog. There have been multiple asks to include VaultId parameter so we definitely plan to prioritize this. I'm closing this issue but please feel free to reopen for any additional queries.

**Closed by Sharmistha-Rai** 2020-10-01 05:29 UTC
Labels: Recovery Services, Recovery Services Site-Recovery, Service Attention, customer-reported, feature-request
