### ISSUE TITLE
LocalizableStrings need a ToString override

### ISSUE THREAD

**Issue by Jaykul** [Azure/azure-powershell#15911] opened 2021-09-20 16:14 UTC
## Description of the new feature

Please ensure the LocalizableString shows up as a string when it's a property of the output (e.g. from Get-AzLog)

## Proposed implementation details (optional)

Obviously you should do this in a Types xml file, but here's the PowerShell equivalent which works:

```PowerShell
Update-TypeData -TypeName Microsoft.Azure.Management.Monitor.Models.LocalizableString -MemberType ScriptMethod -MemberName ToString -Value { $this.LocalizedValue } -Force
```

**Comment by dingmeng-xue** [comment] 2021-09-21 14:51
Thanks for reporting. LocalizableString is only used by Az.Monitor. It may be due to historical reason. Changing it will introduce breaking change to all users. We will consider to update it when next Az major release.

**Comment by vidai-msft** [comment] 2021-11-23 05:56
@Jaykul The Get-AzLog command issue caused by the output of the LocalizableString object has been resolved. Please refer to the issue #15833. The fix will be included in the next release. Thanks!

**Closed by vidai-msft** 2021-11-23 05:56 UTC
Labels: Monitor, feature-request, Breaking Change Release, customer-reported
