### ISSUE TITLE
AzureRm cmdlets do not implement "-WhatIf" correctly

### ISSUE THREAD

**Issue by trondhindenes** [Azure/azure-powershell#1255] opened 2015-11-07 22:47 UTC
When running Remove-AzureRmResourceGroup <rgname> -whatif, PowerShell still prompts to confirm deletion of the specified resource group. This is NOT in accordance with the guidelines (https://technet.microsoft.com/en-us/library/bb204629(v=vs.85).aspx). I'm suspecting that this bug is related to #1135, #718 and #475, and in these bugs make me suspect there's something very wrong with how the AzureRm modules implement ShouldProcess/ShouldContinue. I'd really like some feedback some feedback from the team on this.

**Comment by torgro** [comment] 2015-11-09 22:14
Someone should have a look at this. @jaykul noticed the strange implementation of Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ConfirmAction method June 9th this year!!. That is more than 5 months ago. It is in reverse compared to powershell guidelines. Please fix this ASAP. See comments in issue #475

**Comment by singhkay** [comment] 2015-11-11 00:43
@markcowl @devigned Any ideas if this needs to be done in the base class/cmdlets or does each service own this?

**Comment by markcowl** [comment] 2015-11-11 01:12
@singhkay @trondhindenes @torgro @devigned Yes we have known about this issue for some time.  This is a breaking change to the cmdlets that will require both common and service team fixes.  The plan is to do this with the next known breaking change in a couple of sprints.

**Comment by Jaykul** [comment] 2015-11-12 02:48
Breaking _change_? Wouldn't that be a _working_ change? ;-)
Are you able to get it to _not_ prompt, currently?

**Comment by markcowl** [comment] 2016-02-18 23:04
@singhkay @trondhindenes @torgro @devigned Replacing the current Force pattern with the appropriate ShouldProcess pattern will solve this issue.  We will be aming this change across all ARM cmdlets in a near term release.

**Comment by markcowl** [comment] 2016-03-25 20:04
And unfortunately moving this to May - delaying to make the change right.

**Comment by markcowl** [comment] 2016-05-03 00:42
... and moving again.

**Comment by markcowl** [comment] 2016-05-03 00:48
### Root Cause
Common cmdlet code implements this pattern incorrectly.  Pattern is implemented as:
```
if (!Force || ShouldProcess(...)) { ...
```
 which is just wrong.  Need ti implement both standard ShouldProcess and ShouldProcess with additional ShouldContinue+Force implementation.

Notew that also, not enough cmdlets implement ShouldProcess, which will be dealt with separately

### Proposed Solution
- Add common code methods to implement ShouldProcess  and ShouldProcessWithShouldContinue to handle the most common cases (single action guarded by should process, single action with single predicate for ShouldContinue)
- Update cmdlets impleemnting ShouldProcess incorrectly to use the new common code
- Add breaking change warnings for existing Force parameters that are no longer needed.

### Cost (Work Units): 6

**Comment by markcowl** [comment] 2016-07-14 02:50
Fixed.

**Closed by markcowl** 2016-07-14 02:50 UTC
Labels: 1 - Ready, P1, ShouldProcess Normalization, Team
