### ISSUE TITLE
 Update-azurermvm returns an error when VM is using managed storage account for boot diagnostics 

### ISSUE THREAD

**Issue by achaikaJH** [Azure/azure-powershell#12958] opened 2020-09-14 17:21 UTC
when Update-azurermvm ran agains VM which is using managed storage account for boot diagnostics following error is returned:

 Update-azurermvm -ResourceGroupName rg -VM $vm 

 Update-azurermvm : Required parameter 'bootDiagnostics.storageAccountUri' is missing (null).
ErrorCode: InvalidParameter
ErrorMessage: Required parameter 'bootDiagnostics.storageAccountUri' is missing (null).
ErrorTarget: bootDiagnostics.storageAccountUri
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : b141b1d1-f06f-4d5b-9c45-5f5e194da222
At line:1 char:1
+ Update-azurermvm -ResourceGroupName rg -VM $vm
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Update-AzureRmVM], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.UpdateAzureVMCommand 

run Update-azurermvm against VM which is using managed storage account for boot diagnostics.

 get-module -Name AzureRM.Compute

ModuleType Version    Name                                ExportedCommands                                                                                                                                 
---------- -------    ----                                ----------------                                                                                                                                 
Script     5.9.1      AzureRM.Compute                   

 $PSVersionTable

Name                           Value                                                                                                                                                                       
----                           -----                                                                                                                                                                       
PSVersion                      5.1.14393.3866                                                                                                                                                              
PSEdition                      Desktop                                                                                                                                                                     
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                     
BuildVersion                   10.0.14393.3866                                                                                                                                                             
CLRVersion                     4.0.30319.42000                                                                                                                                                             
WSManStackVersion              3.0                                                                                                                                                                         
PSRemotingProtocolVersion      2.3                                                                                                                                                                         
SerializationVersion           1.1.0.1

**Comment by nehakalems** [comment] 2020-09-16 01:04
I am facing same issue. How do I add the storageaccounturi?

**Comment by dingmeng-xue** [comment] 2020-09-16 03:35
Thanks for reporting. Could you share detail debug message? You can get it when you set `$DebugPreference="Continue"`.

**Comment by achaikaJH** [comment] 2020-09-16 14:46
Please find debug output below.
As a workaround VM boot diagnostics settings could be changed to the custom storage account. It seems issue only affects VMs which have managed storage account configured for boot diagnostics.
`PS C:\Users\ac5> Update-AzureRmVM -ResourceGroupName rg -VM $vm
DEBUG: 10:20:42 AM - UpdateAzureVMCommand begin processing with ParameterSet 'ResourceGroupNameParameterSetName'.
DEBUG: 10:20:42 AM - using account id 'xxx@xxx.COM'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'xxx@xxx.COM', environment: 'AzureCloud', tenant: 'xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 09/16/2020 14:20:42: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/
	Resource: https://management.core.windows.net/
	ClientId: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
	CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (3 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 09/16/2020 14:20:42:  - TokenCache: Deserialized 3 items to token cache.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 09/16/2020 14:20:42: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 09/16/2020 14:20:42: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 09/16/2020 14:20:42: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - TokenCache: 21.0550480916667 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 09/16/2020 14:20:42: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - TokenCache: A matching item (access token or refresh token or both) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 09/16/2020 14:20:42: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
	Access Token Hash: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
	Refresh Token Hash: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
	Expiration Time: 09/16/2020 14:41:45 +00:00
	User Hash: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 09/16/2020 14:20:42: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/
	Resource: https://management.core.windows.net/
	ClientId: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
	CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (3 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 09/16/2020 14:20:42:  - TokenCache: Deserialized 3 items to token cache.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 09/16/2020 14:20:42: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 09/16/2020 14:20:42: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 09/16/2020 14:20:42: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - TokenCache: 21.0536489766667 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 09/16/2020 14:20:42: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - TokenCache: A matching item (access token or refresh token or both) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 09/16/2020 14:20:42: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
	Access Token Hash: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
	Refresh Token Hash: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
	Expiration Time: 09/16/2020 14:41:45 +00:00
	User Hash: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
	

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg/providers/Microsoft.Compute/virtualMachines/VM?api-version=2018-10-01

Headers:
x-ms-client-request-id        : fc32fe77-9c55-4b18-9187-2c274a02357d
accept-language               : en-US

Body:
{
  "properties": {
    "hardwareProfile": {
      "vmSize": "Standard_E2s_V3"
    },
    "storageProfile": {
      "imageReference": {
        "publisher": "MicrosoftWindowsServer",
        "offer": "WindowsServer",
        "sku": "2016-Datacenter",
        "version": "latest"
      },
      "osDisk": {
        "osType": "Windows",
        "name": "VM-OSdisk",
        "caching": "ReadWrite",
        "createOption": "FromImage",
        "managedDisk": {
          "id": "/subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg/providers/Microsoft.Compute/disks/VM-OSdisk"
        }
      },
      "dataDisks": []
    },
    "osProfile": {
      "computerName": "VM",
      "adminUsername": "systems",
      "windowsConfiguration": {
        "provisionVMAgent": true,
        "enableAutomaticUpdates": true
      },
      "secrets": []
    },
    "networkProfile": {
      "networkInterfaces": [
        {
          "id": "/subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg/providers/Microsoft.Network/networkInterfaces/VM-PriNic"
        }
      ]
    },
    "diagnosticsProfile": {
      "bootDiagnostics": {
        "enabled": true
      }
    }
  },
  "location": "eastus2",
  "tags": {
    "CostCenter": "4275"
  }
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
x-ms-ratelimit-remaining-resource: Microsoft.Compute/PutVM3Min;786,Microsoft.Compute/PutVM30Min;3935
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : ca579c17-ae44-43e9-9a82-bacf34e700cc
Cache-Control                 : no-cache
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : c7c18cae-368d-4dcd-9508-8462b9692ffc
x-ms-routing-request-id       : CANADACENTRAL:20200916T142044Z:c7c18cae-368d-4dcd-9508-8462b9692ffc
X-Content-Type-Options        : nosniff
Date                          : Wed, 16 Sep 2020 14:20:44 GMT

Body:
{
  "error": {
    "code": "InvalidParameter",
    "message": "Required parameter 'bootDiagnostics.storageAccountUri' is missing (null).",
    "target": "bootDiagnostics.storageAccountUri"
  }
}


DEBUG: AzureQoSEvent: CommandName - Update-AzureRmVM; IsSuccess - True; Duration - 00:00:00.9353349; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 10:20:44 AM - UpdateAzureVMCommand end processing.
DEBUG: 10:20:44 AM - UpdateAzureVMCommand end processing.
Update-AzureRmVM : Required parameter 'bootDiagnostics.storageAccountUri' is missing (null).
ErrorCode: InvalidParameter
ErrorMessage: Required parameter 'bootDiagnostics.storageAccountUri' is missing (null).
ErrorTarget: bootDiagnostics.storageAccountUri
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : ca579c17-ae44-43e9-9a82-bacf34e700cc
At line:1 char:1
+ Update-AzureRmVM -ResourceGroupName 'rg' -VM $vm
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Update-AzureRmVM], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.UpdateAzureVMCommand
 
DEBUG: AzureQoSEvent: CommandName - Update-AzureRmVM; IsSuccess - False; Duration - 00:00:00.9353349; Exception - Microsoft.Azure.Commands.Compute.Common.ComputeCloudException: Required parameter 'bootDia
gnostics.storageAccountUri' is missing (null).
ErrorCode: InvalidParameter
ErrorMessage: Required parameter 'bootDiagnostics.storageAccountUri' is missing (null).
ErrorTarget: bootDiagnostics.storageAccountUri
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : ca579c17-ae44-43e9-9a82-bacf34e700cc ---> Microsoft.Rest.Azure.CloudException: Required parameter 'bootDiagnostics.storageAccountUri' is missing (null).
   at Microsoft.Azure.Management.Compute.VirtualMachinesOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Compute.VirtualMachinesOperations.<CreateOrUpdateWithHttpMessagesAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Commands.Compute.UpdateAzureVMCommand.<ExecuteCmdlet>b__44_0()
   at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
   at Microsoft.Azure.Commands.Compute.UpdateAzureVMCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 10:20:45 AM - UpdateAzureVMCommand end processing.
DEBUG: 10:20:45 AM - UpdateAzureVMCommand end processing.`

**Comment by nehakalems** [comment] 2020-09-16 16:09
I am getting similar output

**Comment by artisticcheese** [comment] 2020-09-29 19:46
Issue is that api version for Microsoft.Compute/virtualMachines probably is outdated. API version "2020-06-01" which supports managed bootdiag accounts but latest mentioned on official docs and I assume used in powershell is "2019-12-01" (https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/virtualmachines)

**Comment by mpilking** [comment] 2020-10-06 03:13
I battled this for far too long today.  The note above from @artisticcheese led me to upgrade to the latest version of PowerShell (7.0.3) and that fixed it for me.  Prior to that I was using AZ PowerShell in Windows PowerShell 5.1.  The weird thing is that the same command worked fine for me a month ago.

**Comment by tejassumbha71** [comment] 2020-11-19 14:10
how to update the same for azureautomation account

**Comment by Drewm3** [comment] 2020-12-09 19:52
@jaylabell, could you please look into this issue.

**Comment by jaylabell** [comment] 2021-01-07 21:49
Apologies for the delay here due to the holiday season. We are looking into this issue, and will provide feedback shortly.

**Comment by jordanmills** [comment] 2021-02-01 15:03
This also seems to affect the Azure portal.

**Comment by mrozwod** [comment] 2021-02-01 15:10
This happens for Virtual Machine Scale Sets too - for example when trying to set new extensions with
_az vmss extension set_ 

I am unable to install LAD 3.0 extension for VMSS with boot diagnostics enabled, receiving this error.

**Comment by ntachandley** [comment] 2021-02-02 04:31
Been having the same issue for well over a month. Update-AzVm for something as simple as $vm.hardwareprofile.vmsize fails with PS 7.0.3 and the latest Az module. 

Required parameter 'bootDiagnostics.storageAccountUri' is missing (null). ErrorCode: InvalidParameter ErrorMessage: Required parameter
     | 'bootDiagnostics.storageAccountUri' is missing (null). ErrorTarget: bootDiagnostics.storageAccountUri StatusCode: 400 ReasonPhrase: Bad Request
     | OperationID : e66bd508-a3a4-4d17-a0b0-09b5f38da849

**Comment by jaylabell** [comment] 2021-02-11 21:11
**All versions of the AzureRM PowerShell module are outdated. 
The Az PowerShell module is now the recommended PowerShell module for interacting with Azure.**

**Helpful documentation includes:** 
_**Migrate Azure PowerShell from AzureRM to Az**_
[https://docs.microsoft.com/en-us/powershell/azure/migrate-from-azurerm-to-az?view=azps-5.5.0](url)

**_Quickstart: Automatically migrate PowerShell scripts from AzureRM to the Az PowerShell module_**
https://docs.microsoft.com/en-us/powershell/azure/quickstart-migrate-azurerm-to-az-automatically?view=azps-5.5.0

**Comment by jordanmills** [comment] 2021-02-11 22:23
> **All versions of the AzureRM PowerShell module are outdated. The Az PowerShell module is now the recommended PowerShell module for interacting with Azure.**
> 
> **Helpful documentation includes:**
> _**Migrate Azure PowerShell from AzureRM to Az**_
> [https://docs.microsoft.com/en-us/powershell/azure/migrate-from-azurerm-to-az?view=azps-5.5.0](url)
> 
> **_Quickstart: Automatically migrate PowerShell scripts from AzureRM to the Az PowerShell module_**
> https://docs.microsoft.com/en-us/powershell/azure/quickstart-migrate-azurerm-to-az-automatically?view=azps-5.5.0

Cool!  Could you tell the azure portal team?

**Comment by Drewm3** [comment] 2021-02-17 22:01
@ntachandley, could you share the repro you are seeing with  Update-AzVm? It sounds like you are just changing the VM size for what I assume is a VM that is configured with a managed boot diagnostics storage account. Is this correct, or is the VM in your repro using a traditional storage account and/or not using boot diagnostics?

@jordanmills, could you provide a little more context on where you are getting an error in the portal?

**Comment by ThinkFr33ly** [comment] 2021-02-24 20:19
I too am seeing this error. I'm trying to add a custom script extension to an existing VM Scale Set. This exactly script was working a few months ago but now results in the error described.

**Comment by jaylabell** [comment] 2021-02-26 21:02
This issue has been tasked to development for more investigation, updates soon to come!

**Comment by ThinkFr33ly** [comment] 2021-02-26 21:20
One workaround I've found is to temporarily disable boot diagnostics via the portal. Update commands then work as expected. Once done, you can re-enable boot diagnostics without issue.

**Comment by grizzlytheodore** [comment] 2021-03-18 20:30
i am unable to reproduce the issue

# VM with bootdiagnostics enabled with managed storage account 
$vm = get-azvm -ResourceGroupName theo_temp -Name updatebootdiagVM   

# update size from Standard_B1ms to Standard_B2ms
$vm.HardwareProfile.VmSize = "Standard_B2ms"

update-azvm -ResourceGroupName theo_temp -VM $vm

Output:
RequestId IsSuccessStatusCode StatusCode ReasonPhrase
--------- ------------------- ---------- ------------
                         True         OK OK


could you please provide what you did different? @ntachandley

**Comment by avirishuv** [comment] 2021-04-08 19:22
hi @ntachandley would you mind sharing repro steps? That would help troubleshoot/investigate further for Update-AzVM as @grizzlytheodore mentioned.

Also, for the Add-AzVmssExtension, @mrozwod and @ThinkFr33ly could you please share repro steps?

**Comment by avirishuv** [comment] 2021-05-06 21:31
hi everyone, closing this issue due to insufficient information on repro steps. Feel free to reopen if you have questions on this topic, or have additional information you would like to share for further investigation. Thanks.

**Closed by avirishuv** 2021-05-06 21:31 UTC
Labels: Compute - VM, Service Attention, bug, customer-reported
