### ISSUE TITLE
Get-AzureRmAppServicePlan -Name Progress not hidden after execution

### ISSUE THREAD

**Issue by Weishaupt** [Azure/azure-powershell#3340] opened 2017-01-03 09:08 UTC
### Cmdlet(s)
Get-AzureRmAppServicePlan

### PowerShell Version
5.0.10586.672

### Module Version
AzureRM 3.3.0
AzureRM.Websites 2.4.0

### OS Version
10.0.10586.672

### Description
The progress bar is not closed upon completion of the cmdlet execution. The progress bar stays open while subsequent commands are executed.

### Debug Output
n/a

### Script/Steps for Reproduction
Call Get-AzureRmAppServicePlan with the -Name Parameter and a valid AppServicePlan.
Execute any other command like Write-Host.
The progress bar won't be hidden.

**Comment by cormacpayne** [comment] 2017-01-03 17:54
@LukaszStem Hey Lukasz, would you mind taking a look at this issue?

**Comment by totkeks** [comment] 2018-02-23 11:11
From a quick look at the code I would say that the functions only call WriteProgress, but the -completed flag (if used in PowerShell with Write-Progress) is not implicitly set, when the percentage reaches 100.
So either Write-Progress from PowerShell should implicitly set -completed when percentage is 100 or the caller of WriteProgress() has to do it. (see https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/write-progress?view=powershell-6)

**Comment by cormacpayne** [comment] 2018-02-23 16:28
@totkeks Hey Norman, I'm unable to reproduce this issue when running the following commands with the latest version of `AzureRM.Websites` (4.1.0):

```powershell
Get-AzureRmAppServicePlan
Get-AzureRmAppServicePlan -Name {{name}}
Get-AzureRmAppServicePlan -Name {{name}} -ResourceGroupName {{resourceGroupName}}
```

Does the progress stream hang for you on any of the above calls?

**Comment by totkeks** [comment] 2018-02-26 13:23
@cormacpayne Hey Cormac, I just checked if my version is outdated, but it isn't. I also have version 4.1.0 installed.

I tried to figure out something and reproduced it. Try adding some sleep after the actual command:
```
Get-AzureRmAppServicePlan -Name {{name}}; sleep 5
```

The progress bar then stays open until the whole process (including sleep) is finished. From my understanding the progress bar should disappear already after the cmdlet has finished.

**Comment by panchagnula** [comment] 2018-03-09 23:20
@Weishaupt  @totkeks I am closing this since i cannot repro it. Please do test this using preview to validate https://github.com/Azure/azure-powershell/releases/tag/v5.0.0-preview-AzureRM.Websites & re-activate if needed

**Closed by panchagnula** 2018-03-09 23:20 UTC
Labels: Websites

**Comment by totkeks** [comment] 2018-03-13 12:28
Running the 5.0.0 version I get the same results as before. Maybe it is not just the AzureRM.Websites module that needs to be updated?
As you can see in my screenshot, the progress bars stay open after the Get Cmdlet has finished. Even multiple of them.

```
[13:22:28] H:\> Get-Module AzureRM.Websites |fl


Name              : AzureRM.Websites
Path              : C:\Program Files\WindowsPowerShell\Modules\AzureRM.Websites\5.0.0\AzureRM.Websites.psm1
Description       : Microsoft Azure PowerShell - Websites service cmdlets for Azure Resource Manager
ModuleType        : Script
Version           : 5.0.0
NestedModules     : {Microsoft.Azure.Commands.Websites}
ExportedFunctions :
ExportedCmdlets   : {Edit-AzureRmWebAppBackupConfiguration, Get-AzureRmAppServicePlan, Get-AzureRmAppServicePlanMetrics,
                    Get-AzureRmWebApp...}
ExportedVariables :
ExportedAliases   : Swap-AzureRmWebAppSlot
```

![2018_03_13_13_24_15_windows_powershell](https://user-images.githubusercontent.com/2941389/37341598-4408f25c-26c2-11e8-8eba-765d4e562dcf.png)
