### ISSUE TITLE
Delete StorageAccount in Portal causing script to give error, name already exists. Status is 'Creating'

### ISSUE THREAD

**Issue by ward0** [Azure/azure-powershell#3342] opened 2017-01-03 12:59 UTC
### Cmdlet(s)
$StorageAccount = New-AzureRmStorageAccount -ResourceGroupName $ResourceGroupName.ResourceGroupName -Name $StorageAccountName -SkuName $StorageSku -Kind "Storage" -Location "westeurope" -ErrorAction Stop

Executed it the first time = succeeded

Went to AzureRM website and deleted the storageaccount after my checks if everything was ok.

Started my script again and created a new storageaccount : "a storageaccount with this name already exist."

I ran : 

Get-AzureRmStorageAccount

ResourceGroupName   : ****
StorageAccountName  : ****
Id                  : /subscriptions/****/resourceGroups/****/providers/Microsoft.Storage/storageAccounts/****
Location            : westeurope
Sku                 : Microsoft.Azure.Management.Storage.Models.Sku
Kind                : Storage
Encryption          : 
AccessTier          : 
CreationTime        : 
CustomDomain        : 
LastGeoFailoverTime : 
PrimaryEndpoints    : 
PrimaryLocation     : 
ProvisioningState   : Creating
SecondaryEndpoints  : 
SecondaryLocation   : 
StatusOfPrimary     : 
StatusOfSecondary   : 
Tags                : {}
Context             : Microsoft.WindowsAzure.Commands.Common.Storage.LazyAzureStorageContext

### PowerShell Version
5.1.14393.576

### OS Version
10.0.14393.576

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction

Create storageaccount by script
Delete in Portal > Info message : Succeeded.
Create by script > error already exists > status : creating

**Comment by ward0** [comment] 2017-01-03 13:02
Update: I did a new Get-AzureRmStorageAccount and the status is now 'succeeded'. So this is buggy right? The portal is giving me 'finished' and when asking in PS you get another status.

**Comment by ward0** [comment] 2017-01-03 13:06
Update2: It seems this problem occures when using ISE and F11, Then it will stay on 'running a command' even when waiting several minutes. 

When not going into debug it is finished directly..

**Comment by ward0** [comment] 2017-01-03 13:19
Update3: Ok, now i'm totally stuck.. I can't create the storageaccount anymore in the portal 'name already exists' in powershell with Remove-AzureRmStorageAccount -force > conflict.

status is still creating.

**Comment by ward0** [comment] 2017-01-03 13:30
This is crazy, the status finally came to 'Succeeded'.

**Comment by markcowl** [comment] 2017-01-04 01:44
@vincent81-jiang Can you take a look?

**Comment by ward0** [comment] 2017-01-04 11:39
Thanks for assinging someone. This has been reported on forums already:

https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-manage-nsg-arm-ps

Seems to be an old problem..

**Comment by blueww** [comment] 2017-01-09 02:08
This is not caused PowerShell's problem.
It's caused by after delete an account, user need to wait for a while for the account to be cleaned up. And in the mean while user can' create/delete account with same name again will both fail.
Close this issue as customer already agree this is an old problem.

**Closed by blueww** 2017-01-09 02:08 UTC
Labels: Storage
