### ISSUE TITLE
Remove-AzSqlInstanceDatabase : Long running operation failed with status 'Forbidden'" error. 

### ISSUE THREAD

**Issue by InformTechPro** [Azure/azure-powershell#18849] opened 2022-06-30 22:20 UTC
### Description

When running "Remove-AzSqlInstanceDatabase -Name ..."  seeing "Remove-AzSqlInstanceDatabase : Long running operation failed with status 'Forbidden'" error. The database does get removed, but we do not log completed message in the Azure Activity Log (only started and accepted) . The command is using managed identity that has SQL Managed Instance Contributor role to the resource group in the subscription that hosts SQL Instance and DB. We were not successful reproducing the error in another environment (different tenant) with similar permissions and PS modules, but repro was not successful (command successfully executed and we received succeeded event in the activity log). Need help clarifying what triggers the error.

### Issue script & Debug output

```PowerShell
ServerMessage    : AuthorizationFailed: The client '...' with object id 
                   '...' does not have authorization to perform action 
                   'Microsoft.Sql/locations/managedDatabaseAzureAsyncOperation/read' over scope '/subscriptions/.../resourceGroups/rg-dacoe-dev/providers/Microsoft.Sql/locations/eastus/man
                   agedDatabaseAzureAsyncOperation/a85...' or the scope is invalid. If 
                   access was recently granted, please refresh your credentials. 
                   (System.Collections.Generic.List`1[Microsoft.Rest.Azure.CloudError])
ServerResponse   : {Forbidden}
RequestMessage   : {GET https://management.azure.com/subscriptions/e9.../resourceGroups/r
                   g-dacoe-dev/providers/Microsoft.Sql/locations/eastus/managedDatabaseAzureAsyncOperation/a85...?api-version=2020-11-01-preview}
RequestId        : 
InnerException   : False
Exception        : Microsoft.Rest.Azure.CloudException: Long running operation failed with status 'Forbidden'.
                      at 
                   Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.<CheckErrorStatusAndThrowAsync>d__51.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.<GetRawAsync>d__49.MoveNext()
```

### Environment data

```PowerShell
PSVersion                      5.1.15063.726                                                                            
PSEdition                      Desktop                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                  
BuildVersion                   10.0.15063.726                                                                           
CLRVersion                     4.0.30319.42000                                                                          
WSManStackVersion              3.0                                                                                      
PSRemotingProtocolVersion      2.3                                                                                      
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
AuditPolicyDsc	1.1.0.0
Az	7.3.2
Az.Accounts	2.7.4
Az.Advisor	1.1.2
Az.Aks	3.1.2
Az.AnalysisServices	1.1.4
Az.ApiManagement	2.3.1
Az.AppConfiguration	1.0.0
Az.ApplicationInsights	1.3.0
Az.Attestation	1.0.0
Az.Automation	1.7.3
Az.Batch	3.1.1
Az.Billing	2.0.0
Az.Cdn	1.8.1
Az.CloudService	1.1.0
Az.CognitiveServices	1.10.0
Az.Compute	4.24.1
Az.ContainerInstance	3.0.1
Az.ContainerRegistry	2.2.3
Az.CosmosDB	1.5.1
Az.DataBoxEdge	1.1.0
Az.Databricks	1.2.0
Az.DataFactory	1.16.4
Az.DataLakeAnalytics	1.0.2
Az.DataLakeStore	1.3.0
Az.DataShare	1.0.1
Az.DeploymentManager	1.1.0
Az.DesktopVirtualization	3.1.0
Az.DevTestLabs	1.0.2
Az.Dns	1.1.2
Az.EventGrid	1.3.0
Az.EventHub	1.11.0
Az.FrontDoor	1.9.0
Az.Functions	4.0.1
Az.HDInsight	5.0.0
Az.HealthcareApis	1.3.2
Az.IotHub	2.7.4
Az.KeyVault	4.3.0
Az.Kusto	2.0.0
Az.LogicApp	1.5.0
Az.MachineLearning	1.1.3
Az.Maintenance	1.2.0
Az.ManagedServices	3.0.0
Az.MarketplaceOrdering	1.0.2
Az.Media	1.1.1
Az.Migrate	1.1.2
Az.Monitor	3.0.1
Az.MySql	1.0.0
Az.Network	4.15.0
Az.NotificationHubs	1.1.1
Az.OperationalInsights	3.0.1
Az.PolicyInsights	1.5.0
Az.PostgreSql	1.0.0
Az.PowerBIEmbedded	1.1.2
Az.PrivateDns	1.0.3
Az.RecoveryServices	5.2.0
Az.RedisCache	1.6.0
Az.RedisEnterpriseCache	1.0.0
Az.Relay	1.0.3
Az.ResourceMover	1.1.0
Az.Resources	5.4.0
Az.Security	1.1.1
Az.SecurityInsights	1.1.0
Az.ServiceBus	1.8.0
Az.ServiceFabric	3.0.1
Az.SignalR	1.4.1
Az.Sql	3.7.1
Az.SqlVirtualMachine	1.1.0
Az.StackHCI	1.1.0
Az.Storage	4.3.0
Az.StorageSync	1.7.0
Az.StreamAnalytics	2.0.0
Az.Support	1.0.0
Az.Synapse	1.1.0
Az.TrafficManager	1.1.0
Az.Websites	2.10.0
Azure	1.0.3
Azure.Storage	1.0.3
AzureRM.Automation	1.0.3
AzureRM.Compute	1.2.1
AzureRM.Profile	1.0.3
AzureRM.Resources	1.0.3
AzureRM.Sql	1.0.3
AzureRM.Storage	1.0.3
ComputerManagementDsc	5.0.0.0
GPRegistryPolicyParser	0.2
Microsoft.PowerShell.Core	0.0
Microsoft.PowerShell.Diagnostics	0.0
Microsoft.PowerShell.Management	0.0
Microsoft.PowerShell.Security	0.0
Microsoft.PowerShell.Utility	0.0
Microsoft.WSMan.Management	0.0
Orchestrator.AssetManagement.Cmdlets	1.0
PSDscResources	2.9.0.0
SecurityPolicyDsc	2.1.0.0
SqlServer	21.1.18256
StateConfigCompositeResources	1.0
xDSCDomainjoin	1.1
xPowerShellExecutionPolicy	1.1.0.0
xRemoteDesktopAdmin	1.1.0.0
```

### Error output

```PowerShell
ServerMessage    : AuthorizationFailed: The client '...' with object id 
                   '...' does not have authorization to perform action 
                   'Microsoft.Sql/locations/managedDatabaseAzureAsyncOperation/read' over scope '/subscriptions/.../resourceGroups/rg-dacoe-dev/providers/Microsoft.Sql/locations/eastus/man
                   agedDatabaseAzureAsyncOperation/a85...' or the scope is invalid. If 
                   access was recently granted, please refresh your credentials. 
                   (System.Collections.Generic.List`1[Microsoft.Rest.Azure.CloudError])
ServerResponse   : {Forbidden}
RequestMessage   : {GET https://management.azure.com/subscriptions/e9.../resourceGroups/r
                   g-dacoe-dev/providers/Microsoft.Sql/locations/eastus/managedDatabaseAzureAsyncOperation/a85...?api-version=2020-11-01-preview}
RequestId        : 
InnerException   : False
Exception        : Microsoft.Rest.Azure.CloudException: Long running operation failed with status 'Forbidden'.
                      at 
                   Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.<CheckErrorStatusAndThrowAsync>d__51.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.<GetRawAsync>d__49.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at 
                   Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.<UpdateResourceFromPollingUri>d__47.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.<Poll>d__46.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.<StartPollingAsync>d__20.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.<BeginLROAsync>d__15.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at 
                   Microsoft.Rest.Azure.AzureClientExtensions.<GetLongRunningOperationResultAsync>d__1`2.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at 
                   Microsoft.Rest.Azure.AzureClientExtensions.<GetLongRunningOperationResultAsync>d__0`1.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.Rest.Azure.AzureClientExtensions.<GetPutOrPatchOperationResultAsync>d__5`1.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.Azure.Management.Sql.ManagedDatabasesOperations.<CreateOrUpdateWithHttpMessagesAsync>
                   d__7.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.Azure.Management.Sql.ManagedDatabasesOperationsExtensions.<CreateOrUpdateAsync>d__5.M
                   oveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.Azure.Management.Sql.ManagedDatabasesOperationsExtensions.CreateOrUpdate(IManagedData
                   basesOperations operations, String resourceGroupName, String managedInstanceName, String 
                   databaseName, ManagedDatabase parameters)
                      at Microsoft.Azure.Commands.Sql.ManagedDatabase.Services.AzureSqlManagedDatabaseAdapter.RestoreMan
                   agedDatabase(AzureSqlManagedDatabaseModel model)
                      at 
                   Microsoft.Azure.Commands.Sql.ManagedDatabase.Cmdlet.RestoreAzureRmSqlManagedDatabase.GetEntity()
                      at Microsoft.Azure.Commands.Sql.Common.AzureSqlCmdletBase`2.ExecuteCmdlet()
                      at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Message          : Long running operation failed with status 'Forbidden'.
StackTrace       :    at 
                   Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.<CheckErrorStatusAndThrowAsync>d__51.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.<GetRawAsync>d__49.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at 
                   Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.<UpdateResourceFromPollingUri>d__47.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.<Poll>d__46.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.<StartPollingAsync>d__20.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.<BeginLROAsync>d__15.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at 
                   Microsoft.Rest.Azure.AzureClientExtensions.<GetLongRunningOperationResultAsync>d__1`2.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at 
                   Microsoft.Rest.Azure.AzureClientExtensions.<GetLongRunningOperationResultAsync>d__0`1.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.Rest.Azure.AzureClientExtensions.<GetPutOrPatchOperationResultAsync>d__5`1.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.Azure.Management.Sql.ManagedDatabasesOperations.<CreateOrUpdateWithHttpMessagesAsync>
                   d__7.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.Azure.Management.Sql.ManagedDatabasesOperationsExtensions.<CreateOrUpdateAsync>d__5.M
                   oveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.Azure.Management.Sql.ManagedDatabasesOperationsExtensions.CreateOrUpdate(IManagedData
                   basesOperations operations, String resourceGroupName, String managedInstanceName, String 
                   databaseName, ManagedDatabase parameters)
                      at Microsoft.Azure.Commands.Sql.ManagedDatabase.Services.AzureSqlManagedDatabaseAdapter.RestoreMan
                   agedDatabase(AzureSqlManagedDatabaseModel model)
                      at 
                   Microsoft.Azure.Commands.Sql.ManagedDatabase.Cmdlet.RestoreAzureRmSqlManagedDatabase.GetEntity()
                      at Microsoft.Azure.Commands.Sql.Common.AzureSqlCmdletBase`2.ExecuteCmdlet()
                      at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HelpLink         :
```

**Comment by SaurabhSharma-MSFT** [comment] 2022-07-07 23:24
@InformTechPro Did you try creating an Azure support case from Azure portal, so that an engineer can look into your backend logs to identify the cause ?

**Comment by InformTechPro** [comment] 2022-07-08 03:18
@SaurabhSharma-MSFT we noticed that the command was accessing Resource Group/Providers/Microsoft.sql/locations... when double checking permissions realized that the role was assigned at the resource and not the resource group. Once we made sure that the account had SQL Managed Contributor role at the Resource Group, the command worked ok. Thank you for looking into it!

**Comment by SaurabhSharma-MSFT** [comment] 2022-07-08 17:27
@InformTechPro Great. Thanks for the confirmation. We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Closed by SaurabhSharma-MSFT** 2022-07-08 17:27 UTC
Labels: SQL, bug, customer-reported, CXP Attention
