### ISSUE TITLE
Az.Keyvault 4.10.1, Set-AzKeyVaultAccessPolicy : The request content has one or more ambiguous paths

### ISSUE THREAD

**Issue by AlanFlorance** [Azure/azure-powershell#22504] opened 2023-08-04 17:08 UTC
### Description

A call to Set-AzKeyVaultAccessPolicy is now failing with the latest version of the module with the following message

Set-AzKeyVaultAccessPolicy : The request content has one or more ambiguous paths: 'properties.networkAcls.ipRules' required for policy evaluation.
At line:2 char:5
+     Set-AzKeyVaultAccessPolicy -ObjectId $AzADGroup.ObjectId -Permiss ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzKeyVaultAccessPolicy], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.SetAzureKeyVaultAccessPolicy

### Issue script & Debug output

```PowerShell
DEBUG: 17:39:51 - SetAzureKeyVaultAccessPolicy begin processing with ParameterSet 'ByObjectId'.
DEBUG: 17:39:51 - using account id x...
DEBUG: 17:39:51 - [ConfigManager] Got [False] from [DisplayBreakingChangeWarning], Module = [], Cmdlet = [].
DEBUG: [Common.Authentication]: Authenticating using Account: x, environment: 'AzureCloud', tenant: x
DEBUG: 17:39:51 - [ConfigManager] Got nothing from [EnableLoginByWam], Module = [], Cmdlet = []. Returning default value [False].
DEBUG: 17:39:51 - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId: x, Scopes:'https://management.core.windows.net//.default',
AuthorityHost:'https://login.microsoftonline.com/', UserId: x
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 7001c5ef-d218-46aa-84d0-fe7e2f5b47ff] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 7001c5ef-d218-46aa-84d0-fe7e2f5b47ff] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 7001c5ef-d218-46aa-84d0-fe7e2f5b47ff] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 7001c5ef-d218-46aa-84d0-fe7e2f5b47ff] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 7001c5ef-d218-46aa-84d0-fe7e2f5b47ff] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z] Found 1 cache accounts and 0 broker accounts
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z] Returning 1 accounts
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 41667d02-c688-4e21-b115-3c218f4178c5] MSAL MSAL.Desktop with assembly version '4.49.1.0'.
CorrelationId(41667d02-c688-4e21-b115-3c218f4178c5)
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 41667d02-c688-4e21-b115-3c218f4178c5] === AcquireTokenSilent Parameters ===
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 41667d02-c688-4e21-b115-3c218f4178c5] LoginHint provided: False
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 41667d02-c688-4e21-b115-3c218f4178c5] Account provided: True
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 41667d02-c688-4e21-b115-3c218f4178c5] ForceRefresh: False
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 41667d02-c688-4e21-b115-3c218f4178c5]
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 41667d02-c688-4e21-b115-3c218f4178c5
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured:
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 41667d02-c688-4e21-b115-3c218f4178c5] === Token Acquisition (SilentRequest) started:
  Scopes: https://management.core.windows.net//.default
 Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 41667d02-c688-4e21-b115-3c218f4178c5] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 41667d02-c688-4e21-b115-3c218f4178c5] Access token is not expired. Returning the found cache entry. [Current
time (08/04/2023 16:39:51) - Expiration Time (08/04/2023 17:33:02 +00:00) - Extended Expiration Time (08/04/2023 17:33:02 +00:00)]
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 41667d02-c688-4e21-b115-3c218f4178c5] Returning access token found in cache. RefreshOn exists ? False
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 41667d02-c688-4e21-b115-3c218f4178c5] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 41667d02-c688-4e21-b115-3c218f4178c5]
 === Token Acquisition finished successfully:
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 41667d02-c688-4e21-b115-3c218f4178c5]  AT expiration time: 04/08/2023 17:33:02 +00:00, scopes:
https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default. source: Cache
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2023-08-04T17:33:02.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: x, UserId: x
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/x/resourceGroups/x/providers/Microsoft.KeyVault/vaults/x?api-version=2022-07-01

Headers:
x-ms-client-request-id        : 420c422e-e162-4d79-8058-1c471a0cf65b
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-client-request-id        : 420c422e-e162-4d79-8058-1c471a0cf65b
x-ms-keyvault-service-version : 1.5.851.0
x-ms-request-id               : 95524fca-9c23-454a-b3b5-5cc0eb17ff01
X-Content-Type-Options        : nosniff
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-reads: 11999
x-ms-correlation-request-id   : 443d520b-ebe5-4a5c-b370-efbb6eae6c3c
x-ms-routing-request-id       : UKSOUTH:20230804T163951Z:443d520b-ebe5-4a5c-b370-efbb6eae6c3c
Cache-Control                 : no-cache
Date                          : Fri, 04 Aug 2023 16:39:51 GMT
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319

Body:
{
  "id": "/subscriptions/x/resourceGroups/x/providers/Microsoft.KeyVault/vaults/x",
  "name": x,
  "type": "Microsoft.KeyVault/vaults",
  "location": "westeurope",
  "tags": {
  },
  "systemData": {
    "lastModifiedBy": x,
    "lastModifiedByType": "User",
    "lastModifiedAt": "2023-08-02T22:55:20.407Z"
  },
  "properties": {
    "sku": {
      "family": "A",
      "name": "standard"
    },
    "tenantId": x",
    "accessPolicies": [
      {

        "permissions": {
          "keys": [
            "Get",
            "List",
            "Update",
            "Create",
            "Import",
            "Delete",
            "Recover",
            "Backup",
            "Restore",
            "GetRotationPolicy",
            "SetRotationPolicy",
            "Rotate"
          ],
          "secrets": [
            "Get",
            "List",
            "Set",
            "Delete",
            "Recover",
            "Backup",
            "Restore"
          ],
          "certificates": [
            "Get",
            "List",
            "Update",
            "Create",
            "Import",
            "Delete",
            "Recover",
            "Backup",
            "Restore",
            "ManageContacts",
            "ManageIssuers",
            "GetIssuers",
            "ListIssuers",
            "SetIssuers",
            "DeleteIssuers"
          ]
        }
      },
      {

        "permissions": {
          "certificates": [],
          "keys": [],
          "secrets": [
            "Get",
            "List",
            "Set"
          ]
        }
      },
      {

        "permissions": {
          "certificates": [],
          "keys": [],
          "secrets": [
            "Get",
            "List",
            "Set"
          ]
        }
      },
      {

        "permissions": {
          "certificates": [],
          "keys": [],
          "secrets": [
            "get"
          ]
        }
      }
    ],
    "enabledForDeployment": false,
    "enabledForDiskEncryption": false,
    "enabledForTemplateDeployment": false,
    "enableSoftDelete": true,
    "softDeleteRetentionInDays": 90,
    "enableRbacAuthorization": false,
    "vaultUri": "https://x.vault.azure.net/",
    "provisioningState": "Succeeded",
    "publicNetworkAccess": "Enabled"
  }
}

DEBUG: [Common.Authentication]: Authenticating using Account: x, environment: 'AzureCloud', tenant: x
DEBUG: 17:39:51 - [ConfigManager] Got nothing from [EnableLoginByWam], Module = [], Cmdlet = []. Returning default value [False].
DEBUG: 17:39:51 - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:x, Scopes:'https://graph.microsoft.com//.default',
AuthorityHost:'https://login.microsoftonline.com/', UserId: x
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://graph.microsoft.com//.default ] ParentRequestId:
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - bc919877-06f8-4fe5-b47e-add7a1f469f1] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - bc919877-06f8-4fe5-b47e-add7a1f469f1] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - bc919877-06f8-4fe5-b47e-add7a1f469f1] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - bc919877-06f8-4fe5-b47e-add7a1f469f1] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - bc919877-06f8-4fe5-b47e-add7a1f469f1] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z] Found 1 cache accounts and 0 broker accounts
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z] Returning 1 accounts
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 8af9dc1a-a226-4632-806f-ca62f94534b3] MSAL MSAL.Desktop with assembly version '4.49.1.0'.
CorrelationId(8af9dc1a-a226-4632-806f-ca62f94534b3)
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 8af9dc1a-a226-4632-806f-ca62f94534b3] === AcquireTokenSilent Parameters ===
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 8af9dc1a-a226-4632-806f-ca62f94534b3] LoginHint provided: False
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 8af9dc1a-a226-4632-806f-ca62f94534b3] Account provided: True
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 8af9dc1a-a226-4632-806f-ca62f94534b3] ForceRefresh: False
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 8af9dc1a-a226-4632-806f-ca62f94534b3]
=== Request Data ===
Authority Provided? - True
Scopes - https://graph.microsoft.com//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 8af9dc1a-a226-4632-806f-ca62f94534b3
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured:
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 8af9dc1a-a226-4632-806f-ca62f94534b3] === Token Acquisition (SilentRequest) started:
  Scopes: https://graph.microsoft.com//.default
 Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 8af9dc1a-a226-4632-806f-ca62f94534b3] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 8af9dc1a-a226-4632-806f-ca62f94534b3] Access token is not expired. Returning the found cache entry. [Current
time (08/04/2023 16:39:51) - Expiration Time (08/04/2023 17:52:02 +00:00) - Extended Expiration Time (08/04/2023 17:52:02 +00:00)]
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 8af9dc1a-a226-4632-806f-ca62f94534b3] Returning access token found in cache. RefreshOn exists ? False
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 8af9dc1a-a226-4632-806f-ca62f94534b3] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 8af9dc1a-a226-4632-806f-ca62f94534b3]
 === Token Acquisition finished successfully:
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-08-04 16:39:51Z - 8af9dc1a-a226-4632-806f-ca62f94534b3]  AT expiration time: 04/08/2023 17:52:02 +00:00, scopes: email openid
profile https://graph.microsoft.com//AuditLog.Read.All https://graph.microsoft.com//Directory.AccessAsUser.All https://graph.microsoft.com//.default. source: Cache
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://graph.microsoft.com//.default ] ParentRequestId:  ExpiresOn: 2023-08-04T17:52:02.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: x, UserId: x
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://graph.microsoft.com/v1.0/directoryObjects/x

Headers:
x-ms-client-request-id        : 420c422e-e162-4d79-8058-1c471a0cf65b
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Transfer-Encoding             : chunked
Strict-Transport-Security     : max-age=31536000
request-id                    : d9e5adf4-0fc6-4009-9b27-a76a400de0cd
client-request-id             : d9e5adf4-0fc6-4009-9b27-a76a400de0cd
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"UK South","Slice":"E","Ring":"3","ScaleUnit":"003","RoleInstance":"LO2PEPF00000862"}}
x-ms-resource-unit            : 1
OData-Version                 : 4.0
Cache-Control                 : no-cache
Date                          : Fri, 04 Aug 2023 16:39:51 GMT

Body:
{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#directoryObjects/$entity",
  "@odata.type": "#microsoft.graph.group",
  "deletedDateTime": null,
  "classification": null,
  "createdDateTime": "2022-09-13T14:49:13Z",
  "creationOptions": [],
  "expirationDateTime": null,
  "groupTypes": [],
  "isAssignableToRole": null,
  "mail": null,
  "mailEnabled": false,
  "mailNickname": "NotSet",
  "membershipRule": null,
  "membershipRuleProcessingState": null,
  "onPremisesDomainName": null,
  "onPremisesLastSyncDateTime": null,
  "onPremisesNetBiosName": null,
  "onPremisesSamAccountName": null,
  "onPremisesSecurityIdentifier": null,
  "onPremisesSyncEnabled": null,
  "preferredDataLocation": null,
  "preferredLanguage": null,
  "proxyAddresses": [],
  "renewedDateTime": "2022-09-13T14:49:13Z",
  "resourceBehaviorOptions": [],
  "resourceProvisioningOptions": [],
  "securityEnabled": true,
  "theme": null,
  "visibility": null,
  "serviceProvisioningErrors": [],
  "onPremisesProvisioningErrors": []
}

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/x/resourceGroups/x/providers/Microsoft.KeyVault/vaults/x?api-version=2022-07-01

Headers:
x-ms-client-request-id        : 420c422e-e162-4d79-8058-1c471a0cf65b
accept-language               : en-US

Body:
{
  "location": "westeurope",
  "tags": {
  },
  "properties": {
    "sku": {
      "name": "standard",
      "family": "A"
    },
    "accessPolicies": [
      {
        "objectId": "4282d26c-5ec5-4279-8ff5-639f68756ca9",
        "permissions": {
          "keys": [],
          "secrets": [
            "Get",
            "List",
            "Set"
          ],
          "certificates": [],
          "storage": []
        }
      },
      {
        "objectId": "3f617f10-edd8-4042-9db6-86f071e07891",
        "permissions": {
          "keys": [],
          "secrets": [
            "Get",
            "List",
            "Set"
          ],
          "certificates": [],
          "storage": []
        }
      },
      {
        "objectId": "ba065f66-7cf9-4816-b8bd-c052f83865a8",
        "permissions": {
          "keys": [],
          "secrets": [
            "get"
          ],
          "certificates": [],
          "storage": []
        }
      },
      {
        "objectId": "70c11990-a09a-47ea-bf0a-04184f4cb420",
        "permissions": {
          "keys": [
            "All"
          ],
          "secrets": [
            "All"
          ],
          "certificates": [
            "All"
          ],
          "storage": []
        }
      }
    ],
    "vaultUri": "https://xxxxxxxxxxx.vault.azure.net/",
    "enabledForDeployment": false,
    "enabledForDiskEncryption": false,
    "enabledForTemplateDeployment": false,
    "enableSoftDelete": true,
    "softDeleteRetentionInDays": 90,
    "enableRbacAuthorization": false,
    "networkAcls": {
      "IpRules": [],
      "bypass": "AzureServices",
      "defaultAction": "Allow",
      "ipRules": [],
      "virtualNetworkRules": []
    },
    "provisioningState": "Succeeded",
    "publicNetworkAccess": "Enabled"
  }
}

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Conflict

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : da5c86a9-df4e-4caf-a35b-58a0acf9dfd1
x-ms-correlation-request-id   : da5c86a9-df4e-4caf-a35b-58a0acf9dfd1
x-ms-routing-request-id       : UKSOUTH:20230804T163952Z:da5c86a9-df4e-4caf-a35b-58a0acf9dfd1
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Fri, 04 Aug 2023 16:39:51 GMT

Body:
{
  "error": {
    "code": "AmbiguousPolicyEvaluationPaths",
    "message": "The request content has one or more ambiguous paths: 'properties.networkAcls.ipRules' required for policy evaluation."
  }
}

DEBUG: 17:39:52 - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
Set-AzKeyVaultAccessPolicy : The request content has one or more ambiguous paths: 'properties.networkAcls.ipRules' required for policy evaluation.
At line:2 char:5
+     Set-AzKeyVaultAccessPolicy -ObjectId $AzADGroup.ObjectId -Permiss ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzKeyVaultAccessPolicy], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.SetAzureKeyVaultAccessPolicy
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.19041.3031
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3031
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.12.5     Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault...}
Script     4.10.1     Az.KeyVault                         {Add-AzKeyVaultCertificate, Add-AzKeyVaultCertificateContact, Add-AzKeyVaultKey, Add-AzKeyVaultManagedStorageAccount...}
Script     6.9.0      Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment...}
Binary     2.0.2.149  AzureADPreview                      {Add-AzureADAdministrativeUnitMember, Add-AzureADApplicationOwner, Add-AzureADApplicationPolicy, Add-AzureADDeviceRegisteredOwner...}
```

### Error output

```PowerShell
RequestId      : da5c86a9-df4e-4caf-a35b-58a0acf9dfd1
Message        : The request content has one or more ambiguous paths: 'properties.networkAcls.ipRules' required for policy evaluation.
ServerMessage  : AmbiguousPolicyEvaluationPaths: The request content has one or more ambiguous paths: 'properties.networkAcls.ipRules' required for policy evaluation.
                 (System.Collections.Generic.List`1[Microsoft.Rest.Azure.CloudError])
ServerResponse : {Conflict}
RequestMessage : {PUT https://management.azure.com/subscriptions/x/resourceGroups/x/providers/Microsoft.KeyVault/vaults/x?api-version=2022
                 -07-01}
InvocationInfo : {Set-AzKeyVaultAccessPolicy}
Line           :     Set-AzKeyVaultAccessPolicy -ObjectId $AzADGroup.ObjectId -PermissionsToSecrets All -PermissionsToKeys All -PermissionsToCertificates All -VaultName $EnvConfig.KeyVaultName
                 -ResourceGroupName $EnvConfig.ResourceGroupName

Position       : At line:2 char:5
                 +     Set-AzKeyVaultAccessPolicy -ObjectId $AzADGroup.ObjectId -Permiss ...
                 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Management.KeyVault.VaultsOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__17.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.KeyVault.VaultsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__5.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.KeyVault.VaultsOperationsExtensions.<CreateOrUpdateAsync>d__1.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.KeyVault.VaultsOperationsExtensions.CreateOrUpdate(IVaultsOperations operations, String resourceGroupName, String vaultName, VaultCreateOrUpdateParameters
                 parameters)
                    at Microsoft.Azure.Commands.KeyVault.Models.VaultManagementClient.UpdateVault(PSKeyVault existingVault, PSKeyVaultAccessPolicy[] updatedPolicies, Nullable`1 updatedEnabledForDeployment,
                 Nullable`1 updatedEnabledForTemplateDeployment, Nullable`1 updatedEnabledForDiskEncryption, Nullable`1 updatedSoftDeleteSwitch, Nullable`1 updatedPurgeProtectionSwitch, Nullable`1
                 updatedRbacAuthorization, Nullable`1 softDeleteRetentionInDays, PSKeyVaultNetworkRuleSet updatedNetworkAcls, IMicrosoftGraphClient graphClient)
                    at Microsoft.Azure.Commands.KeyVault.SetAzureKeyVaultAccessPolicy.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
```

**Comment by isra-fel** [comment] 2023-08-05 16:58
Thanks for reporting but this is duplicate of #22504

**Closed by isra-fel** 2023-08-05 16:58 UTC
Labels: bug, customer-reported

**Comment by BethanyZhou** [comment] 2023-08-07 05:50
Thanks for reporting this issue here.

Please expect this issue fixed in Az.KeyVault 4.10.2, which will be release within 3 business days. Please use Az.KeyVault 4.9.5 as workaround for the time being. Sorry for inconvenience.
