### ISSUE TITLE
[Az.Functions] Update Linux Dedicated create flow to set linuxFxVersion to runtime|runtimeVersion

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-powershell#10551] opened 2019-11-15 17:53 UTC
cc @ankitkumarr @Francisco-Gamino 

After ANT87 deploys, please update the create flow for linux dedicated apps.

**Comment by Francisco-Gamino** [comment] 2020-02-14 21:59
This is a duplicate of https://github.com/Azure/azure-powershell/issues/11112. Closing this issue.

**Closed by Francisco-Gamino** 2020-02-14 21:59 UTC
Labels: Az 4.x Preview, Functions, Service Attention
