### ISSUE TITLE
Az.Accounts 2.0.0-preview fails login with: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by LeonJansen** [Azure/azure-powershell#9568] opened 2019-07-08 13:45 UTC
## Description
When trying to login to Az using Connect-AzAccount -Credential it fails with the following error messsage:
```powershell
Connect-AzAccount : Object reference not set to an instance of an object.
At line:1 char:1
+ Connect-AzAccount -Credential $creds
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Connect-AzAccount], NullReferenceException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand
```
EDIT: This is a newly created tenant with no subscriptions, the error message indicates that there is problem with that.

## Steps to reproduce

```powershell
$creds = Get-Credential
Connect-AzAccount -Credential $creds
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      6.2.1
PSEdition                      Core
GitCommitId                    6.2.1
OS                             Linux 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:2…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```powershell
ModuleType Version    Name                                PSEdition ExportedCom
                                                                    mands
---------- -------    ----                                --------- -----------
Manifest   1.2.3.0    Microsoft.PowerShell.Archive        Desk      {Compress-…
Manifest   6.1.0.0    Microsoft.PowerShell.Host           Core      {Start-Tra…
Manifest   6.1.0.0    Microsoft.PowerShell.Management     Core      {Add-Conte…
Manifest   6.1.0.0    Microsoft.PowerShell.Security       Core      {Get-Crede…
Manifest   6.1.0.0    Microsoft.PowerShell.Utility        Core      {Export-Al…
Script     1.3.2      PackageManagement                   Desk      {Find-Pack…
Script     2.1.3      PowerShellGet                       Desk      {Find-Comm…
Script     0.0        PSDesiredStateConfiguration         Desk      {AddDscRes…
Script     2.0.0      PSReadLine                          Desk      {Get-PSRea…
Binary     1.1.2      ThreadJob                           Desk      Start-Thre…
Binary     1.5.1905.1 PartnerCenter.NetCore               Core,Desk {Add-Partn…
Script     2.0.0      Az.Accounts                         Core,Desk {Disable-A…
```

## Debug output

```
PS /> Connect-AzAccount -Credential $creds
DEBUG: 1:45:21 PM - Autosave setting from startup session: 'CurrentUser'
DEBUG: 1:45:21 PM - No autosave setting detected in environment variable 'AzContextAutoSave'. 
DEBUG: 1:45:21 PM - Using Autosave scope 'CurrentUser'
WARNING: No accounts found in the shared token cache; removing all user contexts.
WARNING: Unable to set default context 'Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureContext'.
Connect-AzAccount : Object reference not set to an instance of an object.
At line:1 char:1
+ Connect-AzAccount -Credential $creds
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Connect-AzAccount], NullReferenceException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand
 
DEBUG: 1:45:23 PM - ConnectAzureRmAccountCommand end processing.
DEBUG: 1:45:23 PM - ConnectAzureRmAccountCommand end processing.
```

## Error output

```
Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.ListTenants(String tenant)
                    at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.ListSubscriptions(String tenantIdOrDomain)
                    at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment environment, String tenantId, 
                 String subscriptionId, String subscriptionName, SecureString password, Boolean skipValidation, Action`1 promptAction, String name, Nullable`1 
                 shouldPopulateContextList)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass92_0.<ExecuteCmdlet>b__0(AzureRmProfile localProfile, 
                 RMProfileClient profileClient, String name)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass94_0.<SetContextWithOverwritePrompt>b__0(AzureRmProfile prof, 
                 RMProfileClient client)
                    at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.NullReferenceException
InvocationInfo : {Connect-AzAccount}
Line           : Connect-AzAccount -Credential $creds
Position       : At line:1 char:1
                 + Connect-AzAccount -Credential $creds
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 10
```

**Comment by markcowl** [comment] 2019-07-08 22:00
@LeonJansen Thanks, we will take a look.  It should be possible to login to a tenant with no subscription access - for data plane cmdlet support.

**Comment by cormacpayne** [comment] 2019-07-09 21:29
@LeonJansen I'm unable to reproduce this exception when using U/P authentication with an account that access to no subscriptions. Before running `Connect-AzAccount`, would you mind running `Get-AzContext -ListAvailable` and leaving a comment with the result? Also, since the preview does not currently support migrating the contents of the ADAL cache to MSAL, I would recommend just removing all of the existing contexts and starting fresh using the shared token cache. You can clear the contexts by running `Clear-AzContext -Scope CurrentUser -Force`.

**Comment by LeonJansen** [comment] 2019-07-10 09:02
@cormacpayne ```Get-AzContext -ListAvailable``` Doesn't show any output. So there is no context there. I still get the same error message tho. Even cleared the az-context using ```Clear-AzContext```

```powershell
PS /> Connect-AzAccount -Credential $mycreds
WARNING: No accounts found in the shared token cache; removing all user contexts.
Connect-AzAccount : Object reference not set to an instance of an object.
At line:1 char:1
+ Connect-AzAccount -Credential $mycreds
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Connect-AzAccount], NullReferenceException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand
```

I tried the same with an account that has an Azure Subscription, but the problem still remains. So i think it has nothing to do with not having a Subscription. I think the problem is elsewhere. 

Stacktrace from the account with a subscription:

```powershell
Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.Azure.Commands.ResourceManager.Common.RMProfil
                 eClient.ListTenants(String tenant)
                    at Microsoft.Azure.Commands.ResourceManager.Common.RMProfil
                 eClient.ListSubscriptions(String tenantIdOrDomain)
                    at Microsoft.Azure.Commands.ResourceManager.Common.RMProfil
                 eClient.Login(IAzureAccount account, IAzureEnvironment 
                 environment, String tenantId, String subscriptionId, String 
                 subscriptionName, SecureString password, Boolean 
                 skipValidation, Action`1 promptAction, String name, 
                 Nullable`1 shouldPopulateContextList)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCo
                 mmand.<>c__DisplayClass92_0.<ExecuteCmdlet>b__0(AzureRmProfile
                  localProfile, RMProfileClient profileClient, String name)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCo
                 mmand.<>c__DisplayClass94_0.<SetContextWithOverwritePrompt>b__
                 0(AzureRmProfile prof, RMProfileClient client)
                    at Microsoft.Azure.Commands.Profile.Common.AzureContextModi
                 ficationCmdlet.ModifyContext(Action`2 contextAction)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCo
                 mmand.SetContextWithOverwritePrompt(Action`3 setContextAction)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCo
                 mmand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletE
                 xtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletE
                 xtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 
                 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletE
                 xtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePS
                 Cmdlet.ProcessRecord()
Exception      : System.NullReferenceException
InvocationInfo : {Connect-AzAccount}
Line           : Connect-AzAccount -Credential $leicred
Position       : At line:1 char:1
                 + Connect-AzAccount -Credential $leicred
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 11
```

**Comment by markcowl** [comment] 2019-07-11 23:45
@LeonJansen How are you creating the credential?  Does it have a SecureString password, or just a user id?

**Comment by LeonJansen** [comment] 2019-07-12 07:23
@markcowl Yes i am, i also tried the following but still the same error:

```powershell
$Username = "test@test.com"
$Password = "password"
$secpasswd = ConvertTo-SecureString $Password -AsPlainText -Force
$mycreds = New-Object System.Management.Automation.PSCredential ($Username, $secpasswd)
Connect-AzAccount -Credential $mycreds
```

**Comment by aavisek** [comment] 2019-07-18 08:30
I am also getting the same error. 

Connect-AzAccount : Object reference not set to an instance of an object.
At line:26 char:1
+ Connect-AzAccount -CertificateThumbprint $Thumbprint -ApplicationId $ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Connect-AzAccount], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand
 
It's working fine with module 1.6

**Comment by tafzal25** [comment] 2019-08-05 20:22
Hello Guys, 

I was able to reproduce the issue with a slightly different steps. 
We are in the process of migrating from AzureRM to Az. In version AzureRM (6.13.1) and Az(2.4.0) we are not able to reproduce the issue with the command shown below. . However, when I upgrade the machine to use Az 2.5.0 I was getting the following error. 

Connect-AzAccount -TenantId $TenantID -Environment $environment -Subscription $subid 

Connect-AzAccount : Object reference not set to an instance of an object.
At line:1 char:1
+ Connect-AzAccount -TenantId "xxxxx-xxxxx-xxx-xxxx-xxxxxxxx" -E ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-AzAccount], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand

**Comment by CC-Mike** [comment] 2019-09-10 11:15
Hi,

we have exactly the same issue, with a fresh new install of the az module. No AzureRM module was installed before.

`PS C:\> $mycreds = New-Object System.Management.Automation.PSCredential ("mirichte@CCPlatMgmt.onmicrosoft.com", $secpasswd)
PS C:\> Connect-AzAccount -Credential $mycreds
Connect-AzAccount : Object reference not set to an instance of an object.
At line:1 char:1
+ Connect-AzAccount -Credential $mycreds
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Connect-AzAccount], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand
`

Any hints?

Thanks,
Mike

**Comment by markcowl** [comment] 2019-09-17 07:18
@CC-Mike @tafzal25   If you can get debug traces ```$DebugPreference="Continue"```, and the result of running ```Resolve-AzError``` after the error occurs, it would be tremendously helpful.

**Comment by erich-wang** [comment] 2019-09-19 00:46
@LeonJansen , the issue is fixed in the next preview release which will be release this Fall.

**Comment by erich-wang** [comment] 2019-12-02 06:51
Assign to Yeming to track  the release of MSAL

**Comment by dingmeng-xue** [comment] 2020-06-22 03:24
This issue is resolved in the latest Az.Accounts 2.0.x-preview version.

**Closed by dingmeng-xue** 2020-06-22 03:24 UTC
Labels: Azure PS Team, MSAL
