### ISSUE TITLE
Get-AzureAutomationAccount does not find all accounts in subscription

### ISSUE THREAD

**Issue by JakobGSvendsen** [Azure/azure-powershell#474] opened 2015-06-09 10:18 UTC
It seems that my azure powershell cannot see all of my auotmation accounts.

I had 2, but it only showed 1.

For testing I deleted this one account, now it does not show any account (first it showed the old one as NotFound, and now It shows no account at all.)

As picture shows: I do have the account called "RunbookGuruAutomation" 
but it does not show in powershell which means I cannot run any commands against this account

![azureautomatiobaccount](https://cloud.githubusercontent.com/assets/3460807/8055662/6dc7e184-0ea1-11e5-8441-ec74d4e9623c.jpg)

when i try starting a runbook:

PS C:\Windows\system32> Start-AzureAutomationRunbook -Name "Expand-VMDrive" -RunOn "DemoGroup" -AutomationAccountName "RunbookGuruAutomation" -Parameters $params

Start-AzureAutomationRunbook : The Runbook was not found. Runbook name: Expand-VMDrive.
At line:1 char:1
+ Start-AzureAutomationRunbook -Name "Expand-VMDrive" -RunOn "DemoGroup" -Automati ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Start-AzureAutomationRunbook], ResourceCommonException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.StartAzureAutomationRunbook

**Comment by jodoglevy** [comment] 2015-06-10 05:12
Hi Jakob,

Was the 'RunbookGuruAutomation' account created through the new Azure preview portal? If so, that would be the reason for this. By design, Azure Automation accounts created through ARM will not show up in RDFE. Please see https://social.msdn.microsoft.com/Forums/en-US/7a0f00cf-4afb-4822-a8cc-d5f35d760e56/automation-cmdlets-not-working-request-to-a-downlevel-service-failed?forum=azureautomation for more info.

We plan to document this better shortly. Here's the text we plan to document:

**Automation accounts, and the resources they contain, that are created with the Azure preview portal cannot be accessed in the Azure portal. If you want to manage these accounts or their resources with Windows PowerShell, you must use the Azure Resource Manager modules. 

Automation accounts created with the Azure portal can be managed by either portal and either set of cmdlets. Once the account is created, it makes no difference how you create and manage resources within the account. If you are planning to continue to use the Azure portal, then you should use it instead of the Azure preview portal to create any Automation accounts.**

**Comment by JakobGSvendsen** [comment] 2015-06-10 09:00
Yes that is the case. Kind of weird if you ask me. I will not recommend anyone to use the preview portal yet then, if they want full functionality.

Thanks joe!

Too bad i have to redo all my runbooks and assets again.  ;-)

**Comment by devigned** [comment] 2015-06-10 14:54
Based on the comment by @jodoglevy, I'm going to close this issue as it is not a "bug", but certainly an usability issue.

@JakobGSvendsen, thank you for opening this and likely helping someone else figure this out in the future.

**Closed by devigned** 2015-06-10 14:54 UTC
Labels: Automation

**Comment by jodoglevy** [comment] 2015-06-12 00:16
This is now documented: https://azure.microsoft.com/en-us/documentation/articles/automation-configuring/

**Comment by JakobGSvendsen** [comment] 2015-07-13 13:57
seems to be trouble with this.

If I create the automation account in the old portal, I cannot select resource group and I automatically places it in a random generated resource group, and then i need to use this auto generated resource group name in all commands.
(example: OaaSCS2WT6LFDIBA25B3YWV7UA37577W3S7SWTQ5SJVJUDRBZHKSSWDXNA-West-Europe)

When are you planning on releasing ARM cmdlets for automation? 

I feel a bit bad trying to sell this product to my customers with so bad support/usability.
I mean, the automation is IN the new portal. all your demonstrations shows that we should create it through the new portal. But then after weeks of work, customer discovers that the account was not properly created because of this issue.

**Comment by jodoglevy** [comment] 2015-07-25 15:04
The ASM (ADFE) cmdlets don't require you to use resource group names anywhere, so I'm not sure what you mean when you say you have to use the resource group name everywhere. Do you mean our ARM cmdlets make you do so?

To answer your question, we have just released the full set of Azure Automation cmdlets as ARM cmdlets in the last week or so. Please check WebPI for the latest.

The issues you are talking about only happen when you need to manage an ARM automation account through ASM / the current Azure portal, or an ASM automation account through ARM / the Azure preview portal. Now that the full set of Azure Automation ARM cmdlets are out, hopefully there should be less of a reason to need to do this cross-ARM/ASM use, making things easier for your customers.

**Comment by JakobGSvendsen** [comment] 2015-08-03 11:02
Oh yes I meant the ARM cmdlets. sorry about that.

Great news about the full set of cmdlets! .. perfect timing! ;-)

Thanks!
