### ISSUE TITLE
Does not show reservations purchased for SQLDB

### ISSUE THREAD

**Issue by amitkumardokwal** [Azure/azure-powershell#21843] opened 2023-05-17 09:09 UTC
### Description

We have SQL DB Reservations, when I run Get-AzReservation, it shows list of all reservations except SQL DB. I have access to this reservation.

### Issue script & Debug output

```PowerShell
$AllReservations = Get-AzReservation
    $reslist = @()
    foreach ($rev in $AllReservations) {
        if ($rev.ProvisioningState -like "Succeeded") {        
            $reslist += $rev    
        }
    }
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Get-AzReservation                                  0.12.0     Az.Reservations
```

### Error output

```PowerShell
No output for reservations purchased for SQL DB
```

**Comment by navba-MSFT** [comment] 2023-05-22 04:21
@amitkumardokwal  Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment] 2023-05-23 06:30
@amitkumardokwal AFAIK virtual machines (VMs), Azure Databricks, or Azure Kubernetes Service (AKS), SQL Data Warehouse, and Cosmos DB resources will be listed while running Get-AzReservation PS cmdlet. Could you run the cmd `$DebugPreference="Continue" `and please share the debug output with us ?

**Comment by amitkumardokwal** [comment] 2023-05-23 14:56
Below is the output, I have removed the reservations details.
I searched the output (Formatted in JSON and Tabular), it does not contain the SQL DB Reservation.

DEBUG: [CmdletBeginProcessing]: Starting command
DEBUG: CmdletBeginProcessing: 
DEBUG: CmdletProcessRecordStart: 
DEBUG: Client side pagination is enabled for this cmdlet
DEBUG: CmdletGetPipeline: 
DEBUG: CmdletBeforeAPICall: 
DEBUG: URLCreated: /providers/Microsoft.Capacity/reservations?api-version=2022-11-01
DEBUG: RequestCreated: /providers/Microsoft.Capacity/reservations?api-version=2022-11-01      
DEBUG: HeaderParametersAdded: 
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/providers/Microsoft.Capacity/reservations?api-version=2022-11-01 

Headers:
x-ms-unique-id                : 13,14
x-ms-client-request-id        : db3d4a84-6013-4748-91b8-acd2e4441066
CommandName                   : Get-AzReservation
FullCommandName               : Get-AzReservation_List1
ParameterSetName              : __AllParameterSets
User-Agent                    : AzurePowershell/v0.0.0,PSVersion/v7.3.4,Az.Reservations/0.12.0

Body:



DEBUG: BeforeCall: 
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-request-id               : ab1e9bc3-1202-4427-8138-6e483cf7dea1
x-ms-correlation-request-id   : ab1e9bc3-1202-4427-8138-6e483cf7dea1
x-ms-routing-request-id       : GERMANYWESTCENTRAL:20230523T074433Z:ab1e9bc3-1202-4427-8138-6e483cf7dea1
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Tue, 23 May 2023 07:44:32 GMT

Body:
{all reservations data, except SQL DB}

DEBUG: ResponseCreated: 
DEBUG: BeforeResponseDispatch: 

DEBUG: Finally: 
DEBUG: CmdletAfterAPICall: 
DEBUG: [CmdletProcessRecordAsyncEnd]: Finish HTTP process
DEBUG: CmdletProcessRecordAsyncEnd: 
DEBUG: CmdletProcessRecordEnd: 
DEBUG: AzureQoSEvent:  Module: Az.Reservations:0.12.0; CommandName: Get-AzReservation; PSVersion: 7.3.4; IsSuccess: True; Duration: 00:00:01.2049483

Below commands gives all the reservations except the SQL DB.
az reservations list => does not show the SQL Reservation we purchased

**Comment by amitkumardokwal** [comment] 2023-05-24 15:46
Update: I tested the below API and this too does not show the SQL DB reservation
https://learn.microsoft.com/en-us/rest/api/consumption/reservations-summaries/list?tabs=HTTP#reservationsummariesmonthlywithbillingaccountid

**Comment by navba-MSFT** [comment] 2023-05-25 07:38
@amitkumardokwal Thanks for your reply. As per the [REST API specs swagger](https://github.com/Azure/azure-rest-api-specs/blob/4f4073bdb028bc84bc3e6405c1cbaf8e89b83caf/specification/reservations/resource-manager/Microsoft.Capacity/stable/2022-11-01/reservations.json#LL1222C5-L1222C5), Below are the supported reserved resource types:
```
"ReservedResourceType": {
      "type": "string",
      "description": "The type of the resource that is being reserved.",
      "enum": [
        "VirtualMachines",
        "SqlDatabases",
        "SuseLinux",
        "CosmosDb",
        "RedHat",
        "SqlDataWarehouse",
        "VMwareCloudSimple",
        "RedHatOsa",
        "Databricks",
        "AppService",
        "ManagedDisk",
        "BlockBlob",
        "RedisCache",
        "AzureDataExplorer",
        "MySql",
        "MariaDb",
        "PostgreSql",
        "DedicatedHost",
        "SapHana",
        "SqlAzureHybridBenefit",
        "AVS",
        "DataFactory",
        "NetAppStorage",
        "AzureFiles",
        "SqlEdge",
        "VirtualMachineSoftware"
      ]
```
I am doing some research on this. I will keep you posted about the progress.

**Comment by navba-MSFT** [comment] 2023-05-29 04:09
@amitkumardokwal Could you please share the below information over email ?
1. Your tenant ID.
2. You subscription ID
3. Your reservation order ids of the SQL Reservations.

**Comment by navba-MSFT** [comment] 2023-05-31 04:00
@amitkumardokwal I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please share the above requested details. Awaiting your reply.

**Comment by amitkumardokwal** [comment] 2023-05-31 13:17
@navba-MSFT I have shared the details.

**Comment by navba-MSFT** [comment] 2023-06-01 03:50
@amitkumardokwal Thanks for sharing the details. I am discussing this internally with the Product Owners. I will keep you posted about the updates.

**Comment by navba-MSFT** [comment] 2023-06-07 07:02
@amitkumardokwal We had a look at the debug traces and our backend logs. This issue is caused by a bug in our code that we are fetching an incomplete list of Reservations from our database to return to user in some cases. 
This bug was caught last week and the fixed was checked in already. Currently, the fix is being rolled out and will reach all regions by end of week. So you should be able to get expected result by that time.

We sincerely apologize for the inconvenience caused in this regard.

**Closed** 2023-06-12 07:48 UTC
Labels: Reservations, bug, customer-reported, CXP Attention, issue-addressed
