### ISSUE TITLE
Login-AzureRmAccount should accept position PSCredential parameter

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2421] opened 2016-06-07 18:47 UTC
```
Login-AzureRmAccount (Get-Credential)
```

> Add-AzureRmAccount : A positional parameter cannot be found that accepts argument

![image](https://cloud.githubusercontent.com/assets/466713/15870576/f7013d94-2cad-11e6-9bc4-4e45a8d1fafb.png)

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by markcowl** [comment] 2016-06-09 18:51
Closing as duplicate of #2048

**Closed by markcowl** 2016-06-09 18:51 UTC
