### ISSUE TITLE
Invoke-AzVMRunCommand taking 1.30 hours to execute a script.

### ISSUE THREAD

**Issue by ziaul-siddiqui-bzy** [Azure/azure-powershell#24164] opened 2024-02-14 14:19 UTC
### Type of issue

Other (describe below)

### Feedback

I've around 300 VM in Azure, and i am trying to get last login information using script.ps1 file.
when i try to execute .ps1 file in Invoke-AzVMRunCommand. usually it takes a minute to complete on one VM. But randomly some VMs it is taking 1.5 hours which is leading failed to my GitHub workflow.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/az.compute/invoke-azvmruncommand?view=azps-11.3.0&viewFallbackFrom=azps-11.0.0

### Content source URL

https://github.com/Azure/azure-powershell/blob/main/src/Compute/Compute/help/Invoke-AzVMRunCommand.md

### Author

@mikefrobbins

### Document Id

e7d2f266-0b25-3b15-6278-40c58d41600d

**Comment by isra-fel** [comment] 2024-02-18 03:14
@ziaul-siddiqui-bzy thanks for the feedback. I'll loop in the Compute team. At the same time it would be helpful if you could provide more context such as the content of the script ran on your VMs, the logs of the run, the version of Az modules.

**Comment by sandeepraichura** [comment] 2024-03-07 16:26
thanks for reporting, we'll look into it.

**Comment by GabstaMSFT** [comment] 2024-06-27 16:17
@ziaul-siddiqui-bzy are you still experiencing this issue? If so can you easily reproduce the issue?

**Comment by GabstaMSFT** [comment] 2024-07-25 14:51
@ziaul-siddiqui-bzy are you able to reproduce this issue?  Can you provide steps you take to reproduce it?

**Comment by GabstaMSFT** [comment] 2024-08-06 15:26
@ziaul-siddiqui-bzy I haven’t been able to reach you in my last few attempts. Perhaps this is a bad time for you right now due to other obligations or you no longer need assistance. To avoid further ‘spam’ from me trying to contact you I will be closing your issue for now.

Your issue is important to us, and we want to ensure you do get the help you need so if at any time you want to continue working on this issue, please reopen the issue and we would be happy to continue to assist you.

**Closed by GabstaMSFT** 2024-08-06 15:26 UTC
Labels: Compute - VM, Service Attention, bug, customer-reported
