### ISSUE TITLE
New-AzureRmADApplication is throwing an exception with Powershell deploment from VS 2015

### ISSUE THREAD

**Issue by reddaiahnethi** [Azure/azure-powershell#2140] opened 2016-04-25 04:41 UTC

**Comment by reddaiahnethi** [comment] 2016-04-25 04:46
New-AzureRmADApplication is throwing an error as below, if we deploy Powershell from Visual Studio 2015.
Please see the error details below 

New-AzureRmADApplication -DisplayName "AADforOMSExtraction" -HomePage $AADURL -IdentifierUris $AADURL -Password $Password 

New-AzureRmADApplication : Unable to cast object of type 'Microsoft.Azure.TokenCloudCredentials' to type 'Microsoft.Azure.Common.Authentication.AccessTokenCredential'.


But, if we run the powershell outside of VS and giving credentials manually

**Comment by markcowl** [comment] 2016-04-27 19:43
@reddaiahnethi This is an issue with VS integration with Azure PowerShell.  The problem is that the token provided by VS cannot be used with the graph API cmdlets, as it has the wrong audience

**Comment by markcowl** [comment] 2016-05-02 23:11
@reddaiahnethi The solution is to log in with standard PowerShell credentials.  Putting on the backlog (no solution expected in next 3 releases)

**Comment by markcowl** [comment] 2017-05-15 18:55
No reports for over a year.  Closing.

**Closed by markcowl** 2017-05-15 18:55 UTC
Labels: Team

**Comment by ehrnst** [comment] 2018-03-23 08:24
I am trying to programmatic add an application and a service pricipal in multiple tenants. Authentication is done with a multi tenant app and user, getting token from Rest.

I am facing the same issue here when creating the app using New-AzureRmADApplication. I am trying to understand if this is by design, or was the intention to fix it?

**Comment by rafnijs** [comment] 2018-06-25 07:30
I have the same issue from VS:
New-AzureRmADApplication : Value cannot be null.
- Parameter name: token

any solutions or advise?

**Comment by jbender-Tallan** [comment] 2018-08-02 20:54
Same issue from VS 2017:
Get-AzureRmADApplication : Value cannot be null.
Parameter name: token
