### ISSUE TITLE
AzureStack: ADFS: Get-AzureRmRoleAssignement throws GUID error

### ISSUE THREAD

**Issue by viananth** [Azure/azure-powershell#5229] opened 2018-01-04 22:10 UTC
### Cmdlet(s)
Get-AzureRmRoleAssignement

### PowerShell Version
5.1.14393.1910

### Module Version
Azure RM 1.2.11

### OS Version
10.0.14393.1910

### Description
Get-AzureRmRoleAssignment tries to convert Object Id (which is SID) to Guid and throws the following error though all the role assignments were returned correctly:

> Get-AzureRmRoleAssignment : Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).

### Debug Output

`PS C:\Users\AzureStackAdmin\Documents\AzureStack-Tools-master> Get-AzureRmRoleAssignment -Scope "/subscriptions/114fdf88-3d83-4b87-88ab-db94d653e369" -debug
`
DEBUG: 1:23:07 PM - GetAzureRoleAssignmentCommand begin processing with ParameterSet 'ScopeParameterSet'.
DEBUG: 1:23:10 PM - using account id 'cloudadmin@azurestack.local'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'cloudadmin@azurestack.local', environment: 'AzureStackAdmin', tenant
: 'e585a25e-1fe3-4a10-9060-d81cbc7c87f4'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 01/04/2018 21:23:10: c4db7530-e4c4-4088-acbd-6963bc839ef6 - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://adfs.local.azurestack.external/adfs/e585a25e-1fe3-4a10-9060-d81cbc7c87f4/
	Resource: https://graph.local.azurestack.external/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (2 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 01/04/2018 21:23:10: c4db7530-e4c4-4088-acbd-6963bc839ef6 - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 01/04/2018 21:23:10: c4db7530-e4c4-4088-acbd-6963bc839ef6 - TokenCache: An item matching the requested resource was found in
 the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 01/04/2018 21:23:10: c4db7530-e4c4-4088-acbd-6963bc839ef6 - TokenCache: 27.798864925 minutes left until token in cache expir
es

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 01/04/2018 21:23:10: c4db7530-e4c4-4088-acbd-6963bc839ef6 - TokenCache: A matching item (access token or refresh token or bo
th) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 01/04/2018 21:23:10: c4db7530-e4c4-4088-acbd-6963bc839ef6 - AcquireTokenHandlerBase: === Token Acquisition finished successf
ully. An access token was retuned:
	Access Token Hash: yi0pvvFXZDqdbRKIpF8t/qqR+zz1QJ1U0E7SkmTDAiE=
	Refresh Token Hash: ED0uiSSC8AC3jdMg/KZBIpRwkOtM4WJV538XzGJXK30=
	Expiration Time: 01/04/2018 21:50:58 +00:00
	User Hash: CdKd4TxQZMyuxI5X7W1GN3p+Z69IKNlTce2deM2pqQE=
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 01/04/2018 21:23:10:  - TokenCache: Serializing token cache with 2 items.

DEBUG: [Common.Authentication]: Authenticating using Account: 'cloudadmin@azurestack.local', environment: 'AzureStackAdmin', tenant
: 'e585a25e-1fe3-4a10-9060-d81cbc7c87f4'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 01/04/2018 21:23:10: 365e6f3f-93bc-4cf1-9209-0b4c7d36b41b - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://adfs.local.azurestack.external/adfs/e585a25e-1fe3-4a10-9060-d81cbc7c87f4/
	Resource: https://adminmanagement.adfs.azurestack.local/e585a25e-1fe3-4a10-9060-d81cbc7c87f4
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (2 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 01/04/2018 21:23:10: 365e6f3f-93bc-4cf1-9209-0b4c7d36b41b - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 01/04/2018 21:23:10: 365e6f3f-93bc-4cf1-9209-0b4c7d36b41b - TokenCache: An item matching the requested resource was found in
 the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 01/04/2018 21:23:10: 365e6f3f-93bc-4cf1-9209-0b4c7d36b41b - TokenCache: 27.5902588283333 minutes left until token in cache e
xpires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 01/04/2018 21:23:10: 365e6f3f-93bc-4cf1-9209-0b4c7d36b41b - TokenCache: A matching item (access token or refresh token or bo
th) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 01/04/2018 21:23:10: 365e6f3f-93bc-4cf1-9209-0b4c7d36b41b - AcquireTokenHandlerBase: === Token Acquisition finished successf
ully. An access token was retuned:
	Access Token Hash: N7LyalAMcq3Aq4MUZFcUchvwLWjU0M5WB4jQByb/8G4=
	Refresh Token Hash: ED0uiSSC8AC3jdMg/KZBIpRwkOtM4WJV538XzGJXK30=
	Expiration Time: 01/04/2018 21:50:45 +00:00
	User Hash: CdKd4TxQZMyuxI5X7W1GN3p+Z69IKNlTce2deM2pqQE=
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 01/04/2018 21:23:10:  - TokenCache: Serializing token cache with 2 items.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 01/04/2018 21:23:10: 4db93b94-6042-44ea-99cd-fc739d22189b - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://adfs.local.azurestack.external/adfs/e585a25e-1fe3-4a10-9060-d81cbc7c87f4/
	Resource: https://adminmanagement.adfs.azurestack.local/e585a25e-1fe3-4a10-9060-d81cbc7c87f4
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (2 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 01/04/2018 21:23:10: 4db93b94-6042-44ea-99cd-fc739d22189b - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 01/04/2018 21:23:10: 4db93b94-6042-44ea-99cd-fc739d22189b - TokenCache: An item matching the requested resource was found in
 the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 01/04/2018 21:23:10: 4db93b94-6042-44ea-99cd-fc739d22189b - TokenCache: 27.5902588283333 minutes left until token in cache e
xpires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 01/04/2018 21:23:10: 4db93b94-6042-44ea-99cd-fc739d22189b - TokenCache: A matching item (access token or refresh token or bo
th) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 01/04/2018 21:23:10: 4db93b94-6042-44ea-99cd-fc739d22189b - AcquireTokenHandlerBase: === Token Acquisition finished successf
ully. An access token was retuned:
	Access Token Hash: N7LyalAMcq3Aq4MUZFcUchvwLWjU0M5WB4jQByb/8G4=
	Refresh Token Hash: ED0uiSSC8AC3jdMg/KZBIpRwkOtM4WJV538XzGJXK30=
	Expiration Time: 01/04/2018 21:50:45 +00:00
	User Hash: CdKd4TxQZMyuxI5X7W1GN3p+Z69IKNlTce2deM2pqQE=
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 01/04/2018 21:23:10:  - TokenCache: Serializing token cache with 2 items.

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://adminmanagement.local.azurestack.external//subscriptions/114fdf88-3d83-4b87-88ab-db94d653e369/providers/Microsoft.Authoriza
tion/roleAssignments?api-version=2015-07-01

Headers:
x-ms-client-request-id        : d87e0340-8772-4792-b62b-a3d9170ef696
accept-language               : en-US

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-request-id               : 5d76976a-13bd-46ef-8d97-299aae0308aa
x-ms-gateway-ESMET            : DLT=0;PAS=51;DPT=47;GPT=0;SPT=0
x-ms-gateway-ESDIM            : Result=S;RT=RoleA:GetRo;R=pasfe;RI=onebox;SC=OK;SliceKind=Test;FE=;LPSS=0;MPS=Master;DLOT=SRA,SRA;U
F=0;LEUT=0;Version=V2
x-ms-gateway-service-instanceid: onebox
X-Content-Type-Options        : nosniff
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-reads: 14869
x-ms-correlation-request-id   : 2114bcdf-9069-479a-9a07-45972514959b
x-ms-routing-request-id       : LOCAL:20180104T212310Z:2114bcdf-9069-479a-9a07-45972514959b
Cache-Control                 : no-cache
Date                          : Thu, 04 Jan 2018 21:23:10 GMT
Server                        : Microsoft-IIS/10.0

Body:
{
  "value": [
    {
      "properties": {
        "roleDefinitionId": "/subscriptions/114fdf88-3d83-4b87-88ab-db94d653e369/providers/Microsoft.Authorization/roleDefinitions/
8e3af657-a8ff-443c-a75c-2fe8c4bcb635",
        "principalId": "S-1-5-21-2060287033-2409276391-3379839450-1333",
        "scope": "/subscriptions/114fdf88-3d83-4b87-88ab-db94d653e369",
        "createdOn": "2017-11-30T10:33:54.0950233Z",
        "updatedOn": "2017-11-30T10:33:54.0950233Z",
        "createdBy": "S-1-5-21-2060287033-2409276391-3379839450-1214",
        "updatedBy": "S-1-5-21-2060287033-2409276391-3379839450-1214"
      },
      "id": "/subscriptions/114fdf88-3d83-4b87-88ab-db94d653e369/providers/Microsoft.Authorization/roleAssignments/1867f7ea-088d-4e
17-8a1d-10ea3a94e7a7",
      "type": "Microsoft.Authorization/roleAssignments",
      "name": "1867f7ea-088d-4e17-8a1d-10ea3a94e7a7"
    },
    {
      "properties": {
        "roleDefinitionId": "/subscriptions/114fdf88-3d83-4b87-88ab-db94d653e369/providers/Microsoft.Authorization/roleDefinitions/
b24988ac-6180-42a0-ab88-20f7382dd24c",
        "principalId": "S-1-5-21-2060287033-2409276391-3379839450-1325",
        "scope": "/subscriptions/114fdf88-3d83-4b87-88ab-db94d653e369",
        "createdOn": "2017-11-30T11:06:10.399106Z",
        "updatedOn": "2017-11-30T11:06:10.399106Z",
        "createdBy": "",
        "updatedBy": ""
      },
      "id": "/subscriptions/114fdf88-3d83-4b87-88ab-db94d653e369/providers/Microsoft.Authorization/roleAssignments/f9bdf0ff-316b-41
3f-9d50-0e8fb52d4b89",
      "type": "Microsoft.Authorization/roleAssignments",
      "name": "f9bdf0ff-316b-413f-9d50-0e8fb52d4b89"
    },
    {
      "properties": {
        "roleDefinitionId": "/subscriptions/114fdf88-3d83-4b87-88ab-db94d653e369/providers/Microsoft.Authorization/roleDefinitions/
b24988ac-6180-42a0-ab88-20f7382dd24c",
        "principalId": "S-1-5-21-2060287033-2409276391-3379839450-1335",
        "scope": "/subscriptions/114fdf88-3d83-4b87-88ab-db94d653e369",
        "createdOn": "2017-11-30T10:36:40.9648599Z",
        "updatedOn": "2017-11-30T10:36:40.9648599Z",
        "createdBy": "",
        "updatedBy": ""
      },
      "id": "/subscriptions/114fdf88-3d83-4b87-88ab-db94d653e369/providers/Microsoft.Authorization/roleAssignments/21ceb846-e91c-45
b4-89d5-87fe921a103a",
      "type": "Microsoft.Authorization/roleAssignments",
      "name": "21ceb846-e91c-45b4-89d5-87fe921a103a"
    },
    {
      "properties": {
        "roleDefinitionId": "/subscriptions/114fdf88-3d83-4b87-88ab-db94d653e369/providers/Microsoft.Authorization/roleDefinitions/
b24988ac-6180-42a0-ab88-20f7382dd24c",
        "principalId": "S-1-5-21-2060287033-2409276391-3379839450-1349",
        "scope": "/subscriptions/114fdf88-3d83-4b87-88ab-db94d653e369",
        "createdOn": "2018-01-04T20:44:25.8387359Z",
        "updatedOn": "2018-01-04T20:44:25.8387359Z",
        "createdBy": "S-1-5-21-2060287033-2409276391-3379839450-1214",
        "updatedBy": "S-1-5-21-2060287033-2409276391-3379839450-1214"
      },
      "id": "/subscriptions/114fdf88-3d83-4b87-88ab-db94d653e369/providers/Microsoft.Authorization/roleAssignments/42a43bec-0deb-49
32-a216-ac2378b3f0f2",
      "type": "Microsoft.Authorization/roleAssignments",
      "name": "42a43bec-0deb-4932-a216-ac2378b3f0f2"
    }
  ],
  "nextLink": null
}

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 01/04/2018 21:23:10: 580b6944-f1cf-4c4b-b2e9-6471092d837b - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://adfs.local.azurestack.external/adfs/e585a25e-1fe3-4a10-9060-d81cbc7c87f4/
	Resource: https://adminmanagement.adfs.azurestack.local/e585a25e-1fe3-4a10-9060-d81cbc7c87f4
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (2 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 01/04/2018 21:23:10: 580b6944-f1cf-4c4b-b2e9-6471092d837b - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 01/04/2018 21:23:10: 580b6944-f1cf-4c4b-b2e9-6471092d837b - TokenCache: An item matching the requested resource was found in
 the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 01/04/2018 21:23:10: 580b6944-f1cf-4c4b-b2e9-6471092d837b - TokenCache: 27.588696445 minutes left until token in cache expir
es

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 01/04/2018 21:23:10: 580b6944-f1cf-4c4b-b2e9-6471092d837b - TokenCache: A matching item (access token or refresh token or bo
th) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 01/04/2018 21:23:10: 580b6944-f1cf-4c4b-b2e9-6471092d837b - AcquireTokenHandlerBase: === Token Acquisition finished successf
ully. An access token was retuned:
	Access Token Hash: N7LyalAMcq3Aq4MUZFcUchvwLWjU0M5WB4jQByb/8G4=
	Refresh Token Hash: ED0uiSSC8AC3jdMg/KZBIpRwkOtM4WJV538XzGJXK30=
	Expiration Time: 01/04/2018 21:50:45 +00:00
	User Hash: CdKd4TxQZMyuxI5X7W1GN3p+Z69IKNlTce2deM2pqQE=
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 01/04/2018 21:23:10:  - TokenCache: Serializing token cache with 2 items.

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://adminmanagement.local.azurestack.external//subscriptions/114fdf88-3d83-4b87-88ab-db94d653e369/providers/Microsoft.Authoriza
tion/roleDefinitions?$filter=atScopeAndBelow()&api-version=2015-07-01

Headers:
x-ms-client-request-id        : a300448b-17ad-4cca-b5b1-3514dee5496d
accept-language               : en-US

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-request-id               : 080d227f-1928-4b93-8dd0-86717b5adaf6
x-ms-gateway-ESMET            : DLT=0;PAS=6;DPT=4;GPT=0;SPT=0
x-ms-gateway-ESDIM            : Result=S;RT=RoleD:GetRo;R=pasfe;RI=onebox;SC=OK;SliceKind=Test;FE=;LPSS=0;MPS=Master;DLOT=GRDS,GRDS
;UF=0;LEUT=0;Version=V2
x-ms-gateway-service-instanceid: onebox
X-Content-Type-Options        : nosniff
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-reads: 14868
x-ms-correlation-request-id   : dc470373-1512-4d4f-9c5f-690bae0f4ffd
x-ms-routing-request-id       : LOCAL:20180104T212310Z:dc470373-1512-4d4f-9c5f-690bae0f4ffd
Cache-Control                 : no-cache
Date                          : Thu, 04 Jan 2018 21:23:10 GMT
Server                        : Microsoft-IIS/10.0

Body:
{
  "value": [
    {
      "properties": {
        "roleName": "Contributor",
        "type": "BuiltInRole",
        "description": "Lets you manage everything except access to resources.",
        "assignableScopes": [
          "/"
        ],
        "permissions": [
          {
            "actions": [
              "*"
            ],
            "notActions": [
              "Microsoft.Authorization/*/Delete",
              "Microsoft.Authorization/*/Write"
            ]
          }
        ],
        "createdOn": "2017-11-30T10:33:37.3441658Z",
        "updatedOn": "2017-11-30T10:33:37.3441658Z",
        "createdBy": null,
        "updatedBy": null
      },
      "id": "/subscriptions/114fdf88-3d83-4b87-88ab-db94d653e369/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42
a0-ab88-20f7382dd24c",
      "type": "Microsoft.Authorization/roleDefinitions",
      "name": "b24988ac-6180-42a0-ab88-20f7382dd24c"
    },
    {
      "properties": {
        "roleName": "Owner",
        "type": "BuiltInRole",
        "description": "Lets you manage everything, including access to resources.",
        "assignableScopes": [
          "/"
        ],
        "permissions": [
          {
            "actions": [
              "*"
            ],
            "notActions": []
          }
        ],
        "createdOn": "2017-11-30T10:33:37.3441658Z",
        "updatedOn": "2017-11-30T10:33:37.3441658Z",
        "createdBy": null,
        "updatedBy": null
      },
      "id": "/subscriptions/114fdf88-3d83-4b87-88ab-db94d653e369/providers/Microsoft.Authorization/roleDefinitions/8e3af657-a8ff-44
3c-a75c-2fe8c4bcb635",
      "type": "Microsoft.Authorization/roleDefinitions",
      "name": "8e3af657-a8ff-443c-a75c-2fe8c4bcb635"
    },
    {
      "properties": {
        "roleName": "Reader",
        "type": "BuiltInRole",
        "description": "Lets you view everything, but not make any changes.",
        "assignableScopes": [
          "/"
        ],
        "permissions": [
          {
            "actions": [
              "*/read"
            ],
            "notActions": []
          }
        ],
        "createdOn": "2017-11-30T10:33:37.3441658Z",
        "updatedOn": "2017-11-30T10:33:37.3441658Z",
        "createdBy": null,
        "updatedBy": null
      },
      "id": "/subscriptions/114fdf88-3d83-4b87-88ab-db94d653e369/providers/Microsoft.Authorization/roleDefinitions/acdd72a7-3385-48
ef-bd42-f606fba81ae7",
      "type": "Microsoft.Authorization/roleDefinitions",
      "name": "acdd72a7-3385-48ef-bd42-f606fba81ae7"
    }
  ],
  "nextLink": null
}

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 01/04/2018 21:23:10: f21e14fd-ccc9-4bd4-b5ac-b445d0d0cfca - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://adfs.local.azurestack.external/adfs/e585a25e-1fe3-4a10-9060-d81cbc7c87f4/
	Resource: https://graph.local.azurestack.external/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (2 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 01/04/2018 21:23:10: f21e14fd-ccc9-4bd4-b5ac-b445d0d0cfca - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 01/04/2018 21:23:10: f21e14fd-ccc9-4bd4-b5ac-b445d0d0cfca - TokenCache: An item matching the requested resource was found in
 the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 01/04/2018 21:23:10: f21e14fd-ccc9-4bd4-b5ac-b445d0d0cfca - TokenCache: 27.7965211866667 minutes left until token in cache e
xpires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 01/04/2018 21:23:10: f21e14fd-ccc9-4bd4-b5ac-b445d0d0cfca - TokenCache: A matching item (access token or refresh token or bo
th) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 01/04/2018 21:23:10: f21e14fd-ccc9-4bd4-b5ac-b445d0d0cfca - AcquireTokenHandlerBase: === Token Acquisition finished successf
ully. An access token was retuned:
	Access Token Hash: yi0pvvFXZDqdbRKIpF8t/qqR+zz1QJ1U0E7SkmTDAiE=
	Refresh Token Hash: ED0uiSSC8AC3jdMg/KZBIpRwkOtM4WJV538XzGJXK30=
	Expiration Time: 01/04/2018 21:50:58 +00:00
	User Hash: CdKd4TxQZMyuxI5X7W1GN3p+Z69IKNlTce2deM2pqQE=
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 01/04/2018 21:23:10:  - TokenCache: Serializing token cache with 2 items.

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://graph.local.azurestack.external/e585a25e-1fe3-4a10-9060-d81cbc7c87f4/getObjectsByObjectIds?api-version=1.6

Headers:
x-ms-client-request-id        : 38d32db7-e438-4cdd-8852-b120195d1c82
accept-language               : en-US

Body:
{
  "objectIds": [
    "S-1-5-21-2060287033-2409276391-3379839450-1333",
    "S-1-5-21-2060287033-2409276391-3379839450-1325",
    "S-1-5-21-2060287033-2409276391-3379839450-1335",
    "S-1-5-21-2060287033-2409276391-3379839450-1349"
  ],
  "includeDirectoryObjectReferences": true
}

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
request-id                    : bc679497-c383-4bba-b5ca-5410534f673b
OData-Version                 : 4.0
Cache-Control                 : no-cache
Date                          : Thu, 04 Jan 2018 21:23:10 GMT
Server                        : Microsoft-IIS/10.0
X-Powered-By                  : ASP.NET

Body:
{
  "@odata.context": "https://graph.local.azurestack.external:1443/e585a25e-1fe3-4a10-9060-d81cbc7c87f4/$metadata#directoryObjects",

  "value": [
    {
      "@odata.type": "#Microsoft.AzureStack.Graph.Contracts.AzureObjectModel.ServicePrincipal",
      "objectType": "ServicePrincipal",
      "objectId": "S-1-5-21-2060287033-2409276391-3379839450-1349",
      "deletionTimestamp": null,
      "displayName": "Azurestack-sp123-07706edb-b2f0-4e6c-b319-aa40358515a5",
      "appDisplayName": null,
      "replyUrls": [
        "https://localhost/"
      ],
      "accountEnabled": true,
      "appId": "27b20f76-744c-4d11-8d64-36dbace18d1f",
      "keyCredentials": [
        {
          "endDate": "2019-01-04T10:26:28-08:00",
          "keyId": "00000000-0000-0000-0000-000000000000",
          "startDate": "2018-01-04T10:06:28-08:00",
          "type": "AsymmetricX509Cert",
          "usage": "Verify",
          "value": null
        }
      ],
      "publisherName": null,
      "servicePrincipalNames": [
        "27b20f76-744c-4d11-8d64-36dbace18d1f"
      ]
    },
    {
      "@odata.type": "#Microsoft.AzureStack.Graph.Contracts.AzureObjectModel.ServicePrincipal",
      "objectType": "ServicePrincipal",
      "objectId": "S-1-5-21-2060287033-2409276391-3379839450-1335",
      "deletionTimestamp": null,
      "displayName": "AzureStack-AzureStackBridge-Client",
      "appDisplayName": "AzureStack-AzureStackBridge-Resource",
      "replyUrls": [
        "https://azurestackbridge.ADFS.azurestack.local/e585a25e-1fe3-4a10-9060-d81cbc7c87f4"
      ],
      "accountEnabled": true,
      "appId": "bd1e19dc-34ec-4119-a663-864e20a6fda2",
      "keyCredentials": [
        {
          "endDate": "2019-11-30T02:12:48-08:00",
          "keyId": "00000000-0000-0000-0000-000000000000",
          "startDate": "2017-11-30T02:12:48-08:00",
          "type": "AsymmetricX509Cert",
          "usage": "Verify",
          "value": null
        }
      ],
      "publisherName": null,
      "servicePrincipalNames": [
        "bd1e19dc-34ec-4119-a663-864e20a6fda2"
      ]
    },
    {
      "@odata.type": "#Microsoft.AzureStack.Graph.Contracts.AzureObjectModel.ServicePrincipal",
      "objectType": "ServicePrincipal",
      "objectId": "S-1-5-21-2060287033-2409276391-3379839450-1333",
      "deletionTimestamp": null,
      "displayName": "AzureStack-Deployment-Client",
      "appDisplayName": "AzureStack-Deployment-Resource",
      "replyUrls": [
        "https://deploy.ADFS.azurestack.local/e585a25e-1fe3-4a10-9060-d81cbc7c87f4"
      ],
      "accountEnabled": true,
      "appId": "40b56c70-d571-427b-97e5-f6b9e47adae2",
      "keyCredentials": [
        {
          "endDate": "2019-11-30T02:12:54-08:00",
          "keyId": "00000000-0000-0000-0000-000000000000",
          "startDate": "2017-11-30T02:12:54-08:00",
          "type": "AsymmetricX509Cert",
          "usage": "Verify",
          "value": null
        }
      ],
      "publisherName": null,
      "servicePrincipalNames": [
        "40b56c70-d571-427b-97e5-f6b9e47adae2"
      ]
    },
    {
      "@odata.type": "#Microsoft.AzureStack.Graph.Contracts.AzureObjectModel.ServicePrincipal",
      "objectType": "ServicePrincipal",
      "objectId": "S-1-5-21-2060287033-2409276391-3379839450-1325",
      "deletionTimestamp": null,
      "displayName": "AzureStack-AdminMonitoring-Client",
      "appDisplayName": "AzureStack-AdminMonitoring-Resource",
      "replyUrls": [
        "https://adminmonitoring.ADFS.azurestack.local/e585a25e-1fe3-4a10-9060-d81cbc7c87f4"
      ],
      "accountEnabled": true,
      "appId": "15475afa-4d5a-4776-921c-c2b52124c5fc",
      "keyCredentials": [
        {
          "endDate": "2019-11-30T02:12:47-08:00",
          "keyId": "00000000-0000-0000-0000-000000000000",
          "startDate": "2017-11-30T02:12:47-08:00",
          "type": "AsymmetricX509Cert",
          "usage": "Verify",
          "value": null
        }
      ],
      "publisherName": null,
      "servicePrincipalNames": [
        "15475afa-4d5a-4776-921c-c2b52124c5fc"
      ]
    }
  ]
}

Get-AzureRmRoleAssignment : Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
At line:1 char:1
+ Get-AzureRmRoleAssignment -Scope "/subscriptions/114fdf88-3d83-4b87-8 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmRoleAssignment], FormatException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.GetAzureRoleAssignmentCommand
 
DEBUG: 1:23:12 PM - GetAzureRoleAssignmentCommand end processing.
DEBUG: 1:23:12 PM - GetAzureRoleAssignmentCommand end processing.

### Script/Steps for Reproduction
Get-AzureRmRoleAssignment

**Comment by cormacpayne** [comment] 2018-01-08 17:44
@viananth @bganapa please let me know if you would like me to assign this issue back to the contact we have for the Resources team

**Comment by viananth** [comment] 2018-01-08 17:49
@cormacpayne Yes, please assign it to the right contact

**Comment by cormacpayne** [comment] 2018-01-08 18:00
@darshanhs90 Hey Haridarshan, would you mind taking a look at this issue?

**Comment by darshanhs90** [comment] 2018-01-09 20:19
@shaosong2017 can you look into this?

**Comment by shaosong2017** [comment] 2018-01-09 21:48
Hi,

I am on call this week, I will take a look this Friday when my on call ends.

Thanks,
Shaosong Li

**Comment by darshanhs90** [comment] 2018-02-06 01:17
@viananth Closing this Issue as the bug has been fixed.Let me know if the issue is still persisting.

**Comment by viananth** [comment] 2018-06-23 21:16
@darshanhs90 could you please provide the PR number for this bug fix? Stack does not support the latest API version for Resources module. So we'll have to backport the fix. Thanks for your help!

**Comment by bganapa** [comment] 2018-08-01 23:59
Activatign this as this still exists

**Comment by bganapa** [comment] 2018-09-19 18:06
This is fixed with AzureRM 2.3.0 release and AzureRm.Resources module version is 6.0.2

**Closed by bganapa** 2018-09-19 18:06 UTC
Labels: Azure Stack, Resource Authorization
