### ISSUE TITLE
Set-AzResource fails for resources with white spaces

### ISSUE THREAD

**Issue by jopels** [Azure/azure-powershell#10284] opened 2019-10-14 16:17 UTC
## Description
Set-AzResource fails if the resource contains white spaces

## Steps to reproduce
Create a resource with spaces like 'Test Resource'
Apply a tag to the resource
```powershell
Set-AzResource -ResourceId $ResourceId -Tag $TagHashtable -ErrorAction 'stop' -Force
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.17763.592
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.592
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

```powershell
Version     Name
-------     ----
1.6.2       Az.Accounts
1.0.1       Az.Advisor
1.0.2       Az.Aks
1.1.1       Az.AnalysisServices
1.3.1       Az.ApiManagement
1.0.2       Az.ApplicationInsights
1.3.3       Az.Automation
1.1.1       Az.Batch
1.0.1       Az.Billing
1.3.1       Az.Cdn
1.2.1       Az.CognitiveServices
2.6.0       Az.Compute
1.0.1       Az.ContainerInstance
1.1.0       Az.ContainerRegistry
1.3.0       Az.DataFactory
1.0.1       Az.DataLakeAnalytics
1.2.2       Az.DataLakeStore
1.0.1       Az.DeploymentManager
1.0.0       Az.DevTestLabs
1.1.1       Az.Dns
1.2.2       Az.EventGrid
1.4.0       Az.EventHub
1.1.1       Az.FrontDoor
2.0.2       Az.HDInsight
1.3.0       Az.IotHub
1.3.1       Az.KeyVault
1.3.1       Az.LogicApp
1.1.1       Az.MachineLearning
1.0.1       Az.ManagedServices
1.0.1       Az.MarketplaceOrdering
1.1.0       Az.Media
1.3.0       Az.Monitor
1.14.0      Az.Network
1.1.0       Az.NotificationHubs
1.3.3       Az.OperationalInsights
1.1.3       Az.PolicyInsights
1.1.0       Az.PowerBIEmbedded
1.4.5       Az.RecoveryServices
1.1.0       Az.RedisCache
1.0.2       Az.Relay
1.7.0       Az.Resources
1.4.0       Az.ServiceBus
1.2.0       Az.ServiceFabric
1.1.0       Az.SignalR
1.14.2      Az.Sql
1.7.0       Az.Storage
1.2.0       Az.StorageSync
1.0.0       Az.StreamAnalytics
1.0.2       Az.TrafficManager
1.4.2       Az.Websites
```

## Debug output

```
17:59:16 - SetAzureResourceCmdlet begin processing with ParameterSet 'ByResourceId'.

17:59:16 - using account id '[AccountID]'...

[Common.Authentication]: Authenticating using Account: '[AccountID]', environment: 

'AzureCloud', tenant: '[TenantID]'

[Common.Authentication]: Authenticating using configuration values: Domain: '[TenantID]', 

Endpoint: 'https://login.microsoftonline.com/', ClientId: '[ClientID]', ClientRedirect: 

'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthority: 'True'

[Common.Authentication]: Renewing token using AppId: '[AccountID]', AdalConfiguration with 

ADDomain: '[TenantID]', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: 

'[ClientID]', RedirectUri: 'urn:ietf:wg:oauth:2.0:oob'

[ADAL]: Information: 2019-10-14T15:59:16.7381955Z: [OtherID] - LoggerBase.cs: ADAL 

PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version 

'2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...



[ADAL]: Information: 2019-10-14T15:59:16.7381955Z: [OtherID] - LoggerBase.cs: ADAL 

PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version 

'2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...



[ADAL]: Information: 2019-10-14T15:59:16.7381955Z: [OtherID] - LoggerBase.cs: === Token 

Acquisition started: 

	CacheType: null

	Authentication Target: Client

	, Authority Host: login.microsoftonline.com



[ADAL]: Information: 2019-10-14T15:59:16.7381955Z: [OtherID] - LoggerBase.cs: === Token 

Acquisition started:

	Authority: https://login.microsoftonline.com/[TenantID]/

	Resource: https://management.core.windows.net/

	ClientId: [AccountID]

	CacheType: null

	Authentication Target: Client

	



[ADAL]: Verbose: 2019-10-14T15:59:16.7381955Z: [OtherID] - LoggerBase.cs: Loading from cache.



[ADAL]: Verbose: 2019-10-14T15:59:16.7381955Z: [OtherID] - LoggerBase.cs: Loading from cache.



[ADAL]: Information: 2019-10-14T15:59:16.7381955Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Deserialized 1 

items to token cache.



[ADAL]: Verbose: 2019-10-14T15:59:16.7381955Z: [OtherID] - LoggerBase.cs: Looking up cache 

for a token...



[ADAL]: Verbose: 2019-10-14T15:59:16.7381955Z: [OtherID] - LoggerBase.cs: Looking up cache 

for a token...



[ADAL]: Information: 2019-10-14T15:59:16.7381955Z: [OtherID] - LoggerBase.cs: An item 

matching the requested resource was found in the cache



[ADAL]: Information: 2019-10-14T15:59:16.7381955Z: [OtherID] - LoggerBase.cs: An item 

matching the requested resource was found in the cache



[ADAL]: Information: 2019-10-14T15:59:16.7381955Z: [OtherID] - LoggerBase.cs: 

40,9346467416667 minutes left until token in cache expires



[ADAL]: Information: 2019-10-14T15:59:16.7381955Z: [OtherID] - LoggerBase.cs: 

40,9346467416667 minutes left until token in cache expires



[ADAL]: Information: 2019-10-14T15:59:16.7381955Z: [OtherID] - LoggerBase.cs: A matching 

item (access token or refresh token or both) was found in the cache



[ADAL]: Information: 2019-10-14T15:59:16.7381955Z: [OtherID] - LoggerBase.cs: A matching 

item (access token or refresh token or both) was found in the cache



[ADAL]: Information: 2019-10-14T15:59:16.7381955Z: [OtherID] - LoggerBase.cs: === Token 

Acquisition finished successfully. An access token was returned: Expiration Time: 14/10/2019 16:40:12 +00:00



[ADAL]: Information: 2019-10-14T15:59:16.7381955Z: [OtherID] - LoggerBase.cs: === Token 

Acquisition finished successfully. An access token was returned: Expiration Time: 14/10/2019 16:40:12 +00:00Access 

Token Hash: [TokenHash]

	 User id: 



[Common.Authentication]: Checking token expiration, token expires '10/14/2019 16:40:12 +00:00' Comparing to '10/14/2019 

15:59:16 +00:00' With threshold '00:05:00', calculated time until token expiry: '00:40:56.0788045'

============================ HTTP REQUEST ============================



HTTP Method:

GET



Absolute Uri:

https://management.azure.com/subscriptions/[SubscriptionID]/providers?api-version=2016-07-01



Headers:

User-Agent                    : AzurePowershell/v1.0.0,PSVersion/v5.1.17763.592

ParameterSetName              : ByResourceId

CommandName                   : Set-AzResource



Body:







[Common.Authentication]: Authenticating using Account: '[AccountID]', environment: 

'AzureCloud', tenant: '[TenantID]'

[Common.Authentication]: Authenticating using configuration values: Domain: '[TenantID]', 

Endpoint: 'https://login.microsoftonline.com/', ClientId: '[ClientID]', ClientRedirect: 

'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthority: 'True'

[Common.Authentication]: Renewing token using AppId: '[AccountID]', AdalConfiguration with 

ADDomain: '[TenantID]', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: 

'[ClientID]', RedirectUri: 'urn:ietf:wg:oauth:2.0:oob'

[ADAL]: Information: 2019-10-14T15:59:18.8268595Z: [OtherID2] - LoggerBase.cs: ADAL 

PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version 

'2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...



[ADAL]: Information: 2019-10-14T15:59:18.8268595Z: [OtherID2] - LoggerBase.cs: ADAL 

PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version 

'2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...



[ADAL]: Information: 2019-10-14T15:59:18.8268595Z: [OtherID2] - LoggerBase.cs: === Token 

Acquisition started: 

	CacheType: null

	Authentication Target: Client

	, Authority Host: login.microsoftonline.com



[ADAL]: Information: 2019-10-14T15:59:18.8268595Z: [OtherID2] - LoggerBase.cs: === Token 

Acquisition started:

	Authority: https://login.microsoftonline.com/[TenantID]/

	Resource: https://management.core.windows.net/

	ClientId: [AccountID]

	CacheType: null

	Authentication Target: Client

	



[ADAL]: Verbose: 2019-10-14T15:59:18.8268595Z: [OtherID2] - LoggerBase.cs: Loading from cache.



[ADAL]: Verbose: 2019-10-14T15:59:18.8268595Z: [OtherID2] - LoggerBase.cs: Loading from cache.



[ADAL]: Information: 2019-10-14T15:59:18.8268595Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Deserialized 1 

items to token cache.



[ADAL]: Verbose: 2019-10-14T15:59:18.8268595Z: [OtherID2] - LoggerBase.cs: Looking up cache 

for a token...



[ADAL]: Verbose: 2019-10-14T15:59:18.8268595Z: [OtherID2] - LoggerBase.cs: Looking up cache 

for a token...



[ADAL]: Information: 2019-10-14T15:59:18.8268595Z: [OtherID2] - LoggerBase.cs: An item 

matching the requested resource was found in the cache



[ADAL]: Information: 2019-10-14T15:59:18.8268595Z: [OtherID2] - LoggerBase.cs: An item 

matching the requested resource was found in the cache



[ADAL]: Information: 2019-10-14T15:59:18.8268595Z: [OtherID2] - LoggerBase.cs: 40,899835675 

minutes left until token in cache expires



[ADAL]: Information: 2019-10-14T15:59:18.8268595Z: [OtherID2] - LoggerBase.cs: 40,899835675 

minutes left until token in cache expires



[ADAL]: Information: 2019-10-14T15:59:18.8268595Z: [OtherID2] - LoggerBase.cs: A matching 

item (access token or refresh token or both) was found in the cache



[ADAL]: Information: 2019-10-14T15:59:18.8268595Z: [OtherID2] - LoggerBase.cs: A matching 

item (access token or refresh token or both) was found in the cache



[ADAL]: Information: 2019-10-14T15:59:18.8268595Z: [OtherID2] - LoggerBase.cs: === Token 

Acquisition finished successfully. An access token was returned: Expiration Time: 14/10/2019 16:40:12 +00:00



[ADAL]: Information: 2019-10-14T15:59:18.8268595Z: [OtherID2] - LoggerBase.cs: === Token 

Acquisition finished successfully. An access token was returned: Expiration Time: 14/10/2019 16:40:12 +00:00Access 

Token Hash: [TokenHash]

	 User id: 



[Common.Authentication]: Checking token expiration, token expires '10/14/2019 16:40:12 +00:00' Comparing to '10/14/2019 

15:59:18 +00:00' With threshold '00:05:00', calculated time until token expiry: '00:40:53.9901405'

============================ HTTP REQUEST ============================



HTTP Method:

PATCH



Absolute Uri:

https://management.azure.com/subscriptions/[SubscriptionID]/resourceGroups/[ResourceGroup]/pr

oviders/microsoft.insights/metricalerts/Test Resource?api-version=2018-03-01



Headers:

User-Agent                    : AzurePowershell/v1.0.0,PSVersion/v5.1.17763.592

ParameterSetName              : ByResourceId

CommandName                   : Set-AzResource



Body:

{

  "tags": {

    "Environment": "DEV",

    "Service": "Sandbox",

    "BU": "UI"

  }

}





============================ HTTP RESPONSE ============================



Status Code:

NotFound



Headers:

x-ms-ratelimit-remaining-subscription-writes: 1199

x-ms-request-id               : [RequestID]

x-ms-correlation-request-id   : [RequestID]

x-ms-routing-request-id       : [Region]:20191014T155919Z:[RequestID]

Strict-Transport-Security     : max-age=31536000; includeSubDomains

X-Content-Type-Options        : nosniff

Cache-Control                 : private

Date                          : Mon, 14 Oct 2019 15:59:18 GMT

Server                        : Microsoft-IIS/10.0

X-Powered-By                  : ASP.NET



Body:

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 

<html xmlns="http://www.w3.org/1999/xhtml"> 

<head> 

<title>IIS 10.0 Detailed Error - 404.4 - Not Found</title> 

<style type="text/css"> 

<!-- 

body{margin:0;font-size:.7em;font-family:Verdana,Arial,Helvetica,sans-serif;} 

code{margin:0;color:#006600;font-size:1.1em;font-weight:bold;} 

.config_source code{font-size:.8em;color:#000000;} 

pre{margin:0;font-size:1.4em;word-wrap:break-word;} 

ul,ol{margin:10px 0 10px 5px;} 

ul.first,ol.first{margin-top:5px;} 

fieldset{padding:0 15px 10px 15px;word-break:break-all;} 

.summary-container fieldset{padding-bottom:5px;margin-top:4px;} 

legend.no-expand-all{padding:2px 15px 4px 10px;margin:0 0 0 -12px;} 

legend{color:#333333;;margin:4px 0 8px -12px;_margin-top:0px; 

font-weight:bold;font-size:1em;} 

a:link,a:visited{color:#007EFF;font-weight:bold;} 

a:hover{text-decoration:none;} 

h1{font-size:2.4em;margin:0;color:#FFF;} 

h2{font-size:1.7em;margin:0;color:#CC0000;} 

h3{font-size:1.4em;margin:10px 0 0 0;color:#CC0000;} 

h4{font-size:1.2em;margin:10px 0 5px 0; 

}#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS",Verdana,sans-serif; 

 color:#FFF;background-color:#5C87B2; 

}#content{margin:0 0 0 2%;position:relative;} 

.summary-container,.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;} 

.content-container p{margin:0 0 10px 0; 

}#details-left{width:35%;float:left;margin-right:2%; 

}#details-right{width:63%;float:left;overflow:hidden; 

}#server_version{width:96%;_height:1px;min-height:1px;margin:0 0 5px 0;padding:11px 2% 8px 2%;color:#FFFFFF; 

 background-color:#5A7FA5;border-bottom:1px solid #C1CFDD;border-top:1px solid #4A6C8E;font-weight:normal; 

 font-size:1em;color:#FFF;text-align:right; 

}#server_version p{margin:5px 0;} 

table{margin:4px 0 4px 0;width:100%;border:none;} 

td,th{vertical-align:top;padding:3px 0;text-align:left;font-weight:normal;border:none;} 

th{width:30%;text-align:right;padding-right:2%;font-weight:bold;} 

thead th{background-color:#ebebeb;width:25%; 

}#details-right th{width:20%;} 

table tr.alt td,table tr.alt th{} 

.highlight-code{color:#CC0000;font-weight:bold;font-style:italic;} 

.clear{clear:both;} 

.preferred{padding:0 5px 2px 5px;font-weight:normal;background:#006633;color:#FFF;font-size:.8em;} 

--> 

</style> 

 

</head> 

<body> 

<div id="content"> 

<div class="content-container"> 

  <h3>HTTP Error 404.4 - Not Found</h3> 

  <h4>The resource you are looking for does not have a handler associated with it.</h4> 

</div> 

<div class="content-container"> 

 <fieldset><h4>Most likely causes:</h4> 

  <ul> 	<li>The file extension for the requested URL does not have a handler configured to process the request on the 

Web server.</li> </ul> 

 </fieldset> 

</div> 

<div class="content-container"> 

 <fieldset><h4>Things you can try:</h4> 

  <ul> 	<li>If the file extension does not have a handler associated with it, add a handler mapping for the 

extension.</li> 	<li>Verify that the handler associated with the file extension is properly installed and 

configured.</li> 	<li>Create a tracing rule to track failed requests for this HTTP status code. For more information 

about creating a tracing rule for failed requests, click <a 

href="http://go.microsoft.com/fwlink/?LinkID=66439">here</a>. </li> </ul> 

 </fieldset> 

</div> 

 

<div class="content-container"> 

 <fieldset><h4>Detailed Error Information:</h4> 

  <div id="details-left"> 

   <table border="0" cellpadding="0" cellspacing="0"> 

    <tr class="alt"><th>Module</th><td>&nbsp;&nbsp;&nbsp;IIS Web Core</td></tr> 

    <tr><th>Notification</th><td>&nbsp;&nbsp;&nbsp;MapRequestHandler</td></tr> 

    <tr class="alt"><th>Handler</th><td>&nbsp;&nbsp;&nbsp;Not yet determined</td></tr> 

    <tr><th>Error Code</th><td>&nbsp;&nbsp;&nbsp;0x80070002</td></tr> 

     

   </table> 

  </div> 

  <div id="details-right"> 

   <table border="0" cellpadding="0" cellspacing="0"> 

    <tr class="alt"><th>Requested URL</th><td>&nbsp;&nbsp;&nbsp;https://genevaalertrpprod.monitoring.windows.net:443/sub

scriptions/[SubscriptionID]/resourceGroups/[ResourceGroup]/providers/microsoft.insights/metri

calerts/Test Resource?api-version=2018-03-01</td></tr> 

    <tr><th>Physical Path</th><td>&nbsp;&nbsp;&nbsp;E:\sitesroot\0\subscriptions\[SubscriptionID]\re

sourceGroups\[ResourceGroup]\providers\microsoft.insights\metricalerts\Test Resource</td></tr> 

    <tr class="alt"><th>Logon Method</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr> 

    <tr><th>Logon User</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr> 

    <tr class="alt"><th>Request Tracing Directory</th><td>&nbsp;&nbsp;&nbsp;C:\Resources\directory\fcc70d75f35640b6b9d3a

2bebc5f9f7e.AlertRpWebApi.DiagnosticStore\FailedReqLogFiles\Web</td></tr> 

   </table> 

   <div class="clear"></div> 

  </div> 

 </fieldset> 

</div> 

 

<div class="content-container"> 

 <fieldset><h4>More Information:</h4> 

  This error means that the Web server does not recognize the file extension of the requested resource. A module 

handler is not configured on the Web server for this extension. If the file extension being denied is required by the 

Web server, add the appropriate handler for the file extension. 

  <p><a href="http://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=404,4,0x80070002,14393">View more information 

&raquo;</a></p> 

   

 </fieldset> 

</div> 

</div> 

</body> 

</html> 

```

**Comment by msJinLei** [comment] 2019-10-15 02:42
@jopels Thank you for reporting the issue. We will investigate it and let you know if any update.

**Comment by msJinLei** [comment] 2019-12-12 03:42
@jopels Could you provde the cmdlet you used to create the resources?

**Comment by jopels** [comment] 2019-12-17 14:04
@msJinLei Sorry for the late response. The resources actually existed already. In my case these are 'microsoft.insights/metricalerts'. As far as I can see there is no limitation regarding spaces in the resource name if you create them on the Azure portal
![test resource](https://user-images.githubusercontent.com/16117940/71001859-6fdffc00-20de-11ea-87f9-0a3b86d9cab0.png)

**Comment by msJinLei** [comment] 2019-12-19 08:22
@jopels
- Could you provide detailed steps to reproduce your error?
   For example how you use New-AzResource 
- Could you provide the error output & debug output of azure powershell  rather portal?
- I will check whether space is support in azure powershell for resource name.

**Comment by dingmeng-xue** [comment] 2020-02-25 16:12
@jopels, we need to know how you created rule on metric. We test a similar case and service supports it even there is white spaces.

 ```
Set-AzResource -ResourceId "/subscriptions/<sub>/resourceGroups/dixue/providers/microsoft.insights/activityLogAlerts/my test" -Tag @{a="123"}

......
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PATCH

Absolute Uri:
https://management.azure.com/subscriptions/<sub>/resourceGroups/dixue/providers/microsoft.insights/activityLogAlerts/my test?api-version=2017-04-01

Headers:
User-Agent                    : PSVersion/v6.2.3,AzurePowershell/v1.0.0
ParameterSetName              : ByResourceId
CommandName                   : Set-AzResource

Body:
{
  "tags": {
    "a": "123"
  }
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
Vary                          : Accept-Encoding
x-ms-request-id               : eastasia_1a6635277e884c4a99584ac9cdc8a559_637182424489469964
Server                        : Microsoft-IIS/10.0
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : 4d9849e1-2524-4e4a-88bd-13ca2f6daa50
x-ms-routing-request-id       : EASTASIA:20200225T154731Z:4d9849e1-2524-4e4a-88bd-13ca2f6daa50
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Tue, 25 Feb 2020 15:47:30 GMT

Body:
{
  "id": "/subscriptions/<sub>/resourceGroups/dixue/providers/microsoft.insights/activityLogAlerts/my test",
  "type": "Microsoft.Insights/ActivityLogAlerts",
  "name": "my test",
  "location": "Global",
  "kind": null,
  "tags": {
    "a": "123"
  },
  "properties": {
    "scopes": [
      "/subscriptions/<sub>"
    ],
    "condition": {
      "allOf": [
        {
          "field": "category",
          "equals": "Administrative",
          "containsAny": null,
          "odata.type": null
        },
        {
          "field": "status",
          "equals": "failed",
          "containsAny": null,
          "odata.type": null
        }
      ],
      "odata.type": null
    },
    "actions": {
      "actionGroups": []
    },
    "enabled": false,
    "description": ""
  },
  "identity": null
}
......
Name              : my test
ResourceId        : /subscriptions/<sub>/resourceGroups/dixue/providers/microsoft.insights/activityLogAlerts/my test
ResourceName      : my test
ResourceType      : microsoft.insights/activityLogAlerts
ResourceGroupName : dixue
Location          : Global
SubscriptionId    : <sub>
Tags              : {a}
Properties        : @{scopes=System.Object[]; condition=; actions=; enabled=False; description=}

DEBUG: AzureQoSEvent: CommandName - Set-AzResource; IsSuccess - True; Duration - 00:01:13.6543301;
```

**Comment by jopels** [comment] 2020-02-27 09:24
Hello dingmeng-xue and hello msJinLei,

The rules were created using the Azure Portal. I tried to create a new rule to reproduce the problem.
When I compared a new rule with one of the old rules in question I saw that they are actually not of the same type.
I could nor reproduce the problem above with a rule of type _activityLogAlerts_.



```
Get-AzResource -Name 'ab c' | select *

ResourceId            : /subscriptions/subID/resourceGroups/resGrp/providers/microsoft.insights/activityLogAlerts/ab c
Id                    : /subscriptions/subID/resourceGroups/resGrp/providers/microsoft.insights/activityLogAlerts/ab c
Identity              : 
Kind                  : 
Location              : global
ManagedBy             : 
ResourceName          : ab c
Name                  : ab c
ExtensionResourceName : 
ParentResource        : 
Plan                  : 
Properties            : 
ResourceGroupName     : resGrp
Type                  : microsoft.insights/activityLogAlerts
ResourceType          : microsoft.insights/activityLogAlerts
ExtensionResourceType : 
Sku                   : 
Tags                  : {[a, 123]}
SubscriptionId        : 
CreatedTime           : 
ChangedTime           : 
ETag                  : 



Get-AzResource -Name 'bc d' | select *
ResourceId            : /subscriptions/subID/resourceGroups/resGrp2/providers/microsoft.insights/metricalerts/bc d 
Id                    : /subscriptions/subID/resourceGroups/resGrp2/providers/microsoft.insights/metricalerts/bc d 
Identity              : 
Kind                  : 
Location              : global
ManagedBy             : 
ResourceName          : bc d
Name                  : bc d
ExtensionResourceName : 
ParentResource        : 
Plan                  : 
Properties            : 
ResourceGroupName     : resGrp2
Type                  : microsoft.insights/metricalerts
ResourceType          : microsoft.insights/metricalerts
ExtensionResourceType : 
Sku                   : 
Tags                  : {}
SubscriptionId        : 
CreatedTime           : 
ChangedTime           : 
ETag                  : 
```

**Comment by dingmeng-xue** [comment] 2020-02-27 09:26
Do you know how to create old version of rules?

**Comment by jopels** [comment] 2020-02-28 13:29
No sorry.

**Comment by dingmeng-xue** [comment] 2020-02-28 14:25
@jopels, thanks for reporting the issue. I will close this one as not reproducible because old version of resource cannot be created. If you find similar issue again, please create issue. Thanks.

**Closed by dingmeng-xue** 2020-02-28 14:25 UTC
Labels: Azure PS Team, More Info :label:, customer-reported
