### ISSUE TITLE
Az module still references AzureRM cmdlets in error output

### ISSUE THREAD

**Issue by sptramer** [Azure/azure-powershell#7601] opened 2018-10-17 19:55 UTC
### Description

Error outputs (and possibly others) still reference AzureRM cmdlets in the Az modules.

### Script/Steps for Reproduction

When not logged in:

```powershell
PS C:\Program Files\PowerShell\6> Get-AzStorageAccount
Get-AzStorageAccount : No subscription found in the context.  Please ensure that the credentials you provided are authorized to access an Azure subscription, then run Connect-AzureRmAccount to login.
```

### Module Version

Az 0.3.0

### Environment Data

```powershell
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by MiYanni** [comment] 2018-10-18 00:45
@sptramer This work is already covered here: https://github.com/Azure/azure-powershell/issues/7088

Duplicate of https://github.com/Azure/azure-powershell/issues/7088

**Closed by MiYanni** 2018-10-18 00:45 UTC

**Comment by MiYanni** [comment] 2018-10-18 00:47
Duplicate of https://github.com/Azure/azure-powershell/issues/7088
