### ISSUE TITLE
New-AzureRmRoleDefinition - Name Already Exists

### ISSUE THREAD

**Issue by guidooliveira** [Azure/azure-powershell#4365] opened 2017-07-26 14:43 UTC
### Cmdlet(s)
New-AzureRmRoleDefinition

### PowerShell Version
5.1.15063.483

### Module Version
4.2.1
### OS Version
Windows 10 x64

### Description
Can`t create new RoleDefinitions, it claims that the name already exists, same behaviour with JSON file.
### Debug Output
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com//subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/Microsoft.Authorization/roleDefinitions/939b463e
-7942-4b5b-921c-258a67de7775?api-version=2015-07-01

Headers:

Body:
{
  "name": "939b463e-7942-4b5b-921c-258a67de7775",
  "properties": {
    "roleName": "Analysts",
    "description": "Analysts can monitor and restart virtual machines.",
    "type": "CustomRole",
    "permissions": [
      {
        "actions": [
          "Microsoft.Storage/*/read",
          "Microsoft.Compute/*/read",
          "Microsoft.Compute/virtualMachines/start/action",
          "Microsoft.Compute/virtualMachines/restart/action",
          "Microsoft.Authorization/*/read",
          "Microsoft.Resources/subscriptions/resourceGroups/read"
        ],
        "notActions": []
      }
    ],
    "assignableScopes": [
      "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    ]
  }
}

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Conflict

Headers:
Pragma                        : no-cache
x-ms-request-id               : 8333184c-eac2-421b-863c-88e4910be27f
X-Content-Type-Options        : nosniff
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : ca0e75ff-f417-485d-a9bf-ea5ee1deac9c
x-ms-routing-request-id       : WESTUS2:20170726T143806Z:ca0e75ff-f417-485d-a9bf-ea5ee1deac9c
Cache-Control                 : no-cache
Date                          : Wed, 26 Jul 2017 14:38:05 GMT
Set-Cookie                    : x-ms-gateway-slice=productionb; path=/; secure; HttpOnly
Server                        : Microsoft-IIS/8.5
X-Powered-By                  : ASP.NET

Body:
{
  "error": {
    "code": "RoleDefinitionWithSameNameExists",
    "message": "A role definition cannot be updated with a name that already exists."
  }
}

New-AzureRmRoleDefinition : RoleDefinitionWithSameNameExists: A role definition cannot be updated with a name that already exists.
At line:20 char:3
+   New-AzureRmRoleDefinition -Role $Role
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmRoleDefinition], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureRoleDefinitionCommand

### Script/Steps for Reproduction
  Add-AzureRmAccount -SubscriptionId $Subscription.Id -Credential $AzureCredential -TenantId $Subscription.TenantId
  
  $Role = Get-AzureRmRoleDefinition -Name 'Reader'
  $Role.Id = $null
  $Role.Name = 'Analysts'
  $Role.Description = 'Analysts can monitor and restart virtual machines.'
  $Role.IsCustom = $true
  $Role.Actions.Clear()
  $Role.Actions.Add('Microsoft.Storage/*/read')
  $Role.Actions.Add('Microsoft.Compute/*/read')
  $Role.Actions.Add('Microsoft.Compute/virtualMachines/start/action')
  $Role.Actions.Add('Microsoft.Compute/virtualMachines/restart/action')
  $Role.Actions.Add('Microsoft.Authorization/*/read')
  $Role.Actions.Add('Microsoft.Resources/subscriptions/resourceGroups/read')
  $Role.AssignableScopes.Clear()
  $Role.AssignableScopes.Add(('/subscriptions/{0}' -f $Subscription.Id))

  New-AzureRmRoleDefinition -Role $Role

**Comment by cormacpayne** [comment] 2017-07-28 18:07
@guidooliveira can you run `Get-AzureRmRoleDefinition -Name 'Analysts'` to see if a role definition with that name already exists?

**Comment by guidooliveira** [comment] 2017-07-29 21:46
It Doesn't, already triple checked it

**Comment by kmongwa** [comment] 2017-07-30 23:57
@guidooliveira - Ran into the same problem.  Did some reading and found out that Roles are stored in AAD.  I suspect someone else using the same AAD has already used the 'Analysts' role name.   Try a different role name that is unique.  Unfortunately, I still haven't found the proper command to list all custom roles created in AAD.

**Comment by guidooliveira** [comment] 2017-07-31 17:29
@kmongwa I do Have a Group with the same name, but the Object IDs are Different, other than that, the subscriptions are within the same Tenant, does it not provision in the subscription but in the tenant?

**Comment by kmongwa** [comment] 2017-08-01 15:20
It provisions in the tenant, not the subscription.  If you want to reuse the same rule in multiple subscriptions, edit the "AssignableScopes" property to add the additional subscriptions.

**Comment by guidooliveira** [comment] 2017-08-01 17:51
@kmongwa I did that but when updating i get forbidden for every subscription.

**Comment by kmongwa** [comment] 2017-08-02 15:11
Try setting your Azure context to the subscription with which you originally created the role.  Make sure Get-AzureRmRoleDefinition -Name 'Analysts'  returns the role object, before attempting to modify it.

**Comment by spaelling** [comment] 2017-09-18 09:31
I can confirm that you need to change the context to the subscription where the first scope was assigned in order to test if the role already exists. This cannot be working as intended as the role exists in the tenant.

**Comment by darshanhs90** [comment] 2017-12-05 23:11
@guidooliveira  could you let me know the exact issue that is being faced now, so that i can help you in resolving the same

**Comment by darshanhs90** [comment] 2017-12-11 18:12
@guidooliveira any update on the issue that you are facing?

**Comment by mchute84** [comment] 2017-12-12 09:37
We are having the same issue. We have created a role in one subscription and then switched to a new one and tried to create the same role. 

Get-AzureRmRoleDefinition - In Sub1 says it exists
Get-AzureRmRoleDefinition - In Sub2 says doesnt exist but cannot create

**Comment by darshanhs90** [comment] 2017-12-12 19:44
Custom roles are created per tenant,which can be shared across subscriptions.
Since a custom role is already present in the sub1 under the same tenant,you are not bale to create the same in sub2.
One alternative to creating another role is to add this new subscription's scope[sub2 scope] in the assignable scopes of the role in sub1[so that you can access the role even in sub2]

**Comment by darshanhs90** [comment] 2018-01-19 23:11
Closing this issue Since the reason for the error has been provided

**Closed by darshanhs90** 2018-01-19 23:11 UTC
Labels: ResourceAuthorization

**Comment by olson-chris** [comment] 2018-08-07 00:53
This is still not working as intended. If New-AzureRmRoleDefinition is going to blow up when you try and create a "duplicate" role definition in a subscription that has no record of that defintion, then Get-AzureRmRoleDefinition -Custom should return all Custom roles in the AAD tenant, not just the ones in the subscription. Otherwise, how do you programatically discover where the role defintion exists so you can apply it to the active subscription?

**Comment by darshanhs90** [comment] 2018-08-07 01:01
@olson-chris The roledefinitions returned are only part of the subscriptions you have access to and that is by design as returning all the roles for the whole tenant will be a security concern

**Comment by olson-chris** [comment] 2018-08-07 01:11
So, how do I programatically determine where the role is defined? I have full admin rights to the AAD tenant and all of the subscriptions, including the one where the role is defined?

**Comment by darshanhs90** [comment] 2018-08-07 04:47
@olson-chris If you have the admin access at the tenant,you could do a get roledefinition at scope of "/"

**Comment by olson-chris** [comment] 2018-08-08 17:09
@darshanhs90 , that worked well. Might be good to add this as an example to the technet article?

**Comment by DiSae** [comment] 2021-09-28 06:48
I created a role in subscription A.
This subscription is one out of many subscriptions I have access to in a single tenant.
When I run the below code, I can't find the custom role I created in subscription A.
`
$null = Connect-AzAccount -TenantId $tenantId
$newRoleFound = Get-AzRoleDefinition -Name $newRoleName -Scope "/"
`
The values for the variables are defined in a param() section.

When I want to create the same custom role in subscription B, this fails because it already exists in the directory. (This was already mentioned above as 'by design'.)

I currently have no way to find out in which subscription the custom role was initially created. 
Do I really have to loop through all subscriptions to find in which subscription the role was created?

**Comment by Phillip-007** [comment] 2021-12-08 21:10
@DiSae it seems you're right. -scope doesn't work (anymore), but there is a simple solution:
`Get-AzRoleDefinition  -Custom` gives you all custom roles. 
Which makes the comment "_will be a security concern_" not true.
`$RoleId=$(Get-AzRoleDefinition  -Custom | ? {$_.Name -eq "Rolename"} | % {$_.id}) ` will give you the id, if it exists.
