### ISSUE TITLE
Start-AzAutomationRunbook Error when invoked from another runbook

### ISSUE THREAD

**Issue by brettmillerb** [Azure/azure-powershell#12695] opened 2020-08-18 23:34 UTC
## Description
I am attempting to call an Azure automation runbook from another runbook but I get an error when attempting to do so.

## Steps to reproduce

```powershell
$migrateElasticPoolSplat = @{
    ResourceGroup     = $elasticPool.ResourceGroupName
    ElasticPoolName   = $elasticPool.ElasticPoolName
    ServerName        = $elasticPool.ServerName
    Edition           = 'GeneralPurpose'
    VCoreCount        = 2
    ComputeGeneration = 'Gen5'
    DatabaseVCoreMax  = 0.25
}
        
$startAutomationRunBookSplat = @{
    AutomationAccountName = $automationAccountName 
    Name                  = 'Invoke-DbMigration'
    ResourceGroupName     = $automationAccountResourceGroup 
    Parameters            = $migrateElasticPoolSplat
}
        
$migrateElasticPoolSplat
$startAutomationRunBookSplat
        
try {
    Start-AzAutomationRunbook @startAutomationRunBookSplat -verbose -ErrorAction Stop
}
catch {
    $_.Exception.StackTrace
}
```
![image](https://user-images.githubusercontent.com/24279339/90575403-37377b80-e1b3-11ea-9a65-41c279f37aff.png)

Printing the values of the parameters passed to the command are all populated

```powershell
Name                           Value                                                                                    
----                           -----                                                                                    
VCoreCount                     2                                                                                        
ComputeGeneration              Gen5                                                                                     
ElasticPoolName                elasticPool001                                                           
ResourceGroup                  Default-SQL-NorthEurope                                                                  
Edition                        GeneralPurpose                                                                           
DatabaseVCoreMax               0.25                                                                                     
ServerName                     xe4na4qokb                                                                               

Name                           Value                                                                                    
----                           -----                                                                                    
AutomationAccountName          SageOnlineAutomationAccount                                                              
Name                           Invoke-DbMigration                                                                       
ResourceGroupName              s100-stage-oms                                                                           
Parameters                     {VCoreCount, ComputeGeneration, ElasticPoolName, ResourceGroup...}
```

Enabling Debug preference shows that it surfaces an error as ResourceGroup not found but the resourceGroup definitely exists. It appears that this is a generic error being returned as mentioned in https://github.com/Azure/azure-powershell/issues/8200.

This same runbook works in another subscription/automation account fine with the only difference being that some of the modules in that automation account are a build version lower however the Az.Automation module is the same version.

```
Broken                      working
==============              ==============
Az.Accounts = 1.9.2         Az.Accounts = 1.9.1
Az.Automation = 1.3.7       Az.Automation = 1.3.7
Az.Sql = 2.9.1              Az.Sql = 2.9.0
```

## Environment data

This is running in an Azure Automation PowerShell Runbook.

## Module versions

```powershell
Az.Accounts = 1.9.2
Az.Automation = 1.3.7
Az.Sql = 2.9.1
```

## Debug output

<details>

```
============================ HTTP REQUEST ============================

HTTP Method:

GET

Absolute Uri:

https://management.azure.com/subscriptions/365e7e52-f7ee-4f10-a652-35d9eea157b7/resourceGroups/s100-stage-oms/providers/

Microsoft.Automation/automationAccounts/SageOnlineAutomationAccount/runbooks/Invoke-DbMigration?api-version=2018-06-30


Headers:

x-ms-client-request-id        : f78df516-4c83-4b12-95dd-f2d55a86e6de

accept-language               : en-US



Body:


============================ HTTP RESPONSE ============================

Status Code:

NotFound



Headers:

Pragma                        : no-cache

x-ms-failure-cause            : gateway

x-ms-request-id               : c67db8bc-3d1b-48bf-85a8-44cb11ac2dcb

x-ms-correlation-request-id   : c67db8bc-3d1b-48bf-85a8-44cb11ac2dcb

x-ms-routing-request-id       : WESTEUROPE:20200818T224443Z:c67db8bc-3d1b-48bf-85a8-44cb11ac2dcb

Strict-Transport-Security     : max-age=31536000; includeSubDomains

X-Content-Type-Options        : nosniff

Cache-Control                 : no-cache

Date                          : Tue, 18 Aug 2020 22:44:43 GMT



Body:

{

  "error": {

    "code": "ResourceGroupNotFound",

    "message": "Resource group 's100-stage-oms' could not be found."

  }

}





   at Microsoft.Azure.Commands.Automation.Common.AutomationPSClient.ProcessRunbookParameters(String resourceGroupName, String automationAccountName, String runbookName, IDictionary parameters)

   at Microsoft.Azure.Commands.Automation.Common.AutomationPSClient.StartRunbook(String resourceGroupName, String automationAccountName, String runbookName, IDictionary parameters, String runOn)

   at Microsoft.Azure.Commands.Automation.Cmdlet.StartAzureAutomationRunbook.AutomationProcessRecord()

   at Microsoft.Azure.Commands.Automation.Cmdlet.AzureAutomationBaseCmdlet.ExecuteCmdlet()

   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()

10:44:45 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.

10:44:45 PM - using account id 'ef34faae-002f-4c73-8c12-34abd41ac468'...

Breaking changes in the cmdlet 'Resolve-AzError' :

 - The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use 

`Resolve-AzError` instead.



NOTE : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other 

information on breaking changes in Azure PowerShell.



InnerException   : False

Exception        : System.NullReferenceException: Object reference not set to an instance of an object.

                      at Microsoft.Azure.Commands.Automation.Common.AutomationPSClient.ProcessRunbookParameters(String 

                   resourceGroupName, String automationAccountName, String runbookName, IDictionary parameters)

                      at Microsoft.Azure.Commands.Automation.Common.AutomationPSClient.StartRunbook(String 

                   resourceGroupName, String automationAccountName, String runbookName, IDictionary parameters, String 

                   runOn)

                      at 

                   Microsoft.Azure.Commands.Automation.Cmdlet.StartAzureAutomationRunbook.AutomationProcessRecord()

                      at Microsoft.Azure.Commands.Automation.Cmdlet.AzureAutomationBaseCmdlet.ExecuteCmdlet()

                      at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()

Message          : Object reference not set to an instance of an object.

StackTrace       :    at Microsoft.Azure.Commands.Automation.Common.AutomationPSClient.ProcessRunbookParameters(String 

                   resourceGroupName, String automationAccountName, String runbookName, IDictionary parameters)

                      at Microsoft.Azure.Commands.Automation.Common.AutomationPSClient.StartRunbook(String 

                   resourceGroupName, String automationAccountName, String runbookName, IDictionary parameters, String 

                   runOn)

                      at 

                   Microsoft.Azure.Commands.Automation.Cmdlet.StartAzureAutomationRunbook.AutomationProcessRecord()

                      at Microsoft.Azure.Commands.Automation.Cmdlet.AzureAutomationBaseCmdlet.ExecuteCmdlet()

                      at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()

HelpLink         : 

ErrorDetails     : 

ErrorCategory    : CloseError: (:) [Start-AzAutomationRunbook], NullReferenceException

InvocationInfo   : System.Management.Automation.InvocationInfo

ScriptStackTrace : at <ScriptBlock>, <No file>: line 146

AzureQoSEvent: CommandName - Resolve-AzError; IsSuccess - True; Duration - 00:00:00.5027576;

Finish sending metric.

10:44:46 PM - ResolveError end processing.

at <ScriptBlock>, <No file>: line 146

10:44:46 PM - GetAzureRMContextCommand begin processing with ParameterSet 'GetSingleContext'.

10:44:47 PM - using account id 'ef34faae-002f-4c73-8c12-34abd41ac468'...

AzureQoSEvent: CommandName - Get-AzContext; IsSuccess - True; Duration - 00:00:00.6331159;

Finish sending metric.

10:44:48 PM - GetAzureRMContextCommand end processing.

10:44:49 PM - GetAzureRMContextCommand begin processing with ParameterSet 'GetSingleContext'.

10:44:49 PM - using account id 'ef34faae-002f-4c73-8c12-34abd41ac468'...

AzureQoSEvent: CommandName - Get-AzContext; IsSuccess - True; Duration - 00:00:00.6365358;

Finish sending metric.

10:44:50 PM - GetAzureRMContextCommand end processing.

10:44:51 PM - SetAzureSqlElasticPool begin processing with ParameterSet 'DtuBasedPool'.

10:44:51 PM - using account id 'ef34faae-002f-4c73-8c12-34abd41ac468'...

[Common.Authentication]: Checking token expiration, token expires '08/18/2020 23:44:26 +00:00' Comparing to '08/18/2020 

22:44:51 +00:00' With threshold '00:05:00', calculated time until token expiry: '00:59:35.2967249'
```

</details>

## Error output

this is listed above as part of the Runbook output

**Comment by dingmeng-xue** [comment] 2020-08-20 15:11
@brettmillerb , thanks for reporting. I tried the same code but cannot reproduce your issue. I found I don't need to configure Az.Account or Az.Sql because they are not required. Could you let me know how you used them?

**Comment by brettmillerb** [comment] 2020-08-20 15:20
@dingmeng-xue I have added the two (sanitised) runbooks to a gist here: https://gist.github.com/brettmillerb/5a5ab9a9a8c987e30a161dced31b35df

They are both in the same automation account. I have checked and double checked my automationvariables are correct. Removed and recreated them and the resourceGroup definitely exists.

**Comment by brettmillerb** [comment] 2020-09-11 12:06
Okay, so I finally got to the bottom of this today.

The issue I was seeing was that the Context subscription which the runas account was running under was a different subscription to the automation account.

So I added a `Set-AzContext-Subscription $subscription` to the runbook and I was able start the other runbook.

This can be closed but the 'ResourceGroupNotFound` was a little misleading in trying to diagnose the error unfortunately.

**Comment by dingmeng-xue** [comment] 2020-09-11 12:25
@brettmillerb , thanks for information and sorry that I didn't do further investigation.

"NotFound" message is by design in an access controlled system. It won't expose sensitive information that target object is non-existing or inaccessible due to permission.

**Comment by dingmeng-xue** [comment] 2020-09-11 12:25
Close this issue now. Thanks again.

**Closed by dingmeng-xue** 2020-09-11 12:25 UTC
Labels: Automation, customer-reported, question
