### ISSUE TITLE
Update-AzureRmVM : Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by RenarsBD** [Azure/azure-powershell#6916] opened 2018-08-13 15:35 UTC
### Description
Idea is to create Linux VM OsDisk Snapshot to recover from failed OS patching or soft upgrade. 
Before update or patching create VM OsDisk snapshot,
In case need to revert back to initial setup, convert snapshot to managed disk, stop VM, swap/revert back to original OsDisk, start VM. All should be up and running.

#### CREATE VM OS DISK SNAPSHOT AND REVER BACK INITIAL OS DISK ####

# Parameters
$rgName = "TeztXstoreResGrp"
$location = "North Europe"
$vmName = "r01-xstore-App0"
$snapshotName = "r01-xstore-App0_OsDiskSnapshot"
$newDiskName = "r01-xstore-App0_OsDisk_new"

## CREATE SNAPSHOT ##

# Get the VM
$getVm = Get-AzureRmVM -ResourceGroupName $rgName -Name $vmName
# Create snapshot configuration for OS disk
$snapshot = New-AzureRmSnapshotConfig -SourceUri $getVm.Storageprofile.OsDisk.ManagedDisk.Id -Location $location -CreateOption copy
# Make the snapshot
New-AzureRmSnapshot -Snapshot $snapshot -SnapshotName $snapshotName -ResourceGroupName $rgName

## IN CASE NEED TO RESTORE BACK TO ORIGINAL OS DISK ##

# STEP1: CONVERT SNAPSHOT AS NEW MANAGED DISK ####

# Get snapshot object Id to create new OS disk from
$getSnapshotId = Get-AzureRmSnapshot -SnapshotName $snapshotName -ResourceGroupName $rgName
# Create new OS disk configuration from snapshot
$newDiskConfig = New-AzureRmDiskConfig -Location $location -CreateOption Copy -SourceUri $getSnapshotId.Id -SourceResourceId $snapshot.Id
# Do Snapshot conversion to OS disk 
New-AzureRmDisk -Disk $newDiskConfig -ResourceGroupName $rgName -DiskName $newDiskName

# STEP2: SWAP OS DISKS #

# Get the VM name 
$getVm = Get-AzureRmVM -ResourceGroupName $rgName -Name $vmName
# Stop\deallocate VM
Stop-AzureRmVM -ResourceGroupName $rgName -Name $getVm.Name -Force
# Get the new disk that you want to swap in
$disk = Get-AzureRmDisk -ResourceGroupName $rgName -Name $newDiskName
# Set the VM configuration to point to the new disk
Set-AzureRmVMOSDisk -VM $getVM -ManagedDiskId $disk.Id -Name $disk.Name
# Update the VM with the new OS disk
Update-AzureRmVM -ResourceGroupName $rgName -VM $getVm
# Start the VM
Start-AzureRmVM -Name $getVm.Name -ResourceGroupName $rgName

### Module Version

ModuleType Version    Name                                ExportedCommands                    
---------- -------    ----                                ----------------                    
Script     6.6.0      AzureRM                                                                 

### Environment Data

Name                           Value                                                          
----                           -----                                                          
PSVersion                      5.1.15063.909                                                  
PSEdition                      Desktop                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                        
BuildVersion                   10.0.15063.909                                                 
CLRVersion                     4.0.30319.42000                                                
WSManStackVersion              3.0                                                            
PSRemotingProtocolVersion      2.3                                                            
SerializationVersion           1.1.0.1                                                        

### Debug Output

Update-AzureRmVM -ResourceGroupName $rgName -VM $getVm
DEBUG: 6:24:31 PM - UpdateAzureVMCommand begin processing with ParameterSet 'ResourceGroupNameP
arameterSetName'.
DEBUG: 6:24:31 PM - using account id 'email@mail.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'email@mail.com'
, environment: 'AzureCloud', tenant: '585bda71-88ce-428b-1111-11eaa3dce123'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 08/13/2018 15:24:31: 92e3ba32-514d-414e-8cd5-a1234adbb1b1 - AcquireTokenHandlerBase: ===
 Token Acquisition started:
	Authority: https://login.microsoftonline.com/585bda71-88ce-428b-1111-11eaa1dce111/
	Resource: https://management.core.windows.net/
	ClientId: 1950a111-111b-1e11-a1cf-111111111fc1
	CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (3 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 08/13/2018 15:24:31:  - TokenCache: Deserialized 3 items to token cache.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 08/13/2018 15:24:31: 92e3ba32-514d-414e-8cd5-a1234adbb1b1 - TokenCache: Looking up cache
 for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 08/13/2018 15:24:31: 92e3ba32-514d-414e-8cd5-a1234adbb1b1 - TokenCache: An item matching
 the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 08/13/2018 15:24:31: 92e3ba32-514d-414e-8cd5-a1234adbb1b1 - TokenCache: 57.634119195 min
utes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 08/13/2018 15:24:31: 92e3ba32-514d-414e-8cd5-a1234adbb1b1 - TokenCache: A matching item 
(access token or refresh token or both) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 08/13/2018 15:24:31: 92e3ba32-514d-414e-8cd5-a1234adbb1b1 - AcquireTokenHandlerBase: ===
 Token Acquisition finished successfully. An access token was retuned:
	Access Token Hash: 1DNqMLF/WVf1Gvk01rRjcbKrqf11mXhVNlIcHL1cpQ1=
	Refresh Token Hash: 1xwPfWnZJlVQ11l7HkaDfX4fvLt1AXWoVRFEDVVRY11=
	Expiration Time: 08/13/2018 16:22:10 +00:00
	User Hash: IM1FzfXZxja/A1mn1Lk11YR+JZFUVweE1tHYbAd/1nE=
	

Update-AzureRmVM : Object reference not set to an instance of an object.
At line:1 char:1
+ Update-AzureRmVM -ResourceGroupName $rgName -VM $getVm
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Update-AzureRmVM], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.UpdateAzureVMCommand
 
DEBUG: AzureQoSEvent: CommandName - Update-AzureRmVM; IsSuccess - False; Duration - 00:00:00.06
48733; Exception - System.NullReferenceException: Object reference not set to an instance of an
 object.
   at Microsoft.Azure.Management.Compute.Models.StorageAccountTypes.ToString()
   at Microsoft.Azure.Management.Compute.Models.StorageAccountTypesConverter.WriteJson(JsonWrit
er writer, Object value, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWrite
r writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract c
ollectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter wri
ter, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract coll
ectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter wri
ter, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract coll
ectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter wri
ter, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract coll
ectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWrite
r, Object value, Type objectType)
   at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer)
   at Microsoft.Rest.Serialization.TransformationJsonConverter.WriteJson(JsonWriter writer, Obj
ect value, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWrite
r writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract c
ollectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWrite
r, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Typ
e objectType)
   at Microsoft.Rest.Serialization.SafeJsonConvert.SerializeObject(Object obj, JsonSerializerSe
ttings settings)
   at Microsoft.Azure.Management.Compute.VirtualMachinesOperations.<BeginCreateOrUpdateWithHttp
MessagesAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task 
task)
   at Microsoft.Azure.Management.Compute.VirtualMachinesOperations.<CreateOrUpdateWithHttpMessa
gesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task 
task)
   at Microsoft.Azure.Commands.Compute.UpdateAzureVMCommand.<ExecuteCmdlet>b__40_0()
   at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action actio
n)
   at Microsoft.Azure.Commands.Compute.UpdateAzureVMCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 6:24:32 PM - UpdateAzureVMCommand end processing.
DEBUG: 6:24:32 PM - UpdateAzureVMCommand end processing.

**Comment by maddieclayton** [comment] 2018-08-13 18:27
@nibhat @koralski @savyasachisamal Can you take a look at this issue?

**Comment by RenarsBD** [comment] 2018-08-14 10:00
Tested with other AzureRM module versions, same bug observed for AzureRM module versions 6.2.0 - 6.6.0

**Comment by hyonholee** [comment] 2018-08-16 02:15
The root cause is the generated client library has a converter for storage account type, and even the value is null, it tries to write the value by calling value.ToString()  (below line).  

https://github.com/Azure/azure-sdk-for-net/blob/8852cf540d6b68acf2ce7f0d3505749c8dd9aa91/src/SDKs/Compute/Management.Compute/Generated/Models/StorageAccountTypesConverter.cs#L49

**Comment by SMGonc** [comment] 2018-09-12 10:47
**Problem solved in AzureRM module version 6.8.1!**

![2018-09-12_11h38_41](https://user-images.githubusercontent.com/42805372/45419975-bc898b80-b680-11e8-990d-fac1381b871b.png)

# Variables
$rgName="RG-DataDisks"
$rgName2="RG-VMs"
$locName="West Europe"
$vmName = "DC01"

$mdDataDiskName01="DC01_DataDisk02"
$mdTypeDiskName01="Standard_LRS"
$mdSizeDiskName01="32"

# Create Data Disk
$MDdiskConfig01 = New-AzureRmDiskConfig -SkuName $mdTypeDiskName01 -Location $locName -CreateOption Empty -DiskSizeGB $mdSizeDiskName01
$MDdisk01 = New-AzureRmDisk -DiskName $mdDataDiskName01 -Disk $MDdiskConfig01 -ResourceGroupName $rgName

# Add Data Disk
$vm02 = Get-AzureRmVM -Name $vmName -ResourceGroupName $rgName2
$vm02 = Add-AzureRmVMDataDisk -VM $vm02 -Name $mdDataDiskName01 -CreateOption Attach -ManagedDiskId $MDdisk01.Id -Lun 0
Update-AzureRmVM -VM $vm02 -ResourceGroupName $rgName2

![2018-09-12_11h38_32](https://user-images.githubusercontent.com/42805372/45419992-c7dcb700-b680-11e8-9e64-733d5aa237b0.png)

![2018-09-12_11h43_00](https://user-images.githubusercontent.com/42805372/45420065-0b372580-b681-11e8-87e1-db04e4abdb9b.png)

**Comment by maddieclayton** [comment] 2018-09-12 20:17
Closing as fixed.

**Closed by maddieclayton** 2018-09-12 20:17 UTC
Labels: Compute, Compute - VM
