### ISSUE TITLE
Scripts hang due to reporting usage data

### ISSUE THREAD

**Issue by zakimaksyutov** [Azure/azure-powershell#8714] opened 2019-03-07 02:28 UTC
## Description

A few days ago noticed that my deployment scripts (many Az commands) started handing at random places. Using Fiddler learned that every Az command tries to upload usage data and sometimes hangs for 2 minutes (and gets 500):

![image](https://user-images.githubusercontent.com/15914532/53927913-2174db80-403d-11e9-92a2-94f01828aeb7.png)

It is not consistent.

## Expected behavior

I'm fine with uploading usage data and helping Azure Powershell team to improve Az package. But uploading this information **MUST NOT** break the main flow.

Please use -AsJob parameter for uploading usage data. Please also consider using batches instead of doing a call per request.

## Workaround

`Disable-AzDataCollection`

After this command deployment scripts stopped hanging.

**Comment by cormacpayne** [comment] 2019-03-07 16:30
@zakimaksyutov thanks for filing this issue -- we will take a look and let you know if there's any additional information need from your side

**Comment by zakimaksyutov** [comment] 2019-03-07 18:26
I think you should do fire and forget approach for this telemetry - send it over the network and return. Reporting usage data must not interfere with main load.

Right now usage reporting adds overhead for every command. And usage telemetry endpoint might have quite different SLA (all SDKs do it asynchronously) than Azure ARM RP.

**Comment by zakimaksyutov** [comment] 2019-03-08 18:13
Here is ingestion latency for usage data for one of the healthy clusters:

![image](https://user-images.githubusercontent.com/15914532/54046355-e67fbe80-4188-11e9-83dc-fe484871ae55.png)

Note, by doing synchronous reporting you easily add 1-2 seconds latency on regular basis. Plus in many cases cmdlets will hang for way longer period of time up to 2 minutes.

The interesting part is that reported usage telemetry make it look that everything is good. When in fact usage telemetry itself *significantly* downgrades customer experience.

Usage ingestion endpoint does *NOT* have SLA for latency. It doesn't affect customers because all SDKs report data asynchronously and doesn't affect customer's main flow. 

Azure Powershell uses [client.Flush()](https://github.com/Azure/azure-powershell-common/blob/84adc2e8e833a22caa8ea714cd5c367e63da227c/src/Common/MetricHelper.cs#L314) - this is clearly against guidelines that Flush must not be used on main path.

Please consider sending data in fire and forget mode - either by implementing your own Telemetry Channel or by sending data directly using REST API without SDK.

**Comment by markcowl** [comment] 2019-05-02 18:57
Closing as duplicate of #9095  Where we will track the new telemetry mechanism

**Closed by markcowl** 2019-05-02 18:57 UTC
Labels: Azure PS Team, Investigate :mag:
