### ISSUE TITLE
Get-AzSynapsePipeline is failing when a Pipeline contains Dataflows and Expressions

### ISSUE THREAD

**Issue by aanhalzer** [Azure/azure-powershell#20324] opened 2022-11-29 21:53 UTC
### Description

Get-AzSynapsePipeline is failing on pipelines with dataflows and expressions. The command below is with Az.Synapse v 2.1.0
<img width="769" alt="image" src="https://user-images.githubusercontent.com/17557336/204655657-7e973755-5495-4b95-92dd-3ab9d2e99cb3.png">

When a command is run only providing the WorkspaceName parameter, since the workspace contains a Pipeline with Dataflows and expressions, it fails.
<img width="771" alt="image" src="https://user-images.githubusercontent.com/17557336/204655694-904b626e-801a-4600-8faa-89bf86d32701.png">

If a Pipeline that does not contain dataflows and expressions is referenced, the command completes. It also completes if the Workspace does not contain any Pipelines that have dataflows and expressions. The issue is with pipelines that contain dataflows and expressions. Here is an example of a false negative:
<img width="718" alt="image" src="https://user-images.githubusercontent.com/17557336/204658481-cdbcb4e8-d305-4f05-b260-4b8f9c07bdcc.png">

It seems that Powershell commands do not like dynamic variables in Pipelines. This is an example:
<img width="458" alt="image" src="https://user-images.githubusercontent.com/17557336/204676849-475399a0-5750-4a85-b478-420f6438324b.png">

I have noticed this deprecating further and further. In v1.1.0 it was pretty solid, but in v2.1.0 it is much more sensitive.

### Issue script & Debug output

```PowerShell
Get-AzSynapsePipeline : The requested operation requires an element of type 'Number', but the target element 
has type 'Object'.
At line:2 char:1
+ Get-AzSynapsePipeline -WorkspaceName mssdistsynwsnightly
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzSynapsePipeline], InvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Synapse.GetAzureSynapsePipeline
```

### Environment data

```PowerShell
Name                           Value                                                                            
----                           -----                                                                            
PSVersion                      5.1.22621.608                                                                    
PSEdition                      Desktop                                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                          
BuildVersion                   10.0.22621.608                                                                   
CLRVersion                     4.0.30319.42000                                                                  
WSManStackVersion              3.0                                                                              
PSRemotingProtocolVersion      2.3                                                                              
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands                                      
---------- -------    ----                                ----------------                                      
Script     2.1.0      Az.Synapse                          {Add-AzSynapseDataFlowDebugSessionPackage, Add-AzSy...
```

**Comment by SaurabhSharma-MSFT** [comment] 2022-11-30 02:02
@aanhalzer We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment] 2022-12-02 09:48
@aanhalzer I am able to reproduce this issue and redirecting this to services team.
@yanjungao718 Can you please help here.

**Comment by yanjungao718** [comment] 2022-12-05 02:30
@SaurabhSharma-MSFT
Offline synced with @aanhalzer, so far we can just specify spark pool name directly but not through expression, PowerShell cmdlets are kept align with rest APIs, and now they don't support dynamic spark pool name, only when Rest APIs support this feature can PowerShell cmdlets support it.

**Comment by aanhalzer** [comment] 2022-12-05 04:05
Raised concern with @yanjungao718 that v1.1 today supports expressions for Spark Pool Names, but v2.1 does not. 
What got me to submit the ticket is that Spark Job Definition Reference breaks in v1.1 when using expressions. This is the code screenshot attached to this very ticket.

Unless v1.1 and v2.1 leverage different APIs, then the cause of failure is elsewhere.

**Comment by yanjungao718** [comment] 2022-12-05 08:00
> Raised concern with @yanjungao718 that v1.1 today supports expressions for Spark Pool Names, but v2.1 does not. What got me to submit the ticket is that Spark Job Definition Reference breaks in v1.1 when using expressions. This is the code screenshot attached to this very ticket.
> 
> Unless v1.1 and v2.1 leverage different APIs, then the cause of failure is elsewhere.

sorry for wrong typo, the **spark pool name** expression is supported, but the **spark job name** is not supported.

**Comment by yanjungao718** [comment] 2022-12-06 05:44
for this failure:
**Get-AzSynapsePipeline : The requested operation requires an element of type 'Number', but the target element 
has type 'Object'.**
It is caused by wrong "numExecutors" type definition, and we will fix it later.

talked with @aanhalzer for his concern, I think for now the solution is downgrade PS version and wait for fix for this ticket and [issue 20186](https://github.com/Azure/azure-powershell/issues/20186)

**Comment by wonner** [comment] 2023-10-09 04:38
fixed.

**Closed by wonner** 2023-10-09 04:38 UTC
Labels: Service Attention, bug, customer-reported, Synapse
