### ISSUE TITLE
New-AzSignalR not updating existing resource

### ISSUE THREAD

**Issue by mattbrailsford** [Azure/azure-powershell#9636] opened 2019-07-12 13:01 UTC
## Description

I'm trying to create a powershell azure function to auto scale an Azure SignalR resource based on the number of connected clients. I have this setup as a http trigger based function which gets triggered by webhook coming from an alert on the resource.

The function gets called fine, and in the function I calculate a unit count to increment the service to based on the webhook contents. Once I know what the target unit count is I them attempt to call:

    New-AzSignalR -ResourceGroupName $resourceGroupName -Name $resourceName -Location $resourceState.Location -Sku Standard_S1 -UnitCount $targetUnitCount

When I try this using the Azure CLI, this updates the existing plan, however with this module, it doesn't appear to change anything and resource is not updated.

I am calling this method after I have authenticated a service principle which is setup with the collaborator role so I believe I should have the relevant permissions to make the update.

I don't receive any errors, the results from `New-AzSignalR` just seems to return the un-changed resource object.

## Steps to reproduce

Create a SignalR service within the azure portal then attempt to call  `New-AzSignalR` using the same details but with an increased unit count. The new unit count doesn't take affect.

## Module versions

```powershell
[12/07/2019 12:59:54] OUTPUT: ModuleType Version    Name                                PSEdition ExportedCommands
[12/07/2019 12:59:54] OUTPUT: ---------- -------    ----                                --------- ----------------
[12/07/2019 12:59:54] OUTPUT: Script     1.8.0      Az                                  Core,Desk 
[12/07/2019 12:59:54] OUTPUT: Script     1.6.0      Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosav.
[12/07/2019 12:59:54] OUTPUT: Script     1.0.1      Az.Aks                              Core,Desk {Get-AzAks, New-AzAks, Remove-AzAks, Import-AzAksCr.
[12/07/2019 12:59:54] OUTPUT: Script     1.1.0      Az.AnalysisServices                 Core,Desk {Resume-AzAnalysisServicesServer, Suspend-AzAnalysi.
[12/07/2019 12:59:54] OUTPUT: Script     1.0.0      Az.ApiManagement                    Core,Desk {Add-AzApiManagementRegion, Get-AzApiManagementSsoT.
[12/07/2019 12:59:54] OUTPUT: Script     1.0.0      Az.ApplicationInsights              Core,Desk {Get-AzApplicationInsights, New-AzApplicationInsigh.
[12/07/2019 12:59:54] OUTPUT: Script     1.2.1      Az.Automation                       Core,Desk {Get-AzAutomationHybridWorkerGroup, Remove-AzAutoma.
[12/07/2019 12:59:54] OUTPUT: Script     1.1.0      Az.Batch                            Core,Desk {Remove-AzBatchAccount, Get-AzBatchAccount, Get-AzB.
[12/07/2019 12:59:54] OUTPUT: Script     1.0.0      Az.Billing                          Core,Desk {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzE.
[12/07/2019 12:59:54] OUTPUT: Script     1.2.0      Az.Cdn                              Core,Desk {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-AzCd.
[12/07/2019 12:59:54] OUTPUT: Script     1.1.0      Az.CognitiveServices                Core,Desk {Get-AzCognitiveServicesAccount, Get-AzCognitiveSer.
[12/07/2019 12:59:54] OUTPUT: Script     1.8.0      Az.Compute                          Core,Desk {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, N.
[12/07/2019 12:59:54] OUTPUT: Script     1.0.1      Az.ContainerInstance                Core,Desk {New-AzContainerGroup, Get-AzContainerGroup, Remove.
[12/07/2019 12:59:54] OUTPUT: Script     1.0.1      Az.ContainerRegistry                Core,Desk {New-AzContainerRegistry, Get-AzContainerRegistry, .
[12/07/2019 12:59:54] OUTPUT: Script     1.1.1      Az.DataFactory                      Core,Desk {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get-A.
[12/07/2019 12:59:54] OUTPUT: Script     1.0.0      Az.DataLakeAnalytics                Core,Desk {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeA.
[12/07/2019 12:59:54] OUTPUT: Script     1.2.0      Az.DataLakeStore                    Core,Desk {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzDat.
[12/07/2019 12:59:54] OUTPUT: Script     1.0.0      Az.DevTestLabs                      Core,Desk {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdo.
[12/07/2019 12:59:54] OUTPUT: Script     1.0.0      Az.Dns                              Core,Desk {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remove-.
[12/07/2019 12:59:54] OUTPUT: Script     1.1.1      Az.EventGrid                        Core,Desk {New-AzEventGridTopic, Get-AzEventGridTopic, Set-Az.
[12/07/2019 12:59:54] OUTPUT: Script     1.1.0      Az.EventHub                         Core,Desk {New-AzEventHubNamespace, Get-AzEventHubNamespace, .
[12/07/2019 12:59:54] OUTPUT: Script     1.1.0      Az.HDInsight                        Core,Desk {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefinit.
[12/07/2019 12:59:54] OUTPUT: Script     1.1.0      Az.IotHub                           Core,Desk {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGroup.
[12/07/2019 12:59:54] OUTPUT: Script     1.2.0      Az.KeyVault                         Core,Desk {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertif.
[12/07/2019 12:59:54] OUTPUT: Script     1.2.1      Az.LogicApp                         Core,Desk {Get-AzIntegrationAccountAgreement, Get-AzIntegrati.
[12/07/2019 12:59:54] OUTPUT: Script     1.1.0      Az.MachineLearning                  Core,Desk {Move-AzMlCommitmentAssociation, Get-AzMlCommitment.
[12/07/2019 12:59:54] OUTPUT: Script     1.0.0      Az.MarketplaceOrdering              Core,Desk {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}
[12/07/2019 12:59:54] OUTPUT: Script     1.1.0      Az.Media                            Core,Desk {Sync-AzMediaServiceStorageKey, Set-AzMediaServiceK.
[12/07/2019 12:59:54] OUTPUT: Script     1.1.0      Az.Monitor                          Core,Desk {Get-AzMetricDefinition, Get-AzMetric, Remove-AzLog.
[12/07/2019 12:59:54] OUTPUT: Script     1.7.0      Az.Network                          Core,Desk {Add-AzApplicationGatewayAuthenticationCertificate,.
[12/07/2019 12:59:54] OUTPUT: Script     1.1.0      Az.NotificationHubs                 Core,Desk {Get-AzNotificationHub, Get-AzNotificationHubAuthor.
[12/07/2019 12:59:54] OUTPUT: Script     1.2.0      Az.OperationalInsights              Core,Desk {New-AzOperationalInsightsAzureActivityLogDataSourc.
[12/07/2019 12:59:54] OUTPUT: Script     1.0.0      Az.PolicyInsights                   Core,Desk {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPolicy.
[12/07/2019 12:59:54] OUTPUT: Script     1.1.0      Az.PowerBIEmbedded                  Core,Desk {Remove-AzPowerBIWorkspaceCollection, Get-AzPowerBI.
[12/07/2019 12:59:54] OUTPUT: Script     1.3.0      Az.RecoveryServices                 Core,Desk {Get-AzRecoveryServicesBackupProperty, Get-AzRecove.
[12/07/2019 12:59:54] OUTPUT: Script     1.1.0      Az.RedisCache                       Core,Desk {Remove-AzRedisCachePatchSchedule, New-AzRedisCache.
[12/07/2019 12:59:54] OUTPUT: Script     1.0.0      Az.Relay                            Core,Desk {New-AzRelayNamespace, Get-AzRelayNamespace, Set-Az.
[12/07/2019 12:59:54] OUTPUT: Script     1.3.1      Az.Resources                        Core,Desk {Get-AzProviderOperation, Remove-AzRoleAssignment, .
[12/07/2019 12:59:54] OUTPUT: Script     1.0.0      Az.ServiceBus                       Core,Desk {New-AzServiceBusNamespace, Get-AzServiceBusNamespa.
[12/07/2019 12:59:54] OUTPUT: Script     1.0.1      Az.ServiceFabric                    Core,Desk {Add-AzServiceFabricApplicationCertificate, Add-AzS.
[12/07/2019 12:59:54] OUTPUT: Script     1.0.2      Az.SignalR                          Core,Desk {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey, Ne.
[12/07/2019 12:59:54] OUTPUT: Script     1.9.0      Az.Sql                              Core,Desk {Get-AzSqlDatabaseTransparentDataEncryption, Get-Az.
[12/07/2019 12:59:54] OUTPUT: Script     1.2.0      Az.Storage                          Core,Desk {Get-AzStorageAccount, Get-AzStorageAccountKey, New.
[12/07/2019 12:59:54] OUTPUT: Script     1.0.0      Az.StreamAnalytics                  Core,Desk {Get-AzStreamAnalyticsFunction, Get-AzStreamAnalyti.
[12/07/2019 12:59:54] OUTPUT: Script     1.0.1      Az.TrafficManager                   Core,Desk {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove.
[12/07/2019 12:59:54] OUTPUT: Script     1.2.0      Az.Websites                         Core,Desk {Get-AzAppServicePlan, Set-AzAppServicePlan, New-Az.
[12/07/2019 12:59:54] OUTPUT: 
[12/07/2019 12:59:54] OUTPUT:     Directory: C:\Users\***\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\powershell\Modules
[12/07/2019 12:59:54] OUTPUT: 
[12/07/2019 12:59:54] OUTPUT: ModuleType Version    Name                                PSEdition ExportedCommands
[12/07/2019 12:59:54] OUTPUT: ---------- -------    ----                                --------- ----------------
[12/07/2019 12:59:54] OUTPUT: Script     0.1.0      Microsoft.Azure.Functions.PowerShe. Core,Desk {Push-OutputBinding, Get-OutputBinding, Trace-Pipel.
[12/07/2019 12:59:54] OUTPUT: Manifest   1.1.0.0    Microsoft.PowerShell.Archive        Desk      {Compress-Archive, Expand-Archive}
[12/07/2019 12:59:54] OUTPUT: Manifest   6.1.0.0    Microsoft.PowerShell.Management     Core      {Add-Content, Clear-Content, Clear-ItemProperty, Jo.
[12/07/2019 12:59:54] OUTPUT: Manifest   6.1.0.0    Microsoft.PowerShell.Utility        Core      {Export-Alias, Get-Alias, Import-Alias, New-Alias.}
[12/07/2019 12:59:54] OUTPUT: Script     1.3.1      PackageManagement                   Desk      {Find-Package, Get-Package, Get-PackageProvider, Ge.
[12/07/2019 12:59:54] OUTPUT: Script     1.1.7.0    PackageManagement                   Desk      {Find-Package, Get-Package, Get-PackageProvider, Ge.
[12/07/2019 12:59:54] OUTPUT: Script     1.6.7      PowerShellGet                       Desk      {Find-Command, Find-DSCResource, Find-Module, Find-.
[12/07/2019 12:59:54] OUTPUT: Binary     1.1.2      ThreadJob                           Desk      Start-ThreadJob
```

**Comment by sphibbs** [comment] 2019-07-15 23:15
@mattbrailsford can you Set $DebugPreference='Continue' before running the repro and paste the resulting debug stream in the below code block?

**Comment by mattbrailsford** [comment] 2019-07-16 08:36
@sphibbs please see below. But FYI I replaced any reference to my keys + service name to empty guids or the word "test", these are the actual values, but I'm guessing they aren't what you need to see.

    DEBUG: 09:31:38 - NewAzureRmSignalR begin processing with ParameterSet '__AllParameterSets'.
    DEBUG: 09:31:38 - using account id '00000000-0000-0000-0000-000000000000'...

    HostName                                           Location       ServerPort PublicPort ProvisioningState Version
    --------                                           --------       ---------- ---------- ----------------- -------
    test.service.signalr.net                            uksouth        443        443        Succeeded         1.0
    DEBUG: [Common.Authentication]: Authenticating using Account: '00000000-0000-0000-0000-000000000000', environment: 'AzureCloud', tenant:
    '00000000-0000-0000-0000-000000000000'
    DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: '00000000-0000-0000-0000-000000000000', Endpoint:
    'https://login.microsoftonline.com/', ClientId: '00000000-0000-0000-0000-000000000000', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob',
    ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthority: 'True'
    DEBUG: [Common.Authentication]: Renewing token using AppId: '00000000-0000-0000-0000-000000000000', AdalConfiguration with ADDomain:
    '00000000-0000-0000-0000-000000000000', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: '00000000-0000-0000-0000-000000000000',
    RedirectUri: 'urn:ietf:wg:oauth:2.0:oob'
    DEBUG: [ADAL]: Information: 2019-07-16T08:31:38.1727818Z: 26f65e77-c89f-45d3-a515-31fd5eca71a4 - LoggerBase.cs: ADAL PCL.Desktop with assembly version
    '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...
    DEBUG: [ADAL]: Information: 2019-07-16T08:31:38.1727818Z: 26f65e77-c89f-45d3-a515-31fd5eca71a4 - LoggerBase.cs: ADAL PCL.Desktop with assembly version
    '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...
    DEBUG: [ADAL]: Information: 2019-07-16T08:31:38.1727818Z: 26f65e77-c89f-45d3-a515-31fd5eca71a4 - LoggerBase.cs: === Token Acquisition started:
    CacheType: null
    Authentication Target: Client
    , Authority Host: login.microsoftonline.com
    DEBUG: [ADAL]: Information: 2019-07-16T08:31:38.1727818Z: 26f65e77-c89f-45d3-a515-31fd5eca71a4 - LoggerBase.cs: === Token Acquisition started:
    Authority: https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000/
    Resource: https://management.core.windows.net/
    ClientId: 00000000-0000-0000-0000-000000000000
    CacheType: null
    Authentication Target: Client

    DEBUG: [ADAL]: Verbose: 2019-07-16T08:31:38.1727818Z: 26f65e77-c89f-45d3-a515-31fd5eca71a4 - LoggerBase.cs: Loading from cache.
    DEBUG: [ADAL]: Verbose: 2019-07-16T08:31:38.1727818Z: 26f65e77-c89f-45d3-a515-31fd5eca71a4 - LoggerBase.cs: Loading from cache.
    DEBUG: [ADAL]: Information: 2019-07-16T08:31:38.1737796Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Deserialized 7 items to token cache.
    DEBUG: [ADAL]: Verbose: 2019-07-16T08:31:38.1737796Z: 26f65e77-c89f-45d3-a515-31fd5eca71a4 - LoggerBase.cs: Looking up cache for a token...
    DEBUG: [ADAL]: Verbose: 2019-07-16T08:31:38.1737796Z: 26f65e77-c89f-45d3-a515-31fd5eca71a4 - LoggerBase.cs: Looking up cache for a token...
    DEBUG: [ADAL]: Information: 2019-07-16T08:31:38.1737796Z: 26f65e77-c89f-45d3-a515-31fd5eca71a4 - LoggerBase.cs: An item matching the requested
    resource was found in the cache
    DEBUG: [ADAL]: Information: 2019-07-16T08:31:38.1737796Z: 26f65e77-c89f-45d3-a515-31fd5eca71a4 - LoggerBase.cs: An item matching the requested
    resource was found in the cache
    DEBUG: [ADAL]: Information: 2019-07-16T08:31:38.1737796Z: 26f65e77-c89f-45d3-a515-31fd5eca71a4 - LoggerBase.cs: 54.69667034 minutes left until token
    in cache expires
    DEBUG: [ADAL]: Information: 2019-07-16T08:31:38.1737796Z: 26f65e77-c89f-45d3-a515-31fd5eca71a4 - LoggerBase.cs: 54.69667034 minutes left until token
    in cache expires
    DEBUG: [ADAL]: Information: 2019-07-16T08:31:38.1737796Z: 26f65e77-c89f-45d3-a515-31fd5eca71a4 - LoggerBase.cs: A matching item (access token or
    refresh token or both) was found in the cache
    DEBUG: [ADAL]: Information: 2019-07-16T08:31:38.1737796Z: 26f65e77-c89f-45d3-a515-31fd5eca71a4 - LoggerBase.cs: A matching item (access token or
    refresh token or both) was found in the cache
    DEBUG: [ADAL]: Information: 2019-07-16T08:31:38.1737796Z: 26f65e77-c89f-45d3-a515-31fd5eca71a4 - LoggerBase.cs: === Token Acquisition finished
    successfully. An access token was returned: Expiration Time: 16/07/2019 09:26:19 +00:00
    DEBUG: [ADAL]: Information: 2019-07-16T08:31:38.1737796Z: 26f65e77-c89f-45d3-a515-31fd5eca71a4 - LoggerBase.cs: === Token Acquisition finished
    successfully. An access token was returned: Expiration Time: 16/07/2019 09:26:19 +00:00Access Token Hash: pk6gCHZAXwd4SWW8X3Cz2mXD9aMgSwhD0IhShs8jp18=
    User id:
    DEBUG: [Common.Authentication]: Checking token expiration, token expires '07/16/2019 09:26:19 +00:00' Comparing to '07/16/2019 08:31:38 +00:00' With
    threshold '00:05:00', calculated time until token expiry: '00:54:41.7992231'
    DEBUG: ============================ HTTP REQUEST ============================

    HTTP Method:
    GET

    Absolute Uri:
    https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/test/providers/Microsoft.SignalRService/SignalR/test?api-
    version=2018-03-01-preview

    Headers:
    x-ms-client-request-id        : 1c8277dd-0f6b-48dc-8a1e-47cfe2abcabd
    accept-language               : en-US

    Body:


    DEBUG: ============================ HTTP RESPONSE ============================

    Status Code:
    OK

    Headers:
    Pragma                        : no-cache
    x-ms-ratelimit-remaining-subscription-reads: 11999
    Strict-Transport-Security     : max-age=31536000; includeSubDomains
    X-Content-Type-Options        : nosniff
    x-ms-client-request-id        : 0243f24e-ea55-493f-b90e-535560783775
    x-rp-server-mvid              : c48e0eb1-9ff8-46dc-a95a-539a413f2f67
    x-ms-request-id               : f3cad3ee-5d53-42f8-a66e-8e791d46c4a2
    x-ms-correlation-request-id   : f1559279-4e6d-4ca7-93c9-cd1ba80dbcee
    x-ms-routing-request-id       : UKSOUTH2:20190716T083141Z:f1559279-4e6d-4ca7-93c9-cd1ba80dbcee
    Cache-Control                 : no-cache
    Date                          : Tue, 16 Jul 2019 08:31:40 GMT
    Server                        : Kestrel

    Body:
    {
    "sku": {
        "name": "Standard_S1",
        "tier": "Standard",
        "size": "S1",
        "capacity": 1
    },
    "properties": {
        "provisioningState": "Succeeded",
        "externalIP": "51.140.118.50",
        "hostName": "test.service.signalr.net",
        "publicPort": 443,
        "serverPort": 443,
        "version": "1.0",
        "hostNamePrefix": "test",
        "features": [
        {
            "flag": "ServiceMode",
            "value": "Serverless",
            "properties": {}
        }
        ],
        "cors": {
        "allowedOrigins": [
            "*"
        ]
        }
    },
    "location": "uksouth",
    "tags": {},
    "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/test/providers/Microsoft.SignalRService/SignalR/test",
    "name": "test",
    "type": "Microsoft.SignalRService/SignalR"
    }

    DEBUG: AzureQoSEvent: CommandName - New-AzSignalR; IsSuccess - True; Duration - 00:00:00.2965593; Exception - ;
    DEBUG: Finish sending metric.
    DEBUG: 09:31:39 - NewAzureRmSignalR end processing.
    DEBUG: 09:31:39 - NewAzureRmSignalR end processing.

**Comment by ArieShout** [comment] 2019-07-29 09:48
@juniwang as I'm not currently working on the project.

**Comment by juniwang** [comment] 2019-07-31 01:36
Sorry for late response, we are working on that. We identified the root cause and are working on a new version.  However we didn't find any workaround fow now, sorry about that. Will keep you updated if any update or workaound.

**Comment by mattbrailsford** [comment] 2019-08-01 08:22
As an update from my end I did find a workaround by using Az-Resource rather than Az-Signalr. I documented my solution on dev.to over at https://dev.to/mattbrailsford/auto-scaling-azures-signalr-service-via-powershell-function-45j5

Would still be good to get Az-Signalr working, but there is at least a solution in the meantime.

**Comment by juniwang** [comment] 2019-08-01 08:34
Great to hear that.  Thanks a lot @mattbrailsford. New version is under development.  The AzSignalR is outdated for a while. We are not only fixing the issues but also adding more cmdlets to catch up with the latest RestAPI/SDKs. It will take some time but we will try our best.

**Comment by juniwang** [comment] 2019-10-15 04:41
The SignalR CmdLets (>=2.7.0) now supports `Update-SignalR`.  You can scale SignalR using it. Thanks. I'm closing this issue.

**Closed by juniwang** 2019-10-15 04:41 UTC
Labels: Service Attention, SignalR
