### ISSUE TITLE
Remove-AzureRmADServicePrincipal does not communicate permission issue

### ISSUE THREAD

**Issue by yevster** [Azure/azure-powershell#5473] opened 2018-02-07 23:24 UTC
### Cmdlet(s)
Remove-AzureRmADServicePrincipal

### PowerShell Version
```
PSVersion                      6.0.1                                                                                                                                                    
PSEdition                      Core         
```
### Module Version
0.9.1
### OS Version
```
OS                             Darwin 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64                    
```

### Description
I get an "Invalid Operation" exception when trying to remove a service principal without having the requisite permission. 

```
> Remove-AzureRmADServicePrincipal -ObjectId $SP_ID -Force                                                                                            
Remove-AzureRmADServicePrincipal : Exception of type 'System.Exception' was thrown.
At line:1 char:1
+ Remove-AzureRmADServicePrincipal -ObjectId $SP_ID -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Remove-AzureRmADServicePrincipal], Exception
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.ActiveDirectory.RemoveAzureADServicePrincipalCommand
```

This is in contrast to the Azure CLI, which communicates the underlying issue clearly:
```
> az ad sp delete --id $SP_ID                                                                                                                         
Insufficient privileges to complete the operation.
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.26/libexec/lib/python3.6/site-packages/knack/cli.py", line 194, in invoke
    cmd_result = self.invocation.execute(args)
...
```
 
### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

```
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Forbidden

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
Server                        : Microsoft-IIS/10.0
ocp-aad-diagnostics-server-name: rFMv6jCt7k8n9zj2NyMLkO1fEa5ijjfeyD4ZP3WWKYs=
request-id                    : f41b1ebf-74b0-4a1e-afec-fa1cc08d2842
client-request-id             : bc32062a-4ab2-420a-96c3-3ecb85cb0bae
x-ms-dirapi-data-contract-version: 1.6
ocp-aad-session-key           : 7eYP3dBeEMZULOaNyDjm-JL5tRw_YgxSV5TUjQ1-SGHCOM7ojBeG6Y4g1v7RSM-jkFn_LVBqiwPqdUD5hkafBET6oyd6-k5I1qPwk088GIJqGv4o8U-j1cDmbP9nTkMg.yO2oZLzIZGACsb_c23AeTSBXwOx1Hizs91yWKwAQ16s
X-Content-Type-Options        : nosniff
DataServiceVersion            : 3.0;
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Access-Control-Allow-Origin   : *
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET,ASP.NET
Duration                      : 426830
Date                          : Wed, 07 Feb 2018 23:23:15 GMT

Body:
{
  "odata.error": {
    "code": "Authorization_RequestDenied",
    "message": {
      "lang": "en",
      "value": "Insufficient privileges to complete the operation."
    }
  }
}
```

### Script/Steps for Reproduction
Run ```Remove-AzureRmADServicePrincipal``` without having permissions to delete a service principal.

**Comment by markcowl** [comment] 2018-02-12 00:05
@yevster Note that, if you run Resolve-AzureRmError, then these same details become more apparent

**Comment by markcowl** [comment] 2018-02-12 00:08
Closing as duplicate of #3649

**Closed by markcowl** 2018-02-12 00:08 UTC
