### ISSUE TITLE
Issues with New-AzureRmRoleAssignment depending on what Login-AzureRMAccount -TenantID is used

### ISSUE THREAD

**Issue by asbjorn-wiik** [Azure/azure-powershell#4805] opened 2017-10-17 13:05 UTC
### Cmdlet(s)
Login-AzureRMAccount
New-AzureRmRoleAssignment

### PowerShell Version
5.1.15063.632

### Module Version
Manifest   0.4.6      Azure.AnalysisServices
Manifest   0.4.6      AzureRM.AnalysisServices
Manifest   4.4.0      AzureRM.ApiManagement
Manifest   3.4.0      AzureRM.Automation
Manifest   3.4.0      AzureRM.Backup
Manifest   3.4.0      AzureRM.Batch
Manifest   0.13.6     AzureRM.Billing
Manifest   3.4.0      AzureRM.Cdn
Manifest   0.8.6      AzureRM.CognitiveServices
Manifest   3.4.0      AzureRM.Compute
Manifest   0.2.6      AzureRM.Consumption
Manifest   0.0.1      AzureRM.ContainerInstance
Manifest   0.2.6      AzureRM.ContainerRegistry
Manifest   3.4.0      AzureRM.DataFactories
Manifest   0.2.0      AzureRM.DataFactoryV2
Manifest   3.4.0      AzureRM.DataLakeAnalytics
Manifest   4.4.0      AzureRM.DataLakeStore
Manifest   3.4.0      AzureRM.DevTestLabs
Manifest   3.4.0      AzureRM.Dns
Manifest   0.1.0      AzureRM.EventGrid
Manifest   0.4.6      AzureRM.EventHub
Manifest   3.4.0      AzureRM.HDInsight
Manifest   3.4.0      AzureRM.Insights
Manifest   2.4.0      AzureRM.IotHub
Manifest   3.4.0      AzureRM.KeyVault
Manifest   3.4.0      AzureRM.LogicApp
Manifest   0.15.6     AzureRM.MachineLearning
Manifest   0.7.6      AzureRM.Media
Manifest   4.4.0      AzureRM.Network
Manifest   3.4.0      AzureRM.NotificationHubs
Manifest   3.4.0      AzureRM.OperationalInsights
Manifest   3.4.0      AzureRM.PowerBIEmbedded
Manifest   3.4.0      AzureRM.Profile
Manifest   3.4.0      AzureRM.RecoveryServices
Manifest   3.4.0      AzureRM.RecoveryServices.Backup
Manifest   0.1.5      AzureRM.RecoveryServices.SiteRec...
Manifest   3.4.0      AzureRM.RedisCache
Manifest   0.2.6      AzureRM.Relay
Manifest   4.4.0      AzureRM.Resources
Manifest   0.15.6     AzureRM.Scheduler
Manifest   3.4.0      AzureRM.ServerManagement
Manifest   0.4.6      AzureRM.ServiceBus
Manifest   0.2.6      AzureRM.ServiceFabric
Manifest   4.4.0      AzureRM.SiteRecovery
Manifest   3.4.0      AzureRM.Sql
Manifest   3.4.0      AzureRM.Storage
Manifest   3.4.0      AzureRM.StreamAnalytics
Manifest   3.4.0      AzureRM.Tags
Manifest   3.4.0      AzureRM.TrafficManager
Manifest   3.4.0      AzureRM.UsageAggregates
Manifest   3.4.0      AzureRM.Websites

### OS Version
10.0.15063.632

### Description
This **doesn't** work
```
Login-AzureRmAccount -TenantId tenantname.onmicrosoft.com
New-AzureRmRoleAssignment –RoleDefinitionName "Owner" -objectId $GroupGuid -scope "/subscriptions/$cspSub"

New-AzureRmRoleAssignment : Your Azure credentials have not been set up or have expired, please run Login-AzureRMAccount to set up your Azure credentials.
At C:\Users\asbjorn.AD\OneDrive\Jobb\scripts\onboarding.ps1:18 char:1
+ New-AzureRmRoleAssignment –RoleDefinitionName "Owner" -objectId $bcct ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmRoleAssignment], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureRoleAssignmentCommand

```
This **does** work
```
Login-AzureRmAccount -TenantId 111d1a11-abcd-dddd-3332-213562cc3baa
New-AzureRmRoleAssignment –RoleDefinitionName "Owner" -objectId $bcct -scope "/subscriptions/$cspSub"
```

### Debug Output
```
DEBUG: 14:53:32 - NewAzureRoleAssignmentCommand begin processing with ParameterSet 'EmptyParameterSet'.
DEBUG: 14:53:32 - using account id 'asbjorn@basefarm.net'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'asbjorn@basefarm.net', environment: 'AzureCloud', tenant: '111d1a11-abcd-dddd-3332-213562cc3baa'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 10/17/2017 12:53:32: 333d1a22-abcd-dddd-4567-213562cc3baa - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/111d1a11-abcd-dddd-3332-213562cc3baa/
	Resource: https://graph.windows.net/
	ClientId: 22226666-abcd-dddd-4567-213562cc3baa
	CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (1 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 10/17/2017 12:53:32: 333d1a22-abcd-dddd-4567-213562cc3baa - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 10/17/2017 12:53:32: 333d1a22-abcd-dddd-4567-213562cc3baa - TokenCache: No matching token was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 10/17/2017 12:53:32: 333d1a22-abcd-dddd-4567-213562cc3baa - AcquireTokenSilentHandler: No token matching arguments found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Error: 4 : 
DEBUG: 10/17/2017 12:53:32: 333d1a22-abcd-dddd-4567-213562cc3baa - <RunAsync>d__0: Microsoft.IdentityModel.Clients.ActiveDirectory.AdalSilentTokenAcquisitionException: Failed to acquire token silen
tly. Call method AcquireToken
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenSilentHandler.SendTokenRequestAsync()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__0.MoveNext()
	ErrorCode: failed_to_acquire_token_silently

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 10/17/2017 12:53:32:  - TokenCache: Serializing token cache with 1 items.

DEBUG: [Common.Authentication]: Received exception Authentication error while acquiring token: 'Failed to acquire token silently. Call method AcquireToken'., while authenticating.
New-AzureRmRoleAssignment : Your Azure credentials have not been set up or have expired, please run Login-AzureRMAccount to set up your Azure credentials.
At C:\Users\asbjorn.AD\OneDrive\Jobb\scripts\onboarding.ps1:20 char:1
+ New-AzureRmRoleAssignment –RoleDefinitionName "Owner" -objectId $bcct ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmRoleAssignment], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureRoleAssignmentCommand
 
DEBUG: AzureQoSEvent: CommandName - New-AzureRmRoleAssignment; IsSuccess - False; Duration - 00:00:00.0600580; Exception - System.ArgumentException: Your Azure credentials have not been set up or h
ave expired, please run Login-AzureRMAccount to set up your Azure credentials. ---> Microsoft.Rest.Azure.Authentication.AuthenticationException: Authentication error while acquiring token: 'Failed 
to acquire token silently. Call method AcquireToken'. ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalSilentTokenAcquisitionException: Failed to acquire token silently. Call method Acquire
Token
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenSilentHandler.SendTokenRequestAsync()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenSilentCommonAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenSilentAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.Authentication.UserTokenProvider.<CreateCredentialsFromCache>d__28.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Rest.Azure.Authentication.UserTokenProvider.<CreateCredentialsFromCache>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.GetServiceClientCredentials(IAzureContext context, String targetEndpoint)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.GetServiceClientCredentials(IAzureContext context, String targetEndpoint)
   at Microsoft.Azure.Commands.Common.Authentication.Factories.ClientFactory.CreateArmClient[TClient](IAzureContext context, String endpoint)
   at Microsoft.Azure.Graph.RBAC.Version1_6.ActiveDirectory.ActiveDirectoryClient..ctor(IAzureContext context)
   at Microsoft.Azure.Commands.Resources.Models.Authorization.AuthorizationClient..ctor(IAzureContext context)
   at Microsoft.Azure.Commands.Resources.Models.ResourcesBaseCmdlet.get_PoliciesClient()
   at Microsoft.Azure.Commands.Resources.NewAzureRoleAssignmentCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 14:53:32 - NewAzureRoleAssignmentCommand end processing.
DEBUG: 14:53:32 - NewAzureRoleAssignmentCommand end processing.

```
### Script/Steps for Reproduction
Login-AzureRmAccount -TenantId tenantname.onmicrosoft.com
New-AzureRmRoleAssignment –RoleDefinitionName "Owner" -objectId $GroupGuid -scope "/subscriptions/$cspSub"

**Comment by cormacpayne** [comment] 2017-10-17 22:10
@asbjorn-wiik Hey Asbjørn, the first command is failing because you are providing a tenant name for the `TenantId` parameter, which is not supported.

We need to add some checks around users providing a tenant name vs tenant id and provide an appropriate error message so you don't run into the issue you are seeing in the first example. We will keep this issue open to track the status of this work.

@cormacpayne @twitchax  add this in the Cloud Shell work

**Comment by asbjorn-wiik** [comment] 2017-10-18 08:15
@cormacpayne @twitchax 
Hi Cormac, I'm a little confused because you write that using tenant FQDN name is not supported, yet I do get logged in using `Login-AzureRmAccount -TenantID tenantFQDNname`.
Running `Get-AzureRmContext` returns the same output whether logging with tenantFQDNname or UUID
I would also like to point out that the tenantFQDNname should be just as unique as the UUID and therefore it makes sense that tenantFQDNname should be supported 

Regards,
Asbjørn Wiik

**Comment by markcowl** [comment] 2017-11-11 01:28
tenant name is not currently supported, as credentials cannot be retrieved from the cache when they are stored suing the domain name.  This issue is being tracked here: #3974 

Closing this issue as a duplicate of that one, please track the fix there

**Closed by markcowl** 2017-11-11 01:28 UTC
Labels: Azure PS Team
