### ISSUE TITLE
New WAM feature (even when not enabled) breaks Azure PS login due to missing assemblies in nano server container

### ISSUE THREAD

**Issue by keystroke** [Azure/azure-powershell#20824] opened 2023-02-02 00:03 UTC
### Description

Issue script below has more information, but it seems that when using AzurePs from nano server container, the MSAL initialization of WAM induces an error, even if the user of AzurePS is not enabling it or does not want to use it.

### Issue script & Debug output

```PowerShell
`
FROM mcr.microsoft.com/powershell:lts-nanoserver-1809 as final

# Set powershell as default shell
SHELL ["pwsh", "-NonI", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'Continue'; $verbosePreference='Continue';"]

# Disable pwsh ansi escape sequences
ENV NO_COLOR true
# Install Powershell modules
# (added -SkipPublisherCheck because nanoserver can't verify signing )
# (added -Scope AllUsers because the current user's module path is not included in the PSModulePath)
# (Az.ContainerRegistry installs an unsupported version of Az.Accounts, so it must be deleted and replaced with 2.2.8)
RUN [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 ; `
    Install-Module -Name Az.BootStrapper -Force -SkipPublisherCheck -Scope AllUsers ; `
    Install-AzProfile -Profile 2020-09-01-hybrid -Force ; `
    Install-Module -Name AzureStack -RequiredVersion 2.2.0 -Force -SkipPublisherCheck -Scope AllUsers ; `
    Install-Module Azs.ContainerRegistry.Admin -Force -SkipPublisherCheck -Scope AllUsers ; `
    Install-Module -Name Az.ContainerRegistry -Force -SkipPublisherCheck -Scope AllUsers ; `
    Remove-Item 'C:\Program Files\PowerShell\Modules\Az.Accounts\' -Force -Recurse ; `
    Install-Module Az.Accounts -RequiredVersion 2.2.8 -Scope AllUsers -Force -SkipPublisherCheck
````

The issue is then induced when performing a resource owner sign-in flow to an AAD environment (MSAL seems to know ADFS is not supported with WAM).

````
function Login-AdminPowershell {
    param (
        [Parameter(Mandatory = $true)]
        [string] $ResultFileName,
        [Parameter(Mandatory = $false)]
        [string] $AdminEnvironmentName = "AdminARM"
    )

    Invoke-TestCase -TestCaseName "Add-AzEnvironment $AdminEnvironmentName" `
        -Command "Add-AzEnvironment -Name $AdminEnvironmentName -ARMEndpoint $env:AdminArmEndpoint" `
        -ResultFileName $ResultFileName

    Invoke-TestCase -TestCaseName "Connect-AzAccount Service Admin" `
        -Command "Connect-AzAccount -EnvironmentName $AdminEnvironmentName -TenantId $env:TenantId -Credential (New-Object System.Management.Automation.PSCredential (`"${env:ServiceAdminUserName}`", (ConvertTo-SecureString -AsPlainText -Force `"${env:ServiceAdminPassword}`")))" `
        -ResultFileName $ResultFileName
}
````

WARNING: Unable to acquire token for tenant '76440dfb-c97c-4fee-8f6c-dff8ddbe816f' with error 'SharedTokenCacheCredential authentication failed: Unable to load DLL 'msalruntime' or one of its dependencies: The specified module could not be found. (0x8007007E) See https://aka.ms/msal-net-wam#troubleshooting'

Above induces errors on subsequent commands as it cannot sign-in.

The link above indicates this could be do to missing environment configuration, perhaps related to what nano server includes by default versus windows server 2019:

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/wam#unable-to-load-dll-msalruntime-or-one-of-its-dependencies-the-specified-module-could-not-be-found-error-message

However, it seems Azure PS is only intending to flight this as an optional feature:
https://github.com/Azure/azure-powershell/commit/ee54b4c1e3528f31f8b2a18bed31be931fab32cc

It looks like AzurePs enables WAM in all cases for public client use:
https://github.com/Azure/azure-powershell/blob/bc60c4239b7ed59851cb7eead2d1f073cd631f82/src/Accounts/Authentication/Authentication/TokenCache/PowerShellTokenCacheProvider.cs#L167

However it should only be used when passing the relevant flag:
https://github.com/Azure/azure-powershell/blob/bc60c4239b7ed59851cb7eead2d1f073cd631f82/src/Accounts/Authentication/Factories/AuthenticationFactory.cs#L618

It may be that either AzurePs needs to enable enable the broker usage on MSAL unless the caller has opted-in, OR perhaps something in MSAL under the hood is making some assumptions about environment config that don't hold in nano server.

Issue does not repro in linux container, or when using an ADFS authority URI (it seems MSAL under the hood detects /adfs in the authority URI and knows to not "initialize" the WAM stuff).
```


### Environment data

```PowerShell
See above
```

### Module versions

```PowerShell
see above
```

### Error output

```PowerShell
Unable to acquire token for tenant '76440dfb-c97c-4fee-8f6c-dff8ddbe816f' with error 'SharedTokenCacheCredential authentication failed: Unable to load DLL 'msalruntime' or one of its dependencies: The specified module could not be found. (0x8007007E) See https://aka.ms/msal-net-wam#troubleshooting'
```

**Comment by keystroke** [comment] 2023-02-02 00:24
CC @rjaini

**Comment by isra-fel** [comment] 2023-02-02 01:33
I'll investigate.

**Comment by isra-fel** [comment] 2023-02-20 16:14
Hi @keystroke , thanks for reporting and your investigation. I am working on the fix. Targeting the upcoming March 7th release.
It seems to me the root cause is the `SharedTokenCacheCredentialBrokerOptions` type, which only makes sense when WAM is available in the current environment - we should use the alternative `SharedTokenCacheCredentialOptions` when it's not.

https://github.com/Azure/azure-powershell/blob/919880fa25aa35539f6308bbec224e4d9a8e0484/src/Accounts/Authenticators/SilentAuthenticator.cs#L62

**Comment by isra-fel** [comment] 2023-02-21 06:53
@keystroke  Hi, I've made the fix in a PR and produced an engineering build. It would be great if you could give it a quick test. Thanks 😀 

Download the package from: https://azposhpreview.blob.core.windows.net/public/Az.Accounts.2.11.2.nupkg
You can either put it in a local repository and install it from there, or use our utility module Az.Tools.Installer:

```powershell
Install-Module -Name Az.Tools.Installer -Repository PSGallery
Install-AzModule -path https://azposhpreview.blob.core.windows.net/public/Az.Accounts.2.11.2.nupkg -RemovePrevious
```

**Comment by gloacai** [comment] 2023-02-23 15:18
Running into an issue and I believe this is the root cause as well. Running Az.Accounts 2.11.2 on my computer. I'm writing a C# app that eventually calls a powershell.Invoke(). In one of the resulting powershell scripts it makes a call out to Get-AzOperationalInsightsWorkspace which dies because of method not found error on `SharedTokenCacheCredentialBrokerOptions`. 

Downgrading my computer's version of Az.Accounts back to 2.10.4 fixes it. 

Alternatively adding the Azure.Identity.BrokeredAuthentication nuget package will also allow me to go forward but that package is still in BETA so I don't want to use it yet.

**Comment by isra-fel** [comment] 2023-02-24 02:58
@gloacai thanks for sharing the feedback 👍 
This will be fixed in the next release - we won't use `SharedTokenCacheCredentialBrokerOptions` unless you opt-in.
BTW may I know on which OS and architecture did you run into the issue?

**Closed** 2023-02-27 07:57 UTC
Labels: Azure PS Team, bug, Accounts, Tracking
