### ISSUE TITLE
Get-AzureRmAutomationJobOutput -Stream param allows Debug, when it isn't captured

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#5207] opened 2018-01-02 20:37 UTC
### Cmdlet(s)
Get-AzureRmAutomationJobOutput
### PowerShell Version
5.1.16299.98
### Module Version
4.1.1
### OS Version
10.0.16299.98
### Description
As described here (https://docs.microsoft.com/en-us/azure/automation/automation-runbook-output-and-messages), Azure Automation jobs do not store Debug information as part of their output object. However, the [Get-AzureRmAutomationJobOutput](https://docs.microsoft.com/en-us/powershell/module/azurerm.automation/get-azurermautomationjoboutput?view=azurermps-5.1.1) has a parameter to specify the stream type (via -Stream), which allows the value Debug. Since the output does not capture the Debug stream, this stream type won't contain any information.
- [ ] Remove StreamType Debug for -Stream in Get-AzureRmAutomationJobOutput

Also, I have a 'nice to have' suggestion while doing this. Currently, -Stream only accepts one type. For example, `-Stream Verbose`. It would be very nice (and follow PoSh conventions) to allows it to accept a list of types. For example, `-Stream Verbose,Output,Error`. This allows users to simply specify in 1 call what different streams they actually want. Currently, the only option is to use `-Stream Any`, which returns all stream types, and then the client has to parse that information for the streams they want.
- [ ] [Suggested] Allow -Stream to accept multiple (list) of types

**Comment by markcowl** [comment] 2018-01-16 23:20
@vrdmr We should start a discussion about remodling these cmdlets so that they are more compliant and easier to use.

This looks like the cmdlet offers a capability that doesn't exist, so maybe we can fix this before a complete redesign.

**Comment by jeffzabel** [comment] 2019-10-23 19:14
This is working as designed.  Closing

**Closed by jeffzabel** 2019-10-23 19:14 UTC
Labels: Automation, Service Attention
