### ISSUE TITLE
webapp:Sync Network for Azure App Service connected to VNet

### ISSUE THREAD

**Issue by russcam** [Azure/azure-powershell#3391] opened 2017-01-16 07:09 UTC
### PowerShell Version
PSVersion 5.1.14393.693

### OS Version
BuildVersion 10.0.14393.693

### Description

After connecting an App Service to a VNet using something similar to https://docs.microsoft.com/en-us/azure/app-service-web/app-service-vnet-integration-powershell#resource-manager-virtual-networks, "Sync Network" has to be performed before the Azure App can connect to any attached devices in the VNet. Trying to connect to a device before this has been done yields:

```
System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions 
```
"Sync Network" can be done within the Azure Portal:

![vnet_integration](https://cloud.githubusercontent.com/assets/208231/21973718/c913903a-dc16-11e6-8cf8-cd471a57b571.png)

Is this exposed in the Azure PowerShell SDK?

**Comment by markcowl** [comment] 2017-01-17 22:33
@Nking92 Please comment on our support tor this in ARM APIs for WebApps

**Comment by russcam** [comment] 2017-01-17 23:09
I _think_ I've found the setting in [resource explorer](https://resources.azure.com) for it, under 

resource group -> providers -> Microsoft.Web -> serverfarms -> App Service Plan name -> virtualNetworkConnections

```json
[
  {
    "id": null,
    "name": "[redacted]",
    "type": "Microsoft.Web/serverfarms/virtualNetworkConnections",
    "location": "Australia Southeast",
    "tags": null,
    "properties": {
      "vnetResourceId": "/subscriptions/[redacted]/resourceGroups/[redacted]/providers/Microsoft.Network/virtualNetworks/[redacted]",
      "certThumbprint": "[redacted]",
      "certBlob": "[redacted]",
      "routes": null,
      "resyncRequired": false,   <-- is this the setting?
      "dnsServers": null
    }
  }
]
```

but can't see how it's exposed in PowerShell SDK

**Comment by ChrisCompy** [comment] 2017-01-18 01:04
The sync operation is not directly supported in powershell or API.  Rather, it involves several API calls that are currently brokered by the portal to get a package from VNet, pull the certs, set them in app service and also send our generated certs to VNet and make sure they are on what we have.  It also does a route sync operation to ensure that the apps are using the proper VNet owned routes for sending traffic over.  Since the operations to networking are tenant operations, all this is currently implemented at the portal rather than geo.

**Comment by russcam** [comment] 2017-01-18 01:15
As it stands, it is not possible to completely automate connecting an App Service to a Virtual Network, a scenario that I would expect is _extremely common_ e.g. a web application connected to an Elasticsearch cluster on the backend, as in this case. Will this be exposed in a future SDK release?

It would be worth also [updating the documentation](https://docs.microsoft.com/en-us/azure/app-service-web/app-service-vnet-integration-powershell#resource-manager-virtual-networks) to indicate that a sync network is required after connecting the App Service to an existing VNet; I found out through trial and error 😄

**Comment by ChrisCompy** [comment] 2017-01-18 01:21
right.  it's not possible which is painful.  No disagreement from me there and it's something I want to fix someday.  It's not a high priority right now though so this is where it stands for now.  There are some P2S changes coming this year that may help give opportunity though.  
The sync network should only be needed to sync routes.  It should work fine without that with the standard RFC 1918 traffic headed into the VPN though.  Was that not the case for you?

**Comment by russcam** [comment] 2017-01-18 02:59
> The sync network should only be needed to sync routes. It should work fine without that with the standard RFC 1918 traffic headed into the VPN though. Was that not the case for you?

I've found that I need to Sync Network every time, with my example script. I can put together a small reproducible example if it would help to rule out PEBKAC?

**Comment by ChrisCompy** [comment] 2017-01-18 19:42
maybe it's a nuance on how you are doing the script.   I don't remember the exact reason for why we don't do a route sync at the end of setup.  It's been a year since we added the V2 VNet stuff but I will ask and see.

**Comment by russcam** [comment] 2017-01-19 00:14
@ChrisCompy that would be greatly appreciated. Let me know also if you would like a reproducible example and I'll put one together.

**Comment by IoBebe** [comment] 2017-03-07 13:25
i'm running into the same issue here. any updates ?

**Comment by glen-richards-aranzgeo** [comment] 2017-03-28 01:00
I've hit the same problem trying to automate an upgrade process for our infrastructure.

**Comment by liamdawson** [comment] 2017-06-08 05:50
This is _incredibly_ annoying - if I re-run the environment template in CI, an error "Connection attempt failed: The requested address is not valid in its context" returns after **every deploy**. Is there any api at all that can be called? Or even some way I can manually provide my own certificates for the connection? I'm unsure of where the app service gets the private key from.

**Comment by akuryan** [comment] 2017-06-28 16:27
I am hitting the same issue from ARM template - and, yes, it is **incredibly annoying**.
In short, I am provisioning web apps in several web app services to be connected to service on VM in VNET. It will not work until I will not resync network.
If it is not possible from ARM - maybe there is a powershell cmdlet which will resync network for me?

**Comment by 4c74356b41** [comment] 2017-08-31 16:56
any updates? how is portal orchestrating something, why cant we do exactly the same calls?

**Comment by konste** [comment] 2017-10-20 04:33
I was breaking my head over this issue for a couple days by now, but I think I found rather non-obvious workaround which makes the darn thing work without clicking "Sync Network". Check out this link: https://codexample.org/questions/896170/add-a-azure-webapp-to-an-existing-vpn-using-a-point-to-site-connection-rm-powershell.c#acmt-3927376 

In short $packageUri = Get-AzureRmVpnClientPackage for unknown reason (probably a bug) returns packageUri in quotes! One extra statement removes the quotes and vnet connectivity works right away.
```$packageUri = $packageUri.Substring(1, $packageUri.Length-2);```
It helped me and hopefully help you too.

**Comment by turowicz** [comment] 2018-03-19 13:53
It's been a while since the issue was created, is the problem still there?

**Comment by jrudley** [comment] 2018-06-11 17:55
Any update on this?

**Comment by jrudley** [comment] 2018-06-11 20:13
Any update on this? I can reproduce this still

**Comment by turowicz** [comment] 2018-06-15 07:13
Calling @panchagnula and @Nking92

**Comment by panchagnula** [comment] 2018-06-15 15:05
@turowicz sorry no ETA at this time

**Comment by willgarcia** [comment] 2018-08-21 10:16
@panchagnula @Nking92 @turowicz do you know if there is an automated way (az cli / cmdlet / ARM / other) to disconnect + reconnect the App service vnet (as a temporary workaround)?

**Comment by panchagnula** [comment] 2018-08-21 21:14
@willgarcia  we don't have an ETA for first-class command for CLI & Powershell for supporting VNET yet, however please refer to these scripts that might help you for the time-being https://gallery.technet.microsoft.com/scriptcenter/Connect-an-app-in-Azure-ab7527e3
https://docs.microsoft.com/en-us/azure/app-service/web-sites-integrate-with-vnet#powershell-automation

**Comment by panchagnula** [comment] 2019-06-21 05:49
Closing this sine there is a no proper API to support this at this time. We will brig this back after we figure out the API support with the backend.

**Closed by panchagnula** 2019-06-21 05:49 UTC
Labels: App Services, Service Attention

**Comment by abell27** [comment] 2020-04-21 14:25
It has been a year since this was closed. Has this functionality been added? I am having this issue still today.
