### ISSUE TITLE
ARM: Fix Get-AzureLocation and add a location filter for Get-AzureProvider (P2)

### ISSUE THREAD

**Issue by vivsriaus** [Azure/azure-powershell#707] opened 2015-08-06 23:38 UTC
Per Ryan,

1) Get-azure locations should really just show the list of azure locations. This is a breaking change, so we might have to add a warning message and keep the "legacy" output as is, until we decide to sunset it.
2) We add a –location filter to the get-azureprovider cmdlet which allows you to get only providers with types in the specified location.

**Comment by pcgeek86** [comment] 2015-08-08 17:01
Also, `Get-AzureLocation` should have a `-Name` parameter that accepts wildcards.

```
### Retrieve United State Azure regions / locations
Get-AzureLocation -Name *us*;

### Retrieve Japanese Azure regions / locations
Get-AzureLocation -Name *japan*;
```

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by pcgeek86** [comment] 2015-09-12 20:15
ps. Duplicate of https://github.com/Azure/azure-powershell/issues/488

**Comment by pcgeek86** [comment] 2015-09-12 20:28
ps. Still broken in 0.9.8, release just two days ago.

**Comment by chadiel** [comment] 2015-09-14 20:15
I disagree with the name parameter since there is no server side support for this and the client side filtering is very straightforward  

Get-AzureLocation | Where {$_.Name -like '*us*' }

**Comment by pcgeek86** [comment] 2015-09-18 14:19
One of the PowerShell principles that the Azure PowerShell team needs to get on board with is that PowerShell functionality does not necessarily need to match API functionality one-for-one. Designing a PowerShell module, based on the design of a REST API is a recipe for failure. PowerShell module design is its own topic, and a PowerShell user's interface to a REST API should be simplified. Just because there is no server-side support for something, does not mean that a related PowerShell command should also not expose the capability.

The Azure PowerShell team needs to reconsider its objectives, because the current objective of merely wrapping the REST API is not conducive to positive user experience. In some cases, the commands need to implement additional functionality to make the experience simple to use.

You can disagree, but it doesn't change ideal PowerShell design principles.

Cheers,
**Trevor Sullivan**
Microsoft MVP PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by ravbhatnagar** [comment] 2016-02-10 19:03
This is being discussed in #1299 . Please provide feedback there.

**Comment by ravbhatnagar** [comment] 2016-02-12 01:56
#1 is being tracked in #1299 and #2 has been fixed. Closing this.

**Comment by ravbhatnagar** [comment] 2016-02-12 01:57
Leave a comment

**Comment by ravbhatnagar** [comment] 2016-02-12 01:58
Issue 1 above is tracked in #1299 and Issue 2 has been fixed. Closing this.

**Closed by ravbhatnagar** 2016-02-12 01:58 UTC
Labels: ResourceManager
