### ISSUE TITLE
ARM 0.9.5 :: Get-AzureLocation returns confusing results

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#637] opened 2015-07-21 22:07 UTC
# Symptom
The `Get-AzureLocation` command does not return objects that represent locations as top-level elements.

# Expected Results

The `Get-AzureLocation` command should return objects that represent locations (Azure regions). Any Azure services that are available in each Azure region should be exposed as properties of the object.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by alexandair** [comment] 2015-07-22 07:00
@pcgeek86 Is this the same issue as [#488] (https://github.com/Azure/azure-powershell/issues/488)?

**Comment by pcgeek86** [comment] 2015-07-22 17:20
@alexandair Yes, but it wasn't fixed in the 0.9.5 release, as you pointed out. The issue needs visibility, and I fear that it has fallen too far down the list to be prioritized.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by devigned** [comment] 2015-07-22 20:57
I agree this needs to be improved, but I don't see a point in having duplicate issues. I'm closing this due to it being a duplicate of #488.

**Closed by devigned** 2015-07-22 20:57 UTC
