### ISSUE TITLE
Get-AzureRmResource followed by Set-AzureRmResource changing JSON data type 

### ISSUE THREAD

**Issue by jsheetzati** [Azure/azure-powershell#7930] opened 2018-11-28 03:27 UTC
### Description

We are using Get-AzureRmResource and Set-AzureRmResource to automate some logic app deployments. When running the script, Set-AzureRmResource is turning numeric and boolean data types into strings. This looks very similar to this issue: https://github.com/Azure/azure-powershell/issues/5940

For example, in our logic app definition json file, we have the following chunk of json:

```json
"expression": {
	"and": [
		{
			"equals": [
				"@outputs('SubmitParseCsvFileJob')['statusCode']",
				200
			]
		}
	]
}
```

After piping the resource into Set-AzureRmResource, we end up with the following in the Portal: 

```json
"expression": {
	"and": [
		{
			"equals": [
				"@outputs('SubmitParseCsvFileJob')['statusCode']",
				"200"
			]
		}
	]
}
```

This is just one example of a data type changing but it happens many times within the logic app definition when deploying in this manner.

### Script/Steps for Reproduction

If you need the full script illustrating the issue, I am more than happy to provide. 

```powershell
$resource = Get-AzureRmResource ...
$definition = (Get-Content -Raw -Path "jsonFile.json") | ConvertFrom-Json
$resource.Properties.definition = $definition
$resource  | Set-AzureRmResource
```

### Module Version
6.13.1

### Environment Data

PSVersion                      5.1.17134.228                                                                                                           
PSEdition                      Desktop                                                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                 
BuildVersion                   10.0.17134.228                                                                                                          
CLRVersion                     4.0.30319.42000                                                                                                         
WSManStackVersion              3.0                                                                                                                     
PSRemotingProtocolVersion      2.3                                                                                                                     
SerializationVersion           1.1.0.1                                                                                                                 

### Debug Output

Very long.. can provided if needed.

**Comment by jsheetzati** [comment] 2018-12-05 16:23
@cormacpayne I have the debug log that illustrates the issue for you. Unfortunately, due to contractual obligations, I am not able to share publicly. I can send you the gist link if that is okay with you. My email is in my profile. Thanks!

**Comment by jsheetzati** [comment] 2018-12-11 17:52
@cormacpayne I scrubbed the log to remove our personal information that we cannot share. I hope it helps. https://gist.github.com/jsheetzati/bfdf89ba9fd6391f4e22c532f3cd2e2d

**Comment by cormacpayne** [comment] 2019-02-19 17:13
@jsheetzati I'm unable to reproduce this when using the latest `Az` module -- one thing I would figure out is what the value of the `Properties` property on the `$resource` object is after this line is executed:

```powershell
$definition = (Get-Content -Raw -Path "jsonFile.json") | ConvertFrom-Json
```

It may be the case that the `jsonFile.json` file has the certain numeric and boolean values as strings, or they are being converted to strings when executing `ConvertFrom-Json`. Would you mind verifying that the `Properties` property contains the correct value before it is piped to the `Set-AzResource` cmdlet?

**Comment by jsheetzati** [comment] 2019-02-19 18:56
Here is a sample json file + powershell script that I am running. Confirmed it is still an issue with Az 1.3.0. I added some logging on one of the properties right before SetAzResource. After SetAzResource, I retrieve the resource again and the type is now a string.

Output from running script with json file:
Updating JoeTest
Int32
Updated JoeTest
String
done

LogicApp,json
```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Condition": {
                "actions": {
                    "Terminate": {
                        "inputs": {
                            "runError": {
                                "message": "Counter is string"
                            },
                            "runStatus": "Failed"
                        },
                        "runAfter": {},
                        "type": "Terminate"
                    }
                },
                "else": {
                    "actions": {
                        "Terminate_2": {
                            "inputs": {
                                "runStatus": "Succeeded"
                            },
                            "runAfter": {},
                            "type": "Terminate"
                        }
                    }
                },
                "expression": {
                    "and": [
                        {
                            "equals": [
                                "@variables('counter')",
                                "1"
                            ]
                        }
                    ]
                },
                "runAfter": {
                    "Initialize_variable": [
                        "Succeeded"
                    ]
                },
                "type": "If"
            },
            "Initialize_variable": {
                "inputs": {
                    "variables": [
                        {
                            "name": "counter",
                            "type": "Integer",
                            "value": 1
                        }
                    ]
                },
                "runAfter": {},
                "type": "InitializeVariable"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "parameters": {},
        "triggers": {
            "Recurrence": {
                "recurrence": {
                    "frequency": "Week",
                    "interval": 1
                },
                "type": "Recurrence"
            }
        }
    }
}
```
Powershell Script
```powershell
$ResourceName = "LogicAppResourceName"
$ResourceGroupName = "ResourceGroup"
    

Write-Host "Updating $($ResourceName)"
$resource = Get-AzResource -ResourceGroupName $ResourceGroupName -name $ResourceName -ResourceType Microsoft.Logic/workflows 
if (!$resource) {
    throw "No resource found"
}
    
$definitionAsJson = (Get-Content -Raw -Path "LogicApp.json")
if (!$definitionAsJson) { 
    throw "Unable to read json file for $($logicApp)"
}

$definition = $definitionAsJson | ConvertFrom-Json

$resource.Properties.definition = $definition.definition

try {
    Write-Host $resource.Properties.definition.actions.Initialize_variable.inputs.variables[0].value.GetType().Name

    $resource | Set-AzResource -Force -ErrorAction Stop | Out-Null
    
    Write-Host "Updated $($resourceName)"
    
    $updateResource = Get-AzResource -ResourceGroupName $ResourceGroupName -name $ResourceName -ResourceType Microsoft.Logic/workflows 
    Write-Host $updateResource.Properties.definition.actions.Initialize_variable.inputs.variables[0].value.GetType().Name
} catch {
    throw $_
}
    

Write-Host "done"
```

**Comment by cormacpayne** [comment] 2019-02-19 21:49
@jsheetzati thanks for going through the work of getting this extra information. I was able to reproduce this exception and track down where the issue is coming from: https://github.com/Azure/azure-powershell/blob/9fff8523d74afd5e9e499c31e1a0f46373e950e5/src/Resources/ResourceManager/Extensions/PsObjectExtensions.cs#L135

We will look at a fix for this in an upcoming release.

**Comment by jsheetzati** [comment] 2019-02-20 03:00
Awesome. Will this fix be applied to both Az and AzureRm?

**Comment by cormacpayne** [comment] 2019-02-21 22:49
@jsheetzati this fix would only be applied to `Az.Resources` -- we plan on updating `AzureRM` modules only in cases where a high priority bug fix is needed.

**Comment by cormacpayne** [comment] 2019-02-21 23:02
Fix for this issue can be found in PR https://github.com/Azure/azure-powershell/pull/8593

**Comment by jsheetzati** [comment] 2019-02-21 23:26
Sounds good. Thanks for resolving this!

**Comment by cormacpayne** [comment] 2019-03-06 22:50
The fix for this will be available in the upcoming release of `Az` (version 1.5.0 released on March 12th, 2019).

**Closed by cormacpayne** 2019-03-06 22:50 UTC
Labels: Azure PS Team, Pull Request Open
