### ISSUE TITLE
Not able to build the solution 

### ISSUE THREAD

**Issue by kattamudi-karthik** [Azure/azure-powershell#10696] opened 2019-12-11 14:13 UTC
Hi Team ,

When I am trying to clone and build the solution facing the below error

**Your project does not reference ".NETFramework,Version=v4.5.2" framework. Add a reference to ".NETFramework, Version=v4.5.2" in the "TargetFrameworks" property of your project file and then re-run NuGet restore.    Commands.Common.Authentication.ResourceManager**           

I have seen already reference in each project as <TargetFrameworkVersion>v4.5.2</TargetFrameworkVersion>
 
Can you please help me to set up the solution?

**Comment by msJinLei** [comment] 2019-12-12 03:15
@kattamudi-karthik Is your question that you cannot build our existing solution or you cannot build your new added solution? 
If the first one, this may caused by your local dot framework.
 If the second one, you should use Az.props and no target framework is required specifying explicitly.
````
 <Import Project="$(MSBuildThisFileDirectory)..\..\Az.props" />
````

**Comment by kattamudi-karthik** [comment] 2019-12-13 11:03
It the first one .

**Comment by msJinLei** [comment] 2019-12-16 08:53
> It the first one .

Can you run this command and paste result here?
````
dotnet.exe --info
````

The output should something like
````
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
````

**Comment by kattamudi-karthik** [comment] 2019-12-16 10:07
Please find the output below :

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  1.1.14 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by msJinLei** [comment] 2019-12-19 10:40
> Please find the output below :
> 
> .NET Core SDK (reflecting any global.json):
> Version: 3.0.100
> Commit: 04339c3a26
> 
> Runtime Environment:
> OS Name: Windows
> OS Version: 10.0.18363
> OS Platform: Windows
> RID: win10-x64
> Base Path: C:\Program Files\dotnet\sdk\3.0.100\
> 
> Host (useful for support):
> Version: 3.0.0
> Commit: 7d57652f33
> 
> .NET Core SDKs installed:
> 1.1.14 [C:\Program Files\dotnet\sdk]
> 2.1.801 [C:\Program Files\dotnet\sdk]
> 2.1.802 [C:\Program Files\dotnet\sdk]
> 3.0.100 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
> Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
> Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
> Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
> Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
> Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
> Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
> 
> To install additional .NET Core runtimes or SDKs:
> https://aka.ms/dotnet-download

The .net environment looks OK.
- And then how do you run the build process?
- Do you have any other local change in your local machine?
- what about the other environment information? Please run $PSVersionTable in powershell and paste the output in the below code block

**Comment by dingmeng-xue** [comment] 2020-01-14 08:02
@kattamudi-karthik Is there any update?

**Comment by dingmeng-xue** [comment] 2020-03-01 03:36
@kattamudi-karthik, we close this issue now. If you meet other issue, please raise a new issue.

**Closed by dingmeng-xue** 2020-03-01 03:36 UTC
Labels: Azure PS Team, More Info :label:
