### ISSUE TITLE
Get-AzUserAssignedIdentity Ignores DefaultProfile

### ISSUE THREAD

**Issue by jreinmilleratmosera** [Azure/azure-powershell#20963] opened 2023-02-17 22:52 UTC
### Description

Our code runs in two Azure contexts. Need to run Get-AzUserAssignedIdentity in Context 2 using DefaultProfile to lookup a UMI in that Subscription, while the default context is Context 1. The issue is that Get-AzUserAssignedIdentity does not respect the context passed to it via the DefaultProfile parameter. The two Contexts are in different Tenants.

We run dozens of other cmdlets with this same configuration without issue. Only Get-AzUserAssignedIdentity seems to ignore the context specified by DefaultProfile.

Have observed this behavior in both Public and Gov Cloud.

Have observed this behavior with a user or Service Principal login.

### Issue script & Debug output

```PowerShell
# Context 1
PS C:\Users\jreinmiller\Documents> $context1

Name                                     Account                                    SubscriptionName                           Environment                               TenantId
----                                     -------                                    ----------------                           -----------                               --------
Default                                  8f29nnnn-nnnn-nnnn-nnnn-nnnnnnnn639b       Subscription1                              AzureUSGovernment                         b96dnnnn-nnnn-nnnn-nnnn-nnnnnnnnec99

PS C:\Users\jreinmiller\Documents> $context1.Subscription.id
c19cnnnn-nnnn-nnnn-nnnn-nnnnnnnn89ca

# Context 2
PS C:\Users\jreinmiller\Documents> $context2

Name                                     Account                                    SubscriptionName                           Environment                               TenantId
----                                     -------                                    ----------------                           -----------                               --------
Default                                  addcnnnn-nnnn-nnnn-nnnn-nnnnnnnnaf38       Subscription2                              AzureUSGovernment                         e37annnn-nnnn-nnnn-nnnn-nnnnnnnn2d3f

PS C:\Users\jreinmiller\Documents> $context2.Subscription.id
8e70nnnn-nnnn-nnnn-nnnn-nnnnnnnn2471

# Currently in Context 1
PS C:\Users\jreinmiller\Documents> Get-AzContext

Name                                     Account                                    SubscriptionName                           Environment                               TenantId
----                                     -------                                    ----------------                           -----------                               --------
Automation (c19cnnnn-nnnn-nnnn-nnnn-nnn… 8f29nnnn-nnnn-nnnn-nnnn-nnnnnnnn639b       Subscription1                              AzureUSGovernment                         b96dnnnn-nnnn-nnnn-nnnn-nnnnnnnnec99

# Need to run Get-AzUserAssignedIdentity in Context 2 to lookup a UMI in that Subscription.
# The issue is that Get-AzUserAssignedIdentity does not respect the context passed to it via the DefaultProfile parameter.

PS C:\Users\jreinmiller\Documents> Get-AzUserAssignedIdentity `
   -DefaultProfile $context2 `
   -Name "umiName" `
   -ResourceGroupName resourcegroup0 `
   -SubscriptionId 8e70nnnn-nnnn-nnnn-nnnn-nnnnnnnn2471 -debug -verbose

DEBUG: [CmdletBeginProcessing]: Starting command
DEBUG: CmdletBeginProcessing:
DEBUG: CmdletProcessRecordStart:
DEBUG: CmdletGetPipeline:
DEBUG: CmdletBeforeAPICall:
DEBUG: URLCreated: /subscriptions/8e70nnnn-nnnn-nnnn-nnnn-nnnnnnnn2471/resourceGroups/resourcegroup0/providers/Microsoft.ManagedIdentity/userAssignedIdentities/umiName?api-version=2022-01-31-preview
DEBUG: RequestCreated: /subscriptions/8e70nnnn-nnnn-nnnn-nnnn-nnnnnnnn2471/resourceGroups/resourcegroup0/providers/Microsoft.ManagedIdentity/userAssignedIdentities/umiName?api-version=2022-01-31-preview
DEBUG: HeaderParametersAdded:
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.usgovcloudapi.net/subscriptions/8e70nnnn-nnnn-nnnn-nnnn-nnnnnnnn2471/resourceGroups/resourcegroup0/providers/Microsoft.ManagedIdentity/userAssignedIdentities/umiName?api-version=2022-01-31-preview

Headers:
x-ms-unique-id                : 7
x-ms-client-request-id        : f6c1a494-nnnn-nnnn-nnnn-4dc3c27c5341
CommandName                   : Get-AzUserAssignedIdentity
FullCommandName               : Get-AzUserAssignedIdentity_Get
ParameterSetName              : __AllParameterSets
User-Agent                    : AzurePowershell/v9.4.0,PSVersion/v7.3.2,Az.ManagedServiceIdentity/1.1.0

Body:



DEBUG: BeforeCall:
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Unauthorized

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
WWW-Authenticate              : Bearer authorization_uri="https://login.microsoftonline.us/e37annnn-nnnn-nnnn-nnnn-nnnnnnnn2d3f", error="invalid_token", error_description="The access token is from the wrong issuer. It must match the tenant associated with this subscription. Please use correct authority to get the token."
x-ms-failure-cause            : gateway
x-ms-request-id               : a53db4d2-nnnn-nnnn-nnnn-c192a34d47e2
x-ms-correlation-request-id   : a53db4d2-nnnn-nnnn-nnnn-c192a34d47e2
x-ms-routing-request-id       : USGOVARIZONA:20230217T214752Z:a53db4d2-nnnn-nnnn-nnnn-c192a34d47e2
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Fri, 17 Feb 2023 21:47:52 GMT
Connection                    : close

Body:
{
  "error": {
    "code": "InvalidAuthenticationTokenTenant",
    "message": "The access token is from the wrong issuer 'https://sts.windows.net/b96dnnnn-nnnn-nnnn-nnnn-nnnnnnnnec99/'. It must match the tenant 'https://sts.windows.net/e37annnn-nnnn-nnnn-nnnn-nnnnnnnn2d3f/' associated with this subscription. Please use the authority (URL) 'https://login.microsoftonline.us/e37annnn-nnnn-nnnn-nnnn-nnnnnnnn2d3f' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later."
  }
}


DEBUG: ResponseCreated:
DEBUG: BeforeResponseDispatch:
WARNING: Get-AzUserAssignedIdentity_Get is not found. The most similar Azure PowerShell command is:
        Get-AzUserAssignedIdentity
Get-AzUserAssignedIdentity_Get: The access token is from the wrong issuer 'https://sts.windows.net/b96dnnnn-nnnn-nnnn-nnnn-nnnnnnnnec99/'. It must match the tenant 'https://sts.windows.net/e37annnn-nnnn-nnnn-nnnn-nnnnnnnn2d3f/' associated with this subscription. Please use the authority (URL) 'https://login.microsoftonline.us/e37annnn-nnnn-nnnn-nnnn-nnnnnnnn2d3f' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later.
DEBUG: [Finally]: Getting exception 'Microsoft.Azure.Commands.Common.Exceptions.AzPSCloudException: InternalException' from response
DEBUG: Finally:
DEBUG: CmdletAfterAPICall:
DEBUG: [CmdletProcessRecordAsyncEnd]: Finish HTTP process
DEBUG: CmdletProcessRecordAsyncEnd:
DEBUG: CmdletProcessRecordEnd:
DEBUG: AzureQoSEvent: Module: Az.ManagedServiceIdentity:1.1.0; CommandName: Get-AzUserAssignedIdentity; PSVersion: 7.3.2; IsSuccess: False; Duration: 00:00:00.6463770; Exception: InternalException;

# If I manually switch the Context and then run the command, it works as intended.

PS C:\Users\jreinmiller\Documents> set-azcontext -Context $context2
DEBUG: 14:07:33 - SetAzureRMContextCommand begin processing with ParameterSet 'Context'.
DEBUG: 14:07:33 - using account id '8f29nnnn-nnnn-nnnn-nnnn-nnnnnnnn639b'...
DEBUG: 14:07:33 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 14:07:33 - Autosave setting from startup session: 'CurrentUser'
DEBUG: 14:07:33 - No autosave setting detected in environment variable 'AzContextAutoSave'.
DEBUG: 14:07:33 - Using Autosave scope 'CurrentUser'

Name                                     Account                                    SubscriptionName                           Environment                               TenantId
----                                     -------                                    ----------------                           -----------                               --------
Subscription2 (8e70nnnn-n… 		 addcnnnn-nnnn-nnnn-nnnn-nnnnnnnnaf38       Subscription 2                             AzureUSGovernment                         e37annnn-nnnn-nnnn-nnnn-nnnnnnnn2d3f
DEBUG: 14:07:33 - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
DEBUG: AzureQoSEvent: Module: Az.Accounts:2.10.2; CommandName: Set-AzContext; PSVersion: 7.3.2; IsSuccess: True; Duration: 00:00:00.0433286
DEBUG: 14:07:33 - SetAzureRMContextCommand end processing.

PS C:\Users\jreinmiller\Documents> Get-AzUserAssignedIdentity `
   -DefaultProfile $context2 `
   -Name "umiName" `
   -ResourceGroupName resourcegroup0 `
   -SubscriptionId 8e70nnnn-nnnn-nnnn-nnnn-nnnnnnnn2471 -debug -verbose

DEBUG: [CmdletBeginProcessing]: Starting command
DEBUG: CmdletBeginProcessing:
DEBUG: CmdletProcessRecordStart:
DEBUG: CmdletGetPipeline:
DEBUG: CmdletBeforeAPICall:
DEBUG: URLCreated: /subscriptions/8e70nnnn-nnnn-nnnn-nnnn-nnnnnnnn2471/resourceGroups/resourcegroup0/providers/Microsoft.ManagedIdentity/userAssignedIdentities/umiName?api-version=2022-01-31-preview
DEBUG: RequestCreated: /subscriptions/8e70nnnn-nnnn-nnnn-nnnn-nnnnnnnn2471/resourceGroups/resourcegroup0/providers/Microsoft.ManagedIdentity/userAssignedIdentities/umiName?api-version=2022-01-31-preview
DEBUG: HeaderParametersAdded:
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.usgovcloudapi.net/subscriptions/8e70nnnn-nnnn-nnnn-nnnn-nnnnnnnn2471/resourceGroups/resourcegroup0/providers/Microsoft.ManagedIdentity/userAssignedIdentities/umiName?api-version=2022-01-31-preview

Headers:
x-ms-unique-id                : 8
x-ms-client-request-id        : ef8930a3-nnnn-nnnn-nnnn-458f84773a89
CommandName                   : Get-AzUserAssignedIdentity
FullCommandName               : Get-AzUserAssignedIdentity_Get
ParameterSetName              : __AllParameterSets
User-Agent                    : AzurePowershell/v9.4.0,PSVersion/v7.3.2,Az.ManagedServiceIdentity/1.1.0

Body:



DEBUG: BeforeCall:
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-reads: 14989
x-ms-request-id               : 68763b82-nnnn-nnnn-nnnn-bfd72fb1d8c6
x-ms-correlation-request-id   : 68763b82-nnnn-nnnn-nnnn-bfd72fb1d8c6
x-ms-routing-request-id       : USGOVARIZONA:20230217T221015Z:68763b82-nnnn-nnnn-nnnn-bfd72fb1d8c6
X-Content-Type-Options        : nosniff
Date                          : Fri, 17 Feb 2023 22:10:14 GMT

Body:
{
  "id": "/subscriptions/8e70nnnn-nnnn-nnnn-nnnn-nnnnnnnn2471/resourcegroups/resourcegroup0/providers/Microsoft.ManagedIdentity/userAssignedIdentities/umiName",
  "name": "umiName",
  "type": "Microsoft.ManagedIdentity/userAssignedIdentities",
  "location": "usgovvirginia",
  "tags": {},
  "properties": {
    "tenantId": "e37annnn-nnnn-nnnn-nnnn-nnnnnnnn2d3f",
    "principalId": "12a3nnnn-nnnn-nnnn-nnnn-nnnnnnnn3f3b",
    "clientId": "61dcnnnn-nnnn-nnnn-nnnn-nnnnnnnnd267"
  }
}


DEBUG: ResponseCreated:
DEBUG: BeforeResponseDispatch:

DEBUG: Finally:
DEBUG: CmdletAfterAPICall:
DEBUG: [CmdletProcessRecordAsyncEnd]: Finish HTTP process
DEBUG: CmdletProcessRecordAsyncEnd:
DEBUG: CmdletProcessRecordEnd:
DEBUG: AzureQoSEvent: Module: Az.ManagedServiceIdentity:1.1.0; CommandName: Get-AzUserAssignedIdentity; PSVersion: 7.3.2; IsSuccess: True; Duration: 00:00:01.6614696
Location      Name                     ResourceGroupName
--------      ----                     -----------------
usgovvirginia umiName                  resourcegroup0

# We run dozens of other commands using DefaultProfile to set the context and only this command does not respect the passed context.

# This example is from Gov Cloud, but the same behavior can be observed on Public Cloud.

# Public Cloud Example

PS C:\Users\jreinmiller\Documents> $context2public

Name                                     Account                                    SubscriptionName                           Environment                               TenantId
----                                     -------                                    ----------------                           -----------                               --------
Public2      (f14fnnnn-nnnn-nnnn-nnnn-n… abcd@abcd.com                              Public2                                    AzureCloud                                0552nnnn-nnnn-nnnn-nnnn-nnnnnnnn9837


PS C:\Users\jreinmiller\Documents> get-azcontext

Name                                     Account                                    SubscriptionName                           Environment                               TenantId
----                                     -------                                    ----------------                           -----------                               --------
Public1    (2230nnnn-nnnn-nnnn-nnnn-nnn… abcd@abcd.com                              Public1                                    AzureCloud                                5ea0nnnn-nnnn-nnnn-nnnn-nnnnnnnn89d8
DEBUG: 14:34:39 - GetAzureRMContextCommand end processing.


PS C:\Users\jreinmiller\Documents> Get-AzUserAssignedIdentity `
>> -DefaultProfile $context2public `
>> -Name "umiName" `
>> -ResourceGroupName resourcegroup0 `
>> -SubscriptionId f14fnnnn-nnnn-nnnn-nnnn-nnnnnnnn6188
DEBUG: [CmdletBeginProcessing]: Starting command
DEBUG: CmdletBeginProcessing:
DEBUG: CmdletProcessRecordStart:
DEBUG: CmdletGetPipeline:
DEBUG: CmdletBeforeAPICall:
DEBUG: URLCreated: /subscriptions/f14fnnnn-nnnn-nnnn-nnnn-nnnnnnnn6188/resourceGroups/resourcegroup0/providers/Microsoft.ManagedIdentity/userAssignedIdentities/umiName?api-version=2022-01-31-preview
DEBUG: RequestCreated: /subscriptions/f14fnnnn-nnnn-nnnn-nnnn-nnnnnnnn6188/resourceGroups/resourcegroup0/providers/Microsoft.ManagedIdentity/userAssignedIdentities/umiName?api-version=2022-01-31-preview
DEBUG: HeaderParametersAdded:
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/f14fnnnn-nnnn-nnnn-nnnn-nnnnnnnn6188/resourceGroups/resourcegroup0/providers/Microsoft.ManagedIdentity/userAssignedIdentities/umiName?api-version=2022-01-31-preview

Headers:
x-ms-unique-id                : 2
x-ms-client-request-id        : 58e3d6fd-nnnn-nnnn-nnnn-6e4baf2ad935
CommandName                   : Get-AzUserAssignedIdentity
FullCommandName               : Get-AzUserAssignedIdentity_Get
ParameterSetName              : __AllParameterSets
User-Agent                    : AzurePowershell/v9.4.0,PSVersion/v7.3.2,Az.ManagedServiceIdentity/1.1.0

Body:



DEBUG: BeforeCall:
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Unauthorized

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
WWW-Authenticate              : Bearer authorization_uri="https://login.windows.net/0552nnnn-nnnn-nnnn-nnnn-nnnnnnnn9837", error="invalid_token", error_description="The access token is from the wrong issuer. It must match the tenant associated with this subscription. Please use correct authority to get the token."
x-ms-failure-cause            : gateway
x-ms-request-id               : 2b1d125c-nnnn-nnnn-nnnn-8f31237fe68c
x-ms-correlation-request-id   : 2b1d125c-nnnn-nnnn-nnnn-8f31237fe68c
x-ms-routing-request-id       : WESTUS2:20230217T222900Z:2b1d125c-nnnn-nnnn-nnnn-8f31237fe68c
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Fri, 17 Feb 2023 22:28:59 GMT
Connection                    : close

Body:
{
  "error": {
    "code": "InvalidAuthenticationTokenTenant",
    "message": "The access token is from the wrong issuer 'https://sts.windows.net/5ea0nnnn-nnnn-nnnn-nnnn-nnnnnnnn89d8/'. It must match the tenant 'https://sts.windows.net/0552nnnn-nnnn-nnnn-nnnn-nnnnnnnn9837/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/0552nnnn-nnnn-nnnn-nnnn-nnnnnnnn9837' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later."
  }
}


DEBUG: ResponseCreated:
DEBUG: BeforeResponseDispatch:
WARNING: Get-AzUserAssignedIdentity_Get is not found. The most similar Azure PowerShell command is:
        Get-AzUserAssignedIdentity
Get-AzUserAssignedIdentity_Get: The access token is from the wrong issuer 'https://sts.windows.net/5ea0nnnn-nnnn-nnnn-nnnn-nnnnnnnn89d8/'. It must match the tenant 'https://sts.windows.net/0552nnnn-nnnn-nnnn-nnnn-nnnnnnnn9837/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/0552nnnn-nnnn-nnnn-nnnn-nnnnnnnn9837' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later.
DEBUG: [Finally]: Getting exception 'Microsoft.Azure.Commands.Common.Exceptions.AzPSCloudException: InternalException' from response
DEBUG: Finally:
DEBUG: CmdletAfterAPICall:
DEBUG: [CmdletProcessRecordAsyncEnd]: Finish HTTP process
DEBUG: CmdletProcessRecordAsyncEnd:
DEBUG: CmdletProcessRecordEnd:
DEBUG: AzureQoSEvent: Module: Az.ManagedServiceIdentity:1.1.0; CommandName: Get-AzUserAssignedIdentity; PSVersion: 7.3.2; IsSuccess: False; Duration: 00:00:00.3796766; Exception: InternalException;

# Have observed this behavior with both Service Principal and User Logins.
```

### Environment data

```PowerShell
PS C:\Users\jreinmiller\Documents> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
PS C:\Users\jreinmiller\Documents> get-module az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.10.2                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     1.1.0                 Az.ManagedServiceIdentity           {Get-AzFederatedIdentityCredentials, Get-AzSystemAssignedIdentity, Get-AzUserAssignedIdentity, Get-AzUserAssignedIdentityAssociatedResource…}
Script     6.3.1                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
```

### Error output

```PowerShell
DEBUG: 14:45:34 - ResolveError begin processing with ParameterSet 'LastErrorParameterSet'.
DEBUG: 14:45:34 - using account id '8f29nnnn-nnnn-nnnn-nnnn-nnnnnnnn639b'...
DEBUG: 14:45:34 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 68

Message        : [InvalidAuthenticationTokenTenant] : The access token is from the wrong issuer 'https://sts.windows.net/b96dnnnn-nnnn-nnnn-nnnn-nnnnnnnnec99/'. It must match the tenant
                 'https://sts.windows.net/e37annnn-nnnn-nnnn-nnnn-nnnnnnnn2d3f/' associated with this subscription. Please use the authority (URL)
                 'https://login.microsoftonline.us/e37annnn-nnnn-nnnn-nnnn-nnnnnnnn2d3f' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but
                 information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later.
StackTrace     :
Exception      : System.Exception
InvocationInfo : {Get-AzUserAssignedIdentity_Get}
Line           : Get-AzUserAssignedIdentity `

Position       : At line:1 char:1
                 + Get-AzUserAssignedIdentity `
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 68


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.

DEBUG: 14:45:34 - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
DEBUG: AzureQoSEvent: Module: Az.Accounts:2.10.2; CommandName: Resolve-AzError; PSVersion: 7.3.2; IsSuccess: True; Duration: 00:00:00.1177423
DEBUG: 14:45:34 - ResolveError end processing.
```

**Comment by isra-fel** [comment] 2023-02-20 07:06
Hi @jreinmilleratmosera thanks for reporting!
We realized that "-DefaultProfile" does not work for some cmdlets. We are investigating.
At the meantime, you could use `Set-AzContext` as a work-around:

```powershell
# After signing in
Set-AzContext -SubscriptionName "sub 1"
# Run cmdlets against sub 1
Set-AzContext -SubscriptionName "sub 2"
# Run cmdlets against sub 2
```

**Comment by dolauli** [comment] 2023-04-26 08:59
In next release, if cmdlets are executed with `-defaultprofile`, we will print a warning message to tell users it is not working.
The root cause of the issue is it is not supported by autorest.powershell, and the feature for autorest.powershell is tracked in https://github.com/Azure/autorest.powershell/issues/1143.

**Comment by dolauli** [comment] 2023-04-26 09:04
Close the issue considering

1. Workaround has been provided
2. Issue root cause is in autorest.powershell and is tracked in autorest.powershell repo.

**Closed by dolauli** 2023-04-26 09:04 UTC
Labels: Azure PS Team, bug, customer-reported
