### ISSUE TITLE
Could not load file or assembly 'Microsoft.Identity.Client.Extensions.Msal, Version=2.16.2.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'. The system cannot find the file specified. 

### ISSUE THREAD

**Issue by slavizh** [Azure/azure-powershell#13423] opened 2020-11-05 11:44 UTC
## Description
Cannot load Az.Accounts 2.1.2 on Ubuntu 18.04 PS 7.1 RC2.

## Steps to reproduce

```powershell
PS /mnt/c/Users/stas> Import-Module -Name Az.Accounts -RequiredVersion 2.1.2
Import-Module: /home/stan/.local/share/powershell/Modules/Az.Accounts/2.1.2/Az.Accounts.psm1:103
Line |
 103 |  Import-Module (Join-Path -Path $PSScriptRoot -ChildPath Microsoft.Azu …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not load file or assembly 'Microsoft.Identity.Client.Extensions.Msal, Version=2.16.2.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'. The system cannot find the file specified.

PS /mnt/c/Users/stas> get-error

Exception             :
    Type       : System.IO.FileNotFoundException
    Message    : Could not load file or assembly 'Microsoft.Identity.Client.Extensions.Msal, Version=2.16.2.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'. The system cannot find the file specified.

    FileName   : Microsoft.Identity.Client.Extensions.Msal, Version=2.16.2.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae
    TargetSite :
        Name          : SupportCachePersistence
        DeclaringType : Microsoft.Azure.Commands.Common.Authentication.SharedTokenCacheProvider
        MemberType    : Method
        Module        : Microsoft.Azure.PowerShell.Authentication.dll
    StackTrace :
   at Microsoft.Azure.Commands.Common.Authentication.SharedTokenCacheProvider.SupportCachePersistence(String& message)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.OnImport()
   at System.Management.Automation.Runspaces.PSSnapInHelpers.ExecuteModuleInitializer(Assembly assembly, IEnumerable`1 assemblyTypes) in /PowerShell/src/System.Management.Automation/engine/InitialSessionState
.cs:line 5432
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzeModuleAssemblyWithReflection(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, String helpFile, Dictionary
`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers) in /PowerShell/src/System.Management.Automation/engine/InitialSessionState.cs:line 5209
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Dictionary`2& cmdlets, Dictionary`2& al
iases, Dictionary`2& providers, String& helpFile) in /PowerShell/src/System.Management.Automation/engine/InitialSessionState.cs:line 5154
   at System.Management.Automation.Runspaces.InitialSessionState.ImportCmdletsFromAssembly(Assembly assembly, PSModuleInfo module) in /PowerShell/src/System.Management.Automation/engine/InitialSessionState.cs
:line 4058
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(PSModuleInfo parentModule, Boolean trySnapInName, String moduleName, String fileName, Assembly assemblyToLoad, String moduleBase, SessionS
tate ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, String prefix, Boolean loadTypes, Boolean loadFormats, Boolean& found, String shortModuleName, Boolean disableFormatUpdat
es) in /PowerShell/src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs:line 6700
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(Boolean trySnapInName, String moduleName, String fileName, Assembly assemblyToLoad, String moduleBase, SessionState ss, ImportModuleOption
s options, ManifestProcessingFlags manifestProcessingFlags, String prefix, Boolean loadTypes, Boolean loadFormats, Boolean& found) in /PowerShell/src/System.Management.Automation/engine/Modules/ModuleCmdletBa
se.cs:line 6518
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object privateData, ImportModuleOptions& options,
 ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound) in /PowerShell/src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs:line 5875
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(String fileName, String moduleBase, String prefix, SessionState ss, ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlag
s, Boolean& found) in /PowerShell/src/System.Management.Automation/engine/Modules/ModuleCmdletBase.cs:line 5529
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions importModuleOptions, String name) in /PowerShell/src/System.Management.Automation/engine/Modules/ImportM
oduleCommand.cs:line 706
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName_WithTelemetry(ImportModuleOptions importModuleOptions, String name) in /PowerShell/src/System.Management.Automation/engine/M
odules/ImportModuleCommand.cs:line 596
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord() in /PowerShell/src/System.Management.Automation/engine/Modules/ImportModuleCommand.cs:line 1862
   at System.Management.Automation.Cmdlet.DoProcessRecord() in /PowerShell/src/System.Management.Automation/engine/cmdlet.cs:line 173
   at System.Management.Automation.CommandProcessor.ProcessRecord() in /PowerShell/src/System.Management.Automation/engine/CommandProcessor.cs:line 388
    Source     : Microsoft.Azure.PowerShell.Authentication
    HResult    : -2147024894
CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand
InvocationInfo        :
    MyCommand        : Import-Module
    ScriptLineNumber : 103
    OffsetInLine     : 1
    HistoryId        : 18
    ScriptName       : /home/stan/.local/share/powershell/Modules/Az.Accounts/2.1.2/Az.Accounts.psm1
    Line             : Import-Module (Join-Path -Path $PSScriptRoot -ChildPath Microsoft.Azure.PowerShell.Cmdlets.Accounts.dll)

    PositionMessage  : At /home/stan/.local/share/powershell/Modules/Az.Accounts/2.1.2/Az.Accounts.psm1:103 char:1
                       + Import-Module (Join-Path -Path $PSScriptRoot -ChildPath Microsoft.Azu …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : /home/stan/.local/share/powershell/Modules/Az.Accounts/2.1.2
    PSCommandPath    : /home/stan/.local/share/powershell/Modules/Az.Accounts/2.1.2/Az.Accounts.psm1
    InvocationName   : Import-Module
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, /home/stan/.local/share/powershell/Modules/Az.Accounts/2.1.2/Az.Accounts.psm1: line 103
                        at <ScriptBlock>, <No file>: line 1

```

## Environment data

```
PS /mnt/c/Users/stas> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.0-rc.2
PSEdition                      Core
GitCommitId                    7.1.0-rc.2
OS                             Linux 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```powershell


```

## Debug output

```

```

## Error output

```

```

**Comment by erich-wang** [comment] 2020-11-06 03:45
@slavizh, thank you for reporting the issue. I just tried Az.Accounts 2.1.2 on Ubuntu 18.04 + PS 7.1 RC2, but could not reproduce the issue.
Could you please share more info:
1. Please share loaded assemblies before and after running `Import-Module`
```powershell
[System.AppDomain]::CurrentDomain.GetAssemblies()
```
2. Please share loaded modules before and after running `Import-Module`
```powershell
Get-Module
```

**Comment by slavizh** [comment] 2020-11-06 08:58
Ok I figure out why you cannot reproduce it. Initially when I have tested it I thought that was not playing part but seems it does. That is the following command I execute first:

```
Import-Module -Name PartnerCenter -RequiredVersion 3.0.10
```

Currently when I try to import on PS 7.2 RC2 first Partner center 3.0.10 and then Az.Accounts 2.1.2 I get the above error. If I try to import first Az.Accounts 2.1.2 it works but then when I try to import  Partner center 3.0.10 it fails with the issue descried here: https://github.com/microsoft/Partner-Center-PowerShell/issues/335 . That issue is relevant even for PS7. These two modules have always some problems when there are new versions and you try to import them. Usually it is the PartnerCenter module that gets fixed but this time I am getting error from Az as well. I am not sure who should be fixed what in which module.

**Comment by slavizh** [comment] 2020-11-12 07:12
Just did a test and issue is present in PS 7.1 final release as well.

**Comment by dingmeng-xue** [comment] 2020-11-13 06:37
@slavizh , this is known limitation on dotnet core that it cannot load the same assembly with different versions. We'd like to get PartnerCenter further feedback and which assembly has the problem. We will keep eyes on it.

**Comment by slavizh** [comment] 2020-11-13 12:25
@dingmeng-xue ok, Does that means that PartnerCenter module support has to fix this on their module?

**Comment by dingmeng-xue** [comment] 2020-11-13 13:35
Yes, we hope PartnerCenter can finalize their module at the first. The issue should be due to one dependency of  Microsoft.Identity.Client.Extensions.Msal. One issue I can find is Az.Accounts is using Microsoft.Identity.Client 4.21.0.0 but PartnerCenter is using 4.8.1.0. Az.Accounts uses MSAL 2.16.2 but PartnerCenter is 2.6.0.

Ideally, this issue should be resolved by loading Az.Accounts before PartnerCenter. But current PartnerCetner needs to fix their assembly loading logic. If assembly with higher version is loaded, it should continue instead of throwing exception.

**Comment by erich-wang** [comment] 2020-11-13 14:22
One possible workaround for loading both PartnerCenter and Az.Accounts is to:
1. Comment out the following two dll in PartnerCenter.psd1
                         #'.\Microsoft.Identity.Client.dll', 
                         #'.\Microsoft.Identity.Client.Extensions.Msal.dll',
2. Import Az.Accounts first
3. Import PartnerCenter, it should work

As dingment mentioned, the possible solution is to ask PartnerCenter team to move the logic of loading  `.\Microsoft.Identity.Client.Extensions.Msal.dll` `.\Microsoft.Identity.Client.dll` out of RequiredAssemblies to PartnerCenter.psm1, could refer to https://www.powershellgallery.com/packages/Az.Accounts/2.1.2/Content/Az.Accounts.psm1

**Comment by slavizh** [comment] 2020-11-13 14:39
@erich-wang Thanks, the workaround I cannot implement as I am using this in pipeline so it won't be suitable for there but there is logged issue to Partner Center team, hopefully they will respond at some point as it seems their development resources are less than the Az ones.

**Comment by erich-wang** [comment] 2020-11-18 06:36
@slavizh , I'm closing this issue as it should be resolved by PartnerCenter team. Please feel free to reopen this issue or file new issue  if you have any concern, thanks.

**Closed by erich-wang** 2020-11-18 06:36 UTC
Labels: customer-reported, needs-triage, question
