### ISSUE TITLE
Create a feedback cmdlet similar to `az feedback`.

### ISSUE THREAD

**Issue by twitchax** [Azure/azure-powershell#3794] opened 2017-04-18 19:24 UTC
### Cmdlet(s)
N/A.

### PowerShell Version
N/A.

### Module Version
N/A.

### OS Version
N/A.

### Description
Four questions:
1. On a scale from 0 (lowest) to 10 (highest), how likely are you to recommend Azure PowerShell to a friend or colleague?
2. What does Azure PowerShell do well?
3. Where could Azure PowerShell improve?
4. If you would like to join our insiders program and receive tips, tricks, and early access to new features, let us know by leaving your email address (leave blank to skip)

Create new Application Insights event.

### Debug Output
N/A.

### Script/Steps for Reproduction
N/A.

**Comment by markcowl** [comment] 2017-05-01 16:52
Duplicate of #3873 closing

**Closed by markcowl** 2017-05-01 16:52 UTC
Labels: Team
