### ISSUE TITLE
Incorrect constant causes duplication of scope string for importing a blueprint

### ISSUE THREAD

**Issue by noopman** [Azure/azure-powershell#10838] opened 2020-01-06 12:46 UTC
In the file:
https://github.com/Azure/azure-powershell/blob/45a880a7abd05c3cefe707546d7147b6b20cc00f/src/Blueprint/Blueprint/Common/BlueprintConstants.cs
On line 22: public const string ManagementGroupScope = "/providers/Microsoft.Management/managementGroups/{0}";
This causes calls to Import-AzBlueprintWithArtifact to fail when the ManagementGroupId parameter is a management group id. Instead you have to use the management group name property (the name is a guid) to make this cmndlet work.

I cannot overview what to change exactly and the cosequences, but the parameter to the cmdlet should absolutely be the management group id and thus this constant string or the validation for it is incorrect.

**Comment by dingmeng-xue** [comment] 2020-01-07 11:32
Thanks for reporting. This issue requires Bluepint team's input.

**Comment by dingmeng-xue** [comment] 2020-01-07 11:33
Based on recorded test case, group id used by import is its name.

**Comment by noopman** [comment] 2020-01-07 11:46
Given a management group:
$managementGroup = Get-AzManagementGroup | Where-Object -Property DisplayName -eq $managementGroupName
This fails:
Import-AzBlueprintWithArtifact -ManagementGroupId $managementGroup.Id -InputPath '.\{redacted}' -Name '{redacted}'
This works:
Import-AzBlueprintWithArtifact -ManagementGroupId $managementGroup.Name -InputPath '.\{redacted}' -Name '{redacted}'

That proves this implementation is incorrect. The parameter naming is off and sets the wrong expectations for the caller.

The call would be correct if the parameter had a different name:
Import-AzBlueprintWithArtifact -ManagementGroupName $managementGroup.Name -InputPath '.\{redacted}' -Name '{redacted}'

**Comment by alex-frankel** [comment] 2020-02-07 05:20
You are right. The problem is that in the portal, what in portal the "Name" property is actually called ID, and there is a property displayName that is called "Name" in the portal.

It's a question of which is "more" right and which is the more common place to get those properties from. I will discuss this with the rest of the team — I want to better understand what the options are for changing this. It might be a breaking change.

**Comment by noopman** [comment] 2020-02-09 20:22
As I have understood the Name field was used for a generated guid in this case, which cannot be changed. This is fundamentally an incorrect implementation. For Azure contexts if an id is used it should be a property Id set by the system. A Name may have limitations and restrictions, and may or may not be possible to change after creation. But the name should never be set by the system.

**Comment by alex-frankel** [comment] 2020-02-10 18:34
Understood - I think you are correct that what we are using as Name is really more of an ID. Unfortunately, this is not a straightforward change to make.

Adding @rthorn17 as FYI

**Comment by noopman** [comment] 2020-02-11 15:24
I understand that. I have suggested you roll forward in a non-breaking manner.

1) Add an ID field and populate that with the value from Name.
2) Change the creation process to always create an ID and populate that to Name if no name is provided.
3) Add optional Name to the creation api.

Support both Management Group "Resource IDs" using the Id and the Name fields. Both need to work at the same time.

This way all existing MGs still work and people may create new ones with their own specified names.

4) Later make a breaking change for Name to be mandatory.

Something like that. Of course I would not have covered 100% of the ground here - there must be some more factors. This might be a good start.

What's the value of this change? It aligns much better with how Azure resources are named. The only thing that uses the ID is then Subscriptions and that's fair because it has always done that. What you get out of is the strangeness/strangemess of using a Name parameter which is a generated ID. That is just too weird.

Thanks for listening.

**Comment by alex-frankel** [comment] 2020-02-14 02:15
Lots of good suggestions here - thanks. We'll leave this issue open until the cmdlet can handle the full resourceId without failing. We're not likely to get to it soon, but want to keep track of the issue.

**Comment by apclouds** [comment] 2020-09-21 16:06
Hello @noopman just wanted to follow up on this issue. Thanks again for the great suggestions here, will provide an update here once this work gets scheduled.

**Comment by apclouds** [comment] 2020-10-23 02:42
@noopman out of curiosity, is there another scenario where you've needed this? Besides the Blueprint cmdlet.

**Comment by noopman** [comment] 2020-10-27 18:09
Hello! I'm afraid I don't understand. This issue was filed with a Blueprint cmdlet in mind specifically. Is there another scenario that you can think of here?

**Comment by apclouds** [comment] 2020-11-04 16:28
Sorry for the confusion, the question was around other scenarios/issues similar to this outside of the Blueprint cmdlet

**Comment by noopman** [comment] 2020-11-06 10:22
Okay, thanks! In that case I have not seen this same scenario yet outside this context.

**Comment by alex-frankel** [comment] 2020-11-16 16:21
As we are planning to migrate blueprint definitions to template specs, and because template specs are an RG-scoped resource instead of an MG-scoped resource, this is not something we are going to fix. If it any point, it becomes a blocking issue, let us know and we can revisit this decision.

Since the status as "won't fix" will not change, I'm going to close this issue.

**Closed by alex-frankel** 2020-11-16 16:21 UTC
Labels: Blueprint, Service Attention, customer-reported
