### ISSUE TITLE
Cannot import Az module on new profile

### ISSUE THREAD

**Issue by Strandfelt** [Azure/azure-powershell#8963] opened 2019-04-08 13:41 UTC
## Description
At work, we recently joined our workstations to Azure AD. This meant that I got a new account on my workstation. However, it seems that something in the Azure Powershell module is still pointing towards my old user profile - even after uninstalling both the Azure CLI and Azure Powershell.

My old local username was "xxx" and my new local username is "xxx.COMPANY"

## Steps to reproduce

```powershell
Import-Module Az
#Output:
#Import-Module : Could not acquire access to file 'C:\Users\xxx\.Azure\AzureRmContext.json' please try again in a few
#minutes.
#At C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\1.4.0\Az.Accounts.psm1:83 char:1
#+ Import-Module (Join-Path -Path $PSScriptRoot -ChildPath Microsoft.Azu ...
#+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#    + CategoryInfo          : NotSpecified: (:) [Import-Module], UnauthorizedAccessException
#    + FullyQualifiedErrorId : System.UnauthorizedAccessException,Microsoft.PowerShell.Commands.ImportModuleCommand

Connect-AzAccount
#Output
#Connect-AzAccount : The term 'Connect-AzAccount' is not recognized as the name of a cmdlet, function, script file, or
#operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
#again.
#At line:1 char:1
#+ Connect-AzAccount
#+ ~~~~~~~~~~~~~~~~~
#    + CategoryInfo          : ObjectNotFound: (Connect-AzAccount:String) [], CommandNotFoundException
#    + FullyQualifiedErrorId : CommandNotFoundException
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.17763.316
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.316
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

```powershell


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                                                                                                                       
---------- -------    ----                                ----------------                                                                                                                                       
Script     1.4.0      Az.Accounts                         {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave...}                                            
Script     1.0.1      Az.Aks                              {Get-AzAks, New-AzAks, Remove-AzAks, Import-AzAksCredential...}                                                                                        
Script     1.0.2      Az.AnalysisServices                 {Resume-AzAnalysisServicesServer, Suspend-AzAnalysisServicesServer, Get-AzAnalysisServicesServer, Remove-AzAnalysisServicesServer...}                  
Script     1.0.0      Az.ApiManagement                    {Add-AzApiManagementRegion, Get-AzApiManagementSsoToken, New-AzApiManagementCustomHostnameConfiguration, New-AzApiManagementSystemCertificate...}      
Script     1.0.0      Az.ApplicationInsights              {Get-AzApplicationInsights, New-AzApplicationInsights, Remove-AzApplicationInsights, Set-AzApplicationInsightsPricingPlan...}                          
Script     1.2.0      Az.Automation                       {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHybridWorkerGroup, Get-AzAutomationJobOutputRecord, Import-AzAutomationDscNodeConfiguration...} 
Script     1.0.0      Az.Batch                            {Remove-AzBatchAccount, Get-AzBatchAccount, Get-AzBatchAccountKeys, New-AzBatchAccount...}                                                             
Script     1.0.0      Az.Billing                          {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzEnrollmentAccount, Get-AzConsumptionBudget...}                                                       
Script     1.1.0      Az.Cdn                              {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-AzCdnProfile, Remove-AzCdnProfile...}                                                                   
Script     1.0.1      Az.CognitiveServices                {Get-AzCognitiveServicesAccount, Get-AzCognitiveServicesAccountKey, Get-AzCognitiveServicesAccountSkus, Get-AzCognitiveServicesAccountType...}         
Script     1.6.0      Az.Compute                          {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAvailabilitySet, Update-AzAvailabilitySet...}                                                  
Script     1.0.0      Az.ContainerInstance                {New-AzContainerGroup, Get-AzContainerGroup, Remove-AzContainerGroup, Get-AzContainerInstanceLog}                                                      
Script     1.0.1      Az.ContainerRegistry                {New-AzContainerRegistry, Get-AzContainerRegistry, Update-AzContainerRegistry, Remove-AzContainerRegistry...}                                          
Script     1.0.2      Az.DataFactory                      {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get-AzDataFactoryV2, Remove-AzDataFactoryV2...}                                                          
Script     1.0.0      Az.DataLakeAnalytics                {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeAnalyticsCatalogCredential, Remove-AzDataLakeAnalyticsCatalogCredential, Set-AzDataLakeAnalyticsCa...
Script     1.1.0      Az.DataLakeStore                    {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreFirewallRule, Set-AzDataLakeStoreTrustedIdProv...
Script     1.0.0      Az.DevTestLabs                      {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolicy, Get-AzDtlAutoStartPolicy, Get-AzDtlVMsPerLabPolicy...}                                    
Script     1.0.0      Az.Dns                              {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remove-AzDnsRecordSet, Set-AzDnsRecordSet...}                                                              
Script     1.1.0      Az.EventGrid                        {New-AzEventGridTopic, Get-AzEventGridTopic, Set-AzEventGridTopic, New-AzEventGridTopicKey...}                                                         
Script     1.0.1      Az.EventHub                         {New-AzEventHubNamespace, Get-AzEventHubNamespace, Set-AzEventHubNamespace, Remove-AzEventHubNamespace...}                                             
Script     1.0.0      Az.HDInsight                        {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefinition, Wait-AzHDInsightJob, New-AzHDInsightStreamingMapReduceJobDefinition...}                        
Script     1.0.2      Az.IotHub                           {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGroup, Get-AzIotHubConnectionString, Get-AzIotHubJob...}                                                 
Script     1.1.0      Az.KeyVault                         {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertificate, Stop-AzKeyVaultCertificateOperation, Get-AzKeyVaultCertificateOperation...}                  
Script     1.2.1      Az.LogicApp                         {Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccountAssembly, Get-AzIntegrationAccountBatchConfiguration, Get-AzIntegrationAccountCallbackUr...
Script     1.0.0      Az.MachineLearning                  {Move-AzMlCommitmentAssociation, Get-AzMlCommitmentAssociation, Get-AzMlCommitmentPlanUsageHistory, Remove-AzMlCommitmentPlan...}                      
Script     1.0.0      Az.MarketplaceOrdering              {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}                                                                                                       
Script     1.0.0      Az.Media                            {Sync-AzMediaServiceStorageKeys, Set-AzMediaServiceKey, Get-AzMediaServiceKeys, Get-AzMediaServiceNameAvailability...}                                 
Script     1.0.1      Az.Monitor                          {Get-AzMetricDefinition, Get-AzMetric, Remove-AzLogProfile, Get-AzLogProfile...}                                                                       
Script     1.6.0      Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Get-AzApplicationGatewayAuthenticationCertificate, New-AzApplicationGatewayAuthenticationCertifi...
Script     1.0.0      Az.NotificationHubs                 {Get-AzNotificationHub, Get-AzNotificationHubAuthorizationRules, Get-AzNotificationHubListKeys, Get-AzNotificationHubPNSCredentials...}                
Script     1.1.0      Az.OperationalInsights              {New-AzOperationalInsightsAzureActivityLogDataSource, New-AzOperationalInsightsCustomLogDataSource, Disable-AzOperationalInsightsLinuxCustomLogColle...
Script     1.0.0      Az.PolicyInsights                   {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPolicyStateSummary, Get-AzPolicyRemediation...}                                                           
Script     1.0.0      Az.PowerBIEmbedded                  {Remove-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollectionAccessKeys, Get-AzPowerBIWorkspace...}         
Script     1.2.0      Az.RecoveryServices                 {Get-AzRecoveryServicesBackupProperty, Get-AzRecoveryServicesVault, Get-AzRecoveryServicesVaultSettingsFile, New-AzRecoveryServicesVault...}           
Script     1.0.0      Az.RedisCache                       {Remove-AzRedisCachePatchSchedule, New-AzRedisCacheScheduleEntry, Get-AzRedisCachePatchSchedule, New-AzRedisCachePatchSchedule...}                     
Script     1.0.0      Az.Relay                            {New-AzRelayNamespace, Get-AzRelayNamespace, Set-AzRelayNamespace, Remove-AzRelayNamespace...}                                                         
Script     1.2.1      Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRoleAssignment, New-AzRoleAssignment...}                                                      
Script     1.0.0      Az.ServiceBus                       {New-AzServiceBusNamespace, Get-AzServiceBusNamespace, Set-AzServiceBusNamespace, Remove-AzServiceBusNamespace...}                                     
Script     1.0.1      Az.ServiceFabric                    {Add-AzServiceFabricApplicationCertificate, Add-AzServiceFabricClientCertificate, Add-AzServiceFabricClusterCertificate, Add-AzServiceFabricNode...}   
Script     1.0.2      Az.SignalR                          {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey, New-AzSignalRKey...}                                                                                  
Script     1.7.0      Az.Sql                              {Get-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabaseTransparentDataEncryptionActivity, Set-AzSqlDatabaseTransparentDataEncryption, Get-AzS...
Script     1.1.0      Az.Storage                          {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStorageAccount, New-AzStorageAccountKey...}                                                      
Script     1.0.0      Az.StreamAnalytics                  {Get-AzStreamAnalyticsFunction, Get-AzStreamAnalyticsDefaultFunctionDefinition, New-AzStreamAnalyticsFunction, Remove-AzStreamAnalyticsFunction...}    
Script     1.0.1      Az.TrafficManager                   {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove-AzTrafficManagerCustomHeaderFromEndpoint, Add-AzTrafficManagerCustomHeaderToProfile, Remove-AzTr...
Script     1.1.2      Az.Websites                         {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServicePlan, Remove-AzAppServicePlan...}                                                         



```

## Debug output

```
PS C:\WINDOWS\system32> $DebugPreference='Continue'
PS C:\WINDOWS\system32> Import-Module Az
PS C:\WINDOWS\system32> Connect-AzAccount
Connect-AzAccount : The term 'Connect-AzAccount' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ Connect-AzAccount
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Connect-AzAccount:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

```

**Comment by maddieclayton** [comment] 2019-04-08 21:16
@cormacpayne Hey Cormac, could you take a look at this issue and see if there is an easy way to reset where we look for the .azure folder?

**Comment by Strandfelt** [comment] 2019-04-08 21:25
It might be worth noting, that I copied over my `C:/Users/xxx` folder content into `C:/Users/xxx.COMPANY`.

As a temporary workaround, I have moved back my .Azure directory to the old location.

**Comment by cormacpayne** [comment] 2019-04-15 20:39
@Strandfelt Hey Andreas, just to confirm, on your machine you are now logging in as `xxx.COMPANY` rather than `xxx`, correct? We are using the path `Environment.SpecialFolders.UserProfile` as the directory to house this `.Azure` folder that the `AzureRmContext.json` file is then written to. It may be the case that your machine still thinks you're logged in as the `xxx` account and is trying to read from/write to the `.Azure` folder in that user's profile.

**Comment by Strandfelt** [comment] 2019-04-23 07:39
I login with my Azure AD-user xxx@COMPANY.com, yes. That user is mapped to the xxx.COMPANY folder in C:/Users.

**Comment by cormacpayne** [comment] 2019-05-09 17:58
@Strandfelt Sorry for the delayed response -- would you mind trying a few different things in your `xxx.COMPANY` account:

(1) In PowerShell, what is the value of `$env:USERPROFILE`? This value _should_ be `C:\Users\xxx.COMPANY`
(2) In PowerShell, what is the value of `[System.Environment]::GetFolderPath( [System.Environment+SpecialFolder]::UserProfile) ? This value _should_ be `C:\Users\xxx.COMPANY` as well
(3) Would you mind removing all existing `Az` modules that are on your machine and re-install with the latest versions? You can find where they are located by running `Get-Module -Name Az* -ListAvailable` and manually deleting the folders in the given path.

**Comment by Strandfelt** [comment] 2019-05-10 09:33
```
PS C:\WINDOWS\system32> $env:USERPROFILE
C:\Users\xxx.COMPANY
PS C:\WINDOWS\system32> [System.Environment]::GetFolderPath( [System.Environment+SpecialFolder]::UserProfile)
C:\Users\xxx.COMPANY
```

I deleted all modules and reinstalled them. Still, I get an error:
```
PS C:\WINDOWS\system32> Connect-AzAccount
Connect-AzAccount : The term 'Connect-AzAccount' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ Connect-AzAccount
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Connect-AzAccount:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

However, if I recreate my C:\Users\xxx folder containing the .azure-folder, it works fine.

**Comment by markcowl** [comment] 2019-05-23 20:32
@Strandfelt What is the error when you run Import-Module Az.Accounts?

**Comment by Strandfelt** [comment] 2019-05-24 07:45
> @Strandfelt What is the error when you run Import-Module Az.Accounts?

```
Import-Module : Could not acquire access to file 'C:\Users\xxx\.Azure\AzureRmContext.json' please try again in a few minutes.
At C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\1.5.2\Az.Accounts.psm1:83 char:1
+ Import-Module (Join-Path -Path $PSScriptRoot -ChildPath Microsoft.Azu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], UnauthorizedAccessException
    + FullyQualifiedErrorId : System.UnauthorizedAccessException,Microsoft.PowerShell.Commands.ImportModuleCommand
```

**Comment by markcowl** [comment] 2019-08-03 01:34
@Strandfelt The simplest workaround to this si to turn off context autosave.  To do this, you can set the environment variable `"AzContextAutoSave"` to 'false'

**Comment by msJinLei** [comment] 2019-10-15 07:00
@Strandfelt I am not sure whether your problem has already been solved. A workaround for the issue is just to delete "C:\Users\xxx\.Azure\AzureRmContextSettings.json".

**Comment by erich-wang** [comment] 2019-11-06 17:27
Based on the statement from user:
> that I copied over my C:/Users/xxx folder content into C:/Users/xxx.COMPANY when setting up the new profile. 
IMO, the error is expected because user copied the AzureRMContextSettings.json from old dir, but didn't modify ContextDirectory in that file, which result in Azure PowerShell to read context file from old ContextDirectory. The correct way to fix it is to delete AzureRMContextSetttings.json or modify its ContextDirectory and CacheDirectory in AzureRMContextSetttings.json.

**Comment by msJinLei** [comment] 2020-01-21 06:21
Fixed by https://github.com/Azure/azure-powershell/pull/10355

**Closed by msJinLei** 2020-01-21 06:21 UTC
Labels: Azure PS Team, Investigate :mag:, P0, customer-reported
