### ISSUE TITLE
Consider having Start-AzStorageFileCopy return something to invoke Get-AzStorageFileCopyState

### ISSUE THREAD

**Issue by paulomorgado** [Azure/azure-powershell#11788] opened 2020-05-04 18:08 UTC
## Description of the new feature

Consider having `Start-AzStorageFileCopy` return something to invoke `Get-AzStorageFileCopyState`.

The documentation for `Get-AzStorageFileCopyState` doesn't mention what state should be checked. Is it the source or the destionation?

**Comment by markcowl** [comment] 2020-05-04 18:31
@paulomorgado  Thanks for your feature suggestion.  We will get back to you shortly with a detailed reponse.

**Comment by blueww** [comment] 2020-05-06 03:30
@paulomorgado 

For 'Get-AzStorageFileCopyState', is should run on the dest blob. 
Following example shows how to get the copy status from output of Start-AzStorageFileCopy

```powershell
$b = Start-AzStorageBlobCopy  -SrcContainer $containerName -SrcBlob test.txt -DestContainer $containerName -DestBlob testcopy.txt -Context $ctx 

$b | Get-AzStorageBlobCopyState
```

**Comment by paulomorgado** [comment] 2020-05-06 09:22
@blueww,

> `# Start-AzStorageBlobCopy will output the destination blob object`

Not according to [the docs](https://docs.microsoft.com/powershell/module/az.storage/start-azstoragefilecopy#outputs):

>## Outputs
> Void

And that would be a great example to add to `Get-AzStorageBlobCopyState` docs.

**Comment by blueww** [comment] 2020-05-07 03:09
@paulomorgado 
It's a good idea to add the example to help, I have updated  `Get-AzStorageBlobCopyState` help file, by 1. add description to indicate Get copy status should run on destination blob; 2. Add example for pipeline `Start-AzStorageBlobCopy` to ` Get-AzStorageBlobCopyState` in https://github.com/Azure/azure-powershell/pull/11815. The help update will be release in the next PSH rlease.

BTW, The help link you give is not for "Start-AzStorageBlobCopy", the right link is : https://docs.microsoft.com/en-us/powershell/module/az.storage/start-azstorageblobcopy?view=azps-3.8.0#outputs, You can see the output type is listed in the doc as "AzureStorageBlob".  Please note, the output section if for output type.

Let me know if you have any other concern to close this issue.

**Comment by paulomorgado** [comment] 2020-05-07 07:51
@Blueww,

Other than copying from your comments without reading (sorry about that), I never mentioned BlobCopy. This issues has always been about FileCopy.

**Closed** 2020-05-08 03:27 UTC
Labels: Storage, feature-request

**Comment by blueww** [comment] 2020-05-08 03:31
@paulomorgado
The PR to update the output object of Start-AzStorageFileCopy's help docs is merged.
So the issue is closed.

Feel free to contact us again if you have any other question, or need any other assistance.
