### ISSUE TITLE
Add-AzVhd : This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms

### ISSUE THREAD

**Issue by athlon55** [Azure/azure-powershell#10253] opened 2019-10-11 09:27 UTC
## Description
When using the command Az-AddVHD on a Windows enabled FIPS server, I have this error message

Add-AzVhd : Exception has been thrown by the target of an invocation.
At line:1 char:1
+ Add-AzVhd -ResourceGroupName xxxxx -Destination "https: ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Add-AzVhd], TargetInvocationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.StorageServices.AddAzureVhdCommand

As a workaround, I can now use the set-AzStorageBlobContent as it was recently corrected in https://github.com/Azure/azure-powershell/issues/9908

## Steps to reproduce

Run the command Add-AzVHD on a Windows FIPS enabled machine.

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.17763.592
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.592
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

I'm using the latest stable Az.Compute module
```powershell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.6.0      Az.Compute                          {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAvailabilitySet, Update-AzAvailabilitySet...}
```

## Debug output

```
DEBUG: AzureQoSEvent: CommandName - Add-AzVhd; IsSuccess - False; Duration - 00:00:02.5217125; Exception -
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. --->
System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic
algorithms.
at System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
--- End of inner exception stack trace ---
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters,
CultureInfo culture)
at System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
at System.Security.Cryptography.MD5.Create()
at Microsoft.WindowsAzure.Commands.Sync.Upload.BlobCreatorBase.GetMutexName(Uri destinationBlobUri)
at Microsoft.WindowsAzure.Commands.Sync.Upload.BlobCreatorBase.AcquireSingleInstanceMutex(Uri destinationBlobUri)
at Microsoft.WindowsAzure.Commands.Sync.Upload.BlobCreatorBase.Create()
at Microsoft.Azure.Commands.Compute.Models.VhdUploaderModel.Upload(UploadParameters uploadParameters)
at Microsoft.Azure.Commands.Compute.StorageServices.AddAzureVhdCommand.ExecuteCmdlet()
at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 09:12:04 - AddAzureVhdCommand end processing.
```

## Error output

```
Message        : Exception has been thrown by the target of an invocation.
StackTrace     :    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
                    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
                    at System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
                    at System.Security.Cryptography.MD5.Create()
                    at Microsoft.WindowsAzure.Commands.Sync.Upload.BlobCreatorBase.GetMutexName(Uri destinationBlobUri)
                    at Microsoft.WindowsAzure.Commands.Sync.Upload.BlobCreatorBase.AcquireSingleInstanceMutex(Uri destinationBlobUri)
                    at Microsoft.WindowsAzure.Commands.Sync.Upload.BlobCreatorBase.Create()
                    at Microsoft.Azure.Commands.Compute.Models.VhdUploaderModel.Upload(UploadParameters uploadParameters)
                    at Microsoft.Azure.Commands.Compute.StorageServices.AddAzureVhdCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Reflection.TargetInvocationException
InvocationInfo : {Add-AzVhd}
Line           : Add-AzVhd -ResourceGroupName XXXX -Destination "https://XXXX/test.vhd" -LocalFilePath test.vhd
Position       : At line:1 char:1
                 + Add-AzVhd -ResourceGroupName XXXX -Destination "https: ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 7

Message        : This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
StackTrace     :    at System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
Exception      : System.InvalidOperationException
InvocationInfo : {Add-AzVhd}
Line           : Add-AzVhd -ResourceGroupName XXXX -Destination "https://XXXX/test.vhd" -LocalFilePath test.vhd
Position       : At line:1 char:1
                 + Add-AzVhd -ResourceGroupName XXXX -Destination "https: ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 7

```

**Comment by Drewm3** [comment] 2019-10-14 22:25
@hyonholee, could you look into this to see if this issue is due to the crypto package that the Add-AzVhd cmdlet is using directly or if this is an issue with a library that is being used by the Add-AzVhd cmdlet. In either case we should see if there is an alternate crypto algorithm that can be used that is FIPS compliant.

**Comment by Drewm3** [comment] 2019-11-20 01:25
This was incorrectly closed.

**Comment by mikedzikowski** [comment] 2020-01-17 13:42
My customer is seeing this same issue in Microsoft Azure Government.

**Comment by danielli90** [comment] 2020-02-11 17:08
[@markcowl]"As noted in the bug below, this has actually been fixed for Set-AzStorageBlobContent: See: https://github.com/Azure/azure-powershell/pull/5746 )and https://github.com/Azure/azure-powershell/search?q=fipsEnabled&unscoped_q=fipsEnabled" 

[Wei Wei] "Please use Az.Storage 1.7.0 and later for Set-AzStorageBlob/FileContent, we have fixed some issue of FIPS for them in 1.7.0."

**Comment by markcowl** [comment] 2020-02-21 20:28
@Drewm3 @hyonholee Can you respond with whether there are plans to fix this, similar to the analogous fix in Set-AzStorageBlobContent?

**Comment by Drewm3** [comment] 2020-05-21 16:37
Updating to the new owner of this cmdlet.

**Comment by Drewm3** [comment] 2020-06-25 05:24
The team is reviewing the future of the Add-AzVhd cmdlet. Recently there has been more investment in the tool AzCopy, and this may be the longer term recommended tool to use to upload VHDs to Azure. 

@mikedzikowski, could you ask your customer to see if the instructions [here](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/disks-upload-vhd-to-managed-disk-powershell) work for them to upload the VHD?

**Comment by Vaibhav-Agar** [comment] 2020-11-13 19:50
Hi @markcowl, @athlon55,
We do have this in our backlog for Add-AzVhd but we don't have an ETA yet. So, the recommendation is to continue to use the workaround for now. Closing this issue. Please reopen if there are any other questions.

**Comment by Vaibhav-Agar** [comment] 2021-05-13 21:28
Hi @grizzlytheodore, as discussed offline, I didn't try to reproduce it.  @athlon55, this was opened a while back but in case if this is still an issue, can you share any more details that might help in reproducing the issue such as the Windows version?

**Comment by grizzlytheodore** [comment] 2021-05-20 17:47
@athlon55 could you share any information that can help me reproduce this?

**Comment by Vaibhav-Agar** [comment] 2021-06-03 15:10
@grizzlytheodore what is the next step here given that we have not heard back from @athlon55 ?

**Comment by grizzlytheodore** [comment] 2021-09-02 02:51
@athlon55  @Vaibhav-Agar  @markcowl @danielli90 @mikedzikowski 
Hello, everyone. This issue has been open for a while, but after troubleshooting I found that the issue only exists when using PowerShell 5.  
Az.PowerShell is supposed to be used with PowerShell 7 and in PowerShell 7, this issue does not show. 
Please guide your customers to download the latest PowerShell: https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell?view=powershell-7.1

**Closed** 2021-09-02 02:52 UTC
Labels: feature-request, Compute - Images, Service Attention, customer-reported
