### ISSUE TITLE
'DontShow' property specified was not found

### ISSUE THREAD

**Issue by craig-wagner** [Azure/azure-powershell#1344] opened 2015-11-24 15:26 UTC
I just used the Web Platform Installer to install "Microsoft Azure PowerShell - November 2015" (v1.0.1) on Windows 7. I went to the start menu and clicked "Microsoft Azure PowerShell" to start a session. The first thing I did was type "get-help azure". I got a list of commandlets up to "New-AzureStorSimpleStorageAcco..." at which point the list was terminated with the following error.

get-help : 'DontShow' property specified was not found.
At line:1 char:1
- get-help azure
- ~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Get-Help], CustomAttributeFormatException
  - FullyQualifiedErrorId : System.Reflection.CustomAttributeFormatException,Microsoft.PowerShell.Commands.GetHelpCommand

I used to have v0.9 installed but I checked "Programs and Features" and the only version listed as being installed is the November 2015 one identified above.

**Comment by pcgeek86** [comment] 2015-11-27 18:18
@hovsepm I'm not familiar with the `DontShow` attribute parameter on the `[Parameter()]` attribute. Is this a valid parameter?

https://github.com/Azure/azure-powershell/blob/f2674a6648b6fb25a3de337044a77d226ae9af2d/src/ServiceManagement/StorSimple/Commands.StorSimple/Cmdlets/VirtualDevice/NewAzureStorSimpleVirtualDeviceCommand.cs#L45

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by markcowl** [comment] 2015-11-30 21:09
@pcgeek86 @craig-wagner See:  http://www.powershellmagazine.com/2013/07/29/pstip-hiding-parameters-from-tab-completion/

This was added in PowerShell 4.0, which is why it would only show up in windows 7.  We should make sure this attribute is removed until we officially require wmf 4 OR wmf 5

**Comment by markcowl** [comment] 2016-05-03 01:20
### Root Cause
Some cmdlets have 'Dont'Show' as a property in the parameter attribute declarasion

### Proposed Solution
- Check for this property in static analysis and reporta P1 (build break) issue if found
- Remove Dont'sSHow from cmdlets that have it through filling issues with their owners

### Cose (Work Units): 1

**Comment by markcowl** [comment] 2017-05-15 18:53
Noa ction on this for quite a while without complaints.  Closing.  If this issue is hit again, please reopen

**Closed by markcowl** 2017-05-15 18:53 UTC
Labels: P2, Team
