### ISSUE TITLE
[PlaceHolder]: Create Common library for Storage Data Plane

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#3434] opened 2017-01-26 20:32 UTC
### Description

Placeholder to be fleshed out after the associated prototyping issue: #3430

**Comment by markcowl** [comment] 2017-04-20 20:39
closing as absolete

**Comment by cormacpayne** [comment] 2017-10-24 22:15
Duplicate of https://github.com/Azure/azure-powershell/issues/3430

**Closed** 2017-10-24 22:14 UTC
Labels: Azure PS Team, Core CLR, Planning
