### ISSUE TITLE
Az.Compute:  "Get-AzCapacityReservation" not returning VirtualMachinesAssociated

### ISSUE THREAD

**Issue by Alex-wdy** [Azure/azure-powershell#24599] opened 2024-04-10 05:42 UTC
### Description

Customer complains that when using PowerShell command "Get-AzCapacityReservation" to list the VirtualMachinesAssociated it's responding with {} and listing the associated virtual Machines.
 
We have tested with CLI "az capacity reservation group show" command and it's working fine.
 
The Powershell command is NOT working from vscode or from Azure Cloud shell.

![image](https://github.com/Azure/azure-powershell/assets/108926104/8ae05d84-1078-4faf-912b-4db38eca53ec)

 
Here's some screenshots that show the differences between PS and CLI commands:
 
PowerShell
![image](https://github.com/Azure/azure-powershell/assets/108926104/a847ba90-4d1e-4834-b731-c1d9a74c7f40)

CLI:
![image](https://github.com/Azure/azure-powershell/assets/108926104/edfa07bf-7050-4a04-b052-387a81c4167e)

with Invoke-AzRestMethod, we get the virtualMachinesAssociated successfully (I used API version '2023-09-01')
 
Now for Get-AzCapacityReservation with -Debug parameter, I see it uses the same API version. I am attaching the outputs for reference. 
 

Here's the Get-AzCapacityReservation output without  -Debug , as you can see VirtualMachinesAssociated is always an empty array {}
![image](https://github.com/Azure/azure-powershell/assets/108926104/a2be608f-0c60-429c-a245-8ad1192caaf0)

### Issue script & Debug output

```PowerShell
Name                      : Standard_D16ds_v5_1
Type                      : Microsoft.Compute/capacityReservationGroups/capacityReservations
Tags                      : {[global-app, Managed Public IaaS Support Module], [global-appserviceid, a09d9c3a1bec8994e3e66574604bcbbf], [global-cbp, A01908], [global-dataclass, Internal]…}
Location                  : westeurope
Id                        : /subscriptions/7b0ee8af-1494-4621-b118-84a3043b096d/resourceGroups/Z-AES-SUPPORT-PR01-EW1-01/providers/Microsoft.Compute/capacityReservationGroups/zaessupportpr01ew1crg90/capacityReservations/Standard_D16ds_v5_1
VirtualMachinesAssociated : {}
InstanceView              : 
Zones                     : {1}
ReservationId             : 06a0dee7-8bd8-4689-a7e3-27620f3af51f
ProvisioningState         : Succeeded
ProvisioningTime          : 5/9/2023 2:03:10 PM
Sku                       : Microsoft.Azure.Management.Compute.Models.Sku

Name                      : Standard_D16ds_v5_2
Type                      : Microsoft.Compute/capacityReservationGroups/capacityReservations
Tags                      : {[global-app, Managed Public IaaS Support Module], [global-appserviceid, a09d9c3a1bec8994e3e66574604bcbbf], [global-cbp, A01908], [global-dataclass, Internal]…}
Location                  : westeurope
Id                        : /subscriptions/7b0ee8af-1494-4621-b118-84a3043b096d/resourceGroups/Z-AES-SUPPORT-PR01-EW1-01/providers/Microsoft.Compute/capacityReservationGroups/zaessupportpr01ew1crg90/capacityReservations/Standard_D16ds_v5_2
VirtualMachinesAssociated : {}
InstanceView              : 
Zones                     : {2}
ReservationId             : ea5f0dd5-b2fa-4990-bec7-a2def7ab2796
ProvisioningState         : Succeeded
ProvisioningTime          : 5/9/2023 2:03:09 PM
Sku                       : Microsoft.Azure.Management.Compute.Models.Sku

Name                      : Standard_D2ds_v5_1
Type                      : Microsoft.Compute/capacityReservationGroups/capacityReservations
Tags                      : {[global-app, Managed Public IaaS Support Module], [global-appserviceid, a09d9c3a1bec8994e3e66574604bcbbf], [global-cbp, A01908], [global-dataclass, Internal]…}
Location                  : westeurope
Id                        : /subscriptions/7b0ee8af-1494-4621-b118-84a3043b096d/resourceGroups/Z-AES-SUPPORT-PR01-EW1-01/providers/Microsoft.Compute/capacityReservationGroups/zaessupportpr01ew1crg90/capacityReservations/Standard_D2ds_v5_1
VirtualMachinesAssociated : {}
InstanceView              : 
Zones                     : {1}
ReservationId             : 5fdfea45-2764-4744-856b-7b8ccc4ec9b9
ProvisioningState         : Succeeded
ProvisioningTime          : 4/2/2024 8:02:53 AM
Sku                       : Microsoft.Azure.Management.Compute.Models.Sku
```

### Environment data

```PowerShell
API version
'2023-09-01'
```

### Module versions

```PowerShell
Az.compute
```

**Comment by Alex-wdy** [comment] 2024-04-15 09:02
let you know that if we use “AzCapacityReservationGroup” we’d be able to see the VirtualMachineAssociated but it does not work with “Get-AzCapacityReservationGroup”.

**Comment by TravisCragg-MSFT** [comment] 2024-04-18 19:10
@Alex-wdy Can you make sure your [Azure PowerShell modules are up-to-date](https://learn.microsoft.com/en-us/powershell/azure/install-azps-windows?view=azps-11.5.0&tabs=powershell&pivots=windows-psgallery#update-the-az-powershell-module)? We are working to Reproduce this issue .

**Comment by TravisCragg-MSFT** [comment] 2024-04-18 19:54
@Alex-wdy We are unable to reproduce this issue. Please update your PowerShell modules, mkae sure your capacity reservation has VMs attached and try this again.

**Comment by TravisCragg-MSFT** [comment] 2024-05-30 19:32
We are closing this issue. If you would like to continue, please tag me in your response.

**Closed by TravisCragg-MSFT** 2024-05-30 19:32 UTC
Labels: Compute - VM, Service Attention, bug
