### ISSUE TITLE
TemplateParameterObject Serializes Hashtables & PSCustomObject Incorrectly

### ISSUE THREAD

**Issue by abombss** [Azure/azure-powershell#1528] opened 2015-12-21 06:00 UTC
> Name | Version
> AzureRM.Resources | 1.0.1  

If a template takes a parameter of type=object there is no way to send that object via TemplateParameterObject or through dynamic powershell parameters.

Typically in powershell there are two common ways to represent custom objects and have them serialized and deserialized to and from json.  That is using standard powershell hashtables or using pscustomobject.

Using either of these formats when calling New-AzureRmResourceGroupDeployment fails to properly serialize the parameters.  So currently, there is no way through the cmdlets to invoke a template that has parameters of type object.

Template

``` json
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "storageSettings": {
            "type": "object"
        }
    },
    "variables": {
        "storageSettings": "[parameters('storageSettings')]",
        "name": "[variables('storageSettings').name]",
        "resourceGroup": "[variables('storageSettings').resourceGroup]",
        "resourceId": "[resourceId(variables('resourceGroup'), 'Microsoft.Storage/storageAccounts', variables('name'))]"
    },
    "resources": [],
    "outputs": {
        "storageAccountInfo": {
            "value": "[reference(variables('resourceId'), providers('Microsoft.Storage', 'storageAccounts').apiVersions[0])]",
            "type": "object"
        }
    }
}
```

``` powershell
New-AzureRmResourceGroupDeployment -TemplateParameterObject @{
  storageSettings=@{
    name='foo'
    resourceGroup='bar'
  }
}
```

The above command serializes the parameters like this in the request which is invalid, using a dynamic parameter has the same effect.

``` json
"parameters": {
      "storageSettings": {
        "resourceGroup": {
          "value": "bar"
        },
        "name": {
          "value": "foo"
        }
      }
    },

```

Trying to use a powershell custom object actually serializes the object to an xml like string.  I assume its the default output of serializing an pscustomobject with json.net.

``` powershell
New-AzureRmResourceGroupDeployment -storageSettings ([pscustomobject]@{
    name='foo'
    resourceGroup='bar'
  })
```

``` json
    "parameters": {
      "storageSettings": {
        "value": {
          "CliXml": "<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\">\r\n  <Obj RefId=\"0\">\r\n    <TN RefId=\"0\">\r\n      <T>System.Management.Automation.PSCustomObject</T>\r\n      <T>System.Object</T>\r\n    </TN>\r\n    <ToString>@{name=foo; resourceGroup=bar}</ToString>\r\n    <Obj RefId=\"1\">\r\n      <TNRef RefId=\"0\" />\r\n      <MS>\r\n        <S N=\"name\">foo</S>\r\n        <S N=\"resourceGroup\">bar</S>\r\n      </MS>\r\n    </Obj>\r\n    <MS>\r\n      <S N=\"name\">foo</S>\r\n      <S N=\"resourceGroup\">bar</S>\r\n    </MS>\r\n  </Obj>\r\n</Objs>"
        }
      }
    },
```

Please fix the serialization so complex parameter objects can be used as templateparameters, using either hashtables or pscustomobjects.

**Comment by ravbhatnagar** [comment] 2016-02-03 01:26
@abombss - Can you please verify again? I was able to define the template parameter object as follows and use it successfully in my deployment -
-TemplateParameterObject @{storageSettings = @{name='foo'; resourceGroup='bar'}}

**Comment by pgroene** [comment] 2016-02-05 12:22
Have you tried to put all arguments on the same line as the cmdlet? This fixed it in our case.

**Comment by robplank** [comment] 2016-02-07 18:36
I am seeing the same issue when passing an array inside of the Hashtable when executed from Powershell workflow

this works
$Template =  'C:\Linked Templates\Test\azuredeploy.json'
Add-AzureRmAccount
Get-AzureRmSubscription
Select-AzureRmSubscription -SubscriptionId $subId

[arary]$VMName = @()
$VMName += "Test362016"
$VMName += "Test462016"
$Param = @{

VMName = $VMName

}

New-AzureRmResourceGroupDeployment -Name Test -ResourceGroupName sfiaas -TemplateParameterObject $Param -TemplateFile $Template 

but this does not

Workflow Test {
$Template =  'C:\Linked Templates\Test\azuredeploy.json'
Add-AzureRmAccount
Get-AzureRmSubscription
Select-AzureRmSubscription -SubscriptionId $subId

[arary]$VMName = @()
$VMName += "Test362016"
$VMName += "Test462016"
$Param = @{

VMName = $VMName

}

New-AzureRmResourceGroupDeployment -Name Test -ResourceGroupName sfiaas -TemplateParameterObject $Param -TemplateFile $Template 
}
Test

**Comment by ravbhatnagar** [comment] 2016-02-11 22:42
This is by design for now. Lets investigate the work to support this. Investigate.

**Comment by mignonsys** [comment] 2016-07-06 05:26
Have a similar issue when passing a large object (multi-level nested dictionary and array objects). The exception thrown is also similar (xml....)... 
The workaround I adopted was assign the final dictionary object (contains multiple key value pairs) I constructed by powershell to a single key-value dictionary (doing something like $dictobjparam = @{'value'=$originalMultiKeyValueDict}  and then use the $dictobjparam as the parameter everything goes fine.

**Comment by AlexKeySmith** [comment] 2017-06-23 11:11
Hi, has there been any progress on this? 

If the ticket is still relevant, it would be interesting to know which formatting of an object is supported and what isn't.

**Comment by KacperMucha** [comment] 2017-07-22 00:15
I'm experiencing a similar issue. I have a script that gets Azure resource properties, saves them as PSObject and then converts to hashtable with this function:
```powershell
function ConvertPSObjectToHashtable
{
    param (
        [Parameter(ValueFromPipeline)]
        $InputObject
    )

    process
    {
        if ($null -eq $InputObject) { return $null }

        if ($InputObject -is [System.Collections.IEnumerable] -and $InputObject -isnot [string])
        {
            $collection = @(
                foreach ($object in $InputObject) { ConvertPSObjectToHashtable $object }
            )

            Write-Output -NoEnumerate $collection
        }
        elseif ($InputObject -is [psobject])
        {
            $hash = @{}

            foreach ($property in $InputObject.PSObject.Properties)
            {
                $hash[$property.Name] = ConvertPSObjectToHashtable $property.Value
            }

            $hash
        }
        else
        {
            $InputObject
        }
    }
}
```
which I found here: [https://stackoverflow.com/questions/3740128/pscustomobject-to-hashtable](url)
It converts everything fine until it encounters an array. When there is an array in the object I get the same CliXml... output which causes the template deployment to fail.

I created a test script to troubleshoot this issue:
```powershell
begin {
    function Convert-PSObjectToHashtable {
        param (
            [Parameter(ValueFromPipeline)]
            $InputObject
        )

        process {
            if ($null -eq $InputObject) { return $null }

            if ($InputObject -is [System.Collections.IEnumerable] -and $InputObject -isnot [string]) {
                $collection = @(
                    foreach ($object in $InputObject) { Convert-PSObjectToHashtable $object }
                )

                Write-Output -NoEnumerate $collection
            }
            elseif ($InputObject -is [psobject]) {
                $hash = @{}

                foreach ($property in $InputObject.PSObject.Properties) {
                    $hash[$property.Name] = Convert-PSObjectToHashtable $property.Value
                }

                $hash
            }
            else {
                $InputObject
            }
        }
    }
}

process {
    $object = New-Object -TypeName psobject -Property @{
        prop1 = '123'
        prop2 = 2
        prop3 = @()
    }
    $objectHash1 = Convert-PSObjectToHashtable -InputObject $object -Verbose
    $objectHash2 = Convert-PSObjectToHashtable -InputObject $object -Verbose
    $objectHash2.prop3 = @()

    ConvertTo-Json -InputObject $objectHash1
    ConvertTo-Json -InputObject $objectHash2
}
```
What is interesting is that when I assign an empty array outside of the function, everything works and output of objectHash2 operation produces proper JSON format. ObjectHash1 on the other hand produces object instead of an array as a value of prop3.
```powershell
{
    "prop2":  2,
    "prop1":  "123",
    "prop3":  {
                  "value":  [

                            ],
                  "Count":  0
              }
}
{
    "prop2":  2,
    "prop1":  "123",
    "prop3":  [

              ]
}
```

**Comment by gotmoo** [comment] 2017-09-01 02:23
This isn't exactly passing a parameter of type "object" but passing an array as a parameter did the trick for me:


In PowerShell, make an array of hashtables and pass it to New-AzureRmResourceGroupDeployment
```
[array]$nicConfigs = @{name="nic1"; ip = "10.3.4.21"}
[array]$nicConfigs += @{name="nic2"; ip = "10.3.4.22"}

New-AzureRmResourceGroupDeployment -ResourceGroupName rgName `
-TemplateFile C:\Azure\JSON\nicCreateObjectLoopParam.json `
-nicConfigs $nicConfigs
```

in the JSON, set the parameter as array type:
```
  "parameters": {
    "nicConfigs": {
      "type": "array"
    }
  },
```

Then you can use them in your resource creation with copyindex like so:
`              "privateIPAddress": "[parameters('nicConfigs')[copyIndex()].ip]"
`

**Comment by AyoOlubeko** [comment] 2017-10-02 17:35
Adding to gotmoo's answer above, make sure the values of your hashtable are strings otherwise serialization does not happen properly

**Comment by cormacpayne** [comment] 2018-07-05 23:50
@ravbhatnagar ping

**Comment by barborico** [comment] 2019-03-04 06:04
I am experiencing the XML serialization issue when trying to pass `securestring` parameters in the `TemplateParameterObject`. Specifically,
```
$secret = ConvertTo-SecureString "secret" -Force -AsPlainText
$templateParameters = @{
    secret = $secret
}
```
serializes to something like
```
"secret": {
    "value": {
        "CliXml": "<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\">\r\n  <SS>01000000d08c9ddf0115d1118c7a00c04fc297eb01000000729c4a38b9e1504a8553cb163e7db4ea0000000002
000000000003660000c000000010000000b69acba24d02a40845707fe228c2ea0c0000000004800000a0000000100000006114f7443d62aa35a0c346a98c5ddce020000000355b8cb6249eff99d0181349e023379da1bf8de70763f68e3af4d80163b1c2e0140
00000a5313293d68e6403f41d83fd16fbe9212d501a14</SS>\r\n</Objs>"
    }
}
```
It works to pass the parameter as a direct PowerShell command argument though.

**Comment by simonsabin** [comment] 2019-04-16 11:08
Ditto, I'm finding that using TemplateParameterObject with a hashtable containing a securestring fails with error saying the parameter (that is a secure string) is invalid. Using the @parameters, instead of TemplateParameterObject works

**Comment by shenglol** [comment] 2020-07-24 23:57
Same as https://github.com/Azure/azure-powershell/issues/6292.

**Comment by alex-frankel** [comment] 2020-09-23 17:36
This should be fixed in the latest powershell release

**Closed by alex-frankel** 2020-09-23 17:36 UTC
Labels: ARM, ARM - Templates, Service Attention, feature-request
