### ISSUE TITLE
Az.Storage will not accept "-EnableHttpsTrafficOnly $True"

### ISSUE THREAD

**Issue by Gill-Bates** [Azure/azure-powershell#13443] opened 2020-11-06 09:37 UTC
Running the cmdlet `New-AzStorageAccount` (Module-Version 4.02) ends up in an exception. It seems that the Parameter `-EnableHttpsTrafficOnly` cannot handle the Boolean Value.

```
 New-AzStorageAccount `
                            -ResourceGroupName $RG `
                            -Name $AccountName `
                            -Location westeurope `
                            -SkuName Standard_LRS `
                            -Kind StorageV2 `
                            -AccessTier Hot `
                            -EnableHttpsTrafficOnly $True
```

Will end up in:

```
A positional parameter cannot be found that accepts argument 'True'.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception 
exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)!
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException
```

**Running the same command under 2.7.0 works like a charme!**

**Comment by blueww** [comment] 2020-11-06 09:59
@Gill-Bates 

Az.Storage 4.0.2-preview is released long ago (althrough the version is bigger), and not for normal user. 
Please don't use it.

Please use latest Az.Storage with version 3.* .

**Comment by Gill-Bates** [comment] 2020-11-06 10:31
**Version 2.7 and 3.0 works as expected!**

**Comment by blueww** [comment] 2020-11-06 10:34
@Gill-Bates 
As the issue is resolve by using the latest stable version 3.0, I will close the issue.

Feel free to contact us if you need any further assistance on Azure Powershell.

**Closed by blueww** 2020-11-06 10:34 UTC
Labels: customer-reported, needs-triage, question
