### ISSUE TITLE
Get-AzureRmStorageAccount failed at mooncake.

### ISSUE THREAD

**Issue by andyliuliming** [Azure/azure-powershell#2337] opened 2016-05-26 06:43 UTC
C:\Users\andliu\Documents\GitHub\MooncakeImageService\StarDustV2\AutoDeploy [master ↑]> Get-AzureRmStorageAccount
Get-AzureRmStorageAccount : The resource type 'storageAccounts' could not be found in the namespace 'Microsoft.Storage' for api version '2016-01-01'. The
supported api-versions are '2015-06-15,2015-05-01-preview'.
At line:1 char:1
+ Get-AzureRmStorageAccount
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmStorageAccount], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Management.Storage.GetAzureStorageAccountCommand

**Comment by vinjiang** [comment] 2016-05-30 03:34
This is a backwards comp issue caused by the lower SRP API version supported by Mooncake. Please try the older version before Mooncake supports latest API version.

**Comment by blueww** [comment] 2016-09-21 08:45
MoonCake  should already been upgraded, please try if the issue repro

**Comment by blueww** [comment] 2016-09-22 02:56
Close the issue as it's already fixed.
Feel free t reopen if necessary.

**Closed by blueww** 2016-09-22 02:56 UTC
Labels: Storage
