### ISSUE TITLE
Get-AzBatchNodeFile does not respect the ComputeNode parameter

### ISSUE THREAD

**Issue by jn-altius** [Azure/azure-powershell#10514] opened 2019-11-11 18:07 UTC
Following Example 5 in the documentation here:
https://github.com/Azure/azure-powershell/blob/master/src/Batch/Batch/help/Get-AzBatchNodeFile.md

### Setup
I have 3 Pools named LargePool, MediumPool and SmallPool.  LargePool does not contain any Nodes, MediumPool contains 1 dedicated node, and SmallPool contains 1 low priority node.
Both MediumPool and SmallPool have run at least once and there is output in the 'workitems' folder on each.

### Execution
When I run Get-AzBatchNodeFile and pass in the ComputeNodeId for SmallPool I see the 'workitems' output for BOTH SmallPool and MediumPool.

### Expectation
I expect to see only the output for SmallPool because that is the ComputeNodeId that I have passed in.

### Example code
```
$resourceGroups = Get-AzResourceGroup -Name $searchName;

foreach ($resourceGroup in $resourceGroups)
{
    $batches = Get-AzResource -ResourceGroupName $resourceGroup.ResourceGroupName -ResourceType $resourceType;

    foreach($batch in $batches)
    {
        $batchName = $batch.Name;
        Write-Host "Batch is:" $batchName;

        $batchContext = Get-AzBatchAccountKeys -AccountName $batch.Name;

        $pools = Get-AzBatchPool -BatchContext $batchContext;

        foreach ($pool in $pools)
        {
            $poolId = $pool.Id;
            Write-Host "`tPool is:" $poolId;

            $nodes = Get-AzBatchComputeNode -PoolId $pool.Id -BatchContext $batchContext;

            foreach ($node in $nodes)
            {
                $nodeId = $node.Id;
                Write-Host "`t`tNode is:" $nodeId;

                Get-AzBatchNodeFile -ComputeNodeId $node.Id -PoolId $pool.Id -BatchContext $batchContext -Filter "startswith(name, '$folderFilter')" -Recursive;
            }
        }
    }
}
```

Is this a bug in the cmdlet?  Or is there some extra syntax in Example 5 that is missing?

Thanks

**Comment by matthchr** [comment] 2019-11-26 17:58
This is a duplicate of #10572

**Closed by matthchr** 2019-11-26 17:58 UTC
Labels: Batch
