### ISSUE TITLE
Unable to remove diagnostics extension set without role parameter specified due to ConflictError.

### ISSUE THREAD

**Issue by thebothead** [Azure/azure-powershell#1573] opened 2016-01-04 20:51 UTC
If you set the Pass Diagnostics extension without the role parameter, you can then never remove the extension, such that the next time you go to enable the extension without the role parameter you will be notified of an ID conflict (which is your only indicator that the extension is still there!).

Repro steps:
1.  Set-AzureServiceDiagnosticsExtension -StorageContext $storageContext -DiagnosticsConfigurationPath $config –ServiceName $service -Slot $slot
-> Success

2. Get-AzureServiceDiagnosticsExtension –ServiceName $service -Slot $slot
-> Returns the config with the default naming convention.

3. Remove-AzureServiceDiagnosticsExtension –ServiceName $service -Slot $slot
* Note that I have also tried this here using the role for each role.
-> Returns success that extension was removed.

4. Set-AzureServiceDiagnosticsExtension -StorageContext $storageContext -DiagnosticsConfigurationPath $config –ServiceName $service -Slot $slot
-> Returns error that the extension ID already exists.

Set-AzureServiceDiagnosticsExtension : ConflictError: The extension ID Default-PaaSDiagnostics-Production-Ext-0 already exists.
At D:\Sandbox\SchneiderElectric\DevOps\Diagnostics\EnableDiagnostics.ps1:24 char:1
+ Set-AzureServiceDiagnosticsExtension -StorageContext $storageContext  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-AzureServiceDiagnosticsExtension], CloudException
    + FullyQualifiedErrorId : Hyak.Common.CloudException,Microsoft.WindowsAzure.Commands.ServiceManagement.Extensions.SetAzureServiceDiagnosticsExtensionCommand

**Comment by yantang-msft** [comment] 2016-01-20 19:31
@thebothead This is an regression and have been fixed recently. It should work correctly in the next release.

The underlying story is like this, say you have two roles, RoleA, RoleB.
When you enable extension without specifying -Role, we send the request parameter like
{ AllRoles: diagExtensionConfig }

When remove the extension, we first get the current config, which is like below (and this is how the regression happens)
{ RoleA: diagExtensionConfig, RoleB: diagExtensionConfig }
And if you remove the extension without specifying -Role, we try to find the config information in "AllRoles" which is empty, so the command failed.

With the fix, if you don't specify -Role, we will check for the "diagExtensionConfig" in all places and remove it.

**Comment by thebothead** [comment] 2016-01-21 14:42
@yantang-msft Thanks.  I installed the latest Azure PS 1.1.0 from:

https://azure.microsoft.com/en-us/documentation/articles/powershell-install-configure/

When will the next release be available with this fix?  Is there a work-around for the issue in the meantime?

**Comment by yantang-msft** [comment] 2016-01-21 18:23
The next release will be Feb 2nd.
For now, either specifying -Role (the specific roles you want to remove) or -UninstallConfiguration (remove extension for all roles) should work.

**Comment by thebothead** [comment] 2016-01-21 19:34
Thanks.  What is the difference between specifying -Role and -UninstallConfiguration?

**Comment by yantang-msft** [comment] 2016-01-21 19:47
@thebothead As I said, -Role will only remove the extensions for the roles you specified. E.g., you have RoleA, RoleB, RoleC
If you specify -Role @("RoleA", "RoleB"), RoleC will still have extension enabled.
While specifying -UninstallConfiguration will remove extension for all roles in the service.

Actually -UninstallConfiguration does something more, but as the user, you don't need to worry about it. The fact is our configuration process has two steps, we first set the configuration, then do a deployment change. A normal Remove command only change the deployment, and the configuration is still there. By specifying -UninstallConfiguration, we remove the configuration, and that's why the extension on all roles will be removed.

**Comment by thebothead** [comment] 2016-01-21 19:49
@yantang-msft  Thanks for elaborating again.  I forgot that you answered that already in an above reply.

**Comment by markcowl** [comment] 2016-08-08 19:34
Closing, as it looks like this was resolved.

**Closed by markcowl** 2016-08-08 19:34 UTC
