### ISSUE TITLE
[Az.Aks] Get-AzAksUpgradeProfile does not honor -DefaultProfile Parameter

### ISSUE THREAD

**Issue by aydeisen** [Azure/azure-powershell#21319] opened 2023-03-24 15:14 UTC
### Description

When executing `Get-AzAksUpgradeProfile` with `-DefaultProfile`, this cmdlet continues to use the currently selected context for the PowerShell Process.

This cmdlet does work if using `Set-AzContext`

### Issue script & Debug output

```PowerShell
PS C:\Users\aydei> $ctx = Get-AzContext -ListAvailable | ? {$_.Subscription.Name -like "*SUBSCRIPTION2*"}
DEBUG: 11:08:24 - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 11:08:24 - GetAzureRMContextCommand end processing.
PS C:\Users\aydei> Get-AzAksUpgradeProfile -ClusterName AZAKSCLUSTER -ResourceGroupName AKSRESOURCEGROUP
DEBUG: 11:08:25 - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 11:08:25 - GetAzureRMContextCommand end processing.
DEBUG: [CmdletBeginProcessing]: Starting command
DEBUG: CmdletBeginProcessing:
DEBUG: CmdletProcessRecordStart:
DEBUG: CmdletGetPipeline:
DEBUG: CmdletBeforeAPICall:
DEBUG: URLCreated: /subscriptions/SUBSCRIPTION1/resourceGroups/AKSRESOURCEGROUP/providers/Microsoft.ContainerService/managedClusters/AZAKSCLUSTER/upgradeProfiles/default?api-version=2020-09-01
DEBUG: RequestCreated: /subscriptions/SUBSCRIPTION1/resourceGroups/AKSRESOURCEGROUP/providers/Microsoft.ContainerService/managedClusters/AZAKSCLUSTER/upgradeProfiles/default?api-version=2020-09-01
DEBUG: HeaderParametersAdded:
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/SUBSCRIPTION1/resourceGroups/AKSRESOURCEGROUP/providers/Microsoft.ContainerService/managedClusters/AZAKSCLUSTER/upgradeProfiles/default?api-version=2020-09-01

Headers:
x-ms-unique-id                : 4
x-ms-client-request-id        : 913dacbf-732c-480a-89f1-c315184fe229
CommandName                   : Get-AzAksUpgradeProfile
FullCommandName               : Get-AzAksUpgradeProfile_Get
ParameterSetName              : __AllParameterSets
User-Agent                    : AzurePowershell/v9.5.0,PSVersion/v7.3.3,Az.Aks/5.3.1

Body:
DEBUG: 11:08:25 - [ConfigManager] Got nothing from [EnableLoginByWam], Module = [], Cmdlet = []. Returning default value [False].
DEBUG: BeforeCall:
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : 871f4b2c-0331-488b-841d-8148b3d87a5a
x-ms-correlation-request-id   : 871f4b2c-0331-488b-841d-8148b3d87a5a
x-ms-routing-request-id       : CANADACENTRAL:20230324T150826Z:871f4b2c-0331-488b-841d-8148b3d87a5a
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Fri, 24 Mar 2023 15:08:26 GMT

Body:
{
  "error": {
    "code": "ResourceGroupNotFound",
    "message": "Resource group 'AKSRESOURCEGROUP' could not be found."
  }
}
DEBUG: ResponseCreated:
DEBUG: BeforeResponseDispatch:

Get-AzAksUpgradeProfile_Get: Resource group 'AKSRESOURCEGROUP' could not be found.

Get-AzAksUpgradeProfile_Get: Resource group 'AKSRESOURCEGROUP' could not be found.
DEBUG: [Finally]: Getting exception 'Microsoft.Azure.Commands.Common.Exceptions.AzPSResourceNotFoundCloudException: InternalException' from response
DEBUG: Finally:
DEBUG: CmdletAfterAPICall:
DEBUG: [CmdletProcessRecordAsyncEnd]: Finish HTTP process
DEBUG: CmdletProcessRecordAsyncEnd:
DEBUG: CmdletProcessRecordEnd:
DEBUG: AzureQoSEvent:  Module: Az.Aks:5.3.1; CommandName: Get-AzAksUpgradeProfile; PSVersion: 7.3.3; IsSuccess: False; Duration: 00:00:00.3193557; Exception: InternalException;
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.12.1                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     5.3.1                 Az.Aks                              {Disable-AzAksAddOn, Enable-AzAksAddOn, Get-AzAksCluster, Get-AzAksNodePool…}
Script     6.5.3                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
```

### Error output

```PowerShell
HistoryId: 27

Message        : [ResourceGroupNotFound] : Resource group 'AKSRESOURCEGROUP' could not be found.
StackTrace     :
Exception      : System.Exception
InvocationInfo : {Get-AzAksUpgradeProfile_Get}
Line           : Get-AzAksUpgradeProfile -ClusterName AZAKSCLUSTER -ResourceGroupName AKSRESOURCEGROUP
Position       : At line:1 char:1
                 + Get-AzAksUpgradeProfile -ClusterName AZAKSCLUSTER -ResourceGroupN …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 27
```

**Comment by isra-fel** [comment] 2023-03-26 16:37
Hi @YanaXu this cmdlet should be able to work with `Set-AzContext`. Please look into it. Thanks.

**Comment by dolauli** [comment] 2023-04-26 11:56
@aydeisen  For generated cmdlets, the `-defaultprofie` does not work, and the root cause is the generator does not support it(see https://github.com/Azure/autorest.powershell/issues/1143 for details). If you want to specify subscription, you may use the `-SubscriptionId` supported by generated cmdlets.

**Comment by dolauli** [comment] 2023-05-03 02:28
The issues happen to all generated cmdlets. And let track them all in https://github.com/Azure/azure-powershell/issues/21688.

**Comment by dolauli** [comment] 2023-05-03 02:29
Closed it since we have created an issue to track such a kind of issues.

**Closed by dolauli** 2023-05-03 02:29 UTC
Labels: Azure PS Team, Investigate :mag:, bug, customer-reported, needs-team-attention
