### ISSUE TITLE
Support -VaultId option on Site Recovery cmdlets

### ISSUE THREAD

**Issue by sean-nixon** [Azure/azure-powershell#9255] opened 2019-05-21 01:22 UTC
`Set-AzRecoveryServicesVaultContext` displays a warning that it is going away and to use the `-VaultId` parameter instead. However, none of the ASR cmdlets appear to support this parameter (I just installed the latest version it doesn't appear as a valid parameter). Are those cmdlets going to support the new parameter soon?

Deprecation warning:
```
WARNING: Breaking changes in the cmdlet 'Set-AzRecoveryServicesVaultContext' :
WARNING:  - The cmdlet is being deprecated. There will be no replacement for it.


WARNING: Note :The change is expected to take effect from the version :  'This command is getting deprecated. Please use -VaultID parameter in all Recovery Services commands going forward.'
```

**Comment by MiYanni** [comment] 2019-05-21 22:29
@sean-nixon The `-VaultId` parameter is part of the RecoveryServicesBackup cmdlets. For example: https://docs.microsoft.com/en-us/powershell/module/az.recoveryservices/get-azrecoveryservicesbackupcontainer?view=azps-2.1.0
So, that is what the warning is indicating.

**Comment by sean-nixon** [comment] 2019-05-21 22:46
@MiYanni Can this be re-opened? The impact of removing this cmdlet extends beyond just RecoveryServicesBackup cmdlets. This cmdlet can also be used to set the vault context for use with those cmdlets. We are using currently using this cmdlet in production scripts to interact with our recovery services vaults for Site Recovery (see the script excerpt below).

What is the expectation around Azure Site Recovery cmdlets then if this cmdlet is removed?

Example cmdlet:
https://docs.microsoft.com/en-us/powershell/module/az.recoveryservices/get-azrecoveryservicesasrfabric?view=azps-2.1.0

```
$vault = Get-AzureRmRecoveryServicesVault -Name "$vaultName"
Set-AzureRmRecoveryServicesAsrVaultContext -Vault $vault
$asrPrimaryFabric = Get-ASRFabric -Name $primaryFabricName
```

**Comment by MiYanni** [comment] 2019-05-22 19:33
@sean-nixon Since I don't work for the Recovery Services team, based on their deprecation message, I'm assuming that they will add `-VaultID` to [Get-AzRecoveryServicesAsrFabric](https://docs.microsoft.com/en-us/powershell/module/az.recoveryservices/get-azrecoveryservicesasrfabric?view=azps-2.1.0), and to any other cmdlets that had previously used this context mechanism.

@siddharth7 Care to add any details/context?

**Comment by sean-nixon** [comment] 2019-05-31 00:49
@MiYanni Can this be re-opened then? It doesn't seem like this issue should be closed since it is specifically addressing adding -VaultId to those Site Recovery cmdlets not the Backup cmdlets which I understand now support it. Unless there is no plan to add that parameter to Site Recovery cmdlets and there will be a new context mechanism @siddharth7?

**Comment by horpek** [comment] 2019-08-19 01:12
We are using this cmdlet too and have the same concern and here I hit this github issue page.  

I am surprise that this issue is closed by @MiYanni but claimed that he does not work on the Recovery Service Team and provide assumption rather facts/solution.  Why not leave it to right resource instead of closing it?

**Comment by siddharth7** [comment] 2019-11-25 11:40
@sean-nixon @horpek The `-VaultID` parameter is not being removed, we will update the error message in the subsequent release

**Comment by Rajeswari-Mamilla** [comment] 2019-12-10 08:21
@MiYanni Can you please update the label? This is related to Azure Backup

**Comment by DanteNahuel** [comment] 2020-06-23 20:54
@Rajeswari-Mamilla I don't see how this is related to Azure Backup. OP states that the problem is with ASR cmdlets, not with Backup cmdlets
Maybe I'm mistaken, though

**Comment by Rajeswari-Mamilla** [comment] 2020-07-09 16:49
@DanteNahuel - my bad. Please refer to our guidance available at _https://docs.microsoft.com/en-us/azure/site-recovery/azure-to-azure-powershell#set-the-vault-context_ to set the context of a vault for ASR. Can you let me know if you are looking for a different workflow?

**Comment by Rajeswari-Mamilla** [comment] 2020-07-10 06:19
Got it, sean-nixon. Let us review the ask & get back to you on the details

**Comment by Sharmistha-Rai** [comment] 2020-09-02 10:48
We are tracking this in our backlog. We will keep the thread updated with our plans on this.

**Comment by Sharmistha-Rai** [comment] 2020-09-02 11:26
Please feel free to reopen for any additional queries.

**Closed by Sharmistha-Rai** 2020-09-02 11:26 UTC
Labels: Recovery Services Site-Recovery, Service Attention
