### ISSUE TITLE
Why does Get-AzNetworkingServiceTag not have same change number as weekly JSON file?

### ISSUE THREAD

**Issue by Gheedit** [Azure/azure-powershell#20139] opened 2022-11-15 11:57 UTC
### Description

I am trying to get the current change number of service tag "AzureFrontDoor.Backend". In the [weekly JSON](https://www.microsoft.com/en-us/download/details.aspx?id=56519), the change number for this service tag is "13". Though, when getting it via Get-AzNetworkServiceTag cmdlet, it returns "10". How is it, that the number returned from the cmdlet, is behind 3 change cycles compared to the one provided in the JSON? What's the reason for this? 
I saw in [another thread](https://github.com/Azure/azure-powershell/issues/16539#issue-1066913935) that the API has a safer deployment procedure, where changes are rolled out in each region separately - even though this tag is "global" - while the JSON just gets released weekly. I would imagine that the change number can be behind 1 change cycle because of that, but 3 seems to be a bit far off.

`$serviceTag = Get-AzNetworkServiceTag -Location "westeurope"`
`$azureFrontDoorServiceTag = $serviceTag.Values | Where-Object { -not $_.Properties.Region -and $_.Name -eq "AzureFrontDoor.Backend" }`
`$azureFrontDoorChangeNumber = [int]$azureFrontDoorServiceTag.Properties.ChangeNumber`
`$azureFrontDoorServiceTag`
`$azureFrontDoorChangeNumber`

### Script or Debug output

```PowerShell
Name             : AzureFrontDoor.Backend
System Service   : 
Address Prefixes : {4.232.98.120/29, 13.73.248.16/29, 20.21.37.40/29, 20.36.120.104/29...}
Change Number    : 10

10
```

### Environment data

```PowerShell
PSVersion 5.1.17763.2803
```

### Module versions

```PowerShell
Az.Automation 1.7.0
```

**Comment by navba-MSFT** [comment] 2022-11-16 02:37
@Gheedit Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment] 2022-11-17 04:45
@Gheedit I am able to reproduce this issue at my end. I also tried to invoke [this REST API](https://learn.microsoft.com/en-us/rest/api/virtualnetwork/service-tags/list?tabs=HTTP) directly using (api-version=2022-07-01). Even this results in the same issue. I believe this might be expected, since the JSON is updated weekly, but our rest api releases with new api-versions are delayed by a few months. I am discussing this internally with our product owners. I will keep you posted once I hear from them.

**Comment by navba-MSFT** [comment] 2022-11-30 04:32
@Gheedit Apologies for the late reply. I am waiting to hear back from the Product Owners. I will update this thread once I have the details.

**Comment by Gheedit** [comment] 2022-11-30 08:44
Hi @navba-MSFT, I appreciate your response and I look forward to hearing from you!

**Comment by navba-MSFT** [comment] 2022-12-02 04:00
@Gheedit The discrepancy between the change number via Get-AzNetworkServiceTag (i.e. DiscoveryAPI) and Public JSON file is expected since each of them follow a completely different process and are separate pipelines.

Could you elaborate on your dependency on the change numbers? It is not intended to be the same for 2 different processes.

**Comment by Gheedit** [comment] 2022-12-02 08:47
Hi @navba-MSFT, I see. But that makes the Get-AzNetworkServiceTag cmdlet still a usable source to get the IP addresses behind the service tag? 
So, we have a runbook which updates an IP group automatically. The IP group contains all IP addresses of the Azure "AzureFrontDoor.Backend" service tag. Whenever the change number increases by 1, the IP group gets updated with the new IP addresses.

**Comment by navba-MSFT** [comment] 2022-12-06 05:22
@Gheedit Thanks for the details. You could continue using Get-AzNetworkServiceTag cmdlet to pull all the IP addresses assigned to a service tag. This would give you latest IPs via Discovery API. Or you could pull IP info via Public JSON file that is updated 1/week. However, you shouldn’t reference the change number to be the exact same in both cases since follow a completely different process and are separate pipelines. Hope this answers.

**Closed** 2022-12-13 06:03 UTC
Labels: Network, question, customer-reported, CXP Attention, issue-addressed

**Comment by plzm** [comment] 2023-04-20 21:25
> @Gheedit Thanks for the details. You could continue using Get-AzNetworkServiceTag cmdlet to pull all the IP addresses assigned to a service tag. This would give you latest IPs via Discovery API. Or you could pull IP info via Public JSON file that is updated 1/week. However, you shouldn’t reference the change number to be the exact same in both cases since follow a completely different process and are separate pipelines. Hope this answers.

It would be really helpful if this could be added to the documentation page for Get-AzNetworkServiceTag. I just spent a good bit of time myself trying to figure out why the public IPs file (which is extremely difficult to automate around due to its 302 and changing filename/path) differs from the output of this cmdlet. Thanks @Gheedit for raising this issue!
