### ISSUE TITLE
Issue with Type for Parameter 'Receiver' for Set-AzureRmActionGroup (AzureRM.Insights)

### ISSUE THREAD

**Issue by Vijayaraghavanl** [Azure/azure-powershell#6422] opened 2018-06-08 15:09 UTC
Dear Team,

Need help to sort out an issue that I am experiencing while I am trying to add multiple receivers for Azure Action Group at the same time using a powershell script.

I have written a Powershell script that will import all required inputs for variables for Set-AzureRmActionGroup from a CSV. 

My CSV has headers and values as updated below.

EntryType | ActionGroupName | ActionGroupShortName | UserNames | EmailAddresses | SMSUserNumber | Country | CountryCode
-- | -- | -- | -- | -- | -- | -- | --
New | TestGroup08Jun | AGT08Jun | Test1, Test2,Test3 | me@123.com, test@234.com,another123@567.com | 7401021008, 1234567890 | India | 91

I have got a for loop that works through the email addresses & phone numbers and creates different variables for all unique email addresses and phone numbers. I also have a logic to get the variables  created and then store them in yet another variable as say $Receivers

I call this variable $Receivers in the Set-ActionRmActionGroup cmdlet as indicated below.

Set-AzureRmActionGroup -Name $actionGroupName -ResourceGroup $resourceGroupName -ShortName $shortName -Receiver $Receivers

$Receivers = $EmailUser0,$EmailUser1,$EmailUser2,$SMSUser0,$SMSUser1

But then I run into the following error:

Set-AzureRmActionGroup : Cannot bind parameter 'Receiver'. Cannot convert the "$EmailUser0,$EmailUser1,$EmailUser2,$SMSUser0,$SMSUser1" value of type "System.String" to type 
"Microsoft.Azure.Commands.Insights.OutputClasses.PSActionGroupReceiverBase".

If I replace $Receivers with "$EmailUser0,$EmailUser1,$EmailUser2,$SMSUser0,$SMSUser1" I get the same error. If I remove the double quotes the command works as expected. I have not been able to figure out a way to suppress the double quotes when calling $Receivers in the Set-AzureRmActionGroup.

I can assure that my entire logic of the script works just fine and expected until I run the Set-AzureRmActionGroup cmdlet.

I need help to solve this problem as I have a huge azure environment and it ain't practically possible go over creating Action Group & Receivers manually.

Kindly suggest how I could get over this problem at the earliest. 

**General Info**                                                                                                                                                    

ModuleType | Version | Name | ExportedCommands
-- | -- | -- | --
---------- | ------- | ---- | ----------------
Script | 5.7.0 | AzureRM |  

Name | Value
-- | --
---- | -----
PSVersion | 5.1.14393.953
PSEdition | Desktop
PSCompatibleVersions | {1.0, 2.0, 3.0, 4.0...}
BuildVersion | 10.0.14393.953
CLRVersion | 4.0.30319.42000
WSManStackVersion | 3
PSRemotingProtocolVersion | 2.3
SerializationVersion | 1.1.0.

**Comment by praries880** [comment] 2018-06-08 19:30
@Vijayaraghavanl can you share how you prepare the variables `$EmailUser0,$EmailUser1,$EmailUser2,$SMSUser0,$SMSUser1` that you add to the list?

Heres a sample of a script that I wrote that was able to create the Action Group :

```powershell
$email1 = New-Object  Microsoft.Azure.Commands.Insights.OutputClasses.PSEmailReceiver
$email1.EmailAddress = "p1@g.com"
$email1.Name = "p1g"

$email2 = New-Object  Microsoft.Azure.Commands.Insights.OutputClasses.PSEmailReceiver
$email2.EmailAddress = "p2@g.com"
$email2.Name = "p2g"

$sms1 = New-Object  Microsoft.Azure.Commands.Insights.OutputClasses.PSSmsReceiver
$sms1.CountryCode = "91"
$sms1.PhoneNumber = "1234579890"
$sms1.Name = "s1g"

$sms2 = New-Object  Microsoft.Azure.Commands.Insights.OutputClasses.PSSmsReceiver
$sms2.CountryCode = "91"
$sms2.PhoneNumber = "2143579890"
$sms2.Name = "s2g"

$recievers = @($email1,$email2,$sms1,$sms2)

Set-AzureRmActionGroup -Name "Act1" -ResourceGroup "test1" -ShortName "sn1" -Receiver $recievers
```
Let us know if this does not work for you.

**Comment by Vijayaraghavanl** [comment] 2018-06-09 09:16
@praries880 : Thanks for your response.

Below is my script. Part of my problem is that number of email receivers & sms receivers may change based on each action group. Therefore, I may not well in advance be able to define $Receivers in advance. I therefore want $Receivers to contain the variables that I created recently.

Based on your suggestion above I figured out that my variables $EmailUser0,$EmailUser1,$EmailUser2,$SMSUser0,$SMSUser1 are all of the type Microsoft.Azure.Commands.Insights.OutputClasses.PSSmsReceiver.

The Type changes to System.String @ the line where I generate $EmailVariables & $SMSVariables and $Receivers.

$FileLocation = $env:USERPROFILE + "\OneDrive for Business\Scripts\JSON with Powershell\"

$CSVFile = $FileLocation + "Parameters v1.0 - Action Group.csv"

$CSVInput = Import-Csv $CSVFile | Where-Object {$_.EntryType -eq 'New'}

ForEach($InputObj in $CSVInput)
    
    {

    $ActionGroupResourceGroup = "Default-ActivityLogAlerts"

    $ActionGroupName = $InputObj.ActionGroupName
    
    $ActionGroupShortName = $InputObj.ActionGroupShortName
    
    [array]$UserNames = $InputObj.UserNames.Split(",")

    [array]$EmailAddresses	= $InputObj.EmailAddresses.Split(",")
        
    [array]$SMSUserNumbers = $InputObj.SMSUserNumber.Split(",")

    $CountryCode = $InputObj.CountryCode

    $EmailUsers = $null

    $SMSUsers = $null

    Get-Variable | Where-Object {$_.Name -match 'EmailUser*' -and $_.Name -notmatch 'EmailUsers'} | Remove-Variable
    
    Get-Variable | Where-Object {$_.Name -match 'SMSUser*' -and $_.Name -notmatch 'SMSUsers' -and $_.Name -notmatch 'EachSMSUser' -and $_.Name -notmatch 'SMSUserNumber' -and $_.Name -notmatch 'SMSUserNumbers'} | Remove-Variable

    For($EachEmailAddress=0;$EachEmailAddress -lt $EmailAddresses.Count;$EachEmailAddress++)

        {

        $EmailString = "_-EmailAction-"

        $EmailUsers = "EmailUser"

        $UserName = $UserNames[$EachEmailAddress].Trim() + $EmailString

        $EmailAddress = $EmailAddresses[$EachEmailAddress].Trim()

        New-Variable "${EmailUsers}${EachEmailAddress}" -Value $(New-AzureRmActionGroupReceiver -Name $UserName -EmailReceiver -EmailAddress $EmailAddress) -Force

        }

    For($EachSMSUser=0;$EachSMSUser -lt $SMSUserNumbers.Count;$EachSMSUser++)

        {

        $SMSString = "_-SMSAction-"

        $SMSUsers = "SMSUser"

        $UserName = $UserNames[$EachSMSUser].Trim() + $SMSString

        [string]$SMSUserNumber = $SMSUserNumbers[$EachSMSUser].Trim()

        New-Variable "${SMSUsers}${EachSMSUser}" -Value $(New-AzureRmActionGroupReceiver -Name $UserName -SmsReceiver -CountryCode $CountryCode -PhoneNumber $SMSUserNumber) -Force
            
        }

    $EmailVariables = (Get-Variable | Where-Object {$_.Name -match 'EmailUser*' -and $_.Name -notmatch 'EmailUsers'} | Select-Object -ExpandProperty Name) -join "," -replace ("Email",'$Email')

    $SMSVariables = (Get-Variable | Where-Object {$_.Name -match 'SMSUser*' -and $_.Name -notmatch 'SMSUsers' -and $_.Name -notmatch 'EachSMSUser' -and $_.Name -notmatch 'SMSUserNumber' -and $_.Name -notmatch 'SMSUserNumbers'} | Select-Object -ExpandProperty Name) -join "," -replace ("SMS",'$SMS')

    $Receivers = ($EmailVariables, $SMSVariables -join ",")

    Set-AzureRmActionGroup -ResourceGroupName $ActionGroupResourceGroup -Name $ActionGroupName -ShortName $ActionGroupShortName -Receiver $Receivers

**Comment by Vijayaraghavanl** [comment] 2018-06-12 13:14
@praries880 

Hi, did you get a chance to look any my script? I am using a workaround to bypass this problem while I hear from you. I am not too impressed with this approach though my job is getting done and wonder if you have a better suggestion that I could consider.

$FileLocation = $env:USERPROFILE + "\OneDrive for Business\Scripts\JSON with Powershell\" ## Already there in my script above. I have made following additions.

$ReceiverPSScript = $FileLocation + "Receiver.ps1"

$EmailVariables = (Get-Variable | Where-Object {$_.Name -match 'EmailUser*' -and $_.Name -notmatch 'EmailUsers'} | Select-Object -ExpandProperty Name) -join "," -replace ("Email",'$Email')

$SMSVariables = (Get-Variable | Where-Object {$_.Name -match 'SMSUser*' -and $_.Name -notmatch 'SMSUsers' -and $_.Name -notmatch 'EachSMSUser' -and $_.Name -notmatch 'SMSUserNumber' -and $_.Name -notmatch 'SMSUserNumbers'} | Select-Object -ExpandProperty Name) -join "," -replace ("SMS",'$SMS')

$Receiver = ($EmailVariables, $SMSVariables -join ",")

Write-Output "Set-AzureRmActionGroup -ResourceGroupName $ActionGroupResourceGroup -Name $ActionGroupName -ShortName $ActionGroupShortName -Receiver $Receiver" > $ReceiverPSScript

& $ReceiverPSScript

**Comment by Vijayaraghavanl** [comment] 2018-06-13 11:13
@praries880,

Thanks a ton! I sincerely appreciate your time with this. This solves my problem.

I kept my original script as is and took the following lines from what you proposed above. I had to do so, so as to ensure that if a single user has both Email Address & Phone number mentioned we do not end up  creating two different receivers one each for Email Address & Phone Number but instead update the user to include both Email Address & Phone Number. To achieve that I have to append "_-EmailAction-" in the Username for Email Address receiver the username & "_-SMSAction-" in the Username for SMS Receiver.

Again, thanks a lot for all your help to get over this problem.

$Receivers = [System.Collections.ArrayList]@()

$EmailUser = New-AzureRmActionGroupReceiver -EmailReceiver -Name $UserName -EmailAddress $EmailAddress

$Receivers.Add($EmailUser)

$SMSUser = New-AzureRmActionGroupReceiver -SmsReceiver -Name $UserName -CountryCode $CountryCode -PhoneNumber $SMSUserNumber

$Receivers.Add($SMSUser)

Below is  the complete script:

$FileLocation = $env:USERPROFILE + "\OneDrive for Business\Scripts\JSON with Powershell\"

$CSVFile = $FileLocation + "Parameters v1.0 - Action Group.csv"

$CSVInput = Import-Csv $CSVFile | Where-Object {$_.EntryType -eq 'New'}

ForEach($InputObj in $CSVInput)
    
    {

    $ActionGroupResourceGroup = "Default-ActivityLogAlerts"

    $ActionGroupName = $InputObj.ActionGroupName
    
    $ActionGroupShortName = $InputObj.ActionGroupShortName
    
    [array]$UserNames = $InputObj.UserNames.Split(",")

    [array]$EmailAddresses	= $InputObj.EmailAddresses.Split(",")
        
    [array]$SMSUserNumbers = $InputObj.SMSUserNumber.Split(",")

    $CountryCode = $InputObj.CountryCode

    $EmailUsers = $null

    $SMSUsers = $null

    $Receivers = [System.Collections.ArrayList]@()

    For($EachEmailAddress=0;$EachEmailAddress -lt $EmailAddresses.Count;$EachEmailAddress++)
    
        {

        $EmailString = "_-EmailAction-"

        $UserName = $UserNames[$EachEmailAddress].Trim() + $EmailString

        $EmailAddress = $EmailAddresses[$EachEmailAddress].Trim()

        $EmailUser = New-AzureRmActionGroupReceiver -EmailReceiver -Name $UserName -EmailAddress $EmailAddress

        $Receivers.Add($EmailUser)
    
        }

    For($EachSMSUser=0;$EachSMSUser -lt $SMSUserNumbers.Count;$EachSMSUser++)
    
        {

        $SMSString = "_-SMSAction-"

        $UserName = $UserNames[$EachSMSUser].Trim() + $SMSString

        [string]$SMSUserNumber = $SMSUserNumbers[$EachSMSUser].Trim()

        $SMSUser = New-AzureRmActionGroupReceiver -SmsReceiver -Name $UserName -CountryCode $CountryCode -PhoneNumber $SMSUserNumber

        $Receivers.Add($SMSUser)
    
        }

    $Receivers

    Set-AzureRmActionGroup -ResourceGroupName $ActionGroupResourceGroup -Name $ActionGroupName -ShortName $ActionGroupShortName -Receiver $Receivers

    }

**Comment by praries880** [comment] 2018-06-13 16:59
Glad to be of assistance @Vijayaraghavanl :) 
Closing the issue as of now since the issue is resolved.

**Closed by praries880** 2018-06-13 16:59 UTC
Labels: Azure PS Team, More Info
