### ISSUE TITLE
Unexpected script limit encountered when running New-AzKustoScript

### ISSUE THREAD

**Issue by Escape17** [Azure/azure-powershell#17554] opened 2022-03-22 08:56 UTC
### Description

 We are seeing the following error in our CI/CD pipeline when running New-AzKustoScript.

New-AzKustoScript -ClusterName <redacted> -DatabaseName  …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | [BadRequest] Cannot create new script since the number of
     | scripts was exceeded. Each service can contain up to '50'
     | scripts.

This seems straightforward enough on the face of it. However we are still seeing this error even after we have deleted all databases in our cluster (with Remove-AzKustoDatabase) to which the scripts were originally applied. 

This is a problem as the obvious workaround to this (i.e. use Remove-AzKustoScript to delete the scripts instead) does not work if the database to which the script was applied has already been deleted, since it requires the name of said DB as a parameter. 

It really feels like Remove-AzKustoDatabase should also be automatically removing any Kusto scripts that were applied to it using New-AzKustoScript. Was there perhaps a deliberate design reason for not doing so? Or are we doing something wrong?

**Comment by PramodValavala-MSFT** [comment] 2022-03-22 14:58
@Escape17 I would suspect this is due to sub resources from being deleted asynchronously after deleting the database. Could you give it a shot after some time and check to see if you are still seeing the same problem?

**Comment by Aviv-Yaniv** [comment] 2022-03-27 09:33
Thanks for contacting @Escape17 
Code shows scripts should have been removed upon DB deletion
Could you please open a ticket / provide with cluster name and details so we can check the process here?

**Comment by Escape17** [comment] 2022-03-28 06:48
Thank you @Aviv-Yaniv.

Unfortunately the cluster has now been deleted as it became unusable for us due to this issue. I will try to reproduce on a new cluster and follow up with details here.

**Comment by Aviv-Yaniv** [comment] 2022-03-28 07:11
Thank you @Escape17 for writing me back and for sharing details! 
Found the root cause, working on the root fix for the issue and to get such clusters out from from bad state
No need to reproduce, altogether if there are any living clusters that need remediation please provide their details

**Comment by dingmeng-xue** [comment] 2022-06-05 14:38
@Aviv-Yaniv , has this issue been fixed?

**Comment by zoharHenMicrosoft** [comment] 2022-06-06 06:47
@Aviv ***@***.***>

**Comment by Aviv-Yaniv** [comment] 2022-06-06 07:01
@dingmeng-xue Issue is fixed

**Comment by dingmeng-xue** [comment] 2022-06-06 07:33
Thanks Aviv. Close this issue now.

**Closed by dingmeng-xue** 2022-06-06 07:33 UTC
Labels: Service Attention, question, customer-reported, Azure Data Explorer
