### ISSUE TITLE
Error when trying to subscribe to Storage Account events

### ISSUE THREAD

**Issue by thdotnet** [Azure/azure-powershell#6278] opened 2018-05-23 14:32 UTC
I'm trying to subscribe to Storage Account Events using Event Grid. This is storage account was originally on classic mode. After I've migrated to ARM, and then to GPV2, it offers me the "Events" on the portal.

I was trying thourgh the portal, but in the end runs powershell, so I think this is the right place to put this issue.

On the log details I'm getting:

The attempt to configure storage notifications for the provided storage account xxxx failed. Please ensure that your storage account meets the requirements described at https://aka.ms/storageevents. The error is Failed to retrieve credentials for request=RequestUri=https://management.azure.com/subscriptions/e9d0d1a3-9de3-4551-b913-cad770b8044e/resourceGroups/xxxx-migrated/providers/Microsoft.Storage/storageAccounts/xxxx/listAccountSas, Method=POST, response=StatusCode=500, StatusDescription=Internal Server Error, IsSuccessStatusCode=False, Content=System.Net.HttpWebResponse, responseContent={"error":{"code":"InternalServerError","message":"Internal server error."}} (Code: Storage Notification)

Any tips?

**Comment by maddieclayton** [comment] 2018-05-23 22:26
@blueww Can you take a look at this issue? If you believe this is an EventGrid issue, please let me know and I'll reassign to the EventGrid team.

**Comment by blueww** [comment] 2018-05-25 01:57
@thdotnet 

I have try to contact feature team for the issue, and we will need the storage account name and request time/details to investigate further. (better with request ID)

**Comment by kalyanaj** [comment] 2018-05-25 05:04
Thanks @blueww. We are in an e-mail conversation with @thdotnet and the Storage team has made a change that should resolve this.  Thiago will be re-attempting the command to check if the issue is resolved.

**Comment by blueww** [comment] 2018-05-25 05:26
Good to know that.
Thanks for the update!

Please update if the issue is resolved.

**Comment by kalyanaj** [comment] 2018-05-29 14:42
@thdotnet confirmed offline that the fix is working for him, hence closing this issue.

**Closed by kalyanaj** 2018-05-29 14:42 UTC
Labels: Event Grid, Storage

**Comment by MikeMartin180** [comment] 2018-07-17 21:04
Hello,

I have the same issue. Can you share what the fix is?

Error thrown:

Operation name
ListAccountSas
Time stamp
Tue Jul 17 2018 21:59:02 GMT+0100 (British Summer Time)
Event initiated by
Microsoft.EventGrid
Error code
ClientClosedRequest
Message
The connection has been closed by the client while the server is still processing its request for 'Microsoft.Storage'.

**Comment by thdotnet** [comment] 2018-07-17 21:17
Hi,

I’ve fixed after I upgraded the storage account to v2.
