### ISSUE TITLE
Improve error message for Microsoft Account login using -Credential parameter

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#3121] opened 2016-10-25 21:25 UTC
As pointed out by another user in #3108, Microsoft Accounts (MSA) are not supported for logging in using the `-Credential` parameter on `Add-AzureRmAccount`. While this is very unlikely to change, can we at least improve the error message that's returned, when you attempt to login with a Microsoft Account, using the `-Credential` parameter?

Right now, the exception message is extremely vague:

> add-azurermaccount : Sequence contains no elements

/cc @markcowl 

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by doctordns** [comment] 2016-10-26 11:26
Trevor - that will help.
But what I can't really understand is why Microsoft accounts cannot be used, Seems to me it's a simple backend issue that MS could easily solve. As I've said, MS accounts are in the cloud anyway. I'd kind of surprised MS just can't merge them into AAD. 

But it seems like no one has the ability to fix this.

A better error message will help. Improved documentation would also be useful.

**Comment by pcgeek86** [comment] 2016-10-26 17:50
@doctordns Unfortunately it's not as easy as it sounds. Microsoft Accounts and Azure Active Directory are entirely different systems. 

I think the improved documentation is going to be the most realistic option at this point. I'm all about improving functionality, but in this particular case, there is actually a better, supported method. Once you start using Azure Active Directory, instead of Microsoft Account, I think you'll see why.

**Comment by doctordns** [comment] 2016-10-26 20:03
You may be right. 

I wonder if the cmdlet could so some form of screen scraping. Calling the Login-AzureRMAccount does work, just via the GUI. Is the GUI returned capable of being screen scraped? 

The cmdlet error messages need to be improved and the cmdlet documentation needs to be improved both to ensure the issue is clear, as is the workaround.

**Comment by cormacpayne** [comment] 2016-12-06 21:49
Fix is in https://github.com/Azure/azure-powershell/pull/3255

**Closed** 2016-12-06 22:59 UTC
Labels: Team
