### ISSUE TITLE
Get-AzTenant -TenantId needs to return Tenant information from service

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-powershell#12486] opened 2020-07-27 04:43 UTC
## Description of the new feature

Get-AzTenant per id should return tenant object with domain information from service.

**Comment by msJinLei** [comment] 2020-07-28 06:20
The issue is fixed by  https://github.com/Azure/azure-powershell/pull/12495

**Closed by msJinLei** 2020-07-28 06:20 UTC
Labels: Azure PS Team, feature-request
