### ISSUE TITLE
[Azure Stack] Cmdlet New-DataDiskObject  missing Azs Prefix

### ISSUE THREAD

**Issue by troettinger** [Azure/azure-powershell#8109] opened 2018-12-12 22:56 UTC
### Description

Missing Azs Prefix
Function        New-DataDiskObject                                 0.2.0      Azs.Compute.Admin

### Script/Steps for Reproduction

```powershell

```

### Module Version

```powershell
Get-Module -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by deathly809** [comment] 2018-12-13 19:48
This is a duplicate of #8111

**Closed by deathly809** 2018-12-13 19:48 UTC
Labels: Azure Stack
