### ISSUE TITLE
Select-AzureRmSubscription fails when run on a remote computer using invoke-command

### ISSUE THREAD

**Issue by mosharafMS** [Azure/azure-powershell#3924] opened 2017-05-08 03:56 UTC
### Cmdlet(s)
When running Select-AzureRmSubscription on a remote computer using invoke-command, it fails with error 
Provided subscription <valid subscription id> does not exist
    + CategoryInfo          : CloseError: (:) [Set-AzureRmContext], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.SetAzureRMContextCommand
    + PSComputerName        : azLogIntegrator
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with 
On the local computer
Name                           Value
----                           -----
PSVersion                      5.1.14393.1066
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1066
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

On the remote 
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Module Version
2.6

### OS Version
10.0.14393.693

### Description
When running Select-AzureRmSubscription on a remote computer using invoke-command, it fails with error 
### Debug Output
DEBUG: 3:52:43 AM - SetAzureRMContextCommand begin processing with ParameterSet 'SubscriptionId'.
DEBUG: 3:52:43 AM - using account id '<GUID>'...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 05/08/2017 03:52:43:  - TokenCache: Deserialized 1 items to token cache.
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: 'Common', Endpoint:
'https://login.microsoftonline.com/', ClientId: '<GUID>', ClientRedirect:
'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthrity: 'True'
DEBUG: [Common.Authentication]: Renewing token using AppId: '<GUID>', AdalConfiguration
with ADDomain: 'Common', AdEndpoint: 'https://login.microsoftonline.com/', ClientId:
'<GUID>', RedirectUri: 'urn:ietf:wg:oauth:2.0:oob'
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain:
'<GUID>', Endpoint: 'https://login.microsoftonline.com/', ClientId:
'<GUID>', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri:
'https://management.core.windows.net/', ValidateAuthrity: 'True'
DEBUG: [Common.Authentication]: Renewing token using AppId: '8ea7a0df-ab90-4620-98c5-4fa137c18a6c', AdalConfiguration
with ADDomain: '<GUID>', AdEndpoint: 'https://login.microsoftonline.com/', ClientId:
'<GUID>', RedirectUri: 'urn:ietf:wg:oauth:2.0:oob'
Provided subscription <GUID> does not exist
    + CategoryInfo          : CloseError: (:) [Set-AzureRmContext], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.SetAzureRMContextCommand
    + PSComputerName        : azLogIntegrator

DEBUG: 3:52:43 AM - SetAzureRMContextCommand end processing.
DEBUG: 3:52:43 AM - SetAzureRMContextCommand end processing.

### Script/Steps for Reproduction
Invoke-Command -FilePath "C:\_stuff\azuredeploy.ps1" -Session $session

**Comment by markcowl** [comment] 2017-08-08 17:54
This is a duplicate of an existing issue the fix is being tracked here: #1835

**Closed by markcowl** 2017-08-08 17:54 UTC
Labels: Investigate, Team
