### ISSUE TITLE
Update ADAL version in Az module to support device auth in ADFS

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#7625] opened 2018-10-19 01:10 UTC
The following PR is enabling device code flow ADFS

https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/1282/

This change is needed in the ADAL version consumed by the az.profile module

**Comment by MiYanni** [comment] 2018-10-19 23:12
@bganapa We already have an issue for this. But, thank you for linking a specific issue. We'll make sure when we update it, we have the version containing that fix.

**Comment by MiYanni** [comment] 2018-10-19 23:12
Duplicate of https://github.com/Azure/azure-powershell/issues/6739

**Closed by MiYanni** 2018-10-19 23:12 UTC
