### ISSUE TITLE
Get-AzureRmResource fails against public Azure b/c of api-version

### ISSUE THREAD

**Issue by devigned** [Azure/azure-powershell#2891] opened 2016-09-02 22:48 UTC
### Cmdlet(s)
Get-AzureRmResource

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
see image

### Module Version
see image

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
see image

### Description
Get-AzureRmResource fails against public Azure b/c of api-version

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue
Not needed. The api-version is not acceptable by the server and stated in the image.

### Script/Steps for Reproduction
See image

![get-azurermresources-error](https://cloud.githubusercontent.com/assets/386473/18220294/58e02960-7125-11e6-803f-4f342b4f59a3.PNG)

**Comment by devigned** [comment] 2016-09-02 22:58
Just in case anyone is interested, you can get around this with: `Get-AzureRmResource -ApiVersion '2016-07-01'`

**Comment by takekazuomi** [comment] 2016-09-03 12:51
I also had the same problem. This is annoying. Existing script is broken.

```
$ Get-AzureRmResource                                                                                                                                                                                                                                       
Get-AzureRmResource : InvalidApiVersionParameter : The api-version '2016-09-01' is invalid. The supported versions are '2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.     
発生場所 行:1 文字:1                                                                                                                                                                                                                                               
+ Get-AzureRmResource                                                                                                                                                                                                                                       
+ ~~~~~~~~~~~~~~~~~~~                                                                                                                                                                                                                                       
    + CategoryInfo          : CloseError: (:) [Get-AzureRmResource]、ErrorResponseMessageException                                                                                                                                                           
    + FullyQualifiedErrorId : InvalidApiVersionParameter,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet                                                                                                             

$ get-module | ?{$_.Name -match "Azure*"}                                                                                                                                                                          
                                                                                                                                                                                                                   
ModuleType Version    Name                                ExportedCommands                                                                                                                                         
---------- -------    ----                                ----------------                                                                                                                                         
Manifest   2.0.1      Azure.Storage                       {Get-AzureStorageBlob, Get-AzureStorageBlobContent, Get-AzureStorageBlobCopyState, Get-AzureStorageContainer...}                                         
Manifest   2.0.1      AzureRM.Profile                     {Add-AzureRmAccount, Add-AzureRmEnvironment, Disable-AzureRmDataCollection, Enable-AzureRmDataCollection...}                                             
Manifest   3.0.1      AzureRM.Resources                   {Export-AzureRmResourceGroup, Find-AzureRmResource, Find-AzureRmResourceGroup, Get-AzureRmADAppCredential...}                                            
Manifest   2.0.1      AzureRM.Storage                     {Get-AzureRmStorageAccount, Get-AzureRmStorageAccountKey, Get-AzureRmStorageAccountNameAvailability, Get-AzureRmStorageUsage...}                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
```

**Comment by markcowl** [comment] 2016-09-06 05:16
The root cause of this is here: https://github.com/Azure/azure-powershell/blob/dev/src/ResourceManager/Resources/Commands.ResourceManager/Cmdlets/Implementation/Resource/GetAzureResourceCmdlet.cs#L426 

The resource manager cmdlets use the api-version of the 'resourceGroups' resource type, rather then 'resources'.  Normally, these would be the same, but they were different for a short period of time.

The current symptoms of this issue were fixed by a service side change, but we should fix this discrepancy in code to prevent this from recurring.

**Comment by ravbhatnagar** [comment] 2016-10-10 23:53
Fixed

**Closed by ravbhatnagar** 2016-10-10 23:53 UTC
Labels: ResourceManager

**Comment by SaBomNim21** [comment] 2017-10-13 21:20
This is happening now that I updated my azure instance with Install-Module Azure and using "Get-AzureRmResource -ApiVersion '2016-07-01'" fails
