### ISSUE TITLE
PSCloud Shell - Bash Pwsh not update to latest AzureRM.Netcore v.0.11.0

### ISSUE THREAD

**Issue by MaximoTrinidad** [Azure/azure-powershell#5991] opened 2018-04-19 16:02 UTC
### Description

I finally started to use CloudShell and love the fact that has the AzureRM.Netcore module installed in the Bash pwsh side.  The problem is that is not updated to the latest version which is v0.11.0. 

This new version has more modules that version 0.10.0.

I realized that we have no way to update the modules ourselves!

It would be Great if we could installed new modules ourselves,

### Script/Steps for Reproduction

Current CloudShell Bash Pwsh AzureRM.Netcore installed:

```powershell
PS /home/maximo> Get-AzureRMNetcore

Name                      Version
----                      -------
AzureRM.Compute.Netcore   0.10.0
AzureRM.KeyVault.Netcore  0.10.0
AzureRM.Netcore           0.10.0
AzureRM.Network.Netcore   0.10.0
AzureRM.Profile.Netcore   0.10.0
AzureRM.Resources.Netcore 0.10.0
AzureRM.Storage.Netcore   0.10.0
AzureRM.Tags.Netcore      0.10.0
AzureRM.Websites.Netcore  0.10.0
```
Existing new PSGallery AzureRM.Netcore modules v 0.11.0: (sample from Windows OS)
```
PS C:\Program Files\PowerShell\6.1.0-preview.1> Get-AzureRMNetcore

Name                                   Version
----                                   -------
AzureRM.Aks.Netcore                    0.11.0
AzureRM.AnalysisServices.Netcore       0.11.0
AzureRM.ApiManagement.Netcore          0.11.0
AzureRM.ApplicationInsights.Netcore    0.11.0
AzureRM.Automation.Netcore             0.11.0
AzureRM.Backup.Netcore                 0.11.0
AzureRM.Batch.Netcore                  0.11.0
AzureRM.Billing.Netcore                0.11.0
AzureRM.Cdn.Netcore                    0.11.0
AzureRM.CognitiveServices.Netcore      0.11.0
AzureRM.Compute.Netcore                0.11.0
AzureRM.Consumption.Netcore            0.11.0
AzureRM.ContainerInstance.Netcore      0.11.0
AzureRM.ContainerRegistry.Netcore      0.11.0
AzureRM.DataFactories.Netcore          0.11.0
AzureRM.DataFactoryV2.Netcore          0.11.0
AzureRM.DataLakeAnalytics.Netcore      0.11.0
AzureRM.DataLakeStore.Netcore          0.11.0
AzureRM.DevTestLabs.Netcore            0.11.0
AzureRM.Dns.Netcore                    0.11.0
AzureRM.EventGrid.Netcore              0.11.0
AzureRM.EventHub.Netcore               0.11.0
AzureRM.Insights.Netcore               0.11.0
AzureRM.IotHub.Netcore                 0.11.0
AzureRM.KeyVault.Netcore               0.11.0
AzureRM.LogicApp.Netcore               0.11.0
AzureRM.MachineLearning.Netcore        0.11.0
AzureRM.MachineLearningCompute.Netcore 0.11.0
AzureRM.MarketplaceOrdering.Netcore    0.11.0
AzureRM.Media.Netcore                  0.11.0
AzureRM.Netcore                        0.11.0
AzureRM.Network.Netcore                0.11.0
AzureRM.NotificationHubs.Netcore       0.11.0
AzureRM.OperationalInsights.Netcore    0.11.0
AzureRM.PowerBIEmbedded.Netcore        0.11.0
AzureRM.Profile.Netcore                0.11.0
AzureRM.RedisCache.Netcore             0.11.0
AzureRM.Relay.Netcore                  0.11.0
AzureRM.Resources.Netcore              0.11.0
AzureRM.Scheduler.Netcore              0.11.0
AzureRM.ServiceBus.Netcore             0.11.0
AzureRM.ServiceFabric.Netcore          0.11.0
AzureRM.Sql.Netcore                    0.11.0
AzureRM.Storage.Netcore                0.11.0
AzureRM.StreamAnalytics.Netcore        0.11.0
AzureRM.Tags.Netcore                   0.11.0
AzureRM.TrafficManager.Netcore         0.11.0
AzureRM.UsageAggregates.Netcore        0.11.0
AzureRM.Websites.Netcore               0.11.0

```
### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
```

### Environment Data

CloudShell Bash session

```powershell
PS /home/maximo> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.1
PSEdition                      Core
GitCommitId                    v6.1.0-preview.1
OS                             Linux 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

### Debug Output

```

```
![cloudshell _bash_2018-04-19_12-04-39](https://user-images.githubusercontent.com/19892435/39004049-488fa9a4-43ca-11e8-8ff1-08335a598cac.jpg)

**Comment by cormacpayne** [comment] 2018-04-19 16:27
@MaximoTrinidad Hey Maximo, thanks for filing this issue

@HemantMahawar Hey Hemant, it looks like the previous version of `AzureRM.Netcore` was shipped with Bash in Cloud Shell -- would you mind taking a look?

**Comment by HemantMahawar** [comment] 2018-04-19 19:35
@MaximoTrinidad Thanks for reporting the issue. You are correct that we do not have latest version (0.11) of AzureRM*.NetCore module on Cloudshell Linux environment, whereas it is present in Cloudshell Windows environment. We will get it fixed soon.

In the meantime, you can workaround this issue by installing the latest version manually using **Install-Module** cmdlet. Manually installed modules are saved in your Clouddrive so they are persistent across sessions and are loaded automatically (though they will add some delay to pwsh startup since they are not in the OS image). //cc @Jluk & @maertendMSFT

**Comment by MaximoTrinidad** [comment] 2018-04-19 20:29
Hi @HemantMahawar, 

OK! It's a workaround and I know you guys will eventually will update to v.0.11.0.

During this exercise I found our the PowerShell "sort" shorthand doesn't work in Linux. I had to type the full cmdlet name Sort-Object.

:)

```
## - Doesn't work in Linux
Get-Module -ListAvailable AzureRm.*Netcore | Select Name, Version | sort Version, Name 

## - Works in Linux:
Get-Module -ListAvailable AzureRm.*Netcore | Select Name, Version | sort-object Version, Name 
```

![sort_01_2018-04-19_16-26-22](https://user-images.githubusercontent.com/19892435/39016454-83dcecf0-43ee-11e8-9948-7f6370cf545f.jpg)

![sort_02_2018-04-19_16-26-22](https://user-images.githubusercontent.com/19892435/39016513-aa6f8d0a-43ee-11e8-891d-b763052928de.jpg)

**Comment by HemantMahawar** [comment] 2018-04-19 22:05
@MaximoTrinidad, yes its by design because some of the PowerShell aliases conflict with Linux commands. 
Missing aliases (by design) is discussed/commented in  https://github.com/PowerShell/PowerShell/issues/6684

**Comment by MaximoTrinidad** [comment] 2018-04-19 22:38
Thanks @HemantMahawar !

I will take a look at the list. I got the modules installed. 
Of course, I would like to have only one version but I can work with it.

:)

**Comment by cormacpayne** [comment] 2018-11-01 20:13
Closing as we are now shipping the latest version of `Az` with Cloud Shell as the module is released.

**Closed by cormacpayne** 2018-11-01 20:13 UTC
Labels: CloudShell
