### ISSUE TITLE
New-AzResourceGroupDeployment changes Time field value 

### ISSUE THREAD

**Issue by MayankBargali-MSFT** [Azure/azure-powershell#15785] opened 2021-08-31 05:18 UTC
While deploying the [ARM template](https://docs.microsoft.com/answers/storage/attachments/127454-arm.txt) using Templates option in Azure portal the logic app is created successfully and I can see that the timeZone and startTime is correctly set to my recurrence trigger.

But when I deploy the same template using New-AzResourceGroupDeployment command then I observe that it adds Z at the end of the startTime parameter despite the ARM template doesn’t have Z added to the startTime value.

```
New-AzResourceGroupDeployment
-Name LOGIC_APP_NAME
-ResourceGroupName RESOURCE_GROUP
-Mode Incremental
-TemplateFile "C:\Users\USER\Downloads\arm.txt"
```

As Z is added therefor the logic app does not take consider the timeZone option. Can you please confirm if this is issue with the New-AzResourceGroupDeployment as the same template works when deploying ARM template using portal option

**Comment by dingmeng-xue** [comment] 2021-08-31 06:13
This issue should be addressed by https://github.com/Azure/azure-powershell/pull/15552

**Comment by MayankBargali-MSFT** [comment] 2021-08-31 06:31
@dingmeng-xue Thanks for the update. Will test it in the next release targeting on 7th September.

**Comment by MayankBargali-MSFT** [comment] 2021-09-10 04:44
@armleads-azure can you please confirm if this issue is fixed in the latest release as I can still observe the issue in v6.4.0

**Comment by jorgecotillo** [comment] 2021-09-16 15:51
Not sure about v6.4.0, but based on [this](https://github.com/Azure/azure-powershell/blob/main/src/Resources/Resources/ChangeLog.md#version-431) the fix should be in version 4.3.1 can you please confirm?

**Comment by jorgecotillo** [comment] 2021-09-16 22:58
Can you please verify that you are using Resources module 4.3.1? See changelog here: https://github.com/Azure/azure-powershell/blob/main/src/Resources/Resources/ChangeLog.md#version-431

PR #15552 should fix for both parameters and template content serialization, here's the updated code: https://github.com/Azure/azure-powershell/blob/9d6294304d655503e6556b2734c65fff11916662/src/Resources/ResourceManager/SdkClient/ResourceManagerSdkClient.cs#L454

**Comment by dingmeng-xue** [comment] 2021-09-17 04:18
I close this issue now and let's open it if the issue is not fixed.

**Closed by dingmeng-xue** 2021-09-17 04:18 UTC
Labels: Service Attention, ARM - Templates

**Comment by ojintoad** [comment] 2021-12-16 00:07
Is there any possibility that there's still a bug involving times about triggers that include timezone info?

After upgrading from Az 6.3.0 -> Az 6.4.0 I'm seeing error messages like:

```
{
    "status": "Failed",
    "error": {
        "code": "InvalidWorkflowTriggerRecurrence",
        "message": "The recurrence of trigger 'recurrence' has an invalid start time '2017-04-04T17:15:00.0000000+00:00' zone designator for time zone 'Eastern Standard Time'. Expected start time format with zone designator is 'yyyy-MM-ddTHH:mm:ss'."
    }
}
```

However, my template has the following:

```
 "triggers": {
                        "recurrence": {
                            "type": "recurrence",
                            "recurrence": {
                                "frequency": "Day",
                                "interval": 1,
                                "timeZone": "Eastern Standard Time",
                                "startTime": "2017-04-04T12:15:00-05:00"
                            }
                        }
                    },
```

The template is working with Az 6.3.0 and this date issue feels related. I also don't see any unit tests in https://github.com/Azure/azure-powershell/pull/15552 of dates that contain additional timezone information. If you prefer that I open up another bug feel free to let me know.
