### ISSUE TITLE
AZ.Account module 2.7.1 Does Not Support User Password Reset

### ISSUE THREAD

**Issue by Dblakhokage** [Azure/azure-powershell#16869] opened 2022-01-19 07:14 UTC
### Description

I am reaching out regarding an Issue I am experiencing.

I just upgraded to Az.account Powershell module 2.7.1 that was released 14 days ago.

Since then the below cmdlet has been failing:

$RandomString = ConvertTo-SecureString -String 'dummypass' -AsPlainText -Force
Update-AzADUser -Password $RandomString -UserPrincipalName $User.UserPrincipalName

I keep getting the following error: 

“Parameter cannot be processed because the parameter name 'Password' is ambiguous. Possible matches include: -PasswordPolicy -PasswordProfile. (Parameter cannot be processed because the parameter name 'Password' is ambiguous. Possible matches include: -PasswordPolicy -PasswordProfile.) “

I have also tried to use the 2.7.1 module on a local machine and it returned an error too.

I am reaching just to confirm if this is a known issue and is being worked on.

Also, I want to find out if there is a workaround for this scenario, one that does not involve downgrading to an older version. (I am aware that the 1.13.0 and 1.7.5 versions work with the cmdlet)

Thank you for your anticipated response.

Best regards,

### Issue script & Debug output

```PowerShell
N/A
```

### Environment data

```PowerShell
N/A
```

### Module versions

```PowerShell
2.7.1 module
```

### Error output

```PowerShell
“Parameter cannot be processed because the parameter name 'Password' is ambiguous. Possible matches include: -PasswordPolicy -PasswordProfile. (Parameter cannot be processed because the parameter name 'Password' is ambiguous. Possible matches include: -PasswordPolicy -PasswordProfile.) “
```

**Comment by dingmeng-xue** [comment] 2022-01-19 07:36
@VeryEarly , please look into this issue.

**Comment by Dblakhokage** [comment] 2022-01-24 07:34
Any update on this please?

>

**Comment by Dblakhokage** [comment] 2022-01-24 11:37
@VeryEarly please tell this is being worked on? please
its really urgent!

**Comment by VeryEarly** [comment] 2022-01-24 14:06
> @VeryEarly please tell me this is being worked on? please its really urgent!

Hi @Dblakhokage ,

Thanks for reporting this issue, I'm working on the fix, new version of Az.Resources will be available early next month.

**Comment by happywino** [comment] 2022-01-24 19:41
@VeryEarly, this appears to be a duplicate of an issue I opened #16795, can you confirm that this is a bug?

I initially reported similar strange behavior with -EnableAccount but added the -Password issue to the same report, is the -EnableAccount issue a bug too?

**Comment by VeryEarly** [comment] 2022-02-07 07:24
> @VeryEarly, this appears to be a duplicate of an issue I opened #16795, can you confirm that this is a bug?
> 
> I initially reported similar strange behavior with -EnableAccount but added the -Password issue to the same report, is the -EnableAccount issue a bug too?

Yes and it should be fixed in https://www.powershellgallery.com/packages/Az.Resources/5.3.0

**Closed** 2022-02-07 07:30 UTC
Labels: AAD, bug, question, customer-reported
