### ISSUE TITLE
Get-AzureStorageContainer - Forbidden 

### ISSUE THREAD

**Issue by grik001** [Azure/azure-powershell#6613] opened 2018-07-06 07:20 UTC
Hi,

I am trying to execute the following command:

$ctx = New-AzureStorageContext -StorageAccountName "coditstgweinvictusstore" -SasToken ""
$containers = Get-AzureStorageContainer -Context $ctx

It works locally using powershell, but keep returning 401 when executing it from VSTS. This was working previosly, the only thing I can think of that was changed was the SasToken(re-generated).

I have tried generating the SasToken - both from Storage and Azure.

2018-07-06T07:13:37.2414621Z Get-AzureStorageContainer : The remote server returned an error: (403) Forbidden. HTTP Status Code: 403 - HTTP Error 
2018-07-06T07:13:37.2415300Z Message: This request is not authorized to perform this operation.

**Comment by grik001** [comment] 2018-07-06 08:33
Where can I find the : debug log of Get-AzureStorageContainer

**Comment by grik001** [comment] 2018-07-06 08:39
1:
2: ?sv=2017-11-09&ss=bfqt&srt=sco&sp=rwdlacup&se=2019-07-06T16:21:37Z&st=2017-07-06T08:21:37Z&spr=https,http&sig=
3:

**Comment by blueww** [comment] 2018-07-06 08:42
1. Debug log：
Run ： $containers = Get-AzureStorageContainer -Context $ctx -debug
And the output is debug log.

2.The SAS looks good

3. Please check the module version by "get-module".

**Comment by grik001** [comment] 2018-07-06 08:47
1: Azure-Storage-PowerShell-3e98e217-9623-45d8-8ad3-77b60b6cb15c
2: ?sv=2017-11-09&ss=bfqt&srt=sco&sp=rwdlacup&se=2019-07-06T16:21:37Z&st=2017-07-06T08:21:37Z&spr=https,http&sig=
3: Is This correct? Get-Module -Name Azure.Storage

**Comment by blueww** [comment] 2018-07-06 09:09
”Get-Module -Name Azure.Storage“ should work. 
You should run it in the same PowerShell console, after the issue repro.

**Comment by grik001** [comment] 2018-07-06 09:46
@blueww 

Sorry for the delay, I am trying to figure out how I can get VSTS to output this data. I can see the request ID locally but the DEBUG comments are not being printed in VSTS logs during the build.

**Comment by grik001** [comment] 2018-07-06 13:12
@blueww 

I know it may not be related to this. But do you know how I can use -Debug in VSTS since it requires interactive mode?

**Comment by blueww** [comment] 2018-07-09 02:03
@grik001 
I am not sure how to use -Debug in VSTS. 

But if you can't get the debug log, could you share the test account name and test time (UTC)? I can try to find the log.

BTW, please share the module version by run ”Get-Module -Name Azure.Storage“, and show me the output

**Comment by blueww** [comment] 2018-07-17 01:39
@bikramgcnz 
Does the script works before with same SAS? If so, it might caused by the SAS expire.
Could you share the SAS token (hide sig), and the script you use the SAS?
And the module version of the Azure.Storage module.

**Comment by bikramgcnz** [comment] 2018-07-17 01:45
I haven't changed this script for a long time, here is the scenario i have,
 i create the storage account,
 then its assigned to a variable,
 i then use the context from the storage account variable to create the storage container.

So i don't generate the SAS token myself

**Comment by blueww** [comment] 2018-07-17 02:09
@bikramgcnz 
As this issue is for SAS issue, do you mind to open a new issue for it, as it's a different question.
I still don't quite get how your script works. Could you also share the script? 
And the debug log (add -debug) of the failed cmdlets is also needed.
Please hide any credential in script and log.

**Comment by bikramgcnz** [comment] 2018-07-17 02:38
this is what i am doing https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-powershell :)

**Comment by blueww** [comment] 2018-07-17 03:01
@bikramgcnz 

Could you:
1. show debug log (add -debug) of the failed cmdlets "New-AzureStorageContainer". 
2. Run "$Error[0].Exception.ToString()" just after the failed cmdlet, and give output
3. Give the version of AzureRm.Storage
4. Could you show the $ctx after run "$ctx = $storageAccount.Context", please hide any credential like key.
5. Do you meet the 403 error when run other cmdlet like "Get-AzureStorageContainer"?

**Comment by blueww** [comment] 2018-07-19 02:49
@grik001
Is your problem resolved? Let me know if need any futher help form us.

**Comment by grik001** [comment] 2018-07-19 06:47
Hi @blueww 

No, I still had the problem. To go around it I just queried the API directly to get the list of containers. Sorry for not being able to supply the tokens you requested but I was wasting to much time trying to figure out how I can output these in VSTS.

As for replicating it:

Create a PS Task with inline script using the below script, all requests kept returning Forbidden. I regenerated the Token multiple just to be sure it was not the issue, I had it set with full permissions and it still kept failing: 

$ctx = New-AzureStorageContext -StorageAccountName "coditstgweinvictusstore" -SasToken ""
$containers = Get-AzureStorageContainer -Context $ctx

**Comment by blueww** [comment] 2018-07-19 06:56
@grik001 

From the script you provided, I only see how you use the sas token, but it can't help much on the issue investigate.
Please provide following information for further investigate:
1. Debug Log get by add -Debug parameter
2. Run "$Error[0].Exception.ToString()" just after the failed cmdlet, and give output
3. The running time (UTC) and account name (must have at least one of 2 or 3)
4. The "Azure.Storage" module version. Repro the issue and run ”Get-Module -Name Azure.Storage“

**Comment by grik001** [comment] 2018-07-19 07:01
I cannot test this now, as for the UTC I was creating Token with -1yr and lasting +1yr. Also this was working locally, I was literally copy and pasting the code. 

I was also doing Get-Module ... but it was not outputting anything. I will test this in the coming days and let you know. Feel free to close this comment if you feel it is not an issue.

**Comment by blueww** [comment] 2018-07-20 09:18
@grik001 
If you can't share the debug log, could you give the storage account name and the failed cmdlet running time (UTC), I might can also find the server log.

**Comment by blueww** [comment] 2018-07-27 06:39
@grik001 , @bikramgcnz 
Do you still meet the issue? 
Can you provide the necessary information for the trouble shooting?


I will close the issue now, as not receive you message for 1 week.
Feel free to re-open it if you have further questions or need my further support on this.

**Closed by blueww** 2018-07-27 06:39 UTC
Labels: Storage

**Comment by johnstaveley** [comment] 2019-05-21 12:38
I am having this issue when making requests using Azure DevOps in West Europe region. Is this the cause? https://alexandrebrisebois.wordpress.com/2013/04/23/are-you-getting-a-403-forbidden-from-windows-azure-storage-services/

**Comment by blueww** [comment] 2019-05-22 01:53
@johnstaveley 
Thanks for provide the information. Client and Server out of sync can get the 403 error.
Have your issue been resolved by make the client and server sync on time?

**Comment by johnstaveley** [comment] 2019-05-22 03:39
Hi, no, because the client is Azure DevOps. This resolved itself after 4 hours fighting with it and I didn't have to do anything...

**Comment by johnstaveley** [comment] 2019-05-22 07:03
This morning it is back again. This started to occur when I linked the blob storage to a VNET. The error occurs on this command:
if (((Get-AzureStorageContainer -Context $vNetStorageContext) | Where-Object { $_.Name -eq $containerName }) -ne $null) { 
However before this is execute I remove the security from blob storage and replace after all work is done.
Update-AzureRmStorageAccountNetworkRuleSet -ResourceGroupName $resourceGroupName -Name $vNetStorageAccountName -DefaultAction Allow
I have also tried it starting without the storage attached to a VNet however it demonstrates the same effect. In both cases the blob storage is acting as if the security was in place.

**Comment by blueww** [comment] 2019-05-22 07:56
@johnstaveley 
Please make sure set networkrule and Get-AzureStorageContainer point to same storage account, and you might need wait for a while after set networkrule set to make it works.

If the issue still repro:
Could you get a fiddler network trace of the issue (include set networkrule, and Get-AzureStorageContainer), and send to Weiwei@microsoft.com? (hide any credential)
Or you can share the storage account name and issue occur time, then I can look into server log to investigate it.

**Comment by johnstaveley** [comment] 2019-05-22 08:07
Hi. I only get this from AzureDevops. Works fine locally. I am not sure I can do a trace inside Azure Devops. I will email you the storage account name

**Comment by MarkAtAgilliance** [comment] 2020-07-03 21:22
Was this ever resolved?  I am seeing similar random failures from dev ops and no problems from my PC.
I am using MSI from a build server and retrieving the storage account key to use in the context.
Is this a time lag between granting RBAC to the container and that same process being able to list it?

**Comment by blueww** [comment] 2020-07-06 02:43
@MarkAtAgilliance 

The before issue can be caused by the time lag between server and client.
Sometime is can self recovered.

If you still can't get it self recovered, would you please give: 
1. the request ID (Get by Run "$Error[0].Exception.ToString()" just after the failed cmdlet)
Or
2. The storage account name and the time the issue repro (accurate UTC time)

And I can look into server log and investigate it.
