### ISSUE TITLE
Tag value containing date as string is converted for image versions

### ISSUE THREAD

**Issue by NecroFilja** [Azure/azure-powershell#13578] opened 2020-11-24 17:06 UTC
Hello,

To mark related resources we add special tag "created" containing date as string value, for example "2020-12-14T06:08:28Z".
When querying different resources we receive the same tag value set as different value, so we could not match them.
For example for image versions:
$image = Get-AzGalleryImageVersion  -Name "image-version-name"
$image.Tags
shows
created 12/14/2020 06:08:28

for keyvaults:
$keyvault = Get-AzKeyVault  -VaultName "vault-name"
$keyvault.Tags
created                        2020-12-14T06:08:28Z

I expect to have raw value set in both cases

**Comment by dingmeng-xue** [comment] 2020-11-25 05:11
@NecroFilja , thanks for your question. The data format should follow UTC. Could you share the debug message when you execute `$image = Get-AzGalleryImageVersion -Name "image-version-name"`? You can enable it via `$DebugPreference="Continue"`.

**Comment by NecroFilja** [comment] 2020-11-25 08:03
Hello,

here is truncated debug message (only body), please let  us know if you need more info. I cleanup all personal ids. Not depending on the date format (as you mentioned UTC) I would expect tags should be processed the same way for both entities (image version and key vault)? I.e. to be consistent.

```
Body:
{
  "name": "name",
  "id": "id",
  "type": "Microsoft.Compute/galleries/images/versions",
  "location": "westeurope",
  "tags": {
    **"created": "2020-11-14T05:09:18Z",**
    "task": "image deployment",
  },
  "properties": {
    "publishingProfile": {
      "targetRegions": [
        {
          "name": "West Europe",
          "regionalReplicaCount": 1,
          "storageAccountType": "Standard_LRS"
        },
        {
          "name": "West US",
          "regionalReplicaCount": 1,
          "storageAccountType": "Standard_LRS"
        }
      ],
      "replicaCount": 1,
      "excludeFromLatest": false,
      "publishedDate": "2020-11-14T06:47:54.6612741+01:00",
      "storageAccountType": "Standard_LRS"
    },
    "storageProfile": {
      "source": {
        "id": "ID"
      },
      "osDiskImage": {
        "sizeInGB": 127,
        "hostCaching": "ReadWrite",
        "source": {}
      }
    },
    "provisioningState": "Succeeded"
  }
}
```

**Comment by NecroFilja** [comment] 2020-11-25 10:30
looks like related to powershell 7 changed json conversion behaviour. But anyway I expect to entities have the same logic.
https://stackoverflow.com/questions/62896786/how-to-stop-powershell-7-convertfrom-json-reformatting-timestamps

**Comment by axayjo** [comment] 2020-12-01 08:42
Looking into it.

**Comment by Drewm3** [comment] 2020-12-09 21:33
@NecroFilja, I do not believe the tags values are being processed by either the image or key vault resource providers. Instead tags are handled by the general Azure Resource Manager layer of the stack. 

To help identify what is happening here, could you run your code that tags each of these resources with the create date, and then view the resulting resource tags in either the portal tags experience to see if the tags have different formatting. If the formatting is different in the portal, then the code setting the tag is not exactly the same. However if the tags are the same in the portal, but then different on a powerShell GET operation on the two resources, then please share what you see in the portal and what you see on the get response from each cmdlet.

**Comment by olayemio** [comment] 2020-12-10 19:22
@Drewm3 I compared Portal, CLI, REST and PowerShell for image version, VM, and key vault. Portal, CLI, and REST show the raw date for all three resources. PowerShell shows the formatted date for image version and VM while showing the raw date for key vault.

**Comment by Drewm3** [comment] 2021-01-07 20:01
@jaylabell, could you please work with the Compute Platform PowerShell team to debug we are translating the tag as a date. I believe the expected behavior is to treat tags as raw strings.

**Comment by Drewm3** [comment] 2021-01-15 21:24
We have confirmed that this is a bug and we will update this issue when the estimated time for it to be available is known.

**Comment by grizzlytheodore** [comment] 2021-04-26 20:01
It is indeed an issue at the PowerShell level. Below output shows that the API output shows the correct format: "created": "2020-11-14T05:09:18Z"

Then PowerShell output is formatted differently: {"created":"11/14/2020 05:09:18"}

Body:
{
  "value": [
    {
      "name": "1.0.1",
      "id": "/subscriptions//resourceGroups/RGforSDKtestResources/providers/Microsoft.Compute/galleries/gallerysdktest/images/ImageForTest/versions/1.0.1",
      "type": "Microsoft.Compute/galleries/images/versions",
      "location": "eastus2",
      "tags": {
        "created": "2020-11-14T05:09:18Z"
      },
      "properties": {
        "publishingProfile": {
          "targetRegions": [
            {
              "name": "East US 2",
              "regionalReplicaCount": 1,
              "storageAccountType": "Standard_LRS"
            }
          ],
          "replicaCount": 1,
          "excludeFromLatest": false,
          "publishedDate": "2021-04-26T15:47:20.10745-04:00",
          "storageAccountType": "Standard_LRS"
        },
        "storageProfile": {
          "osDiskImage": {
            "sizeInGB": 4,
            "hostCaching": "None",
            "source": {
              "id": "/subscriptions//resourceGroups/RGFORSDKTESTRESOURCES/providers/Microsoft.Compute/snapshots/DataDiskforImage"
            }
          }
        },
        "provisioningState": "Creating"
      }
    }
  ]
}




ResourceGroupName        : RGforSDKtestResources
PublishingProfile        :
  TargetRegions[0]       :
    Name                 : East US 2
    RegionalReplicaCount : 1
    StorageAccountType   : Standard_LRS
  ReplicaCount           : 1
  ExcludeFromLatest      : False
  PublishedDate          : 4/26/2021 7:47:20 PM
  StorageAccountType     : Standard_LRS
ProvisioningState        : Creating
StorageProfile           :
  OsDiskImage            :
    SizeInGB             : 4
    HostCaching          : None
    Source               :
      Id                 : /subscriptions//resourceGroups/RGFORSDKTESTRESOURCES/pro
viders/Microsoft.Compute/snapshots/DataDiskforImage
Id                       : /subscriptions//resourceGroups/RGforSDKtestResources/pro
viders/Microsoft.Compute/galleries/gallerysdktest/images/ImageForTest/versions/1.0.1
Name                     : 1.0.1
Type                     : Microsoft.Compute/galleries/images/versions
Location                 : eastus2
Tags                     : {"created":"11/14/2020 05:09:18"}

**Comment by grizzlytheodore** [comment] 2021-05-03 21:59
questioning whether this is a bug. This happens for all resources, not just image version.       @Drewm3  @jaylabell

**Comment by grizzlytheodore** [comment] 2021-05-06 19:16
this is a compute wide bug. It is happening at the sdk level. When it deserializes the HTTP response, the [deserialization configuration](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/compute/Microsoft.Azure.Management.Compute/src/Generated/ComputeManagementClient.cs#L585) is set to [DateParseHandling = DateTime](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_DateParseHandling.htm) which converts Date formatted strings, e.g. "\/Date(1198908717056)\/" and "2012-03-21T05:40Z", are parsed to DateTime.  This can be solved by changing the configuration to 'none', but it gets overwritten when sdk is generated from autorest. Also, it may change behavior anywhere in the HTTP response not just tags

**Comment by grizzlytheodore** [comment] 2021-05-06 21:23
the behavior with compute is consistent with storage and network

**Comment by Drewm3** [comment] 2021-05-06 21:27
After discussing with @grizzlytheodore, we have agreed that this isn't a compute bug per se, but instead the required behavior in the SDKs is not specifically defined through a common specification. I am reluctant to change any parsing if the issue is not a bug to a defined standard and if the behavior is consistent with both Azure Storage and Azure Networking, then I am much less willing to make this change.

So, I am going to close this one as effectively "By Design"

**Closed by Drewm3** 2021-05-06 21:27 UTC
Labels: Compute - Images, Service Attention, bug, customer-reported
