### ISSUE TITLE
Start-AzureRmHDInsightJob won't accept query with quotes

### ISSUE THREAD

**Issue by CaryJ** [Azure/azure-powershell#2080] opened 2016-04-11 21:12 UTC
The following query string worked with Start-AzureHDInsightJob.

```
$Query = "
 CREATE EXTERNAL TABLE IF NOT EXISTS TestStudent
  (
   id string,
   Name string
  )
  STORED BY 'com.mongodb.hadoop.hive.MongoStorageHandler'
  WITH SERDEPROPERTIES( 'mongo.columns.mapping' = '{""id"":""_id"",""Name"":""Name""}' )
  TBLPROPERTIES( 'mongo.uri' = 'mongodb://x:y@z' );
 "
```

When I try to use it with Start-AzureRmHDInsightJob I get the exception

`Start-AzureRmHDInsightJob : {"error":"Passed in parameter is incorrectly quoted: ..."}
`

I'm attempting to call it now as follows:

```
$hiveJob = New-AzureRmHDInsightHiveJobDefinition -JobName $Name -Query $Query -RunAsFileJob |
    Start-AzureRmHDInsightJob -ClusterName $ClusterName -HttpCredential $HDcredential
```

**Comment by markcowl** [comment] 2016-04-15 21:51
@shefaliv can you take a look.

**Comment by shefaliv** [comment] 2016-06-21 18:52
@pattipaka

**Comment by CaryJ** [comment] 2016-10-25 16:12
I see that the documentation for the older SM HDInsight cmdlets, such as Start-AzureHDInsightJob, are now showing that they will be removed in January.  I hope you will have this issue fixed by then, or we may be stuck!  It's been 6 months with no progress on it.

**Comment by pattipaka** [comment] 2016-10-28 23:05
@CaryJ Do you still this issue? I am able to run the command with out issue. Here is the script which works fine for me

$Query = "
 CREATE EXTERNAL TABLE IF NOT EXISTS TestStudent
  (
   id string,
   Name string
  )
  STORED BY 'com.mongodb.hadoop.hive.MongoStorageHandler'
  WITH SERDEPROPERTIES( 'mongo.columns.mapping' = '{""id"":""_id"",""Name"":""Name""}' )
  TBLPROPERTIES( 'mongo.uri' = 'mongodb://x:y@z' );
 "

#Create an HDInsight Hive job definition
$hiveJobDefinition = New-AzureRmHDInsightHiveJobDefinition -Query $Query 

$clusterName = "YourClusterName"
$creds=Get-Credential

#Submit the job to the cluster
Write-Host "Start the Hive job..." -ForegroundColor Green
$hiveJob = Start-AzureRmHDInsightJob -ClusterName $clusterName -JobDefinition $hiveJobDefinition -ClusterCredential $creds

**Comment by CaryJ** [comment] 2016-11-01 16:32
I am still getting an error:
`Start-AzureRmHDInsightJob : {"error":"Passed in parameter is incorrectly quoted: \nCREATE EXTERNAL TABLE IF NOT EXISTS
TestStudent\n(\nid string,\nName string\n)\nSTORED BY 'com.mongodb.hadoop.hive.MongoStorageHandler'\nWITH SERDEPROPERTIES(
'mongo.columns.mapping' = '{\"id\":\"_id\",\"Name\":\"Name\"}' )\nTBLPROPERTIES( 'mongo.uri' = 'mongodb://x:y@z' );\n"}
At line:1 char:12
+ $hiveJob = Start-AzureRmHDInsightJob -ClusterName $clusterName -JobDe ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Start-AzureRmHDInsightJob], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.HDInsight.StartAzureHDInsightJobCommand`

Maybe I need to update what version I'm using.

**Comment by CaryJ** [comment] 2016-11-01 17:26
I have the "Microsoft Azure PowerShell" from 9/28/2016 installed, which is the latest available from the Web Platform Installer.  I don't see a version number.

**Comment by CaryJ** [comment] 2016-11-02 20:23
Just installed today's update, 11/2/2016, and still get the same error.

**Comment by pattipaka** [comment] 2016-11-03 19:05
@CaryJ , I am able to run with out any issue on latest version as well. Can you please attach the ps file that you are trying? Also, what do you see when you run command $PSVersionTable.PSVersion

**Comment by CaryJ** [comment] 2016-11-03 21:35
I'm just running the commands you gave above, with a couple minor variations.  First, I need to select a different subscription that the cluster is under.  Second, I have to specify the resource group for the cluster - note that my cluster was not created using RM commands, so I had to retrieve the resource group that is listed in the Azure Portal.  I don't believe that should be a problem, however, as I am able to run simpler queries using these same commands.

`C:\ » $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14393  206

C:\ » $Query = "
CREATE EXTERNAL TABLE IF NOT EXISTS TestStudent
(
id string,
Name string
)
STORED BY 'com.mongodb.hadoop.hive.MongoStorageHandler'
WITH SERDEPROPERTIES( 'mongo.columns.mapping' = '{""id"":""_id"",""Name"":""Name""}' )
TBLPROPERTIES( 'mongo.uri' = 'mongodb://x:y@z' );
"
C:\ » add-azurermaccount


Environment           : AzureCloud
Account               : ...
TenantId              : ...
SubscriptionId        : ...
SubscriptionName      : ...
CurrentStorageAccount :



C:\ » $hiveJobDefinition = New-AzureRmHDInsightHiveJobDefinition -Query $Query
C:\ » $clusterName = "..."
C:\ » $creds=Get-Credential

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
C:\ » select-azurermsubscription -subscriptionname "..."


Environment           : AzureCloud
Account               : ...
TenantId              : ...
SubscriptionId        : ...
SubscriptionName      : ...
CurrentStorageAccount :



C:\ » $hiveJob = Start-AzureRmHDInsightJob -ClusterName $clusterName -JobDefinition $hiveJobDefinition -ClusterCredential $creds -resourcegroupname ...
Start-AzureRmHDInsightJob : {"error":"Passed in parameter is incorrectly quoted: \nCREATE EXTERNAL TABLE IF NOT EXISTS
TestStudent\n(\nid string,\nName string\n)\nSTORED BY 'com.mongodb.hadoop.hive.MongoStorageHandler'\nWITH SERDEPROPERTIES(
'mongo.columns.mapping' = '{\"id\":\"_id\",\"Name\":\"Name\"}' )\nTBLPROPERTIES( 'mongo.uri' = 'mongodb://x:y@z' );\n"}
At line:1 char:12
+ $hiveJob = Start-AzureRmHDInsightJob -ClusterName $clusterName -JobDe ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Start-AzureRmHDInsightJob], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.HDInsight.StartAzureHDInsightJobCommand

C:\ »
`

**Comment by pattipaka** [comment] 2016-11-03 22:28
@CaryJ can you please try running following command 

$hiveJob = Start-AzureRmHDInsightJob -ClusterName $clusterName -JobDefinition $hiveJobDefinition -ClusterCredential $creds 

Now you don't need to provide any extra details like resource group or storage account details.

**Comment by pattipaka** [comment] 2016-11-03 22:39
@CaryJ I have tried with -resourcegroupname and still couldn't reproduce.

PS C:\Users\x> $Query = "
>>  CREATE EXTERNAL TABLE IF NOT EXISTS TestStudent
>>   (
>>    id string,
>>    Name string
>>   )
>>   STORED BY 'com.mongodb.hadoop.hive.MongoStorageHandler'
>>   WITH SERDEPROPERTIES( 'mongo.columns.mapping' = '{""id"":""_id"",""Name"":""Name""}' )
>>   TBLPROPERTIES( 'mongo.uri' = 'mongodb://x:y@z' );
>>  "
PS C:\Users\x> $hiveJobDefinition = New-AzureRmHDInsightHiveJobDefinition -Query $Query
PS C:\Users\x> $creds=Get-Credential

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
PS C:\Users\x> $hiveJob = Start-AzureRmHDInsightJob -ClusterName $clusterName -JobDefinition $hiveJobDefinition -ClusterCredential $creds
PS C:\Users\x>

**Comment by CaryJ** [comment] 2016-11-03 23:50
You're right...I tried it before without -resourcegroupname and it didn't work.  I assumed it was because my cluster wasn't an RM cluster.  But, I just tried it again and I can do a simple query without that parameter, though I still get the same error with the above query.

**Comment by pattipaka** [comment] 2016-11-04 00:44
@CaryJ, As the issue repros only in your environment, can you please help narrow down the issue. I want to see at exactly what part of the string is creating issue for you. Can you start with small string like 

$Query = "
CREATE EXTERNAL TABLE IF NOT EXISTS TestStudent
"
and keep add more text and point me where do you start seeing this issue?

**Comment by CaryJ** [comment] 2016-11-04 05:02
The bad line is as expected with all the quotes:
`WITH SERDEPROPERTIES( 'mongo.columns.mapping' = '{""id"":""_id"",""Name"":""Name""}' )`

So, I've tried some simpler queries.  This should work, and query for data with only a " character, but yields the same error:
`$query="select * from TestStudent where name = '""'"`

**Comment by pattipaka** [comment] 2016-11-07 20:02
@markcowl, this seems to be a generic powershell environment issue. Looks like only @CaryJ can reproduce the issue. This seems to be related to handling quotes rather than HDInsight specific issue. Currently we are reading query as

        [Parameter(HelpMessage = "The query to run in the jobDetails.")]
        public string Query
        {
            get { return job.Query; }
            set { job.Query = value; }
        }

Can you please loop in relevant teams to provide suggestion if we need to handle this better?

**Comment by CaryJ** [comment] 2016-11-07 22:24
Note that I originally said this query works with the old `Start-AzureHDInsightJob` command.  Let me refine that to say we also use `-RunAsFileJob` (`New-AzureHDInsightHiveJobDefinition -RunAsFileJob`).  We attempted to try `New-AzureRmHDInsightHiveJobDefinition -RunAsFileJob`, but the `-RunAsFileJob` parameter doesn't seem to make any difference in this case.

**Comment by markcowl** [comment] 2016-11-12 00:24
Can you provide debug traces for this scenario, you can do this by setting:

```
$DebugPreference="Continue"
```
before running your the cmdlet or script

**Comment by CaryJ** [comment] 2016-11-12 00:45
Is there a more secure place I can upload the output to?

**Comment by pattipaka** [comment] 2016-11-14 18:20
@CaryJ, can you please provide details of the cluster that you are trying to execute the query. Is it Linux or windows clusters? What is the version of the cluster? 

I can see same body content for my runs and my Linux 3.5 cluster doesn't show up any issue.


DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://xxxxx.azurehdinsight.net/templeton/v1/hive?user.name=admin

Headers:
accept                        : application/json
useragent                     : HDInsight Job SDK .Net 2.0.3.0
User-Agent                    : HDInsight,Job,SDK,.Net,2.0.3.0

Body:
execute=select%20*%20from%20TestStudent%20where%20name%20%3D%20'%22'&statusdir=2016-11-14T18-11-17-af663e1c-ca22-4a43-ab81-d2d3a3c09da1

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
x-ms-hdi-active               : 10.0.0.19
Set-Cookie                    : hadoop.auth="u=admin&p=xxx&t=xxx&e=xxxx&s=xxxxx"; Path=/; HttpOnly; path=/; secure
Server                        : Microsoft-IIS/8.5
X-Powered-By                  : ARR/3.0,ASP.NET
Date                          : Mon, 14 Nov 2016 18:11:27 GMT

Body:
{
  "id": "job_1478954815679_0003"
}

**Comment by CaryJ** [comment] 2016-11-14 18:34
It is a Windows HDInsight cluster, v3.2.

**Comment by pattipaka** [comment] 2016-11-14 19:31
@CaryJ, This is much older cluster. Can you please try out Linux 3.5 cluster and see if you still have an issue?

**Comment by CaryJ** [comment] 2016-11-17 20:05
I tried it on both the most recent Windows version (Hadoop  on Windows (HDI 3.3.0.1093)) and on Linux ( Hadoop  on Linux (HDI 3.5.1000.0)).  The Windows version still fails, while the Linux version does work.
Note that using a Linux cluster is not an option for us, as we have .Net based map-reduce jobs we run on the cluster.

**Comment by CaryJ** [comment] 2016-11-17 20:55
I just did some more research, and discovered that more recent versions of HDI for Windows will not be supported.
If you want to close this issue as something you won't fix, I'm ok with that.  We have already been investigating other options besides Hadoop, anyway.

**Comment by cormacpayne** [comment] 2018-03-27 22:27
Closing.

**Closed by cormacpayne** 2018-03-27 22:27 UTC
Labels: HDInsight
