### ISSUE TITLE
New-AzureRmVM stalls when called from (gui) event

### ISSUE THREAD

**Issue by keeshuizer** [Azure/azure-powershell#3376] opened 2017-01-11 08:02 UTC
### Cmdlet(s)
New-AzureRmVM

### PowerShell Version
5.1.14393.576

### OS Version
10.0.14393.576

### Description
After running into an issue with storage related cmdlets which are run from a PowerShell GUI script (issue 3205 : https://github.com/Azure/azure-powershell/issues/3205) I'm using an ad-hoc build which includes the fix for this issue.  

I just now ran into a problem (the same problem?) with another cmdlet:

The cmdlet is 'New-AzureRmVM'.

I'm creating a new VM using an existing vhd file, when i run the commands in a normal PowerShell session the New-AzureRmVM exits after a minute or so with the following:

PS N:> New-AzureRmVM -ResourceGroupName $SelectedTestEnv -Location $location -VM $vm -Verbose
VERBOSE: Performing the operation "New" on target "app-keten01".

RequestId IsSuccessStatusCode StatusCode ReasonPhrase

                     True         OK OK
When i run the exact same code from my PowerShell GUI the creation of the VM is initiated (and finishes according to the Azure portal), but the command never finishes, it just hangs after the 'Performing the operation 'New' line.

### Script/Steps for Reproduction
Execute New-AzureRmVM from a GUI event

**Comment by cormacpayne** [comment] 2017-01-17 22:23
@singhkays Hey Kay, would you mind taking a look at this issue? It has been branch off from issue https://github.com/Azure/azure-powershell/issues/3205

**Comment by keeshuizer** [comment] 2017-01-25 08:39
Any news/progress on this issue? I want to continue working on my script/gui but this little bug doesn't make that very easy :-(

**Comment by singhkays** [comment] 2017-01-31 22:28
@hyonholee Can you take a look if this is same as #3205 ? 

@twitchax In #3205 you mentioned. 

> twitchax commented on Dec 28, 2016
> @keeshuizer, as @blueww mentioned, we understand that thread-safety is a concern, but we would prefer to do it right and make all of Azure PowerShell thread-safe. 

Since this seems like the same issue, has there been any update on making PS thread safe?

**Comment by twitchax** [comment] 2017-01-31 23:43
@shahabhijeet, can we engage compute to see if this is the same issue that storage has?  Or, is this possibly caused by our underlying lack of support for concurrency?

**Comment by cormacpayne** [comment] 2018-03-28 00:38
This appears to have been fixed. Closing.

**Closed by cormacpayne** 2018-03-28 00:38 UTC
Labels: Compute
