### ISSUE TITLE
Get-AzureKeyVaultSecret ignoring Name parameter

### ISSUE THREAD

**Issue by iricigor** [Azure/azure-powershell#4740] opened 2017-10-09 07:32 UTC
### Cmdlet(s)
Get-AzureKeyVaultSecret

### PowerShell Version
PSVersion 5.1.15063.632

### Module Version
4.4.0      AzureRM
3.4.0      AzureRM.KeyVault 

### OS Version
Windows 10, BuildVersion                   10.0.15063.632

### Description
When cmdlet is executed with two parameters VaultName and Name, it is properly resolving to the parameter set **BySecretName**.
But, when those two parameters are passed via pipeline (both support _ValueFromPipelineByPropertyName_), then parameter Name is ignored. Parameter set is identified as **ByVaultName**, and all secrets are returned, not just requested one.

### Debug Output
```PowerShell
Get-AzureKeyVaultSecret -VaultName a -Name b -Debug
DEBUG: 9:25:36 AM - GetAzureKeyVaultSecret begin processing with ParameterSet 'BySecretName'.
. . .

[pscustomobject]@{VaultName='a';Name='b'} | Get-AzureKeyVaultSecret -Debug
DEBUG: 9:25:52 AM - GetAzureKeyVaultSecret begin processing with ParameterSet 'ByVaultName'.
. . . 

```
### Script/Steps for Reproduction
As in Debug output. You do not need actually to have any kay vaults to simulate the issue.

### P.S.
I am not sure if this is a mistake in this cmdlet, or it is generally PowerShell parsing parameter sets issue impacting this cmdlet.

**Comment by cormacpayne** [comment] 2017-10-09 17:16
@iricigor thanks for opening up this issue! After a little investigation, this looks to be a PowerShell issue with how they handle piping to a cmdlet with a default parameter set.

I created a test cmdlet with the following attributes:

```powershell
function Test-Cmdlet
{
    [CmdletBinding(DefaultParameterSetName = "FooTemp")]
    Param(
        [Parameter(Mandatory = $true, Position = 0, ValueFromPipelineByPropertyName = $true, ParameterSetName = "FooTemp")]
        [Parameter(Mandatory = $true, Position = 0, ValueFromPipelineByPropertyName = $true, ParameterSetName = "FooBar")]
        $Foo,

        [Parameter(Mandatory = $true, Position = 1, ValueFromPipelineByPropertyName = $true, ParameterSetName = "FooBar")]
        $Bar,

        [Parameter(Mandatory = $true, Position = 2, ValueFromPipelineByPropertyName = $true, ParameterSetName = "FooTemp")]
        $Temp
    )

    $PSCmdlet.ParameterSetName
    "Foo = $Foo"
    "Bar = $Bar"
    "Temp= $Temp"
}
```

Creating a hashtable with the parameters necessary for the `FooBar` parameter set and piping that to this cmdlet will fail:

```powershell
[PSCustomObject]@{Foo = "A"; Bar = "B"} | Test-Cmdlet

Test-Cmdlet : The input object cannot be bound because it did not contain the information required to bind all mandatory parameters:  Temp
At C:\Users\corm\Documents\TestCmdlet.ps1:28 char:25
+ [PSCustomObject]$hash | Test-Cmdlet
+                         ~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (@{Bar=B; Foo=A}:PSObject) [Test-Cmdlet], ParameterBindingException
    + FullyQualifiedErrorId : InputObjectMissingMandatory,Test-Cmdlet
```

However, when I remove the `DefaultParameterSet` from the cmdlet, it works as intended:

```powershell
[PSCustomObject]@{Foo = "A"; Bar = "B"} | Test-Cmdlet

FooBar
Foo = A
Bar = B
Temp =
```

Since the `Get-AzureKeyVaultSecret` cmdlet has a `DefaultParameterSet` of `ByVaultName`, it would make sense that this cmdlet keeps defaulting to that parameter set no matter what in the piping scenario. Let me talk to a few people on the PowerShell Core team and see if this is a bug (which I would like to think it is 😄 ).

**Comment by cormacpayne** [comment] 2017-10-09 22:58
I have opened an issue in the `PowerShell` repository here: https://github.com/PowerShell/PowerShell/issues/5071

**Comment by iricigor** [comment] 2017-10-10 08:29
@cormacpayne Thanks for comments and reporting it in PowerShell repo. I figured out the similar. Yet, some cmdlets are handling piping multiple values properly, as visible in the example below. More or less, it would be expected for related commands to support piping to each other. I would expect this to work: `Get-AzureKeyVaultSecret -VaultName a | Get-AzureKeyVaultSecret` (reads all secrets and pipes them for reading details), but it's not.

Example of cmdlets with proper piping:
```PowerShell
$Loc = 'westus'
$Pub = 'MicrosoftWindows'
Get-AzureRmVMImagePublisher -Location $Loc | ? PublisherName -Match $Pub | Get-AzureRmVMImage | Get-AzureRmVMImageSku
```
_* Filtering added just for speeding up example._

**Comment by cormacpayne** [comment] 2017-10-17 22:30
@pomortaz @dragav would one of you be able to take a look at the most recent comment from @iricigor regarding the broken piping scenarios in the KeyVault cmdlets?

**Comment by dragav** [comment] 2017-10-18 22:14
Trying to slot this in for November.

**Comment by maddieclayton** [comment] 2018-03-21 18:24
@iricigor I am looking at the piping scenarios now, and I am curious about this one:
```
Get-AzureKeyVaultSecret -VaultName a | Get-AzureKeyVaultSecret
```
What does this accomplish that ```Get-AzureKeyVaultSecret -VaultName a ``` does not?  I am looking to enable Get-AzureRmKeyVault | Get-AzureKeyVaultSecret, but would be interested to see what other piping scenarios you think are useful.

**Comment by iricigor** [comment] 2018-03-22 12:32
Hi Maddie,

`Get-AzureKeyVaultSecret -VaultName a` returns an array of **SecretIdentityItem** objects, while piping scenario should return array of **Secret** objects. In API terminology the first command does simple `List Objects`, while the second one does `Get Object(s)` (one by one).

The main difference between these two is with a **SecretValue** property. Listing command is not returning a secret value, while the piping scenario should.

Bottom line is that in [the commandlet Get-AzureKeyVaultSecret code](https://github.com/Azure/azure-powershell/blob/master/src/ResourceManager/KeyVault/Commands.KeyVault/Commands/GetAzureKeyVaultSecret.cs), it is defined in a Parameter set named **BySecretNameParameterSet** to accept parameter Name from pipeline by name (`ValueFromPipelineByPropertyName = true`), but it is not working as designed. 

I was expecting, if I pass both VaultName and Secret name via pipeline, it will return me only secret that I ask for. However, it just lists all secrets.
```PowerShell
[pscustomobject]@{VaultName='a';Name='b'} | Get-AzureKeyVaultSecret -Debug
```
As Cormac demonstrated above, that part is not a fault of this cmdlet, but generally PowerShell. It can be avoided though if `DefaultParameterSet` **is not** used.

Other Azure commandlets are working fine with these scenarious. The example below, from [Compute-Images group](https://github.com/Azure/azure-powershell/tree/master/src/ResourceManager/Compute/Stack/Commands.Compute/Images) are accepting parameters from pipeline as expected:
```PowerShell
$Loc = 'westus'
$Pub = 'MicrosoftWindows'
Get-AzureRmVMImagePublisher -Location $Loc |
 ? PublisherName -Match $Pub |
 Get-AzureRmVMImageOffer |
 Get-AzureRmVMImageSku |
 Get-AzureRmVMImage
```

Or, to make it equivalent example as Get-AzureKeyVaultSecret not working one 
```PowerShell
[pscustomobject]@{Offer='Windows-10';PublisherName='MicrosoftWindowsDesktop';Location='westus'} | Get-AzureRmVMImageOffer
```

So, it seems piping can work as planned.

**Comment by maddieclayton** [comment] 2018-03-23 00:21
@dragav @RandalliLama Do we want to enable this scenario for listing secrets (including secretvalue) by piping Get-AzureRmKeyVault -VaultName <VaultName> | Get-AzureRmKeyVault?  From previous conversations, it seems like we would not want to enable this scenario for the same reason that we don't include the secretvalue when running Get-AzureRmKeyVault -VaultName <VaultName>.

**Comment by dragav** [comment] 2018-03-23 00:37
I understand the need for consistency, but this would effectively trivialize mass-exporting of all the secrets in a vault, and so I am against this change; I just don't see the scenario, aside from the aforementioned wish for consistency. 

For KeyVault, the SecretGet permission is highly privileged, whereas SecretList is non-disclosing. The difference in return types (and the current behavior of the cmdlet) is therefore intentional, and should remain so.

**Comment by maddieclayton** [comment] 2018-03-23 00:42
I will close this issue as will not fix.  The breaking change release will also remove ValueFromPipelineByPropertyName from VaultName and Name, and add piping by InputObject/ResourceId for Vault.

**Closed by maddieclayton** 2018-03-23 00:42 UTC
Labels: KeyVault, More Info

**Comment by iricigor** [comment] 2018-03-23 05:27
I think reason for closing is wrong. Briefly, you have not answered why passing vault name and exactly one secret name to this command should return all secrets list?
```PowerShell
[pscustomobject]@{VaultName='a';Name='b'} | Get-AzureKeyVaultSecret
```

Difference in return types is understandable and also excluding slow operation from default scenario is OK. Parameter **Name** is accepting **single string** only and it should stay like that exactly for the reasons mentioned above. Scenario you mentioned should fail as commandlet is not accepting array.

But I reported different problem: if I pass exactly one secret name, I expected to get secret, not a list of all secrets. My use case is displaying to user all secrets and if filter field matches only one secret, I want to get it.

This would be natural PowerShell and documented in Get-AzureKeyVaultSecret (both parameters accept value from pipeline)

```PowerShell
$SecretList = Get-AzureKeyVaultSecret -VaultName a | ? Name -like $Filter
if ($SecretList.Count -eq 1) {
     $Secret = $SecretList[0] | Get-AzureKeyVaultSecret 
}
```


But, that above is not working, so instead I have to use
```PowerShell
$Secret = Get-AzureKeyVaultSecret -VaultName ($SecretList[0].VaultName) -Name ($SecretList[0].Name)
```

And about trivial export, nothing is preventing users to do a simple loop.
```PowerShell
Get-AzureKeyVaultSecret a | % {Get-AzureKeyVaultSecret a $_.Name}
```

**Comment by maddieclayton** [comment] 2018-03-23 17:44
Unfortunately the failure of ```[pscustomobject]@{VaultName='a';Name='b'} | Get-AzureKeyVaultSecret``` is due to the way PowerShell selects parameter sets, and cannot be easily fixed.  You could likely use splatting to get the correct result.

In the future, ValueFromPipelineByPropertyName will be removed from both parameters, so this scenario will explicitly not be supported.
