### ISSUE TITLE
Error adding action group to Add-AzMetricAlertRuleV2

### ISSUE THREAD

**Issue by royarin** [Azure/azure-powershell#9259] opened 2019-05-21 09:59 UTC
When creating a Azure Monitor metric alert rule using Add-AzMetricAlertRuleV2, the cmdlet fails when trying to add an action group using the -ActionGroup parameter.

Script

Add-AzMetricAlertRuleV2 -Name "App Service Plan CPU gt 70" `
    -ResourceGroupName $resourceGroupName `
    -TargetResourceScope "/subscriptions/$SubscriptionId/$resourceGroupName" `
    -TargetResourceType "Microsoft.Web/serverfarms" `
    -TargetResourceRegion $location `
    -Condition $cpuGt70 `
    -Severity 2 -WindowSize 0:15 -Frequency 0:5 `
    -ActionGroup $actionGroup

where $actionGroup is defined as

$actionGroup=Get-AzActionGroup -Name $actionGroupName -ResourceGroupName $resourceGroupName

Error:

Add-AzMetricAlertRuleV2 : Cannot bind parameter 'ActionGroup'. Cannot convert the "Microsoft.Azure.Commands.Insights.OutputClasses.PSActionGroupResource" value of type 
"Microsoft.Azure.Commands.Insights.OutputClasses.PSActionGroupResource" to type "Microsoft.Azure.Management.Monitor.Models.ActivityLogAlertActionGroup".

The documentation mentions that -ActionGroup should be output of New-AzActionGroup cmdlet. However, creating this in-memory object with the ID of an existing action group doesn't help. I am then getting the following error:

Add-AzMetricAlertRuleV2 : Exception type: ErrorResponseException, Message: Null/Empty, Code: Null, Status code:BadRequest, Reason phrase: Bad Request

**Comment by niander** [comment] 2019-05-21 15:57
@royarin Hi, Could you please fill the issue following this:



## Description



## Steps to reproduce

```powershell

```

## Environment data



```

```

## Module versions



```powershell

```

## Debug output



```

```

## Error output



```

```

**Comment by sureshpagidipati** [comment] 2019-06-04 17:11
I am too getting same error, basically the output type of value returned by either "Set-AzActionGroup" or 'get-AzActionGroup' is "Microsoft.Azure.Commands.Insights.OutputClasses.PSActionGroupResource" but for type of value of argument "-ActionGroup" of method Add-AzMetricAlertRuleV2  is "Microsoft.Azure.Management.Monitor.Models.ActivityLogAlertActionGroup[]" 

also method 'New-AzActionGroup' only lets to create webhook receiver not emails.

**Comment by sureshpagidipati** [comment] 2019-06-05 13:52
Hi @niander & @royarin ,
 I was able to find the fix for this issue (Az module version 2.2.0) after debugging I found that in method New-AzActionGroup it supposed to be resource id resulted from either "Set-AzActionGroup" or 'get-AzActionGroup'  as -ActionGroup outputvariable.Id but in documentation it says it can be either Id or Name of ActionGroup.

**Comment by royarin** [comment] 2019-06-05 14:32
True. I figured it out as well.
Also, I had to use the TargetResourceId and not the TargetResourceScope
Final code that worked for me:

`$actionGroup = Get-AzActionGroup -Name $actionGroupCGName -ResourceGroupName $resourceGroupName

$actionGroupId = New-AzActionGroup -ActionGroupId $actionGroup.Id

Add-AzMetricAlertRuleV2 -Name "App Service Plan CPU gt 70" 
-ResourceGroupName $resourceGroupName
-TargetResourceId $appServicePlan.Id 
-Condition $cpuGt70 
-Severity 2 -WindowSize 0:15 -Frequency 0:5 
-ActionGroup $actionGroupId`

**Comment by Cdoherty95** [comment] 2019-06-20 22:19
@royarin Can you list the commands that made $cpuGt70 and $appServicePlan.Id? I began with the same issue now I'm receiving this error:
`Add-AzMetricAlertRuleV2 : Exception type: ErrorResponseException, Message: Null/Empty, Code: Null, Status code:Conflict, Reason phrase: Conflict`

I am working with web/function apps so I just want to make sure I am making the -Condition parameter collection variable and the -TargetResourceId string variable correct.

To make the -Condition variable I copied the documentation:
`$condition = New-AzMetricAlertRuleV2Criteria -MetricName "Http5xx" -TimeAggregation Average -Operator GreaterThan -Threshold 5`

To make the -TargetResourceId variable I get the resource then pass $resource_Information.Id to the Add-AzMetricAlertRuleV2 cmdlet:
`$resource_Information = Get-AzResource -Name "test-app-99689" -ResourceGroupName "test-app-99689-rg" -ResourceType "Microsoft.Web/sites"`

In debug I can see that $resource_Information.Id = "/subscriptions/<subscriptionID>/resourceGroups/test-app-99689-rg/providers/Microsoft.Web/sites/test-app-99689"

**Comment by 45413** [comment] 2019-07-03 03:30
@Cdoherty95 I had this issue occur anytime I have invalid characters in the name parameter. For instance, If you use the `"DB Space Used > 85%"` it will fail, but `"DB Space Used gt 85"` works fine.

**Comment by Cdoherty95** [comment] 2019-07-24 22:00
Im not sure what I was doing wrong but I seemed to figure it out. Below is a working example of the function I wrote to create a new alert rule.

```powershell
function New-AlertRule ($target_resource_name, $target_resource_group_name, $target_resource_id,
    $metric_name, $alert_rule_aggregation_type, $alert_rule_severity, $alert_rule_operator,
    $alert_rule_threshold, $alert_rule_window_size, $alert_rule_evaluation_frequency, 
    $action_group_name, $action_group_resource_group_name) {
    
    <#
        .SYNOPSIS
            This function creates an alert rule based on the metric name passed in
        .DESCRIPTION
            This function will:

            1. Create an alert rule name by concatenating the resource name and metric
                NOTE: The alert rule name must be unique or it will update the existing alert rule
            2. Create an alert rule description
            3. Get an existing action group
            4. Create an action group in local memory using the existing action groups' ID
            5. Create a criteria object which will trigger the alert rule
            6. Create an alert rule in azure using all the gathered information 
        .PARAMETER target_resource_name
            This is the name of the resource we are going to create the alert rule on. This is only used
            to create the name and description for the alert rule
        .PARAMETER target_resource_group_name
            This is the name of the resource group which the resource is in
        .PARAMETER target_resource_id
            This is the ID of the resource
        .PARAMETER metric_name
            This is the Value of the metric name. Metric name values depend on the type of the resource.
            These values can be found using the Get-AzMetricDefinition cmdlet   
        .PARAMETER alert_rule_aggregation_type
            This defines how the data is collected to be compared to the threshold. This is defined in the
            metrics definition as the PrimaryAggregationType. Aggregation types can include:
            Total, Count, Sum, Average, Maximum, and Minimum depending on the metric
        .PARAMETER alert_rule_severity
            This defines the severity of the alert. Only integers 1-4 are allowed
        .PARAMETER alert_rule_operator
            This defines how the data is compared to the threshold. i.e GreaterThan, GreaterThanOrEqual
        .PARAMETER alert_rule_threshold
            This defines the threshold at which the alert will be triggered. The units which the threshold should 
            be given as depends on the metric. Example: Average response time might be expecting milliseconds or 
            seconds. This is defined by Azure and can be found using the Get-AzMetricDefinition cmdlet
        .PARAMETER alert_rule_window_size
            This defines the period to group the data points together
        .PARAMETER alert_rule_evaluation_frequency
            This defines the frequency the condition is evaluated
        .PARAMETER action_group_name
            This defines the action group to send the alert to
        .PARAMETER action_group_resource_group_name
            This defines the resource group the action group is in
        .EXAMPLE
            New-AlertRule -target_resource_name $targetResource.Name `
                -target_resource_group_name $targetResource.ResourceGroupName `
                -target_resource_id $targetResource.Id `
                -metric_name "Http5xx" `
                -alert_rule_aggregation_type "Total" `
                -alert_rule_severity 3 `
                -alert_rule_operator "GreaterThanOrEqual" `
                -alert_rule_threshold 1 `
                -alert_rule_window_size $windowSize `
                -alert_rule_evaluation_frequency $evaluationFrequency `
                -action_group_name "EmailMe" `
                -action_group_resource_group_name "actionGroup-rg"
    #>

    # Log to console
    Write-Host "`n`rCreating $metric_name Alert Rule on $target_resource_name..."
    
    # Name for the alert rule
    $alertRuleName = ($target_resource_name + " - " + $metric_name + " Issue")

    # Make a description for the alert rule
    $description = ("The resource " + $target_resource_name + " has exceeded the set threshold.")
    
    # Get the action group object
    $actionGroup = Get-AzActionGroup -Name $action_group_name `
        -ResourceGroupName $action_group_resource_group_name    
    
    # Create a new action group in local memory which will be associated to an existing action group in Azure
    $actionGroupId = New-AzActionGroup -ActionGroupId $actionGroup.Id

    # This creates the condition of the Metric Alert Rule to be pass into the Add-AzMetricAlertRuleV2 cmdlet
    $condition = New-AzMetricAlertRuleV2Criteria -MetricName $metric_name `
        -TimeAggregation $alert_rule_aggregation_type `
        -Operator $alert_rule_operator `
        -Threshold $alert_rule_threshold 

    # Create the metric alert rule for the target resource
    Add-AzMetricAlertRuleV2 -Name $alertRuleName `
        -ResourceGroupName $target_resource_group_name `
        -Severity $alert_rule_severity `
        -WindowSize $alert_rule_window_size `
        -Frequency $alert_rule_evaluation_frequency `
        -TargetResourceId $target_resource_id `
        -Description $description `
        -Condition $condition `
        -ActionGroup $actionGroupId `
        -Verbose -ErrorAction Stop
    
    # Log to console
    Write-Host "`n`rDone creating $metric_name Alert Rule on $target_resource_name."
}

# Get a resource object which you want to create an alert rule for
$targetResource = Get-AzResource -Name "resource123" -ResourceType "Microsoft.Web/sites"

# Alert Rule Window Size
$windowSize = New-TimeSpan -Minutes 1

# Alert Rule Evaluation Frequency
$evaluationFrequency = New-TimeSpan -Minutes 1

# Call our function to create an alert rule. When triggered it will send an event to the defined action group
New-AlertRule -target_resource_name $targetResource.Name `
    -target_resource_group_name $targetResource.ResourceGroupName `
    -target_resource_id $targetResource.Id `
    -metric_name "Http5xx" `
    -alert_rule_aggregation_type "Total" `
    -alert_rule_severity 3 `
    -alert_rule_operator "GreaterThanOrEqual" `
    -alert_rule_threshold 1 `
    -alert_rule_window_size $windowSize `
    -alert_rule_evaluation_frequency $evaluationFrequency `
    -action_group_name "EmailMe" `
    -action_group_resource_group_name "actionGroup-rg"
```

**Comment by Cdoherty95** [comment] 2019-08-06 02:06
@royarin @niander I think That should help

**Comment by dingmeng-xue** [comment] 2020-02-20 15:11
Hi All, thanks for your validation. Is the question still valid in Az 3.x? If no, this issue will be closed soon due to inactivity.

**Comment by dingmeng-xue** [comment] 2020-03-16 09:55
This issue is closed. If there is any further question, please report to us.

**Closed by dingmeng-xue** 2020-03-16 09:55 UTC
Labels: Monitor - Metrics, More Info :label:
