### ISSUE TITLE
Multitenant serviceprincipal fails to change context in Az.Accounts version 2.10.4

### ISSUE THREAD

**Issue by lassehastrup** [Azure/azure-powershell#20484] opened 2022-12-20 09:18 UTC
### Description

After Az.Accounts was updated to version 2.10.4 we can no longer change AzContext or generate a Access Token with a multi-tenant App registration.

Connect-AzAccount -TenantId (Tenant1 where the app registration is created) - this works OK.

Set-AzContext -TenantId (Tenant2 where the app registration is linked and registered as an Enterprise App) - We receive error.

Error: ##[error]The running command stopped because the preference variable "WarningPreference" or common parameter is set to Stop: Unable to acquire token for tenant 'XYZ' with error 'No certificate thumbprint or secret provided for the given service principal '***'.'

This is tested and worked in Az.Accounts version 2.10.0 - 2.10.3, and this is critical, as the way the import of Az.Accounts works is difficult to handle. Even though we specify an older version of 
AzurePowershell 
              azurePowerShellVersion: OtherVersion
              preferredAzurePowerShellVersion: 9.1.1 (tested with 8.3.0 and 9.1.0)

The Az will still import the latest version of Az.Accounts which has this error.

### Issue script & Debug output

```PowerShell
Connect-AzAccount -Tenant (Tenant1 where the app registration is created) -Credential $creds -ServicePrincipal- this works OK.

Set-AzContext -TenantId (Tenant2 where the app registration is registered as an Enterprise App) - We receive error.
```

### Environment data

```PowerShell
This is tested and working in Az.Accounts version 2.10.0 - 2.10.3
```

### Module versions

```PowerShell
Az.Accounts version 2.10.4
```

### Error output

```PowerShell
Error: ##[error]The running command stopped because the preference variable "WarningPreference" or common parameter is set to Stop: Unable to acquire token for tenant 'XYZ' with error 'No certificate thumbprint or secret provided for the given service principal '***'.'
```

**Comment by dingmeng-xue** [comment] 2022-12-20 12:25
Thanks for reporting. Could you share the exception stack after you hit the problem? You can get except stack via `$Error[0].Exception | fl -f *` .

**Comment by lassehastrup** [comment] 2022-12-20 14:17
ErrorRecord                 : The running command stopped because the preference variable "WarningPreference" or common parameter is set to Stop:     
                              Unable to acquire token for tenant 'XXXXXXX' with error 'No certificate thumbprint or 
                              secret provided for the given service principal 'XXXXX'.'
WasThrownFromThrowStatement : False
TargetSite                  : System.Collections.ObjectModel.Collection`1[System.Management.Automation.PSObject] 
                              Invoke(System.Collections.IEnumerable)
Message                     : The running command stopped because the preference variable "WarningPreference" or common parameter is set to Stop: 
                              Unable to acquire token for tenant 'XXXXXX' with error 'No certificate thumbprint or 
                              secret provided for the given service principal 'XXXXXXXXX'.'
Data                        : {[System.Management.Automation.Interpreter.InterpretedFrameInfo, 
                              System.Management.Automation.Interpreter.InterpretedFrameInfo[]]}
InnerException              : 
HelpLink                    : 
Source                      : System.Management.Automation
HResult                     : -2146233087
StackTrace                  :    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
                                 at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
                                 at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
                                 at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, 
                              PSDataCollection`1 output, PSInvocationSettings settings)
                                 at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 
                              output, PSInvocationSettings settings)
                                 at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, 
                              PSInvocationSettings settings)
                                 at System.Management.Automation.PowerShell.Invoke[T](IEnumerable input, IList`1 output, PSInvocationSettings 
                              settings)
                                 at System.Management.Automation.PowerShell.Invoke[T](IEnumerable input, PSInvocationSettings settings)
                                 at Microsoft.PowerShell.EditorServices.Services.PowerShell.Utility.PowerShellExtensions.InvokeAndClear[TResult](Powe
                              rShell pwsh, PSInvocationSettings invocationSettings) in 
                              D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Utility\PowerShellExtensions.cs:line 82
                                 at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousPowerShellTask`1.ExecuteNormally(Can
                              cellationToken cancellationToken) in 
                              D:\a\_work\1\s\src\PowerShellEditorServices\Services\PowerShell\Execution\SynchronousPowerShellTask.cs:line 187

**Comment by msJinLei** [comment] 2022-12-21 05:08
@lassehastrup 

Could you check the result of the following cmdlet?

```
PS C:\> Get-AzContext -ListAvailable

Name                                     Account             SubscriptionName    Environment         TenantId
----                                     -------             ----------------    -----------         --------
```
Please see whether all the items are valid?

**Comment by ReneRebsdorf** [comment] 2022-12-25 23:49
@msJinLei FYI it works consistently with 2.10.2, using the same service principal, @lassehastrup also mentions it working with 2.10.3

Easiest way to reproduce is to:
1. Create an App Registration in Tenant A as a Multi-Tenant App Reg
2. Onboard the app to Tenant B
3. Give the app reader permission on a subscription in tenant B
4. Connect using Connect-AzAccount -ServicePrincipal -Credentials $cred -TenantId $tenantBId

The error is reproducible on Linux, Windows, and MacOS.

This is experienced when using Azure DevOps Pipelines which will perform the Connect-AzAccount against 'our' TenantId

When I update to 2.10.4 and run Get-AzContext -ListAvailable I see subscriptions relating to both our tenant, as well as for clients.

Might be worth mentioning we see this even if we try to set context using only -TenantId $tenantId (providing no subscription specification).

When changing tenant we get the warning using Set-AzContext:
```text
'WARNING: Unable to acquire token for tenant 'X with error 'No certificate thumbprint or secret provided for the given service principal 'Y'.''
```
And using commands such as Get-AzResource will yield the error message: 
```text
Get-AzResource: Your Azure credentials have not been set up or have expired, please run Connect-AzAccount to set up your Azure credentials.
No certificate thumbprint or secret provided for the given service principal 'Y'.
```

Debug output from Set-AzContext -TenantID $clientTenantId -Debug
```text
DEBUG: 00:42:06 - SetAzureRMContextCommand begin processing with ParameterSet 'TenantNameOnly'.
DEBUG: 00:42:06 - using account id '823c2bdf-0bc2-4c93-b91d-e9a4bf7df1a8'...
DEBUG: 00:42:06 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].

Confirm
Targeting all subsequent cmdlets in this session at a different tenant
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):

DEBUG: 00:43:12 - Autosave setting from startup session: 'CurrentUser'
DEBUG: 00:43:12 - No autosave setting detected in environment variable 'AzContextAutoSave'.
DEBUG: 00:43:12 - Using Autosave scope 'CurrentUser'
WARNING: Unable to acquire token for tenant 'c905c127-525f-47a9-83f1-bec014f6d613' with error 'No certificate thumbprint or secret provided for the given service principal '823c2bdf-0bc2-4c93-b91d-e9a4bf7df1a8'.'

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):

Name                                     Account                                          SubscriptionName                                 Environment                                      TenantId
----                                     -------                                          ----------------                                 -----------                                      --------
 () - REDACTED CUSTOMER TENANTID… REDACTED APPLICATION ID AzureCloud                                       REDACTED TENANTID

DEBUG: AzureQoSEvent:  Module: Az.Accounts:2.10.4; CommandName: Set-AzContext; PSVersion: 7.3.1; IsSuccess: True; Duration: 00:01:22.1493206
DEBUG: 00:43:28 - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
DEBUG: 00:43:28 - SetAzureRMContextCommand end processing.
```

Running a cmdlet such as Get-AzResource after the above gives:
```text
 Get-AzResource -Debug
DEBUG: 00:44:56 - GetAzureResourceCmdlet begin processing with ParameterSet 'ByTagNameValueParameterSet'.
DEBUG: 00:44:56 - using account id 'REDACTED ACCOUNT ID'...
DEBUG: 00:44:56 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: [Common.Authentication]: Authenticating using Account: 'REDACTED ACCOUNT ID', environment: 'AzureCloud', tenant: 'REDACTED CLIENT TENANT ID'
DEBUG: [Common.Authentication]: Received exception No certificate thumbprint or secret provided for the given service principal 'REDACTED ACCOUNT ID'., while authenticating.
DEBUG: 00:44:56 - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
Get-AzResource: Your Azure credentials have not been set up or have expired, please run Connect-AzAccount to set up your Azure credentials.
No certificate thumbprint or secret provided for the given service principal 'REDACTED ACCOUNT ID'.
DEBUG: 00:44:56 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.Resources:6.5.0; CommandName: Get-AzResource; PSVersion: 7.3.1; IsSuccess: False; Duration: 00:00:00.0129289; Exception: Your Azure credentials have not been set up or have expired, please run Connect-AzAccount to set up your Azure credentials.
No certificate thumbprint or secret provided for the given service principal '823c2bdf-0bc2-4c93-b91d-e9a4bf7df1a8'.;
DEBUG: 00:44:56 - GetAzureResourceCmdlet end processing.
```

**Comment by msJinLei** [comment] 2023-01-05 07:07
>@msJinLei FYI it works consistently with 2.10.2, using the same service principal, @lassehastrup also mentions it working with 2.10.3

@ReneRebsdorf
Want to double confirm the issue `the issue is only found with Az.Accounts 2.10.4 or the issue is found with Az.Accounts 2.10.2, 2.10.3, 2.10.4`?

**Comment by ReneRebsdorf** [comment] 2023-01-05 09:12
@msJinLei

Since writing the above post I can verify that it is working in 2.10.2, 20.10.3, but broken in 2.10.4.

**Comment by msJinLei** [comment] 2023-01-05 15:13
> @msJinLei
> 
> Since writing the above post I can verify that it is working in 2.10.2, 20.10.3, but broken in 2.10.4.

Got it.

Could you try to Connect-AzAccount by both tenantA and tenantB using the service principal separately before you Set-AzContext and see whether the issue is still there?

**Comment by ReneRebsdorf** [comment] 2023-01-08 12:25
@msJinLei 

Nice spot.
Running Connect-AzAccount to tenantB makes azure context and commands works for that tenant, and likewise for tenantA (hence it worked for tenantA to begin with).

However, this is not a valid solution, but hopefully it brings insight into where the bug is introduced?
The rationale behind Connect-AzAccount not being a valid solution stems from the fact the Azure DevOps Pipelines run the 'connect-azaccount', and as such the credential is not exposed to the pipeline context itself for [AzurePowerShell docs](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-powershell-v5?view=azure-pipelines) - in other words we can not run Connect-AzAccount from an azure devops pipeline as we can not re-authenticate in a documented/supported way (to my knowledge)

[AzCLI@2](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-cli-v2?view=azure-pipelines) however exposes these credentials, but does not support Azure PowerShell Modules.

**Comment by ReneRebsdorf** [comment] 2023-01-15 14:46
@msJinLei can we remove the needs author feedback and no recent activity tags?

To our knowledge the necessary feedback was given previously in this thread?

**Comment by dingmeng-xue** [comment] 2023-01-15 16:46
Hi @ReneRebsdorf , are you and @lassehastrup from the same team? If you are not working together, I recommend that you create a new issue for tracking. Current `needs-author-feedback` label tracks comment from origin author only.

**Comment by ReneRebsdorf** [comment] 2023-01-15 17:30
> Hi @ReneRebsdorf , are you and @lassehastrup from the same team? If you are not working together, I recommend that you create a new issue for tracking. Current `needs-author-feedback` label tracks comment from origin author only.

We are from the same team yes.

**Comment by msJinLei** [comment] 2023-01-16 00:58
@ReneRebsdorf OK I will remove the tag temporarily. We are working on the issue.

**Comment by ReneRebsdorf** [comment] 2023-01-16 07:30
> @ReneRebsdorf OK I will remove the tag temporarily. We are working on the issue.

Great to hear🙂

**Comment by basvanveen** [comment] 2023-01-16 12:09
Chipping in a bit... we were also experiencing this in our (ubuntu based) github actions workflows. We tried switching powershell versions but it continued to stick with Az.Accounts 2.10.4. We also got the notice about "No certificate thumbprint" when trying to use `Set-AzContext -SubscriptionId` but this results in `Please provide a valid tenant or a valid subscription.`

![Screenshot 2023-01-16 at 13 03 52](https://user-images.githubusercontent.com/5782868/212674165-d383487e-f0dd-4fdc-b09d-9fbf4f8b364a.png)

this used to work in our workflows we "fixed" it now by adding a refresh of the Az.Accounts ;

`Install-Module Az.Accounts -Repository PSGallery -Force -AllowClobber -ErrorAction Stop`

this does the trick for us, so ubuntu runners seem to get packaged with a version that has this bug 🙃

**Comment by AshishDadhich4h2** [comment] 2023-01-17 14:22
We faced same issue and applied temporary fix 
# So Installed  Az.Accounts -RequiredVersion 2.10.3
# Installed Az -RequiredVersion 9.1.0 to fix Az.KeyVault dependecy on Az.Accounts 2.10.3 version

Install-Module -Name Az -RequiredVersion 9.1.0 -Scope AllUsers -Force -AllowClobber -Verbose
Uninstall-Module -Name Az.Accounts
Install-Module -Name Az.Accounts -RequiredVersion 2.10.3 -Scope AllUsers -Force -AllowClobber -Verbose 

Waiting for the permanent fix

**Comment by AshishDadhich4h2** [comment] 2023-01-24 13:58
@msJinLei Do you have any update?

**Comment by msJinLei** [comment] 2023-01-29 02:47
@basvanveen @AshishDadhich4h2  The issue#20484 is caused by switching to a tenant without login before which means no service principal password is stored. I am not sure whether your cases are the same. Could you provide the steps to reproduce the issue?

**Comment by msJinLei** [comment] 2023-01-31 06:02
Hi @ReneRebsdorf @lassehastrup 

Here is the private build with the fix. Please feel free try it and see whether the problem is resolved.

How to install:
- Install the Az.Tools.Installer module.
    ```powershell
    Install-Module -Name Az.Tools.Installer -Repository PSGallery
    ```
- Install the latest Az.Accounts private build module.
    ```powershell
    Install-AzModule -Path https://azposhpreview.blob.core.windows.net/public/Az.Accounts.2.11.11111.nupkg
   ```

@basvanveen @AshishDadhich4h2 You may also try this version to see whether your problem is solved. if not, You can create another issue and report your cases. Thanks!

**Comment by JonasCordsen** [comment] 2023-02-06 10:24
@msJinLei 

Hello

I work in the same team as @lassehastrup  and @ReneRebsdorf 

I have tested that the version of Az.Accounts does solve the issue.
Following the what I have tested, and how
```

PS /Users> get-module

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.11.11111            Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}

PS /Users> connect-azaccount -tenantid  <Tenant1 ID> -Credential $credentials -ServicePrincipal

Account		SubscriptionName 	TenantId			Environment
-------		---------------- 		-------			-----------
***			Management       		<Tenant1 ID>		AzureCloud

PS /Users> set-azcontext -Subscriptionid <SubscriptionID> -TenantId <Tenant2 ID>
Name	Account			SubscriptionName		Environment		TenantId
----		-------			----------------			-----------		--------
*** 		<AccountID>		<Subscription Name>		AzureCloud		<Tenant2 ID>
```

**Comment by msJinLei** [comment] 2023-02-07 11:27
The fix is included in https://www.powershellgallery.com/packages/Az/9.4.0

**Closed by msJinLei** 2023-02-07 11:27 UTC
Labels: Azure PS Team, bug, Authentication, customer-reported, Accounts, Tracking
