### ISSUE TITLE
Creating a Service Principle using PowerShell does not register the application under the "Enterprise applications" list

### ISSUE THREAD

**Issue by rmodayil** [Azure/azure-powershell#7646] opened 2018-10-23 01:45 UTC
I have registered the application, generated the key and successfully created the SPN with the application ID using PowerShell. But going back to the portal we noticed it does not end up in the 'Enterprise applications' list, however I can see it when 'All applications' is selected. Is there any way of tagging in the cmdlets to include it as an enterprise application?.

**Comment by draggeta** [comment] 2018-10-25 22:43
Hey @rmodayil, I've run into the same issue before and you can tag the SPN with the `Tag` parameter. I believe it should be a hashtable. To make it viewable, it should contain `WindowsAzureActiveDirectoryIntegratedApp` as a tag.
```powershell
Tags                               : {WindowsAzureActiveDirectoryIntegratedApp}
```

**Comment by markcowl** [comment] 2018-11-02 22:36
@rmodayil The ServicePrincipal cmdlets inside Azure PowerSehll are barrowly focused at creating service principals used for client-authentication.  If you want a more full implementation of AD object cmdlets, the AzureAD cmdlets allow you to manipulate AAD objects liek Service Principals anmd other AD objects fully.  Closing as 'By Design'

**Closed by markcowl** 2018-11-02 22:36 UTC
Labels: Azure PS Team :snail:, Investigate :mag:

**Comment by rmodayil** [comment] 2018-11-03 02:47
@marcowl thanks for that and @draggeta I just recently noticed the "Tag" parameter will definitely try using it. Thanks for all the help guys.
