### ISSUE TITLE
[Az.Functions] Update stacks to new schema 

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-powershell#12559] opened 2020-08-03 16:19 UTC
cc @Francisco-Gamino  @anthonychu @ammanifold

Repo: https://github.com/pragnagopa/azure-functions-supported-runtime-stacks is a temporary location and will be deprecated soon.

Please move to updated schema: https://github.com/Azure/azure-functions-ux/tree/dev/server/src/stacks/functionapp/2020-06-01/stacks

NOTE: This info will be available on ARM API. No ETA yet for this.

**Comment by Francisco-Gamino** [comment] 2022-02-04 22:35
This is duplicate of https://github.com/Azure/azure-powershell/issues/14682.

**Closed by Francisco-Gamino** 2022-02-04 22:35 UTC
Labels: feature-request, Service Attention, Functions, P2
