### ISSUE TITLE
[Feature]: Add-AzVHD - Steaming VHD conversion and resize

### ISSUE THREAD

**Issue by fowl2** [Azure/azure-powershell#17274] opened 2022-02-27 02:54 UTC
### Description of the new feature

Add-AzVHD will convert VHDX and VHD files to the fixed size VHD format, resizing if for alignments requirements if needed. It relies on the HyperV platform which means that:

* It only works on Windows
* It requires the HyperV feature to be installed
* It requires enough disk space for a full size copy

Ideally*, the cmdlet would use a cross platform library to stream the content of the VHDX directly to the service without making a copy and without relying on platform functionality unavailable on Linux. Presumably this should make it much faster too.

*well ideally, the service would just support uploading VHDX's as-is...

### Proposed implementation details (optional)

could possibly use https://github.com/DiscUtils/DiscUtils as a starting point, or maybe similar functionality exists in the [Azure Migrate](https://docs.microsoft.com/en-us/azure/migrate/tutorial-migrate-hyper-v?tabs=UI#install-and-register-the-provider)/Site Recovery.

see: #10549

**Comment by Drewm3** [comment] 2022-02-28 16:27
We will consider this feature request for a future PowerShell update after talking with existing customers of this cmdlet and determining the likely additional customers that would start using this cmdlet with the proposed changes.

**Comment by mpb10** [comment] 2022-03-02 22:10
@Drewm3 My work depends heavily on the Add-AzVhd commandlet and we've run into significant issues using it since the issues described by @fowl2 have gone into effect with version 7.0.0 of Azure PowerShell.

Previous Azure PowerShell versions of this commandlet (Which no longer work at all for some reason) were much, much faster and did not create full sized copy on the local system. The execution times of this commandlet are four to six times longer since being forced to upgrade to Azure PowerShell version 7.0.0+.

**Comment by fowl2** [comment] 2022-03-03 00:07
@Drewm3 oh thanks for the info! This is basically my first time using it - What was the previous behaviour? I was operating under the impression it would just fail and you'd have to manually alter the vhds.

**Comment by mpb10** [comment] 2022-03-03 17:31
@fowl2 Previous versions of the commandlet seemed to upload the dynamic sized VHD file directly to Azure, which I assume they would then resize to a full sized disk on their end. At some point I assume they disabled the resizing on their end, which I assume is why Add-AzVhd in any version of Azure PowerShell below 7.0.0 no longer works, since Azure now expects the commandlet to resize the VHD file on your local system.

Our VHD files are usually around 6 to 20 GB when using dynamic sized disks and are always 100 GB when full sized disks. The previous version of the commandlet was definitely uploading the dynamic sized VHD files and not a 100 GB file.

**Comment by ravkash** [comment] 2022-03-04 15:01
@Drewm3 Do you have any insights into why the behavior was changed and there is a plan to bring it back?

**Comment by grizzlytheodore** [comment] 2022-03-04 16:18
subscribing to this thread to stay aware of this topic

**Comment by grizzlytheodore** [comment] 2022-03-04 19:16
please check if you are correctly using the older Add-AzVHD call by running:  
Get-InstalledModule Az.Compute 

Your Az.Compute module should be 4.20.0 or older. 

If you need to downgrade your Az.Compute module: 
Remove-Module Az.Compute   *Run until no Az.Compute module shows when running Get-IntalledModule Az.Compute
Install-Module -Name Az.Compute -RequiredVersion 4.20.0

**Comment by rbreitendev** [comment] 2022-03-08 02:51
@grizzlytheodore so you're saying that an old version of the `Az.Compute` module of `4.20.0` should be leveraged that is outdated at this time? As opposed to leveraging the latest module and its capability?

**Comment by Drewm3** [comment] 2022-03-08 07:06
@grizzlytheodore, was there a change in the behavior of the Add-AzVHD cmdlet? This issue was originally opened as a feature request, but it seems that @mpb10 is claiming that the cmdlet changed behavior. If the behavior changed unexpectedly, then this should be converted to a bug instead of a feature request.

**Comment by grizzlytheodore** [comment] 2022-03-09 03:07
@Drewm3 @rbreitendev @mpb10 

For everyone: 
For an immediate work around, we recommend two options:
using Az.Compute 4.20.0 version, which has the version of Add-AzVhd before the changed behaviors
or [Set-AzStorageBlobContent](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fpowershell%2Fmodule%2Faz.storage%2Fset-azstorageblobcontent%3Fview%3Dazps-7.3.0&data=04%7C01%7CTheodore.Chang%40microsoft.com%7C57e188ecd2334a5c7f3608da0176fa45%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637823907762681095%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HHbR%2BZwt%2BzzaUgAwSHU%2BcJ4dH4FaCyfF4Xe2UE6vVz0%3D&reserved=0), a cmdlet that will upload any file to a blob. 

The issue comes from the following: 
Add-AzVhd is intended for uploading VHD files that will be attached to an Azure VM. An Azure VM will only accept a fixed size VHD that is N*Mib sized, which is why we added functionalities to automatically resize/convert. 
The changed behavior you are seeing is this: before customers could upload dynamically sized VHD files to a blob, however customers would fail when they try to move the dynamically sized to a managed disk to attach to a VM. 
Now Add-AzVHD will try to convert dynamically sized VHD files to fixed size, and if not possible, the cmdlet will fail. It is by design to help customer fail earlier than later. It was approved by the breaking change board and the breaking change message was added adequately before the breaking change went into effect. 

As we discuss updating this cmdlet, please use the workaround. For uploading VHD files to blobs without intentions to attach to a VM, we recommend using [Set-AzStorageBlobContent](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fpowershell%2Fmodule%2Faz.storage%2Fset-azstorageblobcontent%3Fview%3Dazps-7.3.0&data=04%7C01%7CTheodore.Chang%40microsoft.com%7C57e188ecd2334a5c7f3608da0176fa45%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637823907762681095%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HHbR%2BZwt%2BzzaUgAwSHU%2BcJ4dH4FaCyfF4Xe2UE6vVz0%3D&reserved=0)

**Comment by mpb10** [comment] 2022-03-10 16:32
@grizzlytheodore 

We just tested the suggestion to downgrade to Az.Compute 4.20.0 and we confirmed that it still doesn't work. We are getting the same error as we did when we downgraded the entire Az module to version 5.8.0 (Which includes the Az.Compute module). The following is the error message we get when trying to use older versions. We can also see the warning message of the breaking change in the output, however we don't understand why this change even needed to be made to the commandlet if it worked great before:

```
PS D:\work> $AzContainerUri = (Get-AzStorageContainer -Name $AzContainerName -Context $AzStorageAccountContext).CloudBlobContainer.Uri.AbsoluteUri
WARNING: Upcoming breaking changes in the cmdlet 'Add-AzVhd' :
This cmdlet will now try to resize the VHD file to (N * Mib + 512 bytes) using Hyper-V before uploading.
 If Hyper-V is not found, user will have to either enabled Hyper-V or resize manually before uploading.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking
changes in Azure PowerShell.
MD5 hash is being calculated for the file  D:\work\rhel-8.4-v4.vhd.
MD5 hash calculation is completed.
Elapsed time for the operation: 00:05:47
Elapsed time for upload: 00:00:00
Add-AzVhd : One or more errors occurred.
At line:1 char:1
+ Add-AzVhd -Destination "$AzContainerUri/$AzVhdFileName" -LocalFilePat ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Add-AzVhd], AggregateException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.StorageServices.AddAzureVhdCommand
```

I also tested using the `Set-AzStorageBlobContent` command, however as expected, it uploaded our VHD file as a dynamic sized disk of just 5.86 GB. Because the VHD file is dynamic sized, we cannot create an Azure image from the VHD file.

The reason why we used Add-AzVhd in the past was because it would somehow automatically resize the VHD file to be fixed sized once it was uploaded to the Azure storage account container. It never seemed to do any resizing on the local system, which saved us significant time and storage space.

**Comment by grizzlytheodore** [comment] 2022-03-10 16:49
@mpb10 thank you for the information. This is helpful for us. We are investigating why/when there was a change in the service side to stop converting VHD files after being uploaded. We will get back to you with updates.

**Comment by grizzlytheodore** [comment] 2022-03-10 20:10
In the meantime please follow the workarounds:
For uploading to a blob without intention to attach to a VM: 
[Set-AzStorageBlobContent](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fpowershell%2Fmodule%2Faz.storage%2Fset-azstorageblobcontent%3Fview%3Dazps-7.3.0&data=04%7C01%7CTheodore.Chang%40microsoft.com%7C57e188ecd2334a5c7f3608da0176fa45%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637823907762681095%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HHbR%2BZwt%2BzzaUgAwSHU%2BcJ4dH4FaCyfF4Xe2UE6vVz0%3D&reserved=0)
This will not convert or resize your file 

For uploading to attach to a VM: 
You can still use Add-AzVhd, which will convert/resize locally. I understand it is taking a while. 
[AzCopy](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#download-and-install-azcopy) will upload much faster, however you will need to convert and resize VHD files manually. 
To manually resize and convert, please see: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#download-and-install-azcopy

Again, we are working on getting to the bottom of this issue and will provide a plan for a permanent solution soon.

**Comment by archoversight** [comment] 2022-03-10 22:17
@grizzlytheodore previously we could upload the images and they would be resized on the Azure side. This saves a tremendous amount of bandwidth, as we'd only be sending a ~20 GiB file per image.

Expanding all of the images we upload (and the various variants) as required for our various products and teams, is a massive undertaking and increases the bandwidth required to get images into Azure.

It's not just a single image we are talking about, we are talking about 15 - 30 images on a monthly basis to meet security requirements (in-place upgrades of older images to newer versions is not acceptable for us). 30 x 100 GiB is 2.5 TiB of data, instead of ~650 GiB.

**Comment by grizzlytheodore** [comment] 2022-04-18 21:14
this issue has been addressed in this PR: https://github.com/Azure/azure-powershell/pull/177864
which will GA on 4/26. 

Thank you all for your input and insights to help understand and track down the changes that were made.
The PR will restore: 
uploading dynamically sized VHD files are converted to fixed-size during upload.

And also:
any converted/resized file that were created during the process will be deleted automatically after upload.

**Closed** 2022-05-02 20:28 UTC
Labels: Compute, feature-request, Service Attention, customer-reported
