### ISSUE TITLE
Get-AzLocation : Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by AnmolDhillon** [Azure/azure-powershell#9991] opened 2019-09-09 06:23 UTC
I am getting the error : Get-AzLocation : Object reference not set to an instance of an object.
The scripts were running successfully and then all of a sudden they stopped working. 

```
Get-AzLocation : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-AzLocation |Select-Object DisplayName
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzLocation], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureLocationCmdlet
```

I am getting this error for all Az commands.

```
Azure version                     Name                                         Powershell Version
1.6.1                             Az.Accounts                                  5.1
```

**Comment by erich-wang** [comment] 2019-09-09 11:56
@AnmolDhillon, thank you for reporting the issue, please provide the following info:



## Steps to reproduce

```powershell

```

## Environment data

 Please run $PSVersionTable and paste the output in the below code block 

```

```

## Module versions

Please run (Get-Module  -ListAvailable) and paste the output in the below code block

```powershell

```

## Debug output

 Set $DebugPreference='Continue' before running the repro and paste the resulting debug stream in the below code block

```

```

## Error output

 Please run Resolve-AzError and paste the output in the below code block

```

```

**Comment by AnmolDhillon** [comment] 2019-09-09 13:27
> @AnmolDhillon, thank you for reporting the issue, please provide the following info:
> 
> ## Steps to reproduce
> ## Environment data
> Please run $PSVersionTable and paste the output in the below code block
> Name                           Value
----                           -----
PSVersion                      5.1.17134.858
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.858
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
> ```
> 
> ```
> 
> ## Module versions
> Please run (Get-Module -ListAvailable) and paste the output in the below code block
> 
[AzVersion.txt](https://github.com/Azure/azure-powershell/files/3590673/AzVersion.txt)

> ## Debug output
> Set $DebugPreference='Continue' before running the repro and paste the resulting debug stream in the below code block
> 
[AzError-Debug.txt](https://github.com/Azure/azure-powershell/files/3590675/AzError-Debug.txt)

> ```
> 
> ```
> 
> ## Error output
> Please run Resolve-AzError and paste the output in the below code block
> PS C:\Users\anmol.dhillon> Resolve-AzError
DEBUG: 6:56:01 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 6:56:01 PM - using account id 'anmol.dhillon@ad.infosys.com'...


   HistoryId: 27


Message        : 'this.Client.SubscriptionId' cannot be null.
StackTrace     :    at Microsoft.Azure.Management.Compute.VirtualMachineSizesOperations.<ListWithHttpMessagesAsync>d__5.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Commands.Compute.GetAzureVMSizeCommand.<ExecuteCmdlet>b__19_0()
                    at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
                    at Microsoft.Azure.Commands.Compute.GetAzureVMSizeCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Rest.ValidationException
InvocationInfo : {Get-AzVMSize}
Line           : Get-AzVMSize -Location 'eastus'
Position       : At line:1 char:1
                 + Get-AzVMSize -Location 'eastus'
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 27



   HistoryId: 26


Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureLocationCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.NullReferenceException
InvocationInfo : {Get-AzLocation}
Line           : Get-AzLocation
Position       : At line:1 char:1
                 + Get-AzLocation
                 + ~~~~~~~~~~~~~~
HistoryId      : 26



   HistoryId: 24


Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureLocationCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.NullReferenceException
InvocationInfo : {Get-AzLocation}
Line           : Get-AzLocation
Position       : At line:1 char:1
                 + Get-AzLocation
                 + ~~~~~~~~~~~~~~
HistoryId      : 24



   HistoryId: 18


Message        : 'this.Client.SubscriptionId' cannot be null.
StackTrace     :    at Microsoft.Azure.Management.Compute.VirtualMachineImagesOperations.<ListPublishersWithHttpMessagesAsync>d__8.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Commands.Compute.GetAzureVMImagePublisherCommand.<ExecuteCmdlet>b__4_0()
                    at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
                    at Microsoft.Azure.Commands.Compute.GetAzureVMImagePublisherCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Rest.ValidationException
InvocationInfo : {Get-AzVMImagePublisher}
Line           : Get-AzVMImagePublisher -Location "eastus"
Position       : At line:1 char:1
                 + Get-AzVMImagePublisher -Location "eastus"
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 18



   HistoryId: 16


Message        : 'this.Client.SubscriptionId' cannot be null.
StackTrace     :    at Microsoft.Azure.Management.Compute.VirtualMachineSizesOperations.<ListWithHttpMessagesAsync>d__5.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Commands.Compute.GetAzureVMSizeCommand.<ExecuteCmdlet>b__19_0()
                    at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
                    at Microsoft.Azure.Commands.Compute.GetAzureVMSizeCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Rest.ValidationException
InvocationInfo : {Get-AzVMSize}
Line           : Get-AzVMSize
Position       : At line:1 char:1
                 + Get-AzVMSize
                 + ~~~~~~~~~~~~
HistoryId      : 16



   HistoryId: 15


Message        : 'this.Client.SubscriptionId' cannot be null.
StackTrace     :    at Microsoft.Azure.Management.Compute.VirtualMachineSizesOperations.<ListWithHttpMessagesAsync>d__5.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Commands.Compute.GetAzureVMSizeCommand.<ExecuteCmdlet>b__19_0()
                    at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
                    at Microsoft.Azure.Commands.Compute.GetAzureVMSizeCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Rest.ValidationException
InvocationInfo : {Get-AzVMSize}
Line           : Get-AzVMSize -Location 'uksouth'

Position       : At C:\Users\anmol.dhillon\Desktop\master.ps1:3 char:1
                 + Get-AzVMSize -Location 'uksouth'
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 15

Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureLocationCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.NullReferenceException
InvocationInfo : {Get-AzLocation}
Line           : Get-AzLocation

Position       : At C:\Users\anmol.dhillon\Desktop\master.ps1:2 char:1
                 + Get-AzLocation
                 + ~~~~~~~~~~~~~~
HistoryId      : 15



   HistoryId: 14


Message        : 'this.Client.SubscriptionId' cannot be null.
StackTrace     :    at Microsoft.Azure.Management.Compute.VirtualMachineSizesOperations.<ListWithHttpMessagesAsync>d__5.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Commands.Compute.GetAzureVMSizeCommand.<ExecuteCmdlet>b__19_0()
                    at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
                    at Microsoft.Azure.Commands.Compute.GetAzureVMSizeCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Rest.ValidationException
InvocationInfo : {Get-AzVMSize}
Line           : Get-AzVMSize -Location "uksouth"
Position       : At C:\Users\anmol.dhillon\Desktop\loc2.ps1:1 char:1
                 + Get-AzVMSize -Location "uksouth"
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 14

Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureLocationCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.NullReferenceException
InvocationInfo : {Get-AzLocation}
Line           : Get-AzLocation |Select-Object DisplayName,Location
Position       : At C:\Users\anmol.dhillon\Desktop\loc1.ps1:1 char:1
                 + Get-AzLocation |Select-Object DisplayName,Location
                 + ~~~~~~~~~~~~~~
HistoryId      : 14



   HistoryId: 13


Message        : 'this.Client.SubscriptionId' cannot be null.
StackTrace     :    at Microsoft.Azure.Management.Compute.VirtualMachineSizesOperations.<ListWithHttpMessagesAsync>d__5.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Commands.Compute.GetAzureVMSizeCommand.<ExecuteCmdlet>b__19_0()
                    at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
                    at Microsoft.Azure.Commands.Compute.GetAzureVMSizeCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Rest.ValidationException
InvocationInfo : {Get-AzVMSize}
Line           : Get-AzVMSize
Position       : At line:1 char:1
                 + Get-AzVMSize
                 + ~~~~~~~~~~~~
HistoryId      : 13



   HistoryId: 12


Message        : 'this.Client.SubscriptionId' cannot be null.
StackTrace     :    at Microsoft.Azure.Management.Compute.VirtualMachineSizesOperations.<ListWithHttpMessagesAsync>d__5.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Commands.Compute.GetAzureVMSizeCommand.<ExecuteCmdlet>b__19_0()
                    at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
                    at Microsoft.Azure.Commands.Compute.GetAzureVMSizeCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Rest.ValidationException
InvocationInfo : {Get-AzVMSize}
Line           : Get-AzVMSize -Location "uksouth"
Position       : At C:\Users\anmol.dhillon\Desktop\loc2.ps1:1 char:1
                 + Get-AzVMSize -Location "uksouth"
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 12

Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureLocationCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.NullReferenceException
InvocationInfo : {Get-AzLocation}
Line           : Get-AzLocation |Select-Object DisplayName,Location
Position       : At C:\Users\anmol.dhillon\Desktop\loc1.ps1:1 char:1
                 + Get-AzLocation |Select-Object DisplayName,Location
                 + ~~~~~~~~~~~~~~
HistoryId      : 12



   HistoryId: 10


Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureLocationCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.NullReferenceException
InvocationInfo : {Get-AzLocation}
Line           : Get-AzLocation |Select-Object DisplayName
Position       : At line:1 char:1
                 + Get-AzLocation |Select-Object DisplayName
                 + ~~~~~~~~~~~~~~
HistoryId      : 10



   HistoryId: 9


Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureLocationCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.NullReferenceException
InvocationInfo : {Get-AzLocation}
Line           : Get-AzLocation |Select-Object DisplayName
Position       : At line:1 char:1
                 + Get-AzLocation |Select-Object DisplayName
                 + ~~~~~~~~~~~~~~
HistoryId      : 9



   HistoryId: 1


Message        : Cannot find type [System.Windows.Forms.Form]: verify that the assembly containing this type is loaded.
StackTrace     :    at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
Exception      : System.Management.Automation.PSArgumentException
InvocationInfo : {New-Object}
Line           : $main_form=New-Object System.Windows.Forms.Form
Position       : At line:1 char:12
                 + $main_form=New-Object System.Windows.Forms.Form
                 +            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1

DEBUG: AzureQoSEvent: CommandName - Resolve-AzError; IsSuccess - True; Duration - 00:00:01.3215174; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 6:56:04 PM - ResolveError end processing.
DEBUG: 6:56:04 PM - ResolveError end processing.
> ```
> 
> ```

**Comment by erich-wang** [comment] 2019-09-23 15:14
@AnmolDhillon , could you please run the cmdlet first and rerun your cmdlet?
`Clear-AzContext`

**Comment by erich-wang** [comment] 2019-10-11 03:47
@AnmolDhillon, have you tried `Clear-AzContext`? We'll close the issue if we don't hear from you in 5 days.

**Comment by erich-wang** [comment] 2019-10-24 05:36
@AnmolDhillon , we close the issue since we don't hear from you long time. Please create a new issue if necessary, thanks.

**Closed by erich-wang** 2019-10-24 05:36 UTC
Labels: Azure PS Team, More Info :label:
