### ISSUE TITLE
Get-AzStorageAccount unable to handle 429 response code from Azure portal

### ISSUE THREAD

**Issue by saurabs** [Azure/azure-powershell#14504] opened 2021-03-10 17:24 UTC
**## Description**
We are observing an issue where "Get-AzStorageAccount" when called from Powershell is unable to handle the 429 response code from Azure (which is returned in case the backend API is throttled).
...

## Steps to reproduce
Use below script to reproduce the problem.. make sure that the backend Storage Account is in throttled state (by submitting more than 100 calls in 5 min).

$timeout = new-timespan -Minutes 6
$count = 0
$sw = [diagnostics.stopwatch]::StartNew()
while ($sw.elapsed -lt $timeout){​​​​
   Get-AzStorageAccount -ResourceGroupName <rgname>
   $registryData.value
   $count ++
    $count
    start-sleep -seconds 1
}​​​​

 

```

## Environment data

We have collected the versions of the module used for the PowerShell, below are the same:
•	3.1.0      Az.Storage
•	Script     2.6.0      Az.Storage
•	Script     1.2.0      Az.Storage
Also, we have collected the powerShell version you are using, below are the same:

•	Version : 5.1.19041.610


## Debug output
PowerShell command keep waiting for data, since the 429 status code is not parsed properly.
```

**Comment by blueww** [comment] 2021-03-12 11:10
@saurabs

Actually, server response with 429 can be parsed correctly by Powershell (and SDK inside). Powershell can also get `Retry-After: 17` in the responds, then retry the request.
The problem is PSH will retry again and again every 17s, so it looks like PSH keeps waiting.

I think you request is make Get-AzStorageAccount fail fast in this case, and show the error details.
I will contact related team to investigate it, and update you later.

**Comment by saurabs** [comment] 2021-03-15 22:42
Thanks a lot, we will wait for your valuable feedback and guidance.

**Comment by saurabs** [comment] 2021-03-22 21:49
Any new updates?

**Comment by blueww** [comment] 2021-03-23 06:50
@saurabs 

We have found this hang code is in .net SDK framework, and is in discussion with .net SDK team to see if they can fix it.
Besides that, there's a workaround to replace the default HttpClient when create .net SDK object. I have prototype it and it works. But it might has potential issue since will lost many setting in default HttpClient. So the better solution is still to fix .net SDK.
Will update you if get decision for how to fix this.

**Comment by saurabs** [comment] 2021-03-23 09:40
This is awesome.

**Comment by blueww** [comment] 2021-05-26 07:17
@saurabs 

[Az 6.0.0](https://github.com/Azure/azure-powershell/releases/tag/v6.0.0-May2021) opened 2 environment variables for set the retry times of 429 error on Get-AzStorageAccount (will also impact retry times of many other cmdlets).

You can set the following 2 environment variable to smaller value to make Get-AzStorageAccount fail fast. 

- AZURE_PS_HTTP_MAX_RETRIES 
    - Default value is : 3
    - Value range: integer >= 0
    - Change it will impact other error code retry times
- AZURE_PS_HTTP_MAX_RETRIES_FOR_429
    - Default value is : infinite
    - Value range: integer >=1, (0 behavior same as 1)
    - Change it only impact 429 error retry times

The total request run times (include first run and retry) for a request always return 429 is: `AZURE_PS_HTTP_MAX_RETRIES_FOR_429  * (AZURE_PS_HTTP_MAX_RETRIES + 1) `

So to make Get-AzStorageAccount only send request for 1 time (no retry), you can use following script, and it will show the failure if request fail:
```powershell
$env:AZURE_PS_HTTP_MAX_RETRIES_FOR_429 = 1
$env:AZURE_PS_HTTP_MAX_RETRIES = 0
Get-AzStorageAccount 
```
As the environment variable change will also impact many other cmdlets retry times on error return, you can remove the 2 environment variable after finish running Get-AzStorageAccount, to recover the default behavior:
```powershell
$env:AZURE_PS_HTTP_MAX_RETRIES_FOR_429 = $null
$env:AZURE_PS_HTTP_MAX_RETRIES = $null 
```

**Comment by blueww** [comment] 2021-05-28 08:13
Close this issue as Az 6.0.0 has already opened environment variables to make Get-AzStorageAccount fail fast, with correct error reported.

**Closed by blueww** 2021-05-28 08:13 UTC
Labels: Service Attention, Storage, customer-reported, question
