### ISSUE TITLE
use -confirm instead of "-force"

### ISSUE THREAD

**Issue by trondhindenes** [Azure/azure-powershell#475] opened 2015-06-09 11:15 UTC
The -"confirm" switch has alwas been meant as a way for a user to specify wether or not a cmdlet should prompt the user for confirmation. Throughout the azure cmdlets the "-Force" switch is used instead. Make sure the azure cmdlets stay "true" to PowerShell by using the "confirm" switch instead of "force".

**Comment by doctordns** [comment] 2015-06-09 14:03
I think -force is right in most cases - you want to force the cmdlet to some something. Of course, -confirm would be useful to 'force' confirmation.

**Comment by trondhindenes** [comment] 2015-06-09 14:23
I beg to differ (maybe you could reach out to the PowerShell team on this one). IMHO: Confirm is meant as a switch to confirm "high-impact" operations, such as deleting a VM. There is a variable controlling this behaviour ($ConfirmPreference ). The "force" switch is typically used for other types of overrides, such as creating a file in a non-existing folder (the "force" switch will auto-create the missing folder in that situation).

**Comment by geekjimmy** [comment] 2015-06-09 14:29
trondhindenes is right. -force is for things like overwriting existing items, where running the cmdlet without the -force switch would result in failure.

it's also used by things like Get-ChildItem to show hidden files.

**Comment by RamblingCookieMonster** [comment] 2015-06-09 14:41
I personally prefer the presence of both. -Confirm:$False might make sense to many of us, but it's a bit more difficult than simply specifying -Force.

**Comment by trondhindenes** [comment] 2015-06-09 14:48
Gotcha. I'm just worried that this leads to "language sprawl", and as such Microsoft's own modules should be examples of correct parameter usage. If they don't get it right, who will?

**Comment by jrich523** [comment] 2015-06-09 15:13
actually if you look at any of the original commands, this is how it was... Force for something like Delete that should always prompt, and then confirm for something like Rename, where you might want to prompt... 

it was actually VMWare that started this horrible horrible trend... and PowerCLI is probably one of the WORST set of cmdlets..

Use -Force and avoid -Confirm:$false

I was super sad to see MS start to use the -confirm:false in some of the newer stuff, it was explained to me that it was other teams making PS cmdlets (much like the azure team making cmdlets) that did this, and not the core team...

Stop the Sprawl! use Force!

**Comment by dlwyatt** [comment] 2015-06-09 15:58
I think it's a bit ugly to have to pass "false" to switch parameters.  That said, using both parameters can lead to some confusion.  What happens if someone runs your command with `-Force -Confirm`?

If I could go back in time and reinvent things, I'd probably have made -Force and -Confirm mutually exclusive, common parameters (where -Force is just the equivalent of -Confirm:$false today).  But since that ship has already sailed, I think when I'm authoring commands that support ShouldProcess, I'll lean toward just having a single `-Confirm` parameter.

**Comment by jrich523** [comment] 2015-06-09 16:08
i'd have to imagine that if someone picks both (pondering a way to prevent that) they are smoking crack and deserve whatever oddness may happen :)

**Comment by mattmcnabb** [comment] 2015-06-09 16:32
In the Powershell core cmdlets (*-Item), -Force has a different semantic meaning than -Confirm. For instance, with Remove-Item, it's used to remove items flagged as hidden as well as unhidden items. For this reason I think the Azure cmdlets should use -Confirm.

However, I agree with Dave W. that the usage of -Confirm:$false is atrocious and causes problems for those new to Powershell.

**Comment by Jaykul** [comment] 2015-06-09 16:33
`Confirm:$False` is _most definitely_ an anti-pattern which breaks several strict guidelines, particularly since Confirm and WhatIf are common parameters provided by ShouldProcess.

If you look at the guidelines for `ShouldProcess` and `ShouldContinue` ... `-Confirm` serves to trigger ConfirmPreference to High, and **must** always come from SupportsShouldProcess. `-Force` is recommended for use whenever you use ShouldContinue to prompt. If you're adding Confirm to your commands by hand, **you're doing it wrong**, period.

### Most built-in commands that use -Force also use Confirm

I can't believe anyone is arguing against the combination of these ... let me give you a short list of the *core cmdlets* which support both:

Add-Computer, Add-Content, Clear-Content, Clear-Item, Clear-ItemProperty, Clear-RecycleBin, Clear-Variable, ConvertTo-MacOs9LineEnding, ConvertTo-UnixLineEnding, ConvertTo-WindowsLineEnding, Copy-Item, Copy-ItemProperty, Disable-PSRemoting, Disable-PSSessionConfiguration, Edit-File, Enable-PSRemoting, Enable-PSSessionConfiguration, Expand-Archive, Export-Alias, Export-Clixml, Export-Console, Export-Csv, Import-Alias, Move-Item, Move-ItemProperty, New-Alias, New-Item, New-ItemProperty, New-MSMQueue, New-Variable, Out-File, Register-PSSessionConfiguration, Remove-Computer, Remove-Item, Remove-ItemProperty, Remove-Job, Remove-Module, Remove-PSDrive, Remove-Variable, Rename-Computer, Rename-Item, Rename-ItemProperty, Restart-Computer, Restart-Service, Set-Alias, Set-AuthenticodeSignature, Set-Content, Set-ExecutionPolicy, Set-FileTime, Set-Item, Set-ItemProperty, Set-PSSessionConfiguration, Set-Variable, Stop-Computer, Stop-Process, Stop-Service, Stop-TerminalSession, Suspend-Job, Unregister-Event, Unregister-PSSessionConfiguration, Update-Help, Update-TypeData

**Comment by trondhindenes** [comment] 2015-06-09 16:40
My point exactly Joel - I'd like the Azure cmdlets to use the existing language features (ShouldProcess/ShouldContinue) to provide a standardized way of interacting with "high-impact" operations. I'm of course not asking them to implement support for "confirm" without the proper plumbing underneath.

**Comment by doctordns** [comment] 2015-06-09 16:41
Trondhiness says:
"IMHO: Confirm is meant as a switch to confirm "high-impact" operations, such as deleting a VM. There 
is a variable controlling this behaviour ($ConfirmPreference )."

Agreed - I think you also mean to say: conrfirmation should only happen if -CONFIRM is specified moderated by $ConfirmPreference. 

He also says
" The "force" switch is typically used for other types of overrides, such as creating a file in a non-existing folder (the "force" switch will auto-create the missing folder in that situation)."

As I see it, -Force is short cut to (shut up and just do what I ask - I know what I am doing". 

I think the OP is making the point that confirmation is happening without -confirm being requested and where other cmdlets might have just done the operation. 

This last point is important - I hate seeing these popups. Heck, I can kill a process or service with out popups - why for Azure?

**Comment by Jaykul** [comment] 2015-06-09 16:49
@trondhindenes I haven't used these cmdlets in a while -- is the problem just that they have their ConfirmImpact set too high, or are they using ShouldContinue when they should be using ShouldProcess, or is it something _else_?  That is, if you set `$ConfirmPreference = "None"` does that turn off the prompts?

I mean, when you ask for `-Force` I was assuming they're using ShouldContinue instead of ShouldProcess -- but maybe the problem is just that they've specified `ConfirmImpact="High"` on their commands (setting your ConfirmImpact too high is a common mistake from non-PowerShell-using developers who don't understand the impact that has).

**Comment by trondhindenes** [comment] 2015-06-09 16:50
Well sorta. I just want consistency. Which is (imho) one of the very important strengths of the PowerShell language. If a cmdlet accepts the "confirm" parameter, I expect to be able to run the cmdlet with "-confirm:$false" in order to suppress prompts, which is certainly not the case with a lot of the azure cmdlets (remove-azureservice, for example still prompts to confirm if the confirm switch is set to false). This makes it a lot harder to automate tasks because I need to manually test each cmdlet to find out how to "mute" it instead of being able to rely on "-confirm".

**Comment by Jaykul** [comment] 2015-06-09 17:08
That cmdlet (for example) looks like it's just calling ConfirmAction in the base [AzurePSCmdlet](https://github.com/Azure/azure-powershell/blob/ae0983c74a9a3035af8df42ab8da995d544e53e8/src/Common/Commands.Common/AzurePSCmdlet.cs) class, which looks like this:

```
        protected void ConfirmAction(bool force, string actionMessage, string processMessage, string target, Action action)
        {
            if (force || ShouldContinue(actionMessage, ""))
            {
                if (ShouldProcess(target, processMessage))
                {
                    action();
                }
            }
        }
```

Can I just say: _you got this inside out folks!_  It basically makes it so that **everything** that goes through here needs `-Force` to even see the ShouldProcess prompt. On top of that, they're not supporting the "All" options in ShouldContinue, so you presumably have to use -Force or be prompted for each item.  That's a mess.

Of course, there's also [a "custom" implementation of ShouldProcess over here](https://github.com/Azure/azure-powershell/blob/7e051495ebb8a9f7613c932a8a91f80fed365763/src/ServiceManagement/Services/Commands.Utilities/Store/PowerShellCustomConfirmation.cs) so if they're using that, then it's wrong all over again in another way....

**Comment by trondhindenes** [comment] 2015-06-19 23:11
I did some more thinking on this, and at least for me the following is the right pattern:
-If the operation is simply a high-impact operation such as deleting a VM or whatever, the builtin functionality should be used. This is what gives us the -confirm switch.
-if the operation should have a "brute-force" option then "-force" should be used. An example of this is "get-childitem -force", which shows hidden files and folders as opposed to non-hidden.

**Comment by jtuliani** [comment] 2015-07-21 18:07
My 2c: I like the approach of using 'Confirm' to suppress confirmation prompts and 'Force' to make the behaviour more 'determined to achieve success despite obstacles'.  This has the advantage of being more in line with standard PowerShell behaviour, and enabling $ConfirmPreference to be set for an entire script.
Moving to this model should be the goal.  But it's a breaking change, which has to be handled carefully.  Also, we must ensure consistency across Azure.

**Comment by trondhindenes** [comment] 2015-07-28 09:18
@jtuliani well put sir. And I 100% agree.

**Comment by trondhindenes** [comment] 2015-07-28 09:34
Any comments from the Azure team on this?

**Comment by markcowl** [comment] 2016-02-17 18:10
Hello all,  we will be tacking this issue over the next sprint or two.  My question to the community is how would you prefer we roll this out?  Should we phase this in a few services at a time, or make a single large breaking change and make all ARM cmdlets consistent all at once? If we want to continue using semantic versioning on the roll-up package, this almost forces us to make the change all at once, or go through a serious of major version changes.

In the mean, I believe the correct thing is to use ShouldProcess in most of the places where we are currently using Force, and mainly remove Force from most cmdlets.  I think we should be reserving Force for operations that require special confirmation, such as updating/removing a resource without checking the eTag, or removing a resource that contains other resources (storage accounts that contain blobs, resource groups that contain resources, etc.)

Would appreciate any comments or contrary opinions on this.

@doctordns is correct about the reason this decision was made long ago - it was in favoring ease of documentation for powershell novices at the expense of compliance to please those with more PowerShell experience.  Given the growing importance of scripting, we are taking a new look at many of those original decisions, and have decided that we should tackle this one next.

To set expectations, we would mainly target ARM cmdlets for this, as this is where we expect most new development.

I'm curious as to whether people on this thread think it's a priority to propagate this change to ServiceManagement cmdlets as well?

**Comment by trondhindenes** [comment] 2016-02-17 18:28
I would just get it done. For every day that passes with the modules containing the current bugs/design failures/whatever we call them, there's another group of people learning the "wrong kind" of powershell. But whatever you do, just make sure it's documented (as in real built-in help). 

I agree with the (new) proposed usage of "-force".

As for ASM, it doesn't have the consistent wrongness that ARM does in this regard. I would leave the ASM cmdlets alone.

**Comment by doctordns** [comment] 2016-02-18 07:20
I agree with Trond - just get it done. It's a mess that is slowly getting less messy. I totally agre with trond about the current design challenges and it's impact on new users. 

I would like to see the cmdlets (ASM vs ARM) to be consistent. I would only change ASM cmdlets if/where their usage is different to what is being proposed for ARM cmdlets. Please, consistency is really important, imho.

**Comment by KirkMunro** [comment] 2016-02-18 14:00
I agree with getting it done all at once across all modules.  Better to make the community adjust once to the breaking changes rather than to drag it out over time.

**Comment by doctordns** [comment] 2016-02-18 15:05
Kirk makes a great point about not dragging this out. It's easy to say, it's a change that should have been made a while ago - but that's not helpful. Let's make the change, everywhere, so that the use of -Force and -Confirm is consistent between ARM/ASM - there's enough new stuff for PowerShell IT Pros to learn wrt Azure, let's make ARM and ASM cmdlets as compatible and consistent as is possible. 

Can we have some confirmation as to the team's plans - once you have had the opportunity to reflect on the feedback?

**Comment by kilasuit** [comment] 2016-02-18 15:23
See #1826 - there's a big need for there to be more community driven involvement as there is a big issue with the Azure PowerShell Team to Community communications and I've suggested some possible improvements in #1826

**Comment by markcowl** [comment] 2016-03-10 18:06
@KirkMunro @doctordns @trondhindenes The candidate PR with most of this chage is here:  https://github.com/Azure/azure-powershell/pull/1922

**Comment by markcowl** [comment] 2016-07-14 03:14
Default implementation was fixed in the above PR

**Closed by markcowl** 2016-07-14 03:14 UTC
Labels: 1 - Ready, P1, ShouldProcess Normalization, Team
