### ISSUE TITLE
The access token expiry UTC time 'XXX' is earlier than current UTC time 'XXX'

### ISSUE THREAD

**Issue by nthewara** [Azure/azure-powershell#4695] opened 2017-10-02 01:27 UTC
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with Name                           Value
----                           -----
PSVersion                      5.1.15063.608
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.608
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Module Version
Powershell 4.4.0 (Ignite)

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction
Using latest Azure Powershell version, I have enabled Enable-AzureRmContextAutosave and since doing this I get token expiry error message when I try to deploy from VS Code or Visual Studio 2017

**Comment by nthewara** [comment] 2017-10-04 11:33
i can confirm that after running Disable-AzureRmContextAutosave i dont have token expiry issues anymore

**Comment by markcowl** [comment] 2017-10-04 20:58
@nthewara Yes, this is a known issue with the new cmdlets, see: https://github.com/Azure/azure-powershell/issues/4656 This is due to be fixed in our cleanup release next week.  Closing this as a duplicate of the issue.

**Closed by markcowl** 2017-10-04 20:58 UTC
Labels: Investigate, Team

**Comment by prafulbusa** [comment] 2019-06-29 21:03
Still getting error for Virtual Network, NIC, Public-IP etc...The issue is still not resolved yet.
