### ISSUE TITLE
Storage context | Missing type map configuration or unsupported mapping

### ISSUE THREAD

**Issue by cadumi** [Azure/azure-powershell#4418] opened 2017-08-07 06:47 UTC
### Cmdlet(s)
Get-AzureStorageAccount ; Get-AzureStorageAccountKey
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
https://github.com/Azure/azure-powershell/releases/tag/v4.2.1-July2017
Name                           Value                                                                                                                                          
----                           -----                                                                                                                                          
PSVersion                      5.1.15063.483                                                                                                                                  
PSEdition                      Desktop                                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                        
BuildVersion                   10.0.15063.483                                                                                                                                 
CLRVersion                     4.0.30319.42000                                                                                                                                
WSManStackVersion              3.0                                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                                            
SerializationVersion           1.1.0.1  

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

W10

### Description
Customer is trying to manage his classic resources by logging into the German Cloud using:
Login-AzureRMAccount -Environment "AzureGermanCLoud"
#switching to classic mode using
Select-AzureSubscription -SubscriptionID ...
#switching or calling the storage context with
Get-AzureStorageAccount
Get-AzureStorageAccountKey

this will fail with the below error, but not on every try. It is persistent once it appears.

Get-AzureStorageAccount : Missing type map configuration or unsupported mapping.
Mapping types:
StorageAccountGetResponse -> StorageServicePropertiesOperationContext
Microsoft.WindowsAzure.Management.Storage.Models.StorageAccountGetResponse -> Microsoft.WindowsAzure.Commands.ServiceManagement.Model.StorageServicePropertiesOperationContext
Destination path:
StorageServicePropertiesOperationContext
Source value:
Microsoft.WindowsAzure.Management.Storage.Models.StorageAccountGetResponse
At line:1 char:1
+ Get-AzureStorageAccount -StorageAccountName "pterpplaystore"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureStorageAccount], AutoMapperMappingException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.ServiceManagement.StorageServices.GetAzureStorageAccountCommand 

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction
no repro.

Any ways how I can troubleshoot this? The -debug/verbose output is not very relevant.

**Comment by cormacpayne** [comment] 2017-08-11 18:19
@blueww Hey Wei, would you mind taking a look at this issue?

**Comment by blueww** [comment] 2017-08-14 10:08
Get-AzureStorageAccount, Get-AzureStorageAccountKey are for RDFE account.
Login-AzureRMAccount is for ARM account.

Get-AzureStorageAccount and Get-AzureStorageAccountKey won't use  the credential set with "Login-AzureRMAccount", but will use the cached credential in : "%appdata%\Windows Azure Powershell"

Would you please try:

1. Close all PowerShell console
2. Clean the cached credential file in "%appdata%\Windows Azure Powershell"
3. Open new Powershell Console
4. Logon with Add-AzureAccount or Import-AzurePublishSettingsFile, and then Select-AzureSubscription 
5. Try to run Get-AzureStorageAccount and Get-AzureStorageAccountKey

**Comment by cadumi** [comment] 2017-08-14 12:07
Hi Wei,

Thanks for your input.
Unfortunately, for this customer the Add-AzureAccount login does not work as expected. See below verbose output. That's why we tried with Login-AzureRMAccount and then Select-Azuresubscription and the storage commands.
Any help is greatly appreciated on how we can work this around and log in with Add-AzureAccount.

PS C:\Windows\system32> Add-AzureAccount -Environment "AzureGermanCloud" -Verbose -Debug
DEBUG: 4:38:10 PM - AddAzureAccount begin processing with ParameterSet 'User'.
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: 'Common', Endpoint: 'https://login.microsoftonline.de/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedire
ct: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.cloudapi.de/', ValidateAuthrity: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.de/Common/', CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: 'Common', AdEndpoint: 'https://login.microsoftonline.de/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRe
directUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 08/03/2017 14:38:13: c2696a76-d42d-47b5-a474-4f1fe9c80790 - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.de/Common/
	Resource: https://management.core.cloudapi.de/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (2 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 08/03/2017 14:38:13:  - WindowsFormsWebAuthenticationDialogBase: Navigating to 'https://login.microsoftonline.de/Common/oauth2/authorize?resource=https://management.core.cloudapi.de/&client_id=19
50a258-227b-4e31-a9cf-717495945fc2&response_type=code&haschrome=1&redirect_uri=urn:ietf:wg:oauth:2.0:oob&client-request-id=c2696a76-d42d-47b5-a474-4f1fe9c80790&prompt=login&x-client-SKU=.NET&x-client-Ve
r=2.28.3.860&x-client-CPU=x64&x-client-OS=Microsoft Windows NT 10.0.10586.0&site_id=501358&display=popup'.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 08/03/2017 14:38:13:  - WindowsFormsWebAuthenticationDialogBase: Navigated to 'https://login.microsoftonline.de/Common/oauth2/authorize?resource=https://management.core.cloudapi.de/&client_id=195
0a258-227b-4e31-a9cf-717495945fc2&response_type=code&haschrome=1&redirect_uri=urn:ietf:wg:oauth:2.0:oob&client-request-id=c2696a76-d42d-47b5-a474-4f1fe9c80790&prompt=login&x-client-SKU=.NET&x-client-Ver
=2.28.3.860&x-client-CPU=x64&x-client-OS=Microsoft Windows NT 10.0.10586.0&site_id=501358&display=popup'.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 08/03/2017 14:38:44:  - WindowsFormsWebAuthenticationDialogBase: Navigating to 'https://login.microsoftonline.de/common/login'.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 08/03/2017 14:38:45:  - WindowsFormsWebAuthenticationDialogBase: WebBrowser state: IsBusy: True, ReadyState: Complete, Created: True, Disposing: False, IsDisposed: False, IsOffline: False

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 08/03/2017 14:38:45:  - WindowsFormsWebAuthenticationDialogBase: WebBrowser state (after Stop): IsBusy: False, ReadyState: Complete, Created: True, Disposing: False, IsDisposed: False, IsOffline:
 False

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 08/03/2017 14:38:45:  - TokenCache: Deserialized 2 items to token cache.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 08/03/2017 14:38:45: c2696a76-d42d-47b5-a474-4f1fe9c80790 - TokenCache: Storing token in the cache...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 08/03/2017 14:38:45: c2696a76-d42d-47b5-a474-4f1fe9c80790 - TokenCache: An item was stored in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 08/03/2017 14:38:45: c2696a76-d42d-47b5-a474-4f1fe9c80790 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
	Access Token Hash: cCqPKOs2vJSoZ5qAFh023poHvmRzweWM0SRX8i9Uvog=
	Refresh Token Hash: 7dX8vqX6foIVQ5DMcoeazVDrzMLXYGRIlx0sFwwUvqg=
	Expiration Time: 08/03/2017 15:38:44 +00:00
	User Hash: LpMOu5J1bUEAG/Wsu4g5PO+OKTOI0gxNJEIREwLNQw8=
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 08/03/2017 14:38:45:  - TokenCache: Serializing token cache with 2 items.

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.core.cloudapi.de/subscriptions

Headers:
x-ms-version                  : 2013-08-01

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
x-ms-request-id               : c51c2b12870a44de96885cc5bdec68b8
Cache-Control                 : no-cache
Date                          : Thu, 03 Aug 2017 14:38:45 GMT
Server                        : 1.0.6198.511,(rd_rdfe_stable.170710-1700),Microsoft-HTTPAPI/2.0

Body:
<Subscriptions xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance" />


Add-AzureAccount : No subscriptions are associated with the logged in account in Azure Service Management (RDFE). This means that the logged in user is not an administrator or co-administrator for any 
account.\r\nDid you mean to execute Login-AzureRmAccount?
At line:1 char:1
+ Add-AzureAccount -Environment "AzureGermanCloud" -Verbose -Debug
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Add-AzureAccount], ArgumentException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Profile.AddAzureAccount
 
DEBUG: 4:39:55 PM - AddAzureAccount end processing.
DEBUG: 4:39:55 PM - AddAzureAccount end processing.

**Comment by blueww** [comment] 2017-08-15 03:48
@markcowl , @cormacpayne , would you please help to look at the "Add-AzureAccount" issue the customer meet.  Or assign it to proper teams.

@cadumi, could you check the user really has Azure Access. From the error message it looks like the user don't have Azure RDFE access.

**Comment by cadumi** [comment] 2017-08-16 06:42
@blueww , customer has Azure access, as the Login-AzureRM command works just fine. only Add-AzureAccount does not work.
I alwo have this opened ICM 44106566 . but no owner.

**Comment by blueww** [comment] 2017-08-16 07:16
@cadumi, I see a similar issue resolved in https://social.msdn.microsoft.com/Forums/en-US/e6bdb2f3-c3b0-4a99-b75d-3493cf63e03b/loginazurermaccount-vs-addazureaccount?forum=azurescripting

The issue resolved when the user was set as Co-admin on old portal on subscription.

**Comment by cadumi** [comment] 2017-08-16 07:20
@blueww , this is happening under the German Cloud as mentioned in first posts, so there is no old portal in the german cloud only the new one.
Classic resources can only be accessed trough Powershell for Black Forest.

**Comment by blueww** [comment] 2017-08-16 08:53
@markcowl , @cormacpayne, this is a not a storage cmdlet issue, but a login issue with Add-AzureAccount. Would you please help to look at it? And remove the storage tag.

@cadumi, if there's no old portal in german cloud, then why you need use service mode account? Why not use resource mode account. You can use all service (Blob, File, Queue, Table) support in service mode account , in Resource mode Account.

**Comment by cadumi** [comment] 2017-08-21 07:28
@blueww , that is what we were trying to do, meaning login-azurermaccount then select-subscription "SubID" and manage the classic storage accounts, but then we get the error above:
Get-AzureStorageAccount : Missing type map configuration or unsupported mapping.

**Comment by blueww** [comment] 2017-08-21 09:13
@markcowl  @cormacpayne , could you help on the login issue of “Add-AzureAccount” ?

@cadumi, Yes, the issue if cause you can't manage RDFE account with ARM credential. Before the RDFE login issue is resolved, Can use you ARM account, it also support service (Blob, File, Queue, Table)?

**Comment by josephsctan** [comment] 2017-09-01 02:02
Hi Folks,

I am running Azure Powershell 4.3.1 and having the same issue. 

Get-AzureStorageAccount  was working find for me, and then suddenly stopped working.

Now it **always** returns the following: 

> Get-AzureStorageAccount -StorageAccountName  [...redacted...]
> Get-AzureStorageAccount : Missing type map configuration or unsupported mapping.
> Mapping types:
> StorageAccountGetResponse -> StorageServicePropertiesOperationContext
> Microsoft.WindowsAzure.Management.Storage.Models.StorageAccountGetResponse ->
> Microsoft.WindowsAzure.Commands.ServiceManagement.Model.StorageServicePropertiesOperationContext
> Destination path:
> StorageServicePropertiesOperationContext
> Source value:
> Microsoft.WindowsAzure.Management.Storage.Models.StorageAccountGetResponse
 

Once this happens, it is no longer possible to manage that Classic storage account with powershell.

**Comment by blueww** [comment] 2017-09-01 02:17
@josephsctan 

The issue seems caused by use the ARM credential to manage the RDFE (class) accounts. Since the source is from "Microsoft.WindowsAzure.Management.Storage" which is from ARM accounts

To do more investigate on the issue, could you run and give the result:
Get-module
Get-AzureStorageAccount -debug

To resolve your issue, could you try:
1.Close all PowerShell console
2.Clean the cached credential file in "%appdata%\Windows Azure Powershell"
3.Open new Powershell Console
4.Login with Add-AzureAccount or Import-AzurePublishSettingsFile, and then Select-AzureSubscription
5.Try to run Get-AzureStorageAccount or Get-AzureStorageAccountKey

**Comment by cormacpayne** [comment] 2017-10-05 18:31
@cadumi @josephsctan @blueww we believe this is an issue with `AutoMapper` being used statically across numerous modules. I have a PR open to make a mapper instance for each module, which _should_ resolve the above issue: https://github.com/Azure/azure-powershell/pull/4679

We are looking to get this fix into the release that goes out on Tuesday (October 10th).

**Comment by cormacpayne** [comment] 2017-10-26 19:18
The fix for this has been merged and will be available in the November release of Azure PowerShell (version 5.0.0 - set to release November 8th)The fix for this has been merged and will be available in the November release of Azure PowerShell (version 5.0.0 - set to release November 8th)

**Comment by cormacpayne** [comment] 2017-11-08 18:55
@cadumi @josephsctan @blueww a potential fix for this has been merged in [Azure PowerShell 5.0.0](https://github.com/Azure/azure-powershell/releases/tag/v5.0.0-November2017). Would anyone be able to validate this?

**Comment by huan086** [comment] 2017-11-09 02:08
v4 not working for me. v5 works. Thanks for the fix!

**Comment by blueww** [comment] 2018-01-29 08:43
Close as the issue already fixed on  Azure PowerShell 5.0.0.

**Closed by blueww** 2018-01-29 08:43 UTC
Labels: Storage
