### ISSUE TITLE
Add-AzureRmAccount: Add mechanism to go directly to Microsoft Account authentication

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2870] opened 2016-08-31 14:53 UTC
### Cmdlet(s)

Add-AzureRmAccount
### PowerShell Version

Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
### Module Version

2.01 - AzureRM.Profile
### OS Version

Windows 10 Anniversary Update
### Description

Please add a mechanism to go directly to Microsoft Account authentication, and bypass the AAD login screen.
### Script/Steps for Reproduction
1. Run `Add-AzureRmAccount`
2. Type in Microsoft Account (MSA) e-mail address
3. User is redirected to Microsoft Account login page

This UX is less than ideal, considering the redirect is unnecessary, from a UX perpsective.

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by markcowl** [comment] 2016-09-12 18:39
### Description

Mechanism for going direcftly to 'MSA' versus 'School or Business' login - this by passes one level of UI that can make login annoying.

Investigate the feasibility of using existing APIs for this, and file issues for the necessary changes - this would mean option parameters to choose MSA or OrgId login, or using a -UserId setting to decide at the beginning.

### Cost: 1

**Comment by twitchax** [comment] 2017-01-30 02:54
Approved for investigation.  If existing APIs can achieve this, then I propose we fix.  If this behavior cannot be addressed without large changes to existing infrastructure, then I propose we close as by design.

@markcowl, @cormacpayne, @shahabhijeet, do we have any time this milestone to make this investigation?  Or, should we coalesce this into future auth changes?

**Comment by markcowl** [comment] 2017-11-07 23:32
Closing for lack of user comments.  Please reopen if this continues to be a pain point.

**Closed by markcowl** 2017-11-07 23:32 UTC
Labels: Azure PS Team, Investigate
