### ISSUE TITLE
Get-AzStorageAccount : Unable to deserialize the response.

### ISSUE THREAD

**Issue by ivanignatiev** [Azure/azure-powershell#11765] opened 2020-04-30 08:55 UTC
## Description

Not sure where to report this bug to Azure Storage or Az. 

I do not how but I succeed to deploy a Storage Account with wrong `accessTier` property value.  After I execute `$st = Get-AzStorageAccount -ResourceGroupName $ResourceGroupeName -Name $StorageAccountName` I got: 

```
Get-AzStorageAccount : Unable to deserialize the response.
Au caractère Ligne:1 : 7
+ $st = Get-AzStorageAccount -ResourceGroupName $ResourceGroupeName ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError : (:) [Get-AzStorageAccount], SerializationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Management.Storage.GetAzureStorageAccountCommand 
```

## Steps to reproduce

Deploy a storage account with template and `"accessTier": "0",`
```
 {
            "type": "Microsoft.Storage/storageAccounts",
            "apiVersion": "2019-04-01",
            "name": "[parameters('name')]",
            "location": "[parameters('location')]",
            "tags": "[parameters('tags')]",
            "sku": {
                "name": "[parameters('sku').name]",
                "tier": "[parameters('sku').tier]"
            },
            "kind": "[parameters('sku').kind]",
            "identity": {
                "type": "SystemAssigned"
            },
            "properties": {
                "supportsHttpsTrafficOnly": true,
                "accessTier": "0",
		"networkAcls": {
			"bypass": "AzureServices",
			"defaultAction": "Deny",
		}
           }
        }
```

## Environment data

```
Name                           Value                                                                                                        
----                           -----                                                                                                        
PSVersion                      5.1.18362.628                                                                                                
PSEdition                      Desktop                                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                      
BuildVersion                   10.0.18362.628                                                                                               
CLRVersion                     4.0.30319.42000                                                                                              
WSManStackVersion              3.0                                                                                                          
PSRemotingProtocolVersion      2.3                                                                                                          
SerializationVersion           1.1.0.1
```

## Module versions

```powershell
 Az 3.4.0
 Az.Storage 1.10.0
```

## Debug output

```
DÉBOGUER : 10:43:30 - GetAzureStorageAccountCommand begin processing with ParameterSet 'AccountNameParameterSet'.
DÉBOGUER : 10:43:32 - using account id '***'...
DÉBOGUER : [Common.Authentication]: Authenticating using Account: '***', environment: 'AzureCloud', tenant: '***'
DÉBOGUER : [Common.Authentication]: Authenticating using configuration values: Domain: '***', Endpoint: 'https://login.microsoftonline.com/', ClientId: '***', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthority: 'True'
DÉBOGUER : [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/***/', CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DÉBOGUER : [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: '***', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: '***', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DÉBOGUER : [ADAL]: Information: 2020-04-30T08:43:32.1792091Z: fb1f5a72-8b46-406a-8c7b-97a78933bb8a - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...

DÉBOGUER : [ADAL]: Information: 2020-04-30T08:43:32.1792091Z: fb1f5a72-8b46-406a-8c7b-97a78933bb8a - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...

DÉBOGUER : [ADAL]: Information: 2020-04-30T08:43:32.1792091Z: fb1f5a72-8b46-406a-8c7b-97a78933bb8a - LoggerBase.cs: === Token Acquisition started: 
	CacheType: null
	Authentication Target: User
	, Authority Host: login.microsoftonline.com

DÉBOGUER : [ADAL]: Information: 2020-04-30T08:43:32.1792091Z: fb1f5a72-8b46-406a-8c7b-97a78933bb8a - LoggerBase.cs: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/***/
	Resource: https://management.core.windows.net/
	ClientId: ***
	CacheType: null
	Authentication Target: User
	
DÉBOGUER : [ADAL]: Verbose: 2020-04-30T08:43:32.1792091Z: fb1f5a72-8b46-406a-8c7b-97a78933bb8a - LoggerBase.cs: Loading from cache.
DÉBOGUER : [ADAL]: Verbose: 2020-04-30T08:43:32.1792091Z: fb1f5a72-8b46-406a-8c7b-97a78933bb8a - LoggerBase.cs: Loading from cache.
DÉBOGUER : [ADAL]: Information: 2020-04-30T08:43:32.1802061Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Deserialized 4 items to token cache.
DÉBOGUER : [ADAL]: Verbose: 2020-04-30T08:43:32.1812058Z: fb1f5a72-8b46-406a-8c7b-97a78933bb8a - LoggerBase.cs: Looking up cache for a token...
DÉBOGUER : [ADAL]: Verbose: 2020-04-30T08:43:32.1812058Z: fb1f5a72-8b46-406a-8c7b-97a78933bb8a - LoggerBase.cs: Looking up cache for a token...
DÉBOGUER : [ADAL]: Information: 2020-04-30T08:43:32.1812058Z: fb1f5a72-8b46-406a-8c7b-97a78933bb8a - LoggerBase.cs: An item matching the requested resource was found in the cache
DÉBOGUER : [ADAL]: Information: 2020-04-30T08:43:32.1812058Z: fb1f5a72-8b46-406a-8c7b-97a78933bb8a - LoggerBase.cs: An item matching the requested resource was found in the cache
DÉBOGUER : [ADAL]: Information: 2020-04-30T08:43:32.1812058Z: fb1f5a72-8b46-406a-8c7b-97a78933bb8a - LoggerBase.cs: 12,4729132366667 minutes left until token in cache expires
DÉBOGUER : [ADAL]: Information: 2020-04-30T08:43:32.1812058Z: fb1f5a72-8b46-406a-8c7b-97a78933bb8a - LoggerBase.cs: 12,4729132366667 minutes left until token in cache expires
DÉBOGUER : [ADAL]: Information: 2020-04-30T08:43:32.1812058Z: fb1f5a72-8b46-406a-8c7b-97a78933bb8a - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache
DÉBOGUER : [ADAL]: Information: 2020-04-30T08:43:32.1812058Z: fb1f5a72-8b46-406a-8c7b-97a78933bb8a - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache
DÉBOGUER : [ADAL]: Information: 2020-04-30T08:43:32.1812058Z: fb1f5a72-8b46-406a-8c7b-97a78933bb8a - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 30/04/2020 08:56:00 +00:00
DÉBOGUER : [ADAL]: Information: 2020-04-30T08:43:32.1812058Z: fb1f5a72-8b46-406a-8c7b-97a78933bb8a - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 30/04/2020 08:56:00 +00:00Access Token Hash: ****
	 User id: ***

DÉBOGUER : [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '04/30/2020 08:56:00 +00:00', MultipleResource? 'True', Tenant: '***', UserId: '***'
DÉBOGUER : [Common.Authentication]: User info for token DisplayId: '***', Name:  , IdProvider: 'https://sts.windows.net/***/', Uid: '***'
DÉBOGUER : [Common.Authentication]: Checking token expiration, token expires '04/30/2020 08:56:00 +00:00' Comparing to '04/30/2020 08:43:32 +00:00' With threshold '00:05:00', calculated time until token expiry: '00:12:28.3737991'
DÉBOGUER : ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/***/resourceGroups/RGNAME/providers/Microsoft.Storage/storageAccounts/***?api-version=2019-06-01

Headers:
x-ms-client-request-id        : 7179448c-6f1f-427a-84ad-db2129419e0c
accept-language               : en-US

Body:



DÉBOGUER : ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-request-id               : 577f54bb-aeaf-42b2-9643-c77e531cb895
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-reads: 11985
x-ms-correlation-request-id   : 1047544a-2557-405e-a767-0a9bc333c6fe
x-ms-routing-request-id       : FRANCECENTRAL:20200430T084540Z:1047544a-2557-405e-a767-0a9bc333c6fe
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Thu, 30 Apr 2020 08:45:39 GMT
Server                        : Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0

Body:
{
  "identity": {
    "principalId": "***",
    "tenantId": "***",
    "type": "SystemAssigned"
  },
  "sku": {
    "name": "Standard_LRS",
    "tier": "Standard"
  },
  "kind": "StorageV2",
  "id": "/subscriptions/***/resourceGroups/RGNAME/providers/Microsoft.Storage/storageAccounts/***",
  "name": "***",
  "type": "Microsoft.Storage/storageAccounts",
  "location": "northeurope",
  "tags": {},
  "properties": {
    "privateEndpointConnections": [],
    "networkAcls": {
      "bypass": "AzureServices",
      "virtualNetworkRules": [
        {
          "id": "/subscriptions/***/resourceGroups/RGNAME/providers/Microsoft.Network/virtualNetworks/VNETNAME/subnets/SUBNETNAME",
          "action": "Allow",
          "state": "Succeeded"
        },
        {
          "id": "/subscriptions/***/resourceGroups/RGNAME/providers/Microsoft.Network/virtualNetworks/VNETNAME/subnets/SUBNETNAME",
          "action": "Allow",
          "state": "Succeeded"
        }
      ],
      "ipRules": [
        {
          "value": "***",
          "action": "Allow"
        },
        {
          "value": "***",
          "action": "Allow"
        }
      ],
      "defaultAction": "Deny"
    },
    "supportsHttpsTrafficOnly": true,
    "encryption": {
      "keyvaultproperties": {
        "currentVersionedKeyIdentifier": "https://***.vault.azure.net/keys/***-key/***",
        "lastKeyRotationTimestamp": "2020-04-23T05:18:04.0928592Z",
        "currentVersionedKeyExpirationTimestamp": "1970-01-01T00:00:00Z",
        "keyvaulturi": "https://***.vault.azure.net/",
        "keyname": "***-key",
        "keyversion": "***"
      },
      "services": {
        "file": {
          "keyType": "Account",
          "enabled": true,
          "lastEnabledTime": "2020-04-23T05:09:11.9802042Z"
        },
        "blob": {
          "keyType": "Account",
          "enabled": true,
          "lastEnabledTime": "2020-04-23T05:09:11.9802042Z"
        }
      },
      "keySource": "Microsoft.Keyvault"
    },
    "accessTier": "Invalid",
    "provisioningState": "Succeeded",
    "creationTime": "2020-04-23T05:09:11.9021073Z",
    "primaryEndpoints": {
      "dfs": "https://***.dfs.core.windows.net/",
      "web": "https://***.z16.web.core.windows.net/",
      "blob": "https://***.blob.core.windows.net/",
      "queue": "https://***.queue.core.windows.net/",
      "table": "https://***.table.core.windows.net/",
      "file": "https://***.file.core.windows.net/"
    },
    "primaryLocation": "northeurope",
    "statusOfPrimary": "available"
  }
}


Get-AzStorageAccount : Unable to deserialize the response.
Au caractère Ligne:4 : 7
+ $st = Get-AzStorageAccount -ResourceGroupName $ResourceGroupName -Nam ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError : (:) [Get-AzStorageAccount], SerializationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Management.Storage.GetAzureStorageAccountCommand
 
DÉBOGUER : AzureQoSEvent: CommandName - Get-AzStorageAccount; IsSuccess - False; Duration - 00:00:02.4741759; Exception - Microsoft.Rest.SerializationException: Unable to deserialize the response. ---> Newtonsoft.Json.JsonSerializationException: Error converting value "Invalid" to 
type 'System.Nullable`1[Microsoft.Azure.Management.Storage.Models.AccessTier]'. Path 'properties.accessTier', line 1, position 2472. ---> System.ArgumentException: La valeur demandée 'Invalid' est introuvable.
   à System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   à System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   à Newtonsoft.Json.Utilities.EnumUtils.ParseEnumName(String enumText, Boolean isNullable, Boolean disallowValue, Type t)
   à Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   --- Fin de la trace de la pile d'exception interne ---
   à Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   à Microsoft.Rest.Serialization.TransformationJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
   à Microsoft.Azure.Management.Storage.StorageAccountsOperations.<GetPropertiesWithHttpMessagesAsync>d__8.MoveNext()
   --- Fin de la trace de la pile d'exception interne ---
   à Microsoft.Azure.Management.Storage.StorageAccountsOperations.<GetPropertiesWithHttpMessagesAsync>d__8.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   à Microsoft.Azure.Management.Storage.StorageAccountsOperationsExtensions.<GetPropertiesAsync>d__7.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à Microsoft.Azure.Management.Storage.StorageAccountsOperationsExtensions.GetProperties(IStorageAccountsOperations operations, String resourceGroupName, String accountName, Nullable`1 expand)
   à Microsoft.Azure.Commands.Management.Storage.GetAzureStorageAccountCommand.ExecuteCmdlet()
   à Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DÉBOGUER : Finish sending metric.
DÉBOGUER : 10:43:34 - GetAzureStorageAccountCommand end processing.
DÉBOGUER : 10:43:34 - GetAzureStorageAccountCommand end processing.
```

## Error output

```
 HistoryId : 28


Message        : Unable to deserialize the response.
StackTrace     :    à Microsoft.Azure.Management.Storage.StorageAccountsOperations.<GetPropertiesWithHttpMessagesAsync>d__8.MoveNext()
                 --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                    à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    à System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
                    à Microsoft.Azure.Management.Storage.StorageAccountsOperationsExtensions.<GetPropertiesAsync>d__7.MoveNext()
                 --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                    à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                    à Microsoft.Azure.Management.Storage.StorageAccountsOperationsExtensions.GetProperties(IStorageAccountsOperations 
                 operations, String resourceGroupName, String accountName, Nullable`1 expand)
                    à Microsoft.Azure.Commands.Management.Storage.GetAzureStorageAccountCommand.ExecuteCmdlet()
                    à Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Rest.SerializationException
InvocationInfo : {Get-AzStorageAccount}
Line           : $st = Get-AzStorageAccount -ResourceGroupName $ResourceGroupName -Name $StorageAccountName -Debug
Position       : Au caractère Ligne:4 : 7
                 + $st = Get-AzStorageAccount -ResourceGroupName $ResourceGroupName -Nam ...
                 +       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 28

Message        : Error converting value "Invalid" to type 'System.Nullable`1[Microsoft.Azure.Management.Storage.Models.AccessTier]'. Path 
                 'properties.accessTier', line 1, position 2472.
StackTrace     :    à Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, 
                 JsonSerializer serializer)
                    à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader 
                 reader, Type objectType, Object existingValue)
                    à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean 
                 checkAdditionalContent)
                    à Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
                    à Microsoft.Rest.Serialization.TransformationJsonConverter.ReadJson(JsonReader reader, Type objectType, Object 
                 existingValue, JsonSerializer serializer)
                    à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader 
                 reader, Type objectType, Object existingValue)
                    à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean 
                 checkAdditionalContent)
                    à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
                    à Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
                    à Microsoft.Azure.Management.Storage.StorageAccountsOperations.<GetPropertiesWithHttpMessagesAsync>d__8.MoveNext()
Exception      : Newtonsoft.Json.JsonSerializationException
InvocationInfo : {Get-AzStorageAccount}
Line           : $st = Get-AzStorageAccount -ResourceGroupName $ResourceGroupName -Name $StorageAccountName -Debug
Position       : Au caractère Ligne:4 : 7
                 + $st = Get-AzStorageAccount -ResourceGroupName $ResourceGroupName -Nam ...
                 +       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 28

Message        : La valeur demandée 'Invalid' est introuvable.
StackTrace     :    à System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
                    à System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
                    à Newtonsoft.Json.Utilities.EnumUtils.ParseEnumName(String enumText, Boolean isNullable, Boolean disallowValue, Type t)
                    à Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, 
                 JsonSerializer serializer)
Exception      : System.ArgumentException
InvocationInfo : {Get-AzStorageAccount}
Line           : $st = Get-AzStorageAccount -ResourceGroupName $ResourceGroupName -Name $StorageAccountName -Debug
Position       : Au caractère Ligne:4 : 7
                 + $st = Get-AzStorageAccount -ResourceGroupName $ResourceGroupName -Nam ...
                 +       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 28
```

**Comment by blueww** [comment] 2020-04-30 10:37
@ivanignatiev 
From the log, it looks like the error is caused by ""accessTier": "Invalid"" in your account.
I will contact feature team to see if it's a server issue , or swagger issue. 

For the work around, would you like to update the account Acces tier to Hot or Cool, then list again?
```powershell
Set-AzStorageAccount -ResourceGroupName $rgname -StorageAccountName $accountName -AccessTier Hot
```

**Comment by ivanignatiev** [comment] 2020-04-30 11:51
@bluewwThank you! I confirm that with correctly set Access Tier everything is working good

**Comment by blueww** [comment] 2020-05-01 09:06
@ivanignatiev 
Thanks for the update!
I think you are not blocked now.

And as "0" is not a valid "Accesstier", do you mind to change the deployment template, by remove following line, and see if any issue?

>  "accessTier": "0",

Besides that,I have contact featture team, and they agree server should not allow set "0" to accesstier. They will see how to fix it on server. 

Since there seems nothing we can do from Powershell now, do you mind I close the issue?

**Comment by ivanignatiev** [comment] 2020-05-01 11:35
@blueww thank you ! I do not have any blocker. We can close the issue if it is ok for you.

**Comment by blueww** [comment] 2020-05-01 11:37
@ivanignatiev
Thanks for confirmation!
I will close the issue.
Feel free to contact us if you need any further assistance on Azure Powershell.

**Closed by blueww** 2020-05-01 11:37 UTC
Labels: customer-reported, question, triage
