### ISSUE TITLE
PowerShellExtensions Code Error for string formatting

### ISSUE THREAD

**Issue by ankushbindlish2** [Azure/azure-powershell#8455] opened 2019-01-30 23:26 UTC
### Description

While debugging Unit test, I encountered this error.
Source code : c:\code\azure-powershell\tools\ScenarioTest.ResourceManager\PowerShellExtensions.cs
Bug in line : xunitLogger.Information(string.Format("{0}\n", item.ToString()));
Proposal : xunitLogger.Information(item.ToString() + Environment.NewLine);
*****************
============================ HTTP RESPONSE ============================

Status Code:
Forbidden

Headers:
Cache-Control                 : no-cache
Date                          : Wed, 30 Jan 2019 23:16:39 GMT
Pragma                        : no-cache
Server                        : Microsoft-IIS/10.0
ocp-aad-diagnostics-server-name: 68S1qiYTGdlYlteO57AcAfRdh6gxMgQ4BOpjpsClWbY=
request-id                    : dcddd24e-638b-4c73-bb24-3713f6af15ec
client-request-id             : 53b037fe-e36f-44a1-875b-74bb61922301
x-ms-dirapi-data-contract-version: 1.6
ocp-aad-session-key           : 8KwKaE57PCBbAqwK6whWE4NIvckimu25P5DY0FpP2FoR0YcB_d9sZyDMDRUMZBShWpimQznC30FmU1xefN2qAi5lqAQtB0_OvGXvvBMjgBP5B7BahK2LmYLbqbG7DTp7.rji8uhc0fKsbeghBH9DYbI4r0A2l_HYKDBtAcDpH-do
DataServiceVersion            : 3.0;
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Access-Control-Allow-Origin   : *
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET
Duration                      : 608227

Body:
{
  "odata.error": {
    "code": "Authorization_RequestDenied",
    "message": {
      "lang": "en",
      "value": "Insufficient privileges to complete the operation."
    },
    "requestId": "dcddd24e-638b-4c73-bb24-3713f6af15ec",
    "date": "2019-01-30T23:16:39"
  }
}

*****************

### Script/Steps for Reproduction

```powershell

```

### Module Version

```powershell
Get-Module -ListAvailable
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by vladimir-shcherbakov** [comment] 2019-01-31 19:34
@ankushbindlish2  What makes you think there is a bug in the line?

**Comment by ankushbindlish2** [comment] 2019-01-31 19:47
Though, the exception would conveniently absorved but the above message will not be logged. 
It is same as string.Format(string.Format("{0}", "{sdfs}"), null);

c:\code\azure-powershell\tools\ScenarioTest.ResourceManager\XunitTracingInterceptor.cs
private void Write(string message, params object[] arguments)
        {
            try
            {
                traceOutputArray.Add(string.Format(message, arguments));
            }
            catch { }
        }

**Comment by markcowl** [comment] 2019-01-31 21:10
How can this line have a formatexception?  It has only one element and one parameter.  If you can reproduce this, please place the test of the format exception, including the values that produced the format exception, and we will be happy to fix.  Also, please feel free to submit a PR for this.

**Comment by ankushbindlish2** [comment] 2019-01-31 21:21
I am not sure why we are eager to close the issue without understanding the problem or even having a conversation with issue creator. 


**Call Sequence :** 
xunitLogger.Information(string.Format("{0}\n", item.ToString()));  [A]
..
Write(string message, params object[] arguments)
    traceOutputArray.Add(string.Format(message, arguments));  [B]

**Line B will fail** : If item has braces { } in it, string.Format [B] above will have message with braces in it with arguments null
@markcowl, I didn't suggest string.Format fails for Line A.
**No Impact on scenario :** catch all exceptions will helps absorb the exception but impacts tracing **only**.

I am reopening this issue and let you close the comment. I will not spend more time on this.

**Comment by markcowl** [comment] 2019-03-07 20:42
So the issue is actually here: https://github.com/Azure/azure-powershell/blob/af37e27433527fbcfebe5f52fdc510b4e9ac14e2/tools/ScenarioTest.ResourceManager/XunitTracingInterceptor.cs#L44 

Where a message sent with no arguments should simply be written without using string.format.

This is a simple enough fix - we just need to treat the single string and string with arguments separately in the Write method.

**Comment by ankushbindlish2** [comment] 2019-03-07 22:03
Yes. That's correct.

**Comment by markcowl** [comment] 2019-03-08 18:59
Fixed in #8725

**Closed by markcowl** 2019-03-08 18:59 UTC
Labels: Azure PS Team, Investigate :mag:

**Comment by ankushbindlish2** [comment] 2019-03-08 19:02
Thank you !
