### ISSUE TITLE
Get-AzureStorageTable & Get-AzureStorageContainer not respecting -ErrorAction

### ISSUE THREAD

**Issue by shiningdragon** [Azure/azure-powershell#1270] opened 2015-11-10 15:50 UTC
Get-AzureStorageContainer -Name 'blah' -Context $myContext -ErrorAction SilentlyContinue

and 
Get-AzureStorageTable -Name 'blah' -Context $myContext -ErrorAction SilentlyContinue

both throw an error when the resource doesnt exist - error should be suppressed - this was working in 0.9.8

**Comment by markcowl** [comment] 2015-11-11 00:48
closing as duplicate of #1135

**Closed by markcowl** 2015-11-11 00:48 UTC
