### ISSUE TITLE
Docs repeat themselves Docs repeat themselves

### ISSUE THREAD

**Issue by MisinformedDNA** [Azure/azure-powershell#6828] opened 2018-08-01 19:37 UTC
If you go [here](https://docs.microsoft.com/en-us/powershell/module/azurerm.datalakeanalytics/submit-azurermdatalakeanalyticsjob?view=azurermps-6.6.0#syntax) you will see the syntax repeated 6 times.

Also, the navigation link `Inputs` is repeated 6 times.

Finally, the `Inputs` sections seems like a poorly duplicated version of the `Required` and `Optional` sections. `Output` could use a link to the type or something, looks wrong.

**Comment by markcowl** [comment] 2018-08-01 22:02
@MisinformedDNA By Design By Design :-)

Actually, the first issue is that these syntax blocks represent different parameter sets, and the parameter set names are not shown in the heading for each syntax block, as they are if you use ```Get-Help``` to get the same data.

Also, the issue is that the parameter sets for this particular cmdlet could use a bit of fixing,a s they are ambiguous (multiple parameter sets using the same number of string-typed positional parameters).

As for the Inputs section, this is an experimental usage of the Inputs section to delineate piped parameters by type - we really need to limit this to the types that accept input piped by Value (just one), or be specific about the parameter set when specifying parameters that accept pipeline input ByPropertyName

**Comment by dingmeng-xue** [comment] 2020-07-13 06:25
@MisinformedDNA , The similar syntax repeated couple times because optional parameters `script` and `script` are mutual exclusive. So, PowerShell needs to similar syntax to present them. In addition, this cmdlet needs to support Recurrence and pipeline. As the result, there are 6 parameter sets totally.  It's expected from design perspective.  Closing this issue now. 

Please contact us if you have meet further issue.

**Closed by dingmeng-xue** 2020-07-13 06:25 UTC
Labels: Azure PS Team, Doc - Reference
