### ISSUE TITLE
Get-AzureRmImage fails to set BlobUri

### ISSUE THREAD

**Issue by mcollier** [Azure/azure-powershell#3730] opened 2017-04-05 18:12 UTC
The Get-AzureRmImage cmdlet fails to set the StorageProfile.OsDisk.BlobUri property value for an Image based on a VM using Managed Disks.

### PowerShell Version
5.1.15063.0

### Module Version
3.7.0 - AzureRM
2.8.0 - AzureRM.Compute

### OS Version
10.0.15063.0

### Description
The Get-AzureRmImage cmdlet fails to set the StorageProfile.OsDisk.BlobUri property value for an Image based on a VM using Managed Disks.

### Debug Output
Attached
[Get-AzureRmImage Debug Output.txt](https://github.com/Azure/azure-powershell/files/900364/Get-AzureRmImage.Debug.Output.txt)

### Script/Steps for Reproduction
Attempt to get an Image. Get the resulting object's StorageProfile.OsDisk. The BlobUri value is empty.

**Comment by shahabhijeet** [comment] 2017-04-07 19:01
@mcollier I have asked our service team to take a look at this issue.

**Comment by mcollier** [comment] 2017-04-10 02:56
@shahabhijeet The more I think about this, the more I think it is **not** a bug (esp. as it relates to Manged Disks). For an Managed Disk Image, you shouldn’t really be concerned with the underlying blob. The blob is only necessary when you need to copy the Image to another region or subscription. And for that scenario, one would likely be better off (currently) working with snapshots.

**Comment by markcowl** [comment] 2017-05-19 18:13
@singhkays Can you take a look?  Is @mcollier right about the difference between managed disks and 'unmanaged' disks in this scenario?

**Comment by singhkays** [comment] 2017-05-19 23:38
Yes, I think this is by design since MD hides the underlying blob from the user for security.

**Comment by maddieclayton** [comment] 2018-03-10 01:25
@singhkays Can we close this issue?

**Comment by singhkays** [comment] 2018-04-19 23:11
@mcollier The value for BlobUri is only set when the image source is a native blob.

**Closed by singhkays** 2018-04-19 23:11 UTC
Labels: Compute - Images
