### ISSUE TITLE
SharedTokenCacheCredential authentication unavailable

### ISSUE THREAD

**Issue by ABurhanKhan** [Azure/azure-powershell#15015] opened 2021-05-17 09:21 UTC
Unable to connect Azure after upgrade the power shell, please check below error

PS C:\Windows\system32> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  906    

## Description

PS C:\Windows\system32> Install-Module -Name PowerShellGet -Force

PS C:\Windows\system32> Connect-AzAccount
WARNING: Unable to acquire token for tenant 'ae5f9c40-55d3-4be7-920e-d6fa05f82e9b' with error 'SharedTokenCacheCredential authentication una
vailable. Token acquisition failed for user faburhan@yahoo.com. Ensure that you have authenticated with a developer tool that supports Azure
 single sign on.'
WARNING: Unable to acquire token for tenant '6171e1a1-b822-451c-b9bb-e6e35d88b0db' with error 'SharedTokenCacheCredential authentication una
vailable. Token acquisition failed for user faburhan@yahoo.com. Ensure that you have authenticated with a developer tool that supports Azure
 single sign on.'
WARNING: Unable to acquire token for tenant 'd33b9929-8c73-489a-b4c3-62669c1783a1' with error 'SharedTokenCacheCredential authentication una
vailable. Token acquisition failed for user faburhan@yahoo.com. Ensure that you have authenticated with a developer tool that supports Azure
 single sign on.'

**Comment by dingmeng-xue** [comment] 2021-05-18 12:12
Thanks for reporting. Could you try `Connect-AzAccount -Tenant ae5f9c40-55d3-4be7-920e-d6fa05f82e9b`

**Comment by ShrutiMishra871** [comment] 2021-05-21 21:16
I too am facing this issue.

**Comment by ABurhanKhan** [comment] 2021-05-22 16:28
Now it is workin fine


Sent from Yahoo Mail for iPhone


On Saturday, May 22, 2021, 1:16 AM, ShrutiMishra871 ***@***.***> wrote:




I too am facing this issue.

**Comment by dingmeng-xue** [comment] 2021-05-27 00:50
@ShrutiMishra871, are you still facing this issue? If yes, please share the debug log. You can turn on it via `$DebugPreference = "Continue"`

**Comment by ShrutiMishra871** [comment] 2021-05-27 21:24
@dingmeng-xue It's now working with Connect-AzAccount -Tenant TenantID. Thank you for helping.

**Comment by ABurhanKhan** [comment] 2021-06-04 10:39
Thank you, 
The issue is already resolved and I had already responded to you in my last email.
Best regards,
Burhan AliIT System Analyst,
Abu-Dhabi Commercial Bank Abu-Dhabi 
***@***.***+971552157954

 

    On Friday, June 4, 2021, 06:02:28 AM GMT+4, msftbot[bot] ***@***.***> wrote:  
 
 


Hi, we're sending this friendly reminder because we haven't heard back from you in a while. We need more information about this issue to help address it. Please be sure to give us your input within the next 7 days. If we don't hear back from you within 14 days of this comment the issue will be automatically closed. Thank you!

**Comment by dingmeng-xue** [comment] 2021-06-04 10:40
Thanks. Close it now.

**Closed by dingmeng-xue** 2021-06-04 10:40 UTC
Labels: Authentication, customer-reported, needs-team-attention, question

**Comment by craig-martin** [comment] 2021-08-04 19:17
What was the resolution?  I'm seeing this issue too.

**Comment by dingmeng-xue** [comment] 2021-08-05 00:57
@craig-martin , please create a new github issue to track it. The root cause or solution may be different even though the error message is the same.

**Comment by nathanfisk** [comment] 2022-01-07 11:02
> Thanks for reporting. Could you try `Connect-AzAccount -Tenant ae5f9c40-55d3-4be7-920e-d6fa05f82e9b`

For anyone facing this issue, this fixed it for me today
