### ISSUE TITLE
Storage account not found. The selected service connection 'Service Principal' supports storage accounts of Azure Resource Manager type only.

### ISSUE THREAD

**Issue by diegum** [Azure/azure-powershell#19209] opened 2022-08-11 19:00 UTC
### Description

I'm getting the same issue described in [this Azure Pipeline Tasks repo thread](https://github.com/microsoft/azure-pipelines-tasks/issues/14647).

In that occasion, it stopped happening on its own. [The contributor closing the issue](https://github.com/microsoft/azure-pipelines-tasks/issues/14647#issuecomment-813354508) asked to file a ticket here if it happened again, alleging that _"Az commands are not able to retrieve storage accounts immediately."_

### Issue script & Debug output

```PowerShell
# Azure file copy task on my ADO pipeline
- task: AzureFileCopy@4
  displayName: 'Checking AzureFileCopy'
  inputs:
    sourcePath: <path/to/the/file/to/copy>
    connectedServiceNameARM: <my service connection>
    destination: AzureVMs
    storage: <my storage account>
    resourceGroup: <my resource group>
    machineNames: <my VM>
    vmsAdminUserName: <VM admin>
    vmsAdminPassword: <VM admin password>
    targetPath: <internal\vm\path\to\the\copy\destination\folder>
    cleanTargetBeforeCopy: true
```

### Environment data

```PowerShell
I don't have that info available as this runs inside the Azure DevOps sandbox. I believe that it's Windows PowerShell (as opposed to PowerShell Core.)
```

### Module versions

```PowerShell
Import-Module -Name C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.2.8\Az.Accounts.psd1 -Global
Import-Module -Name C:\Program Files\WindowsPowerShell\Modules\Az.Resources\3.5.0\Az.Resources.psd1 -Global
Import-Module -Name C:\Program Files\WindowsPowerShell\Modules\Az.Storage\3.6.0\Az.Storage.psd1 -Global
Import-Module -Name C:\Program Files\WindowsPowerShell\Modules\Az.Compute\4.12.0\Az.Compute.psd1 -Global
Import-Module -Name C:\Program Files\WindowsPowerShell\Modules\Az.Network\4.7.0\Az.Network.psd1 -Global
```

### Error output

```PowerShell
##[error]Storage account: <my existing and accessible storage account> not found. The selected service connection 'Service Principal' supports storage accounts of Azure Resource Manager type only.
```

**Comment by dingmeng-xue** [comment] 2022-08-14 13:24
@diegum , could you see the same issue when you use the same cmdlet in PowerShell console local rather than Azure pipeline. We need you provide debug information. You can see debug information after setting `$DebugPreference = "Continue"`.

**Comment by mitsha-microsoft** [comment] 2022-08-18 06:39
We are facing the same issue, in an Azure Pipeline's Release Pipeline `Azure file copy` task with an existing storage account. It fails and passes intermittently.
In both the failing and passing pipelines with the same storage account and service connection, I think v2.9.0 is used:
```
##[debug]Loading module from path 'C:\Modules\az_7.5.0\Az.Accounts\2.9.0\Az.Accounts.psm1'.
```

**Comment by blueww** [comment] 2022-08-18 07:05
@diegum , @mitsha-microsoft 

From the comment https://github.com/microsoft/azure-pipelines-tasks/issues/14647#issuecomment-808056727, I see:
The failure is on `Get-AzureRmStorageAccount`, which is very old cmdlet, it has changed to `Get-AzStorageAccount` in the end of 2018.

And per https://github.com/microsoft/azure-pipelines-tasks/issues/14647#issuecomment-808064237, it looks  `Get-AzStorageAccount` work well.

Would you please upgrade to `Get-AzStorageAccount` cmdlet in Az.Storage module?

And it looks the error is from server.
If you can share the debug log by setting `$DebugPreference = "Continue"`, we can see more details for the error, and then can continue the investigation.

**Comment by mitsha-microsoft** [comment] 2022-08-18 08:52
@blueww I will need to verify what cmdlet and version is being used by the respective Azure Pipelines Task and will get back to you on it after I get some details.
I can try generating and sharing the Debug logs, but the issue occurs randomly in a release pipeline so reproducing it might get tricky. Let me check what I can do here

**Comment by navba-MSFT** [comment] 2022-08-19 02:55
@diegum Thanks for reaching out to us and reporting this issue. Did you get a chance to look at the above comment and check your pipeline tasks ?

Also Could you please confirm if you are facing the same issue while running the command from Powershell console ? If yes, please share the $DebugPreference = "Continue" output while running the same command in the Powershell. Awaiting your reply.

**Comment by mitsha-microsoft** [comment] 2022-08-19 05:37
@navba-MSFT I have asked for clarification in [this issue](https://github.com/microsoft/azure-pipelines-tasks/issues/16757) since I did see references of `Get-AzureRmStorageAccount` which I believe might be causing this bug. Will update when there's any response to it.

**Comment by diegum** [comment] 2022-08-20 05:01
> @diegum , could you see the same issue when you use the same cmdlet in PowerShell console local rather than Azure pipeline. We need you provide debug information. You can see debug information after setting `$DebugPreference = "Continue"`.

How could I try? I'm not the maker of that command let. I'm an end user, actually. I have a declared pipeline and applied that `AzureFileCopy` task based on its documentation. Are you suggesting that I clone the Azure pipeline tasks repo and try to run the file copy task manually??

**Comment by diegum** [comment] 2022-08-20 05:05
> @diegum , @mitsha-microsoft
> 
> From the comment [microsoft/azure-pipelines-tasks#14647 (comment)](https://github.com/microsoft/azure-pipelines-tasks/issues/14647#issuecomment-808056727), I see: The failure is on `Get-AzureRmStorageAccount`, which is very old cmdlet, it has changed to `Get-AzStorageAccount` in the end of 2018.
> 
> And per [microsoft/azure-pipelines-tasks#14647 (comment)](https://github.com/microsoft/azure-pipelines-tasks/issues/14647#issuecomment-808064237), it looks `Get-AzStorageAccount` doesn't have the issue and works well.
> 
> Would you please upgrade to `Get-AzStorageAccount` cmdlet in Az.Storage module?
> 
> And it looks the error is from server. If you can share the debug log by setting `$DebugPreference = "Continue"`, we can see more details for the error, and then can continue the investigation.

Thanks, @blueww but, how can I upgrade the cmdlet?? I'm using an Azure pipeline task (`AzureFileCopy`). Whatever the task uses under the hood is outside my reach. Am I missing something?

**Comment by diegum** [comment] 2022-08-20 05:14
> @diegum Thanks for reaching out to us and reporting this issue. Did you get a chance to look at the [above comment ](https://github.com/Azure/azure-powershell/issues/19209#issuecomment-1219113638)and check your pipeline tasks and use `Get-AzStorageAccount` PS cmdlet instead?
> 
> Also Could you please confirm if you are facing the same issue while running the command from Powershell console ? If yes, please share the $DebugPreference = "Continue" output while running the same command in the Powershell. Awaiting your reply.

Hi, @navba-MSFT . I replied to these comments (check whether the azure pipeline task uses an obsolete command, and the suggestion to run from terminal. I'll summarize my answers here: I'm an end-user. I'm just using `AzureFileCopy` as a black box from a pipeline. I don't have access to that task source code (although I know that its source code is in the Azure pipeline tasks repo.) I want to confirm that you guys are asking me to clone the Azure Pipeline tasks repo, try running the AzureFileCopy task from its command let.

What I certainly can't do is to modify the `AzureFileCopy` implementation, I'm afraid. I guess that if we confirm that the implementation is obsolete, I'll depend on the Azure pipeline tasks guys to fix it. Ironically, as I said when opening the thread, they asked the community to reopen this ticket to you guys.

**Comment by mitsha-microsoft** [comment] 2022-08-20 14:54
Hi @diegum,
I dont think you need to either clone the task and run it from terminal, or try to modify the implementation of the AzureFileCopy task. I have raised the appropriate concerns raised by @navba-MSFT / @blueww with a new issue on the Azure Pipelines Task ([linked here](https://github.com/microsoft/azure-pipelines-tasks/issues/16757)) and you are correct, that we need to depend on the Azure pipeline task guys to fix it. Lets wait for their response.

**Comment by navba-MSFT** [comment] 2022-08-22 04:38
Thanks @mitsha-microsoft .

@diegum I am following up offline with the assignee of https://github.com/microsoft/azure-pipelines-tasks/issues/16757 to look into it on priority.

**Comment by navba-MSFT** [comment] 2022-09-01 04:53
@diegum @mitsha-microsoft see this PR https://github.com/microsoft/azure-pipelines-tasks/pull/16785 and the below comments from it:

> I have completed this PR - https://dev.azure.com/mseng/AzureDevOps/_git/AzureDevOps/pullrequest/663407
for creating AzureFileCopyV5 task.

**Comment by mitsha-microsoft** [comment] 2022-09-01 05:22
@navba-MSFT Thanks for taking it up and fixing the issue in the Az Pipelines Repo. When will you make the requested changes (bumping up the task versions) so that we can get an idea of when we can consume the new tasks in our pipelines?

**Comment by navba-MSFT** [comment] 2022-09-05 06:57
@diegum  @mitsha-microsoft The suggested changes have been made in the OR and the PR is now merged. It will get released as a part of current sprint (210). Check current Azure DevOps sprint - https://whatsprintis.it/

**Closed by navba-MSFT** 2022-09-05 06:57 UTC
Labels: Storage, bug, customer-reported, CXP Attention
