### ISSUE TITLE
Import-Module -Name Az now causes "There is no active Azure PowerShell session" error due to recent changes

### ISSUE THREAD

**Issue by lee27350** [Azure/azure-powershell#23503] opened 2023-11-20 16:48 UTC
### Description

Running a simple, explicit

`Import-Module -Name Az`

now causes a "There is no active Azure PowerShell session. Please run 'Connect-AzAccount'" error.

https://github.com/Azure/azure-powershell/blob/a7e8e7f4874babf70a277bdaef4f2d1c8981fb12/src/Functions/Functions.Autorest/custom/HelperFunctions.ps1 is calling SetLinuxandWindowsSupportedRuntimes when the module is imported, which is calling GetFunctionAppStackDefinition, which since the https://github.com/Azure/azure-powershell/commit/569ebf5ba1eb1db581be13fe2fb52c93c5fe1caf commit is now doing the following:

# Make sure there is an active Azure session
    $context = Get-AzContext -ErrorAction SilentlyContinue
    if (-not $context)
    {
        $errorMessage = "There is no active Azure PowerShell session. Please run 'Connect-AzAccount'"
        $exception = [System.InvalidOperationException]::New($errorMessage)
        ThrowTerminatingError -ErrorId "LoginToAzureViaConnectAzAccount" `
                              -ErrorMessage $errorMessage `
                              -ErrorCategory ([System.Management.Automation.ErrorCategory]::InvalidOperation) `
                              -Exception $exception
    }

It should be possible to run `Import-Module -Name Az` without it trying to do things with a connected account.

### Issue script & Debug output

```PowerShell
Import-Module -Name Az
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     11.0.0                Az
Script     2.13.2                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzConte…
Script     2.0.0                 Az.Advisor                          {Disable-AzAdvisorRecommendation, Enable-AzAdviso…
Script     6.0.0                 Az.Aks                              {Disable-AzAksAddOn, Enable-AzAksAddOn, Get-AzAks…
Script     1.1.4                 Az.AnalysisServices                 {Add-AzAnalysisServicesAccount, Export-AzAnalysis…
Script     4.0.2                 Az.ApiManagement                    {Add-AzApiManagementApiToGateway, Add-AzApiManage…
Script     1.0.0                 Az.App                              {Disable-AzContainerAppRevision, Enable-AzContain…
Script     1.3.0                 Az.AppConfiguration                 {Clear-AzAppConfigurationDeletedStore, Get-AzAppC…
Script     2.2.2                 Az.ApplicationInsights              {Get-AzApplicationInsights, Get-AzApplicationInsi…
Script     1.0.0                 Az.ArcResourceBridge                {Get-AzArcResourceBridge, Get-AzArcResourceBridge…
Script     2.0.0                 Az.Attestation                      {Add-AzAttestationPolicySigner, Get-AzAttestation…
Script     1.0.0                 Az.Automanage                       {Get-AzAutomanageBestPractice, Get-AzAutomanageCo…
Script     1.9.1                 Az.Automation                       {Export-AzAutomationDscConfiguration, Export-AzAu…
Script     3.5.0                 Az.Batch                            {Disable-AzBatchAutoScale, Disable-AzBatchCompute…
Script     2.0.3                 Az.Billing                          {Get-AzBillingAccount, Get-AzBillingInvoice, Get-…
Script     3.1.1                 Az.Cdn                              {Clear-AzCdnEndpointContent, Clear-AzFrontDoorCdn…
Script     2.0.0                 Az.CloudService                     {Get-AzCloudService, Get-AzCloudServiceInstanceVi…
Script     1.14.1                Az.CognitiveServices                {Add-AzCognitiveServicesAccountNetworkRule, Get-A…
Script     7.0.0                 Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAddition…
Script     1.0.0                 Az.ConfidentialLedger               {Get-AzConfidentialLedger, New-AzConfidentialLedg…
Script     4.0.0                 Az.ContainerInstance                {Add-AzContainerInstanceOutput, Get-AzContainerGr…
Script     4.1.2                 Az.ContainerRegistry                {Connect-AzContainerRegistry, Get-AzContainerRegi…
Script     1.13.0                Az.CosmosDB                         {Get-AzCosmosDBAccount, Get-AzCosmosDBAccountKey,…
Script     1.1.0                 Az.DataBoxEdge                      {Get-AzDataBoxEdgeBandwidthSchedule, Get-AzDataBo…
Script     1.7.1                 Az.Databricks                       {Get-AzDatabricksAccessConnector, Get-AzDatabrick…
Script     1.17.1                Az.DataFactory                      {Add-AzDataFactoryV2DataFlowDebugSessionPackage, …
Script     1.0.3                 Az.DataLakeAnalytics                {Add-AzDataLakeAnalyticsDataSource, Add-AzDataLak…
Script     1.3.0                 Az.DataLakeStore                    {Add-AzDataLakeStoreFirewallRule, Add-AzDataLakeS…
Script     2.1.0                 Az.DataProtection                   {Backup-AzDataProtectionBackupInstanceAdhoc, Edit…
Script     1.0.1                 Az.DataShare                        {Get-AzDataShare, Get-AzDataShareAccount, Get-AzD…
Script     1.1.0                 Az.DeploymentManager                {Get-AzDeploymentManagerArtifactSource, Get-AzDep…
Script     4.2.0                 Az.DesktopVirtualization            {Disconnect-AzWvdUserSession, Expand-AzWvdMsixIma…
Script     1.0.0                 Az.DevCenter                        {Deploy-AzDevCenterUserEnvironment, Get-AzDevCent…
Script     1.0.2                 Az.DevTestLabs                      {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShut…
Script     1.2.0                 Az.Dns                              {Add-AzDnsRecordConfig, Get-AzDnsRecordSet, Get-A…
Script     1.6.0                 Az.EventGrid                        {Enable-AzEventGridPartnerTopic, Get-AzEventGridC…
Script     4.2.0                 Az.EventHub                         {New-AzEventHubAuthorizationRuleSASToken, Approve…
Script     1.10.0                Az.FrontDoor                        {Disable-AzFrontDoorCustomDomainHttps, Enable-AzF…
Script     6.0.2                 Az.HDInsight                        {Add-AzHDInsightClusterIdentity, Add-AzHDInsightC…
Script     2.0.0                 Az.HealthcareApis                   {Get-AzHealthcareApisService, Get-AzHealthcareApi…
Script     2.7.5                 Az.IotHub                           {Add-AzIotHubCertificate, Add-AzIotHubConfigurati…
Script     5.0.0                 Az.KeyVault                         {Add-AzKeyVaultCertificate, Add-AzKeyVaultCertifi…
Script     2.3.0                 Az.Kusto                            {Add-AzKustoClusterLanguageExtension, Add-AzKusto…
Script     1.0.0                 Az.LoadTesting                      {Get-AzLoad, New-AzLoad, Remove-AzLoad, Update-Az…
Script     1.5.0                 Az.LogicApp                         {Get-AzIntegrationAccount, Get-AzIntegrationAccou…
Script     1.1.3                 Az.MachineLearning                  {Add-AzMlWebServiceRegionalProperty, Export-AzMlW…
Script     1.0.0                 Az.MachineLearningServices          {Get-AzMLServiceQuota, Get-AzMLServiceUsage, Get-…
Script     1.4.0                 Az.Maintenance                      {Get-AzApplyUpdate, Get-AzConfigurationAssignment…
Script     1.1.1                 Az.ManagedServiceIdentity           {Get-AzFederatedIdentityCredentials, Get-AzSystem…
Script     3.0.0                 Az.ManagedServices                  {Get-AzManagedServicesAssignment, Get-AzManagedSe…
Script     2.0.0                 Az.MarketplaceOrdering              {Get-AzMarketplaceTerms, Invoke-AzMarketplaceSign…
Script     1.1.2                 Az.Media                            {Get-AzMediaService, Get-AzMediaServiceKey, Get-A…
Script     2.2.0                 Az.Migrate                          {Get-AzMigrateDiscoveredServer, Get-AzMigrateJob,…
Script     5.0.0                 Az.Monitor                          {Add-AzLogProfile, Add-AzMetricAlertRule, Add-AzM…
Script     1.1.1                 Az.MySql                            {Get-AzMySqlConfiguration, Get-AzMySqlConnectionS…
Script     7.0.0                 Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificat…
Script     1.0.0                 Az.NetworkCloud                     {Deploy-AzNetworkCloudCluster, Disable-AzNetworkC…
Script     1.1.2                 Az.NotificationHubs                 {Get-AzNotificationHub, Get-AzNotificationHubAuth…
Script     3.2.0                 Az.OperationalInsights              {Disable-AzOperationalInsightsIISLogCollection, D…
Script     1.6.4                 Az.PolicyInsights                   {Get-AzPolicyAttestation, Get-AzPolicyEvent, Get-…
Script     1.1.0                 Az.PostgreSql                       {Get-AzPostgreSqlConfiguration, Get-AzPostgreSqlC…
Script     2.0.0                 Az.PowerBIEmbedded                  {Get-AzPowerBIEmbeddedCapacity, New-AzPowerBIEmbe…
Script     1.0.4                 Az.PrivateDns                       {Add-AzPrivateDnsRecordConfig, Get-AzPrivateDnsRe…
Script     6.6.1                 Az.RecoveryServices                 {Add-AzRecoveryServicesAsrReplicationProtectedIte…
Script     1.8.1                 Az.RedisCache                       {Export-AzRedisCache, Get-AzRedisCache, Get-AzRed…
Script     1.2.0                 Az.RedisEnterpriseCache             {Export-AzRedisEnterpriseCache, Get-AzRedisEnterp…
Script     2.0.0                 Az.Relay                            {Get-AzRelayAuthorizationRule, Get-AzRelayHybridC…
Script     1.2.0                 Az.ResourceMover                    {Add-AzResourceMoverMoveResource, Get-AzResourceM…
Script     6.12.0                Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, G…
Script     1.5.0                 Az.Security                         {Add-AzSecurityAdaptiveNetworkHardening, Add-AzSe…
Script     3.1.1                 Az.SecurityInsights                 {Get-AzSentinelAlertRule, Get-AzSentinelAlertRule…
Script     3.0.0                 Az.ServiceBus                       {New-AzServiceBusAuthorizationRuleSASToken, Test-…
Script     3.3.0                 Az.ServiceFabric                    {Add-AzServiceFabricClientCertificate, Add-AzServ…
Script     2.0.0                 Az.SignalR                          {Get-AzSignalR, Get-AzSignalRKey, Get-AzSignalRUs…
Script     4.11.0                Az.Sql                              {Add-AzSqlDatabaseToFailoverGroup, Add-AzSqlElast…
Script     2.1.0                 Az.SqlVirtualMachine                {Get-AzAvailabilityGroupListener, Get-AzSqlVM, Ge…
Script     2.2.3                 Az.StackHCI                         {Add-AzStackHCIVMAttestation, Disable-AzStackHCIA…
Script     6.0.0                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorage…
Script     1.2.0                 Az.StorageMover                     {Get-AzStorageMover, Get-AzStorageMoverAgent, Get…
Script     2.1.0                 Az.StorageSync                      {Get-AzStorageSyncCloudEndpoint, Get-AzStorageSyn…
Script     2.0.0                 Az.StreamAnalytics                  {Get-AzStreamAnalyticsCluster, Get-AzStreamAnalyt…
Script     1.0.0                 Az.Support                          {Get-AzSupportProblemClassification, Get-AzSuppor…
Script     3.0.4                 Az.Synapse                          {Add-AzSynapseDataFlowDebugSessionPackage, Add-Az…
Script     1.2.2                 Az.TrafficManager                   {Add-AzTrafficManagerCustomHeaderToEndpoint, Add-…
Script     3.1.2                 Az.Websites                         {Add-AzWebAppAccessRestrictionRule, Add-AzWebAppT…
```

### Error output

```PowerShell
> Resolve-AzError

   HistoryId: 2

Message        : There is no active Azure PowerShell session. Please run 'Connect-AzAccount'
StackTrace     :    at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
Exception      : System.InvalidOperationException
InvocationInfo : {}
Line           :     throw $errorRecord

Position       : At C:\Users\[redacted]\Documents\PowerShell\Modules\Az.Functions\4.0.7\custom\HelperFunctions.ps1:869
                 char:5
                 +     throw $errorRecord
                 +     ~~~~~~~~~~~~~~~~~~
HistoryId      : 2
```

**Comment by isra-fel** [comment] 2023-11-22 10:21
Thanks for the feedback. @dolauli can you try to reproduce the issue? Let's discuss for a solution to this.

As a _temporary work-around_, `Import-Module Az.Accounts; Connect-AzAccount` before importing Az.

**Comment by jackmtpt** [comment] 2024-01-22 14:42
It looks like this is caused by the Az.Functions module:

```
at ThrowTerminatingError, /azp/.local/share/powershell/Modules/Az.Functions/4.0.7/custom/HelperFunctions.ps1: line 869
at GetFunctionAppStackDefinition, /azp/.local/share/powershell/Modules/Az.Functions/4.0.7/custom/HelperFunctions.ps1: line 1734
at SetLinuxandWindowsSupportedRuntimes, /azp/.local/share/powershell/Modules/Az.Functions/4.0.7/custom/HelperFunctions.ps1: line 2118
at <ScriptBlock>, /azp/.local/share/powershell/Modules/Az.Functions/4.0.7/custom/HelperFunctions.ps1: line 2171
at <ScriptBlock>, /azp/.local/share/powershell/Modules/Az/11.2.0/Az.psm1: line 135
at <ScriptBlock>, <No file>: line 1
```

**Comment by jklotzsche-msft** [comment] 2024-02-06 19:48
Same issue applies for pipelines (e.g. GitHub Actions). Cannot import Az.Functions module in build process anymore. Connect-AzAccount is not possible, as I don't want to authenticate in this process.

**Comment by isra-fel** [comment] 2024-02-07 01:41
> Cannot import Az.Functions module in build process anymore...as I don't want to authenticate in this process.

@jklotzsche-msft could you please share what you import Az.Functions (without authentication) for?

**Comment by jklotzsche-msft** [comment] 2024-02-23 08:09
@isra-fel, sure. There are two reasons:

1. We want to detect broken dependencies for any module we reuse in our build scripts. Using Import-Module, we have to import the dependencies of Az.Functions (and others) as well and could detect any issues with that in the build process.
2. The newest version of the module is imported automatically.

We reuse our build scripts not only for DevOps/GitHub, but also for local packaging. If there are multiple versions of the same module installed locally, we want to make sure to use the latest version for the packaging process.

You can have a look at the script we use to obtain the required dependencies in the [PSModuleDevelopment module on GitHib](https://github.com/PowershellFrameworkCollective/PSModuleDevelopment/blob/development/templates/MiniModule/build/vsts-prerequisites.ps1)

**Comment by FriedrichWeinmann** [comment] 2024-02-23 08:19
There are several reasons to import without authentication:

> Automatic Tests of a module that takes a dependency on Az.Functions.

Lets say I have a module that takes a dependency on Az.Functions and as part of my release pipeline, I run a limited number of tests for powershell related aspects of my own module. For example, whether the help was properly written.
In that case, I need to import my module (which requires loading all dependencies) but do not need actual functionality.
If I do this automatically in a github action, where I don't have any azure authentication set up (why would I, no need for a help test) ... well, here we are ...

> script requires

When writing a script, it is usually recommended to add all required modules at the top of the file using a `#requires` statement:

```powershell
#requires -Modules Az.Functions
```

This ensures that all modules are loaded before the script ever runs and is a clear declaration of dependencies.
However, if that script is the first piece of logic - e.g. when ran from the task scheduler - it has no chance to run a Connect-AzAccount before loading the modules and - now - fails.

> Module Dependencies

Lets say I develop a module implementing my own Azure Function management tools (including handling the authentication). Now that module declares all its dependencies, so that my users just need to run `Install-Module` and everything is ready.
The user now starts a new PowerShell console and runs:

```powershell
Connect-MyModuleFancyConnect
```

Which is part of my module and should do all the connection handling needed. What happens behind the scenes in PowerShell?

- Resolves `Connect-MyModuleFancyConnect` as a command in module `MyModule`
- `MyModule` is not imported yet, so it starts the module import
- Loads all modules `MyModule` depends on
- Loads `MyModule`
- Executes `Connect-MyModuleFancyConnect`

By failing the module import of `Az.Functions` without a connection, this entire process fails in the third step.

> Concluding

Please do not enforce an existing connection before module import, PowerShell dependency handling and years of coding tradition as practiced by the community argue strongly against it.

**Comment by Francisco-Gamino** [comment] 2024-06-10 16:34
This issue is a duplicated of https://github.com/Azure/azure-powershell/pull/24656, which has been fixed on the latest `Az.Functions` release.

**Closed by Francisco-Gamino** 2024-06-10 16:34 UTC
Labels: Service Attention, Functions, bug, customer-reported
