### ISSUE TITLE
Get-AzAutomationRunbook not returning runbook description

### ISSUE THREAD

**Issue by julian-wendt** [Azure/azure-powershell#17086] opened 2022-02-11 13:22 UTC
### Description

Not sure if this is a bug. I am wondering that `Get-AzAutomationRunbook` only returns a runbook description if a single runbook is explicit mentioned with `-Name`.

For example, this would not return a runbook description:
```powershell
Get-AzAutomationRunbook -AutomationAccountName "Contoso17" -ResourceGroupName "ResourceGroup01"
```

Instead I have to loop through all previously received runbooks and once again run Get-AzAutomationRunbook -Name:
```powershell
Get-AzAutomationRunbook -AutomationAccountName "Contoso17" -ResourceGroupName "ResourceGroup01" | Foreach-Object {
  Get-AzAutomationRunbook -AutomationAccountName "Contoso17" -ResourceGroupName "ResourceGroup01" -Name $_.Name
}
```

### Environment data

GitHub Action running windows-latest and ubuntu-latest. Also on Win11 with PS 7.2.1.

### Module versions

```PowerShell
Az.Automation 1.7.2
```

**Comment by SaurabhSharma-MSFT** [comment] 2022-02-11 23:06
@julian-wendt This behavior looks like correct as when you are using `Get-AzAutomationRunbook` with `AutomationAccountName" and "ResourceGroupName" parameters, you are going to get all runbooks in the Azure Automation account (which you are passing through **AutomationAccountName**). Also, if you want to get any specific runbook, you need to specify its name by using the `-Name` parameter. 
Please let me know if you have any other questions.

Thanks
Saurabh

**Comment by julian-wendt** [comment] 2022-02-21 15:06
Thanks for your feedback but unfortunately this is not what I meant.

If I use `Get-AzAutomationRunbook` without the `-Name` parameter to get a list of all runbooks, the description is missing for every runbook. My question is if that is by design?

I need a complete list of all runbooks including the description. Currently I have to run `Get-AzAutomationRunbook` once without the name parameter and then again afterwards with the name parameter to add the description. This takes a lot of time.

Thanks a lot for your help.

**Comment by SaurabhSharma-MSFT** [comment] 2022-03-14 21:22
@julian-wendt Yes, that is correct that is by design and you need to go through each runbooks individually to get detailed information. Thanks

**Comment by SaurabhSharma-MSFT** [comment] 2022-03-17 19:20
@julian-wendt We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Closed by SaurabhSharma-MSFT** 2022-03-17 19:20 UTC
Labels: Automation, question, customer-reported, needs-team-attention, CXP Attention

**Comment by Giangi72** [comment] 2022-09-19 10:27
I'm facing the same behaviour.
How can it be "by design"?
It is the same function having 2 different results, all properties are correctly valued except the description.
For me it is a bug.
Sorry
