### ISSUE TITLE
New-AzureRMAutomationCredential: backslash in -name cause "Automation Account not found" error

### ISSUE THREAD

**Issue by arcotek-ltd** [Azure/azure-powershell#4499] opened 2017-08-23 23:23 UTC
### Cmdlet(s)
`New-AzureRMAutomationCredential`

### PowerShell Version
```
PS C:\> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14409  1005    
```

### Module Version

```
PS C:\> get-command New-AzureRmAutomationAccount

CommandType     Name                                               Version    Source                                                                                                                                         
-----------     ----                                               -------    ------                                                                                                                                         
Cmdlet          New-AzureRmAutomationAccount                       4.2.1      AzureRM   
```

### OS Version
```
PS C:\> gwmi win32_operatingsystem | select version

version 
------- 
6.1.7601
```
### Description

When providing the parameter -name as `domain\someuser` the use of the backslash causes the cmdlet to throw a very unhelpful and incorrect error, suggesting the 

### Debug Output
I'm sorry, I don't have time to redact and add it. Just run the steps below and you'll see what I mean. If you can't reproduce, get it touch and I'll show you...

### Script/Steps for Reproduction
1. Confirm the name and resource group name are 100% correct:
```
PS C:\> $oAutomationAccount = $oAAResources | Get-AzureRmAutomationAccount
$oAutomationAccount

SubscriptionId        : 12345
ResourceGroupName     : MyRG
AutomationAccountName : MyAA
Location              : westcentralus
State                 : Ok
Plan                  : 
CreationTime          : 24/05/2017 14:08:56 +01:00
LastModifiedTime      : 18/08/2017 08:48:12 +01:00
LastModifiedBy        : john@smith.com
Tags                  : {}
```

2. Create credential object:
`[System.Management.Automation.PSCredential]$oCred = New-Object System.Management.Automation.PSCredential("SMITH\SomeUser",(ConvertTo-SecureString 'Pa$$w0rd!' -AsPlainText -Force))
`
3. Create automation asset:
```
New-AzureRmAutomationCredential `
    -ResourceGroupName "MyRG" `
    -AutomationAccountName "MyAA" `
    -Name "SMITH\SomeUser" `
    -Description "For DSC" `
    -Value $oCred
```
Returns:
```
New-AzureRmAutomationCredential : The Automation account was not found.
At line:16 char:1
+ New-AzureRmAutomationCredential -ResourceGroupName "MyRG ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmAutomationCredential], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.NewAzureAutomationCredential`
```

Which is clearly not the case! We should be allowed to add backslashes as it would be a perfectly logical name, If it causes problems in doing so, correct the error message to say there is an invalid character. It has nothing to do with the Automation Account missing!

TIA

**Comment by arcotek-ltd** [comment] 2017-08-23 23:31
I've also just discovered that once the command runs successfully, if it is run again with the exact same parameters, it results in another unhelpful and misleading error:

```
New-AzureRmAutomationCredential : Input string was not in a correct format.
At line:9 char:1
+ New-AzureRmAutomationCredential `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmAutomationCredential], FormatException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.NewAzureAutomationCredential
```

**Comment by sphibbs** [comment] 2017-08-25 18:15
@vrdmr  can you take a look at this issue

**Comment by vrdmr** [comment] 2017-09-16 01:36
@arcotek-ltd Thanks for the repro steps. The issue has to do with better handling of error from our end. The "The Automation account was not found." is just the final fallback message. That needs to be fixed on our end and we have added this to our backlog. We'll try to get the issue fixed as soon as possible.

**Comment by andyw248** [comment] 2019-06-15 17:22
Triaged: By design - backslash needs to be escaped. Closing.

**Closed by andyw248** 2019-06-15 17:22 UTC
Labels: Automation, Service Attention, automation-cheetah
