### ISSUE TITLE
[ARS] Get-AzRecoveryServicesBackupRecoveryPoint, Pipeline has stopped

### ISSUE THREAD

**Issue by Manbearpiet** [Azure/azure-powershell#14695] opened 2021-04-06 18:00 UTC
## Description

Selecting an index (backup) out of all backups throws an error. Enclosing the fetch of recoverypoints does work, omitting the select object works fine also. I was advised to also mention this: 

_19:16 seeminglyscience :
Also probably file an issue telling the azure team they need to rethrow flow control exceptions_

## Steps to reproduce

Error
```powershell
Get-AzRecoveryServicesBackupRecoveryPoint -Item $Item -VaultId $vaultid | Select-Object -Index 0
```

Workaround
```powershell
(Get-AzRecoveryServicesBackupRecoveryPoint -Item $Item -VaultId $vaultid) | Select-Object -Index 0
```

## Environment data

```
 $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```powershell
Script     2.10.0                Az.RecoveryServices                 Core,Desk {Get-AzRecoveryServicesBackupProperty, Get-AzRecoveryServicesVault, Get-AzRecoveryServicesVaultSettingsFile, New-AzRecoveryServicesVault…}
```

## Debug output

```
Get-AzRecoveryServicesBackupRecoveryPoint -Item $item[0] -VaultId $id | select -Index 0 -Debug

RecoveryPointId    RecoveryPointType  RecoveryPointTime      ContainerName                        ContainerType
---------------    -----------------  -----------------      -------------                        -------------
18468056749134388… AppConsistent      05/04/2021 20:12:39    iaasvmcontainerv2;christian-rsg;res… AzureVM
Get-AzRecoveryServicesBackupRecoveryPoint: The pipeline has been stopped.
```

## Error output

```
   HistoryId: 10

Message        : The pipeline has been stopped.
StackTrace     :    at System.Management.Automation.CommandProcessor.ProcessRecord()
                    at System.Management.Automation.CommandProcessorBase.DoExecute()
                    at System.Management.Automation.Internal.Pipe.AddItems(Object objects)
                    at System.Management.Automation.Cmdlet.WriteObject(Object sendToPipeline, Boolean enumerateCollection)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.WriteObject(Object sendToPipeline, Boolean enumerateCollection)
                    at Microsoft.Azure.Commands.RecoveryServices.Backup.Cmdlets.GetAzureRmRecoveryServicesBackupRecoveryPoint.<ExecuteCmdlet>b__27_0()
                    at Microsoft.Azure.Commands.RecoveryServices.Backup.Cmdlets.RecoveryServicesBackupCmdletBase.ExecutionBlock(Action action, Boolean shouldProcess)
Exception      : System.Management.Automation.PipelineStoppedException
InvocationInfo : {Get-AzRecoveryServicesBackupRecoveryPoint}
Line           : Get-AzRecoveryServicesBackupRecoveryPoint -Item $item[0] -VaultId $id | select
                 -Index 0
Position       : At line:1 char:1
                 + Get-AzRecoveryServicesBackupRecoveryPoint -Item $item[0] -VaultId $id …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 10
```

**Comment by mepand** [comment] 2021-04-12 13:39
Thanks @Manbearpiet for bringing this to our notice. We are looking into the issue and shall soon share an update.

**Comment by mepand** [comment] 2021-05-06 16:41
@Manbearpiet we could repro the issue . I have created a backlog item for engineering team to analyse it further . At this minute , we are not sure if the issue is related to backup module or PS in general. Based on the analysis, we will plan the fix .

**Comment by SatishBoddu-MSFT** [comment] 2021-10-24 02:08
Hello @mepand , @Manbearpiet Please let us know if we are good to close this issue?
I see that this issue is opened a long time ago and no further activity had taken place. So wanted to check if you are still looking for assistance on this query? Please let us know.

**Comment by pvrk** [comment] 2021-11-01 09:07
@SatishBoddu-MSFT, @Manbearpiet :  Sincere apologies for the delay. We are following up with the platform team and will come back with an ETA for the fix. Thanks for your patience.

**Comment by pvrk** [comment] 2021-11-01 09:08
Also, assigned this to the relevant engineer.

**Comment by Manbearpiet** [comment] 2021-11-08 16:17
> 
> 
> Hi, we're sending this friendly reminder because we haven't heard back from you in a while. We need more information about this issue to help address it. Please be sure to give us your input within the next **7 days**. If we don't hear back from you within **14 days** of this comment the issue will be automatically closed. Thank you!

Please don't.

**Comment by Daya-Patil** [comment] 2024-01-29 03:52
no reply to reminder

**Closed** 2024-01-29 03:51 UTC
Labels: Recovery Services Backup, Service Attention, question, customer-reported, needs-team-attention
