### ISSUE TITLE
Linux Powershell Login issues

### ISSUE THREAD

**Issue by JillRebecca** [Azure/azure-powershell#7417] opened 2018-09-28 15:25 UTC
### Description

I am trying to log into my Azure account from Linux and receive an error message.
Note that this previously worked but has now stopped working.

### Script/Steps for Reproduction

From Linux environment, Launch Powershell
Run Connect-AzureRmAccount
Open a browser (this is done in Windows), enter the code to authenticate, select the correct account to log in, receive a message "You have signed in to the Windows Azure PowerShell application on your device. You may now close this window."
After a minute or two, receive this message in the Powershell session in Linux:

Connect-AzureRmAccount : The operation was canceled.                                                                                                             
At line:1 char:1                                                                                                                                                 
+ Connect-AzureRmAccount                                                                                                                                         
+ ~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                         
+ CategoryInfo          : CloseError: (:) [Connect-AzureRmAccount], OperationCanceledException                                                                   
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand  

### Module Version

0.13.1

### Environment Data

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Linux 3.10.0-693.33.1.el7.x86_64 #1 SMP Thu May 24 16:41:13 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### Debug Output

N/A - no script to run, just azure command Connect-AzureRmAccount

**Comment by cormacpayne** [comment] 2018-09-28 16:41
@JillRebecca would you mind uninstalling the `AzureRM.Netcore` modules and install the new `Az` module? This is the .NET Standard module that we recommend using moving forward. Would you mind installing this module and verifying that the same behavior occurs?

**Comment by phillipsj** [comment] 2018-10-01 02:30
I have confirmed that the Az module on Linux works and does not produce this error.

**Comment by MaximoTrinidad** [comment] 2018-10-09 14:03
@JillRebecca,

In my case I use WSL - Ubuntu on the latest Windows 10 with the latest Azure modules, which are no longer labeled AzureRM just Az version 0.2.2. 

Az module is replacing the AzureRM module.

Everything seems to work fine.

![azmoduleconnect_01_2018-10-09_9-51-37](https://user-images.githubusercontent.com/19892435/46674348-e1065400-cba9-11e8-8736-43eaf9f69f08.jpg)

```
PS /home/maxt> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Linux 4.4.0-18252-Microsoft #1000-Microsoft Fri Sep 28 14:10:00 PST 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS /home/maxt> cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

Now, there still some missing information. Which distro of linux are you using?
Is this a Virtual Machine? or a WSL?

:)

**Comment by MaximoTrinidad** [comment] 2018-10-15 20:42
And, the latest release of Az module is now version 0.3.0.

**Comment by maddieclayton** [comment] 2018-11-13 22:41
Looks like this issue has been resolved in Az, closing.  Please open a new issue if you are still seeing any issues in Az.

**Closed by maddieclayton** 2018-11-13 22:41 UTC
Labels: More Info :label:
