### ISSUE TITLE
Calling Set-AzureServiceDiagnosticsExtension with -Role failing

### ISSUE THREAD

**Issue by craig-wagner** [Azure/azure-powershell#387] opened 2015-05-14 16:19 UTC
Based on the version number showing in "Programs and Features" I'm running 0.9.1 of the Azure Powershell. I installed it yesterday (2015/05/13) using the Web Platform Installer.

    $storage_name = "mystorageaccountname"
    $key = "mykey"
    $service_name = "cwagner-ipseity-worker"
    $public_config = "C:\tfs\SI\ipseity\trunk\BuildArtifacts\Deployment\Packages\AzureWorker\PaaSDiagnostics.Ipseity.Server.MessageProcessor.AzureWorkerRole.PubConfig.xml" 
    $storageContext = New-AzureStorageContext -StorageAccountName $storage_name -StorageAccountKey $key
    Set-AzureServiceDiagnosticsExtension -StorageContext $storageContext -DiagnosticsConfigurationPath $public_config -ServiceName $service_name -Slot Production -Role Ipseity.Server.MessageProcessor.AzureWorkerRole

I get the following output:

> VERBOSE: Setting PaaSDiagnostics configuration for Ipseity.Server.MessageProcessor.AzureWorkerRole.
> Set-AzureServiceDiagnosticsExtension : BadRequest: The extension ID
IpseityServerMessageProcessorAzureWorkerRole-PaaSDiagnostics-Production-Ext-0 is invalid.
> At line:1 char:1
> + Set-AzureServiceDiagnosticsExtension -StorageContext $storgeContext -Diagnostics ...
> + > ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>    + CategoryInfo          : NotSpecified: (:) [Set-AzureServiceDiagnosticsExtension], CloudException
>    + FullyQualifiedErrorId : Hyak.Common.CloudException,Microsoft.WindowsAzure.Commands.ServiceManagement.Extensions.
   SetAzureServiceDiagnosticsExtensionCommand

I realize this is similar to https://github.com/Azure/azure-powershell/issues/72 (dots in the role name) but it is my understanding that that issue has been fixed and the reported extension ID in error has had the dots stripped.

If we don't specify the `-Role` parameter it works.

**Comment by devigned** [comment] 2015-05-26 16:00
@matt-gibbs or @markcowl thoughts on this one?

**Comment by bgambs** [comment] 2015-05-27 19:23
Similar issue here; 

     $setdeployment = Set-AzureDeployment -Upgrade -Slot $slot -Package $packageLocation -Configuration $cloudConfigLocation -label $deploymentLabel -ServiceName $serviceName -Force -ExtensionConfiguration @($workerDiagConfig,$webDiagConfig)

yields
   
    BadRequest: The extension ID FixxxxxxWorkerRoleCommandProcessor-PaaSDiagnostics-Production-Ext-0 is invalid.

We don't have a full stack trace yet, because Jenkins, but

    + CategoryInfo          : NotSpecified: (:) [Set-AzureDeployment], CloudException
    + FullyQualifiedErrorId : Hyak.Common.CloudException,Microsoft.WindowsAzure.Commands.ServiceManagement.HostedServices.SetAzureDeploymentCommand

**Comment by bgambs** [comment] 2015-05-27 23:34
@craig-wagner  @devigned  We managed to resolve this particular issue - by shortening the name of the worker role. No idea what the limit is by FixxxxxxWorkerRoleCommandProcessor is too long and FixxxxxxWorker is not.

**Comment by singhkay** [comment] 2015-06-17 22:44
@huangpf Can you take a look at why long worker role names are causing this? Thanks!

**Comment by ToonDC** [comment] 2015-06-19 13:34
@huangpf Info: having the same issue also in 0.9.3.

**Comment by huangpf** [comment] 2015-06-19 17:09
@ToonDC 
Does the problem occur in ```Set-AzureDeployment```, ```Set-AzureServiceDiagnosticsExtension```, or both?

Do you have the repro steps, operation IDs, logs, etc?

**Comment by ToonDC** [comment] 2015-06-22 18:38
I have it for both + also for `New-AzureDeployment`, I created a sample project that you can find here [code](https://github.com/ToonDC/azurecli) on github. 

1. Publish the solution via Visual Studio 2013 Update 4 and notice that that works as expected.
2. Execute the script [New-AzureDeployment.ps1](https://github.com/ToonDC/azurecli/blob/master/New-AzureDeployment.ps1)
3. Same for the script [Set-AzureDeployment.ps1](https://github.com/ToonDC/azurecli/blob/master/Set-AzureDeployment.ps1)
4. Same for the script [Set-AzureServiceDiagnosticsExtension.ps1](https://github.com/ToonDC/azurecli/blob/master/Set-AzureServiceDiagnosticsExtension.ps1)
5. View (my) output on the [screenshot](https://raw.githubusercontent.com/ToonDC/azurecli/master/ScriptScreenshot.png)  ![screenshot](https://raw.githubusercontent.com/ToonDC/azurecli/master/ScriptScreenshot.png) (CLI version is also visible on the top of the script.

If you are not able to reproduce I would like to provide the operation IDs, etc.

**Comment by huangpf** [comment] 2015-06-22 19:14
@ToonDC Thanks for the information. It does reproduce.

Is it feasible for you to use a shorter role name, like ```$azureWebRoleName = "WebRole1"```? One our end, we need to triage and come up with a better solution to handle the recent extension ID-related issues. Assign it back to @singhkay for creating an item for triage and tracking.

@craig-wagner 
This is a different issue than #72 in that here the validation is about the length of the extension ID.

**Comment by ToonDC** [comment] 2015-06-23 07:55
@huangpf it is feasible to rename the web/workerroles, but it's far from ideal.

**Comment by huangpf** [comment] 2015-06-23 17:09
@ToonDC Sorry for the inconvenience. This is just a temporary mitigation for now. 

We would try to come up with a better and more generic solution for the extension ID-related issues.

Thanks.

**Comment by craig-wagner** [comment] 2015-06-23 17:18
@huangpf Thanks. I realized it was a different issue. I only put the reference to #72 in because they sound very similar (and have the same title) and was trying to avoid someone saying, "That's already been fixed, see #72."

**Comment by huangpf** [comment] 2015-06-23 17:49
@craig-wagner Thanks for your information. I added notes there, and here as well.

Note: this issue is about the length of extension ID, while #72 is about the invalid character of ```.``` used in the extension ID which should have been fixed. Since we have seen quite a few issues about extension IDs recently, we would try to triage them together and come up with a more generic solution for them altogether.

**Comment by ivanz** [comment] 2015-08-03 17:17
Is there a workaround for this that doesn't involve renaming roles?

**Comment by huangpf** [comment] 2015-09-15 17:50
@ivanz @craig-wagner @ToonDC 
The fix is in the main repo's dev branch. Please help try it out if feasible. Thanks.

**Comment by craig-wagner** [comment] 2015-09-23 15:05
@huangpf, I'd be happy to try it out but I'm not sure how to from the dev branch. Please forgive a naive question, but I'm assuming I need to download the source from the dev branch, build it, and then what do I do with the output in order to try executing it?

**Comment by huangpf** [comment] 2015-09-23 17:03
@craig-wagner, Thanks for your information and help. After msbuild, you can find the .msi installer in the output folder. On the other hand, you can also run it via VS, and here is some guide information: https://github.com/Azure/azure-powershell/wiki/Microsoft-Azure-PowerShell-Developer-Guide. Thanks.

**Comment by nshampur** [comment] 2016-01-15 23:36
This issue is still half addressed. If the RoleName contains an underscore, it results in an Invalid Extension ID error from the API. I tried this on v1.0.3 and it is still a problem
Please re-open the issue and make appropriate changes to the extension ID convention.

**Comment by huangpf** [comment] 2016-01-15 23:42
@nshampur Please contact @yantang-msft who owns the diagnostics extension code.

@yantang-msft Could you please help take a look -- whether it's still a problem in the general extension code, or the override diagnostics extension code?

**Comment by yantang-msft** [comment] 2016-01-16 00:14
@huangpf From what @nshampur said, it's the problem related to the extension id.
We have code to stripe the "." and " " in role name, but not for "_", so I believe need to do more work to fully address the issue in general extension code.

**Comment by nshampur** [comment] 2016-01-16 00:14
@huangpf .. thanks .. Will do

@yantang-msft .. This is still an issue

Microsoft.WindowsAzure.Commands.ServiceManagement.Extensions.ExtensionRole

PrefixName = PrefixName.Replace(".", string.Empty);
                PrefixName = PrefixName.Replace(" ", string.Empty);
                RoleType = ExtensionRoleType.NamedRoles;

Underscore is also not permitted. I think a more aggressive sanitation logic needs to be in place

**Comment by nshampur** [comment] 2016-01-16 00:15
@yantang-msft  .. looks like our messages crossed.

Yes - the rules need to be strengthened. Our RoleNames are XYZ_Web, XYZ_Worker and we hit this issue upon upgrading to the newer SDKs

**Comment by huangpf** [comment] 2016-01-16 00:49
@hyonholee 
Is it now feasible for user to specify an extension ID to override the auto generated one?

**Comment by nshampur** [comment] 2016-01-16 01:00
@huangpf  . Yes . The API does support specifying an ExtensionID. This is how we are going to workaround this problem (Renaming Roles is not a viable option for us).

However - I think the bug should be fixed.

**Comment by nshampur** [comment] 2016-02-03 00:50
@singhkay @huangpf @yantang-msft ... What is the status of this? I still see RoleNames with an underscore being an issue due to the following code

Microsoft.WindowsAzure.Commands.ServiceManagement.Extensions.ExtensionRole

PrefixName = PrefixName.Replace(".", string.Empty);
PrefixName = PrefixName.Replace(" ", string.Empty);
RoleType = ExtensionRoleType.NamedRoles;


It was my understanding from the issue https://github.com/Azure/azure-powershell/issues/1573 that the next release was Feb 2 (today). Please improve this to include all invalid characters.

**Comment by huangpf** [comment] 2016-02-03 01:01
The patch will not make it to the 2/2 release, but it will be shipped via the ```PSGet Module`` once @hyonholee submitted the PR to the ```Azure``` branch. Thanks.

https://github.com/AzureRT/azure-powershell/blob/dev/src/ServiceManagement/Compute/Commands.ServiceManagement/Extensions/Common/ExtensionRole.cs#L68

**Comment by nshampur** [comment] 2016-02-03 01:18
@huangpf .. In order to workaround this, I plan on using unique IDs for extensionID. The downside is having to remove older unused IDs. How does one determine if an extension is unused?  (Try delete and ignore errors from extensions in use?)

**Comment by yantang-msft** [comment] 2016-02-03 01:59
> How does one determine if an extension is unused

@nshampur I believe even if you don't remove the older unused IDs, you can still make it work by specifying the new extension id.
Sure delete the unused ones is a good practice. And if one extension is not used by any roles in any production/staging slot, then it's not used so you can delete it.

**Comment by singhkay** [comment] 2016-04-25 22:58
@huangpf I see you linked PR #1792. Can this be closed now?

**Closed** 2016-04-26 21:11 UTC
Labels: Compute, IAAS
