### ISSUE TITLE
New-AzureRmWebApp fails with "InternalServerError" when cloning web apps

### ISSUE THREAD

**Issue by AWahlqvist** [Azure/azure-powershell#2617] opened 2016-07-15 14:37 UTC
When cloning web apps following the procedure at:
https://azure.microsoft.com/en-us/documentation/articles/app-service-web-app-cloning/

I always get the error "New-AzureRmWebApp : Long running operation failed with status 'InternalServerError'". Also, This cmdlet might need better parameter sets/error handling since you can leave out parameters completely that are needed for the command to work (for example AppServicePlan) and it will still issue the command to ARM, leaving the thread hanging for a couple of minutes before it fails.

Cloning the same app works without any issues in the portal.

I was running version 1.5.0 during testing.

**Comment by markcowl** [comment] 2016-07-15 16:24
@akurmi can you take a look?

**Comment by AWahlqvist** [comment] 2016-07-18 12:40
Update: Not entirely sure why but it actually seems to work today. I did recreate the apps so either they were in a "bad state" or I had "fat fingers" earlier... It seems to work now anyway, I've done multiple successful attempts. I still think that the parameter sets/error handling of the cmdlet should be addressed though since it's a bit confusing right now what you actually need to make it work, but another issue should probably be opened that just addresses that.

Apologies if I wasted anybodies time here! Spent hours on this last Friday so I was pretty sure this was a bug. Anyway, thanks!

**Comment by PirateBread** [comment] 2017-10-26 16:46
This is still happening, on most occasions cloning an app via powershell throws this error.

**Comment by jtheisen** [comment] 2018-03-02 10:32
I also get this.

**Comment by mulaysmara** [comment] 2018-04-24 13:42
I am also experiencing the same issue when cloning **AppSlot** from existing One.

**Comment by luuksommers** [comment] 2018-04-26 15:48
Yep can confirm it's broken again.

**Comment by PirateBread** [comment] 2018-04-29 10:30
Still happening here.

It's worth noting that the clone operation still completes in all situations I have tried it. I have successfully cloned production apps many times for migrations and they have all worked.

My script just catches the error and ignores it.

**Comment by coderangerdan** [comment] 2018-06-28 11:19
I get the error but it never works so catching the error would be pointless as the webapp is never created; basically i can't use the SourceWebApp parameter on a decent size app it seems

**Comment by funnay** [comment] 2018-07-02 13:29
Hello. Can someone please check this again?

AFAICT, it's still happening and I'm able to reproduce it just using the scripts based on the following book: https://www.microsoftpressstore.com/store/exam-ref-70-533-implementing-microsoft-azure-infrastructure-9781509306503

Is it related to other thing that I may be doing wrong or is it an issue?

Create a Web App deployment slot:

```powershell
$resourceGroupName = "contoso"
$webAppName = "myowncontoso-hr-app"
$stagingSlotName = "Staging"

# Create a new web app deployment slot
New-AzureRmWebAppSlot -ResourceGroupName $resourceGroupName `
    -Name $webAppName -Slot $stagingSlotName 
```

Clone the existing deployment slot

```powershell
$resourceGroupName = "contoso"
$appServicePlanName = "contoso"
$webAppName = "myowncontoso-hr-app"
$stagingSlotName = "Staging"
$productionSlotName = "Production" 

# Get a reference to the production deployment slot
$stagingSite = Get-AzureRmWebAppSlot -ResourceGroupName $resourceGroupName `
    -Name $webAppName -Slot $stagingSlotName

# Create a deployment slot that clones the production deployment slot settings
New-AzureRmWebAppSlot -ResourceGroupName $resourceGroupName `
    -Name $webAppName -Slot $productionSlotName `
    -AppServicePlan $appServicePlanName -SourceWebApp $stagingSite 
```
Result:

```powershell
New-AzureRmWebAppSlot : Long running operation failed with status 'InternalServerError'.
At line:1 char:1
+ New-AzureRmWebAppSlot -ResourceGroupName $resourceGroupName `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmWebAppSlot], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.DeploymentSlots.NewAzureWebAppSlotCmdlet
```

**Comment by saeohioalpha** [comment] 2018-09-19 17:39
Just a heads up, this still exists. I was trying to clone a webapp to a new slot and it failed. Both locally with PS and remotely on the Azure portal with Azure PS.

**Comment by sergeroz** [comment] 2018-11-16 01:43
Issue is still happening and clone operation does **not** succeed.

**Comment by LukeDearden** [comment] 2019-04-12 06:35
I been trying to migrate sites from Standard App Service to Premv2 using clone via powershell. I've had an SR open with Azure Support for the past 2 weeks. Seems a bit flakey to say the least

**Comment by nicklasjepsen** [comment] 2019-08-01 20:39
Why is this closed? This is still happening.

**Comment by LukeDearden** [comment] 2019-08-02 11:00
I can confirm this is still happening.

I've had to reopen my ticket with Azure Support. They advised the issue would be resolved with an update rolled out in June. I hadn't had time to test until last week. I'm getting internal server errors and conflicts where the cloning process seems to fail but continue in the background leaving the cloned app in limbo until it eventually becomes accessible in the portal again.

**Comment by AWahlqvist** [comment] 2019-09-03 13:57
Reopened since this seems to still be happening

**Comment by gtalton** [comment] 2019-09-04 01:11
Thanks for the Reopen @AWahlqvist this bit me today also on three webapps that all timed out. Is there any way to modify the timeout timer on this api call?

**Comment by panchagnula** [comment] 2019-09-20 17:16
I am closing this since the advice is to use the Az equivalents and not the AzureRM - if some one still see this please open a new issue with all the info needed as per the Az GitHub issue template. Thank you.

**Closed by panchagnula** 2019-09-20 17:16 UTC
Labels: App Services, Service Attention

**Comment by saeohioalpha** [comment] 2019-09-20 17:26
Since AzureRm is supposed to get bugfixes until Dec. 2020, why is the only solution to use the Az module? This is obviously a bug, that has existed since before the Az module was in general release.

**Comment by AWahlqvist** [comment] 2019-09-20 17:32
Maybe others have had better experience, but I'm done reporting bugs. Complete waste of time and no issues raised are being adressed. This module is said to be supported but apparently this: "the AzureRM module is still officially maintained and will get bug fixes through December 2020." is a complete lie.

The new module has a bunch of bugs that makes it close to unusable for us and we haven't received any updates on the issues raised there neither for many months.

Feel free to close these, but don't count on people ever helping out by raising new ones.

**Comment by MickaelMRA** [comment] 2019-10-16 10:00
Hello, for me I needed to add this option -IgnoreCustomHostNames at the end of New-AzureRmWebAppSlot command. The long run operation error failed with the 'InternalServerError' status was not explicit enough.
I hope that will help you too. I lost several hours :)

**Comment by LukeDearden** [comment] 2019-10-21 10:24
> Hello, for me I needed to add this option -IgnoreCustomHostNames at the end of New-AzureRmWebAppSlot command. The long run operation error failed with the 'InternalServerError' status was not explicit enough.
> I hope that will help you too. I lost several hours :)

I've always used this switch but still had the InternalServer Errors.

I'll try using the new Az module instead....

**Comment by nikydobrev** [comment] 2019-11-12 16:16
Hello, any update about this topic? When using "New-AzWebAppSlot" I am getting the same error "New-AzWebAppSlot : Long running operation failed with status 'InternalServerError'"

**Comment by gesturer121** [comment] 2019-11-27 04:15
I too am facing the same issue .Can someone from MS take the accountability and fix this.We understand that we need to migrate to Az module but this has to be smooth.You just cannot stop support for AzureRM like that.

**Comment by panchagnula** [comment] 2019-11-27 05:46
@thejachowdary can you check using the equivalent az command you get the same error? if so then work on a fix & work with the neceesary teams to understand what it takes to port the fix to AzureRM module. Thanks!

**Comment by ChristianJonsson** [comment] 2020-03-17 14:13
> Hello, any update about this topic? When using "New-AzWebAppSlot" I am getting the same error "New-AzWebAppSlot : Long running operation failed with status 'InternalServerError'"

Same here

**Comment by panchagnula** [comment] 2020-03-17 18:44
I am going to create a new issue for us to track this with the az module version - just for clarification @ChristianJonsson can you share the version of az PowerShell you are using that still repros this error?

**Comment by panchagnula** [comment] 2020-03-17 18:51
Btw there is an associated GitHub issue #10397 can you please check if the work around provided in this works or the issue in general sounds familiar?

**Comment by ChristianJonsson** [comment] 2020-03-17 19:25
> I am going to create a new issue for us to track this with the az module version - just for clarification @ChristianJonsson can you share the version of az PowerShell you are using that still repros this error?

Actually, when it comes to the New-AzWebAppSlot it was my error, after following all the steps required to post an issue, the 'Resolve-AzError' gave me the full stacktrace - I had missed to include the -Slot parameter, so by default it tried to create a slot with the same name as the Web App... which conflicted and resulted in an InternalServerError. Have not used the AzureRm so cannot comment on that, but possibly same issue?

But at least with the New-AzWebAppSlot, my error - it works! ~blush~
