### ISSUE TITLE
Key Vault PowerShell cannot import openssl generated key

### ISSUE THREAD

**Issue by jasonxdhu** [Azure/azure-powershell#11854] opened 2020-05-09 01:28 UTC
## Description
This issue is reported by a customer.

Customer uses openssl to generate a key and tries to import key into key vault with PowerShell. It errors out.

The same key can be imported via Azure portal. So the key is not the issue and PS command is.

## Steps to reproduce

[1] Use openssl.exe generate key
```
openssl.exe genrsa -aes256 -out E:\Temp\test.pem -passout pass:123 2048 2
openssl.exe pkcs12 -keypbe PBE-SHA1-3DES -aes256 -export -nocerts -inkey E:\Temp\test.pem -out E:\Temp\test.pfx -passin pass:123 -passout pass:123
```

[2]
```powershell
Add-AzKeyVaultKey -VaultName your-vault -Name test-openssl-key -KeyFilePath "E:\Temp\test.pfx" -KeyFilePassword $keyPassword -Destination HSM -debug 
```

## Module versions

```powershell

```

## Debug output

```

```

## Error output
Add-AzKeyVaultKey : The parameter is incorrect.
At line:1 char:1
+ Add-AzKeyVaultKey -VaultName test-bugfix -Name test-openssl-key -KeyF ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Add-AzKeyVaultKey], CryptographicException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.AddAzureKeyVaultKey

```

```

**Comment by dingmeng-xue** [comment] 2020-05-09 04:54
@isra-fel , please evaluate this issue.

**Comment by isra-fel** [comment] 2020-05-09 08:27
## How to reproduce
```powershell
openssl.exe genrsa -aes256 -out D:\Temp\test.pem -passout pass:123456 2048
openssl.exe pkcs12 -keypbe PBE-SHA1-3DES -aes256 -export -nocerts -inkey D:\Temp\test.pem -out D:\Temp\test.pfx -passin pass:123456 -passout pass:123456
$pass = ConvertTo-SecureString "123456" -AsPlainText -Force
Add-AzKeyVaultKey -VaultName "yeming" -Name "pfxfromps" -KeyFilePath D:\Temp\test.pem -KeyFilePassword $pass
```

## Investigation
Exception thrown at https://github.com/Azure/azure-powershell/blob/master/src/KeyVault/KeyVault/Models/PfxWebKeyConverter.cs#L58

Message: "The parameter is incorrect"
Stacktrace:
```
		StackTrace	"   
        at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(Byte[] rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags)\r\n   
        at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)\r\n   
        at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, SecureString password, X509KeyStorageFlags keyStorageFlags)\r\n   
        at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, SecureString password, X509KeyStorageFlags keyStorageFlags)\r\n   
        at Microsoft.Azure.Commands.KeyVault.Models.PfxWebKeyConverter.Convert(String pfxFileName, SecureString pfxPassword) in C:\\Users\\yeliu\\isra-fel\\azure-powershell\\src\\KeyVault\\KeyVault\\Models\\PfxWebKeyConverter.cs:line 58\r\n   
        at Microsoft.Azure.Commands.KeyVault.Models.PfxWebKeyConverter.ConvertKeyFromFile(FileInfo fileInfo, SecureString password) in C:\\Users\\yeliu\\isra-fel\\azure-powershell\\src\\KeyVault\\KeyVault\\Models\\PfxWebKeyConverter.cs:line 36\r\n   
        at Microsoft.Azure.Commands.KeyVault.AddAzureKeyVaultKey.CreateWebKeyFromFile() in C:\\Users\\yeliu\\isra-fel\\azure-powershell\\src\\KeyVault\\KeyVault\\Commands\\AddAzureKeyVaultKey.cs:line 300\r\n   
        at Microsoft.Azure.Commands.KeyVault.AddAzureKeyVaultKey.ExecuteCmdlet() in C:\\Users\\yeliu\\isra-fel\\azure-powershell\\src\\KeyVault\\KeyVault\\Commands\\AddAzureKeyVaultKey.cs:line 251\r\n   
        at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)\r\n   
        at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)\r\n   
        at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)\r\n   
        at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()"	string
```

**Comment by isra-fel** [comment] 2020-05-09 08:59
@jasonxdhu 
It seems the root cause is that the way dotnet parses an pfx does not work well when there's no certificate in it.
What is the reason behind `-nocerts` when generating the pfx file and is it possible for the customer to use a certificate to do it? i.e. `openssl.exe pkcs12 -in cert.pem ...`

**Comment by manorris6** [comment] 2020-05-12 19:28
@isra-fel Is do you know of a workaround that would allow the customer to use powershell for a pfx like this? 
Also they are using -nocerts due to Azure SQL BYOK using the an RSA to wrap the database encryption key. If the customer were to use a cert, what would happen with it in the import process to Key Vault?

**Comment by isra-fel** [comment] 2020-05-13 07:14
@manorris6  If the pfx is with a cert I'm pretty sure the current code will work (tested).

**Comment by isra-fel** [comment] 2020-05-13 07:15
Looping in KeyVault team. Could you kindly share some insights of how to parse a pfx file with no cert in it (in dotnet)?
Thanks

**Comment by jasonxdhu** [comment] 2020-05-13 17:14
This can be done through azure portal UX:
Go to your azure portal https://portal.azure.com/ and login
Select your key-vault (create one if you do not have)
Click "Keys" under "Settings"
Click "+ Generate/Import"
"Create a key" page will be displayed.
Select "Import" under "Options"
Select your key file under "File Upload"
Type key name
Click "Create" button

It will work with pfx file with no cert in it.

**Comment by manorris6** [comment] 2020-05-13 17:26
@jasonxdhu thanks for that information. Just to confirm, at this time, there is no way for a .pfx that does not contain a cert to be imported to Azure Key Vault using Powershell? This is the bug that is currently being addressed?

**Comment by jasonxdhu** [comment] 2020-05-13 17:33
Correct. That is my understanding. UX works but not PS. This is why customer was asking this to be fixed.

**Comment by qinl-li** [comment] 2020-05-13 18:49
Key vault portal has dependency on forgejs for this area. It is a third party library.(https://github.com/digitalbazaar/forge) 
It extracts JWK object from the key file and posted to service.

**Comment by isra-fel** [comment] 2020-05-14 02:13
> Key vault portal has dependency on forgejs for this area. It is a third party library.(https://github.com/digitalbazaar/forge)
> It extracts JWK object from the key file and posted to service.

Good to know. Thanks!
I was originally thinking the pfx file was uploaded to backend and parsed there by C# code :P
As Azure PowerShell is written in C# I cannot use forgejs directly, but I'll try to find a replacement.

**Comment by isra-fel** [comment] 2020-05-15 07:23
@grayzu @dcaro this is a feature request to Az.KeyVault, would you please consider it? Thank you

In short, the customer wants Az.KeyVault to support importing a special key, in the form of .pfx but not containing certification info, to Azure Key Vault.

**Comment by isra-fel** [comment] 2020-05-21 05:31
@jasonxdhu I did some research with the 3rd party library and it seemed not able to parse such special pfx file unfortunately. I'm sorry to say that we cannot support this scenario for the time being, my suggestion remains the same -- please use a pfx which contains certificate.

**Comment by dingmeng-xue** [comment] 2020-06-02 14:41
Close this issue because there is a no ready solution to support this case.

**Closed by dingmeng-xue** 2020-06-02 14:41 UTC
Labels: Azure PS Team, KeyVault, customer-reported, feature-request
