### ISSUE TITLE
Azure Disk Encryption extension version '2.2' is not supported.

### ISSUE THREAD

**Issue by thwpike** [Azure/azure-powershell#6337] opened 2018-05-30 08:39 UTC
### Description

When attempting to enable disk encryption the following error is shown:

```
Azure Disk Encryption extension version '2.2' is not supported
```

### Script/Steps for Reproduction

Having run [this script](https://github.com/Azure/azure-powershell/blob/master/src/ResourceManager/Compute/Commands.Compute/Extension/AzureDiskEncryption/Scripts/AzureDiskEncryptionPreRequisiteSetup.ps1), specifically this line:

```powershell
Set-AzureRmVMDiskEncryptionExtension -ResourceGroupName $resourceGroupName -VMName $vmName -DiskEncryptionKeyVaultUrl $diskEncryptionKeyVaultUrl -DiskEncryptionKeyVaultId $keyVaultResourceId -KeyEncryptionKeyUrl $keyEncryptionKeyUrl -KeyEncryptionKeyVaultId $keyVaultResourceId -VolumeType 'All';
```

We get this error:
```
DEBUG: 10:47:22 AM - SetAzureDiskEncryptionExtensionCommand end processing.
Set-AzureRmVMDiskEncryptionExtension : Azure Disk Encryption extension version '2.2' is not supported.
ErrorCode: NotSupported
ErrorMessage: Azure Disk Encryption extension version '2.2' is not supported.
StatusCode: 409
ReasonPhrase: Conflict
OperationID : 2cb4ac35-e2a5-4cd4-84d9-3174663e0a46
At line:1 char:1
+ Set-AzureRmVMDiskEncryptionExtension -ResourceGroupName $resourceGrou ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmVMDiskEncryptionExtension], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Extension.AzureDiskEncryption.SetAzureDiskEncryptionExtensionCommand
```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable

ModuleType Version    Name                                ExportedCommands                                                                                                                    
---------- -------    ----                                ----------------                                                                                                                    
Script     6.0.1      AzureRM                                                                                                                                                                 
```

**Comment by maddieclayton** [comment] 2018-05-30 20:27
@ejarvi @hyonholee Can you take a look at this issue?

**Comment by bytemech** [comment] 2018-06-05 10:56
Same issue happening to my environment as well. Have version 6.1.1 of AzureRM module installed, version 5.0.0 of the AzureRM.Compute module. 

Decompiled and took a look at the Microsoft.Azure.Commands.Compute dll and it looks to me that it's not the powershell module that's the cause, and the 409 response is coming from Graph.

**Comment by rkluijt** [comment] 2018-06-06 12:09
Hi thwpike,

Did you found any resolution yet?
I have the same error message during disk encryption on my Windows 2016 VM in Azure.

Thanks

Kind regards
Robin

**Comment by ejarvi** [comment] 2018-06-06 18:02
Took a look at this issue.  

The ability to add encryption without specifying AAD credentials is new and still requires an opt-in from some subscriptions until full rollout is complete.   In support of earlier comments this would also support why the failure was seen coming from Graph rather than the powershell module. 

Two potential workarounds for this would be to either reverting back to using the AAD parameters in the syntax (avoiding the use of this feature entirely), or opting in manually to this feature using the following steps prior to enabling encryption:

```
Register-AzureRmProviderFeature -ProviderNamespace "Microsoft.Compute" -FeatureName  "UnifiedDiskEncryptionForVMs"
Wait 10 min till state transitions to 'Registered' 
Register-AzureRmResourceProvider -ProviderNamespace Microsoft.Compute 
```

**Comment by rkluijt** [comment] 2018-06-07 09:56
Dear Ejarvi,

Thanks for the workaround I will try this later today.
Keep you posted on this.

Kind regards
Robni

**Comment by rkluijt** [comment] 2018-06-07 10:09
Hi Ejarvi,

Nope. the 2nd wordaround didn't work. Will have a look into the AAD parameters and hopefully I can get this working.

Keep you posted again.

Kind regards
RObin

**Comment by bytemech** [comment] 2018-06-07 13:04
Works for me!

**Comment by ejarvi** [comment] 2018-06-14 18:42
The opt-in requirement has now been removed in all regions, so closing this out.   (The workaround should no longer be needed)

**Closed by ejarvi** 2018-06-14 18:42 UTC
Labels: Compute - Extensions

**Comment by rkluijt** [comment] 2018-06-15 06:52
Hi Guys,

I noticed that because the Key-Vault was in a different Region then the VM it failed.
Now everything is working as it should be.

Thanks all for you help and support.

Kind regards
Robin
