### ISSUE TITLE
Enable-AzCdnCustomDomainCustomHttps - Bad Request (Property 'CustomHttpsParameters.CertificateSourceParameters.CertificateType' is required but it was not set)

### ISSUE THREAD

**Issue by pjmvp** [Azure/azure-powershell#18700] opened 2022-06-23 20:39 UTC
### Description

I'm trying to enable HTTPS in my CDN custom domain. I want it to have a CDN-managed certificate.

I get the Cdn Custom Domain using **Get-AzCdnCustomDomain** and pipe the result to **Enable-AzCdnCustomDomainCustomHttps**.

I pass a hash table to **Enable-AzCdnCustomDomainCustomHttps**' CustomDomainHttpsParameter. 

The hash table is defined as:

```
$customDomainHttpsParameter = @{
  CertificateSource = "Cdn"
  ProtocolType = "ServerNameIndication"
  MinimumTlsVersion = "TLS12" 
}
```

But the response is a BadRequest with the error message:

> "Property 'CustomHttpsParameters.CertificateSourceParameters.CertificateType' is required but it was not set"

I've also tried:

```
$customDomainHttpsParameter = @{
  CertificateSource = "Cdn"
  ProtocolType = "ServerNameIndication"
  MinimumTlsVersion = "TLS12" 
  CertificateSourceParameter = @{
    CertificateType = "Shared"
  }  
}
```

But the result is the same. When running with -Debug flag I see the payload being POSTed is:

```
Body:
{
  "certificateSource": "Cdn",
  "protocolType": "ServerNameIndication",
  "minimumTlsVersion": "TLS12"
}

```
So the CertificateSourceParameter , if needed at all, is being ignored by the parser.
This behaviour is probably driven by [this part of the code](https://github.com/Azure/azure-powershell/blob/38d92a863ad7216504913fcf6ce0e11dc393c167/src/Cdn/generated/api/Models/Api20210601/CustomDomainHttpsParameters.PowerShell.cs#L68-L90).

It looks like a mismatch between the REST API and what the cmdlet serializes and sends. Or could I be creating my hash table incorrectly? The [documentation is incomplete.](https://docs.microsoft.com/en-us/powershell/module/az.cdn/enable-azcdncustomdomaincustomhttps?view=azps-8.0.0)

How can I enable HTTPS in my CDN custom domain using this PowerShell Module?

### Issue script & Debug output

```PowerShell
$customDomainHttpsParameter = @{
  CertificateSource = "Cdn"
  ProtocolType = "ServerNameIndication"
  MinimumTlsVersion = "TLS12" 
  CertificateSourceParameter = @{
    CertificateType = "Shared"
  }  
}

Get-AzCdnCustomDomain -ResourceGroupName $ResourceGroup -ProfileName $ProfileName -EndpointName $EndpointName -Name $CustomDomainName | Enable-AzCdnCustomDomainCustomHttps -CustomDomainHttpsParameter $customDomainHttpsParameter -Debug
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      6.2.4
PSEdition                      Core
GitCommitId                    6.2.4
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.8.0      Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     2.1.0      Az.Cdn                              {Clear-AzCdnEndpointContent, Clear-AzFrontDoorCdnEndpointContent, Disable-AzCdnCustomDomainCustomHttps, Enable-AzCdnCustomDomainCustomHttps…}
```

### Error output

```PowerShell
Message        : [BadRequest] : Property 'CustomHttpsParameters.CertificateSourceParameters.CertificateType' is required but it was not set
StackTrace     :
Exception      : System.Exception
InvocationInfo : {Enable-AzCdnCustomDomainCustomHttps_EnableViaIdentity}
Line           : Get-AzCdnCustomDomain -ResourceGroupName $ResourceGroup -ProfileName $ProfileName -EndpointName $EndpointName -Name $CustomDomainName | Enable-AzCdnCustomDomainCustomHttps
                 -CustomDomainHttpsParameter $customDomainHttpsParameter -Debug

Position       : At C:\Users\pedro\Source\Repos\dataops-snowbox\devops\deploy\scripts\SetCdn.ps1:47 char:1
                 + Get-AzCdnCustomDomain -ResourceGroupName $ResourceGroup -ProfileName  ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 4
```

**Comment by navba-MSFT** [comment] 2022-06-27 04:16
@pjmvp Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment] 2022-06-28 04:47
@pjmvp Could you please try this ?

>$customDomainHttpsParameter = [New-AzCdnManagedHttpsParametersObject](https://docs.microsoft.com/en-us/powershell/module/az.cdn/new-azcdnmanagedhttpsparametersobject?view=azps-8.0.0) -CertificateSourceParameterCertificateType Dedicated -CertificateSource Cdn -ProtocolType ServerNameIndication
>
>[Enable-AzCdnCustomDomainCustomHttps](https://docs.microsoft.com/en-us/powershell/module/az.cdn/enable-azcdncustomdomaincustomhttps?view=azps-8.0.0) -ResourceGroupName RGName -ProfileName name -EndpointName name -CustomDomainName domain.in -CustomDomainHttpsParameter $customDomainHttpsParameter

**Comment by navba-MSFT** [comment] 2022-07-01 05:01
@pjmvp I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by pjmvp** [comment] 2022-07-01 23:29
@navba-MSFT, thanks for reaching out. 

It works when I run it locally (my laptop). 

- The fact that one can/should use 'New-AzCdnManagedHttpsParametersObject' is not [properly documented.](https://docs.microsoft.com/en-us/powershell/module/az.cdn/enable-azcdncustomdomaincustomhttps?view=azps-8.0.0)

However, if I **run it in Azure DevOps**, using the AzurePowerShell@5

```
    - task: AzurePowerShell@5
      displayName: Enable HTTPS in CustomDomain
      inputs:
        azureSubscription: '...service connection...'
        ScriptPath: ...path to .ps1 script...'
        ScriptArguments: '...the arguments...'
        azurePowerShellVersion: LatestVersion     
```

it fails with 

> ##[error]The term 'New-AzCdnManagedHttpsParametersObject' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Sounds like a version mismatch? 

Can Az PowerShell 8.0.0 be used in Azure DevOps together with AzurePowerShell@5?

**Comment by navba-MSFT** [comment] 2022-07-05 10:56
@pjmvp Could you please ensure that you are using Azure Powershell task and not plain powershell task? Did you try with the Azure Powershell Script:Inline task ? Awaiting your reply.

**Comment by pjmvp** [comment] 2022-07-05 18:07
@navba-MSFT, I am indeed using the Azure PowerShell task (`AzurePowerShell@5`, as shown in my previous comment's code snippet), which reads the script content from a **.ps1** file specified in ScriptPath.

However, `New-AzCdnManagedHttpsParametersObject` doesn't seem to be available in that task. I'd imagine the task is using an older version of Azure PowerShell (e.g. 7.5.0) which doesn't have that command yet?

I can't seem to find any documentation saying which version of Azure PowerShell is used by the AzurePowerShell@5 task.
Or if it's possible to somehow make it use the 8.0.0 version for that matter. I can try putting the script inline instead of from a file, but I don't think it'll make a difference, the script content is the same whether it's read from a file or inline.

**Comment by navba-MSFT** [comment] 2022-07-07 04:58
@pjmvp The command is introduced in Az PowerShell 8.0, that might explain why this command couldn't be find in AzurePowerShell@5 task.

You could actually specify the target Azure PowerShell version in the task: [[https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops]](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops)

 
![image](https://user-images.githubusercontent.com/57353862/177694542-78b2999b-ffb9-4c71-828d-3a66446f675d.png)



![image](https://user-images.githubusercontent.com/57353862/177694586-45b7cb42-08c4-4675-a9c4-43bb4fcd1ffc.png)

You could also update the Az.Cdn module to 2.1.0 in your script using:

>Update-Module -Name Az.Cdn -RequiredVersion 2.1.0

Let me know if this solves your problem. Awaiting your reply.

**Comment by navba-MSFT** [comment] 2022-07-08 03:41
@pjmvp Thanks for getting back. I am glad that the issue is addressed. I will create a PR to enhance [this](https://docs.microsoft.com/en-us/powershell/module/az.cdn/enable-azcdncustomdomaincustomhttps?view=azps-8.0.0#description) documentation.

**Comment by navba-MSFT** [comment] 2022-07-08 04:23
@pjmvp Seems like the fix for the examples has been committed already. see [here](https://github.com/Azure/azure-powershell/commit/6b2487b93576d5b86f82ab050a89bae79eaaf7e5). So this should be fixed in next release. With that we will proceed with closure of this GitHub thread. If you have any follow-up queries, please feel free to reopen this thread. We would be happy to help.

**Closed** 2022-07-08 04:23 UTC
Labels: Network - CDN, bug, customer-reported, CXP Attention
