### ISSUE TITLE
Get-AzureResourceGroup is not recognized in AzureRM Version 1.6

### ISSUE THREAD

**Issue by KeithHaysHSTM** [Azure/azure-powershell#2673] opened 2016-07-27 15:38 UTC
PS C:\Users\khays> Get-AzureResourceGroup -Tag @{Name="Owner";Value="Keith"}
Get-AzureResourceGroup : The term 'Get-AzureResourceGroup' is not recognized as the name 
of a cmdlet, function, script file, or operable program. Check the spelling of the name, 
or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-AzureResourceGroup -Tag @{Name="Owner";Value="Keith"}
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-AzureResourceGroup:String) [], Command 
   NotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by markcowl** [comment] 2016-07-27 17:11
@KeithHaysHSTM This is by design.  All ARM cmdlets now use the Noun prefix AzureRM instead of Azure.  This was done to allow loading RDFE and ARM cmdlets side-by-side.  See this [wiki article](https://github.com/Azure/azure-powershell/wiki/Deprecation-of-Switch-AzureMode-in-Azure-PowerShell) for details.

Closing ass by design

**Closed by markcowl** 2016-07-27 17:11 UTC
