### ISSUE TITLE
Get-AzRecoveryServicesBackupRecoveryPoint inconsistant data

### ISSUE THREAD

**Issue by DanteNahuel** [Azure/azure-powershell#10102] opened 2019-09-24 17:38 UTC
Hi all
When I use the cmdlet I get inconsistant/incorrect output.
Sometimes the output comes up empty but I check the Portal and there are Recovery Points available.
Sometimes the output comes up empty if I use -startdate parameter
And instead brings up all the Restore Points if I don't use -startdate 

Here's the general cmdlet I use
```
$dates = ((get-date).adddays(-90)).ToUniversalTime()
$rp = Get-AzRecoveryServicesBackupRecoveryPoint -Item $backupitem -VaultId $VaultID -StartDate $dates
```

I understand this is not very specific but I believe the issue is with dates longer than 30 days ago.

**Comment by msJinLei** [comment] 2019-09-25 06:12
@DanteNahuel 
Could you provide the following information for your environment and issue? 

## Environment data



```

```

## Module versions



```powershell

```

## Debug output



```

```

## Error output




_If the problem is unable be reproduced stably. Please list in details about your environment and provide steps which are most possible to reproduce it.__

**Comment by msJinLei** [comment] 2019-10-11 02:01
@DanteNahuel Any update for it?

**Comment by msJinLei** [comment] 2019-12-12 03:35
@DanteNahuel We are going to close the issue if no update for this issue for a long time. You can submit a new one when you have further update.

**Closed** 2019-12-16 08:49 UTC
Labels: More Info :label:, customer-reported
