### ISSUE TITLE
ARM: Add-AzureRmAccount doesn't persist credentials between sessions

### ISSUE THREAD

**Issue by tylerham** [Azure/azure-powershell#1272] opened 2015-11-10 23:14 UTC
Service Manager's `Add-AzureAccount` keeps credentials between sessions. This is very handy when using these cmdlets for automation.
It would be great if Resource Manager's `Add-AzureRMAccount` / `Login-AzureRmAccount` had a similar feature.

**Comment by markcowl** [comment] 2015-11-11 00:06
@tylerham  The move away from *automatically* persisting credentials is intentional. You can use 

```
Save-AzureRMProfile -Path <path-to-file>
```
to save your current credentials and

```
Select-AzureRmProfile -Path <path to file>
```

to load them in a new session.

**Comment by markcowl** [comment] 2015-11-11 00:07
@tylerham  We also have a work item to add an opt-in automatic save and load of credentials feature.  Closing this as a duplicate for now in lieu of this feature

**Closed by markcowl** 2015-11-11 00:07 UTC

**Comment by tylerham** [comment] 2015-11-11 00:19
Great, thanks. I figured it was intentional especially when I saw `Save-AzureRmProfile` but couldn't figure out the usage.

**Comment by gregjhogan** [comment] 2016-03-20 20:19
@markcowl is the auto save/load still in progress?  Where is the issue that this is a duplicate of?  Thanks!
