### ISSUE TITLE
Get-AzAutomationWebhook doesn't return Webhook parameters

### ISSUE THREAD

**Issue by brsrom** [Azure/azure-powershell#10041] opened 2019-09-16 15:21 UTC
## Description

Get-AzAutomationWebhook doesn't return any parameters, however, those are specified on the Azure Portal and visible there (see debug output).

## Steps to reproduce

```
Get-AzAutomationWebhook -ResourceGroupName "blablabla-rg" -AutomationAccountName "blablabla-aa" -RunbookName "runbook001" 

```

## Module versions
Az.Automation = 1.3.2

## Debug output

```
ResourceGroupName     : blablabla-rg
AutomationAccountName : blablabla-aa
Name                  : runbook001Webhook
CreationTime          : 04/01/2019 14:12:37 +01:00
Description           : 
ExpiryTime            : 04/01/2021 14:10:05 +01:00
IsEnabled             : True
LastInvokedTime       : 13/09/2019 15:38:19 +02:00
LastModifiedTime      : 11/07/2019 07:52:58 +02:00
Parameters            : {}
RunbookName           : runbook001
WebhookURI            : 
HybridWorker          : 
```

**Comment by abhinav-ghai** [comment] 2019-09-19 00:23
I just tried this cmdlet with version 1.3.2 and it seems to return webhook parameters. Can you please provide the parameter block of your runbook?

**Comment by brsrom** [comment] 2019-09-19 09:14
> I just tried this cmdlet with version 1.3.2 and it seems to return webhook parameters. Can you please provide the parameter block of your runbook?

Here is a snippet from a runbook: 
`

    param(
    [parameter(Mandatory=$True)]
    [String] $Connection,

    [parameter(Mandatory=$True)]
    [string] $Server,
        
    [parameter(Mandatory=$False)]
    [string] $Database = "blablabla",
        
    [parameter(Mandatory=$True)]
    [PSCredential] $Credentials,

    [Parameter (Mandatory = $false)]
    [Object] $WebhookData
)

`

**Comment by abhinav-ghai** [comment] 2019-09-19 18:30
I tried to create a webhook with exactly same list of parameters in a runbook. I was able to see the parameters.

PS C:\windows\system32> $webhook
ResourceGroupName     : rgName
AutomationAccountName : accountName
Name                  : testParamWebhook
CreationTime          : 9/19/2019 11:27:22 AM -07:00
Description           :
ExpiryTime            : 9/19/2020 11:26:06 AM -07:00
IsEnabled             : True
LastInvokedTime       : 1/1/0001 12:00:00 AM +00:00
LastModifiedTime      : 9/19/2019 11:27:22 AM -07:00
Parameters            : {Connection, Credentials, Database, Server...}
RunbookName           : testRunbook
WebhookURI            :
HybridWorker          :

PS C:\windows\system32> $webhook.Parameters

Name                           Value
----                           -----
Connection                     connectionStringValue
Credentials                    @{UserName=user; Password=password}
Database                       databaseStringValue
Server                         serverStringValue
webhookData                    {}

**Comment by brsrom** [comment] 2019-09-20 07:52
Can you please check it with PowerShell Core?

**Comment by abhinav-ghai** [comment] 2019-09-23 20:21
Just tried on PowerShell Core with version 1.3.2 for Az Automation on Mac. No repro.

![image](https://user-images.githubusercontent.com/1511158/65459549-0618c480-de05-11e9-83b6-6cd0896de78c.png)

**Comment by brsrom** [comment] 2019-09-24 13:30
> Just tried on PowerShell Core with version 1.3.2 for Az Automation on Mac. No repro.
> 
> ![image](https://user-images.githubusercontent.com/1511158/65459549-0618c480-de05-11e9-83b6-6cd0896de78c.png)

Ok, got it. Indeed, there are 2 different commands to get either name of the webhooks in the runbook or get full data about webhook including parameters. 

But here is some JSON parsing issue for you:

`Body:
{
  "id": "/subscriptions/xxxxx/resourceGroups/xxxxxxx/providers/Microsoft.Automation/automationAccounts/xxxxxx/webhooks/xxxxxxxx",
  "name": "xxxxxxxx",
  "type": "Microsoft.Automation/AutomationAccounts/Webhooks",
  "properties": {
    "isEnabled": true,
    "expiryTime": "2021-01-04T14:10:05.196+01:00",
    "runbook": {
      "name": "xxxxxxx"
    },
    "lastInvokedTime": "2019-09-13T15:38:19.8549363+02:00",
    "runOn": null,
    "parameters": {
      "Server": "\"xxxxxxx.mysql.database.azure.com\"",
      "Connection": "\"devSubscriptionConnection\"",
      "credentials": "MySQLDev",
      "Database": "\"xxxxxxxx\""
    },
    "uri": "",
    "creationTime": "2019-01-04T14:12:37.894897+01:00",
    "lastModifiedBy": "",
    "lastModifiedTime": "2019-07-11T07:52:58.7597985+02:00"
  }
}


Get-AzAutomationWebhook : Conversion from JSON failed with error: Unexpected character encountered while parsing value: M. Path '', line 0, position 0.
At line:1 char:12
+ $webhook = Get-AzAutomationWebhook -ResourceGroupName "xxxxxxxxx ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Get-AzAutomationWebhook], CmdletInvocationException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationWebhook`

**Comment by abhinav-ghai** [comment] 2019-09-24 17:50
The issue is with the extra double quotes in your parameters section on Server, Connection and Database. Remove the additional double quotes and it should work.

**Comment by brsrom** [comment] 2019-09-26 12:09
> The issue is with the extra double quotes in your parameters section on Server, Connection and Database. Remove the additional double quotes and it should work.

they are escaped with a backslash, github doesn't show it. I know that this is the issue, but the question is whether it's expected behavior?

**Comment by andyw248** [comment] 2019-12-21 01:16
Closing as for the original issue the cmdlet behavior has been clarified.

**Closed by andyw248** 2019-12-21 01:16 UTC
Labels: Automation, Service Attention
