### ISSUE TITLE
Add wildcard support and ensure top level resources can be filtered by Name only

### ISSUE THREAD

**Issue by kilasuit** [Azure/azure-powershell#6549] opened 2018-06-27 15:10 UTC
### Description

I should be able to return VM's without needing to supply a Resource Group name directly from calling  get-AzureRMVM without having to pipe this to Where-Object 

### Script/Steps for Reproduction

```powershell
$VMName = 'MyVM'
Get-AzureRMVM -Name  $VMName 

```

forces a request for the resource group name - this should not be a requirement when Name is provided and should be 2 seperate Parameter Sets, one that allows you to get the VM by name and one that allows you to get all VM's in a Resource Group by Resource Group Name

This is likely not just limited to VM's but all resource types
### Module Version

AzureRM.Compute 5.1.1
AzureRM 6.3.0
### Environment Data

``` powershell
$psversiontable

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      16299  431     
```

**Comment by cormacpayne** [comment] 2018-07-02 18:29
@kilasuit Hey Ryan, thanks for the feedback -- I think this is something that should be done for all `Get-*` cmdlets to allow for another type of filter 😀

@praries880 would you mind syncing up with @hyonholee about what would need to be done to enable this scenario in the generated cmdlet code for Compute?

**Comment by kilasuit** [comment] 2018-07-25 09:12
Thanks @cormacpayne  - @hyonholee & @praries880 - Any updates on this at all?

**Comment by markcowl** [comment] 2018-08-14 19:03
@kilasuit Yes, we are looking at a common set of functionality across cmdlets to allow wildcards and completion over the components of the resource ID.  This would include allowing you to filter the list of VMs by name (or partial name) for example, and potentially auto-complete VM names by partial name.

We plan to prototype this functionality post-ignite, and have this released later this year.

**Comment by markcowl** [comment] 2018-10-13 01:39
@maddieclayton Post Resource completer - Get cmdlets for top level resources that:
(1) Allow providing a resource name or wildcard to list all VMs with that name

**Comment by cormacpayne** [comment] 2018-12-18 22:59
@kilasuit the has been added to `Get-AzVM`, but we are looking for more areas to add this functionality as well

**Comment by maddieclayton** [comment] 2018-12-26 18:40
This seems to be multiple parts:
- [ ] Ensure that all top level resources can list over subscription as well as resourcegroupname
- [ ] Add wildcard support for all Get "Name" parameters to allow listing with filters

We need to decide whether this will just be in top level resources, and whether we only filter by "Name", or if we would support filtering by parent resource name as well (this could increase the time that it takes to run the cmdlet by a fair amount).

**Comment by maddieclayton** [comment] 2019-01-28 22:53
Add separate issue for Wildcard support: https://github.com/Azure/azure-powershell/issues/8426

Will make this issue only about supporting name only filtering for top level gets.

**Comment by pcgeek86** [comment] 2019-02-20 22:46
This is a duplicate of #3030

**Comment by maddieclayton** [comment] 2019-03-02 07:06
Base work done and logic applied to Compute! https://github.com/Azure/azure-powershell/pull/8492
Next core cmdlet:
- [ ] Network
- [ ] KeyVault
- [ ] SQL
- [ ] Automation
- [ ] Resources (where applicable)
- [ ] Storage
- [ ] Websites

**Comment by maddieclayton** [comment] 2019-04-09 19:44
Applied to all core cmdlets, the rest will be taken care of with the generator

**Closed by maddieclayton** 2019-04-09 19:44 UTC
Labels: Azure PS Team, Customer Experience, Pull Request Open
