### ISSUE TITLE
Set-AzureRmContext doesn't work after using Select-AzureRmProfile

### ISSUE THREAD

**Issue by wangzq** [Azure/azure-powershell#2387] opened 2016-06-03 04:34 UTC
To reproduce:

```
# First login as usual, such as Add-AzureRmAccount
Save-AzureRmProfile -Path .\armprofile.json
# Create a new PowerShell session, or use current one
Select-AzureRmProfile -Path .\armprofile.json
Select-AzureRmSubscription -SubscriptionName '<your subscription name>'
```

The last command above will fail with following error:
```
Set-AzureRmContext : Cannot retrieve the dynamic parameters for the cmdlet. Cannot process argument because the value of argument "validValues" is out of range. Change argument "validValues" to  a value
that is within range.
Parameter name: validValues
Actual value was System.String[].
```

This is because the subscriptions list is empty or null in following code from SetAzureRMContext.cs, since we used `Select-AzureRmProfile` instead of `Add-AzureRmAccount` to login:

```
        private RuntimeDefinedParameterDictionary CreateDynamicParameterDictionary()
        {
            var runtimeDefinedParameterDictionary = new RuntimeDefinedParameterDictionary();

            var subscriptionIdAttributes = new Collection<Attribute>
            {
                new ParameterAttribute
                {
                    ParameterSetName = SubscriptionIdParameterSet,
                    Mandatory = false,
                    HelpMessage = "Subscription",
                    ValueFromPipelineByPropertyName = true
                },
                new ValidateSetAttribute(AzureRmProfileProvider.Instance.Profile.Context.Account.GetPropertyAsArray(AzureAccount.Property.Subscriptions)),
            };
```

**Comment by markcowl** [comment] 2016-06-03 21:00
@wangzq Yeah, this is actually terribly broken cod, as the subscription name is the allowed set of subscription names are always dynamic

**Comment by wangzq** [comment] 2016-06-03 21:32
As a temporary workaround, I wrote following function:

```
function Set-AzureExRmContext
{
	<#
	.Synopsis
		Azure-PowerShell 1.5.0 has an issue: if you use Select-AzureRmProfile to load a profile from file, then it 
		will not contain subscriptions list, thus the Add-AzureRmContext (alias: Select-AzureRmSubscription) will fail
		as the dynamic parameter `SubscriptionName` will need a list of subscriptions to work.

		To workaround this issue, I created this cmdlet to directly invoke the related c# code from 1.5.0 source code.
	.Example
		PS> Set-AzureExRmContext $subscriptionName
	#>
	[CmdletBinding()]
	param (
		[Parameter(Mandatory=$true)]
		[string] $SubscriptionName
		)
	
	<#
                var profileClient = new RMProfileClient(AzureRmProfileProvider.Instance.Profile);
                if (!string.IsNullOrWhiteSpace(SubscriptionId) || !string.IsNullOrWhiteSpace(SubscriptionName))
                {
                    profileClient.SetCurrentContext(SubscriptionId, SubscriptionName, TenantId);
                }
	#>	
	$profileClient = New-Object Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient([Microsoft.WindowsAzure.Commands.Common.AzureRmProfileProvider]::Instance.Profile)
	# TODO: it might be possible to retrieve the tenant id from AzureRmProfile
	$profileClient.SetCurrentContext($null, $SubscriptionName, $null)
}
```

**Comment by spaelling** [comment] 2016-06-09 20:55
The issue is not only with -SubscriptionName, the code below also fails:

```
# this works fine
$SubId = (Set-AzureRmContext -SubscriptionName 'bizspark').Subscription.SubscriptionId
# now this fails
Set-AzureRmContext -SubscriptionId $SubId
```

So in general for me I cannot select the subscription I want using ID.

**Comment by markcowl** [comment] 2016-06-21 20:00
help is on the way.  Just sent a PR that fixes this and should be out on the strreet tomorrow.

**Comment by markcowl** [comment] 2016-06-24 23:25
This is now on webpi and will be in the gallery in a bit.

**Closed by markcowl** 2016-06-24 23:25 UTC
Labels: Team
