### ISSUE TITLE
Add automated test for -JsonAttribute & -ChefServiceInterval option for Set-AzureRMVmChefExtension

### ISSUE THREAD

**Issue by Vasu1105** [Azure/azure-powershell#3147] opened 2016-10-27 09:17 UTC
REF: #3083 

Pending automated test for newly added option -JsonAttribute & -ChefServiceInterval in Set-AzureRMVMChefExtension

There is dependency on #2713 to be get merged for this.

**Comment by markcowl** [comment] 2016-11-02 19:23
closing a sduplicate of #3146

**Closed by markcowl** 2016-11-02 19:23 UTC
Labels: Compute, Test Debt
