### ISSUE TITLE
Remove-AzVmssDataDisk does not work if there is only 1 data disk attached to VMSS

### ISSUE THREAD

**Issue by Jyotsna-Anand** [Azure/azure-powershell#13368] opened 2020-10-29 22:27 UTC
## Description
I noticed an issue with the Remove-AzVmssDataDisk cmdlet. The cmdlet works fine when there are multiple data disks attached to a VMSS. But when the disk I’m trying to delete is the ONLY data disk attached to the VMSS, the cmdlet does not throw an error but the deletion is never actually performed. I have been using the below set of commands to remove the data disk. 

The same scenario works fine when I delete using portal or CLI. Can you please review and let me know if there is an issue with this specific scenario?

## Steps to reproduce
1. Create a VMSS with only 1 data disk attached. 
2. Delete the data disk using below PS commands
3. Check instance view of VMSS VM after running the commands. The disk will still be attached. 
```powershell
$vmssRemoveConfig = Get-AzVmss -ResourceGroupName $rgname -VMScaleSetName $vmssname
$vmssRemoveConfig = Remove-AzVmssDataDisk -VirtualMachineScaleSet $vmssRemoveConfig -Lun $diskLUNSlot
Update-AzVmss -ResourceGroupName $rgname -Name $vmssname -VirtualMachineScaleSet $vmssRemoveConfig 
```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by ArmaanMcleod** [comment] 2020-10-30 14:46
I can confirm the same behaviour version 4.7.0. Seems like this is a bug.

**Comment by Drewm3** [comment] 2020-11-05 05:41
@avirishuv, could you please look into this issue.

**Comment by avirishuv** [comment] 2020-11-05 20:00
I was able to repro this, removing data disk from VMSS that has only one data disk using Azure PowerShell returns successfully but does not delete the data disk, while it works if there are more than one data disks attached to VMSS.
Marking this as a bug.

**Comment by avirishuv** [comment] 2020-12-03 21:09
quick update: we have added this as a bug to be resolved, will provide an update here when the work gets picked up.

**Comment by avirishuv** [comment] 2021-03-03 19:42
apologies for the delay here, this work is yet to be picked up for development.

**Comment by grizzlytheodore** [comment] 2021-03-11 15:02
this seems to be an issue in the API level. Here is the API request on response output. It requests https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesets/createorupdate without lun 0 but it still returns VMSS with lun 0. 

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/e37510d7-33b6-4676-886f-ee75bcc01871/resourceGroups/theo_temp/providers/Microsoft.Compute/virtualMachineScaleSets/vmssTemp?api-version=2020-06-01

Headers:
x-ms-client-request-id        : 88af996a-4104-48db-9f10-235ab63df7dc
Accept-Language               : en-US

Body:
{
  "sku": {
    "name": "Standard_B1s",
    "tier": "Standard",
    "capacity": 2
  },
  "properties": {
    "upgradePolicy": {
      "mode": "Manual"
    },
    "virtualMachineProfile": {
      "osProfile": {
        "computerNamePrefix": "vmsstempg",
        "adminUsername": "grizzlytheodore",
        "windowsConfiguration": {
          "provisionVMAgent": true,
          "enableAutomaticUpdates": true
        },
        "secrets": []
      },
      "storageProfile": {
        "imageReference": {
          "publisher": "MicrosoftWindowsServer",
          "offer": "WindowsServer",
          "sku": "2019-Datacenter",
          "version": "latest"
        },
        "osDisk": {
          "caching": "ReadWrite",
          "writeAcceleratorEnabled": false,
          "createOption": "FromImage",
          "diskSizeGB": 127,
          "osType": "Windows",
          "managedDisk": {
            "storageAccountType": "Premium_LRS"
          }
        }
      },
      "networkProfile": {
        "networkInterfaceConfigurations": [
          {
            "name": "theo_temp-vnet-nic01",
            "properties": {
              "primary": true,
              "enableAcceleratedNetworking": false,
              "networkSecurityGroup": {
                "id": "/subscriptions/e37510d7-33b6-4676-886f-ee75bcc01871/resourceGroups/theo_temp/providers/Microsoft.Network/networkSecurityGroups/basicNsgtheo_temp-vnet-nic01"
              },
              "dnsSettings": {
                "dnsServers": []
              },
              "ipConfigurations": [
                {
                  "name": "theo_temp-vnet-nic01-defaultIpConfiguration",
                  "properties": {
                    "subnet": {
                      "id": "/subscriptions/e37510d7-33b6-4676-886f-ee75bcc01871/resourceGroups/theo_temp/providers/Microsoft.Network/virtualNetworks/theo_temp-vnet/subnets/default"
                    },
                    "primary": true,
                    "privateIPAddressVersion": "IPv4"
                  }
                }
              ],
              "enableIPForwarding": false
            }
          }
        ]
      },
      "diagnosticsProfile": {
        "bootDiagnostics": {
          "enabled": true
        }
      },
      "extensionProfile": {
        "extensions": [
          {
            "name": "Microsoft.Azure.Security.AntimalwareSignature.AntimalwareConfiguration",
            "properties": {
              "publisher": "Microsoft.Azure.Security.AntimalwareSignature",
              "type": "AntimalwareConfiguration",
              "typeHandlerVersion": "2.0",
              "autoUpgradeMinorVersion": true,
              "enableAutomaticUpgrade": true,
              "settings": {},
              "provisionAfterExtensions": []
            }
          },
          {
            "name": "Microsoft.Azure.Geneva.GenevaMonitoring",
            "properties": {
              "publisher": "Microsoft.Azure.Geneva",
              "type": "GenevaMonitoring",
              "typeHandlerVersion": "2.0",
              "autoUpgradeMinorVersion": true,
              "enableAutomaticUpgrade": true,
              "settings": {},
              "provisionAfterExtensions": []
            }
          }
        ]
      },
      "priority": "Regular"
    },
    "overprovision": true,
    "doNotRunExtensionsOnOverprovisionedVMs": false,
    "singlePlacementGroup": true,
    "platformFaultDomainCount": 5,
    "scaleInPolicy": {
      "rules": [
        "Default"
      ]
    }
  },
  "location": "eastus2",
  "tags": {
    "platformsettings.host_environment.service.platform_optedin_for_rootcerts": "true"
  }
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
Retry-After                   : 10
Azure-AsyncOperation          : https://management.azure.com/subscriptions/e37510d7-33b6-4676-886f-ee75bcc01871/providers/Microsoft.Compute/locations/eastus2/operations/7ce2e627-a126-4a6f-a62d-3039afdad7c7?api-version=2020-06-01
Azure-AsyncNotification       : Enabled
x-ms-ratelimit-remaining-resource: Microsoft.Compute/CreateVMScaleSet3Min;58,Microsoft.Compute/CreateVMScaleSet30Min;297,Microsoft.Compute/VmssQueuedVMOperations;0
x-ms-request-charge           : 0
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 7ce2e627-a126-4a6f-a62d-3039afdad7c7
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : 543d8d62-9b9b-4337-856a-7d1f2f0c64e3
x-ms-routing-request-id       : CENTRALUS:20210311T145149Z:543d8d62-9b9b-4337-856a-7d1f2f0c64e3
X-Content-Type-Options        : nosniff
Date                          : Thu, 11 Mar 2021 14:51:48 GMT

Body:
{
  "name": "vmssTemp",
  "id": "/subscriptions/e37510d7-33b6-4676-886f-ee75bcc01871/resourceGroups/theo_temp/providers/Microsoft.Compute/virtualMachineScaleSets/vmssTemp",
  "type": "Microsoft.Compute/virtualMachineScaleSets",
  "location": "eastus2",
  "tags": {
    "platformsettings.host_environment.service.platform_optedin_for_rootcerts": "true"
  },
  "sku": {
    "name": "Standard_B1s",
    "tier": "Standard",
    "capacity": 2
  },
  "properties": {
    "singlePlacementGroup": true,
    "upgradePolicy": {
      "mode": "Manual"
    },
    "scaleInPolicy": {
      "rules": [
        "Default"
      ]
    },
    "virtualMachineProfile": {
      "osProfile": {
        "computerNamePrefix": "vmsstempg",
        "adminUsername": "grizzlytheodore",
        "windowsConfiguration": {
          "provisionVMAgent": true,
          "enableAutomaticUpdates": true
        },
        "secrets": [],
        "allowExtensionOperations": true,
        "requireGuestProvisionSignal": true
      },
      "storageProfile": {
        "osDisk": {
          "osType": "Windows",
          "createOption": "FromImage",
          "caching": "ReadWrite",
          "writeAcceleratorEnabled": false,
          "managedDisk": {
            "storageAccountType": "Premium_LRS"
          },
          "diskSizeGB": 127
        },
        "imageReference": {
          "publisher": "MicrosoftWindowsServer",
          "offer": "WindowsServer",
          "sku": "2019-Datacenter",
          "version": "latest"
        },
        "dataDisks": [
          {
            "lun": 0,
            "createOption": "Empty",
            "caching": "None",
            "managedDisk": {
              "storageAccountType": "Premium_LRS"
            },
            "diskSizeGB": 4
          }
        ]
      },
      "networkProfile": {
        "networkInterfaceConfigurations": [
          {
            "name": "theo_temp-vnet-nic01",
            "properties": {
              "primary": true,
              "enableAcceleratedNetworking": false,
              "networkSecurityGroup": {
                "id": "/subscriptions/e37510d7-33b6-4676-886f-ee75bcc01871/resourceGroups/theo_temp/providers/Microsoft.Network/networkSecurityGroups/basicNsgtheo_temp-vnet-nic01"
              },
              "dnsSettings": {
                "dnsServers": []
              },
              "enableIPForwarding": false,
              "ipConfigurations": [
                {
                  "name": "theo_temp-vnet-nic01-defaultIpConfiguration",
                  "properties": {
                    "primary": true,
                    "subnet": {
                      "id": "/subscriptions/e37510d7-33b6-4676-886f-ee75bcc01871/resourceGroups/theo_temp/providers/Microsoft.Network/virtualNetworks/theo_temp-vnet/subnets/default"
                    },
                    "privateIPAddressVersion": "IPv4"
                  }
                }
              ]
            }
          }
        ]
      },
      "diagnosticsProfile": {
        "bootDiagnostics": {
          "enabled": true
        }
      },
      "extensionProfile": {
        "extensions": [
          {
            "name": "Microsoft.Azure.Security.AntimalwareSignature.AntimalwareConfiguration",
            "properties": {
              "autoUpgradeMinorVersion": true,
              "provisionAfterExtensions": [],
              "enableAutomaticUpgrade": true,
              "publisher": "Microsoft.Azure.Security.AntimalwareSignature",
              "type": "AntimalwareConfiguration",
              "typeHandlerVersion": "2.0",
              "settings": {}
            }
          },
          {
            "name": "Microsoft.Azure.Geneva.GenevaMonitoring",
            "properties": {
              "autoUpgradeMinorVersion": true,
              "provisionAfterExtensions": [],
              "enableAutomaticUpgrade": true,
              "publisher": "Microsoft.Azure.Geneva",
              "type": "GenevaMonitoring",
              "typeHandlerVersion": "2.0",
              "settings": {}
            }
          }
        ]
      },
      "priority": "Regular"
    },
    "provisioningState": "Updating",
    "overprovision": true,
    "doNotRunExtensionsOnOverprovisionedVMs": false,
    "uniqueId": "4c5654b2-d769-4495-9393-a0bfe2c5bbac",
    "platformFaultDomainCount": 5
  }
}


DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/e37510d7-33b6-4676-886f-ee75bcc01871/providers/Microsoft.Compute/locations/eastus2/operations/7ce2e627-a126-4a6f-a62d-3039afdad7c7?api-version=2020-06-01

Headers:
x-ms-client-request-id        : 88af996a-4104-48db-9f10-235ab63df7dc

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-ratelimit-remaining-resource: Microsoft.Compute/GetOperation3Min;14996,Microsoft.Compute/GetOperation30Min;29982
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 8eedbda7-61ee-4aea-991f-2c0acb53ba60
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 11999
x-ms-correlation-request-id   : 80f1aabc-c04e-4ada-b9b2-873c84d37453
x-ms-routing-request-id       : CENTRALUS:20210311T145159Z:80f1aabc-c04e-4ada-b9b2-873c84d37453
X-Content-Type-Options        : nosniff
Date                          : Thu, 11 Mar 2021 14:51:58 GMT

Body:
{
  "startTime": "2021-03-11T09:51:48.0809664-05:00",
  "endTime": "2021-03-11T09:51:48.4402929-05:00",
  "status": "Succeeded",
  "name": "7ce2e627-a126-4a6f-a62d-3039afdad7c7"
}


DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/e37510d7-33b6-4676-886f-ee75bcc01871/resourceGroups/theo_temp/providers/Microsoft.Compute/virtualMachineScaleSets/vmssTemp?api-version=2020-06-01

Headers:
x-ms-client-request-id        : 88af996a-4104-48db-9f10-235ab63df7dc

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-ratelimit-remaining-resource: Microsoft.Compute/GetVMScaleSet3Min;361,Microsoft.Compute/GetVMScaleSet30Min;2551
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 879a5b6e-a765-4961-8250-b71234c31371
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 11998
x-ms-correlation-request-id   : 94635e81-4282-43c0-a195-61dc319385a1
x-ms-routing-request-id       : CENTRALUS:20210311T145159Z:94635e81-4282-43c0-a195-61dc319385a1
X-Content-Type-Options        : nosniff
Date                          : Thu, 11 Mar 2021 14:51:58 GMT

Body:
{
  "name": "vmssTemp",
  "id": "/subscriptions/e37510d7-33b6-4676-886f-ee75bcc01871/resourceGroups/theo_temp/providers/Microsoft.Compute/virtualMachineScaleSets/vmssTemp",
  "type": "Microsoft.Compute/virtualMachineScaleSets",
  "location": "eastus2",
  "tags": {
    "platformsettings.host_environment.service.platform_optedin_for_rootcerts": "true"
  },
  "sku": {
    "name": "Standard_B1s",
    "tier": "Standard",
    "capacity": 2
  },
  "properties": {
    "singlePlacementGroup": true,
    "upgradePolicy": {
      "mode": "Manual"
    },
    "scaleInPolicy": {
      "rules": [
        "Default"
      ]
    },
    "virtualMachineProfile": {
      "osProfile": {
        "computerNamePrefix": "vmsstempg",
        "adminUsername": "grizzlytheodore",
        "windowsConfiguration": {
          "provisionVMAgent": true,
          "enableAutomaticUpdates": true
        },
        "secrets": [],
        "allowExtensionOperations": true,
        "requireGuestProvisionSignal": true
      },
      "storageProfile": {
        "osDisk": {
          "osType": "Windows",
          "createOption": "FromImage",
          "caching": "ReadWrite",
          "writeAcceleratorEnabled": false,
          "managedDisk": {
            "storageAccountType": "Premium_LRS"
          },
          "diskSizeGB": 127
        },
        "imageReference": {
          "publisher": "MicrosoftWindowsServer",
          "offer": "WindowsServer",
          "sku": "2019-Datacenter",
          "version": "latest"
        },
        "dataDisks": [
          {
            "lun": 0,
            "createOption": "Empty",
            "caching": "None",
            "managedDisk": {
              "storageAccountType": "Premium_LRS"
            },
            "diskSizeGB": 4
          }
        ]
      },
      "networkProfile": {
        "networkInterfaceConfigurations": [
          {
            "name": "theo_temp-vnet-nic01",
            "properties": {
              "primary": true,
              "enableAcceleratedNetworking": false,
              "networkSecurityGroup": {
                "id": "/subscriptions/e37510d7-33b6-4676-886f-ee75bcc01871/resourceGroups/theo_temp/providers/Microsoft.Network/networkSecurityGroups/basicNsgtheo_temp-vnet-nic01"
              },
              "dnsSettings": {
                "dnsServers": []
              },
              "enableIPForwarding": false,
              "ipConfigurations": [
                {
                  "name": "theo_temp-vnet-nic01-defaultIpConfiguration",
                  "properties": {
                    "primary": true,
                    "subnet": {
                      "id": "/subscriptions/e37510d7-33b6-4676-886f-ee75bcc01871/resourceGroups/theo_temp/providers/Microsoft.Network/virtualNetworks/theo_temp-vnet/subnets/default"
                    },
                    "privateIPAddressVersion": "IPv4"
                  }
                }
              ]
            }
          }
        ]
      },
      "diagnosticsProfile": {
        "bootDiagnostics": {
          "enabled": true
        }
      },
      "extensionProfile": {
        "extensions": [
          {
            "name": "Microsoft.Azure.Security.AntimalwareSignature.AntimalwareConfiguration",
            "properties": {
              "autoUpgradeMinorVersion": true,
              "provisionAfterExtensions": [],
              "enableAutomaticUpgrade": true,
              "publisher": "Microsoft.Azure.Security.AntimalwareSignature",
              "type": "AntimalwareConfiguration",
              "typeHandlerVersion": "2.0",
              "settings": {}
            }
          },
          {
            "name": "Microsoft.Azure.Geneva.GenevaMonitoring",
            "properties": {
              "autoUpgradeMinorVersion": true,
              "provisionAfterExtensions": [],
              "enableAutomaticUpgrade": true,
              "publisher": "Microsoft.Azure.Geneva",
              "type": "GenevaMonitoring",
              "typeHandlerVersion": "2.0",
              "settings": {}
            }
          }
        ]
      },
      "priority": "Regular"
    },
    "provisioningState": "Succeeded",
    "overprovision": true,
    "doNotRunExtensionsOnOverprovisionedVMs": false,
    "uniqueId": "4c5654b2-d769-4495-9393-a0bfe2c5bbac",
    "platformFaultDomainCount": 5
  }
}

**Comment by grizzlytheodore** [comment] 2021-03-11 16:58
@jaylabell  @avirishuv  could you help me redirect this to the VMSS team?

**Comment by grizzlytheodore** [comment] 2021-03-15 22:06
hello, fix to this bug has been created here: https://github.com/Azure/azure-powershell/pull/14553
You can expect this change to take place in [S185][https://github.com/Azure/azure-powershell/milestone/120](url)   Release to CloudShell: 04/09; Release to Customers: 04/13

**Closed** 2021-03-17 02:41 UTC
Labels: Compute - VMSS, Service Attention, bug, customer-reported
