### ISSUE TITLE
AzureRM.Profile Get-AzureRmTenant returns incorrect directory name

### ISSUE THREAD

**Issue by iamGavinJ** [Azure/azure-powershell#4325] opened 2017-07-18 12:24 UTC
### Cmdlet(s)
Get-AzureRmTenant

### PowerShell Version
5.1.15063.483

### Module Version
3.2.0

### OS Version
10.0.15063.483

### Description
When my user is a member of multiple directories/tenants, and Get-AzureRMTenant is called without any arguments, the list of available tenants returns with correct GUIDs but the directory name returns the first in the list for all subsequent GUIDs.

### Debug Output
Prints out too much security sensitive info.

### Script/Steps for Reproduction
call Get-AzureRmTenant with no arguments when logged in as a user which has multiple directory associations.

**Comment by cormacpayne** [comment] 2017-07-24 17:32
@iamGavinJ Hey Gavin, unfortunately this is by design. Currently, the tenant API call does not return the domain name, only the Id. If, in the future, the domain is included in the call, we will resurface this issue. Closing for now.

**Closed by cormacpayne** 2017-07-24 17:32 UTC
