### ISSUE TITLE
Error using Set-AzureRmPolicyAssignment to set -Sku

### ISSUE THREAD

**Issue by russellds** [Azure/azure-powershell#6055] opened 2018-04-26 16:07 UTC
### Description

When attempting to set the -Sku for an existing Azure Policy assignment using Set-AzureRmPolicyAssignment I am getting the following error:

```powershell
Set-AzureRmPolicyAssignment : MissingPolicyParameter : The policy assignment 'RestrictLocationPolicyAssignment' is
missing the parameter(s) 'listOfAllowedLocations' as defined in the policy definition
'e56962a6-4747-49cd-b67b-bf8b01975c4c'.
At line:1 char:1
+ Set-AzureRmPolicyAssignment -ResourceId $policyAssignment.ResourceId  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmPolicyAssignment], ErrorResponseMessageException
    + FullyQualifiedErrorId : MissingPolicyParameter,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.S
   etAzurePolicyAssignmentCmdlet
```

**Note:** If the Policy doesn't have parameters, setting the -Sku works successfully.
### Script/Steps for Reproduction

```powershell
$ResourceGroup = Get-AzureRmResourceGroup -Name "ResourceGroup11"
$Policy = Get-AzureRmPolicyDefinition | Where-Object {$_.Properties.DisplayName -eq 'Allowed locations' -and $_.Properties.PolicyType -eq 'BuiltIn'}
$Locations = Get-AzureRmLocation | where displayname -like "*east*"
$AllowedLocations = @{"listOfAllowedLocations"=($Locations.location)}
New-AzureRmPolicyAssignment -Name "RestrictLocationPolicyAssignment" -PolicyDefinition $Policy -Scope $ResourceGroup.ResourceId -PolicyParameterObject $AllowedLocations
$policyAssignment = Get-AzureRmPolicyAssignment -Name "RestrictLocationPolicyAssignment" -Scope $ResourceGroup
Set-AzureRmPolicyAssignment -ResourceId $policyAssignment.ResourceId -Sku @{name='A1'; tier='Standard'}
```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable

    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     5.7.0      AzureRM
```

### Environment Data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14409.1012
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1012
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Debug Output

```
DEBUG: 11:34:49 AM - SetAzurePolicyAssignmentCmdlet begin processing with ParameterSet 'SetByPolicyAssignmentId'.
DEBUG: 11:34:49 AM - using account id '*******@***********.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: '*******@***********.com', environment: 'AzureCloud',
tenant: '********-****-****-****-************'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 04/26/2018 15:34:49:  - TokenCache: Serializing token cache with 1 items.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 04/26/2018 15:34:49:  - TokenCache: Serializing token cache with 1 items.
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain:
'********-****-****-****-************', Endpoint: 'https://login.microsoftonline.com/', ClientId:
'********-****-****-****-************', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri:
'https://management.core.windows.net/', ValidateAuthrity: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority
'https://login.microsoftonline.com/********-****-****-****-************/', CorrelationId:
'00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain:
'********-****-****-****-************', AdEndpoint: 'https://login.microsoftonline.com/', ClientId:
'********-****-****-****-************', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 04/26/2018 15:34:49: 4433b13a-ca9b-46eb-864e-212d783890c6 - AcquireTokenHandlerBase: === Token Acquisition
started:
 Authority: https://login.microsoftonline.com/********-****-****-****-************/
 Resource: https://management.core.windows.net/
 ClientId: ********-****-****-****-************
 CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (1 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 04/26/2018 15:34:49: 4433b13a-ca9b-46eb-864e-212d783890c6 - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 04/26/2018 15:34:49: 4433b13a-ca9b-46eb-864e-212d783890c6 - TokenCache: An item matching the requested resource
was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 04/26/2018 15:34:49: 4433b13a-ca9b-46eb-864e-212d783890c6 - TokenCache: 45.29347229 minutes left until token in
cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 04/26/2018 15:34:49: 4433b13a-ca9b-46eb-864e-212d783890c6 - TokenCache: A matching item (access token or refresh
 token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 04/26/2018 15:34:49: 4433b13a-ca9b-46eb-864e-212d783890c6 - AcquireTokenHandlerBase: === Token Acquisition
finished successfully. An access token was retuned:
 Access Token Hash: ***************************==
 Refresh Token Hash: ***************************=
 Expiration Time: 04/26/2018 16:20:06 +00:00
 User Hash: ***************************=

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 04/26/2018 15:34:49:  - TokenCache: Serializing token cache with 1 items.
DEBUG: [Common.Authentication]: Received token with LoginType 'LiveId', Tenant: '********-****-****-****-************',
 UserId: '*******@***********.com'
DEBUG: [Common.Authentication]: Authenticating using Account: '*******@***********.com', environment: 'AzureCloud',
tenant: '********-****-****-****-************'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 04/26/2018 15:34:49:  - TokenCache: Serializing token cache with 1 items.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 04/26/2018 15:34:49:  - TokenCache: Serializing token cache with 1 items.
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain:
'********-****-****-****-************', Endpoint: 'https://login.microsoftonline.com/', ClientId:
'********-****-****-****-************', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri:
'https://management.core.windows.net/', ValidateAuthrity: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority
'https://login.microsoftonline.com/********-****-****-****-************/', CorrelationId:
'00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain:
'********-****-****-****-************', AdEndpoint: 'https://login.microsoftonline.com/', ClientId:
'********-****-****-****-************', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 04/26/2018 15:34:49: ba92e08c-74fc-4d4f-9e34-84a033b17b63 - AcquireTokenHandlerBase: === Token Acquisition
started:
 Authority: https://login.microsoftonline.com/********-****-****-****-************/
 Resource: https://management.core.windows.net/
 ClientId: ********-****-****-****-************
 CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (1 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 04/26/2018 15:34:49: ba92e08c-74fc-4d4f-9e34-84a033b17b63 - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 04/26/2018 15:34:49: ba92e08c-74fc-4d4f-9e34-84a033b17b63 - TokenCache: An item matching the requested resource
was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 04/26/2018 15:34:49: ba92e08c-74fc-4d4f-9e34-84a033b17b63 - TokenCache: 45.29347229 minutes left until token in
cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 04/26/2018 15:34:49: ba92e08c-74fc-4d4f-9e34-84a033b17b63 - TokenCache: A matching item (access token or refresh
 token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 04/26/2018 15:34:49: ba92e08c-74fc-4d4f-9e34-84a033b17b63 - AcquireTokenHandlerBase: === Token Acquisition
finished successfully. An access token was retuned:
 Access Token Hash: ***************************==
 Refresh Token Hash: ***************************=
 Expiration Time: 04/26/2018 16:20:06 +00:00
 User Hash: ***************************=

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 04/26/2018 15:34:49:  - TokenCache: Serializing token cache with 1 items.
DEBUG: [Common.Authentication]: Received token with LoginType 'LiveId', Tenant: '********-****-****-****-************',
 UserId: '*******@***********.com'
DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '04/26/2018 16:20:06 +00:00',
MultipleResource? 'True', Tenant: '********-****-****-****-************', UserId: '*******@***********.com'
DEBUG: [Common.Authentication]: User info for token DisplayId: '*******@***********.com', Name: ******* ******,
IdProvider: 'https://sts.windows.net/********-****-****-****-************/', Uid:
'********-****-****-****-************'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '04/26/2018 16:20:06 +00:00' Comparing to
'04/26/2018 15:34:49 +00:00' With threshold '00:05:00', calculated time until token expiry: '00:45:17.6083374'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/********-****-****-****-************/resourceGroups/ResourceGroup11/provider
s/Microsoft.Authorization/policyAssignments/RestrictLocationPolicyAssignment?api-version=2017-06-01-preview

Headers:
User-Agent                    : PSVersion/v5.1.14409.1012,AzurePowershell/v5.7.0
ParameterSetName              : SetByPolicyAssignmentId
CommandName                   : Set-AzureRmPolicyAssignment

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Vary                          : Accept-Encoding
x-ms-request-id               : eastus:8e808339-12ed-4490-9a1e-64939f737d73
x-ms-ratelimit-remaining-subscription-reads: 14990
x-ms-correlation-request-id   : 87af8861-3ba7-40e9-8840-8c74d22b8ba0
x-ms-routing-request-id       : EASTUS:20180426T153449Z:87af8861-3ba7-40e9-8840-8c74d22b8ba0
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Thu, 26 Apr 2018 15:34:48 GMT

Body:
{
  "sku": {
    "name": "A0",
    "tier": "Free"
  },
  "properties": {
    "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/e56962a6-4747-49cd-b67b-bf8b01975c4c",
    "scope": "/subscriptions/********-****-****-****-************/resourceGroups/ResourceGroup11",
    "parameters": {
      "listOfAllowedLocations": {
        "value": [
          "eastasia",
          "southeastasia",
          "eastus",
          "eastus2",
          "japaneast",
          "australiaeast",
          "australiasoutheast",
          "canadaeast"
        ]
      }
    }
  },
  "id":
"/subscriptions/********-****-****-****-************/resourceGroups/ResourceGroup11/providers/Microsoft.Authorization/p
olicyAssignments/RestrictLocationPolicyAssignment",
  "type": "Microsoft.Authorization/policyAssignments",
  "name": "RestrictLocationPolicyAssignment"
}

DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '04/26/2018 16:20:06 +00:00',
MultipleResource? 'True', Tenant: '********-****-****-****-************', UserId: '*******@***********.com'
DEBUG: [Common.Authentication]: User info for token DisplayId: '*******@***********.com', Name: ******* ******,
IdProvider: 'https://sts.windows.net/********-****-****-****-************/', Uid:
'********-****-****-****-************'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '04/26/2018 16:20:06 +00:00' Comparing to
'04/26/2018 15:34:49 +00:00' With threshold '00:05:00', calculated time until token expiry: '00:45:17.4573349'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/********-****-****-****-************/resourceGroups/ResourceGroup11/provider
s/Microsoft.Authorization/policyAssignments/RestrictLocationPolicyAssignment?api-version=2017-06-01-preview

Headers:
User-Agent                    : PSVersion/v5.1.14409.1012,AzurePowershell/v5.7.0
ParameterSetName              : SetByPolicyAssignmentId
CommandName                   : Set-AzureRmPolicyAssignment

Body:
{
  "properties": {
    "scope": "/subscriptions/********-****-****-****-************/resourceGroups/ResourceGroup11",
    "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/e56962a6-4747-49cd-b67b-bf8b01975c4c"
  },
  "name": "RestrictLocationPolicyAssignment",
  "sku": {
    "name": "A1",
    "tier": "Standard"
  }
}

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
x-ms-request-id               : eastus:a46ee0bb-7a4c-48a4-925c-9d7dbd736a7e
x-ms-ratelimit-remaining-subscription-writes: 1197
x-ms-correlation-request-id   : a122f426-6f3e-41e4-9fe0-e9f585e5420a
x-ms-routing-request-id       : EASTUS:20180426T153449Z:a122f426-6f3e-41e4-9fe0-e9f585e5420a
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Thu, 26 Apr 2018 15:34:48 GMT

Body:
{
  "error": {
    "code": "MissingPolicyParameter",
    "message": "The policy assignment 'RestrictLocationPolicyAssignment' is missing the parameter(s)
'listOfAllowedLocations' as defined in the policy definition 'e56962a6-4747-49cd-b67b-bf8b01975c4c'."
  }
}

Set-AzureRmPolicyAssignment : MissingPolicyParameter : The policy assignment 'RestrictLocationPolicyAssignment' is
missing the parameter(s) 'listOfAllowedLocations' as defined in the policy definition
'e56962a6-4747-49cd-b67b-bf8b01975c4c'.
At line:1 char:1
+ Set-AzureRmPolicyAssignment -ResourceId $policyAssignment.ResourceId  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmPolicyAssignment], ErrorResponseMessageException
    + FullyQualifiedErrorId : MissingPolicyParameter,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.S
   etAzurePolicyAssignmentCmdlet

PS C:\> Resolve-AzureRmError
DEBUG: 12:03:30 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 12:03:30 PM - using account id '*******@***********.com'...


   HistoryId: 11


Message        : MissingPolicyParameter : The policy assignment 'RestrictLocationPolicyAssignment' is missing the
                 parameter(s) 'listOfAllowedLocations' as defined in the policy definition
                 'e56962a6-4747-49cd-b67b-bf8b01975c4c'.
StackTrace     :    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.RestClients.ResourceManagerRestClientBase.<Send
                 RequestAsync>d__9.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.RestClients.ResourceManagerRestClientBase.<Send
                 RequestAsync>d__6.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.RestClients.ResourceManagerRestClientBase.<Perf
                 ormOperationAsync>d__4.MoveNext()
Exception      : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Entities.ErrorResponses.ErrorResponseMessageException
InvocationInfo : {Set-AzureRmPolicyAssignment}
Line           : Set-AzureRmPolicyAssignment -ResourceId $policyAssignment.ResourceId -Sku @{name='A1';
                 tier='Standard'}
Position       : At line:1 char:1
                 + Set-AzureRmPolicyAssignment -ResourceId $policyAssignment.ResourceId  ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 11

DEBUG: AzureQoSEvent: CommandName - Resolve-AzureRmError; IsSuccess - True; Duration - 00:00:00.0938968; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 12:03:30 PM - ResolveError end processing.
DEBUG: 12:03:30 PM - ResolveError end processing.
```

**Comment by markcowl** [comment] 2018-04-30 22:47
@cormacpayne @darshanhs90 can you take a look?

**Comment by camillemarie** [comment] 2018-05-02 21:03
This looks like a bug in the policy cmdlets. The parameters are getting stripped out on the  Set-AzureRmPolicyAssignment and  Get-AzureRmPolicyAssignment . We've created a tracking task to investigate and fix it.

**Comment by fbodmer** [comment] 2018-05-14 10:37
Having a similar issue. Attempting to assign a single region results in an error. Easy to reproduce, just use example in documentation and set filter to result in single hit, e.g. "*southeast asia*" instead of "*southeast asia*".

**Comment by mentat9** [comment] 2018-06-26 17:37
This is fixed as part of the next Powershell release: https://github.com/Azure/azure-powershell/milestone/49

**Comment by mentat9** [comment] 2018-07-11 17:31
@russellds could you please validate that the problem is fixed in the current release, and close (or update) this issue?

**Comment by mentat9** [comment] 2018-09-18 18:00
Closing, fix has been shipping for a while.

**Closed by mentat9** 2018-09-18 18:00 UTC
Labels: Policy, Resource Authorization
