### ISSUE TITLE
Wrong Path for 'New-AzureServicePorject' cmdlet

### ISSUE THREAD

**Issue by seanlarge** [Azure/azure-powershell#2199] opened 2016-05-03 01:25 UTC
Hi,

Following this tutorial: https://azure.microsoft.com/en-us/documentation/articles/cloud-services-nodejs-develop-deploy-express-app/

When running the 'New-AzureServiceProject' it looks for the scaffold.xml in path 

```
C:\Program Files (x86)\Microsoft
SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\AzureRM.Profile\Resources\Scaffolding\General\scaffold.xml'.

```

however it is not there. Looking at the comments from this post: https://azure.microsoft.com/en-us/documentation/articles/cloud-services-nodejs-develop-deploy-app/

I find that the correct path is: 
`C:\Program Files (x86)\microsoft sdks\azure\PowerShell\ServiceManagement\Azure\Services\Resources\Scaffold\General\scaffold.xml`

**Comment by seanlarge** [comment] 2016-05-03 01:29
the version is 1.3.2
Microsoft Azure Powershell -- April 2016

**Comment by markcowl** [comment] 2016-05-03 01:53
@seanlarge Thanks.  This is actually *not* the correct path, the path should be in the Azure service management cmdlets. WIll take a look.

**Comment by karlti** [comment] 2016-08-04 09:13
same here...
Only when copying over the `**Resources`**  folder from 

> `\ServiceManagement\Azure\Services

`to 

> \ResourceManager\AzureResourceManager\AzureRM.Profile

`" i get that to work

**Comment by cormacpayne** [comment] 2016-09-29 23:36
@markcowl This incorrect scaffolding path gets created [here](https://github.com/Azure/azure-powershell/blob/dev/src/ServiceManagement/Services/Commands.Utilities/Common/CloudServiceProject.cs#L143):

```cs
Scaffold.GenerateScaffolding(Path.Combine(scaffoldingFolderPath, Resources.GeneralScaffolding), serviceRootPath, parameters);
```

where `Resources.GeneralScaffolding` is `Resources\Scaffold\General\scaffold.xml`

So the problem is the value of `scaffoldingFolderPath`, which gets set [here](https://github.com/Azure/azure-powershell/blob/dev/src/ServiceManagement/Services/Commands.Utilities/Common/CloudServiceProject.cs#L116):

```cs
scaffoldingFolderPath = FileUtilities.GetAssemblyDirectory();
```

which looks to be getting the directory name of the executing assembly (based on the implementation of this function [here](https://github.com/Azure/azure-powershell/blob/b8d3a16d9e667ecbb82e89d1e79c826d42b8b941/src/Common/Commands.Common.Authentication/Utilities/FileUtilities.cs#L37))

When run in debug mode and importing the module `src\Package\Debug\ServiceManagement\Azure\Services\Microsoft.WindowsAzure.Commands.dll`, the cmdlet works as expected, since the `assemblyPath` is `src\Package\Debug\ServiceManagement\Azure\Services\Microsoft.Azure.Commands.Common.Authentication.DLL`.

Any idea why, when run outside of debug mode, the `assemblyPath` is set to the AzureRM.Profile.psd1 file?

**Comment by Justus-Maier** [comment] 2016-11-16 10:15
+1
Trips up new guys to Azure Cloud like me :/
The whole article about how to install and configure is not really straight forward either :(

**Comment by twitchax** [comment] 2017-02-03 21:48
Closing as won't fix.

**Closed by twitchax** 2017-02-03 21:48 UTC
Labels: 1 - Ready, Investigate, Pairing, Team
