### ISSUE TITLE
[ARM 1.*] 10 ARM key vault cmdlets in AzureRM.KeyVault module are not properly prefixed with AzureRm

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-powershell#1338] opened 2015-11-23 02:52 UTC
```
PS C:\> gcm -Module AzureRM.KeyVault -Noun azurekey*

CommandType Name                             Version Source
----------- ----                             ------- ------
Cmdlet      Add-AzureKeyVaultKey             1.1.0   AzureRM.KeyVault
Cmdlet      Backup-AzureKeyVaultKey          1.1.0   AzureRM.KeyVault
Cmdlet      Get-AzureKeyVaultKey             1.1.0   AzureRM.KeyVault
Cmdlet      Get-AzureKeyVaultSecret          1.1.0   AzureRM.KeyVault
Cmdlet      Remove-AzureKeyVaultKey          1.1.0   AzureRM.KeyVault
Cmdlet      Remove-AzureKeyVaultSecret       1.1.0   AzureRM.KeyVault
Cmdlet      Restore-AzureKeyVaultKey         1.1.0   AzureRM.KeyVault
Cmdlet      Set-AzureKeyVaultKeyAttribute    1.1.0   AzureRM.KeyVault
Cmdlet      Set-AzureKeyVaultSecret          1.1.0   AzureRM.KeyVault
Cmdlet      Set-AzureKeyVaultSecretAttribute 1.1.0   AzureRM.KeyVault


PS C:\> gcm -Module AzureRM.KeyVault -Noun azurermkey*

CommandType Name                               Version Source
----------- ----                               ------- ------
Cmdlet      Get-AzureRmKeyVault                1.1.0   AzureRM.KeyVault
Cmdlet      New-AzureRmKeyVault                1.1.0   AzureRM.KeyVault
Cmdlet      Remove-AzureRmKeyVault             1.1.0   AzureRM.KeyVault
Cmdlet      Remove-AzureRmKeyVaultAccessPolicy 1.1.0   AzureRM.KeyVault
Cmdlet      Set-AzureRmKeyVaultAccessPolicy    1.1.0   AzureRM.KeyVault
```

**Comment by pomortaz** [comment] 2016-03-12 00:28
This is by design. \*-AzureRmKeyVault\* CmdLets talk to ARM, but \*-AzureKeyVault\* CmdLets don't talk to ARM and instead make calls to Key Vault data-plane and therefore, don't have Rm in the name.

**Comment by alexandair** [comment] 2016-03-12 01:19
I must say that's very confusing design decision. As a user I shouldn't care about management- or data-planes. If cmdlets belong to AzureRM module I expect them to be properly prefixed with AzureRM prefix. If they are different than they should belong to Azure.KeyVault module. 

/cc @markcowl

**Comment by cormacpayne** [comment] 2017-09-02 03:03
Closing as this has been the pattern for KeyVault cmdlets for over a year now.

**Closed by cormacpayne** 2017-09-02 03:03 UTC
Labels: KeyVault
