### ISSUE TITLE
Uniform naming for Az.Storage cmdlets regarding container 

### ISSUE THREAD

**Issue by ToMakeSense** [Azure/azure-powershell#9306] opened 2019-05-27 11:39 UTC
## Description of the new feature
I found there are 10 commands contain **AzRm** in their noun part in all Az module, which is caused by merging from previous Azure.Storage and AzureRM.Storage. they are sets of cmdlets regarding storage account container(they are coming from `AzureRM.Storage` module).

```powershell
PS C:\WINDOWS\system32> get-command *-azrm*

CommandType     Name                                               Version    Source                                                                          
-----------     ----                                               -------    ------                                                                          
Cmdlet          Add-AzRmStorageContainerLegalHold                  1.3.0      Az.Storage                                                                      
Cmdlet          Get-AzRmStorageContainer                           1.3.0      Az.Storage                                                                      
Cmdlet          Get-AzRmStorageContainerImmutabilityPolicy         1.3.0      Az.Storage                                                                      
Cmdlet          Lock-AzRmStorageContainerImmutabilityPolicy        1.3.0      Az.Storage                                                                      
Cmdlet          New-AzRmStorageContainer                           1.3.0      Az.Storage                                                                      
Cmdlet          Remove-AzRmStorageContainer                        1.3.0      Az.Storage                                                                      
Cmdlet          Remove-AzRmStorageContainerImmutabilityPolicy      1.3.0      Az.Storage                                                                      
Cmdlet          Remove-AzRmStorageContainerLegalHold               1.3.0      Az.Storage                                                                      
Cmdlet          Set-AzRmStorageContainerImmutabilityPolicy         1.3.0      Az.Storage                                                                      
Cmdlet          Update-AzRmStorageContainer                        1.3.0      Az.Storage  
```
There are also another set of cmdlets regarding storage account container with **Az** only in their noun part(they are coming from `Azure.Storage` module).

```powershell
PS C:\WINDOWS\system32> get-command *-azstorageContainer* -CommandType Cmdlet

CommandType     Name                                               Version    Source                                                                          
-----------     ----                                               -------    ------                                                                          
Cmdlet          Get-AzStorageContainer                             1.3.0      Az.Storage                                                                      
Cmdlet          Get-AzStorageContainerStoredAccessPolicy           1.3.0      Az.Storage                                                                      
Cmdlet          New-AzStorageContainer                             1.3.0      Az.Storage                                                                      
Cmdlet          New-AzStorageContainerSASToken                     1.3.0      Az.Storage                                                                      
Cmdlet          New-AzStorageContainerStoredAccessPolicy           1.3.0      Az.Storage                                                                      
Cmdlet          Remove-AzStorageContainer                          1.3.0      Az.Storage                                                                      
Cmdlet          Remove-AzStorageContainerStoredAccessPolicy        1.3.0      Az.Storage                                                                      
Cmdlet          Set-AzStorageContainerAcl                          1.3.0      Az.Storage                                                                      
Cmdlet          Set-AzStorageContainerStoredAccessPolicy           1.3.0      Az.Storage    
```
After comparing, I found below three pairs cmdlets have the same functionality.
```
Get-AzStorageContainer
Get-AzRmStorageContainer

New-AzStorageContainer
New-AzRmStorageContainer

Remove-AzStorageContainer
Remove-AzRmStorageContainer
```
## Proposed implementation details (optional)
So I suggest getting the 10 "AzRm" cmdlets'  naming convention uniformed, just like other Az cmdlets. We could get the three pairs cmdlets that have the same functionality merged, as to other 7 "AzRm" cmdlets, removing "Rm" in their noun part will not cause conflict with existing cmdlets.

**Comment by ToMakeSense** [comment] 2019-05-27 11:51
Getting 3 pairs cmdlets having the same functionality merged (Example: Get-AzRmStorageContainer and Get-AzStorageContainer)

**Cmdlets at present**
```powershell
Get-AzRmStorageContainer
   [-ResourceGroupName] <String>
   [-StorageAccountName] <String>
   [-Name <String>]
   [-DefaultProfile <IAzureContextContainer>]
   [<CommonParameters>]

Get-AzRmStorageContainer
   -StorageAccount <PSStorageAccount>
   [-Name <String>]
   [-DefaultProfile <IAzureContextContainer>]
   [<CommonParameters>]
```
```powershell
Get-AzStorageContainer
   [[-Name] <String>]
   [-MaxCount <Int32>]
   [-ContinuationToken <BlobContinuationToken>]
   [-Context <IStorageContext>]
   [-ServerTimeoutPerRequest <Int32>]
   [-ClientTimeoutPerRequest <Int32>]
   [-DefaultProfile <IAzureContextContainer>]
   [-ConcurrentTaskCount <Int32>]
   [<CommonParameters>]
```

**Proposed cmdlets**
```powershell
Get-AzStorageContainer
   [-ResourceGroupName] <String>
   [-StorageAccountName] <String>
   [-Name <String>]
   [-DefaultProfile <IAzureContextContainer>]
   [<CommonParameters>]

Get-AzStorageContainer
   -StorageAccount <PSStorageAccount>
   [-Name <String>]
   [-DefaultProfile <IAzureContextContainer>]
   [<CommonParameters>]

Get-AzStorageContainer
   [[-Name] <String>]
   [-MaxCount <Int32>]
   [-ContinuationToken <BlobContinuationToken>]
   [-Context <IStorageContext>]
   [-ServerTimeoutPerRequest <Int32>]
   [-ClientTimeoutPerRequest <Int32>]
   [-DefaultProfile <IAzureContextContainer>]
   [-ConcurrentTaskCount <Int32>]
   [<CommonParameters>]
```

**Comment by blueww** [comment] 2019-05-28 01:34
@ToMakeSense 
Get-AzRmStorageContainer and Get-AzStorageContainer are not same:

- They have similar function: both can get blob containers in a storage account
- They have different credential: Get-AzRmStorageContainer use login Azure Account (in resource module), Get-AzStorageContainer use Storage account name + key/sas/oauth
- the output object type is different. Get-AzRmStorageContainer can list more information, like the detail of ImmutabilityPolicy and LegalHold. 
- Get-AzRmStorageContainer can pipeline to other cmdlets with "AzRm", to set ImmutabilityPolicy and LegalHold...

For other AzRm cmdlets, they all use the login Azure Account (in resource module), and is aligned with Get-AzRmStorageContainer. So they all use the name aligned with "AzRm".

So this is by design.

**Comment by niander** [comment] 2019-05-28 21:50
Closing this as by design

**Closed by niander** 2019-05-28 21:50 UTC
Labels: Azure PS Team, Feature Request

**Comment by ToMakeSense** [comment] 2019-05-29 16:46
@blueww  thanks for your clarification. it should be better to simply note this somewhere in the docs, may be the [release note](https://docs.microsoft.com/zh-cn/powershell/azure/release-notes-azureps?view=azps-2.1.0) or [Breaking changes for Az 1.0.0](https://docs.microsoft.com/en-us/powershell/azure/migrate-az-1.0.0?view=azps-2.1.0).

**Comment by blueww** [comment] 2019-05-30 02:19
@ToMakeSense 
Thanks for the suggestion!
Actually, this is not breaking change of Az.1.0.0. The cmdlets are added before Az1.0.0 ( added in https://github.com/Azure/azure-powershell/releases/tag/v6.9.0-September2018). Anyway, the cmdlets name has some change (Azure/AzureRm->Az/AzRm), but this is a common change and mentioned in the doc. 
Besides that , from the cmdlets name "AzRm" indicate it's is resource module., and from the parameter set, user can also find the credential are different.

**Comment by ToMakeSense** [comment] 2019-05-30 15:03
@blueww thanks for so much details!
