### ISSUE TITLE
Select-AzureRmSubscription(Set-AzureRmContext) should just be able to take the SubscriptionName

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#1117] opened 2015-10-14 22:43 UTC
we cannot select a subscription just with the name now, it always asks for the SubscriptionID. Need a parameterset for these

**Comment by markcowl** [comment] 2015-10-21 01:07
The idea is that Set-AzureRmContext makes no Rest calls, so the -SubscriptionName parameter is just filling out the name property of the subscription in the current context.  If you want to get a subscription by name and set your context, use:

```
Get-AzureRmSubscription -SubscriptionName <name> | Set-AzureRmContext
```

That said, this seems to be confusing to users, and we have a work item tracking this here, where you can follow the progress:  https://www.pivotaltracker.com/story/show/105517922

**Comment by markcowl** [comment] 2015-10-21 01:23
Closing as duplicate of #1102

**Closed by markcowl** 2015-10-21 01:23 UTC
