### ISSUE TITLE
Get-AzStorageContainerStoredAccessPolicy cause reference object not set to an instance error

### ISSUE THREAD

**Issue by talalhaddad** [Azure/azure-powershell#16544] opened 2021-11-30 21:10 UTC
### Description

After setting the stored access policy from the portal with 0 permissions, getting that access policy using Get-AzStorageContainerStoredAccessPolicy will cause a reference object not set to an instance error, to reproduce:
1- set a container stored access policy with 0 permissions from the portal
![image](https://user-images.githubusercontent.com/37385101/144127962-95ac995b-20df-415a-8189-17138479b98e.png)
2- from powershell, use the  Get-AzStorageContainerStoredAccessPolicy to get the stored access policy for the container.

Even if you have multiple policies that have permissions, if one of them with 0 permission you will always get the same error

### Issue script & Debug output

```PowerShell
DEBUG: 10:58:19 PM - Init Operation Context for 'GetAzureStorageContainerStoredAccessPolicyCommand' with client request id
  Azure-Storage-PowerShell-cf25acda-ca61-4d0d-b041-55892a01cf78. If you want to get more details, please add "-Debug" to y
our command.
DEBUG: 10:58:19 PM - GetAzureStorageContainerStoredAccessPolicyCommand begin processing with ParameterSet '__AllParameterS
ets'.
DEBUG: 10:58:19 PM - Use storage account '<StorageAccountName>' from storage context.
DEBUG: Request [3e1d55f7-6d6b-4549-a0db-078a66f26ecf] GET https://<StorageAccountName>.blob.core.windows.net/tests?restype=container&c
omp=acl
x-ms-version:2020-10-02
Accept:application/xml
User-Agent:AzurePowershell/v1.0.0,azsdk-net-Storage.Blobs/12.10.0,(.NET Framework 4.8.4420.0; Microsoft Windows 10.0.22000
 )
x-ms-client-request-id:3e1d55f7-6d6b-4549-a0db-078a66f26ecf
x-ms-return-client-request-id:true
x-ms-date:Tue, 30 Nov 2021 20:58:19 GMT
Authorization:REDACTED
client assembly: Azure.Storage.Blobs
DEBUG: Response [3e1d55f7-6d6b-4549-a0db-078a66f26ecf] 200 OK (00.9s)
Transfer-Encoding:chunked
Vary:Origin
x-ms-request-id:e22c5bc4-301e-0054-692d-e63e8a000000
x-ms-client-request-id:3e1d55f7-6d6b-4549-a0db-078a66f26ecf
x-ms-version:2020-10-02
Date:Tue, 30 Nov 2021 20:58:19 GMT
ETag:"0x8D9B409B92C5D7E"
Server:Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
Content-Type:application/xml
Last-Modified:Tue, 30 Nov 2021 14:00:10 GMT

Get-AzStorageContainerStoredAccessPolicy : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-AzStorageContainerStoredAccessPolicy -Container "tests" -Context  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzStorageContainerStoredAccessPolicy], NullReferenceException
    + FullyQualifiedErrorId : NullReferenceException,Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorage 
   ContainerStoredAccessPolicyCommand
 
DEBUG: 10:58:20 PM - GetAzureStorageContainerStoredAccessPolicyCommand end processing, Start 0 remote calls. Finish 0 remo
te calls. Elapsed time 165473.93 ms. Client operation id: Azure-Storage-PowerShell-cf25acda-ca61-4d0d-b041-55892a01cf78.
DEBUG: AzureQoSEvent: Module: Az.Storage:3.12.0; CommandName: Get-AzStorageContainerStoredAccessPolicy; PSVersion: 5.1.220
00.282; IsSuccess: False; Duration: 00:00:00.9976913; Exception: Object reference not set to an instance of an object.;
DEBUG: Finish sending metric.
DEBUG: 10:58:21 PM - GetAzureStorageContainerStoredAccessPolicyCommand end processing.
```

### Environment data

```PowerShell
PSVersion                      5.1.22000.282                                                                             
PSEdition                      Desktop                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                   
BuildVersion                   10.0.22000.282                                                                            
CLRVersion                     4.0.30319.42000                                                                           
WSManStackVersion              3.0                                                                                       
PSRemotingProtocolVersion      2.3                                                                                       
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
Script     2.6.2      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connec...
Script     3.12.0     Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountMana...
```

### Error output

```PowerShell
DEBUG: 10:59:39 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 10:59:39 PM - using account id 'tahaddad@microsoft.com'...
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Reso
lve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information 
on breaking changes in Azure PowerShell.


   HistoryId: 9


Message        : Object reference not set to an instance of an object.
StackTrace     :    at 
                 Microsoft.WindowsAzure.Commands.Storage.Common.AccessPolicyHelper.ConstructPolicyOutputPSObject[T](T 
                 identifier)
                    at Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageContainerStoredAccessPolicyComm
                 and.<GetAzureContainerStoredAccessPolicyAsync>d__14.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.WindowsAzure.Commands.Storage.Common.LimitedConcurrencyTaskScheduler.<RunConcurrentTask>
                 d__26.MoveNext()
Exception      : System.NullReferenceException
InvocationInfo : {Get-AzStorageContainerStoredAccessPolicy}
Line           : Get-AzStorageContainerStoredAccessPolicy -Container "tests" -Context $ctx 
Position       : At line:1 char:1
                 + Get-AzStorageContainerStoredAccessPolicy -Container "tests" -Context  ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 9
```

**Comment by blueww** [comment] 2021-12-01 03:34
@talalhaddad 
Thanks for reporting this issue!
I have raised a PR to fix it: https://github.com/Azure/azure-powershell/pull/16546

**Comment by talalhaddad** [comment] 2021-12-09 09:03
@blueww thank you for the update.

I updated the modules and it is working when the storage is a normal storage, we had a similar error when the access policy has an empty start/end dates:

ModuleType Version    Name                                ExportedCommands                                               
---------- -------    ----                                ----------------                                               
Script     2.7.0      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connec...
Script     4.1.0      Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountMana...


**Error Details:**
DEBUG: 10:32:30 AM - Init Operation Context for 'GetAzureStorageContainerStoredAccessPolicyCommand' with client request id
  Azure-Storage-PowerShell-0417cc63-4bec-4fef-934e-48a9d6b32c48. If you want to get more details, please add "-Debug" to y
our command.
DEBUG: 10:32:30 AM - GetAzureStorageContainerStoredAccessPolicyCommand begin processing with ParameterSet '__AllParameterS
ets'.
DEBUG: 10:32:30 AM - Use storage account 'tahaddadadls' from storage context.
DEBUG: Request [8ee6fabf-501d-4ca1-b3cf-df86af7e9e89] GET https://tahaddadadls.blob.core.windows.net/test?restype=REDACTED
&comp=REDACTED
x-ms-version:REDACTED
Accept:REDACTED
User-Agent:REDACTED
x-ms-client-request-id:REDACTED
x-ms-return-client-request-id:REDACTED
x-ms-date:REDACTED
Authorization:REDACTED
client assembly: Azure.Storage.Blobs
DEBUG: Response [8ee6fabf-501d-4ca1-b3cf-df86af7e9e89] 200 OK (00.7s)
Transfer-Encoding:REDACTED
x-ms-request-id:REDACTED
x-ms-client-request-id:REDACTED
x-ms-version:REDACTED
Date:REDACTED
ETag:REDACTED
Server:REDACTED
Content-Type:REDACTED
Last-Modified:REDACTED

Get-AzStorageContainerStoredAccessPolicy : Value cannot be null.
Parameter name: accessPolicy
At line:1 char:1
+ Get-AzStorageContainerStoredAccessPolicy -Container "test" -Context $ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-AzStorageContainerStoredAccessPolicy], ArgumentNullException
    + FullyQualifiedErrorId : ArgumentNullException,Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageC 
   ontainerStoredAccessPolicyCommand
 
DEBUG: 10:32:31 AM - GetAzureStorageContainerStoredAccessPolicyCommand end processing, Start 0 remote calls. Finish 0 remo
te calls. Elapsed time 481765.78 ms. Client operation id: Azure-Storage-PowerShell-0417cc63-4bec-4fef-934e-48a9d6b32c48.
DEBUG: AzureQoSEvent: Module: Az.Storage:4.1.0; CommandName: Get-AzStorageContainerStoredAccessPolicy; PSVersion: 5.1.2200
0.282; IsSuccess: False; Duration: 00:00:00.7606509; Exception: Value cannot be null.
Parameter name: accessPolicy;
DEBUG: Finish sending metric.
DEBUG: 10:32:32 AM - GetAzureStorageContainerStoredAccessPolicyCommand end processing.

**Comment by blueww** [comment] 2021-12-09 10:24
@talalhaddad 
Thanks for reporting this issue!
As the 2 issues might has different root cause, would you like to open a new issue for better track?

BTW, this looks more like a .net SDK issue instead of Powershell code issue, since I can repro it with only .net SDK (Azure.Storage.Blobs.12.11.0-beta.2) ,by run ` BlobServiceClient.GetAccessPolicy()` on a container which has an Access policy with permission, startTime, ExpireTime are all null (Even has one of the 3 properties, the API won't fail.)
Following is the exception detail.

BTW, in the new issue, would you please share the scenario that user need define a container access policy has none of permission, startTime, ExpireTime. This kind of access policy seems has not use.

```
System.ArgumentNullException: Value cannot be null.
Parameter name: accessPolicy
   at Azure.Storage.Blobs.Models.BlobSignedIdentifier..ctor(String id, BlobAccessPolicy accessPolicy)
   at Azure.Storage.Blobs.Models.BlobSignedIdentifier.DeserializeBlobSignedIdentifier(XElement element)
   at Azure.Storage.Blobs.ContainerRestClient.GetAccessPolicy(Nullable`1 timeout, String leaseId, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobContainerClient.<GetAccessPolicyInternal>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.BlobContainerClient.GetAccessPolicy(BlobRequestConditions conditions, CancellationToken cancellationToken)
```

**Comment by blueww** [comment] 2022-06-01 03:02
@talalhaddad

I will close the issue as not get responds from you for a long time.
Feel free to contact us if need any further assistance on Azure Powershell.

**Closed by blueww** 2022-06-01 03:02 UTC
Labels: Storage, Service Attention, bug, question, customer-reported
