### ISSUE TITLE
Get-AzureRMResourceGroup no longer shows groups resources

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/azure-powershell#1683] opened 2016-01-20 03:57 UTC
Get-AzureRMResourceGroup used to show the resources in a resource group - it no longer seems to do that and the .Resource property of the group is empty.

**Comment by ravbhatnagar** [comment] 2016-02-11 22:40
This is by design. To get all resources in a ResourceGroup, we recommend using Get-AzureRmResource cmdlet. Note that cmdlet has an existing issue which hinders this scenario. But that will be fixed in the next release. So for now, you can use Find-AzureRmResource.

**Closed by ravbhatnagar** 2016-02-11 22:40 UTC
Labels: ResourceManager
