### ISSUE TITLE
Error setting the Azure Context when the user has access to more than 50 subscriptions

### ISSUE THREAD

**Issue by crou** [Azure/azure-powershell#3181] opened 2016-11-08 18:45 UTC
### Cmdlet(s)
Set-AzureRmContext

### PowerShell Version
5.0.10586.494   

### Module Version
3.1.0
2.1.0

### OS Version
10.0.10586.494

### Description
Set-AzureRmContext : Provided subscription xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx does not exist

### Debug Output
Body:
{
  "value": [
    {
      "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
      "subscriptionId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
      "displayName": "xxx",
      "state": "Enabled",
      "subscriptionPolicies": {
        "locationPlacementId": "Public_2014-09-01",
        "quotaId": "MSDN_2014-09-01",
        "spendingLimit": "On"
      }
    }, #### ... 49/50 subscriptions returned here ... #####
    {
      "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
      "subscriptionId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
      "displayName": "xxxx",
      "state": "Enabled",
      "subscriptionPolicies": {
        "locationPlacementId": "Public_2014-09-01",
        "quotaId": "EnterpriseAgreement_2014-09-01"
      }
    }
  ],
  "nextLink": "https://management.azure.com/subscriptions?api-version=2014-04-01-preview&%24skiptoken=xxxxxx"
}

Set-AzureRmContext : Provided subscription  does not exist

### Script/Steps for Reproduction
Using an account with access to more then 50 Subscriptions, get the list of subscrptions you have access:
$subcriptions = Get-AzureRmSubscription

Then try the set-AzureRMContext with one of the subscriptionid, using the debug param to get the output:
Set-AzureRmContext -SubscriptionId xxx -Debug

 Get the json containing the list of 50 subscriptions (output), and compare the list with your list $subscriptions.   Try the set-azureRMContext with one of the subscription present in the Subscription list but not in the Output.     And you will get the error.

There is a **nextLink** variable in the output that leads to a paging functionnality but it looks like the cmdlet doesn't handle that feature...

**Comment by cormacpayne** [comment] 2016-11-15 18:13
@markcowl is this issue related to https://github.com/Azure/azure-powershell/issues/3186 ?

**Comment by markcowl** [comment] 2016-11-22 03:21
@crou This is a duplicate of #3186 
You cna get around this by specifying the subscriptionId and TenantId when logging in in this case.

**Comment by markcowl** [comment] 2016-11-22 03:21
clsoign as duplicate

**Closed by markcowl** 2016-11-22 03:21 UTC
Labels: Team
