### ISSUE TITLE
New-AzSubscriptionAlias function fails

### ISSUE THREAD

**Issue by stefanstranger** [Azure/azure-powershell#22502] opened 2023-08-04 13:15 UTC
### Description

After the update of Az.Subscription Module the following command fails with the error: 

Failed to create subscription: [BillingScopeOrDisplayNameIsNotAllowed] :  Billing scope or Display name is not allowed in the request when subscription id provided.

This is a strange error because my command looks like this:
```PowerShell
New-AzSubscriptionAlias -AliasName $($i.AliasName) -DisplayName $($i.SubscriptionName) -BillingScope $($i.BillingScope) -Workload $($i.Workload)
```

### Issue script & Debug output

```PowerShell
Failed to create subscription: [BillingScopeOrDisplayNameIsNotAllowed] :
     | Billing scope or Display name is not allowed in the request when
     | subscription id provided
```

### Environment data

```PowerShell
Running a build agent
```

### Module versions

```PowerShell
Az.Subscription:  0.10.0
```

### Error output

```PowerShell
see above
```

**Comment by isra-fel** [comment] 2023-08-05 16:57
Thanks for reporting @stefanstranger !
Is it possible to share the debug log? It contains useful info about the http request/response.
Run the cmdlet with `-Debug`. Be sure to remove any sensitive information before posting.

cc @lijinpei2008

**Comment by hachi1030-Allen** [comment] 2023-08-07 07:49
Hi @isra-fel,

I can almost confirm this is a bug since I have found out the root cause of the issue.

I tested from my side with the -Debug and if you see the below information:

![image](https://github.com/Azure/azure-powershell/assets/32292089/f2417058-56db-4d30-9afd-cfa22839a91f)

You can see the body already has a subscription, which I found it's from the AzContext.

![image](https://github.com/Azure/azure-powershell/assets/32292089/cc68e55c-3151-4f4a-9822-38b5ad527e98)

That is a bug since we should never take that subscription because we are trying to create a new subscription.

Hope this helps. And I can confirm that the last version 0.9.0 works fine with this command.

Please help to fix the bug asap.

Thanks!

**Comment by emykamal** [comment] 2023-08-07 12:05
I am facing the same issue. any fixes or workarounds ?

**Comment by hachi1030-Allen** [comment] 2023-08-07 13:50
> I am facing the same issue. any fixes or workarounds ?

I think the easiest way is to downgrade to 0.9.0 version which is the last version.

**Comment by lijinpei2008** [comment] 2023-08-08 07:58
![image](https://github.com/Azure/azure-powershell/assets/31384087/f017bb1b-387b-4c98-9f3e-693b1b057d60)
This parameter is automatically generated when auto-gen, and all modules will have and will pass the command [(Get-AzContext). Subscription.Id] Give a default value,
![image](https://github.com/Azure/azure-powershell/assets/31384087/d8b6f6b8-41e5-42e9-b419-c17ac8a76962)
Obviously, this logic is not appropriate in the current module.
The script is being modified to circumvent this issue

**Comment by dburlinson** [comment] 2023-08-10 01:32
Same issue here. This issue has prevented a large company from being able to vend Azure subscriptions and ultimately consume the Azure platform's resources.

In the mean time they have reverted back to old version as a workaround, but please ensure this is fixed in the module ASAP and also ensure such changes of functionality are documented. I didnt see any mention of this here:

https://learn.microsoft.com/en-us/powershell/azure/release-notes-azureps?view=azps-10.2.0
https://learn.microsoft.com/en-us/powershell/azure/upcoming-breaking-changes?view=azps-10.2.0

And PowerShell code snippet is wrong here:

https://learn.microsoft.com/en-us/azure/cost-management-billing/manage/programmatically-create-subscription-enterprise-agreement?tabs=azure-powershell#create-subscriptions-under-a-specific-enrollment-account

**Comment by jleechpe** [comment] 2023-08-16 17:37
As an alternative to rolling back you can pass `-SubscriptionId $null` as a parameter which will blank out the default.

**Closed** 2023-08-28 02:16 UTC
Labels: Azure PS Team, Subscription, bug, Tracking
