### ISSUE TITLE
Random Login-AzureRmAccount : Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by avishnyakov** [Azure/azure-powershell#2576] opened 2016-07-06 23:45 UTC
Hello team, 

We recently started having pretty random error as following:
```
Login-AzureRmAccount : Object reference not set to an instance of an object.
```

So you run the script, all work well. Run again, works well. Run for the third time - here we go, "Login-AzureRmAccount : Object reference not set to an instance of an object.". Run again, having an exception as well.

Restart PS session, run script - all fine. Run script again - getting exception.

How to troubleshoot that? We have dozens scripts for Azure which now working randomly.

**Comment by avishnyakov** [comment] 2016-07-07 01:26
Got the stacktrace:

```
Login-AzureRmAccount : Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
At Azure.Common.ps1:3216 char:18
+             $ARMAccount = Login-AzureRmAccount -Credential $cred -Ser ...
+                           ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ArgumentOutOfRangeException
    + FullyQualifiedErrorId : System.ArgumentOutOfRangeException
 
   at System.Collections.ArrayList.set_Item(Int32 index, Object value)
   at Microsoft.Azure.Commands.Common.Authentication.Factories.ClientFactory.AddHandler[T](T handler) in d:\repro\azure-po
wershell\src\Common\Commands.Common.Authentication\Factories\ClientFactory.cs:line 266
   at lambda_method(Closure )
   at System.Management.Automation.CommandProcessor.Init(CmdletInfo cmdletInformation)
```

**Comment by markcowl** [comment] 2016-07-14 02:55
@avishnyakov What is the context in which this is happening?  WHich versions of the cmdlets are you using? Are there multiple threads running cmdlets in the same AppDomain?  This looks awfully similar to issues I've seen reported in scenarios with multiple scripts running per app domain.

**Comment by markcowl** [comment] 2016-07-21 18:29
@avishnyakov Also, the stack trace is a slightly different error, are these two errors related, or separate?

**Comment by avishnyakov** [comment] 2016-07-21 23:34
1.5.0 / 1.5.1

Correct, we use PSParallel to boots up things. I would point out multiple threads as the most likely cause of the issue.

https://www.powershellgallery.com/packages/PSParallel/2.2.2

The error is extremely random, it's done by now. We tried Azure PS reinstall, 1.5.0 / 1.5.1, other VMs, reboots, nothing helped. Right now we don't seem to have that issue. May be 1 of 250 runs will give it.

Having said that, what might be suggestions around running all that stuff in the parallel mode? VM provisioning is something we extremely keen to do in parallel. Running multiple scripts is not an option, all comes under CI/CD builds.

**Comment by markcowl** [comment] 2016-07-22 17:19
@avishnyakov Right now, the cmdlets are not really designed for parallel execution.  This is something that we plan to address in the Fall, both by targeting sources of parallel issues and by supporting powershell background jobs.  Meanwhile, once we find the root cause here, we'll release a fix.

**Comment by markcowl** [comment] 2016-08-01 06:39
Verified the issue and added stress test to catch it.  The bug for the fix is #2701 .  Closing the invesitgation in favor of the fix bug (currently scheduled for September release.

**Closed by markcowl** 2016-08-01 06:39 UTC
Labels: Investigate, Team

**Comment by rohansahai** [comment] 2018-03-14 19:46
Getting this error in a cloud shell session started from Azure Portal. Specifically, when running:

`New-AzureADMSInvitation` and passing required arguments.. the result is:

```
New-AzureADMSInvitation : Object reference not set to an instance of an object.
At line:1 char:1
+ New-AzureADMSInvitation
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureADMSInvitation], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.Open.MSGraphV10.PowerShell.NewAzureADMSInvitation
```

Anyone have a work around? I don't have a windows computer which is why I opted for the cloud shell, but my next step will be to cancel that subscription and try on my own windows device.

**Comment by Epoxboy** [comment] 2018-07-06 05:18
@rohansahai  mate, do you find a solution? I'm in the same situation when using azuresdk/azure-powershell-core.

cheers,

**Comment by rohansahai** [comment] 2018-07-07 18:35
@Epoxboy unfortunately not, I ended up using a windows computer power shell to do what I needed to do

**Comment by Epoxboy** [comment] 2018-07-09 02:07
@rohansahai I figured it out, you can set the proxy on Docker deamon in the config.json then container will pick it up.

**Comment by NikitaYeryomin** [comment] 2018-08-15 07:41
Guys, I'm new to powershell and Azure but seems getting same issue. When I run this command directly in cloudshell it works:
Set-AzureRmResource -ResourceId /subscriptions/.../resourceGroups/ae-devtest-network/providers/Microsoft.Compute/virtualMachines/vmname -Tag @{ Dept="IT"; Environment="Test" } -Force

But when I try to run it inside the script or inside Function App code, I get:

Set-AzureRmResource : Object reference not set to an instance of an object.
At /usr/nikita/clouddrive/test.ps1:13 char:1
+ Set-AzureRmResource -ResourceId $resourceId -Tag @{ Dept="IT"; Enviro ...
+ ~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], NullReferenceException
+ FullyQualifiedErrorId : System.NullReferenceException

Thanks for any advise in advance!
