### ISSUE TITLE
New-AzMonitorLogAnalyticsSolution: The server responded with an unrecognized response, Status: OK

### ISSUE THREAD

**Issue by Proxicon** [Azure/azure-powershell#17254] opened 2022-02-23 15:14 UTC
### Description

As per Microsoft sample code  [SentinelallInOne.ps1](https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Sentinel-All-In-One/Powershell/SentinelallInOne.ps1) 

Line 87 to 92
`if (($solutions | Where-Object Name -eq 'SecurityInsights').Enabled) {
    Write-Host "Azure Sentinel is already installed on workspace $($Workspace)"
}
else {    
    New-AzMonitorLogAnalyticsSolution -Type SecurityInsights -ResourceGroupName $ResourceGroup -Location $WorkspaceObject.Location -WorkspaceResourceId $WorkspaceObject.ResourceId
}
`
New-AzMonitorLogAnalyticsSolution completes and throws and error however it appears that the Azure resource  / analytics solution was successfully created. 

Expected result will be to NOT throw an error here since the work completed successfully.

Some error object data:
Invocation Info:

`$E_Obj.InvocationInfo

MyCommand             : New-AzMonitorLogAnalyticsSolution_CreateExpanded
BoundParameters       : {}
UnboundArguments      : {}
ScriptLineNumber      : 130
OffsetInLine          : 9
HistoryId             : 26
ScriptName            : C:\Program Files\WindowsPowerShell\Modules\Az.MonitoringSolutions\0.1.0\custom\New-AzMonitorLogAnalyticsSolution.ps1
Line                  :         Az.MonitoringSolutions.internal\New-AzMonitorLogAnalyticsSolution @PSBoundParameters

PositionMessage       : At C:\Program Files\WindowsPowerShell\Modules\Az.MonitoringSolutions\0.1.0\custom\New-AzMonitorLogAnalyticsSolution.ps1:130 char:9
                        +         Az.MonitoringSolutions.internal\New-AzMonitorLogAnalyticsSolu ...
                        +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PSScriptRoot          : C:\Program Files\WindowsPowerShell\Modules\Az.MonitoringSolutions\0.1.0\custom
PSCommandPath         : C:\Program Files\WindowsPowerShell\Modules\Az.MonitoringSolutions\0.1.0\custom\New-AzMonitorLogAnalyticsSolution.ps1
InvocationName        : Az.MonitoringSolutions.internal\New-AzMonitorLogAnalyticsSolution
PipelineLength        : 0
PipelinePosition      : 0
ExpectingInput        : False
CommandOrigin         : Internal
DisplayScriptPosition :`

Error Details:
`$E_Obj.ErrorDetails

Message                                                        RecommendedAction
-------                                                        -----------------
The server responded with an unrecognized response, Status: OK`

Expect this to not throw an error and actually complete successful ? - The resource created OK in Azure.

### Issue script & Debug output

```PowerShell
New-AzMonitorLogAnalyticsSolution -Type SecurityInsights -ResourceGroupName $ResourceGroup -Location $WorkspaceObject.Location -WorkspaceResourceId $WorkspaceObject.ResourceId -Debug
DEBUG: 17:10:26 - GetAzureRMContextCommand end processing.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: [CmdletBeginProcessing]: Starting command
DEBUG: CmdletBeginProcessing:
DEBUG: CmdletProcessRecordStart:
Confirm
Are you sure you want to perform this action?
Performing the operation "New-AzMonitorLogAnalyticsSolution_CreateExpanded" on target "Call remote 'SolutionsCreateOrUpdate' operation".
DEBUG: [CmdletProcessRecordAsyncStart]: Created new QosEvent for command 'New-AzMonitorLogAnalyticsSolution_CreateExpanded'
DEBUG: CmdletProcessRecordAsyncStart:
DEBUG: CmdletGetPipeline:
DEBUG: CmdletBeforeAPICall:
DEBUG: URLCreated:
https://management.azure.com/subscriptions/dce9a6ed-038e-4658-ac36-fff815b33df8/resourcegroups/RG-SentinelTest00/providers/Microsoft.OperationsManagement/solutions/SecurityInsights(WS-Sentine
lTest00)?api-version=2015-11-01-preview
DEBUG: RequestCreated:
https://management.azure.com/subscriptions/dce9a6ed-038e-4658-ac36-fff815b33df8/resourcegroups/RG-SentinelTest00/providers/Microsoft.OperationsManagement/solutions/SecurityInsights(WS-Sentine
lTest00)?api-version=2015-11-01-preview
DEBUG: HeaderParametersAdded:
https://management.azure.com/subscriptions/dce9a6ed-038e-4658-ac36-fff815b33df8/resourcegroups/RG-SentinelTest00/providers/Microsoft.OperationsManagement/solutions/SecurityInsights(WS-Sentine
lTest00)?api-version=2015-11-01-preview
DEBUG: BodyContentSet:
https://management.azure.com/subscriptions/dce9a6ed-038e-4658-ac36-fff815b33df8/resourcegroups/RG-SentinelTest00/providers/Microsoft.OperationsManagement/solutions/SecurityInsights(WS-Sentine
lTest00)?api-version=2015-11-01-preview
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/dce9a6ed-038e-4658-ac36-fff815b33df8/resourcegroups/RG-SentinelTest00/providers/Microsoft.OperationsManagement/solutions/SecurityInsights(WS-Sentine
lTest00)?api-version=2015-11-01-preview

Headers:

Body:
{
  "plan": {
    "name": "SecurityInsights(WS-SentinelTest00)",
    "product": "OMSGallery/SecurityInsights",
    "promotionCode": "",
    "publisher": "Microsoft"
  },
  "properties": {
    "workspaceResourceId": "/subscriptions/dce9a6ed-038e-4658-ac36-fff815b33df8/resourceGroups/RG-SentinelTest00/providers/Microsoft.OperationalInsights/workspaces/WS-SentinelTest00"
  },
  "location": "UK South"
}

DEBUG: BeforeCall:
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Request-Context               : appId=cid-v1:e6336c63-aab2-45f0-996a-e5dbab2a1508
X-Content-Type-Options        : nosniff
api-supported-versions        : 2015-11-01-preview
Access-Control-Allow-Origin   : *
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-request-id               : 65c8581a-5690-4d5a-9818-db0902f720be
x-ms-correlation-request-id   : 65c8581a-5690-4d5a-9818-db0902f720be
x-ms-routing-request-id       : SOUTHAFRICAWEST:20220223T151038Z:65c8581a-5690-4d5a-9818-db0902f720be
Cache-Control                 : no-cache
Date                          : Wed, 23 Feb 2022 15:10:38 GMT
Server                        : Microsoft-IIS/10.0
X-Powered-By                  : ASP.NET

Body:
{
  "plan": {
    "name": "SecurityInsights(ws-sentineltest00)",
    "publisher": "Microsoft",
    "promotionCode": "",
    "product": "OMSGallery/SecurityInsights"
  },
  "properties": {
    "workspaceResourceId": "/subscriptions/dce9a6ed-038e-4658-ac36-fff815b33df8/resourceGroups/RG-SentinelTest00/providers/Microsoft.OperationalInsights/workspaces/WS-SentinelTest00",
    "provisioningState": "Succeeded",
    "creationTime": "Wed, 23 Feb 2022 14:49:01 GMT",
    "sku": {
      "name": "PerGB"
    },
    "lastModifiedTime": "Wed, 23 Feb 2022 15:10:38 GMT",
    "containedResources": [],
    "workbookTemplates": []
  },
  "location": "UK South",
  "tags": {},
  "id": "/subscriptions/dce9a6ed-038e-4658-ac36-fff815b33df8/resourceGroups/RG-SentinelTest00/providers/Microsoft.OperationsManagement/solutions/SecurityInsights(WS-SentinelTest00)",
  "name": "SecurityInsights(WS-SentinelTest00)",
  "type": "Microsoft.OperationsManagement/solutions"
}

DEBUG: ResponseCreated:
DEBUG: BeforeResponseDispatch:

Confirm
The server responded with an unrecognized response, Status: OK
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
Az.MonitoringSolutions.internal\New-AzMonitorLogAnalyticsSolution : The server responded with an unrecognized response, Status: OK
At C:\Program Files\WindowsPowerShell\Modules\Az.MonitoringSolutions\0.1.0\custom\New-AzMonitorLogAnalyticsSolution.ps1:130 char:9
+         Az.MonitoringSolutions.internal\New-AzMonitorLogAnalyticsSolu ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ SubscriptionI...view.Solution }:<>f__AnonymousType4`4) [New-AzMonitorLo..._CreateExpanded], RestException`1
    + FullyQualifiedErrorId : OK,Microsoft.Azure.PowerShell.Cmdlets.MonitoringSolutions.Cmdlets.NewAzMonitorLogAnalyticsSolution_CreateExpanded
DEBUG: Finally:
DEBUG: CmdletAfterAPICall:
DEBUG: [CmdletProcessRecordAsyncEnd]: Finish HTTP process
DEBUG: CmdletProcessRecordAsyncEnd:
DEBUG: CmdletProcessRecordEnd:
DEBUG: AzureQoSEvent: Module: Az.MonitoringSolutions:0.1.0; CommandName: New-AzMonitorLogAnalyticsSolution_CreateExpanded; PSVersion: 5.1.19041.1320; IsSuccess: True; Duration: 00:00:00
DEBUG: Finish sending metric.
DEBUG: CmdletEndProcessing:
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
Get-Module Az*

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.7.2      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount...}
Script     0.1.0      Az.MonitoringSolutions              {Get-AzMonitorLogAnalyticsSolution, New-AzMonitorLogAnalyticsSolution, Remove-AzMonitorLogAnalyticsSolution, Update-AzMonitorLogAn...
Script     3.0.1      Az.OperationalInsights              {Disable-AzOperationalInsightsIISLogCollection, Disable-AzOperationalInsightsLinuxCustomLogCollection, Disable-AzOperationalInsigh...
Script     5.3.1      Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment...}
```

### Error output

```PowerShell
HistoryId: 26


Message        : The server responded with an unrecognized response, Status: OK
StackTrace     :
Exception      : Microsoft.Azure.PowerShell.Cmdlets.MonitoringSolutions.Runtime.RestException`1[Microsoft.Azure.PowerShell.Cmdlets.MonitoringSolutions.Models.Api20151101Preview.ICodeMessageEr
                 ror]
InvocationInfo : {New-AzMonitorLogAnalyticsSolution_CreateExpanded}
Line           :         Az.MonitoringSolutions.internal\New-AzMonitorLogAnalyticsSolution @PSBoundParameters

Position       : At C:\Program Files\WindowsPowerShell\Modules\Az.MonitoringSolutions\0.1.0\custom\New-AzMonitorLogAnalyticsSolution.ps1:130 char:9
                 +         Az.MonitoringSolutions.internal\New-AzMonitorLogAnalyticsSolu ...
                 +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 26
```

**Comment by dingmeng-xue** [comment] 2022-02-24 01:43
We will look into it.

**Comment by RakeshMohanMSFT** [comment] 2022-10-26 06:36
Duplicate of https://github.com/Azure/azure-powershell/issues/19896

**Closed by RakeshMohanMSFT** 2022-10-26 06:36 UTC
Labels: Operations Management, Service Attention, bug, question, customer-reported
