### ISSUE TITLE
Users shouldn't be able to update public Azure Environment

### ISSUE THREAD

**Issue by vivsriaus** [Azure/azure-powershell#404] opened 2015-05-20 00:56 UTC
PS C:\> Set-AzureEnvironment -Name AzureChinaCloud -GalleryEndpoint https://gallery.chinacloudapi.cn/
Set-AzureEnvironment : Changing public environment is not supported.
Parameter name: environment
At line:1 char:1
+ Set-AzureEnvironment -Name AzureChinaCloud -GalleryEndpoint https://gallery.chin ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureEnvironment], ArgumentException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Profile.SetAzureEnvironmentCommand

PS C:\> Get-AzureEnvironment -Name AzureChinaCloud

Name                                     : AzureChinaCloud
ActiveDirectoryServiceEndpointResourceId : https://management.core.chinacloudapi.cn/
AdTenant                                 :
Gallery                                  : https://gallery.chinacloudapi.cn/
ManagementPortalUrl                      : http://go.microsoft.com/fwlink/?LinkId=301902
ServiceManagement                        : https://management.core.chinacloudapi.cn/
PublishSettingsFileUrl                   : http://go.microsoft.com/fwlink/?LinkID=301776
ResourceManager                          :
SqlDatabaseDnsSuffix                     : .database.chinacloudapi.cn
StorageEndpointSuffix                    : core.chinacloudapi.cn
ActiveDirectory                          : https://login.chinacloudapi.cn/
Graph                                    :
TrafficManagerDnsSuffix                  : trafficmanager.cn
AzureKeyVaultDnsSuffix                   :
AzureKeyVaultServiceEndpointResourceId   :

**Comment by devigned** [comment] 2015-05-26 16:39
This is the intended behavior for not being able to update public Azure environments. This issue is two fold.
- The gallery property for AzureChinaCloud should be populated, as currently is not. (defect or not available - Resource Management)
- The subsequent Get after the Set of environment should not have the change to gallery. (defect - AzPS)

One work around for this, is to make a new environment based off of the AzureChinaCloud environment which will have the Gallery uri set.

**Comment by markcowl** [comment] 2016-02-18 22:23
fixed in the above PR, closing.

**Closed by markcowl** 2016-02-18 22:23 UTC
Labels: Team
