### ISSUE TITLE
Various issues with the operation names in the Microsoft.Sql provider

### ISSUE THREAD

**Issue by SiloReed** [Azure/azure-powershell#4162] opened 2017-06-20 19:40 UTC
### Cmdlet(s)
Set-AzureRmSqlDatabase,  Get-AzureRMProviderOperation

### PowerShell Version
5.1.15063.413

### Module Version
AzureRM.Sql 3.1.0

### OS Version
10.0.15063.413

### Description
I'm attempting to determine the least amount of privileges necessary to update the tags on a SQL Database. I'm using a service principal with a custom role assignment and role definition. It appears that the Set-AzureRmSqlDatabase cmdlet is using the 'Microsoft.Sql/servers/databases/write' operation but this operation is not returned by Get-AzureRMProviderOperation and cannot be set with New-AzureRMRoleDefinition. Further, there are operations in the 'SQL DB Contributors' role that can't be get or set.

### Script/Steps for Reproduction
It appears that I have to include the "Microsoft.Sql/servers/databases/*" action in the custom role definition, else this exception is thrown by Set-AzureRmSqlDatabase:
```powershell
AuthorizationFailed: The client 'cc5bf1cc-ced3-4912-9da0-92f3bfbb9f6c' with object id
'cc5bf1cc-ced3-4912-9da0-92f3bfbb9f6c' does not have authorization to perform action
'Microsoft.Sql/servers/databases/write' over scope '/subscriptions/########-####-####-####-############/resourceGroups/
rg-ODSTest/providers/Microsoft.Sql/servers/azrodstst01/databases/AZDWTST01'.
    + CategoryInfo          : CloseError: (:) [Set-AzureRmSqlDatabase], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Sql.Database.Cmdlet.SetAzureSqlDatabase
    + PSComputerName        : localhost
```
It seems odd that the operation in the exception is named 'Microsoft.Sql/servers/databases/write', yet this operation is not returned by this command:
```powershell
Get-AzureRMProviderOperation Microsoft.Sql/* | Where Operation -like "Microsoft.Sql/servers/databases/write*" | Select Operation, Description 
```
If I try to include 'Microsoft.Sql/servers/databases/write' in the array of actions in the custom role definition, then the New-AzureRMRoleDefinition cmdlet throws this exception:
```powershell
New-AzureRMRoleDefinition : InvalidActionOrNotAction: 'Microsoft.Sql/servers/databases/write' does not match any of the actions supported by the providers.
```
Executing:
```powershell
(Get-AzureRmRoleDefinition -Name 'SQL DB Contributor').Actions
```
Shows an action named 'Microsoft.Sql/servers/read' yet this action is not returned by:
```powershell
Get-AzureRMProviderOperation Microsoft.Sql/* | Where Operation -eq "Microsoft.Sql/servers/read" | Select Operation, Description
```
Likewise, this command returns NotActions that aren't returned by Get-AzureRMProviderOperation Microsoft.Sql/* :
```powershell
(Get-AzureRmRoleDefinition -Name 'SQL DB Contributor').NotActions
```
Such as:
'Microsoft.Sql/servers/databases/auditingSettings/*'
'Microsoft.Sql/servers/databases/auditRecords/read'

**Comment by cormacpayne** [comment] 2017-06-20 20:23
@akromm Hey Adam, would you mind taking a look at this issue?

**Comment by akromm** [comment] 2017-06-20 21:35
Hi @shahabhijeet, thanks for reporting this.  I have investigated the issue and determined the cause.  To fix this it will require some backend changes and deployment.  I will update when I have a timeline for the expected fix.

**Comment by cormacpayne** [comment] 2017-06-20 22:19
@SiloReed ^

**Comment by akromm** [comment] 2017-06-23 17:19
@SiloReed I expect the fix to be rolled out hopefully by the end of next week (June 30).

**Comment by akromm** [comment] 2017-06-29 16:34
@SiloReed The fix has been rolled out worldwide and your issue should be resolved now.  Can you try again and let me know if it is working for you?

**Comment by SiloReed** [comment] 2017-06-30 19:38
@akromm I re-tested and I can happily confirm that everything looks good on my end. Thanks!

**Closed** 2017-06-30 19:38 UTC
Labels: Sql
