### ISSUE TITLE
AzureRmVirtualNetworkGatewayConnection uint mapping errors

### ISSUE THREAD

**Issue by jonsabo** [Azure/azure-powershell#2873] opened 2016-08-31 23:55 UTC
### Cmdlet(s)

Get-AzureRmVirtualNetworkGatewayConnection
New-AzureRmVirtualNetworkGatewayConnection
### PowerShell Version

5.0.10586.494
### Module Version

2.0.1
### OS Version

BuildVersion                   10.0.10586.494   
### Description

I received an error getting the status of a connection. I removed it without issue to modify the local gw, but then when I tried to create the connection again it errored out with the same Int64 -> UInt64 mapping error:

```
get-AzureRmVirtualNetworkGatewayConnection : Missing type map configuration or unsupported mapping.
Mapping types:
Int64 -> UInt64
System.Int64 -> System.UInt64
Destination path:
PSVirtualNetworkGatewayConnection.EgressBytesTransferred.EgressBytesTransferred
Source value:
2374563
```

I was able to re-create the connection using the portal successfully. Once I did that, the portal was able to pull the details of the connection, but the posh cmdlets failed with the same mapping error again.

It appears there are others having this issue sporadically:
https://github.com/Azure/azure-powershell/issues/2786
https://github.com/Azure/azure-powershell/issues/1812

If you need any more detail on my side let me know. I tried digging through, but my lack of familiarity with the code base and automapper led to some difficulties. I can see where those properties are defined as uints here:
https://github.com/Azure/azure-powershell/blob/master/src/ResourceManager/Network/Commands.Network/Models/PSVirtualNetworkGatewayConnection.cs#L40-L42

``` c#
        public ulong EgressBytesTransferred { get; set; }
        public ulong IngressBytesTransferred { get; set; }
```

But not sure why it's having difficulty converting the values from signed to unsigned or where that type map is defined.
### Debug Output

```
get-AzureRmVirtualNetworkGatewayConnection -Name connectionname -ResourceGroupName rgname -Debug
...

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/subid/resourceGroups/rgname/providers/Microsoft.Network/connections/connectionname?api-version=2016-06-01

Headers:
x-ms-client-request-id        : da6c06d1-aa6c-444d-a874-3da644bdcc64
accept-language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-request-id               : f6b1be94-e98a-4cc1-972d-87be61e60b83
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-cache
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 14978
x-ms-correlation-request-id   : b5990ffa-de64-48e4-9fd0-355e2ff6322b
x-ms-routing-request-id       : SOUTHCENTRALUS:20160831T232017Z:b5990ffa-de64-48e4-9fd0-355e2ff6322b
Date                          : Wed, 31 Aug 2016 23:20:16 GMT

Body:
{
  "name": "connectionname",
  "id": "/subscriptions/subid/resourceGroups/rgname/providers/Microsoft.Network/connections/connectionname",
  "etag": "W/\"b9597bfd-6885-4024-84df-7d4a85102a6c\"",
  "type": "Microsoft.Network/connections",
  "location": "centralus",
  "properties": {
    "provisioningState": "Succeeded",
    "resourceGuid": "guid",
    "virtualNetworkGateway1": {
      "id": "/subscriptions/subid/resourceGroups/rgname/providers/Microsoft.Network/virtualNetworkGateways/gwname"
    },
    "localNetworkGateway2": {
      "id": "/subscriptions/subid/resourceGroups/rgname/providers/Microsoft.Network/localNetworkGateways/localgwname"
    },
    "connectionType": "IPsec",
    "routingWeight": 0,
    "sharedKey": "redacted",
    "enableBgp": false,
    "connectionStatus": "Connected",
    "ingressBytesTransferred": 2858474,
    "egressBytesTransferred": 2374563
  }
}


get-AzureRmVirtualNetworkGatewayConnection : Missing type map configuration or unsupported mapping.
Mapping types:
Int64 -> UInt64
System.Int64 -> System.UInt64
Destination path:
PSVirtualNetworkGatewayConnection.EgressBytesTransferred.EgressBytesTransferred
Source value:
2374563
At line:1 char:1
+ get-AzureRmVirtualNetworkGatewayConnection -Name connectionname -Reso ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmVirt...tewayConnection], AutoMapperMappingException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.GetAzureVirtualNetworkGatewayConnectionCommand

DEBUG: 6:20:29 PM - GetAzureVirtualNetworkGatewayConnectionCommand end processing.
DEBUG: 6:20:29 PM - GetAzureVirtualNetworkGatewayConnectionCommand end processing.
```

**Comment by cormacpayne** [comment] 2016-09-01 16:13
@DeepakRajendranMsft Hey Deepak, would you mind taking a look at this issue?

**Comment by mraymond77** [comment] 2016-10-06 21:56
Also getting this with AzureRmVirtualNetworkGatewayConnection related commands

**Version:**
```
> Get-Module AzureRM | Select-Object Version

Version
-------
2.1.0
```
**Examples:**
```
> get-AzureRmVirtualNetworkGatewayConnection -Name $ConName -ResourceGroupName $RGName
get-AzureRmVirtualNetworkGatewayConnection : Missing type map configuration or unsupported mapping.
Mapping types:
Int64 -> UInt64
System.Int64 -> System.UInt64
Destination path:
PSVirtualNetworkGatewayConnection.EgressBytesTransferred.EgressBytesTransferred
Source value:
0
At line:1 char:1 onprem
+ get-AzureRmVirtualNetworkGatewayConnection -Name azure-to-onprem-tu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmVirt...tewayConnection], AutoMapperMappingException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.GetAzureVirtualNetworkGatewayConnectionCommand
```
```
> New-AzureRmVirtualNetworkGatewayConnection -Name $ConName -ResourceGroupName $RGName `
-Location 'East US' -VirtualNetworkGateway1 $gateway1 -LocalNetworkGateway2 $local `
-ConnectionType IPsec -RoutingWeight 10 -SharedKey $key
WARNING: The output object type of this cmdlet will be modified in a future release.
New-AzureRmVirtualNetworkGatewayConnection : 
Mapping types:
UInt64 -> Nullable`1
System.UInt64 -> System.Nullable`1[[System.Int64, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]
Destination path:
VirtualNetworkGatewayConnection.EgressBytesTransferred.EgressBytesTransferred
Source value:
0
At line:1 char:1
+ New-AzureRmVirtualNetworkGatewayConnection -Name azure-to-onprem-tu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmVirt...tewayConnection], AutoMapperMappingException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.NewAzureVirtualNetworkGatewayConnectionCommand
```

**Comment by invisibleaxm** [comment] 2016-10-10 14:03
Looping @markjbrown as it looks like he identified a similar (same?) issue #1812 back in May. I tried multiple things, including installing older versions of AzureRM / AzureRM.Network with no success:

`> Get-Module AzureRM | Select-Object Version

Version
-------
1.5.0  `

Getting the same error 

`
get-azurermvirtualnetworkgatewayconnection : Missing type map configuration or unsupported mapping.
Mapping types:
Int64 -> UInt64
System.Int64 -> System.UInt64
Destination path:
PSVirtualNetworkGatewayConnection.EgressBytesTransferred.EgressBytesTransferred
Source value:
0
At line:1 char:10
+ $conn1 = get-azurermvirtualnetworkgatewayconnection -Name "Primary" - ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmVirt...tewayConnection], AutoMapperMappingException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.GetAzureVirtualNetworkGatewayConnectionCommand
`

In my case, I need to create a new virtual network gateway connection and enable BGP, is there a work-around that doesn't involve using the new-azurermvirtualnetworkgatewayconnection commandlet?

**Comment by shadewlkr** [comment] 2016-11-02 18:32
Has anyone come up with a solution to this?   I receive the same error when trying to create a connection using New-AzureRmVirtualNetworkGatewayConnection.   Is there any other way to enable BGP aside from powershell?

**Comment by alenat10** [comment] 2016-11-18 20:11
same issue :(

**Comment by Fazered** [comment] 2016-12-01 17:04
Same issue and I'm trying to create a Web Application Firewall and that can't be done by JSON yet. Very frustrating.

**Comment by shadewlkr** [comment] 2016-12-06 19:49
@markjbrown were you able to ever resolve the same issues you were having around this?

**Comment by jrochet** [comment] 2016-12-28 19:59
Same issue here with New-AzureRmVirtualNetworkGatewayConnection:
PS C:\Users\jbrad> New-AzureRmVirtualNetworkGatewayConnection -Name 'JBLAB-S2S' -ResourceGroupName 'JBLAB-RG' -Location CanadaEast -VirtualNetworkGate
way1 $VNetGW -LocalNetworkGateway2 $LocalGW -ConnectionType 'IPSec' -RoutingWeight 10 -SharedKey 'abc123'
WARNING: The output object type of this cmdlet will be modified in a future release.
New-AzureRmVirtualNetworkGatewayConnection :
Mapping types:
UInt64 -> Nullable`1
System.UInt64 -> System.Nullable`1[[System.Int64, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]
Destination path:
VirtualNetworkGatewayConnection.EgressBytesTransferred.EgressBytesTransferred
Source value:
0
At line:1 char:1
+ New-AzureRmVirtualNetworkGatewayConnection -Name 'JBLAB-S2S' -Resourc ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmVirt...tewayConnection], AutoMapperMappingException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.NewAzureVirtualNetworkGatewayConnectionCommand

**Comment by markjbrown** [comment] 2017-01-02 17:57
Let me get with our team and take another look at this. Will update here.

thanks.

**Comment by inghak** [comment] 2017-01-02 19:59
I have had this problem for a long time. I resolved it by removing AzureRm installed with powershell and instead installed using the msi.

**Comment by markjbrown** [comment] 2017-01-02 20:20
Thanks @inghak. Will look more closely at that.

**Comment by Fazered** [comment] 2017-01-06 09:27
Thanks @inghak 

For others: I tested just installing the msi from https://github.com/Azure/azure-powershell/releases without first removing the azure package and it worked flawlessly.

**Comment by singlekorn** [comment] 2017-01-20 01:51
@inghak @Fazered Thank you.  This also resolved my issue today.

**Comment by andyjballgit** [comment] 2017-01-28 10:44
I just hit this issue again running Get-AzureRMApplicationGateway and installled "over the top" of existing installation as per @Fazered s post above and fixed for me

**Comment by RayBrindley** [comment] 2017-02-03 04:51
I tried doing this but it is still a problem for me. I have tried it on different type of connections and all get the same issue! Any ideas on why it happens?

**Comment by invisibleaxm** [comment] 2017-02-03 05:18
hi there, i tried the work-around with no luck. Any ETA on a fix ?

Thanks!

**Comment by dimachait** [comment] 2017-02-13 15:18
Looks like this still happens in 3.5.0
PS C:\WINDOWS\system32> Get-AzureRmVirtualNetworkGatewayConnection -Name <REMOVED> -ResourceGroupName <REMOVED> -Debug
DEBUG: 10:12:53 AM - GetAzureVirtualNetworkGatewayConnectionCommand begin processing with ParameterSet '__AllParameterSets'.

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-request-id               : <REMOVED>
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-cache
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 14975
x-ms-correlation-request-id   : <REMOVED>
x-ms-routing-request-id       : <REMOVED>:20170213T151256Z:<REMOVED>
Date                          : Mon, 13 Feb 2017 15:12:56 GMT

Body:
{
  "name": "<REMOVED>",
  "id": "/subscriptions/<REMOVED>/resourceGroups/<REMOVED>/providers/Microsoft.Network/connections/<REMOVED>",
  "etag": "W/\"<REMOVED>\"",
  "type": "Microsoft.Network/connections",
  "location": "<REMOVED>",
  "properties": {
    "provisioningState": "Succeeded",
    "resourceGuid": "<REMOVED>",
    "virtualNetworkGateway1": {
      "id": "/subscriptions/<REMOVED>/resourceGroups/<REMOVED>/providers/Microsoft.Network/virtualNetworkGateways/<REMOVED>"
    },
    "virtualNetworkGateway2": {
      "id": "/subscriptions/<REMOVED>/resourceGroups/<REMOVED>/providers/Microsoft.Network/virtualNetworkGateways/<REMOVED>"
    },
    "connectionType": "Vnet2Vnet",
    "routingWeight": 0,
    "sharedKey": "<REMOVED>",
    "enableBgp": false,
    "connectionStatus": "Connected",
    "ingressBytesTransferred": 3567687239,
    "egressBytesTransferred": 2986874728
  }
}


Confirm
Missing type map configuration or unsupported mapping.

Mapping types:
Int64 -> UInt64
System.Int64 -> System.UInt64

Destination path:
PSVirtualNetworkGatewayConnection.EgressBytesTransferred.EgressBytesTransferred

Source value:
2986874728
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
Get-AzureRmVirtualNetworkGatewayConnection : Missing type map configuration or unsupported mapping.
Mapping types:
Int64 -> UInt64
System.Int64 -> System.UInt64
Destination path:
PSVirtualNetworkGatewayConnection.EgressBytesTransferred.EgressBytesTransferred
Source value:
2986874728
At line:1 char:1
+ Get-AzureRmVirtualNetworkGatewayConnection -Name <REMOVED> - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmVirt...tewayConnection], AutoMapperMappingException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.GetAzureVirtualNetworkGatewayConnectionCommand

DEBUG: 10:13:16 AM - GetAzureVirtualNetworkGatewayConnectionCommand end processing.
DEBUG: 10:13:16 AM - GetAzureVirtualNetworkGatewayConnectionCommand end processing.
PS C:\WINDOWS\system32> Get-Module AzureRM | Select-Object Version

Version
-------
3.5.0

**Comment by takekazuomi** [comment] 2017-03-23 06:13
hi there,
Today I got this error. Why has this problem been left for such a long time?

I went on a long journey. Follow me, If you like :D

It seems to be falling here.
Https://github.com/Azure/azure-powershell/blob/dev/src/ResourceManager/Network/Commands.Network/VirtualNetworkGatewayConnection/VirtualNetworkGatewayConnectionBaseCmdlet.cs#L66

Mapping was defined here.
Https://github.com/Azure/azure-powershell/blob/dev/src/ResourceManager/Network/Commands.Network/Common/NetworkResourceManagerProfile.cs#L387

MNM.VirtualNetworkGatewayConnection is the type of Azure SDK. In my opinion.
The source of the SDK is here.
Https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/VirtualNetworkGatewayConnection.cs#L155

This source is generated by swagger. The latest definition is here.
Https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2017-03-01/swagger/virtualNetworkGateway.json#L1425

Looking at it, EgressBytesTransferred and IngressBytesTransferred are signed 64 bit int.

My conclusion is to change the model of PowerShell's model class EgressBytesTransferred and IngressBytesTransferred. Here.
Https://github.com/Azure/azure-powershell/blob/master/src/ResourceManager/Network/Commands.Network/Models/PSVirtualNetworkGatewayConnection.cs#L41

What do you think? If you agree, I will create a PR.

**Comment by takekazuomi** [comment] 2017-04-01 07:49
# Shortest reproduction step. #

1. Start new PowerShell session
2. Login-AzureRmAccount
3. Get-AzureRmVM -ErrorAction SilentlyContinue | Out-Null
4. Get-AzureRmVirtualNetworkGatewayConnection -ResourceGroupName *****

I got following errors.
```
Get-AzureRmVirtualNetworkGatewayConnection: Missing type map configuration or unsupported mapping.
Mapping types:
Int64 -> UInt 64
System.Int64 -> System.UInt64
Destination path:
PSVirtualNetworkGatewayConnection.EgressBytesTransferred.EgressBytesTransferred
Source value:
0
```
When not execute step 3 'Get-AzureRmVM'. Everything works fine.

# Root cause: #
AzureRm.Network and AzureRm.Compute use AutoMapper 3.1.1, but AzureRm.Compute does not include AutoMapper.Net4.dll which is .NET 4 PlatformSpecificMapper. The converter of System.Int64 -> System.UInt64 is included in AutoMapper.Net4.dll. Since AutoMapper 's default converter is initialized only once, when AzureRm.Compute is executed for the first time, the converter of System.Int64 -> System.UInt64 is not included in the default converter.

On the other hand, AzureRm.Network refers to AutoMapper.Net4.dll. When AutoMapper is initialized in the context of AzureRm.Network, the converter of System.Int64 -> System.UInt64 is included in the default converter.

I spent a lot of time for reproducing this problem in last week.
I will create a PR again.

**Comment by markcowl** [comment] 2017-04-20 23:27
This should be fixed by #3715.  The fix will go out in the May release.

**Comment by henry416** [comment] 2017-04-27 16:51
@markcowl Was this fix included in PS 3.8 gallery release? We are still seeing issues with nullable and uint casting in 3.8.

**Comment by takekazuomi** [comment] 2017-04-27 17:02
@henry416  It is not included in 3.8. I think it will be in the next release.

## Workaround
It can be avoided by copying AutoMapper.Net4.dll from AzureRm.Network directory to AzureRm.Compute directory .

In my environment, modules are installed in the following directories.
```
C: \Program Files\WindowsPowerShell\Modules\AzureRM.Network\3.7.0
C: \Program Files\WindowsPowerShell\Modules\AzureRM.Compute\2.9.0
```

**Comment by henry416** [comment] 2017-04-27 17:03
@takekazuomi Okay thanks. I actually read the comment wrong. I will forward this information to others who are experiencing this issue.

**Comment by nshampur** [comment] 2017-04-28 02:54
Surprised how this wasn't caught by the tests. Thanks @takekazuomi  for the workaround

**Comment by takekazuomi** [comment] 2017-05-12 09:46
@markcowl  I confirmed the fix in 4.0.0.
Thank you.

**Closed** 2017-06-07 00:09 UTC
Labels: Networking

**Comment by pixelicous** [comment] 2017-10-09 07:16
A powershell workflow runbook that worked continuously, stopped working out of the blue. nothing changed on the automation account.
The lines that followed that error:
Select-AzureRmSubscription -SubscriptionName $SubscriptionName
$AzureRMVMSS = Get-AzureRMVMSS (<<< The error is on this line)

It might be out of date modules, but this as worked up till today, without us updating the modules manually or anything. Kind of weird for it to stopped working out of the blue.

Get-AzureRMVMSS : Missing type map configuration or unsupported mapping.

Mapping types:
VirtualMachineScaleSet -> PSVirtualMachineScaleSetList
Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSet -> 
Microsoft.Azure.Commands.Compute.Automation.Models.PSVirtualMachineScaleSetList

Destination path:
PSVirtualMachineScaleSetList

Source value:
Microsoft.Azure.Management.Compute.Models.VirtualMachineScaleSet
At Set-VaronisScaleSet:12 char:12
+ 
    + CategoryInfo          : NotSpecified: (:) [Get-AzureRmVmss], AutoMapperMappingException
    + FullyQualifiedErrorId : 
AutoMapper.AutoMapperMappingException,Microsoft.Azure.Commands.Compute.Automation.GetAzureRmVmss

**Comment by cormacpayne** [comment] 2017-10-09 21:19
@pixelicous thanks for the update. We're looking to fix issues relating to `AutoMapperMappingException` in [this PR](https://github.com/Azure/azure-powershell/pull/4679) and have it go in with the 4.4.1 release of Azure PowerShell.

**Comment by pixelicous** [comment] 2017-10-24 06:41
@cormacpayne Ok, it haven't happened since, today happened again, all scheduled jobs running related to vm scale sets couldn't execute..

**Comment by cormacpayne** [comment] 2017-10-24 16:24
@pixelicous unfortunately we weren't able to get the PR into the 4.4.1 release, but it will be in the 5.0.0 release 😄 sorry about the delay!
