### ISSUE TITLE
Get-AzureSubscription fails on profiles using auth token

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/azure-powershell#344] opened 2015-04-16 21:54 UTC
If you create a new profile with an authtoken and select it, you are authn'd against Azure but Get-AzureSubscription will fail with:

Get-AzureSubscription : Illegal credential type
Parameter name: credentialType
At line:1 char:1
+ Get-AzureSubscription
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureSubscription], ArgumentException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Profile.GetAzureSubscriptionCommand

**Comment by hovsepm** [comment] 2015-04-30 18:31
Thanks for filing. We can reproduce it with latest build. Will be fixed in the next release.

**Comment by stankovski** [comment] 2015-06-25 00:03
@bmoore-msft this is by design since Get-AzureSubscription requires different tenant tokens to query subscriptions. Please use profile created from username/password or service principal with this cmdlet.

**Closed by stankovski** 2015-06-25 00:03 UTC
Labels: Team

**Comment by bmoore-msft** [comment] 2015-07-02 22:58
Ok, I think we need to revisit this - if I run Get-AzureSubscription when I have multiple/different accounts authn'd - it fails for all of them.  It might be fine to not return or warn for the token account, but having the token account in there shouldn't prevent the others from working.
