### ISSUE TITLE
AZ connect module not working

### ISSUE THREAD

**Issue by ChrisCalzaretta** [Azure/azure-powershell#11768] opened 2020-04-30 15:41 UTC
As soon as i ran the file storage preview all went down the drain
Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope CurrentUser

# Navigate to where AzFilesHybrid is unzipped and stored and run to copy the files into your path
.\CopyToPSPath.ps1 

#Import AzFilesHybrid module 
Import-Module -Name AzFilesHybrid

i am unable to use connect-azconnect

Ran these commands
PS C:\WINDOWS\system32> Install-Module -name AZ -Force -AllowClobber 

PS C:\WINDOWS\system32> Import-Module -Name Az.Accounts

PS C:\WINDOWS\system32> Import-Module Az.Accounts -Force
Import-Module : Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, 
Version=3.19.2.6005, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The 
system cannot find the file specified.
At C:\Users\Chris\Documents\WindowsPowerShell\Modules\Az.Accounts\1.7.4\Az.Accounts.psm1:83 char:1
+ Import-Module (Join-Path -Path $PSScriptRoot -ChildPath Microsoft.Azu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand

Can you help? I cant run any az command now

**Comment by dingmeng-xue** [comment] 2020-05-01 13:13
@ChrisCalzaretta, what's module of AzFilesHybrid? Could you try to import Az.Accounts at the first and check if Az.Accounts can be loaded successfully?

**Comment by ChrisCalzaretta** [comment] 2020-05-01 18:08
The azfileshybrid
https://github.com/Azure-Samples/azure-files-samples

This module is to allow you to enable RBAC on file storage. However my
machine got hosed from it :(

**Comment by ChrisCalzaretta** [comment] 2020-05-01 20:35
No i am not able to import the module.. It does error on newtonsoft dll v 10.0.0 not being in place anymore

**Comment by dingmeng-xue** [comment] 2020-05-02 01:02
The error seems different from previous. Could you share the full error message?

**Comment by dcaro** [comment] 2020-06-01 23:12
@wmgries this seems to be related to the AzFilesHybrid module, can you please have a look?

**Comment by dcaro** [comment] 2020-06-22 22:25
@ChrisCalzaretta the issue is in the AzFilesHybrid module and we do not own this module. Can you please open an issue on their repo https://github.com/Azure-Samples/azure-files-samples ? 
I'm going to close this issue, feel free to reopen it here is the owner of the module identifies that the issue is related to the Az modules.

**Closed by dcaro** 2020-06-22 22:25 UTC
Labels: Azure PS Team, More Info :label:, customer-reported, question
