### ISSUE TITLE
Start-AzStorageBlobCopy

### ISSUE THREAD

**Issue by abu3lia** [Azure/azure-powershell#16902] opened 2022-01-24 11:24 UTC
### Description

How many copy operation can Start-AzStorageBlobCopy command handle in parallel? 
https://docs.microsoft.com/en-us/powershell/module/az.storage/start-azstorageblobcopy?view=azps-7.1.0

We have did some test and noticed that 2 blobs are getting copied at a time, once finished another blobs start the copy.
Can you please mention how the copy operation is being handled by this command and how many operation it can handle in simultaneously?

**Comment by blueww** [comment] 2022-01-25 03:14
@abu3lia 
start-azstorageblobcopy will trigger server side blob sync copy, and Blob Async Copy is all handled by server, PowerShell can’t change it .
And Blob Async Copy don’t have any SLA when the source/dest blob are in different account. (In same account, SLA is 90s )
So it’s by design if customer see cross account blob async copy is slow, or only have small count of copies run parallelly.

See more details in : 
[Copy Blob (REST API) - Azure Storage | Microsoft Docs](https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob)
> Multiple pending Copy Blob operations within an account might be processed sequentially. 

[SLA for Storage | Azure](https://www.azure.cn/en-us/support/sla/storage/)
> Copy Blob	Ninety (90) seconds (where the source and destination blobs are within the same storage account)

Besides that, if it's block blob copy, you might can try Copy-AzStorageblob. This is server side sync copy.

**Comment by blueww** [comment] 2022-01-25 03:15
I will update the help doc of start-azstorageblobcopy for that information.
And will update this issue after the doc update is merged.

**Comment by abu3lia** [comment] 2022-01-25 07:28
> I will update the help doc of start-azstorageblobcopy for that information. And will update this issue after the doc update is merged.

Thanks @blueww for your help on this :)

**Comment by blueww** [comment] 2022-01-25 09:38
Pr https://github.com/Azure/azure-powershell/pull/16914 is raised to update doc for this issue.

**Comment by dingmeng-xue** [comment] 2022-02-07 02:38
Close this issue as #16914 is merged.

**Closed by dingmeng-xue** 2022-02-07 02:38 UTC
Labels: Storage, Doc - Reference, Service Attention, question, customer-reported
