### ISSUE TITLE
Create and Manage WebJobs via AzureRm PowerShell?

### ISSUE THREAD

**Issue by mrichman** [Azure/azure-powershell#4997] opened 2017-11-15 19:55 UTC
Is there no way to list or configure WebJobs via AzureRm PowerShell?

This is as far as I can get using the generic cmdlets:

```
Invoke-AzureRmResourceAction -ResourceGroupName $resourceGroup -ResourceType Microsoft.Web/sites/TriggeredWebJobs -ResourceName "$AppService/$($webJobName)" -Action run -ApiVersion 2015-08-01 -Force

$job = Get-AzureRmResource -ResourceGroupName $resourceGroup -ResourceName $AppService -ResourceType Microsoft.web/sites/TriggeredWebJobs -ApiVersion $Apiversion 
$job.Properties.latest_run
```

Output:

```
id         : 201711152040120309
name       : 201711152040120309
status     : Running
start_time : 2017-11-15T20:40:12.0309595Z
end_time   : 0001-01-01T00:00:00
duration   : 00:00:00.9219138
output_url : https://900013sisclientweb.scm.azurewebsites.net/vfs/data/jobs/triggered/MyWebJob/201711152040120309/output_log.txt
error_url  : 
url        : https://900013sisclientweb.scm.azurewebsites.net/api/triggeredwebjobs/MyWebJob/history/201711152040120309
job_name   : MyWebJob
trigger    : External - PSVersion/v5.1.15063.674 AzurePowershell/v4.4.0
```

**Comment by cormacpayne** [comment] 2017-11-16 16:03
@mrichman Hey Mark, unfortunately there are currently no cmdlets in `AzureRM` for managing WebJobs.

@Nking92 Hey Nicholas, do you know if this functionality is on the radar for your team?

Closing this issue as it is a duplicate of https://github.com/Azure/azure-powershell/issues/661 . We can move the discussion there.

**Closed by cormacpayne** 2017-11-16 16:03 UTC
