### ISSUE TITLE
Missing parameter -SnapshotName

### ISSUE THREAD

**Issue by maniaX1** [Azure/azure-powershell#25791] opened 2024-08-09 12:02 UTC
### Type of issue

Missing information

### Feedback

Hello,
 I tried to create manual backups with PowerShell and with parameter -UseExistingSnapshot but it failed because of:
 New-AzNetAppFilesBackup : Long running operation failed with status 'Failed'. Additional Info:'Missing value for
'SnapshotName''
At line:1 char:1
+ New-AzNetAppFilesBackup -ResourceGroupName "rgname" -Acc ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzNetAppFilesBackup], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.NetAppFiles.Backup.NewAzureRmNetAppFilesBackup

There is no such value SnapshotName in documentation.
Please fix that.
Thank you.

### Page URL

https://learn.microsoft.com/en-us/powershell/module/az.netappfiles/new-aznetappfilesbackup?view=azps-12.2.0

### Content source URL

https://github.com/Azure/azure-powershell/blob/main/src/NetAppFiles/NetAppFiles/help/New-AzNetAppFilesBackup.md

### Author

@mikefrobbins

### Document Id

e561cf36-db18-5b8e-c2a5-05ff714f4f64

**Comment by audunn** [comment] 2024-08-16 09:52
Looking in to this

**Comment by audunn** [comment] 2024-08-20 10:04
@isra-fel The issue is fixed in this PR https://github.com/Azure/azure-powershell/pull/25837

**Comment by audunn** [comment] 2024-08-21 09:25
This is fixed and should be in the next release ETA 9/3

**Closed by audunn** 2024-08-21 09:25 UTC
Labels: Service Attention, NetApp Files, customer-reported

**Comment by maniaX1** [comment] 2024-08-21 09:31
Thank you very much!
