### ISSUE TITLE
Set-AzureSubscription should accept pipeline objects

### ISSUE THREAD

**Issue by trondhindenes** [Azure/azure-powershell#429] opened 2015-05-26 20:52 UTC
This used to work:
Get-AzureSubscription -Current | set-AzureSubscription etc, however it doesn't anymore. Please re-add pipline support to the set-azuresubscription cmdlet.

**Comment by stankovski** [comment] 2015-06-25 01:26
@trondhindenes thank you for filing this. We can repro the issue.

**Comment by markcowl** [comment] 2016-02-18 22:25
@trondhindenes This is schedule for the late March release

**Comment by markcowl** [comment] 2016-05-03 01:12
### Root Cause
Mismatch in output properties in Get-AzureSubscription and input parameters for Set-AzureSUbscription

### Proposed Solution
- Add an alias to each Parameter to support tne new output object properties for Get-AzureSubscription
- Add a mocked scenario test to verify the functionality

### Cost (Work Units): 2

**Comment by hovsepm** [comment] 2016-05-19 21:31
Fixed in dev branch, will be available in June release

**Closed by hovsepm** 2016-05-19 21:31 UTC
Labels: 1 - Ready, P2, Team, Work units: 2
