### ISSUE TITLE
[Eng]: Build fails with multiple NU1504 errors

### ISSUE THREAD

**Issue by Brandon411** [Azure/azure-powershell#19489] opened 2022-09-14 22:31 UTC
### Description

I am using a fresh checkout of the azure-powershell repo on the main branch. When trying to build with the command `msbuild build.proj` per the documentation, I am getting multiple NU1504 errors.

> "C:\swg\azure-powershell\build.proj" (default target) (1) ->
> (BuildNormalModules target) ->
>   C:\swg\azure-powershell\src\Websites\Websites.Helper\Websites.Helper.csproj : error NU1504: Duplicate 'PackageReference' items found. Remove the duplicate items or use the Update functionality to ensure a c
> onsistent restore behavior. The duplicate 'PackageReference' items are: Newtonsoft.Json 10.0.3, Newtonsoft.Json 10.0.3. [C:\swg\azure-powershell\build.proj]
>   C:\swg\azure-powershell\src\RecoveryServices\RecoveryServices.SiteRecovery.Test\RecoveryServices.SiteRecovery.Test.csproj : error NU1504: Duplicate 'PackageReference' items found. Remove the duplicate items
>  or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageReference' items are: Microsoft.Azure.Management.RecoveryServices 4.3.3-preview, Microsoft.Azure.Management.Reco
> veryServices 4.3.3-preview. [C:\swg\azure-powershell\build.proj]
>   C:\swg\azure-powershell\src\SqlVirtualMachine\SqlVirtualMachine.Test\SqlVirtualMachine.Test.csproj : error NU1504: Duplicate 'PackageReference' items found. Remove the duplicate items or use the Update func
> tionality to ensure a consistent restore behavior. The duplicate 'PackageReference' items are: Microsoft.Azure.Management.ResourceManager 3.17.3-preview, Microsoft.Azure.Management.ResourceManager 3.17.3-prev
> iew. [C:\swg\azure-powershell\build.proj]
>   C:\swg\azure-powershell\src\Websites\Websites.Helper\Websites.Helper.csproj : error NU1504: Duplicate 'PackageReference' items found. Remove the duplicate items or use the Update functionality to ensure a c
> onsistent restore behavior. The duplicate 'PackageReference' items are: Newtonsoft.Json 10.0.3, Newtonsoft.Json 10.0.3. [C:\swg\azure-powershell\build.proj]
>   C:\swg\azure-powershell\src\RecoveryServices\RecoveryServices.SiteRecovery.Test\RecoveryServices.SiteRecovery.Test.csproj : error NU1504: Duplicate 'PackageReference' items found. Remove the duplicate items
>  or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageReference' items are: Microsoft.Azure.Management.RecoveryServices 4.3.3-preview, Microsoft.Azure.Management.Reco
> veryServices 4.3.3-preview. [C:\swg\azure-powershell\build.proj]
>   C:\swg\azure-powershell\src\SqlVirtualMachine\SqlVirtualMachine.Test\SqlVirtualMachine.Test.csproj : error NU1504: Duplicate 'PackageReference' items found. Remove the duplicate items or use the Update func
> tionality to ensure a consistent restore behavior. The duplicate 'PackageReference' items are: Microsoft.Azure.Management.ResourceManager 3.17.3-preview, Microsoft.Azure.Management.ResourceManager 3.17.3-prev
> iew. [C:\swg\azure-powershell\build.proj]
>   C:\swg\azure-powershell\build.proj(194,5): error MSB3073: The command "dotnet build C:\swg\azure-powershell\artifacts/Azure.PowerShell.sln -c Debug" exited with code 1.

MSBuild version 17.3.1+2badb37d1 for .NET Framework
SDK Version: 6.0.401

**Comment by Brandon411** [comment] 2022-09-15 00:14
I talked to @BethanyZhou and she informed me that this is an expected issue when using .NET 6 and this project, and then I can downgrade to .NET 5 which should fix the issue. Maybe this is a documentation issue not an internal engineering issue, but I think the development instructions should say that .NET 6 is not supported. The pre-requisite instructions link to a page which defaults to downloading .NET 6.

Install the latest [.NET Core SDK and .NET Framework Dev Pack 4.7.2](https://dotnet.microsoft.com/download) or greater

**Comment by dingmeng-xue** [comment] 2022-09-15 01:58
Thanks for suggestion. We will update the docs.

**Comment by NoriZC** [comment] 2022-09-19 07:23
Hi @Brandon411,
 
Thank you for reaching out! I am a new hire to our team and I encountered the same issue when I built the whole project at my first time. 

This issue is caused by the new version of the package manage tool Nuget, whose update comes with the new version of .NET 6. BTW as long as you are using Visual Studio 2022, it will install .NET 6 for you continuously hence the downgrade of .NET from 6 to 5 should better be with the downgrade of Visual Studio 2022 to 2019. 

This issue is now fixed and you can pull the latest code to continue your development with VS 2022 after the PR merging.

**Closed** 2022-09-19 08:04 UTC
Labels: Engineering, Tracking
