### ISSUE TITLE
Unexpected case change of paramter tags when creating RSG via azure pipelines

### ISSUE THREAD

**Issue by wembleyford** [Azure/azure-powershell#13425] opened 2020-11-05 16:53 UTC
## Description
This is a follow up to this bug report 
https://github.com/microsoft/azure-pipelines-tasks/issues/13822

When using new-azsubscriptionDeployment to deploy a resource group using a template file and parameter file, when doing this with the latest version of the Az module in an Azure devops pipeline, my resourcegroup tags are being renamed from their original case as defined in the parameter file to camelcase.    This does not occur when I use the same version on my laptop which is running Gentoo.

The above referenced bug report revealed that if I specific version 4.3.0 of the Az module, this behaviour does not occur.

## Steps to reproduce

With a parameter file containing 
```
"resourceGroupTags": {
      "value": {
        "TechnicalOwner": "John Smith", }
}
```
the output object from New-AzSubscription contains:
```
ParametersString        : 
...                       resourceGroupTags        Object                     {
                            "technicalOwner": "John Smith",
```

## Environment data

Explicitly setting the az module ot version 4.3.0 does not do this, newer versions do - but only in azure pipelines. 

My pipeline is using the default powershell@4 task in devops. 
The values of the $PSVersionTable are below

```
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Linux 4.15.0-1098-azure #109~16.04.1-Ubuntu SMP…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

Obviously I need to have confidence that the values I'm providing for Parameter names do not changing depending on the context of where they're being generated (in a pipeline, or ran manually from an interactive shell).   I note that with the latest versions of the module, this behaviour is only apparently when running in a pipeline and not on Gentoo.

Thanks

**Comment by dingmeng-xue** [comment] 2020-11-08 03:01
Resources team, please help to look into this issue.

**Comment by ChristopherGLewis** [comment] 2020-11-18 16:54
I can confirm this is happening, but also that it DOES NOT happen with AZ CLI

**Comment by dcaro** [comment] 2020-11-18 23:19
@armleads-azure can you please have a look?

**Comment by ChristopherGLewis** [comment] 2020-11-19 03:56
Forgot my module list:

```
Script     1.9.4      Az.Accounts                    
Script     1.9.3      Az.Accounts                    
Script     1.1.1      Az.Advisor                     
Script     1.3.0      Az.Aks                         
Script     1.1.4      Az.AnalysisServices            
Script     2.1.0      Az.ApiManagement               
Script     1.1.0      Az.ApplicationInsights         
Script     1.4.0      Az.Automation                  
Script     3.1.0      Az.Batch                       
Script     1.0.3      Az.Billing                     
Script     1.4.3      Az.Cdn                         
Script     1.6.0      Az.CognitiveServices           
Script     4.4.0      Az.Compute                     
Script     4.2.1      Az.Compute                     
Script     1.0.3      Az.ContainerInstance           
Script     1.1.1      Az.ContainerRegistry           
Script     1.1.0      Az.DataBoxEdge                 
Script     1.10.1     Az.DataFactory                 
Script     1.0.2      Az.DataLakeAnalytics           
Script     1.2.8      Az.DataLakeStore               
Script     1.0.0      Az.DataShare                   
Script     1.1.0      Az.DeploymentManager           
Script     2.0.0      Az.DesktopVirtualization       
Script     1.0.2      Az.DevTestLabs                 
Script     1.1.2      Az.Dns                         
Script     1.3.0      Az.EventGrid                   
Script     1.6.0      Az.EventHub                    
Script     1.6.1      Az.FrontDoor                   
Script     1.0.2      Az.Functions                   
Script     3.6.0      Az.HDInsight                   
Script     1.1.0      Az.HealthcareApis              
Script     2.5.0      Az.IotHub                      
Script     2.2.0      Az.KeyVault                    
Script     1.0.0      Az.Kusto                       
Script     1.3.2      Az.LogicApp                    
Script     1.1.3      Az.MachineLearning             
Script     1.1.0      Az.Maintenance                 
Script     1.1.0      Az.ManagedServices             
Script     1.0.2      Az.MarketplaceOrdering         
Script     1.1.1      Az.Media                       
Script     2.1.0      Az.Monitor                     
Script     3.4.0      Az.Network                     
Script     1.1.1      Az.NotificationHubs            
Script     2.3.0      Az.OperationalInsights         
Script     1.3.1      Az.PolicyInsights              
Script     1.1.2      Az.PowerBIEmbedded             
Script     1.0.3      Az.PrivateDns                  
Script     2.12.1     Az.RecoveryServices            
Script     1.2.1      Az.RedisCache                  
Script     1.0.3      Az.Relay                       
Script     0.7.7      Az.ResourceGraph               
Script     2.5.1      Az.Resources                   
Script     2.4.0      Az.Resources                   
Script     1.4.1      Az.ServiceBus                  
Script     2.2.0      Az.ServiceFabric               
Script     1.2.0      Az.SignalR                     
Script     2.11.0     Az.Sql                         
Script     1.1.0      Az.SqlVirtualMachine           
Script     2.6.0      Az.Storage                     
Script     1.3.0      Az.StorageSync                 
Script     1.0.1      Az.StreamAnalytics             
Script     1.0.0      Az.Support                     
Script     1.0.4      Az.TrafficManager              
Script     1.11.0     Az.Websites                    

```

**Comment by ChristopherGLewis** [comment] 2020-12-01 16:41
This looks like it was fixed in the Az 5.0 or 5.1 release.  Az.Resources 3.0.1 does not have this issue.

Thanks!

**Comment by dcaro** [comment] 2020-12-02 00:30
@wembleyford can you also confirm if this has been fixed with Az 5.1?

**Comment by wembleyford** [comment] 2020-12-02 10:17
Unfortunately, I cannot, as the latest avalable version in the MS Hosted pipelines appeares to be 4.7.0. Attempting to select 5.0.0 or 5.1.0 fails with an unknown module version error.

**Comment by SatishBoddu-MSFT** [comment] 2021-10-31 00:08
Hello @wembleyford @dcaro @ChristopherGLewis Apologies for the delayed response. I see that this issue is opened a long time ago and no further activity had taken place. So wanted to check if you are still looking for assistance on this query? Please let us know.

**Closed** 2021-11-21 08:01 UTC
Labels: Service Attention, question, ARM - Templates, customer-reported, needs-author-feedback, no-recent-activity, needs-team-triage
