### ISSUE TITLE
Add All AzureRM aliases by default to any AZ Cmdlets and remove the Enable-AzureRMAlias cmdlet

### ISSUE THREAD

**Issue by kilasuit** [Azure/azure-powershell#8226] opened 2019-01-03 11:53 UTC
`Enable-AzureRMAlias` is IMO a bad implementation idea and should not have been implemented, with my reasons as per below.

Aliases tend to, but do not have to be limited to, enable short hand use of cmdlets like `gps` is an alias of `get-process`, they can also enable use of extended names of a Cmdlet/function by aliasing the longer command name to a shorter command which would not break existing scripts and be a better decision decision going forward

You can actually have multiple aliases defined within a Cmdlet using the following approach 
https://github.com/PowerShell/PowerShell/blob/56569b9315c6f8afa707942c36d9953ca69f2e54/src/Microsoft.PowerShell.Commands.Utility/commands/utility/RemoveAliasCommand.cs#L14 and adding additional Aliases as Required by means like the below

```
[Alias('one','two','three')]
```
This way allows multiple Aliases to be defined and maintained at the source of the cmdlet and that is how it should be developed and maintained going forward IMO

**Comment by markcowl** [comment] 2019-01-04 01:55
@kilasuit Thanks for the good feedback. 

We did consider having the old cmdlet names automatically exported by the modules alongside the new ones.

Here are some reasons why we decided to use a set of cmdlets to manage aliases for compatibility instead.  I've also included some of the reasons why we wanted to make a sweeping cmdlet name change in the first place.

- The primary purpose of the cmdlet name change was to make the discovery and usage of cmdlets simpler for all users.  Doubling the number of cmdlet/alias names exported by each module would IMO make discovery and usage more complex for both new and existing users.

- We had consistent customer feedback over surveys and in-person interviews favoring the shorter cmdlet names over the existing cmdlet names.  We want the default experience for new users to be seeing only the new names.

- The cmdlet noun prefixes were in need of a change for consistency's sake.  The old rule of using 'Azure' for data plane cmdlets and 'AzureRm' for management plane cmdlets was both inconsistently applied and not well understood by customers in any case.  We wanted the default user experience to be only 1 widely used cmdlet prefix, rather than 3.

- In the fullness of time, new versions of the modules may not need to support the old cmdlet names, as their usage goes down.  The deprecation process for a cmdlet [6 months advance notice] is far simpler and easier to understand than deprecating hundreds of aliases.  This is a long in the future consideration, but a consideration nonetheless.

- Exporting the old cmdlet aliases as part of the module manifest presents some acquisition problems with the new module. Install-Module could not be used to install the module without 'AllowClobber', even with the RDFE 'Azure' module because of the clash in cmdlet names.   It would also require explicitly importing modules or using fully qualified cmdlet names when using the old module in side-by-side scenarios.  

Again, thanks for the feedback.

**Comment by kilasuit** [comment] 2019-01-04 03:16
Hi Mark,

Some counter points

>  The primary purpose of the cmdlet name change was to make the discovery and usage of cmdlets simpler for all users. Doubling the number of cmdlet/alias names exported by each module would IMO make discovery and usage more complex for both new and existing users.

I disagree and whilst I personally will always suggest against aliases this is one of the few rare occasions where Aliases make for a semi sensible suggestion to use. The main irk with Aliases that are not defined within the Cmdlet definition is that I cannot get that info from a search of the source code, which is where aliases should be defined, not after the fact and then added as an additional running requirement prior to being able to migrate a script from the AzureRM series of Modules to the Az Modules - A renaming decision that I still semi disagree with but your point below to move from 3 prefixes to 1 makes more sense than anything else I had seen communicated prior. However the rename of the Modules themselves liklely never needed to happen, and it is that rename that causes issues and irritation as you have seen.


>   We had consistent customer feedback over surveys and in-person interviews favoring the shorter cmdlet names over the existing cmdlet names. We want the default experience for new users to be seeing only the new names.

Can you share this feedback openly at all, as it would make interesting reading to me and a number of others in the wider PowerShell EcoSystem - especially as whilst the AzureRM command names are atrociously in some cases there is other work on going in the PowerShell repository that shows promise to make interactive use much much easier in a future version of PowerShell Core with partial cmdlet tab completion results 

>   The cmdlet noun prefixes were in need of a change for consistency's sake. The old rule of using 'Azure' for data plane cmdlets and 'AzureRm' for management plane cmdlets was both inconsistently applied and not well understood by customers in any case. We wanted the default user experience to be only 1 widely used cmdlet prefix, rather than 3.

Arguably the original decision decision was a flawed one, one that I guess at the time made sense, but quickly out grew it making any actual sense. This point does make a lot more sense with where Azure is now, compared, to say, 2015/16 time. 

>  In the fullness of time, new versions of the modules may not need to support the old cmdlet names, as their usage goes down. The deprecation process for a cmdlet [6 months advance notice] is far simpler and easier to understand than deprecating hundreds of aliases. This is a long in the future consideration, but a consideration nonetheless.

Disagree with this point a little, because you will be in time looking to deprecate the `Enable-AzureRMAliases` cmdlet and all the aliases with it, and whilst it may be simpler for you to remove a file for the cmdlet and the list of aliases it includes, I would argue that you could and likely should make a single commit that changes all the current cmdlets that have AzureRM aliases to add the aliases to their resulting definition files that end up creating the compiled cmdlets and then revert that single commit when you want to remove them. This to me feels much cleaner for end users than having an additional cmdlet that they need to run to be able to swap scripts across to the new AZ modules. 

Whether that is feasible or not is something you'd know better than I would as I believe a fair amount of the cmdlets are autogenerated rather than manually created.

>  Exporting the old cmdlet aliases as part of the module manifest presents some acquisition problems with the new module. Install-Module could not be used to install the module without 'AllowClobber', even with the RDFE 'Azure' module because of the clash in cmdlet names. It would also require explicitly importing modules or using fully qualified cmdlet names when using the old module in side-by-side scenarios.

This is in part due to your decision to rename the modules and not sticking to the AzureRM module prefix as under the hood nuget uses the name as a unique identifer, which is semi ridiculous as that doesn't allow modules/packages to survive renames due to things like acquisitions or just product evolution correctly.
It is also in part to PowerShellGet being overly defensively coded, with some other parts relating to other issues being down to other different design decisions in other areas of the wider PowerShell Eco System. 


I still think that having aliases defined anywhere but within the definition of the cmdlet is a bad practice, if aliases need to be defined at all and this is the one of the few areas where I advocate the use of Aliases within a module at all, and as a User, and a Trainer, I will say that this implementation to me seems to cause more issues than it actually fixes, and incorrectly encourages use of aliases where they perhaps weren't needed at all.

A side suggestion would be to ship a set of PSScriptAnalyzer rules with this module that can be used to determine script compatibility between different versions of these modules because that can then be used within automated nightly testing of a repository of a teams scripts for any issues and would flag failures to teams quicker than the `band aid` approach that this approach seems to have the feel of, and whilst it's a working solution (at least in your eyes and many users eyes too I would guess) I cant help but feel that there's a better solution out there like what I've detailed above.

Always happy to discuss further ideas around this

**Comment by markcowl** [comment] 2019-03-08 00:54
@kilasuit 

Sorry it took so long to respond.

We do understand that changes are painful, we do not make changes like this lightly, and it is fair for you to dispute that name changes for modules and cmdlets were necessary / desirable.  

Given that we did make the change, I think the cmdlets to enable and disable aliases are more in line with our goals around simplicity and ease of use than static aliases would be. I agree with you in principle about how cmdlet Aliases should be defined.

I doubt that I can share feedback, unless I can find it in an anonymized form.  We did share some general aggregated survey data on this when we undertook simipification for VM and VMSS cmdlets around 18 months ago, and got more similar feedback after those cmdlets were released.

I think the PSScriptAnalyzer suggestion is a good one - since we have good tools for diffing the PowerShell interface, having a script analyzer script to validate compatibility, a cmdlet that used ScriptAnalyzer to validate compatibility, or a cmdlet that used the built-in language parsing facilities in System.Management.Automation to validate compatibility would make lots of sense in helping people evaluate the cost of upgrading.  We have brought this up with MVPs in the past, with lukewarm results, but it is likely worth evaluating this again.

Thanks for the feedback, and please keep it coming.

**Comment by brendonthiede** [comment] 2019-03-21 11:44
Is there an easy way to toggle the aliases on and off within a single script?

The situation I'm seeing is that the Get-AzureRmWebApp uses older behavior that can't get the Identity, so I'd like to use Get-AzWebApp, but I still would like to use the aliases for some shared scripts that are built for AzureRm 6.12 or 6.13. The only way that I've seen to disable the aliases involves starting a new PowerShell session.

**Comment by ChrisLGardner** [comment] 2019-03-21 13:37
You can use Remove-Item to get rid of an alias you don't like/need, `Remove-Item:\Get-AzureRmWebApp`.

I'm surprised you're seeing a difference in behavior since they'll both be calling exactly the same command (since that's the point of aliases).

Do you have any repro steps?
________________________________

**Comment by maddieclayton** [comment] 2019-03-21 16:28
You can also use the "Disable-AzureRmAlias" which will basically run Remove-Item over all of the aliases that were created (you can scope down using -Module)

**Comment by brendonthiede** [comment] 2019-03-22 01:28
Steps to reproduce would be install Az module on a fresh system and enable aliases:

```
Install-Module -Name Az -AllowClobber
Enable-AzureRmAlias -Scope CurrentUser
```

Now look at the version of a command, such as `Get-AzureRmWebApp`:

```
(Get-Command Get-AzureRmWebApp).Version.ToString()
# 4.2.2
```

Now on a different system with AzureRM installed (in my case, version 6.12.0 on a local build server) and run the same command:

```
(Get-Command Get-AzureRmWebApp).Version.ToString()
# 5.2.0
```

Another example is `Get-AzureRmADServicePrincipal`, where the alias in Az behaves like version 5.5.2 of AzureRm.Resources instead of the current version of 6.7.3, which results in drastically different parameters available to the cmdlet.

I'm currently considering creating my own module with "Aliases" that will translate the subset  of cmdlets that our builds use from AzureRm 6.12.0 that translate to Az PowerShell cmdlets so we can use both at once as we migrate.

**Comment by brendonthiede** [comment] 2019-03-22 15:25
I was confused... Somehow I had AzureRM installed on my system _as well as_ Az. This should have been obvious from the result of `Get-Command`, as it did not show as an alias. I closed all PowerShell Windows, opened an Admin instance, and ran `Uninstall-AzureRm`. After opening a new PowerShell window and enabling aliases, CommandType when calling `Get-Command Get-AzureRmWebApp` is now "Alias". Sorry for any confusion I may have caused others.

In case anyone else finds this in the future, another symptom I found (while both AzureRm and AZ were installed) was that a call to `Get-Command Connect-AzAccount` would return the message:

```
WARNING: AzureRM.Profile already loaded. Az and AzureRM modules cannot be imported in the same session or used in the same script or runbook. If you are running PowerShell in an environment you control you can use the 'Uninstall-AzureRm' cmdlet to remove all AzureRm modules from your machine. If you are running in Azure Automation, take care that none of your runbooks import both Az and AzureRM modules. More information can be found here: https://aka.ms/azps-migration-guide.
```

Which describes both the problem and the solution, but I ignored it...

**Comment by markcowl** [comment] 2019-05-23 20:19
Closing this issue, the feedback, especially about the importance of good communication and a migration plan have been heard and will be incorporated in our new versions going forward.  Please feel free to open a new issue if you have any further feedback about moving to Az.

**Closed by markcowl** 2019-05-23 20:19 UTC
Labels: Azure PS Team, Investigate :mag:
