### ISSUE TITLE
New-AzureRmADAppCredential throws a generic "Invalid Operation" exception

### ISSUE THREAD

**Issue by mgaufman** [Azure/azure-powershell#4249] opened 2017-07-05 20:50 UTC
### Cmdlet(s)
New-AzureRmADAppCredential

### PowerShell Version
5.1.15063.413

### Module Version
AzureRM.Profile: 3.1.0
AzureRM.Resources: 4.1.0

### OS Version
10.0.15063.413

### Description
New-AzureRmADAppCredential throws a generic "Invalid Operation" exception if executed for an application which already has keys (passwords) created in the portal with non-empty key descriptions.

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction
Create an application through the portal or via a PowerShell script.
Create a key (password) for this application through the portal, setting some non-empty Description.
Execute **New-AzureRmADAppCredential -ApplicationId _ApplicationId_ -Password P@ssw0rd (after logging into Azure)**

**Comment by cormacpayne** [comment] 2017-07-07 18:37
@mgaufman Hey Maxim, would you mind running the cmdlet `Resolve-AzureRmError` after this error and provide us with error details it provides? Would you also run the cmdlet you are having issues with again with `$DebugPreference="Continue"` and provide us the debug output?

**Comment by mgaufman** [comment] 2017-07-07 19:57
[New-AzureRmADAppCredential Transcript.txt](https://github.com/Azure/azure-powershell/files/1132153/New-AzureRmADAppCredential.Transcript.txt)

@cormacpayne Hi Cormac, please find the transcript attached (contains both debug output and ResolveAzureRmError).

**Comment by cormacpayne** [comment] 2017-07-07 20:11
@mgaufman thanks Maxim. As an FYI, I edited your comment above to remove the link provided since it appears it may contain a password (different from the `P@ssw0rd` string you provided in the original description) in the cmdlet calls.

**Comment by markcowl** [comment] 2017-08-08 17:48
@mgaufman are you still seeing this issue?  A redeacted debug and error output would really help to diagnose.

**Comment by mgaufman** [comment] 2017-08-08 17:54
I haven't tried it recently, were there any fixes to this issue?
I have already provided debug and error output, and the issue can be easily reproduced. Do you need any help with this?

**Comment by markcowl** [comment] 2017-08-08 19:42
@mgaufman We need debug output that we could actually pass on to the team that would work on a fix.  If you cna get this, that would be helpful, if not, we can ask them to repro - the case is stronger if we have debug output to share.

**Comment by mgaufman** [comment] 2017-08-08 19:58
@markcowl, Please find attached.
[New-AzureRmADAppCredential.Transcript.txt](https://github.com/Azure/azure-powershell/files/1209377/New-AzureRmADAppCredential.Transcript.txt)

**Comment by markcowl** [comment] 2017-08-24 22:28
@darshanhs90 Can you take a look at the attached transcript and debug this error?  Also, can we throw a better exception in thsi case?

**Comment by darshanhs90** [comment] 2017-09-22 21:40
The fix for this issue has been merged tot he repo

**Comment by darshanhs90** [comment] 2017-09-26 18:33
Closing this as the issue is fixed in the powershell release 4.4.0

**Closed by darshanhs90** 2017-09-26 18:33 UTC
Labels: ResourceAuthorization
