### ISSUE TITLE
Enable-AzCdnCustomDomainHttps: Add Key Vault certificate import

### ISSUE THREAD

**Issue by shibayan** [Azure/azure-powershell#10839] opened 2020-01-06 18:20 UTC
## Description of the new feature

The current version of the cmdlet is missing the key vault certificate import function. Azure CDN from Microsoft and Verizon supports Key Vault, so it needs to support cmdlets.

https://docs.microsoft.com/en-us/azure/cdn/cdn-custom-ssl?tabs=option-2-enable-https-with-your-own-certificate

Front Door's similar cmdlet is supported with Key Vault certificate.

## Proposed implementation details (optional)

Ideally the same implementation as the Front Door cmdlets.

https://docs.microsoft.com/en-us/powershell/module/az.frontdoor/enable-azfrontdoorcustomdomainhttps?view=azps-3.2.0

**Comment by dingmeng-xue** [comment] 2020-01-07 11:38
According to FrontDoor cmdlet, it requires additional 2 parameters VaultId and SecretName.

**Comment by lsmith130** [comment] 2020-01-29 23:57
Closing as a duplicate of #8930

**Closed by lsmith130** 2020-01-29 23:57 UTC
Labels: CDN, Feature Request, Service Attention, customer-reported

**Comment by timmkrause** [comment] 2021-04-28 07:13
Nearly 1.5 years and no progress on this, Azure CLI does support it...
Unfortunately Azure CLI and PowerShell Az modules cannot be used side by side in an ARM template as well (`Microsoft.Resources/deploymentScripts`) where it could potentially be combined...

So we really have to get bare bones and use the REST API.

This yak shaving is really a pain...
