### ISSUE TITLE
Adding an API to an API Management Service via Backend ID

### ISSUE THREAD

**Issue by tcsdmaic** [Azure/azure-powershell#10460] opened 2019-11-01 20:45 UTC
## Description of the new feature
When I manually add an API to my API Management Service (APIMS), I click "Add API", go to "API App", and select an existing web application from the dropdown.  Adding an API this way automatically adds the operations to that API, adds the web application as a backend to that APIMS, and sets that as the backend for that API in the policies.

But when I want to add an API via a powershell script, it can only be done via Service URL (the URL of the web application), and doing that does not automatically do any of those things.  So I have to make sure I also add the web application as a backend to that APIMS, add the operations for that API, and set the policy for that API that specifies the application as its backend.

It would be great if instead I could simply add the web application as a backend to the APIMS, then add the API via the Backend ID, where doing so would automatically set that application as the API's backend and add the operations.

## Proposed implementation details (optional)
So maybe an overload for New-AzApiManagementApi would be something like this:
New-AzApiManagementApi
   -Context `<PsApiManagementContext>`
   -Name `<String>`
   -BackendId `<String>`
   -Path `<String>`
   -Protocols `<PsApiManagementSchema[]>`
(with the other optional parameters)

Example:
$apimsContext = New-AzApiManagementContext -ResourceGroupName "MyRG" -ServiceName "MyAPIMS"
$WebApp = New-AzApiManagementBackend -Context $apimsContext -Protocol "http" -Url "[web app's URL]"
New-AzApiManagementApi -Context $apimsContext -Name "MyAPI" -BackendId $WebApp.BackendId -Path "myapipath" -Protocols "Https"

And just by doing that, then you would see in the API under that APIMS, all the operations are there, and the inbound policy includes
`<set-backend-service id="[some name]" backend-id="[$WebApp.BackendId]" />`

**Comment by lilyjma** [comment] 2020-08-27 19:44
@tcsdmaic, are you still experiencing this problem?

**Comment by DSpirit** [comment] 2021-09-17 14:52
It's still not possible to create an API with an attached backend. Any news here?
Another thing that needs to be mentioned, is that the creation of a Backend with an Azure AppService Resource via Powershell is not possible, as the -ResourceId parameter doesn't accept the id but demands an URL.

```New-AzApiManagementBackend -Context $ctx -BackendId $backendId -Protocol http -Url "https://$hostName" -ResourceId $app.Id -Title "FooBaz API"```
    leads to:
`[Code= ValidationError, Message= Value should represent absolute http URL, Target= resourceId]`

**Comment by navba-MSFT** [comment] 2022-02-17 08:48
@tcsdmaic Apologies for the late reply. Did you try the samples mentioned [here](https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/new-azapimanagementapi) ? Could you please use the most recent version of the [Az APIM PS module](https://www.powershellgallery.com/packages/Az.ApiManagement/2.3.1) and let us know if you are still seeing this issue ? Awaiting your reply.

**Comment by DSpirit** [comment] 2022-02-24 15:58
@navba-MSFT this is not a bug, we just want to create API's by using backends via script and there is still no option for it (from: https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/new-azapimanagementapi?view=azps-7.2.0):
```
New-AzApiManagementApi
   -Context <PsApiManagementContext>
   [-ApiId <String>]
   -Name <String>
   [-Description <String>]
   -ServiceUrl <String>
   -Path <String>
   -Protocols <PsApiManagementSchema[]>
   [-AuthorizationServerId <String>]
   [-AuthorizationScope <String>]
   [-OpenIdProviderId <String>]
   [-BearerTokenSendingMethod <String[]>]
   [-SubscriptionKeyHeaderName <String>]
   [-SubscriptionKeyQueryParamName <String>]
   [-ProductIds <String[]>]
   [-SubscriptionRequired]
   [-ApiVersionDescription <String>]
   [-ApiVersionSetId <String>]
   [-ApiVersion <String>]
   [-SourceApiId <String>]
   [-SourceApiRevision <String>]
   [-DefaultProfile <IAzureContextContainer>]
   [<CommonParameters>]
   ```

**Comment by navba-MSFT** [comment] 2022-02-25 03:50
@DSpirit Thanks for your reply. We are looking into this and we will update this thread once we have more details on this. 

@adrianhall Could you please provide an update on this once you get a chance ? Awaiting your reply.

**Comment by adrianhall** [comment] 2022-02-28 20:52
The PowerShell module is a reflection of the REST API.  As such, to add such a support, we would have to add it to the API.  However, we already have a preferred mechanism for importing such APIs - via an OpenAPI definition - you can use OpenAPI 2.x or 3.0 currently.

I've taken this request as a feature request onto our backlog.  When we take a look at features for upcoming releases, we will certainly review this.  However, it's a longer term item, so I'll close this item.

**Closed by adrianhall** 2022-02-28 20:52 UTC
Labels: API Management, feature-request, Service Attention, customer-reported, needs-author-feedback
