### ISSUE TITLE
Your Azure credentials have not been set up or have expired

### ISSUE THREAD

**Issue by AjKundnani** [Azure/azure-powershell#14502] opened 2021-03-10 15:58 UTC
## Description
When I run Connect-AzAccount, it authenticates, gives me some warning regarding tenants and then connects me to first subscription in current tenant.

However the second command I run like Get-AzResourceGroup gives me error 
> Your Azure credentials have not been set up or have expired, please run Connect-AzAccount to set up your Azure credentials.

Have tried **Clear-AzContext -Force** and ensured **Get-AzContextAutoSaveSetting** is disabled both at localmachine and currentuser.

## Steps to reproduce

```powershell
Connect-AzAccount
Get-AzResourceGroup
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.2
PSEdition                      Core
GitCommitId                    7.1.2
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```powershell
File Attached - 
[Module_Output.txt](https://github.com/Azure/azure-powershell/files/6116793/Module_Output.txt)
```

## Debug output

```
File Attached - 
[PowerShell_transcript.AJKUNDNA01.uMmzirIP.20210310202543.txt](https://github.com/Azure/azure-powershell/files/6117152/PowerShell_transcript.AJKUNDNA01.uMmzirIP.20210310202543.txt)

```

## Error output

```
File Attached - 
[PowerShell_transcript.AJKUNDNA01.+U9Wwbq5.20210310212631.txt](https://github.com/Azure/azure-powershell/files/6117172/PowerShell_transcript.AJKUNDNA01.%2BU9Wwbq5.20210310212631.txt)

```

**Comment by AjKundnani** [comment] 2021-03-12 06:23
@erich-wang / @dingmeng-xue - Any updates please, we've some dev efforts pending on this bug

**Comment by AjKundnani** [comment] 2021-03-12 12:47
Quick update, I was able to reproduce this issue on a different VM with different tenant. Any inputs please regarding this issue?

**Comment by erich-wang** [comment] 2021-03-12 13:46
@AjKundnani, based on the debug stream, you're able to get token for first tenant, but has issue for other tenant. Do you still get issue if you specify Connect-AzAccount -TenantId ?

**Comment by AjKundnani** [comment] 2021-03-12 13:51
@erich-wang, thanks for checking in. The issue is within first tenant itself i.e. am trying to get subscriptions/resource group in first tenant selected by Connect-AzAccount by default.

If i use `Connect-AzAccount -SubscriptionId xxx -TenantId xxx `I don't see this issue no, but for dev efforts we need to populate subscription names in drop-down such that users don't have to grab tenantId / subscription Id manually from Portal.

If I use `Connect-AzAccount -TenantId xxx,` it works fine first time i.e. I can see resource groups, but after I run `Get-AzSubscription`, it again tries to enumerate other tenants and then subsequently fails with same error.
**Get-AzResourceGroup: Your Azure credentials have not been set up or have expired, please run Connect-AzAccount to set up your Azure credentials.**

**Comment by erich-wang** [comment] 2021-03-12 14:08
Offline synced with @AjKundnani, it seems one of tenant has special auth requirement, Azure PowerShell should expose warning instead of error if at least one tenant has gotten token successfully.

**Comment by brwilkinson** [comment] 2021-03-13 23:33
I came here to say this same thing.... I finally (after having issues for about 3 weeks, figured out what the repro was).

If i simply do connect-azaccount i get this exception: Exception: Azure.Identity.CredentialUnavailableException (0x80131500)

However if I provide the following it works correctly.

```powershell
Select-AzSubscription -Tenant $AZ.TenantId -SubscriptionId $AZ.ID
```

**Comment by brwilkinson** [comment] 2021-03-14 00:58
Adding some more info on the exception: Exception: Azure.Identity.CredentialUnavailableException (0x80131500): SharedTokenCacheCredential

```powershell
connect-azaccount

WARNING: TenantId '72f988bf-86f1-41af-91ab-2d7cd011db47' contains more than one active subscription. First one will be selected for further use. To select another subscription, use Set-AzContext.
WARNING: Unable to acquire token for tenant '98e9ba89-e1a1-4e38-9007-8bdabc25de1d'

Account               SubscriptionName                     TenantId                             Environment
-------               ----------------                     --------                             -----------
benwilk@microsoft.com Microsoft Azure Internal Consumption 72f988bf-86f1-41af-91ab-2d7cd011db47 AzureCloud


$DebugPreference = 'continue'
get-azvm

DEBUG: 7:49:43 PM - GetAzureVMCommand begin processing with ParameterSet 'DefaultParamSet'.
DEBUG: 7:49:43 PM - using account id 'benwilk@microsoft.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'benwilk@microsoft.com', environment: 'AzureCloud', tenant: '72f988bf-86f1-41af-91ab-2d7cd011db47'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
DEBUG: SharedTokenCacheCredential.GetToken was unable to retrieve an access token. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  Exception: Azure.Identity.CredentialUnavailableException (0x80131500): SharedTokenCacheCredential
authentication unavailable. No accounts were found in the cache.
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
DEBUG: SharedTokenCacheCredential.GetToken was unable to retrieve an access token. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  Exception: Azure.Identity.CredentialUnavailableException (0x80131500): SharedTokenCacheCredential
authentication unavailable. No accounts were found in the cache.
DEBUG: [Common.Authentication]: Received exception SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache., while authenticating.
get-azvm : Your Azure credentials have not been set up or have expired, please run Connect-AzAccount to set up your Azure credentials.
At line:1 char:1
+ get-azvm
+ ~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzVM], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.GetAzureVMCommand

DEBUG: AzureQoSEvent: CommandName - Get-AzVM; IsSuccess - False; Duration - 00:00:00.1194743; Exception - System.ArgumentException: Your Azure credentials have not been set up or have expired, please run Connect-AzAccount to set up your Azure credentials. --->
Azure.Identity.CredentialUnavailableException: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
   at Azure.Identity.SharedTokenCacheCredential.<GetAccountAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Identity.SharedTokenCacheCredential.<GetTokenImplAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
   at Azure.Identity.SharedTokenCacheCredential.<GetTokenImplAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Identity.SharedTokenCacheCredential.<GetTokenAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.PowerShell.Authenticators.MsalAccessToken.<GetAccessTokenAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account, IAzureEnvironment environment, String tenant, SecureString password, String promptBehavior, Action`1 promptAction, IAzureTokenCache tokenCache,
String resourceId)
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.GetServiceClientCredentials(IAzureContext context, String targetEndpoint)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.GetServiceClientCredentials(IAzureContext context, String targetEndpoint)
   at Microsoft.Azure.Commands.Common.Authentication.Factories.ClientFactory.CreateArmClient[TClient](IAzureContext context, String endpoint)
   at Microsoft.Azure.Commands.Compute.ComputeClient..ctor(IAzureContext context)
   at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.get_ComputeClient()
   at Microsoft.Azure.Commands.Compute.VirtualMachineBaseCmdlet.get_VirtualMachineClient()
   at Microsoft.Azure.Commands.Compute.GetAzureVMCommand.<ExecuteCmdlet>b__30_0()
   at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 7:49:44 PM - GetAzureVMCommand end processing
```

Here is the comparison.

```powershell
$DebugPreference = 'silentlycontinue'
Connect-AzAccount -TenantId $AZ.TenantId -SubscriptionId $AZ.ID

Account               SubscriptionName                     TenantId                             Environment
-------               ----------------                     --------                             -----------
benwilk@microsoft.com Microsoft Azure Internal Consumption 72f988bf-86f1-41af-91ab-2d7cd011db47 AzureCloud


get-azvm

ResourceGroupName                     Name  Location          VmSize  OsType                      NIC ProvisioningState Zone
-----------------                     ----  --------          ------  ------                      --- ----------------- ----
ACU1-BRW-AOA-RG-P0 ACU1-BRW-AOA-P0-vmDNS01 centralus Standard_D2s_v3 Windows ACU1-BRW-AOA-P0-nicDNS01         Succeeded    1
ACU1-BRW-AOA-RG-P0 ACU1-BRW-AOA-P0-vmDNS02 centralus Standard_D2s_v3 Windows ACU1-BRW-AOA-P0-nicDNS02         Succeeded    2
```

**Comment by erich-wang** [comment] 2021-03-17 08:09
Somehow could not reproduce the issue, online synced with @brwilkinson, Ben will help to reproduce this issue.

**Comment by brwilkinson** [comment] 2021-03-26 06:09
Adding this other issue here as well, it's very similar however this is using a **User Assigned managed Identity** that can no longer get the context.


![image](https://user-images.githubusercontent.com/3605266/112589801-f5148f00-8dbe-11eb-8508-c51a4404c84b.png)


```powershell

gmo

ModuleType Version PreRelease Name ExportedCommands
---------- ------- ---------- ---- ----------------
Script 2.2.6 Az.Accounts {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script 4.5.0 Az.Network {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplicationGatew…
Manifest 7.0.0.0 Microsoft.PowerShell.Management {Add-Content, Clear-Content, Clear-Item, Clear-ItemProperty…}
Manifest 7.0.0.0 Microsoft.PowerShell.Utility {Add-Member, Add-Type, Clear-Variable, Compare-Object…}
Script 2.0.2 PSReadLine {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandl…

```

```powershell

PS /> $DebugPreference = 'continue'
PS /> login-azaccount -Identity
DEBUG: 5:46:22 AM - ConnectAzureRmAccountCommand begin processing with ParameterSet 'ManagedServiceLogin'.
DEBUG: 5:46:22 AM - Autosave setting from startup session: 'CurrentUser'
DEBUG: 5:46:22 AM - No autosave setting detected in environment variable 'AzContextAutoSave'.
DEBUG: 5:46:22 AM - Using Autosave scope 'CurrentUser'
Connect-AzAccount: The default context can no longer be found; please run 'Get-AzContext -ListAvailable' to see all available contexts, 'Select-AzContext' to select a new default context, or 'Connect-AzAccount' to login with a new account.
DEBUG: AzureQoSEvent: CommandName - Connect-AzAccount; IsSuccess - False; Duration - 00:00:00.0279754; Exception - System.Management.Automation.PSInvalidOperationException: The default context can no longer be found; please run 'Get-AzContext -ListAvailable' to see all available contexts,'Select-AzContext' to select a new default context, or 'Connect-AzAccount' to login with a new account.
at Microsoft.Azure.Commands.Common.Authentication.Models.AzureRmProfile.get_DefaultContext()
at Microsoft.Azure.Commands.Common.Authentication.ResourceManager.AzureRmAutosaveProfile.get_DefaultContext()
at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient..ctor(IProfileOperations profile)
at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)
at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)
at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()
at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 5:46:22 AM - ConnectAzureRmAccountCommand end processing.

```

```powershell

 get-azcontext -ListAvailable

Name Account SubscriptionName Environment TenantId
---- ------- ---------------- ----------- --------
MSFT BENWILK AIRS (b8f402aa-20f7-4888-b… MSI@50342 MSFT BENWILK AIRS AzureCloud 72f988bf-86f1-41af-91ab-…
DEBUG: 5:50:15 AM - GetAzureRMContextCommand end processing.

```

```powershell


 get-azcontext -ListAvailable | select *

Name : MSFT BENWILK AIRS (b8f402aa-20f7-4888-b45c-3cf086dad9c3) - 72f988bf-86f1-41af-91ab-2d7cd011db47 - MSI@50342
Account : MSI@50342
Environment : AzureCloud
Subscription : b8f402aa-20f7-4888-b45c-3cf086dad9c3
Tenant : 72f988bf-86f1-41af-91ab-2d7cd011db47
TokenCache :
VersionProfile :
ExtendedProperties : {}

DEBUG: 5:52:00 AM - GetAzureRMContextCommand end processing.
```

```powershell

login-azaccount -Identity -Tenant 72f988bf-86f1-41af-91ab-2d7cd011db47 -Subscription b8f402aa-20f7-4888-b45c-3cf086dad9c3 -AccountId 31fc64df-7a33-4ac5-b39d-31f0081487f3


DEBUG: 5:56:03 AM - ConnectAzureRmAccountCommand begin processing with ParameterSet 'ManagedServiceLogin'.
DEBUG: 5:56:03 AM - Autosave setting from startup session: 'CurrentUser'
DEBUG: 5:56:03 AM - No autosave setting detected in environment variable 'AzContextAutoSave'.
DEBUG: 5:56:03 AM - Using Autosave scope 'CurrentUser'
Connect-AzAccount: The default context can no longer be found; please run 'Get-AzContext -ListAvailable' to see all available contexts, 'Select-AzContext' to select a new default context, or 'Connect-AzAccount' to login with a new account.
DEBUG: AzureQoSEvent: CommandName - Connect-AzAccount; IsSuccess - False; Duration - 00:00:00.0269346; Exception - System.Management.Automation.PSInvalidOperationException: The default context can no longer be found; please run 'Get-AzContext -ListAvailable' to see all available contexts,'Select-AzContext' to select a new default context, or 'Connect-AzAccount' to login with a new account.
at Microsoft.Azure.Commands.Common.Authentication.Models.AzureRmProfile.get_DefaultContext()
at Microsoft.Azure.Commands.Common.Authentication.ResourceManager.AzureRmAutosaveProfile.get_DefaultContext()
at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient..ctor(IProfileOperations profile)
at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)
at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)
at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()
at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 5:56:03 AM - ConnectAzureRmAccountCommand end processing.
```

```powershell
Get-AzNetworkInterface
Get-AzNetworkInterface: The default context can no longer be found; please run 'Get-AzContext -ListAvailable' to see all available contexts, 'Select-AzContext' to select a new default context, or 'Connect-AzAccount' to login with a new account.
```

**Comment by clarkezone** [comment] 2021-04-08 19:29
I'm also having this issue but the workaround to supply sub ID and tenent ID isn't working for me

**Comment by brwilkinson** [comment] 2021-04-08 19:33
Thanks @clarkezone ... can you please keep the logs from $home\.Azure\ErrorRecords

There should be the exception in there as well, if you are able to share it ?

something like these

![image](https://user-images.githubusercontent.com/3605266/114085715-90e5d680-9866-11eb-9ed8-41a9ff55c3eb.png)

**Comment by erich-wang** [comment] 2021-04-20 05:30
@AjKundnani, after further investigation, we found the issue happens because your account is disabled in one of tenant, and token is deleted because of  AzureAD/microsoft-authentication-library-for-dotnet#2535. 

You may use work around below:

```powershell
Connect-AzAccount -Tenant 'tenant id in which your account is active'

$Tenants = Get-AzTenant

foreach ($Tenant in $Tenants) {

    if ($Tenant.TenantID -ne 'tenant id in which your account is disabled') { #

        Get-AzSubscription -TenantId $Tenant.TenantId

    }    

}
```

**Comment by erich-wang** [comment] 2021-04-20 05:31
Close this PR as we're using https://github.com/Azure/azure-powershell/issues/14723 to track the release.

**Closed** 2021-04-20 05:32 UTC
Labels: Authentication, customer-reported, feature-request
