### ISSUE TITLE
Enable a way to get an access token for an authenticated account

### ISSUE THREAD

**Issue by tillig** [Azure/azure-powershell#2494] opened 2016-06-22 16:03 UTC
I believe I'm running into the same (or similar) issue as seen in #1164.

I'm trying to automate the use of Azure Key Vault keys through PowerShell but there aren't currently cmdlets for encrypting/decrypting values. I can call [the REST API operations](https://msdn.microsoft.com/en-us/library/dn878060.aspx) but I need an access token. Given the user is already authenticated, re-authenticating just for that seems like an added unnecessary interaction.

I looked at the commands available for `Invoke-AzureRmResourceAction` but there is no command for encrypting or decrypting using Key Vault.

I also noticed that the `Account.AccessToken` is null when I do `Get-AzureRmContext` so I can't get the token from there, either.

Having a generic `Invoke-AzureRestMethod` as suggested in #1164 would get me around the challenge of not having PowerShell cmdlets for all the operations - I could write them myself.

**Comment by markcowl** [comment] 2016-06-22 19:46
Closing as duplicate of #1164

**Comment by tillig** [comment] 2016-06-22 19:50
Are you planning on re-opening #1164? The last note in there indicates that a new issue should be filed if the challenge comes up again, which is why I opened what's effectively a duplicate.

If not, is there a workaround? Or was it decided this isn't an interesting scenario to support?

**Comment by markcowl** [comment] 2016-06-24 00:22
@tillig That's what I get for not rereading the old issue

**Comment by jnxxx** [comment] 2016-07-14 13:15
I would like to be able to obtain an access token for "graph.microsoft.com", then then make rest calls to it.
Purpose is to read all application info, including key expiration date and owner which is not returned by Get-AzureRmADApplication.

**Comment by markcowl** [comment] 2016-08-08 18:22
@tillig @jnxxx  If you need access in the same AppDomain (read PowerShell session) then you can use TokenCache.DefaultShared which will contain the tokens you need.  If you need access in a different AppDomain, then you can use TokenCahce.Deserialize with the data from PowerShell's TokenCahce, which you can get this way:

```PowerShell
$cache = [Microsoft.WindowsAzure.Commands.Common.AzureRMProfileProvider]::Instance.Profile.Context.TokenCache
```

**Comment by tillig** [comment] 2016-08-08 18:35
So, to verify, I'd be looking at a workaround like this?

``` powershell
$tenantId = (Get-AzureRmSubscription -SubscriptionId 'subscription-id-guid-here').TenantId
$cache = [Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache]::DefaultShared
$token = $cache.ReadItems() | Where-Object { $_.TenantId -eq $tenantId }
# $token.AccessToken is the token to use for REST ops
```

**Comment by MarcelMeurer** [comment] 2016-08-10 08:33
Hi. 

I found a workarround to get an access token with PowerShell, user name and password: 
https://www.sepago.com/blog/2016/08/09/create-a-bearer-access-token-for-Azure-REST-silent-user-password

**Comment by initparam** [comment] 2016-08-23 18:28
I am using this code to get my token in my scripts, Works really great - i use it With Invoke-RestMethod

`function GetAuthToken {
   param([Parameter(Mandatory=$true)]$ApiEndpointUri, [Parameter(Mandatory=$true)]$AADTenant)
 
   $adal = "${env:ProgramFiles(x86)}\Microsoft SDKs\Azure\PowerShell\ServiceManagement\Azure\Services\" + `
"Microsoft.IdentityModel.Clients.ActiveDirectory.dll"
   $adalforms = "${env:ProgramFiles(x86)}\Microsoft SDKs\Azure\PowerShell\ServiceManagement\Azure\Services\" + `
"Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms.dll"

   [System.Reflection.Assembly]::LoadFrom($adal) | Out-Null
   [System.Reflection.Assembly]::LoadFrom($adalforms) | Out-Null

   $clientId = "1950a258-227b-4e31-a9cf-717495945fc2"
   $redirectUri = "urn:ietf:wg:oauth:2.0:oob"
   $authorityUri = “https://login.windows.net/$aadTenant”

   $authContext = New-Object "Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext" -ArgumentList $authorityUri

   $authResult = $authContext.AcquireToken($ApiEndpointUri, $clientId,$redirectUri, "Auto")
 
return $authResult
} `

it can be used like this, for ex.
(Get-AzureAccount).Tenants[Index of Tenant you want to use]
`$ApiEndpointUri = "https://management.azure.com/"
$token = GetAuthToken -AADTenant (Get-AzureAccount).Tenants[0] -ApiEndpointUri $ApiEndpointUri
`

**Comment by markcowl** [comment] 2016-09-06 06:16
@MarcelMeurer @initparam  In the same appdomain, code like this will automatically use the TokenCache provided by PowerShell, and can use the same tokens, if you use the ClientId for PowerShell, and the appropriate user id and tenantid when retrieving the tokens.  

I would advise calling AcquireTokenSilent for each request - this will just grab the access  token from the cache, or automatically get a new access token using the refresh token in the cache if the token has expired.

@tillig No, more like what @MarcelMeurer is doing.  If you pass the TokenCache in when creating the AuthenticationContext, then, if you use the same values as powershell (client id, user id, tenant id)  you will get the same tokens that powwrshell woudl have.  You do not have direct access to tokens from the cache, which is one of the reasons we don't return them.

**Comment by tillig** [comment] 2016-09-06 15:03
OK, now I'm confused. [Up here](https://github.com/Azure/azure-powershell/issues/2494#issuecomment-238329663) @markcowl you mentioned...

> If you need access in the same AppDomain (read PowerShell session) then you can use `[Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache]::DefaultShared` which will contain the tokens you need.

[My follow-up comment](https://github.com/Azure/azure-powershell/issues/2494#issuecomment-238333651) uses the shared cache, but apparently not in the prescribed way. However, [the example you point to by @MarcelMeurer](https://github.com/Azure/azure-powershell/issues/2494#issuecomment-244859146) just gets a token fresh [using a REST call](https://www.sepago.com/blog/2016/08/09/create-a-bearer-access-token-for-Azure-REST-silent-user-password) - it doesn't use any authentication context or cache or anything.

Perhaps you could provide a short but complete code example explaining what you mean to help disambiguate? If me getting the token out of the token cache isn't correct, how do you correctly use the cache?

**Comment by markcowl** [comment] 2016-09-27 23:57
Sorry, should have said @initparam is doing.  When initializing the AuthenticationContext, you can pass in a token cache, or it will automatically use the DefaultSHared TokenCache in the current AppDomain.

**Comment by robdmoore** [comment] 2017-03-12 07:07
The following worked for me:

```powershell
function Get-AccessToken($tenantId) {
    $cache = [Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache]::DefaultShared
    $cacheItem = $cache.ReadItems() | Where-Object { $_.TenantId -eq $tenantId } | Select-Object -First 1
    return $cacheItem.AccessToken
}
```

Main issue I have is that I can't seem to use that token for a call to the Azure AD Graph API unless Iset the version to `1.42-previewInternal`, but there is a bug in that version of the API if you use a service principal :P

**Comment by pburkholder** [comment] 2017-04-21 17:23
Just to be explicit for the noob, here's how to get a token to make a call to list all the resourceGroups (you'd normally use `Get-AzureRMResourceGroup`, but just showing a simple example in this case:

```ps1

Function Get-AccessToken($tenantId) {
    $cache = [Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache]::DefaultShared
    $cacheItem = $cache.ReadItems() | Where-Object { $_.TenantId -eq $tenantId } | Select-Object -First 1
    return $cacheItem.AccessToken
}

$tentantID = (Get-AzureRmSubscription -SubscriptionName Dev).tenantID
$SubscriptionID = (Get-AzureRmSubscription -SubscriptionName Dev).SubscriptionId
$token = Get-AccessToken $tentantID

$requestHeader = @{
  "Authorization" = "Bearer " + $token
  "Content-Type" = "application/json"
}

$ApiEndpoint = 'management.usgovcloudapi.net'
$Uri = "https://$ApiEndpoint/subscriptions/$SubscriptionID/resourceGroups?api-version=2016-09-01"
$Result = (Invoke-RestMethod -Method Get -Headers $requestheader -Uri $Uri
```

**Comment by jimoneil** [comment] 2017-06-03 01:25
@pburkholder @markcowl How does the above respond when the access token expires? With AcquireTokenSilent I'd a new token behind the scenes, but I cannot determine how to access the AuthenticationContext of the already authenticated session in order to make the call to AcquireTokenSilent.

**Comment by pauldalyii** [comment] 2017-08-09 22:12
For some reason, I was not able to obtain an access token by using:
> $cache = [Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache]::DefaultShared

I was able to get it by doing this:
```
Add-AzureRmAccount
$context = Get-AzureRmContext
$cache = $context.TokenCache
$cacheItem.AccessToken
```

However, I am trying to use the token to authenticate with the AzureAD PowerShell module's [Connect-AzureAD](https://docs.microsoft.com/en-us/powershell/module/azuread/connect-azuread?view=azureadps-2.0) cmdlet:
`Connect-AzureAD -AadAccessToken $cacheItem.AccessToken -AccountId "<account-id>" -TenantId $tenantId`

At first, this appears to work because the method returns without error, but when I make a subsequent call to another AzureAD cmdlet to verify that I've successfully authenticated:
`Get-AzureADTenantDetail`

I get the following error:
> Get-AzureADTenantDetail : Error occurred while executing GetTenantDetails 
> Code: Authentication_ExpiredToken
> Message: Your access token has expired. Please renew it before submitting the request.

I realize this may be something I need to raise with the AzureAD PowerShell module team, but wanted to verify with someone here that I haven't gone astray by switching from:
> $cache = [Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache]::DefaultShared

to

> $context = Get-AzureRmContext
> $cache = $context.TokenCache

Are the tokens between the AzureRM and AzureAD modules compatible?

**Comment by 4c74356b41** [comment] 2017-08-10 12:01
@pauldalyii they shouldn't be because you are authenticating to a completely different endpoint. That being said, I would love so see a way to use AzureRM session to auth to AzureAD. Anyone?

**Comment by pauldalyii** [comment] 2017-08-25 16:50
Sharing sessions would be awesome, but ultimately, I'd just like the AzureAD module to merge with AzureRm.  There's a weird overlap of AD features and the AD module is much further ahead.

Until that day comes, I'd like the Azure PowerShell task in VSTS to load both the AzureRm and AzureAD modules, not just AzureRM.  I've got another issue regarding this here:

[https://github.com/Microsoft/vsts-tasks/issues/4830](https://github.com/Microsoft/vsts-tasks/issues/4830)

**Comment by mikeblakeuk** [comment] 2017-11-28 19:08
Has anyone read a token with c#.
So, login to powershell
Save azure RM context
Run an exe to read the json context and get a bearer token within c#
Call azure APIs

**Comment by maddieclayton** [comment] 2017-12-05 23:04
Closing in favor of https://github.com/Azure/azure-powershell/issues/3806

**Closed by maddieclayton** 2017-12-05 23:04 UTC
Labels: Azure PS Team

**Comment by bretthackermsft** [comment] 2018-03-07 08:06
Although this is closed, @pauldalyii got very close. When I played with this, I noticed a collection of tokens. All but one had a resource property pointing to management.core.windows.net. But one of them was pointing to graph.windows.net. That token, it turns out, works great.

```powershell
$context = Get-AzureRmContext
$cache = $context.TokenCache
$cacheItem = $cache.ReadItems()

$token = ($cacheItem | where { $_.Resource -eq "https://graph.windows.net/" }).accessToken

$aad = Connect-AzureAD -AadAccessToken $token -AccountId $context.Account.Id -TenantId $context.Tenant.Id

#test
Get-AzureADApplication
```

**Comment by 4c74356b41** [comment] 2018-03-07 17:31
this is gold

**Comment by LockTar** [comment] 2018-05-02 08:07
@bretthackermsft Nice code, my token cache was only filled when I first tried to get something via the RM commands like `Get-AzureRmADApplication`. Only strange enough the right permission aren't in the token. So managing AD groups doesn't work... 
I always get the error _Insufficient privileges to complete the operation_.

    $TenantId = ""
    $ApplicationId = ""
    $ServicePrincipalKey = ConvertTo-SecureString -String "" -AsPlainText -Force
    $AzureADCred = New-Object System.Management.Automation.PSCredential($ApplicationId, $ServicePrincipalKey)
    Add-AzureRmAccount -ServicePrincipal -Credential $AzureADCred -TenantId $TenantId
    Get-AzureRmADApplication -ApplicationId $ApplicationId -Debug
    
    $groupName = "Test"
    Get-AzureRmADGroup -SearchString $groupName
    
    $context = Get-AzureRmContext
    $cache = $context.TokenCache
    $cacheItem = $cache.ReadItems()
    
    $token = ($cacheItem | where { $_.Resource -eq "https://graph.windows.net/" }).accessToken
    
    Write-Output "AccountId=$($context.Account.Id)"
    Write-Output $token
    
    $aad = Connect-AzureAD -AadAccessToken $token -AccountId $context.Account.Id -TenantId $context.Tenant.Id
    
    #test
    #$group = Get-AzureADGroup -SearchString $groupName -Debug
    Get-AzureADApplication
    #Get-AzureRmADApplication -ApplicationId $ApplicationId

**Comment by bretthackermsft** [comment] 2018-05-02 19:30
Also, I just realized you are logging in with an SP. The SP doesn't have any user rights so can't ask for things you as a user can. I was using this to login to ARM as myself in PSH, then use that token to connect as myself to AzureAD without having to go through the dance again.

**Comment by mganeshphani** [comment] 2018-07-13 23:14
I have a multi-tenant accounts in azure.. one with my employer and one with my client.. the code below, would lead to multiple entries in this case.. hence it would be better to put in multiple conditions in that where clause 
$token = ($cacheItem | where { $_.Resource -eq "https://graph.windows.net/" }).accessToken

**Comment by LockTar** [comment] 2018-08-14 18:56
@bretthackermsft 
Today, I needed this again (login to AzureAD with sp and key) and I found multiple solid solutions for this. See in example my blogpost: https://www.locktar.nl/programming/powershell/connect-to-azuread-with-service-principal/

You can also use my other post for [using AzureAD cmdlets in a VSTS extension](https://www.locktar.nl/programming/powershell/use-azuread-powershell-cmdlets-on-vsts-agent).

**Comment by brandonh-msft** [comment] 2019-07-23 20:47
Nothing in this thread helps for getting access tokens to **other resources**, unfortunately, [like the Kusto API](https://docs.microsoft.com/en-us/azure/kusto/api/rest/authentication), for instance.
This appears to be well taken care of by the `--resource` flag on the `az rest` CLI command, but nothing equivalent in AzPosh.

**Comment by reecebradley** [comment] 2019-09-06 17:24
I'd like to see the `az rest` show up in AzPosh to help bridge the gap for the time being.
