### ISSUE TITLE
Get-AzureRmContext : Could not load file or assembly 'System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by EricBourland** [Azure/azure-powershell#7400] opened 2018-09-26 23:20 UTC
### Description

Running Get-AzureRmContext in the same working directory as Microsoft.Rest.ClientRuntime.dll throws an error:

Get-AzureRmContext : Could not load file or assembly 'System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

### Script/Steps for Reproduction
cd into a directory containing Microsoft.Rest.ClientRuntime.dll
Get-AzureRmContext

### Module Version

6.9.0

### Environment Data

Name                           Value
----                           -----
PSVersion                      5.1.14409.1012
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1012
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Debug Output

```
DEBUG: 7:20:27 PM - GetAzureRMContextCommand begin processing with ParameterSet 'GetSingleContext'.
Get-AzureRmContext : Could not load file or assembly 'System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
At line:1 char:1
+ Get-AzureRmContext
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureRmContext], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.Azure.Commands.Profile.GetAzureRMContextCommand
```

**Comment by cormacpayne** [comment] 2018-09-27 16:08
@EricBourland would you mind providing the full list of `AzureRM` modules you have installed on your machine? You can get this information by running `Get-Module -Name AzureRM* -ListAvailable`

**Comment by EricBourland** [comment] 2018-10-01 01:33
ModuleType Version    Name                               
---------- -------    ----                               
Script     6.3.0      AzureRM                            
Script     0.6.8      AzureRM.AnalysisServices           
Script     6.1.0      AzureRM.ApiManagement              
Script     0.1.4      AzureRM.ApplicationInsights        
Script     5.0.0      AzureRM.Automation                 
Script     4.0.5      AzureRM.Backup                     
Script     4.1.0      AzureRM.Batch                      
Script     0.14.2     AzureRM.Billing                    
Script     5.0.0      AzureRM.Cdn                        
Script     0.9.5      AzureRM.CognitiveServices          
Script     5.1.1      AzureRM.Compute                    
Script     0.3.3      AzureRM.Consumption                
Script     0.2.6      AzureRM.ContainerInstance          
Script     1.0.5      AzureRM.ContainerRegistry          
Script     5.0.0      AzureRM.DataFactories              
Script     0.5.5      AzureRM.DataFactoryV2              
Script     5.0.0      AzureRM.DataLakeAnalytics          
Script     6.0.1      AzureRM.DataLakeStore              
Script     4.0.5      AzureRM.DevTestLabs                
Script     5.0.0      AzureRM.Dns                        
Script     0.3.4      AzureRM.EventGrid                  
Script     0.6.4      AzureRM.EventHub                   
Script     4.1.3      AzureRM.HDInsight                  
Script     5.0.0      AzureRM.Insights                   
Script     3.1.3      AzureRM.IotHub                     
Script     5.0.2      AzureRM.KeyVault                   
Script     4.0.4      AzureRM.LogicApp                   
Script     0.18.0     AzureRM.MachineLearning            
Script     0.4.3      AzureRM.MachineLearningCompute     
Script     0.2.2      AzureRM.MarketplaceOrdering        
Script     0.10.0     AzureRM.Media                      
Script     6.2.0      AzureRM.Network                    
Script     5.0.0      AzureRM.NotificationHubs           
Script     5.0.1      AzureRM.OperationalInsights        
Script     1.0.1      AzureRM.PolicyInsights             
Script     4.1.5      AzureRM.PowerBIEmbedded            
Script     5.3.0      AzureRM.profile                    
Script     4.1.3      AzureRM.RecoveryServices           
Script     4.2.0      AzureRM.RecoveryServices.Backup    
Script     0.2.5      AzureRM.RecoveryServices.SiteRec...
Script     5.0.0      AzureRM.RedisCache                 
Script     0.3.4      AzureRM.Relay                      
Script     6.1.0      AzureRM.Resources                  
Script     0.16.5     AzureRM.Scheduler                  
Script     0.6.5      AzureRM.ServiceBus                 
Script     0.3.6      AzureRM.ServiceFabric              
Script     4.6.1      AzureRM.Sql                        
Script     5.0.0      AzureRM.Storage                    
Script     4.0.5      AzureRM.StreamAnalytics            
Script     4.0.2      AzureRM.Tags                       
Script     4.0.6      AzureRM.TrafficManager             
Script     4.0.3      AzureRM.UsageAggregates            
Script     5.0.3      AzureRM.Websites

**Comment by cormacpayne** [comment] 2018-10-05 21:17
@EricBourland I'm unable to reproduce this error when running on my machine:

```
PS C:\Program Files\WindowsPowerShell\Modules\AzureRM.Profile\5.6.0> dir


    Directory: C:\Program Files\WindowsPowerShell\Modules\AzureRM.Profile\5.6.0


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        9/17/2018   9:04 AM           7860 AzureRM.Profile.psd1
-a----        9/17/2018   9:04 AM          29862 AzureRM.Profile.psm1
-a----        9/17/2018   9:04 AM          67648 Hyak.Common.dll
-a----        9/17/2018   9:04 AM         150760 Microsoft.ApplicationInsights.dll
-a----        9/17/2018   9:04 AM          89192 Microsoft.Azure.Commands.Common.Aks.dll
-a----        9/17/2018   9:04 AM          90216 Microsoft.Azure.Commands.Common.Authentication.Abstractions.dll
-a----        9/17/2018   9:04 AM         105064 Microsoft.Azure.Commands.Common.Authentication.dll
-a----        9/17/2018   9:04 AM          70760 Microsoft.Azure.Commands.Common.Authentication.ResourceManager.dll
-a----        9/17/2018   9:04 AM         150120 Microsoft.Azure.Commands.Common.Authorization.dll
-a----        9/17/2018   9:04 AM        1416808 Microsoft.Azure.Commands.Common.Compute.dll
-a----        9/17/2018   9:04 AM         240232 Microsoft.Azure.Commands.Common.Graph.RBAC.dll
-a----        9/17/2018   9:04 AM         121960 Microsoft.Azure.Commands.Common.KeyVault.dll
-a----        9/17/2018   9:04 AM        1686120 Microsoft.Azure.Commands.Common.Network.dll
-a----        9/17/2018   9:04 AM         132200 Microsoft.Azure.Commands.Common.Storage.Management.dll
-a----        9/17/2018   9:04 AM        3270248 Microsoft.Azure.Commands.Common.WebSites.dll
-a----        9/17/2018   9:04 AM         139368 Microsoft.Azure.Commands.Profile.dll
-a----        9/17/2018   9:04 AM         510780 Microsoft.Azure.Commands.Profile.dll-Help.xml
-a----        9/17/2018   9:04 AM          24954 Microsoft.Azure.Commands.Profile.format.ps1xml
-a----        9/17/2018   9:04 AM          17233 Microsoft.Azure.Commands.Profile.types.ps1xml
-a----        9/17/2018   9:04 AM         584808 Microsoft.Azure.Commands.ResourceManager.Common.dll
-a----        9/17/2018   9:04 AM          30872 Microsoft.Azure.Common.dll
-a----        9/17/2018   9:04 AM          18072 Microsoft.Azure.Common.NetFramework.dll
-a----        9/17/2018   9:04 AM          13472 Microsoft.Azure.KeyVault.Core.dll
-a----        9/17/2018   9:04 AM         194336 Microsoft.IdentityModel.Clients.ActiveDirectory.dll
-a----        9/17/2018   9:04 AM          52032 Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms.dll
-a----        9/17/2018   9:04 AM          58760 Microsoft.Rest.ClientRuntime.Azure.Authentication.dll
-a----        9/17/2018   9:04 AM          95608 Microsoft.Rest.ClientRuntime.Azure.dll
-a----        9/17/2018   9:04 AM          79224 Microsoft.Rest.ClientRuntime.dll
-a----        9/17/2018   9:04 AM          37104 Microsoft.Threading.Tasks.dll
-a----        9/17/2018   9:04 AM          47424 Microsoft.Threading.Tasks.Extensions.Desktop.dll
-a----        9/17/2018   9:04 AM          31520 Microsoft.Threading.Tasks.Extensions.dll
-a----        9/17/2018   9:04 AM         230504 Microsoft.WindowsAzure.Commands.Common.dll
-a----        9/17/2018   9:04 AM          19560 Microsoft.WindowsAzure.Commands.Common.Storage.dll
-a----        9/17/2018   9:04 AM         107672 Microsoft.WindowsAzure.Management.dll
-a----        9/17/2018   9:04 AM         653824 Newtonsoft.Json.10.dll
-a----        9/17/2018   9:04 AM         513536 Newtonsoft.Json.dll
-a----        9/17/2018   9:04 AM          22224 System.Net.Http.Extensions.dll
-a----        9/17/2018   9:04 AM          21720 System.Net.Http.Primitives.dll


PS C:\Program Files\WindowsPowerShell\Modules\AzureRM.Profile\5.6.0> Get-AzureRmContext


Name             : Node CLI Test (2c224e7e-3ef5-431d-a57b-e71f4662e3a6) - corm@microsoft.com
Account          : corm@microsoft.com
SubscriptionName : Node CLI Test
TenantId         : 72f988bf-86f1-41af-91ab-2d7cd011db47
Environment      : AzureCloud
```

Would you mind mind updating to the latest version of `AzureRM` and validating that you see this error? I would recommend removing all `AzureRM` modules on your machine and validating with a fresh install of `AzureRM`.

**Comment by markcowl** [comment] 2018-10-13 00:05
Closing as no repro - please open a new issue if you are still experiencing this

**Closed by markcowl** 2018-10-13 00:05 UTC
Labels: Azure PS Team :snail:, More Info :label:
