### ISSUE TITLE
Emit status of deletion for Remove-AzureResourceGroup

### ISSUE THREAD

**Issue by clamanna** [Azure/azure-powershell#334] opened 2015-04-14 09:30 UTC
As reported from partners -- currently the Remove-AzureResourceGroup cmdlet is like a block-box where it takes a long time after you hit enter and user does not know anything about the progress details, if it is even doing some work or not.

Depending on the number of resources in the resource group it is taking 2-5 minutes to finish the operation in my experience. It would be very useful if there could be some progress indication in this cmdlet, like “Deleting storage account”, “Deleting virtual IP”, etc.

**Comment by markcowl** [comment] 2016-02-18 22:20
@clamanna does your team have any plan to address this? Do you need any support from us?

**Comment by markcowl** [comment] 2016-03-11 22:43
@vivsriaus Please respond.  If we have plans to fix this, please place this in one of the three milestones.

**Comment by vivsriaus** [comment] 2016-03-11 23:10
Thanks Mark. We haven't planned for this yet in the upcoming release, but we'll add this to our queue. Agree that the experience is less than ideal. cc/ @ravbhatnagar

**Comment by ravbhatnagar** [comment] 2016-04-29 22:16
#1167

**Comment by ravbhatnagar** [comment] 2016-05-06 22:57
Need some work on the server side. Blocked as of now so moving to backlog.

**Comment by ravbhatnagar** [comment] 2016-05-06 22:58
Dupe of 1167 so closing this one.

**Closed by ravbhatnagar** 2016-05-06 22:58 UTC
Labels: ResourceManager
