### ISSUE TITLE
[Az.Tools.Installer] - Update-Module errors when Az modules are installed using Az.Tools.Installer

### ISSUE THREAD

**Issue by MarcoJanse** [Azure/azure-powershell#21262] opened 2023-03-21 09:02 UTC
### Description

When installing or updating the Az modules by using Az.Tools.Installer, I find that the `Update-Module` gives me errors for each installed Az-module with this error: 

```powershell
Install-Package: Unable to find repository 'C:\Users\MarcoJanse\AppData\Local\Temp\d7667bac-2395-418b-a27b-da73c3efc0a1'. Use
Get-PSRepository to see all available repositories.
```

I only have the Powershell gallery installed as repository:

```powershell
Get-PSRepository 

Name                      InstallationPolicy   SourceLocation
----                      ------------------   --------------
PSGallery                 Trusted              https://www.powershellgallery.com/api/v2
```

I have tried uninstalling all Az modules and reinstalling them using `Uninstall-AzModule` and `Install-AzModule` but I keep getting this error when using the Update-Module. The Az modules work fine and can be managed using Az.Tools.Installer, but I have other PS modules installed and this generates a lot of errors when trying to update all modules.

### Issue script & Debug output

```PowerShell
Update-Module
DEBUG: 00:00:00.0002044 Trying provider assembly: C:\program files\windowsapps\microsoft.powershell_7.3.3.0_x64__8wekyb3d8bbwe\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.ArchiverProviders.dll
DEBUG: 00:00:00.0001442 Trying provider assembly: C:\program files\windowsapps\microsoft.powershell_7.3.3.0_x64__8wekyb3d8bbwe\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.NuGetProvider.dll
DEBUG: 00:00:00.0001958 Trying provider assembly: C:\program files\windowsapps\microsoft.powershell_7.3.3.0_x64__8wekyb3d8bbwe\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.MetaProvider.PowerShell.dll
DEBUG: 00:00:00.0001355 Trying provider assembly: C:\program files\windowsapps\microsoft.powershell_7.3.3.0_x64__8wekyb3d8bbwe\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.CoreProviders.dll
DEBUG: 00:00:00.0024610 Attempting loading of assembly: C:\program files\windowsapps\microsoft.powershell_7.3.3.0_x64__8wekyb3d8bbwe\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.MetaProvider.PowerShell.dll
DEBUG: 00:00:00.0025611 Attempting loading of assembly: C:\program files\windowsapps\microsoft.powershell_7.3.3.0_x64__8wekyb3d8bbwe\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.ArchiverProviders.dll
DEBUG: 00:00:00.0026152 Attempting loading of assembly: C:\program files\windowsapps\microsoft.powershell_7.3.3.0_x64__8wekyb3d8bbwe\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.CoreProviders.dll
DEBUG: 00:00:00.0029912 Attempting loading of assembly: C:\program files\windowsapps\microsoft.powershell_7.3.3.0_x64__8wekyb3d8bbwe\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.NuGetProvider.dll
DEBUG: 00:00:00.0337108 Registering providers via metaproviders for assembly Microsoft.PackageManagement.MetaProvider.PowerShell.Internal.PowerShellMetaProvider
DEBUG: 00:00:00.0643090 Initializing provider 'zipfile'
DEBUG: 00:00:00.0644092 Initializing provider 'Bootstrap'
DEBUG: 00:00:00.0646523 Initializing provider 'WebDownloader'
DEBUG: 00:00:00.0646602 Initializing provider 'NuGet'
DEBUG: 00:00:00.0869833 Provider 'zipfile' Initialized
DEBUG: 00:00:00.0871398 Using Archiver Provider zipfile
DEBUG: 00:00:00.1108546 Provider 'WebDownloader' Initialized
DEBUG: 00:00:00.1110298 Calling 'zipfile::GetFeatures'
DEBUG: 00:00:00.1110373 Using Downloader Provider WebDownloader
DEBUG: 00:00:00.1113505 Initialize Bootstrapper
DEBUG: 00:00:00.1118013 Provider 'Bootstrap' Initialized
DEBUG: 00:00:00.1118861 Using Package Provider Bootstrap
DEBUG: 00:00:00.1129981 Calling 'NuGet'::'InitializeProvider'.
DEBUG: 00:00:00.1130562 Provider 'NuGet' Initialized
DEBUG: 00:00:00.1130796 Using Package Provider NuGet
DEBUG: 00:00:00.1134241 SUCCESS provider assembly: C:\program files\windowsapps\microsoft.powershell_7.3.3.0_x64__8wekyb3d8bbwe\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.ArchiverProviders.dll
DEBUG: 00:00:00.1186523 Calling 'WebDownloader::GetFeatures'
DEBUG: 00:00:00.1202019 Calling 'Bootstrap::GetFeatures'
DEBUG: 00:00:00.1202019 Calling 'NuGet'::'GetFeatures'.
DEBUG: 00:00:00.1211480 The provider 'Bootstrap' is imported
DEBUG: 00:00:00.1216078 SUCCESS provider assembly: C:\program files\windowsapps\microsoft.powershell_7.3.3.0_x64__8wekyb3d8bbwe\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.CoreProviders.dll
DEBUG: 00:00:00.1217703 The provider 'NuGet' is imported
DEBUG: 00:00:00.1218464 SUCCESS provider assembly: C:\program files\windowsapps\microsoft.powershell_7.3.3.0_x64__8wekyb3d8bbwe\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.NuGetProvider.dll
DEBUG: 00:00:00.1263840 Trying to register metaprovider
DEBUG: 00:00:00.1297510 Initializing PowerShell MetaProvider
DEBUG: 00:00:00.3419211 Attempting to load PowerShell Provider Module [C:\program files\windowsapps\microsoft.powershell_7.3.3.0_x64__8wekyb3d8bbwe\Modules\PowerShellGet\PSModule.psm1]
DEBUG: 00:00:00.4488446 Loaded PowerShell package provider: '[C:\program files\windowsapps\microsoft.powershell_7.3.3.0_x64__8wekyb3d8bbwe\Modules\PowerShellGet\PSModule.psm1]'.
DEBUG: 00:00:00.4536266 Loaded PowerShell Provider: PowerShellGet
DEBUG: 00:00:00.4552108 Initializing provider 'PowerShellGet'
DEBUG: 00:00:00.4592442 Calling New() : MethodName = 'InitializeProvider'
DEBUG: 00:00:00.4592859 WarningAction: SilentlyContinue
DEBUG: 00:00:00.4593023 ErrorAction: SilentlyContinue
DEBUG: 00:00:00.4626924 INVOKING PowerShell Fn Initialize-Provider with args  that has length 0
DEBUG: 00:00:00.4679861 In PowerShellGet Provider - 'Initialize-Provider'.
DEBUG: 00:00:00.4683703 PowerShell Script 'PSModule' Function 'Initialize-Provider' returns null.
DEBUG: 00:00:00.4773936 Done calling powershell «Initialize-Provider» «PSModule»
DEBUG: 00:00:00.4774605 Provider 'PowerShellGet' Initialized
DEBUG: 00:00:00.4774806 Using Package Provider PowerShellGet
DEBUG: 00:00:00.4839805 Calling New() : MethodName = 'GetFeatures'
DEBUG: 00:00:00.4840324 WarningAction: SilentlyContinue
DEBUG: 00:00:00.4840465 ErrorAction: SilentlyContinue
DEBUG: 00:00:00.4849380 INVOKING PowerShell Fn Get-Feature with args  that has length 0
DEBUG: 00:00:00.4872590 In PowerShellGet Provider - 'Get-Feature'.
DEBUG: 00:00:00.4907031 Done calling powershell «Get-Feature» «PSModule»
DEBUG: 00:00:00.4908413 The provider 'PowerShellGet' is imported
DEBUG: 00:00:00.4920153 SUCCESS provider assembly: C:\program files\windowsapps\microsoft.powershell_7.3.3.0_x64__8wekyb3d8bbwe\Modules\PackageManagement\coreclr\netstandard2.0\Microsoft.PackageManagement.MetaProvider.PowerShell.dll
DEBUG: 00:00:00.0000022 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0001729 Name: *
DEBUG: 00:00:00.0001973 WarningAction: SilentlyContinue
DEBUG: 00:00:00.0002097 ErrorAction: SilentlyContinue
DEBUG: 00:00:00.0011136 INVOKING PowerShell Fn Get-DynamicOptions with args Provider that has length 1
DEBUG: 00:00:00.0057810 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0113984 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0185141 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0185454 Name: *
DEBUG: 00:00:00.0185568 WarningAction: SilentlyContinue
DEBUG: 00:00:00.0185664 ErrorAction: SilentlyContinue
DEBUG: 00:00:00.0191858 INVOKING PowerShell Fn Get-DynamicOptions with args Install that has length 1
DEBUG: 00:00:00.0196690 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0246095 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0489315 Calling New() : MethodName = 'GetInstalledPackages'
DEBUG: 00:00:00.0495984 ErrorAction: SilentlyContinue
DEBUG: 00:00:00.0500453 ProviderName: PowerShellGet
DEBUG: 00:00:00.0504692 Type: Module
DEBUG: 00:00:00.0508670 MessageResolver: Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:00.0512875 WarningAction: SilentlyContinue
DEBUG: 00:00:00.0516310 Name: *
DEBUG: 00:00:00.0528885 INVOKING PowerShell Fn Get-InstalledPackage with args *, , ,  that has length 4
DEBUG: 00:00:00.0566036 In PowerShellGet Provider - 'Get-InstalledPackage'.
DEBUG: 00:00:00.0577867 OPTION: ErrorAction => SilentlyContinue
DEBUG: 00:00:00.0581197 OPTION: ProviderName => PowerShellGet
DEBUG: 00:00:00.0584168 OPTION: Type => Module
DEBUG: 00:00:00.0587932 OPTION: MessageResolver => Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:00.0592563 OPTION: WarningAction => SilentlyContinue
DEBUG: 00:00:00.0597303 OPTION: Name => *
DEBUG: 00:00:00.9251794 Done calling powershell «Get-InstalledPackage» «PSModule»
DEBUG: Get-InstallationScope: C:\Users\MarcoJanse\OneDrive - companyname\Documents\PowerShell\Modules\Az.Accounts\2.12.1 True False : CurrentUser
DEBUG: 00:00:00.0000014 Calling New() : MethodName = 'ResolvePackageSources'
DEBUG: 00:00:00.0000618 Name: Az.Accounts
DEBUG: 00:00:00.0000774 Source: C:\Users\MarcoJanse\AppData\Local\Temp\d7667bac-2395-418b-a27b-da73c3efc0a1
DEBUG: 00:00:00.0009775 INVOKING PowerShell Fn Resolve-PackageSource with args  that has length 0
DEBUG: 00:00:00.0045798 In PowerShellGet Provider - 'Resolve-PackageSource'.
DEBUG: 00:00:00.0166419 PowerShell Script 'PSModule' Function 'Resolve-PackageSource' returns null.
DEBUG: 00:00:00.0174983 Done calling powershell «Resolve-PackageSource» «PSModule»
Install-Package: Unable to find repository 'C:\Users\MarcoJanse\AppData\Local\Temp\d7667bac-2395-418b-a27b-da73c3efc0a1'. Use
Get-PSRepository to see all available repositories.
DEBUG: 00:00:00.0000021 Calling New() : MethodName = 'ResolvePackageSources'
DEBUG: 00:00:00.0000677 Name: Az.Advisor
DEBUG: 00:00:00.0000961 Source: C:\Users\MarcoJanse\AppData\Local\Temp\d7667bac-2395-418b-a27b-da73c3efc0a1
DEBUG: 00:00:00.0013565 INVOKING PowerShell Fn Resolve-PackageSource with args  that has length 0
DEBUG: 00:00:00.0021276 In PowerShellGet Provider - 'Resolve-PackageSource'.
DEBUG: 00:00:00.0035932 PowerShell Script 'PSModule' Function 'Resolve-PackageSource' returns null.
DEBUG: 00:00:00.0044679 Done calling powershell «Resolve-PackageSource» «PSModule»
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.12.1                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContexΓÇª
Script     0.2.1                 az.tools.Installer                  {Install-AzModule, Uninstall-AzModule, Update-AzMoΓÇª
Script     1.1.0                 Az.Tools.Predictor                  {Disable-AzPredictor, Enable-AzPredictor, Open-AzPΓÇª
```

### Error output

```PowerShell
EBUG: 10:02:05 - ResolveError begin processing with ParameterSet 'LastErrorParameterSet'.
DEBUG: 10:02:05 - using account id ''
DEBUG: 10:02:05 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 2

Message        : Unable to find repository 'C:\Users\MarcoJanse\AppData\Local\Temp\d7667bac-2395-418b-a27b-da73c3efc0a1'. Use Get-PSRepository to see all available repositories.
StackTrace     :
Exception      : System.Exception
InvocationInfo : {Install-Package}
Line           :             $sid = PackageManagement\Install-Package @PSBoundParameters

Position       : At C:\program files\windowsapps\microsoft.powershell_7.3.3.0_x64__8wekyb3d8bbwe\Modules\PowerShellGet\PSModule.psm1:13069 char:20
                 + …           $sid = PackageManagement\Install-Package @PSBoundParameters
                 +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2



DEBUG: 10:02:05 - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.Accounts:2.12.1; CommandName: Resolve-AzError; PSVersion: 7.3.3; IsSuccess: True; Duration: 00:00:00.0182201
DEBUG: 10:02:05 - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 10:02:05 - ResolveError end processing.
```

**Comment by isra-fel** [comment] 2023-03-22 06:50
Thanks for the feedback Marco!
@msJinLei could you look into this issue? It looks to me the temporary repository solution has some compatibility issue with PowerShellGet.

**Comment by msJinLei** [comment] 2023-03-22 07:16
@MarcoJanse
could you double confirm the cmdlet you are using? Update-Module is the cmdlet from PowerShellGet and Update-AzModule is the cmdlet from Az.Tools.installer

**Comment by MarcoJanse** [comment] 2023-03-22 10:24
I'm using `Update-Module` from PowerShellGet to update other modules, and that gives the error on each Az module managed with Az.Tools.Installer.

I hope that clears things up for you

**Comment by msJinLei** [comment] 2023-03-22 17:28
> I'm using `Update-Module` from PowerShellGet to update other modules, and that gives the error on each Az module managed with Az.Tools.Installer.
> 
> I hope that clears things up for you

What is the PowerShellGet version installed?

**Comment by MarcoJanse** [comment] 2023-03-23 13:54
PowerShellGet version is `2.2.5.0`

**Comment by dolauli** [comment] 2023-04-26 11:20
@msJinLei Any update for the issue?

**Comment by msJinLei** [comment] 2023-04-26 14:59
> @msJinLei Any update for the issue?

According to the message from PowerShell team, the issue can be manually fixed by changing the $PowerShellFolder\Modules\Az.Network\$version\PSGetModuleInfo.xml
```
<S N="RepositorySourceLocation">C:\Users\MarcoJanse\AppData\Local\Temp\d7667bac-2395-418b-a27b-da73c3efc0a1</S>
<S N="Repository">AzTempRepo</S>
```
To
```
<S N="RepositorySourceLocation">https://www.powershellgallery.com/api/v2</S>
<S N="Repository">PSGallery</S>
```

But the issue is non-blocking. Even the error is reported, the updating of the other modules won't be affected. If you want to update Az modules, you can use Az.Tools.Installer.

As the module amount involved is too larget, the manual fix is not recommended.
We can try to fix the PSGetModuleInfo.xml programmatically in the next Az.Tools.Installer release

**Comment by isra-fel** [comment] 2023-09-15 02:16
We can replace the metadata (location and repository) with the real repo that we install az modules.

**Comment by msJinLei** [comment] 2023-10-16 13:57
Fix in https://www.powershellgallery.com/packages/Az.Tools.Installer/0.2.3

**Closed by msJinLei** 2023-10-16 13:57 UTC
Labels: Azure PS Team, bug, customer-reported, Az.Tools.Installer, Tracking
