### ISSUE TITLE
Az.DataFactory AccessToken error with MSI json

### ISSUE THREAD

**Issue by plk** [Azure/azure-powershell#13672] opened 2020-12-05 18:34 UTC
## Description

Set-AzDataFactoryV2LinkedService gives spurious AccessToken missing error when creating/updating databricks linked service which is using MSI (no tokens). Presumably this is wrong as no access token is required when using MSI?

## Steps to reproduce
With "C:\test.json" containing the following:

```json
{
    "name": "AzureDatabricks2",
    "properties": {
        "annotations": [],
        "type": "AzureDatabricks",
        "typeProperties": {
            "domain": "https://adb-3580467424468365.5.azuredatabricks.net",
            "authentication": "MSI",
            "workspaceResourceId": "/subscriptions/69407d6c-78a8-4a25-a7cc-e454a28d0a10/resourceGroups/MSBIinfra/providers/Microsoft.Databricks/workspaces/MSBIinfraDEVdb1",
            "newClusterNodeType": "Standard_NC12",
            "newClusterNumOfWorker": "1",
            "newClusterVersion": "5.5.x-gpu-scala2.11"
        }
    },
    "type": "Microsoft.DataFactory/factories/linkedservices"
}

```

```powershell

Set-AzDataFactoryV2LinkedService -ResourceGroupName $RGname -DataFactoryName $ADFname -Name AzureDatabricks2 -DefinitionFile $("C:\test.json")
Set-AzDataFactoryV2LinkedService: 'AccessToken' cannot be null.


```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

## Module versions

```powershell
    Directory: C:\program files\powershell\7\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Manifest   7.0.0.0               CimCmdlets                          Core      {Get-CimAssociatedInstance, Get-CimClas…
Manifest   1.2.5                 Microsoft.PowerShell.Archive        Desk      {Compress-Archive, Expand-Archive}
Manifest   7.0.0.0               Microsoft.PowerShell.Diagnostics    Core      {Get-WinEvent, New-WinEvent, Get-Counte…
Manifest   7.0.0.0               Microsoft.PowerShell.Host           Core      {Start-Transcript, Stop-Transcript}
Manifest   7.0.0.0               Microsoft.PowerShell.Management     Core      {Add-Content, Clear-Content, Get-Clipbo…
Manifest   7.0.0.0               Microsoft.PowerShell.Security       Core      {Get-Acl, Set-Acl, Get-PfxCertificate, …
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        Core      {Export-Alias, Get-Alias, Import-Alias,…
Manifest   7.0.0.0               Microsoft.WSMan.Management          Core      {Disable-WSManCredSSP, Enable-WSManCred…
Script     1.4.7                 PackageManagement                   Desk      {Find-Package, Get-Package, Get-Package…
Script     2.2.5                 PowerShellGet                       Desk      {Find-Command, Find-DSCResource, Find-M…
Script     2.0.5                 PSDesiredStateConfiguration         Core      {Configuration, New-DscChecksum, Get-Ds…
Script     7.0.0.0               PSDiagnostics                       Core      {Disable-PSTrace, Disable-PSWSManCombin…
Script     2.1.0                 PSReadLine                          Desk      {Get-PSReadLineKeyHandler, Set-PSReadLi…
Binary     2.0.3                 ThreadJob                           Desk      Start-ThreadJob

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     5.1.0                 Az                                  Core,Desk
Script     2.2.1                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzCo…
Script     1.1.1                 Az.Advisor                          Core,Desk {Get-AzAdvisorRecommendation, Enable-Az…
Script     2.0.1                 Az.Aks                              Core,Desk {Get-AzAksCluster, New-AzAksCluster, Re…
Script     1.1.4                 Az.AnalysisServices                 Core,Desk {Resume-AzAnalysisServicesServer, Suspe…
Script     2.1.0                 Az.ApiManagement                    Core,Desk {Add-AzApiManagementApiToGateway, Add-A…
Script     1.0.0                 Az.AppConfiguration                 Core,Desk {Get-AzAppConfigurationStore, Get-AzApp…
Script     1.1.0                 Az.ApplicationInsights              Core,Desk {Get-AzApplicationInsights, New-AzAppli…
Script     1.4.0                 Az.Automation                       Core,Desk {Get-AzAutomationHybridWorkerGroup, Rem…
Script     3.1.0                 Az.Batch                            Core,Desk {Remove-AzBatchAccount, Get-AzBatchAcco…
Script     2.0.0                 Az.Billing                          Core,Desk {Get-AzBillingInvoice, Get-AzBillingPer…
Script     1.6.0                 Az.Cdn                              Core,Desk {Get-AzCdnProfile, Get-AzCdnProfileSsoU…
Script     1.8.0                 Az.CognitiveServices                Core,Desk {Get-AzCognitiveServicesAccount, Get-Az…
Script     4.6.0                 Az.Compute                          Core,Desk {Remove-AzAvailabilitySet, Get-AzAvaila…
Script     1.0.3                 Az.ContainerInstance                Core,Desk {New-AzContainerGroup, Get-AzContainerG…
Script     2.0.0                 Az.ContainerRegistry                Core,Desk {New-AzContainerRegistry, Get-AzContain…
Script     1.1.0                 Az.DataBoxEdge                      Core,Desk {Get-AzDataBoxEdgeJob, Get-AzDataBoxEdg…
Script     1.0.1                 Az.Databricks                       Core,Desk {Get-AzDatabricksVNetPeering, Get-AzDat…
Script     1.11.1                Az.DataFactory                      Core,Desk {Set-AzDataFactoryV2, Update-AzDataFact…
Script     1.0.2                 Az.DataLakeAnalytics                Core,Desk {Get-AzDataLakeAnalyticsDataSource, New…
Script     1.3.0                 Az.DataLakeStore                    Core,Desk {Get-AzDataLakeStoreTrustedIdProvider, …
Script     1.0.0                 Az.DataShare                        Core,Desk {New-AzDataShareAccount, Get-AzDataShar…
Script     1.1.0                 Az.DeploymentManager                Core,Desk {Get-AzDeploymentManagerArtifactSource,…
Script     2.0.1                 Az.DesktopVirtualization            Core,Desk {Disconnect-AzWvdUserSession, Expand-Az…
Script     1.0.2                 Az.DevTestLabs                      Core,Desk {Get-AzDtlAllowedVMSizesPolicy, Get-AzD…
Script     1.1.2                 Az.Dns                              Core,Desk {Get-AzDnsRecordSet, New-AzDnsRecordCon…
Script     1.3.0                 Az.EventGrid                        Core,Desk {New-AzEventGridTopic, Get-AzEventGridT…
Script     1.7.1                 Az.EventHub                         Core,Desk {New-AzEventHubNamespace, Get-AzEventHu…
Script     1.6.1                 Az.FrontDoor                        Core,Desk {New-AzFrontDoor, Get-AzFrontDoor, Set-…
Script     2.0.0                 Az.Functions                        Core,Desk {Get-AzFunctionApp, Get-AzFunctionAppAv…
Script     4.1.0                 Az.HDInsight                        Core,Desk {Get-AzHDInsightJob, New-AzHDInsightSqo…
Script     1.1.0                 Az.HealthcareApis                   Core,Desk {New-AzHealthcareApisService, Remove-Az…
Script     2.7.0                 Az.IotHub                           Core,Desk {Add-AzIotHubKey, Get-AzIotHubEventHubC…
Script     3.1.0                 Az.KeyVault                         Core,Desk {Add-AzManagedHsmKey, Get-AzManagedHsmK…
Script     1.0.0                 Az.Kusto                            Core,Desk {Add-AzKustoClusterLanguageExtension, A…
Script     1.4.0                 Az.LogicApp                         Core,Desk {Get-AzIntegrationAccountAgreement, Get…
Script     1.1.3                 Az.MachineLearning                  Core,Desk {Move-AzMlCommitmentAssociation, Get-Az…
Script     1.1.0                 Az.Maintenance                      Core,Desk {Get-AzApplyUpdate, Get-AzConfiguration…
Script     2.0.0                 Az.ManagedServices                  Core,Desk {Get-AzManagedServicesAssignment, New-A…
Script     1.0.2                 Az.MarketplaceOrdering              Core,Desk {Get-AzMarketplaceTerms, Set-AzMarketpl…
Script     1.1.1                 Az.Media                            Core,Desk {Sync-AzMediaServiceStorageKey, Set-AzM…
Script     2.2.0                 Az.Monitor                          Core,Desk {Get-AzMetricDefinition, Get-AzMetric, …
Script     4.3.0                 Az.Network                          Core,Desk {Add-AzApplicationGatewayAuthentication…
Script     1.1.1                 Az.NotificationHubs                 Core,Desk {Get-AzNotificationHub, Get-AzNotificat…
Script     2.3.0                 Az.OperationalInsights              Core,Desk {New-AzOperationalInsightsAzureActivity…
Script     1.3.1                 Az.PolicyInsights                   Core,Desk {Get-AzPolicyEvent, Get-AzPolicyState, …
Script     1.1.2                 Az.PowerBIEmbedded                  Core,Desk {Remove-AzPowerBIWorkspaceCollection, G…
Script     1.0.3                 Az.PrivateDns                       Core,Desk {Get-AzPrivateDnsZone, Remove-AzPrivate…
Script     3.0.1                 Az.RecoveryServices                 Core,Desk {Get-AzRecoveryServicesBackupProperty, …
Script     1.4.0                 Az.RedisCache                       Core,Desk {Remove-AzRedisCachePatchSchedule, New-…
Script     1.0.3                 Az.Relay                            Core,Desk {New-AzRelayNamespace, Get-AzRelayNames…
Script     3.0.1                 Az.Resources                        Core,Desk {Get-AzProviderOperation, Remove-AzRole…
Script     1.4.1                 Az.ServiceBus                       Core,Desk {New-AzServiceBusNamespace, Get-AzServi…
Script     2.2.0                 Az.ServiceFabric                    Core,Desk {Add-AzServiceFabricClientCertificate, …
Script     1.2.0                 Az.SignalR                          Core,Desk {New-AzSignalR, Get-AzSignalR, Get-AzSi…
Script     2.12.0                Az.Sql                              Core,Desk {Get-AzSqlDatabaseTransparentDataEncryp…
Script     1.1.0                 Az.SqlVirtualMachine                Core,Desk {New-AzSqlVM, Get-AzSqlVM, Update-AzSql…
Script     3.0.0                 Az.Storage                          Core,Desk {Get-AzStorageAccount, Get-AzStorageAcc…
Script     1.3.0                 Az.StorageSync                      Core,Desk {Invoke-AzStorageSyncCompatibilityCheck…
Script     1.0.1                 Az.StreamAnalytics                  Core,Desk {Get-AzStreamAnalyticsFunction, Get-AzS…
Script     1.0.0                 Az.Support                          Core,Desk {Get-AzSupportService, Get-AzSupportPro…
Script     0.1.1                 Az.Tools.Installer                  Core,Desk {Install-AzModule, Uninstall-AzModule, …
Script     1.0.4                 Az.TrafficManager                   Core,Desk {Add-AzTrafficManagerCustomHeaderToEndp…
Script     2.1.0                 Az.Websites                         Core,Desk {Get-AzAppServicePlan, Set-AzAppService…
Script     1.0.1                 Microsoft.PowerShell.Operation.Val… Desk      {Get-OperationValidation, Invoke-Operat…
Binary     1.0.840               MicrosoftPowerBIMgmt.Admin          Desk      {Add-PowerBIEncryptionKey, Get-PowerBIE…
Binary     1.0.840               MicrosoftPowerBIMgmt.Capacities     Desk      Get-PowerBICapacity
Binary     1.0.840               MicrosoftPowerBIMgmt.Data           Desk      {Add-PowerBIDataset, Set-PowerBITable, …
Binary     1.0.840               MicrosoftPowerBIMgmt.Profile        Desk      {Connect-PowerBIServiceAccount, Disconn…
Binary     1.0.840               MicrosoftPowerBIMgmt.Reports        Desk      {Get-PowerBIReport, New-PowerBIReport, …
Binary     1.0.840               MicrosoftPowerBIMgmt.Workspaces     Desk      {Get-PowerBIWorkspace, Get-PowerBIWorks…
Binary     1.0.0.1               PackageManagement                   Desk      {Find-Package, Get-Package, Get-Package…
Script     4.10.1                Pester                              Desk      {Describe, Context, It, Should…}
Script     3.4.0                 Pester                              Desk      {Describe, Context, It, Should…}
Script     2.6.4.3               Poshspec                            Desk      {ADGroup, ADOrganizationalUnit, ADUser,…
Script     2.0.0.0               powershell-yaml                     Desk      {ConvertFrom-Yaml, ConvertTo-Yaml}
Script     1.0.0.1               PowerShellGet                       Desk      {Install-Module, Find-Module, Save-Modu…
Script     2.0.0      beta2      PSReadline                          Desk      {Get-PSReadLineKeyHandler, Set-PSReadLi…
Script     21.1.18221            SqlServer                           Desk      {Add-RoleMember, Add-SqlAvailabilityDat…
Script     1.5.9                 WorkplaceCommonFunctions            Desk      {ConvertTo-SRNTAccountOrSID, Get-SRFree…
Script     1.2.5.2               WorkplaceLabels                     Desk      {Get-SRLabel, Remove-SRLabel, Set-SRLab…
Script     1.3.5                 WorkplaceLogging                    Desk      {Get-SRLoggingConfig, Get-SRLogMessageL…
Script     1.2.5                 WorkplaceNotification               Desk      {New-SRNAction, New-SRNAppId, New-SRNAu…
Script     1.0.2                 WorkplacePlatformSecurityLogging    Desk      New-SRPCRAndFirmwareSettings
Script     1.5.3                 WorkplaceSupportToolkit             Desk      {Clear-SRCSCache, Format-SRBootStick, G…
Script     1.6.9                 WorkplaceSyncBuddy                  Desk      {Disable-SRSB, Enable-SRSB, Get-SRSBCSC…
Script     2.0.12                WorkplaceValidation                 Desk      {Invoke-SRValidation, New-SRApplication…

    Directory: C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Manifest   1.0.0.0               AppBackgroundTask                   Core,Desk {Disable-AppBackgroundTaskDiagnosticLog…
Manifest   2.0.1.0               Appx                                Core,Desk {Add-AppxPackage, Get-AppxPackage, Get-…
Script     1.0.0.0               AssignedAccess                      Core,Desk {Clear-AssignedAccess, Get-AssignedAcce…
Manifest   1.0.0.0               BitLocker                           Core,Desk {Unlock-BitLocker, Suspend-BitLocker, R…
Manifest   1.0.0.0               BranchCache                         Core,Desk {Add-BCDataCacheExtension, Clear-BCCach…
Manifest   1.0                   ConfigDefender                      Core,Desk {Get-MpPreference, Set-MpPreference, Ad…
Manifest   1.0                   Defender                            Core,Desk {Get-MpPreference, Set-MpPreference, Ad…
Manifest   1.0.2.0               DeliveryOptimization                Core,Desk {Delete-DeliveryOptimizationCache, Get-…
Manifest   1.0.0.0               DirectAccessClientComponents        Core,Desk {Disable-DAManualEntryPointSelection, E…
Script     3.0                   Dism                                Core,Desk {Add-AppxProvisionedPackage, Add-Window…
Manifest   1.0.0.0               DnsClient                           Core,Desk {Resolve-DnsName, Clear-DnsClientCache,…
Manifest   1.0.0.0               EventTracingManagement              Core,Desk {Start-EtwTraceSession, New-EtwTraceSes…
Script     1.1.0.0               IISAdministration                   Core,Desk
Manifest   2.0.0.0               International                       Core,Desk {Get-WinDefaultInputMethodOverride, Set…
Manifest   3.0.0.0               Microsoft.PowerShell.Diagnostics    Core,Desk {Get-WinEvent, Get-Counter, Import-Coun…
Manifest   1.0.0.0               Microsoft.PowerShell.LocalAccounts  Core,Desk {Add-LocalGroupMember, Disable-LocalUse…
Manifest   3.1.0.0               Microsoft.PowerShell.Management     Core,Desk {Add-Content, Clear-Content, Clear-Item…
Manifest   1.0                   MMAgent                             Core,Desk {Disable-MMAgent, Enable-MMAgent, Set-M…
Manifest   2.0.0.0               NetAdapter                          Core,Desk {Disable-NetAdapter, Disable-NetAdapter…
Manifest   1.0.0.0               NetConnection                       Core,Desk {Get-NetConnectionProfile, Set-NetConne…
Manifest   1.0.0.0               NetEventPacketCapture               Core,Desk {New-NetEventSession, Remove-NetEventSe…
Manifest   2.0.0.0               NetLbfo                             Core,Desk {Add-NetLbfoTeamMember, Add-NetLbfoTeam…
Manifest   1.0.0.0               NetNat                              Core,Desk {Get-NetNat, Get-NetNatExternalAddress,…
Manifest   2.0.0.0               NetQos                              Core,Desk {Get-NetQosPolicy, Set-NetQosPolicy, Re…
Manifest   2.0.0.0               NetSecurity                         Core,Desk {Get-DAPolicyChange, New-NetIPsecAuthPr…
Manifest   1.0.0.0               NetSwitchTeam                       Core,Desk {New-NetSwitchTeam, Remove-NetSwitchTea…
Manifest   1.0.0.0               NetTCPIP                            Core,Desk {Get-NetIPAddress, Get-NetIPInterface, …
Manifest   1.0.0.0               NetworkConnectivityStatus           Core,Desk {Get-DAConnectionStatus, Get-NCSIPolicy…
Manifest   1.0.0.0               NetworkSwitchManager                Core,Desk {Disable-NetworkSwitchEthernetPort, Ena…
Manifest   1.0.0.0               NetworkTransition                   Core,Desk {Add-NetIPHttpsCertBinding, Disable-Net…
Manifest   1.0.0.0               PcsvDevice                          Core,Desk {Get-PcsvDevice, Start-PcsvDevice, Stop…
Manifest   1.0.0.0               PnpDevice                           Core,Desk {Get-PnpDevice, Get-PnpDeviceProperty, …
Manifest   1.1                   PrintManagement                     Core,Desk {Add-Printer, Add-PrinterDriver, Add-Pr…
Binary     1.0.11                ProcessMitigations                  Core,Desk {Get-ProcessMitigation, Set-ProcessMiti…
Manifest   1.0.0.0               ScheduledTasks                      Core,Desk {Get-ScheduledTask, Set-ScheduledTask, …
Manifest   2.0.0.0               SecureBoot                          Core,Desk {Confirm-SecureBootUEFI, Set-SecureBoot…
Manifest   2.0.0.0               SmbShare                            Core,Desk {Get-SmbShare, Remove-SmbShare, Set-Smb…
Manifest   2.0.0.0               SmbWitness                          Core,Desk {Get-SmbWitnessClient, Move-SmbWitnessC…
Manifest   1.0.0.0               StartLayout                         Core,Desk {Export-StartLayout, Import-StartLayout…
Manifest   2.0.0.0               Storage                             Core,Desk {Add-InitiatorIdToMaskingSet, Add-Parti…
Manifest   1.0.0.0               TroubleshootingPack                 Core,Desk {Get-TroubleshootingPack, Invoke-Troubl…
Manifest   2.0.0.0               TrustedPlatformModule               Core,Desk {Get-Tpm, Initialize-Tpm, Clear-Tpm, Un…
Binary     2.1.639.0             UEV                                 Core,Desk
Manifest   2.0.0.0               VpnClient                           Core,Desk {Add-VpnConnection, Set-VpnConnection, …
Manifest   1.0.0.0               Wdac                                Core,Desk {Get-OdbcDriver, Set-OdbcDriver, Get-Od…
Manifest   2.0.0.0               Whea                                Core,Desk {Get-WheaMemoryPolicy, Set-WheaMemoryPo…
Manifest   1.0.0.0               WindowsDeveloperLicense             Core,Desk {Get-WindowsDeveloperLicense, Unregiste…
Script     1.0                   WindowsErrorReporting               Core,Desk {Enable-WindowsErrorReporting, Disable-…
Manifest   1.0.0.0               WindowsSearch                       Core,Desk {Get-WindowsSearchSetting, Set-WindowsS…
Manifest   1.0.0.0               WindowsUpdate                       Core,Desk Get-WindowsUpdateLog
Manifest   1.0.0.2               WindowsUpdateProvider               Core,Desk {Get-WUAVersion, Get-WULastInstallation…

    Directory: C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Manifest   2.0                   SQLASCMDLETS                        Desk
Manifest   1.0                   SQLPS                               Desk

    Directory: C:\Program Files (x86)\Microsoft Azure Information Protection\Powershell

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Binary     2.8.85.0              AzureInformationProtection          Desk

    Directory: C:\Program Files (x86)\AWS Tools\PowerShell

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Binary     4.0.6.0               AWSPowerShell                       Desk

```

## Debug output

```
DEBUG: 7:29:36 PM - SetAzureDataFactoryLinkedServiceCommand begin processing with ParameterSet 'ByFactoryName'.
DEBUG: 7:29:36 PM - using account id 'b6cf9c7e-f654-4fd8-9ae2-cd64e0d8b0a6'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'b6cf9c7e-f654-4fd8-9ae2-cd64e0d8b0a6', environment: 'AzureCloud', tenant: '45597f60-6e37-4be7-acfb-4c9e23b261ea'
DEBUG: ClientSecretCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
DEBUG: Request [97a0e5f5-5416-4abc-8ace-f069bf9d8816] POST https://login.microsoftonline.com/45597f60-6e37-4be7-acfb-4c9e23b261ea/oauth2/v2.0/token
x-client-SKU:REDACTED
x-client-Ver:REDACTED
x-client-OS:REDACTED
x-client-current-telemetry:REDACTED
x-client-last-telemetry:REDACTED
x-ms-PKeyAuth:REDACTED
x-ms-lib-capability:REDACTED
client-request-id:REDACTED
return-client-request-id:REDACTED
x-app-name:REDACTED
x-app-ver:REDACTED
x-ms-client-request-id:97a0e5f5-5416-4abc-8ace-f069bf9d8816
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.4.0-beta.1,(.NET 5.0.0; Microsoft Windows 10.0.18363)
client assembly: Azure.Identity
DEBUG: Response [97a0e5f5-5416-4abc-8ace-f069bf9d8816] 200 OK (00.2s)
Cache-Control:no-store, no-cache
Pragma:no-cache
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
P3P:REDACTED
client-request-id:REDACTED
x-ms-request-id:REDACTED
x-ms-ests-server:REDACTED
x-ms-clitelem:REDACTED
Set-Cookie:REDACTED
Date:Sat, 05 Dec 2020 18:29:35 GMT
Content-Type:application/json; charset=utf-8
Expires:-1
Content-Length:1427

DEBUG: ClientSecretCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2020-12-05T19:29:35.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: '45597f66-6e37-4be7-acfb-4c9e23b261ea', UserId: 'b6cf9c7e-f654-4fd8-9ae2-cd54e0d8b0a6'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/69a5d461-c3cb-4bf9-a0b0-d33f17da01d8/resourceGroups/msbiinfranp/providers/Microsoft.DataFactory/factories/MSBItestDF2/linkedservices/AzureDatabricks2?api-version=2018-06-01

Headers:
x-ms-client-request-id        : f6f92057-946c-408f-b7ad-983eea65dc36
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Server                        : Microsoft-IIS/10.0
X-Powered-By                  : ASP.NET
x-ms-ratelimit-remaining-subscription-reads: 11998
x-ms-request-id               : d4281b14-de9f-4290-96fd-a606c8796b49
x-ms-correlation-request-id   : d4281b14-de9f-4290-96fd-a606c8796b49
x-ms-routing-request-id       : SWITZERLANDNORTH:20201205T182936Z:d4281b14-de9f-4290-96fd-a606c8796b49
Date                          : Sat, 05 Dec 2020 18:29:36 GMT

Body:
{
  "error": {
    "code": "NotFound",
    "message": "The document could not be retrieved because it does not exist.",
    "target": "/subscriptions/69a5d461-c3cb-4bf9-a0b0-d33f17da01d8/resourceGroups/msbiinfranp/providers/Microsoft.DataFactory/factories/MSBItestDF2/linkedservices/AzureDatabricks2",
    "details": null
  }
}


Set-AzDataFactoryV2LinkedService: 'AccessToken' cannot be null.
DEBUG: AzureQoSEvent: CommandName - Set-AzDataFactoryV2LinkedService; IsSuccess - False; Duration - 00:00:00.2312088;; Exception - Microsoft.Rest.ValidationException: 'AccessToken' cannot be null.
   at Microsoft.Azure.Management.DataFactory.Models.AzureDatabricksLinkedService.Validate()
   at Microsoft.Azure.Management.DataFactory.Models.LinkedServiceResource.Validate()
   at Microsoft.Azure.Management.DataFactory.LinkedServicesOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String factoryName, String linkedServiceName, LinkedServiceResource linkedService, String ifMatch, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.DataFactory.LinkedServicesOperationsExtensions.CreateOrUpdateAsync(ILinkedServicesOperations operations, String resourceGroupName, String factoryName, String linkedServiceName, LinkedServiceResource linkedService, String ifMatch, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.DataFactory.LinkedServicesOperationsExtensions.CreateOrUpdate(ILinkedServicesOperations operations, String resourceGroupName, String factoryName, String linkedServiceName, LinkedServiceResource linkedService, String ifMatch)
   at Microsoft.Azure.Commands.DataFactoryV2.DataFactoryClient.CreateOrUpdateLinkedService(String resourceGroupName, String dataFactoryName, String linkedServiceName, String rawJsonContent)
   at Microsoft.Azure.Commands.DataFactoryV2.DataFactoryClient.<>c__DisplayClass65_0.<CreatePSLinkedService>b__0()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ConfirmAction(Boolean force, String continueMessage, String processMessage, String target, Action action, Func`1 useShouldContinue)
   at Microsoft.Azure.Commands.DataFactoryV2.DataFactoryClient.CreatePSLinkedService(CreatePSAdfEntityParameters parameters)
   at Microsoft.Azure.Commands.DataFactoryV2.SetAzureDataFactoryLinkedServiceCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 7:29:37 PM - SetAzureDataFactoryLinkedServiceCommand end processing.
```

## Error output

```

  HistoryId: 72

Message        : 'AccessToken' cannot be null.
StackTrace     :    at Microsoft.Azure.Management.DataFactory.Models.AzureDatabricksLinkedService.Validate()
                    at Microsoft.Azure.Management.DataFactory.Models.LinkedServiceResource.Validate()
                    at Microsoft.Azure.Management.DataFactory.LinkedServicesOperations.CreateOrUpdateWithHttpMessagesAs
                 ync(String resourceGroupName, String factoryName, String linkedServiceName, LinkedServiceResource
                 linkedService, String ifMatch, Dictionary`2 customHeaders, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.DataFactory.LinkedServicesOperationsExtensions.CreateOrUpdateAsync(IL
                 inkedServicesOperations operations, String resourceGroupName, String factoryName, String
                 linkedServiceName, LinkedServiceResource linkedService, String ifMatch, CancellationToken
                 cancellationToken)
                    at Microsoft.Azure.Management.DataFactory.LinkedServicesOperationsExtensions.CreateOrUpdate(ILinked
                 ServicesOperations operations, String resourceGroupName, String factoryName, String
                 linkedServiceName, LinkedServiceResource linkedService, String ifMatch)
                    at Microsoft.Azure.Commands.DataFactoryV2.DataFactoryClient.CreateOrUpdateLinkedService(String
                 resourceGroupName, String dataFactoryName, String linkedServiceName, String rawJsonContent)
                    at Microsoft.Azure.Commands.DataFactoryV2.DataFactoryClient.<>c__DisplayClass65_0.<CreatePSLinkedSe
                 rvice>b__0()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ConfirmAction(Boolean force,
                 String continueMessage, String processMessage, String target, Action action, Func`1 useShouldContinue)
                    at Microsoft.Azure.Commands.DataFactoryV2.DataFactoryClient.CreatePSLinkedService(CreatePSAdfEntity
                 Parameters parameters)
                    at Microsoft.Azure.Commands.DataFactoryV2.SetAzureDataFactoryLinkedServiceCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronously
                 OrAsJob>b__3_0(T c)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet, Action`1 executor)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Rest.ValidationException
InvocationInfo : {Set-AzDataFactoryV2LinkedService}
Line           : Set-AzDataFactoryV2LinkedService -ResourceGroupName $RGname -DataFactoryName $ADFname -Name
                 AzureDatabricks2 -DefinitionFile $("C:\Users\user\Desktop\thing.json")
Position       : At line:1 char:1
                 + Set-AzDataFactoryV2LinkedService -ResourceGroupName $RGname -DataFact …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by dingmeng-xue** [comment] 2020-12-07 02:10
Service team, please help to look into this question.

**Comment by plk** [comment] 2020-12-10 15:31
Any news on this? It's a bit of a show-stopper now that MSI for databricks is GA.

**Comment by plk** [comment] 2020-12-18 13:27
Any news on this? Does it need fixing in Az module or on the backend service? It is preventing deploys with MSI-enabled databricks in ADF.

**Comment by shawnxzq** [comment] 2020-12-24 08:31
@plk This is because MSI is a new feature for Azure Databricks linked service, while this new feature is not included in the PS yet, we will work on this. For now, please use UX or generic azure resource PS cmdlet to work around this, thanks!

**Comment by plk** [comment] 2020-12-24 12:48
Do you know if it will be in the next Az module release? It's a bit of a problem when a new feature comes out like this, our users adopt it but the APIs we use don't support it yet ...

**Comment by hellhax** [comment] 2021-01-11 22:30
The same issue occurs if you want to update Linked Service via .NET SDK of Data Factory (version 4.13.0) - some exception with the same error message. On the other hand, it works fine when you want to update Linked Service manually via Azure portal. So I think the issue is not in the API - it's probably somewhere in .NET SDK and Powershell uses that SDK under the hood. 

I also tried to update via Azure CLI but was not able to - some unclear error message saying unrecognized properties parameter even though I followed the example from the MS docs. 

Looks like to only civilized way to switch from PAT to MSI is via Azure Portal (which is lame). 

Didn't try ARM though. As said above this is a showstopper for migration from ugly PAT to MSI. Hopefully, it will be fixed soon.

**Comment by shawnxzq** [comment] 2021-01-14 07:22
@plk You are correct and it's a client side issue only, you will have the same issue using SDK/PS/CLI, please continue to use the workaround till we fix the issue, thanks!

**Comment by shawnxzq** [comment] 2021-02-07 09:47
@plk The fix is already coded, however, we still need a azure PowerShell release train to get it fixed in power shell. You can expect to get the fix in PS in early March.

**Comment by shawnxzq** [comment] 2021-03-05 15:52
It's fixed in the latest Az module.

**Closed by shawnxzq** 2021-03-05 15:52 UTC
Labels: Data Factory, Service Attention, customer-reported, question
