### ISSUE TITLE
Set-AzureKeyVaultSecret does not recognize vaultName

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/azure-powershell#1524] opened 2015-12-18 22:18 UTC
I have an old script I dusted off in the 1.0.2 release, Set-AzureKeyVaultSecret seems to have regressed:

``` PowerShell
New-AzureRMKeyVault -VaultName $vaultName -ResourceGroupName $resourceGroupName -Location eastus
Set-AzureKeyVaultSecret -VaultName $vaultName -Name adminPassword -SecretValue (ConvertTo-SecureString -String 'secretpassword' -AsPlainText -Force)
```

Now the set cmdlet returns:

Set-AzureKeyVaultSecret : The remote name could not be resolved: '<snip>.vault.azure.net'
At line:1 char:1
- Set-AzureKeyVaultSecret -VaultName $vaultName -Name test -SecretValue (ConvertTo ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : CloseError: (:) [Set-AzureKeyVaultSecret], WebException
  - FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.SetAzureKeyVaultSecret

Even though the vault was created just fine...

**Comment by joshmouch** [comment] 2016-02-18 22:23
Any idea why this error message occurs?  I'm also getting a "The remove name could not be resolved: '*.vault.azure.net", except I get it when running Set-AzureRmVMDiskEncryptionExtension.

**Comment by bryanar** [comment] 2016-07-08 17:43
I'm seeing this as well, many months later. Did anyone ever try to resolve this? Is the key vault team in the know?

**Comment by Pradebban** [comment] 2016-08-23 03:41
Same here, this is very strange! works sometime and not the other time!
Do we have any updates on this. 

@markcowl, could you please have a look here.

Thanks,
Pradebban Raja

**Comment by mbukosky** [comment] 2016-08-26 12:40
+1

**Comment by xinyiou** [comment] 2016-09-11 11:46
+1

**Comment by clintonm9** [comment] 2016-10-27 19:32
+1

**Comment by Kandarp2516** [comment] 2016-12-02 01:58
+1

**Comment by Technolink** [comment] 2016-12-02 23:35
+1

**Comment by diahughes** [comment] 2016-12-03 14:14
Same here, works one minute then not the other.

**Comment by davoodharun** [comment] 2017-02-23 05:54
+1

**Comment by wbreza** [comment] 2017-03-27 01:38
+1

**Comment by kpratik16** [comment] 2017-04-11 22:59
+1

**Comment by kpratik16** [comment] 2017-04-11 23:03
It was due to invalid dns cache for me. Flushing out dns cache fixed it. 

Command:   ipconfig /flushdns

**Comment by LukeDearden** [comment] 2017-04-20 08:59
I use this to trap it. Seems to be an intermittent problem
```
$dnscheck = Resolve-DnsName ([System.Uri](Get-AzureRmKeyVault -VaultName $myVault).VaultURI).Host
     if (!$dnscheck) {
        write-host "AZURE BUG : Resolve-DnsName could not resolve vault name. Keep trying!"
        exit
    }
```

**Comment by JinhongZh** [comment] 2017-09-21 06:16
+1
And ipconfig /flushdns didn't work for me :(

**Comment by pixelicous** [comment] 2018-01-02 10:24
+1

This is amazingly annoying, also happens in terraform.. This must be resolved

**Comment by pixelicous** [comment] 2018-01-07 12:22
Can anyone take a look at this matter????? 2 years after, this is still happening :(

**Comment by maddieclayton** [comment] 2018-02-07 00:20
Closing in favor of https://github.com/Azure/azure-powershell/issues/5326

**Closed by maddieclayton** 2018-02-07 00:20 UTC
Labels: KeyVault

**Comment by pixelicous** [comment] 2018-02-27 15:22
Dont understand why this is closed, this is open since 2015, i just reinstated on another issue that it still exists *face palm*

**Comment by dmarlow** [comment] 2019-02-21 21:18
Also running into this.

**Comment by placidseven** [comment] 2019-09-10 17:17
This issue is still unresolved.
This is also clearly an issue with the module!

![image](https://user-images.githubusercontent.com/54321928/64635185-b7126e80-d3c4-11e9-92e0-bf2e7025eaa9.png)

If I can find the resource with Get-AzKeyVault then I should be able to find it with Set-AzKeyVaultSecret or Get-AzKeyVaultSecret. 
Someone needs to look at this.

**Comment by dmarlow** [comment] 2019-09-10 17:44
I run into strange stuff all the time related to DNS. I think it's deeper than these instances related to KeyVault. I often times get failures resolving the Let's Encrypt endpoint. One thing in common on all occurrences is the fact that it's .NET under the covers.

**Comment by placidseven** [comment] 2019-09-23 13:43
For anyone that finds this problem @LukeDearden stated eventually the request will go through. Takes up to 10 min for me at times.

```
function getSecret{
    while (!$secret) {
        Start-Sleep -Seconds 30
        write-host "Resolve-DnsName could not resolve $vaultName. Keep trying!"
        $secret = Get-AzKeyVaultSecret -VaultName $vaultName -Name $secretName -ErrorAction SilentlyContinue
    }
}

$secret = Set-AzKeyVaultSecret -VaultName $vmVaultName -Name $secretName -SecretValue $secretString -ErrorAction SilentlyContinue
setSecret
}
```

Not sure if increasing the frequency of the request would increase chances of a successful call. I also have an almost identical code block for Set-AzKeyVaultSecret. Unfortunately this module is necessary for my deployment automation so I have to make due.

**Comment by pixelicous** [comment] 2020-02-05 12:26
The keyvault cmdlets in powershell always had issues, instead of the api returning an object after the hostname have been propogated successfully the cmdlet have a sleep function, i know this by a fact as we opened a ticket to microsoft requesting this to be fixed and the product team only added a minute and a half sleep, stating why it is supposed to solve it.

Part of that matter, keyvault and storage account endpoints have constant issues during the two and a half years i have been working with them, very unreliable infrastructure.

p.s - the python libraries aren't any better ;)

**Comment by seabrin** [comment] 2021-07-23 23:43
I know this issue is closed but I just ran into this error in July 2021 and found a pretty simple workaround that works consistently. Somewhere in my online troubleshooting travels, a poster mentioned that get-azkeyvault (without any parameters) worked even though get-azkeyvaultsecret failed to resolve the remote name. So I assigned get-azkeyvault to a variable and used the vaultname property ($varVault.VaultName). I used that for the get-azkeyvaultsecret -vaultname parameter and it works. Every time. Hopefully this helps someone.

`$varVault = get-azkeyvault
get-azkeyvaultsecret -VaultName $varVault.VaultName -secret _"<secret>"`_

**Comment by RDavis3000** [comment] 2023-01-25 15:47
this is embarrassing; I was using the -VaultName arg and for me the error was caused by the value I was giving it was just the wrong string. 
It was trying to access a KeyVault which didn't exist. 
So for those who come after, double check your value!
