### ISSUE TITLE
Get-AzRecoveryServicesVaultSettingsFile : Parameter set cannot be resolved using the specified named parameters.

### ISSUE THREAD

**Issue by villanub** [Azure/azure-powershell#9580] opened 2019-07-09 22:30 UTC
## Description

Unable to run Get-AzRecoveryServicesVaultSettingsFile : Parameter set cannot be resolved using the specified named parameters.

## Steps to reproduce

```powershell
Type Get-AzRecoveryServicesVaultSettingsFile error occurs, does not accept any parameters

Get-AzRecoveryServicesVaultSettingsFile : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Get-AzRecoveryServicesVaultSettingsFile
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-AzRecoveryServicesVaultSettingsFile], ParameterBindingExceptio
   n
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Azure.Commands.RecoveryServices.GetAzureRmRecoveryServic
   esVaultSettingsFile
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.17763.503
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.503
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

```powershell
Get-InstalledModule -Name  Az.RecoveryServices

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
2.0.0-preview        Az.RecoveryServices                 PSGallery            Microsoft Azure PowerShell - Recovery ...


```

## Debug output

```
PS C:\WINDOWS\system32> Get-AzRecoveryServicesVaultSettingsFile -Vault $ASR -Debug -Verbose
Get-AzRecoveryServicesVaultSettingsFile : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Get-AzRecoveryServicesVaultSettingsFile -Vault $ASR -Debug -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-AzRecoveryServicesVaultSettingsFile], ParameterBindingExceptio
   n
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Azure.Commands.RecoveryServices.GetAzureRmRecoveryServic
   esVaultSettingsFile

```

## Error output

```
Message        : Parameter set cannot be resolved using the specified named parameters.
StackTrace     :    at System.Management.Automation.CmdletParameterBinderController.ThrowAmbiguousParameterSetException
                 (UInt32 parameterSetFlags, MergedCommandParameterMetadata bindableParameters)
                    at System.Management.Automation.CmdletParameterBinderController.ValidateParameterSets(Boolean
                 prePipelineInput, Boolean setDefault)
                    at
                 System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1
                 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary
                 psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object
                 input)
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object
                 input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput,
                 CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][]
                 commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                 frame)
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {Get-AzRecoveryServicesVaultSettingsFile}
Line           : Get-AzRecoveryServicesVaultSettingsFile
Position       : At line:1 char:1
                 + Get-AzRecoveryServicesVaultSettingsFile
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 14
```

**Comment by Wand3rvogel** [comment] 2019-07-10 07:27
You need -Backup or -SiteRecovery.
And -Certificate is a must.

(https://docs.microsoft.com/en-us/powershell/module/az.recoveryservices/get-azrecoveryservicesvaultsettingsfile?view=azps-2.4.0)

**Comment by diegopietruszka** [comment] 2019-07-18 13:55
This command work perfectly fine with the AzureRM module 

Get-AzurermRecoveryServicesVaultSettingsFile -Vault $vault -SiteRecovery -Path 'c:\something\'

The problem is on the AZ module. Do we have to go back to the AzureRM modules?

**Comment by diegopietruszka** [comment] 2019-08-01 13:45
Anyone on this?

**Comment by pvrk** [comment] 2019-08-21 06:29
@diegopietruszka: Unfortunately, due to underlying platform limitations, Az module requires a certificate whereas AzureRM does not. While we are pursuing this PS team, request you to kindly take a look at documentation where we provided an example and re-try.

https://docs.microsoft.com/azure/backup/backup-client-automation#registering-using-the-ps-az-module

**Comment by diegopietruszka** [comment] 2019-08-21 12:52
Thanks for the answer, but makes no sense. I will stay with the azurerm module then, I'm using Azure to make things easier and simpler for us, don't need this kind of nonsense complications.

**Comment by marktheiii** [comment] 2020-02-04 18:32
Any activity on this from Microsoft? Managing a self-signed certificate for the vault process is an extra hurdle that we don't need. This severely impedes my work to update all of our automation processes to the new Az module.

**Comment by pvrk** [comment] 2020-03-10 06:39
@marktheiii : Unfortunately, we still need a self-signed certificate for this with Az Module but we have fixed few issues with the command that may ease the problem a little bit. Please refer to this section for more details

https://docs.microsoft.com/azure/backup/backup-client-automation#registering-using-the-ps-az-module

**Comment by mganeshphani** [comment] 2020-04-28 17:46
@pvrk it is again broken.. not sure why this is soo much unreliable
Get-AzRecoveryServicesVaultSettingsFile: X509Certificate is immutable on this platform. Use the equivalent constructor instead.

**Comment by pvrk** [comment] 2020-06-08 05:48
@vidyadharijami : Can you please check on this?
@mganeshphani : We tested this internally and this works. Can you please share the version number and more details?

**Comment by vidyadharijami** [comment] 2020-06-08 05:54
@mganeshphani  Can you please use windows powershell instead of powershell core to check this.

**Comment by vidyadharijami** [comment] 2020-06-08 06:02
Please refer below documentation to download vault cred file https://docs.microsoft.com/azure/backup/backup-client-automation#registering-using-the-ps-az-module

**Comment by NimalDas** [comment] 2020-07-30 16:01
tried this but no luck. opened a new issue #12541

**Comment by pvrk** [comment] 2020-09-14 18:44
Closing this issue since this is tracked in the new issue.

**Closed by pvrk** 2020-09-14 18:44 UTC
Labels: Recovery Services, Service Attention, customer-response-expected
