### ISSUE TITLE
New-AzureRmVirtualNetworkGateway : An error occured.

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2419] opened 2016-06-07 15:59 UTC
> New-AzureRmVirtualNetworkGateway : An error occured.

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by markcowl** [comment] 2016-06-09 18:48
nice.

**Comment by markcowl** [comment] 2016-06-09 18:49
@deepakrajendranmsft can you take a look?

**Comment by markcowl** [comment] 2016-06-09 18:49
@pcgeek86 If you can repro, would you get the debug traces for this execution?  It will help the network team in debugging this.

**Comment by DeepakRajendranMsft** [comment] 2016-06-09 19:59
@amitsriva @lamchester please take a look

**Comment by amitsriva** [comment] 2016-06-09 20:04
Could you send more details about this error? We would need steps to reproduce this. Alternatively if you post the subscription id, region and approximate time range we can look up in logs. Will fix once we know the root cause.

**Comment by mcumpl** [comment] 2016-09-19 10:19
Any news here? I am getting the same error.

`New-AzureRmVirtualNetworkGateway : An error occured.
StatusCode: 500
ReasonPhrase: Internal Server Error
OperationID : 'f5a5ad43-48cb-467f-a563-cfb85a3ded35'
At C:\Projects\eVzp.Infrastructure.Itest\deployment\helpers\CreateGateway.ps1:11 char:5
+     New-AzureRmVirtualNetworkGateway -Name $vnetGatewayName -Resource ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmVirtualNetworkGateway], NetworkCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.NewAzureVirtualNetworkGatewayCommand`

**Comment by lamchester** [comment] 2016-09-19 19:21
I looked at the request. The ipconfiguration being referenced doesn’t exist. Also, you can only have one VPN gateway per virtual network, so you’d need to create another virtual network (and public ip address, and ipconfiguration) to create another virtual network gateway.

PUT https://westeurope.network.azure.com:30008/a9c6dfb3-3353-42f2-a1e2-c690d527bca1/131182912168662763/subscriptions/(subid)/resourceGroups/evzp-itest-asp/providers/Microsoft.Network/virtualNetworkGateways/evzp-itest-asp-gateway-x?api-version=2016-06-01
<snip some http headers>
{
  "properties": {
    "ipConfigurations": [
      {
        "properties": {
          "privateIPAllocationMethod": "Dynamic",
          "publicIPAddress": {
            "id": "/subscriptions/(subid)/resourceGroups/evzp-itest-asp/providers/Microsoft.Network/publicIPAddresses/evzp-itest-asp-ip"
          }
        },
        "name": "evzp-itest-asp-gateway-config",
        "id": "/subscriptions/(subid)/resourceGroups/ResourceGroupNotSet/providers/Microsoft.Network/virtualNetworkGateways/VirtualNetworkGatewayNameNotSet/virtualNetworkGatewayIpConfigurations/evzp-itest-asp-gateway-config"
      }
    ],
    "gatewayType": "Vpn",
    "vpnType": "RouteBased",
    "enableBgp": false,
    "sku": {
      "name": "Basic",
      "tier": "Basic",
      "capacity": 0
    },
    "vpnClientConfiguration": {
      "vpnClientAddressPool": {
        "addressPrefixes": [
          "10.1.1.0/24"
        ]
      },
      "vpnClientRootCertificates": [],
      "vpnClientRevokedCertificates": []
    }
  },
  "location": "westeurope"
}

Let me know if there are any questions.

Thanks,
Chester

**Comment by pcgeek86** [comment] 2016-09-22 16:47
So you identified one or more root causes? Looks like a good opportunity to improve the error messages / handling.

**Comment by maddieclayton** [comment] 2018-03-22 18:18
Closing - improving error messaging across the board is covered by other issues in our repo, and looks like the error here was resolved.

**Closed by maddieclayton** 2018-03-22 18:18 UTC
Labels: Networking
