### ISSUE TITLE
Set-AzStorageFileContent does not work in Azure Automation Runbook.

### ISSUE THREAD

**Issue by jude-chen** [Azure/azure-powershell#8642] opened 2019-02-27 21:34 UTC
Set-AzStorageFileContent does not work in Azure Automation Runbook, always get "Illegal characters in path" error for the "source" parameter, no matter how good looking the source file path string is. However, the exact same code works just fine in an interactive PowerShell session on the same Azure VM where the hybrid worker is running.

After modifying the code to using AzureRM and Azure.Storage modules, and then it works just fine in Azure Automation Runbook through the same hybrid worker.

Tested on an Azure VM hybrid worker with both latest AzureRM and Az modules installed. 
AzureRM version 6.13.1
Azure.Storage version 4.6.1
Az version 1.4.0
Az.Storage version 1.0.2

**Comment by blueww** [comment] 2019-02-28 02:12
This issue has same root cause as https://github.com/Azure/azure-powershell/issues/8531 
Runbook team is working to fix the issue in runbook.
Will update when get progress.

**Comment by cormacpayne** [comment] 2019-02-28 16:39
Thanks for the update @blueww -- I'm going to close this issue in favor of the existing issue https://github.com/Azure/azure-powershell/issues/8531 so we can keep updates and track status in one place. Please let us know if you have any questions!

**Closed by cormacpayne** 2019-02-28 16:39 UTC
