### ISSUE TITLE
Unable to use Get-AzureRmResourceGroup in Azure automation using service principal

### ISSUE THREAD

**Issue by Blackbaud-PaulSebestyen** [Azure/azure-powershell#2067] opened 2016-04-07 17:53 UTC
I can't seem to get Get-AzureRmResourceGroup to work in Azure automation when using the service principal credentials.  My code:

	
	$azureCred = Get-AutomationPSCredential -Name '<CredentialName>'
			
	Login-AzureRmAccount -Credential $azureCred -ServicePrincipal -TenantId '<TenantID>'
		
	Get-AzureRMVM		#This works!
	Get-AzureRMResourceGroup -Name '<ExistingRGName>'	

This is the error I am getting:

Get-AzureRMResourceGroup : Your Azure credentials have not been set up or have expired, please run Login-AzureRMAccount 
to set up your Azure credentials.
At line:16 char:3
+         Get-AzureRMResourceGroup #-Name 'ExistingRGName'
+         ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmResourceGroup], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.GetAzureResourceGroupCommand

**Comment by hovsepm** [comment] 2016-04-08 00:47
@Blackbaud-PaulSebestyen please run following cmdlet after the failure and post here results.
```
Get-Module | Format-Table -Property Name, Path -Groupby Name
```

**Comment by Blackbaud-PaulSebestyen** [comment] 2016-04-08 14:32
Name: AzureRM.Compute

Name                                                         Path                                                       
----                                                         ----                                                       
AzureRM.Compute                                              C:\Modules\User\AzureRM.Compute\AzureRM.Compute.psd1       
d1

   Name: AzureRM.profile

Name                                                         Path                                                       
----                                                         ----                                                       
AzureRM.profile                                              C:\Modules\User\AzureRM.profile\AzureRM.profile.psd1       
d1

   Name: AzureRM.Resources

Name                                                         Path                                                       
----                                                         ----                                                       
AzureRM.Resources                                            C:\Modules\User\AzureRM.Resources\AzureRM.Resources.psd1   
d1

   Name: CheckVersions

Name                                                         Path                                                       
----                                                         ----                                                       
CheckVersions                                                C:\Modules\User\AzureRM.profile\CheckVersions.ps1          
s1

   Name: Orchestrator.AssetManagement.Cmdlets

Name                                                         Path                                                       
----                                                         ----                                                       
Orchestrator.AssetManagement.Cmdlets                         C:\Modules\Global\Orchestrator.AssetManagement.Cmdlets\O...
m...

   Name: Orchestrator.GraphRunbook.Cmdlets

Name                                                         Path                                                       
----                                                         ----                                                       
Orchestrator.GraphRunbook.Cmdlets                            C:\Orchestrator\GraphRunbookCmdlets\Orchestrator.GraphRu...
m1

**Comment by ravbhatnagar** [comment] 2016-04-12 18:38
It is not clear from above which version of AzureRM, AzureRm.Profile and AzureRm.Resources do you have on your machine? Can you please verify and let us know the version with Get-InstalledModule?

**Comment by Blackbaud-PaulSebestyen** [comment] 2016-04-13 13:38
@ravbhatnagar - this is in **AzureAutomation**, not locally

**Comment by Stijnc** [comment] 2016-04-13 18:11
I see that you are using the add-azureRmaccount using serviceprinciple and credentials.
Currently the cmdlet uses the credential store, wich is not available in azure automation. if using a service principle you need to authenticate using a certificate.
see issue #655 . the issue is marked as closed, as a workaround is provided.

**Comment by ravbhatnagar** [comment] 2016-04-14 01:22
@Blackbaud-PaulSebestyen Can you try the solution mentioned in the article here - https://azure.microsoft.com/en-us/documentation/articles/automation-sec-configure-azure-runas-account/
cc jodoglevy

**Comment by vsilgalis-rise** [comment] 2016-04-14 21:41
Seeing a similar issue here with AzureRM.Profile 1.0.6 in AzureAutomation.

When using the default version it was fine, AzureRM.Profile 1.0.3, once I upgraded to 1.0.6 I started seeing this issue:
Unexpected exception: Run Login-AzureRmAccount to login. (Unexpected exception: Run Login-AzureRmAccount to login.)

**Comment by markcowl** [comment] 2016-04-15 21:55
@vsilgalis-rise Unfortunately, there are assembly dependency issues that require you to use trhe specific version of AzureRM.Profile with the matching version of the AzureRM.Resources module.  If you update one mnodule to the latest version, you must update the others.

This is a point in time issue, but this is the current advice.

**Comment by vsilgalis-rise** [comment] 2016-04-18 16:07
@markcowl Looks I missed one of the modules when I was upgrading them (would be nice to get the dependencies across all the libraries).  Thanks for the help.

**Comment by Stijnc** [comment] 2016-04-19 07:36
@vsilgalis-rise  update-azureRM should do the trick to keep your modules into sync. (http://www.powershellgallery.com/packages/AzureRM/1.3.0 or Install-Module -Name AzureRM ).

**Comment by markcowl** [comment] 2016-05-03 01:31
@vsilgalis-rise @Stijnc ```Update-AzureRM``` was removed in the last release.  Now use Install-Module AzureRM for the correct dependencies.

**Comment by vsilgalis-rise** [comment] 2016-05-03 14:53
My issues weren't local but in Azure Automation when updating the modules there.

**Comment by markcowl** [comment] 2016-05-07 02:24
@vsilgalis-rise Yes, unfortunately the easiest solution nis to use the latest version of the module and/or to match based on the AzureRM.profile dependency.  If we could use the new module manifest format, then this error would be easier to discover, as we could make the version depednency explicit.  However, this would preclude compatibility with WMF4 and PowerShell 3.

**Comment by markcowl** [comment] 2016-08-08 18:54
Clopsing, as I believe the underlying issue was resolved.

**Closed by markcowl** 2016-08-08 18:54 UTC
Labels: More Info, Team

**Comment by tyconsulting** [comment] 2017-03-15 11:13
I'm having the same problem when signing in using Service Principal and credential. all AzureRM modules are up to date as of March 2017. According to @Stijnc 's comment on 14th April 2016, this is not supported. are there any plans to support this in the future?
