### ISSUE TITLE
Stop-AzSynapseTrgger throws generic error

### ISSUE THREAD

**Issue by hydrilllo** [Azure/azure-powershell#20509] opened 2022-12-23 18:03 UTC
### Description

the cmdlet throws a generic error. Tried with different PS versions (5 and 7). Modules are up to date. Also tried with different authentications (MI, User and Service Principal). Users are Synapse Administrators and Contributors on the workspace.

### Issue script & Debug output

```PowerShell
DEBUG: Response [90d2a309-9ccb-443f-957e-c96753b6a46b] 200 OK (00.5s)
Strict-Transport-Security:REDACTED
x-ms-correlation-request-id:REDACTED
x-ms-request-id:bbd8ec84-ffee-4d66-9e9d-9d6ebfd340a5
x-ms-client-request-id:90d2a309-9ccb-443f-957e-c96753b6a46b
Content-Length:2
Content-Type:application/json; charset=utf-8
Date:Fri, 23 Dec 2022 18:03:10 GMT
Server:Kestrel Microsoft-HTTPAPI/2.0
DEBUG: 6:03:10 PM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning
default value [True].
Stop-AzSynapseTrigger : {}
At line:1 char:1
+ Stop-AzSynapseTrigger -WorkspaceName "scm-bi-syn-sn-prd" -Name "Daily ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Stop-AzSynapseTrigger], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Synapse.StopAzureSynapseTrigger

DEBUG: 6:03:11 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = [].
Returning default value [True].
DEBUG: AzureQoSEvent: Module: Az.Synapse:1.5.0; CommandName: Stop-AzSynapseTrigger; PSVersion: 5.1.20348.859;
IsSuccess: False; Duration: 00:00:02.0676687; Exception: {};
DEBUG: Finish sending metric.
DEBUG: 6:03:12 PM - StopAzureSynapseTrigger end processing.
```

### Environment data

```PowerShell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.20348.859
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.20348.859
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.5.0      Az.Synapse                          {Add-AzSynapseDataFlowDebugSessionPackage, Add-AzSynapseTr...
```

### Error output

```PowerShell
PS C:\Users\patrick.vogler> Resolve-AzError
DEBUG: 6:00:54 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 6:00:54 PM - using account id 'patrick.vogler@swiss-commerce.ch'...
DEBUG: 6:00:54 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = [].
Returning default value [True].
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use
`Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other
information on breaking changes in Azure PowerShell.


   HistoryId: 10


Message        : {}
StackTrace     :    at Microsoft.Azure.Commands.Synapse.Common.Utils.Poll(Operation operation)
                    at Microsoft.Azure.Commands.Synapse.Models.SynapseAnalyticsArtifactsClient.StopTrigger(String
                 triggerName)
                    at Microsoft.Azure.Commands.Synapse.StopAzureSynapseTrigger.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Exception
InvocationInfo : {Stop-AzSynapseTrigger}
Line           : $tr | Stop-AzSynapseTrigger
Position       : At line:1 char:7
                 + $tr | Stop-AzSynapseTrigger
                 +       ~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 10



   HistoryId: 8


Message        : The term 'pwsh' is not recognized as the name of a cmdlet, function, script file, or operable
                 program. Check the spelling of the name, or if a path was included, verify that the path is correct
                 and try again.
StackTrace     :    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName,
                 CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin
                 commandOrigin, ExecutionContext context)
                    at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName,
                 CommandOrigin commandOrigin, Nullable`1 useLocalScope)
                    at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
                    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe,
                 CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[]
                 redirections, ExecutionContext context)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput,
                 CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][]
                 commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                 frame)
Exception      : System.Management.Automation.CommandNotFoundException
InvocationInfo : {}
Line           : pwsh
Position       : At line:1 char:1
                 + pwsh
                 + ~~~~
HistoryId      : 8



   HistoryId: 7


Message        : {}
StackTrace     :    at Microsoft.Azure.Commands.Synapse.Common.Utils.Poll(Operation operation)
                    at Microsoft.Azure.Commands.Synapse.Models.SynapseAnalyticsArtifactsClient.StopTrigger(String
                 triggerName)
                    at Microsoft.Azure.Commands.Synapse.StopAzureSynapseTrigger.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Exception
InvocationInfo : {Stop-AzSynapseTrigger}
Line           : Stop-AzSynapseTrigger
Position       : At line:1 char:1
                 + Stop-AzSynapseTrigger
                 + ~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 7



   HistoryId: 6


Message        : {}
StackTrace     :    at Microsoft.Azure.Commands.Synapse.Common.Utils.Poll(Operation operation)
                    at Microsoft.Azure.Commands.Synapse.Models.SynapseAnalyticsArtifactsClient.StopTrigger(String
                 triggerName)
                    at Microsoft.Azure.Commands.Synapse.StopAzureSynapseTrigger.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Exception
InvocationInfo : {Stop-AzSynapseTrigger}
Line           : $tr | Stop-AzSynapseTrigger
Position       : At line:1 char:7
                 + $tr | Stop-AzSynapseTrigger
                 +       ~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 6



   HistoryId: 4


Message        : {}
StackTrace     :    at Microsoft.Azure.Commands.Synapse.Common.Utils.Poll(Operation operation)
                    at Microsoft.Azure.Commands.Synapse.Models.SynapseAnalyticsArtifactsClient.StopTrigger(String
                 triggerName)
                    at Microsoft.Azure.Commands.Synapse.StopAzureSynapseTrigger.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Exception
InvocationInfo : {Stop-AzSynapseTrigger}
Line           : $tr | Stop-AzSynapseTrigger
Position       : At line:1 char:7
                 + $tr | Stop-AzSynapseTrigger
                 +       ~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 4


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.

DEBUG: 6:00:54 PM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning
default value [True].
DEBUG: AzureQoSEvent: Module: Az.Accounts:2.9.1; CommandName: Resolve-AzError; PSVersion: 5.1.20348.859; IsSuccess:
True; Duration: 00:00:00.1908139
DEBUG: Finish sending metric.
DEBUG: 6:00:54 PM - ResolveError end processing.
```

**Comment by SaurabhSharma-MSFT** [comment] 2022-12-24 02:16
@hydrilllo We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment] 2022-12-27 03:22
@hydrilllo I am not able to reproduce this issue.  I am using 2.1.0 version of `Az.Synapse`.  Can you please upgrade to latest version and check again.

**Comment by SaurabhSharma-MSFT** [comment] 2022-12-30 09:46
@hydrilllo Please let me know if you are still facing the same problem.

**Comment by SaurabhSharma-MSFT** [comment] 2022-12-31 11:37
@hydrilllo We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Closed by SaurabhSharma-MSFT** 2022-12-31 11:37 UTC
Labels: bug, customer-reported, needs-author-feedback, CXP Attention
