### ISSUE TITLE
Set-AzVMADDomainExtension fails when there are spaces in OUPath parameter

### ISSUE THREAD

**Issue by PlanetWilson** [Azure/azure-powershell#15768] opened 2021-08-27 14:11 UTC
## Description
When I am setting the domain join extension on a VM and the OUPath has spaces in, e.g. "OU=EUC Cloud Hosted,DC=testdlg,DC=local" then the domain join fails.

## Steps to reproduce

```powershell
$ouPath = "OU=EUC Cloud Hosted,DC=testdlg,DC=local"
$domainusername = "avdjoin@testdlg.local"
$domainpassword = (ConvertTo-SecureString "mysecretpassword" -Force -AsPlainText)
$domaincredential = New-Object System.Management.Automation.PScredential ($domainusername, $domainpassword)
Set-AzVMADDomainExtension -DomainName $domainName -OUPath $ouPath -VMName $vmName -Credential $domaincredential -ResourceGroupName $rg -JoinOption 0x00000003 -restart -verbose 

```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Darwin 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```powershell
    Directory: /Users/mark/.local/share/powershell/Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     2.5.0                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAut…
Script     2.4.0                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAut…
Script     4.15.0                Az.Compute                          Core,Desk {Remove-AzAvailabilitySet, Get-AzAvailabilitySe…
Script     3.0.0                 Az.DesktopVirtualization            Core,Desk {Disconnect-AzWvdUserSession, Expand-AzWvdMsixI…
Script     3.4.5                 Az.KeyVault                         Core,Desk {Add-AzKeyVaultCertificate, Update-AzKeyVaultCe…
Script     4.10.0                Az.Network                          Core,Desk {Add-AzApplicationGatewayAuthenticationCertific…
Script     1.1.0                 Az.Wvd                              Core,Desk {Enable-WvdStartVmOnConnect, Export-WvdConfig, …
Manifest   1.6.0                 PnP.PowerShell                      Core,Desk {Add-PnPClientSidePage, Add-PnPClientSidePageSe…

    Directory: /usr/local/microsoft/powershell/7/Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Manifest   1.2.5                 Microsoft.PowerShell.Archive        Desk      {Compress-Archive, Expand-Archive}
Manifest   7.0.0.0               Microsoft.PowerShell.Host           Core      {Start-Transcript, Stop-Transcript}
Manifest   7.0.0.0               Microsoft.PowerShell.Management     Core      {Add-Content, Clear-Content, Clear-ItemProperty…
Manifest   7.0.0.0               Microsoft.PowerShell.Security       Core      {Get-Credential, Get-ExecutionPolicy, Set-Execu…
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        Core      {Export-Alias, Get-Alias, Import-Alias, New-Ali…
Script     1.4.7                 PackageManagement                   Desk      {Find-Package, Get-Package, Get-PackageProvider…
Script     2.2.5                 PowerShellGet                       Desk      {Find-Command, Find-DSCResource, Find-Module, F…
Script     2.0.5                 PSDesiredStateConfiguration         Core      {Configuration, New-DscChecksum, Get-DscResourc…
Script     2.1.0                 PSReadLine                          Desk      {Get-PSReadLineKeyHandler, Set-PSReadLineKeyHan…
Binary     2.0.3                 ThreadJob                           Desk      Start-ThreadJob

    Directory: /Users/mark/.vscode/extensions/ms-vscode.powershell-2021.8.2/modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     1.1.3                 Plaster                             Desk      {Invoke-Plaster, New-PlasterManifest, Get-Plast…
Binary     2.4.9                 PowerShellEditorServices            Core,Desk Start-EditorServices
Binary     0.2.0                 PowerShellEditorServices.VSCode     Desk      {New-VSCodeHtmlContentView, Show-VSCodeHtmlCont…
Script     2.1.0                 PSReadLine                          Desk      {Get-PSReadLineKeyHandler, Set-PSReadLineKeyHan…
Script     1.19.1                PSScriptAnalyzer                    Desk      {Get-ScriptAnalyzerRule, Invoke-ScriptAnalyzer,…

```

## Debug output

```
N/A....the detail is contained in the extension logs inside the VM.

Current domain:  (), current workgroup: WORKGROUP, IsDomainJoin: True, Target Domain/Workgroup: mydomain.local.
2021-08-26T19:30:53.0794566Z	[Info]:	Domain Join Path.
2021-08-26T19:30:53.0794566Z	[Info]:	Current Domain name is empty/null. Try to get Local domain name.
2021-08-26T19:30:53.0794566Z	[Info]:	In AD Domain extension process, the local domain is: ''.
2021-08-26T19:30:53.0950819Z	[Info]:	Domain Join will be performed.
2021-08-26T19:30:53.8606579Z	[Error]:	Try join: domain='mydomain.local', ou='OU=EUC Cloud Hosted,DC=mydomain,DC=local', user='avdjoin@mydomain.local', option='NetSetupJoinDomain, NetSetupAcctCreate' (#3:User Specified), errCode='2'.
2021-08-26T19:30:53.8762845Z	[Error]:	Setting error code to 53 while joining domain
2021-08-26T19:30:54.4704048Z	[Error]:	Try join: domain='mydomain.local', ou='OU=EUC Cloud Hosted,DC=mydomain,DC=local', user='avdjoin@mydomain.local', option='NetSetupJoinDomain' (#1:User Specified without NetSetupAcctCreate), errCode='1332'.
2021-08-26T19:30:54.4704048Z	[Error]:	Setting error code to 53 while joining domain
2021-08-26T19:30:54.4704048Z	[Error]:	Computer failed to join domain 'mydomain.local' from workgroup 'WORKGROUP'.
2021-08-26T19:30:54.4704048Z	[Info]:	Retrying action after 15 seconds, at attempt 1 out of '10'.
```

## Error output

```

```

**Comment by avirishuv** [comment] 2021-09-01 18:11
@amjads1 - could you please take a look at this for Domain Extension?

**Comment by amjads1** [comment] 2021-09-09 07:27
Looking into the issue.

**Comment by axelgMS** [comment] 2021-09-30 19:27
@PlanetWilson  The JoinDomain extension should just make a call to the NetJoinDomain Win32 API and passing the parameters.
So you can try to reproduce with Powershell "Add-Computer" - https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/add-computer?view=powershell-5.1

If you reproduce the issue, then we'll ask the Windows team in charge of this API.
If it works fine, then it can be the extension that doesn't parse correctly the space in the OUPath, and we'll engage the team in charge of the extension.

**Comment by amjads1** [comment] 2021-11-04 17:49
Based on the recommendations shared above, closing this issue as we didn't hear any response from the user but feel free to re-open if the issue is not resolved.

**Closed as completed by amjads1** 2021-11-04 17:49 UTC
Labels: Compute - VM, Service Attention, question, customer-reported, needs-author-feedback
