### ISSUE TITLE
New-AzureRmAppServicePlan is missing Tags parameter

### ISSUE THREAD

**Issue by ronbok** [Azure/azure-powershell#4071] opened 2017-06-03 17:01 UTC
This cmdlet still needs -Tags.

**Comment by cormacpayne** [comment] 2017-06-06 16:28
@Nking92 Hey Nicholas, would you mind taking a look at this issue?

**Comment by cormacpayne** [comment] 2017-06-06 19:47
After looking through our issues a little more, I found that this is a duplicate of https://github.com/Azure/azure-powershell/issues/3996

Closing this issue to track the status on the previously opened issue.

**Closed by cormacpayne** 2017-06-06 19:47 UTC
Labels: Websites
