### ISSUE TITLE
Connect-AzAccount session persist when closing PowerShell, even over multiple days.

### ISSUE THREAD

**Issue by o-l-a-v** [Azure/azure-powershell#10599] opened 2019-11-25 14:38 UTC
## Description
Session/ token persist when closing the PowerShell session. Even days after, if you haven't run Disconnect-AzureAD until it stops outputing objects, you're still logged in and can do stuff with the Az module. No Microsoft PowerShell module has worked like this previously, is it by design?

So, summary:
* Az sessions persist when closing the PowerShell terminal, unlike how AzureAD and other MS modules works.
* You can also be connected with multiple Az sessions at the time. Get-AzContext will then return the session you last established. But when Disconnect-AzAccount, you can run that command once for each of the previously connected/ not yet disconnected sessions.
* Disconnect-AzAccount does not disconnect multiple active sessions if there are indeed multiple not disconnected sessions available. Why shouldn't it do so?
    * Connect-AzAccount two times to two different environments. Disconnect-AzAccount once, then once more.

## Steps to reproduce

```powershell
Connect-AzAccount
```

Then close PowerShell.
Take the weekend of. Or not.
Then open PowerShell.

```powershell
Get-AzContext
```

You are still authenticated/ in a active session.

## Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

```powershell


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.6.4      Az.Accounts                         {Disable-AzDataCollection, Disable-AzContextAutosave, Enab...
Script     1.1.0      Az.Advisor                          {Get-AzAdvisorRecommendation, Enable-AzAdvisorRecommendati...
Script     1.0.2      Az.Aks                              {Get-AzAks, New-AzAks, Remove-AzAks, Import-AzAksCredentia...
Script     0.1.0      Az.AlertsManagement                 {Get-AzAlert, Get-AzAlertObjectHistory, Update-AzAlertStat...
Script     1.1.1      Az.AnalysisServices                 {Resume-AzAnalysisServicesServer, Suspend-AzAnalysisServic...
Script     1.3.2      Az.ApiManagement                    {Add-AzApiManagementApiToProduct, Add-AzApiManagementProdu...
Script     0.1.3      Az.AppConfiguration                 {Get-AzAppConfigurationStore, Get-AzAppConfigurationStoreK...
Script     1.0.2      Az.ApplicationInsights              {Get-AzApplicationInsights, New-AzApplicationInsights, Rem...
Binary     1.0.1      Az.ApplicationMonitor               {Set-ApplicationInsightsMonitoringConfig, Get-ApplicationI...
Script     0.1.2      Az.Attestation                      {New-AzAttestation, Get-AzAttestation, Remove-AzAttestation}
Script     1.3.4      Az.Automation                       {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHyb...
Script     2.0.1      Az.Batch                            {Remove-AzBatchAccount, Get-AzBatchAccount, Get-AzBatchAcc...
Script     1.0.1      Az.Billing                          {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzEnrollme...
Script     0.2.7      Az.Blueprint                        {Get-AzBlueprint, Get-AzBlueprintAssignment, New-AzBluepri...
Script     1.4.0      Az.Cdn                              {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-AzCdnProfil...
Script     1.6        Az.CloneVirtualMachine              New-AzVMClone
Script     1.2.1      Az.CognitiveServices                {Get-AzCognitiveServicesAccount, Get-AzCognitiveServicesAc...
Script     3.0.0      Az.Compute                          {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAv...
Script     0.7.0      Az.Compute.ManagedService           ConvertTo-AzVhd
Script     0.7.0      Az.Consumption                      {Get-AzConsumptionBudget, Get-AzConsumptionMarketplace, Ge...
Script     1.0.1      Az.ContainerInstance                {New-AzContainerGroup, Get-AzContainerGroup, Remove-AzCont...
Script     1.1.0      Az.ContainerRegistry                {New-AzContainerRegistry, Get-AzContainerRegistry, Update-...
Script     0.1.0      Az.DataBox                          {Get-AzDataBoxJob, Get-AzDataBoxCredential, Stop-AzDataBox...
Script     0.1.1      Az.DataBoxEdge                      {Get-AzDataBoxEdgeJob, Get-AzDataBoxEdgeDevice, New-AzData...
Script     1.4.1      Az.DataFactory                      {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get-AzDataFa...
Script     1.0.1      Az.DataLakeAnalytics                {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeAnalytic...
Script     1.2.4      Az.DataLakeStore                    {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeSt...
Script     0.7.3      Az.DataMigration                    {New-AzDataMigrationDatabaseInfo, New-AzDataMigrationConne...
Script     0.1.0      Az.DataShare                        {New-AzDataShareAccount, Get-AzDataShareAccount, Remove-Az...
Script     1.0.1      Az.DeploymentManager                {Get-AzDeploymentManagerArtifactSource, New-AzDeploymentMa...
Script     0.7.1      Az.DeviceProvisioningServices       {New-AzIoTDeviceProvisioningService, Get-AzIoTDeviceProvis...
Script     0.7.2      Az.DevSpaces                        {Get-AzDevSpacesController, New-AzDevSpacesController, Rem...
Script     1.0.0      Az.DevTestLabs                      {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolic...
Script     1.1.1      Az.Dns                              {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remove-AzDnsRe...
Script     1.2.2      Az.EventGrid                        {New-AzEventGridTopic, Get-AzEventGridTopic, Set-AzEventGr...
Script     1.4.0      Az.EventHub                         {New-AzEventHubNamespace, Get-AzEventHubNamespace, Set-AzE...
Script     1.1.2      Az.FrontDoor                        {New-AzFrontDoor, Get-AzFrontDoor, Set-AzFrontDoor, Remove...
Script     0.10.6     Az.GuestConfiguration               {Get-AzVMGuestPolicyStatus, Get-AzVMGuestPolicyStatusHistory}
Script     3.0.0      Az.HDInsight                        {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefinition, Wa...
Script     1.0.0      Az.HealthcareApis                   {New-AzHealthcareApisService, Remove-AzHealthcareApisServi...
Script     0.7.0      Az.Insights                         {Get-AzMetricDefinition, Get-AzMetric, Remove-AzLogProfile...
Script     0.7.1      Az.IotCentral                       {New-AzIotCentralApp, Get-AzIotCentralApp, Set-AzIotCentra...
Script     2.0.0      Az.IotHub                           {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGroup, Get-A...
Script     1.3.1      Az.KeyVault                         {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertificate, ...
Script     0.1.2      Az.Kusto                            {New-AzKustoCluster, Get-AzKustoCluster, Remove-AzKustoClu...
Script     1.3.1      Az.LogicApp                         {Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccou...
Script     1.1.1      Az.MachineLearning                  {Move-AzMlCommitmentAssociation, Get-AzMlCommitmentAssocia...
Script     0.7.0      Az.MachineLearningCompute           {Get-AzMlOpCluster, Get-AzMlOpClusterKey, Test-AzMlOpClust...
Script     0.7.2      Az.ManagedServiceIdentity           {New-AzUserAssignedIdentity, Get-AzUserAssignedIdentity, R...
Script     1.0.1      Az.ManagedServices                  {Get-AzManagedServicesAssignment, New-AzManagedServicesAss...
Script     0.7.1      Az.ManagementPartner                {Get-AzManagementPartner, New-AzManagementPartner, Update-...
Script     0.7.1      Az.Maps                             {Get-AzMapsAccount, New-AzMapsAccount, Remove-AzMapsAccoun...
Script     1.0.1      Az.MarketplaceOrdering              {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}
Script     1.1.0      Az.Media                            {Sync-AzMediaServiceStorageKey, Set-AzMediaServiceKey, Get...
Script     0.1.2      Az.MixedReality                     {Get-AzSpatialAnchorsAccount, Get-AzSpatialAnchorsAccountK...
Script     1.4.0      Az.Monitor                          {Get-AzMetricDefinition, Get-AzMetric, Remove-AzLogProfile...
Script     0.1.3      Az.NetAppFiles                      {Get-AzNetAppFilesAccount, New-AzNetAppFilesAccount, Remov...
Script     2.0.0      Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Get-Az...
Script     1.1.0      Az.NotificationHubs                 {Get-AzNotificationHub, Get-AzNotificationHubAuthorization...
Script     1.3.3      Az.OperationalInsights              {New-AzOperationalInsightsAzureActivityLogDataSource, New-...
Script     0.1.6      Az.Peering                          {Get-AzPeering, Get-AzPeerAsn, New-AzPeerAsn, New-AzPeerin...
Script     1.1.3      Az.PolicyInsights                   {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPolicyStateSu...
Script     1.1.0      Az.PowerBIEmbedded                  {Remove-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspa...
Script     1.0.0      Az.PrivateDns                       {Get-AzPrivateDnsZone, Remove-AzPrivateDnsZone, Set-AzPriv...
Script     0.7.0      Az.Profile                          {Disable-AzDataCollection, Disable-AzContextAutosave, Enab...
Script     2.0.1      Az.RecoveryServices                 {Get-AzRecoveryServicesBackupProperty, Get-AzRecoveryServi...
Script     1.1.1      Az.RedisCache                       {Remove-AzRedisCachePatchSchedule, New-AzRedisCacheSchedul...
Script     1.0.2      Az.Relay                            {New-AzRelayNamespace, Get-AzRelayNamespace, Set-AzRelayNa...
Script     0.7.1      Az.Reservations                     {Get-AzReservationOrder, Get-AzReservation, Get-AzReservat...
Script     0.7.6      Az.ResourceGraph                    Search-AzGraph
Script     1.7.1      Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzR...
Script     0.7.3      Az.Search                           {New-AzSearchService, Get-AzSearchService, Set-AzSearchSer...
Script     0.7.6      Az.Security                         {Get-AzSecurityAlert, Set-AzSecurityAlert, Get-AzSecurityA...
Script     1.4.0      Az.ServiceBus                       {New-AzServiceBusNamespace, Get-AzServiceBusNamespace, Set...
Script     2.0.0      Az.ServiceFabric                    {Add-AzServiceFabricClientCertificate, Add-AzServiceFabric...
Script     1.1.0      Az.SignalR                          {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey, New-AzSig...
Script     2.0.0      Az.Sql                              {Get-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlData...
Script     0.1.0      Az.SqlVirtualMachine                {New-AzSqlVM, Get-AzSqlVM, Update-AzSqlVM, Remove-AzSqlVM...}
Script     1.9.0      Az.Storage                          {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStor...
Script     1.2.1      Az.StorageSync                      {Invoke-AzStorageSyncCompatibilityCheck, New-AzStorageSync...
Manifest   1.0.7      Az.StorageTable                     {Add-AzStorageTableRow, Get-AzStorageTableRowAll, Get-AzSt...
Script     1.0.0      Az.StreamAnalytics                  {Get-AzStreamAnalyticsFunction, Get-AzStreamAnalyticsDefau...
Script     0.7.0      Az.Tags                             {Remove-AzTag, Get-AzTag, New-AzTag}
Script     1.0.2      Az.TrafficManager                   {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove-AzTraf...
Script     0.7.0      Az.UsageAggregates                  Get-UsageAggregates
Script     1.5.0      Az.Websites                         {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServ...
```

## Debug output

```

```

## Error output

```

```

**Comment by VeryEarly** [comment] 2019-11-27 03:51
Hi @o-l-a-v ,

the "no expiration" login state and the "one for one" disconnect are by design.

**Comment by o-l-a-v** [comment] 2019-11-27 11:30
> Hi @o-l-a-v ,
> 
> the "no expiration" login state and the "one for one" disconnect are by design.

Ait, thanks for the info. While I can see why this is useful, I think the potential dangers outweights the benefits. It's easy for unexperienced users or just people not knowing about this design desition (me until now), to do stuff on the wrong tenant and/ or subscription. Maybe one should consider to hide this functionality behind some switches or something?

**Comment by VeryEarly** [comment] 2019-11-27 11:33
Hi @o-l-a-v ,

Thanks for the suggestion, you can create another issue with label "feature request" and detail provided, we will have a discussion with our PM to see if and how we can do it.

will close this issue for now.

**Comment by VeryEarly** [comment] 2019-11-27 11:38
> > Hi @o-l-a-v ,
> > the "no expiration" login state and the "one for one" disconnect are by design.
> 
> Ait, thanks for the info. While I can see why this is useful, I think the potential dangers outweights the benefits. It's easy for unexperienced users or just people not knowing about this design desition (me until now), to do stuff on the wrong tenant and/ or subscription. Maybe one should consider to hide this functionality behind some switches or something?

Sorry, delete incorrect context, you can try "Disable-AzContextAutosave" or "Enable-AzContextAutoSave -Scope Progress" to disable this feature or apply it to current powershell session only.

**Closed** 2019-12-03 09:20 UTC
Labels: Azure PS Team, customer-reported
