### ISSUE TITLE
Install-Module AzureRM fails with PackageManagement\Install-Package: Package 'AzureRM.profile' failed to be installed because: A local file header is corrupt.

### ISSUE THREAD

**Issue by lambdakris** [Azure/azure-powershell#2757] opened 2016-08-10 15:25 UTC
I am using a fresh Windows 10 build 1607 and I am getting the following error when trying to install the AzureRM module:
<img width="946" alt="azurerm module installation error" src="https://cloud.githubusercontent.com/assets/15176003/17559663/ea998658-5ed3-11e6-9bbb-cb63d9654d9a.PNG">

**Comment by ljt91** [comment] 2016-08-10 15:29
+1 - Receiving this issue as well.

**Comment by quoctruong** [comment] 2016-08-10 18:59
Hi, @lambdakris please try the following steps:

1.	Install-Module AzureRM.Profile -RequiredVersion 1.0.11
2.	Install-Module AzureRM.Profile -RequiredVersion 2.0.0.0
3.	Install-Module Azure.Storage -RequiredVersion 1.1.5
4.	Install-Module Azure.Storage -RequiredVersion 2.0
5.	Install-Module AzureRM

**Comment by KrishnaV-MSFT** [comment] 2016-08-10 19:23
This problem happens because of the following reason:

1.	AzureRM has lots of dependencies. If you traverse the dependency chain, you will notice different versions of AzureRM.Profile in the dependency chain.
2.	PowerShellGet has a problem installing 2 versions of the same module in 1 Install-Module call

Thanks for reporting the issue. Please use the workaround that @quoctruong mentioned until we fix this issue.

**Comment by ljt91** [comment] 2016-08-10 21:48
@quoctruong thank you for that, I've just tried it however still receiving the follow:

PackageManagement\Install-Package : Package 'AzureRM.profile' failed to be installed because: A local file header is corrupt.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1375 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidResult: (AzureRM.profile:String) [Install-Package], Exception
    + FullyQualifiedErrorId : Package '{0}' failed to be installed because: {1},Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

PackageManagement\Install-Package : Collection was modified; enumeration operation may not execute.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1375 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Comment by markcowl** [comment] 2016-08-10 22:15
@ljt91 @quoctruong @KrishnaV-MSFT @lambdakris Just finished a thread with Krishna and Quoc, this assessment is not correct.  The Gallery is apparently not resolving the dependent module RequiredVersion constraint correctly.

**Comment by markcowl** [comment] 2016-08-10 22:17
This should be resolved when the new version is pushed out (within the hour)

**Comment by markcowl** [comment] 2016-08-10 23:08
@lambdakris @ljt91 @anurse @KrishnaV-MSFT @quoctruong This is now resolved.  The hotfix modules for 2.0 are out.  Please verify, and apologies for the bad experience.  We've adjusted our hotfix policies, and we'll work with the PSGet team to ensure this doesn't happen again when pulling back a module.

**Comment by ljt91** [comment] 2016-08-10 23:21
@markcowl I can confirm that it's resolved from my side. All installed and working. Thank you very much for getting the fix out so quickly.

**Comment by markcowl** [comment] 2016-08-10 23:52
closing for now

**Comment by adumont** [comment] 2017-08-18 10:27
This is happening to me today. Recently installed Powershell 5, on a Windows 7 machine.

PS C:\> Install-Module AzureRM
WARNING: Source Location 'https://www.powershellgallery.com/api/v2/package/AzureRM.Sql/3.3.1' is not valid.
PackageManagement\Install-Package : Package 'AzureRM.Sql' failed to download.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1375 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Users\adumon...ureRM.Sql.nupkg:String) [Install-Package], Excep
   tion
    + FullyQualifiedErrorId : PackageFailedInstallOrDownload,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPac
   kage

PackageManagement\Install-Package : Collection was modified; enumeration operation may not execute.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1375 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallP
   ackage


PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS C:\> Get-InstalledModule

Version    Name                                Type       Repository
-------    ----                                ----       ----------
4.3.1      Azure                               Module     PSGallery
0.4.4      Azure.AnalysisServices              Module     PSGallery
3.3.1      Azure.Storage                       Module     PSGallery
0.4.4      AzureRM.AnalysisServices            Module     PSGallery
4.3.1      AzureRM.ApiManagement               Module     PSGallery
3.3.1      AzureRM.Automation                  Module     PSGallery
3.3.1      AzureRM.Backup                      Module     PSGallery
3.3.1      AzureRM.Batch                       Module     PSGallery
0.13.4     AzureRM.Billing                     Module     PSGallery
3.3.1      AzureRM.Cdn                         Module     PSGallery
0.8.4      AzureRM.CognitiveServices           Module     PSGallery
3.3.1      AzureRM.Compute                     Module     PSGallery
0.2.4      AzureRM.Consumption                 Module     PSGallery
0.2.4      AzureRM.ContainerRegistry           Module     PSGallery
3.3.1      AzureRM.DataFactories               Module     PSGallery
3.3.1      AzureRM.DataLakeAnalytics           Module     PSGallery
4.3.1      AzureRM.DataLakeStore               Module     PSGallery
3.3.1      AzureRM.DevTestLabs                 Module     PSGallery
3.3.1      AzureRM.Dns                         Module     PSGallery
0.4.4      AzureRM.EventHub                    Module     PSGallery
3.3.1      AzureRM.HDInsight                   Module     PSGallery
3.3.1      AzureRM.Insights                    Module     PSGallery
2.3.1      AzureRM.IotHub                      Module     PSGallery
3.3.1      AzureRM.KeyVault                    Module     PSGallery
3.3.1      AzureRM.LogicApp                    Module     PSGallery
0.15.4     AzureRM.MachineLearning             Module     PSGallery
0.7.4      AzureRM.Media                       Module     PSGallery
4.3.1      AzureRM.Network                     Module     PSGallery
3.3.1      AzureRM.NotificationHubs            Module     PSGallery
3.3.1      AzureRM.OperationalInsights         Module     PSGallery
3.3.1      AzureRM.PowerBIEmbedded             Module     PSGallery
3.3.1      AzureRM.profile                     Module     PSGallery
3.3.1      AzureRM.RecoveryServices            Module     PSGallery
3.3.1      AzureRM.RecoveryServices.Backup     Module     PSGallery
3.3.1      AzureRM.RedisCache                  Module     PSGallery
0.2.4      AzureRM.Relay                       Module     PSGallery
4.3.1      AzureRM.Resources                   Module     PSGallery
0.15.4     AzureRM.Scheduler                   Module     PSGallery
3.3.1      AzureRM.ServerManagement            Module     PSGallery
0.4.4      AzureRM.ServiceBus                  Module     PSGallery
0.2.4      AzureRM.ServiceFabric               Module     PSGallery

**Comment by cormacpayne** [comment] 2018-09-25 21:36
@rachelgshaffer would you mind running the following two commands and returning the results?

- `Get-Module -ListAvailable`
- `Install-Module -Name AzureRM -Repository PSGallery`

**Comment by markcowl** [comment] 2018-10-13 00:05
Closing as no repro

**Closed by markcowl** 2018-10-13 00:05 UTC
Labels: Azure PS Team :snail:, More Info :label:

**Comment by ShubhamThakkar** [comment] 2018-10-16 10:47
I tried to install AzSk with the following command : iwr 'https://aka.ms/azsk/install.ps1' -UseBasicParsing | iex

I am getting the following error :

![image](https://user-images.githubusercontent.com/20641150/47011228-01f91700-d15f-11e8-981a-f038b08f17bd.png)
