### ISSUE TITLE
Need event source info for data filtering in *-AzureRmDataCollection

### ISSUE THREAD

**Issue by jianyunt** [Azure/azure-powershell#4786] opened 2017-10-13 21:19 UTC
### Description

By running Enable-AzureRmDataCollection is to allow to collect data for the current user on the current machine.  However sometimes this is not enough. We need to be able to tell from which event source (e.g., modules vs user input) so that we can filter on event source.

The following does not help because Get-AzureRmVM still got collected. 
Disable-AzureRMDataCollection
Get-AzureRmVM
Enable-AzureRMDataCollection

Using $env:Azure_PS_Data_Collection does not do anything difference then Enable-AzureRMDataCollection 

Here is how we turned on:

[Microsoft.Azure.Common.Authentication.AzureSession]::ClientFactory.AddUserAgent(‘Foobar, ‘1.0’) 
 Enable-AzureRMDataCollection

### PowerShell Version

PSVersion                      5.1.14393.1480
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1480
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Module Version

Script     4.3.1      AzureRM
Script     3.3.1      AzureRM.profile 

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

**Comment by markcowl** [comment] 2017-10-16 15:46
For context, I believe the ask here is to make it possible to add additional data on the event source to the existing client-side telemetry.  This would allow determining which calls to generic resource cmdlets come from direct user input and which come form usages of wrapping cmdlets.

**Comment by maddieclayton** [comment] 2018-05-03 22:38
@twitchax ping

**Comment by twitchax** [comment] 2018-05-04 05:09
The method that you describe is the preferred way to indicate event source.  Closing as by design.

**Closed by twitchax** 2018-05-04 05:09 UTC
Labels: Azure PS Team, CloudShell
