### ISSUE TITLE
Set-AzureRmApplicationGatewayRequestRoutingRule not working

### ISSUE THREAD

**Issue by alexsab1** [Azure/azure-powershell#4853] opened 2017-10-25 21:28 UTC
### Cmdlet(s)

Set-AzureRmApplicationGatewayRequestRoutingRule

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

5.1.14393.1770

### Module Version

3.4.0

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

10.0.14393.1770

### Description

I want to modify the HTTP Backend setting for the existing routing rule

Using example provided in the documentation I get immediate response from the powershell call confirming that the change was made, howerver in the Portal the backend settings remains the same

https://docs.microsoft.com/en-us/powershell/module/azurerm.network/set-azurermapplicationgatewayrequestroutingrule?view=azurermps-4.4.1

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction

1. Create new app gate way
2. Configure new routing rule via Azure Portal
3. Create new http backend setting
4. Attempt to change the http backend setting on the existing routing rule via powershell example provided in the article

**Comment by alexsab1** [comment] 2017-10-25 21:42
I'm no longer sure if this issue is just for the Set-AzureRmApplicationGatewayRequestRoutingRule. I also tried Set-AzureRmApplicationGatewayBackendHttpSettings and also get immediate successful return in the console however Azure Portal is never updated. The object that the cmdlet returns is of type Microsoft.Azure.Commands.Network.Models.PSApplicationGateway.

The return object shows that update is applied, but Azure Portal does not show that, even after refreshing it.

**Comment by markcowl** [comment] 2017-10-30 21:41
@alexsab1 I believe this is by design, the Set-ApplicationGatewayRequestRoutingRule is only making an in-memory change to the routing rules in a gateway, you have to pass the resulting value into the ```Set-AzureRmApplicationGateway``` cmdlet, so that the flow looks kind of like:

```
Get-AzureRmApplicationGateway | Set-AzureRmApplicationGatewayRequestRoutingRule | Set-AzureRmApplicationGateway
```

or something similar.

**Comment by markcowl** [comment] 2017-10-30 21:42
Assigning to the network team, as this may be a documentation issue.

**Comment by markcowl** [comment] 2017-10-30 21:42
@DeepakRajendranMsft Can you take a look?

**Comment by alexsab1** [comment] 2017-12-14 17:04
@markcowl Thank you, this can be closed

**Closed** 2018-03-22 00:25 UTC
Labels: Networking
