### ISSUE TITLE
Remove-AzResourceGroup accepts non-resource group ResourceIds

### ISSUE THREAD

**Issue by ghost** [Azure/azure-powershell#9882] opened 2019-08-21 20:13 UTC
I accidentally ran 
```
Remove-AzResourceGroup -Id "/subscriptions/<guid>/resourceGroups/<string>/providers/Microsoft.Storage/storageAccounts/<string>" -Force
```
when I meant to use `Remove-AzResource`.

Instead of rejecting that ResourceId since it points to a storage account and not a resource group, `Remove-AzResourceGroup` deleted the resource group that storage account was in. 

P.S. This is using version 2.5.0 for Az and 1.6.1 for Az.Resources

**Comment by cormacpayne** [comment] 2019-08-22 16:52
@jowilkes-msft thanks for filing this issue -- it looks like we're accepting any resource id, parsing the resource group name from the string, and deleting that resource group, which doesn't follow what the help for the `-Id` parameter states:

> _Specifies the ID of resource group to remove._

@Tiano2017 just to confirm with you, is it expected that the user can provide the resource id for _any_ resource and we would delete the corresponding resource group, or should we be throwing if the user is providing an id that isn't that of a resource group?

**Comment by o-l-a-v** [comment] 2020-02-23 18:10
Has this been fixed/ looked into yet? Looks like unwanted behavior that can cause serious harm.

**Comment by ifeoluwaokunoren** [comment] 2020-03-19 02:32
Thanks for reporting this issue. 

Currently this is actually by design - where for `id` - we currently accept either resourcegroupid or resourceId. In the case where the user provides a resourceId,  we extract the resource group id from the resourceId. It's understandable that this behavior, could either be helpful or harmful depending on the scenario it is being used.

However, one check we've put in place, is that for scenario where the user provides a resourceId for this command - `Remove-AzureRmResourceGroup - id {resourceId}`, there's actually a prompt that asks the user to confirm if they actually want to delete the *resource group* but I understand, you wouldn't get that prompt since you're using a `-force`

This behavior can also be seen for example in `Get-AzureRmResourceGroup -id {resourceId}` but you're right, this can cause unwanted effects - especially since we extract the resourcegroupId from the resourceId, even in cases where the resourceId is invalid.

I'd add to our backlog, so we can make a fix to provide an additional guard rail for users for this across the affected commands for actions on Resource Groups.

**Comment by ifeoluwaokunoren** [comment] 2020-05-01 22:16
Closing issue since PR with fix has been merged.

**Closed by ifeoluwaokunoren** 2020-05-01 22:16 UTC
Labels: ARM, Service Attention
