### ISSUE TITLE
ARM deployment of HDInsight cluster with script action fails

### ISSUE THREAD

**Issue by maciejKopec** [Azure/azure-powershell#1954] opened 2016-03-16 14:36 UTC
I have an ARM template that deploys Spark cluster. It's similar to [https://github.com/Azure/azure-quickstart-templates/tree/master/hdinsight-linux-run-script-action](https://github.com/Azure/azure-quickstart-templates/tree/master/hdinsight-linux-run-script-action). The difference is that I'm using blob storage with SAS as a location for my script. To pass SAS token to template I'm using the approach taken from Azure Resource Group deployment project so my script action definition in json template looks like: `{
                  "name": "my custom script",
                  "uri": "[concat(parameters('_artifactsLocation'), '/my-script.sh', parameters('_artifactsLocationSasToken'))]",
                  "parameters": ""
                }`. 
The deployment succeeds if I run it from machine where I have Microsoft Azure SDK for .NET 2.8.2.1 installed (it comes with AzureRM.Resources 1.0.4). On CI machine I've installed the latest Azure Powershell module from PowerShellGallery and for now AzureRM.Resources version is 1.0.5. On this machine my deployment script fails and the error message I get from Azure audit logs is:

> DeploymentDocument 'CsmDocument_2_0' failed the validation. Error: 'Script Action location cannot be accessed Uri : https://mystorage.blob.core.windows.net/mycontainer/my-script.sh?sv=2015-04-05&sr=c&sig=lJudtEuUHtSdgh11Vhc/qQ92fbTNfQuFvXWbgfx1MpM=&spr=https,http&se=2016-03-16T09:31:16Z&sp=r, ErrorMessage : The remote server returned an error: (403) Forbidden.' 

Please look that SAS token has unescaped slash, colons and comma instead of e.g. %3A and %2C.

**Comment by markcowl** [comment] 2016-03-16 22:13
@shefaliv Can you have the appropriate HDInsight folks take a look?

**Comment by dulems** [comment] 2016-03-17 20:48
The issue is the SAS key expired yesterday (Wed, 16 Mar 2016 09:31:16 GMT). This is a user error.

**Comment by maciejKopec** [comment] 2016-03-19 20:09
Of course in the url I pasted the storage name and the container was modified because I don't want to expose it so please don't expect it will work. Just to describe you shortly my deployment process: 
1. Copy all sh scripts from local dir to blob storage.
2. Create SAS token for blob container in which scripts are located (with expiry time + 4h).
3. Pass the location and SAS token (of SecureString type) as dynamic parameters to New-AzureRmResourceGroupDeployment

All this logic is part of standard script provided by Microsoft when you create Azure Resource Group deployment project - I just used this 'upload artifacts' pattern that was originally implemented for uploading DSC resources.

As I said SAS token is created every time I run deployment so please don't focus on expiration date in the url.

This whole deployment runs without any problems when I have Azure SDK installed. When I uninstall it and install Azure Powershell from the gallery then I have a failure with aforementioned error message. My very quick assumption is that in new version some bug was introduced and some unnecessary uri unescape happens.
If you really want me to provide you the script on blob storage with SAS I can do that.

**Comment by dulems** [comment] 2016-03-20 19:26
I see. Do you have the name of the failed HDInsight cluster and the approximate time when the deployment failed. I want to check what format of the SAS token that our resource provider receives.

In addition, you don't need to use SAS if your scripts are stored in a storage account that is linked to the provisioned cluster.

**Comment by maciejKopec** [comment] 2016-03-22 21:37
You can look at 'clusterfordulems' that failed with the same message just a few minutes ago. I will also run this deployment once again when I reinstall Azure SDK and it should be ok so you will be able to compare it.

BTW I've read about not using SAS but I couldn't make it work. Could you please show me how this uri should be composed then? Should I use wasb protocol instead of http?

**Comment by dulems** [comment] 2016-03-22 23:14
I looked at our log and yes, it really looks like the newer SDK caused the issue. Since this cmdlet (New-AzureRmResourceGroupDeployment) is maintained by a different team, we might need to contact them for help debugging the issue.

At the same time, can you please try the following steps to remove the need for SAS keys?

1) Link your storage account (cdf****storage) to the created cluster in your ARM template.
2) Use the following script uri:
https://cdf****storage.blob.core.windows.net/hdi-scripts/create-user-dir.sh

These steps should definitely work. If not, you can try the following URI:
wasbs://hdi-scripts@cdf****storage.blob.core.windows.net/create-user-dir.sh

Let me know if you run into any issues.

**Comment by maciejKopec** [comment] 2016-03-24 13:11
This approach without SAS token works (surprisingly for me because I could swear I tried it before). 
So in my case it's solved but if somebody wants to provide uri with escaped characters it will fail.

**Comment by dulems** [comment] 2016-03-24 13:15
Great to hear this!

@shefaliv Now that the reported issue is resolved, can you please engage the right person for debugging New-AzureRmResourceGroupDeployment?

**Comment by shefaliv** [comment] 2016-03-24 15:32
@markcowl Can you please direct this thread to the appropriate person?

**Comment by maddieclayton** [comment] 2018-02-27 23:33
Closed as it seems as if the issue is resolved. Please reopen if there is still an issue.

**Closed by maddieclayton** 2018-02-27 23:33 UTC
Labels: HDInsight
