### ISSUE TITLE
Set-AzureRmResource can  set  'Memory Limit' Rule rule but not 'status code' rule  for Auto Heal Rule

### ISSUE THREAD

**Issue by lovelangy** [Azure/azure-powershell#19289] opened 2022-08-23 04:16 UTC
### Description

I followed the https://docs.microsoft.com/en-us/azure/templates/microsoft.web/sites/config-web?pivots=deployment-language-arm-template#statuscodesbasedtrigger-1, 

```powershell
$props = @{
    autoHealEnabled =  $true
    autoHealRules =  @{
        triggers =  @{
            requests =  $null
            privateBytesInKB =  8888888
            statusCodes =  @(
             {
                    status =  500
                    path =  ""
                    count =  50
                    timeInterval =  "00:05:00"
                })
            statusCodesRange =   @()
            slowRequests =  $null
            slowRequestsWithPath =  @()
        }
        actions =  @{
            actionType = "Recycle"
            minProcessExecutionTime =  "00:02:00"
        }
        }
    };

 Auto Heal is turned on and 'Memory Limit' Rule is configurated, However the  Status Codes rule is missing.
Set-AzureRmResource -Force -Properties -$props -ResourceGroupName $mygroup -ResourceName "$mywebsitename/web" -ResourceType "Microsoft.Web/sites/config"
``` 

![image](https://user-images.githubusercontent.com/5171614/186068126-aa741689-36fb-48b0-87e9-d77c2be97f32.png)

### Issue script & Debug output

```PowerShell
n/a
```

### Environment data

```PowerShell
$PSVersionTable 

Name                           Value                                                                                                                                                                     
----                           -----                                                                                                                                                                     
PSVersion                      5.1.22000.832                                                                                                                                                             
PSEdition                      Desktop                                                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                   
BuildVersion                   10.0.22000.832                                                                                                                                                            
CLRVersion                     4.0.30319.42000                                                                                                                                                           
WSManStackVersion              3.0                                                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                                                       
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
PS C:\WINDOWS\system32> Get-Module Az*

ModuleType Version    Name                                ExportedCommands                                                                                                                               
---------- -------    ----                                ----------------                                                                                                                               
Script     4.6.0      AzureRM.Profile                     {Add-AzureRmEnvironment, Clear-AzureRmContext, Clear-AzureRmDefault, Connect-AzureRmAccount...}                                                
Script     5.5.2      AzureRM.Resources                   {Export-AzureRmResourceGroup, Find-AzureRmResource, Find-AzureRmResourceGroup, Get-AzureRmADAppCredential...}
```

**Comment by navba-MSFT** [comment] 2022-08-29 07:13
@lovelangy Closing this as duplicate of https://github.com/Azure/azure-powershell/issues/19288. 

issue will be worked and discussed on the other thread. https://github.com/Azure/azure-powershell/issues/19288.

**Closed by navba-MSFT** 2022-08-29 07:13 UTC
Labels: bug, ARM - Core, customer-reported, CXP Attention
