### ISSUE TITLE
Releases on Powershell Gallery

### ISSUE THREAD

**Issue by kvaes** [Azure/azure-powershell#3178] opened 2016-11-05 21:17 UTC
The version that's listed on powershell gallery is quite "old" (August). Would it be possible to publish new releases to the gallery too?

Thanks in advance!

**Comment by kilasuit** [comment] 2016-11-06 04:30
@kvaes - What version is it that you are seeing on the PowerShell Gallery?

When I run `Find-Module -Name AzureRM` I get the 3.1.0 release returned from the PowerShell Gallery which is the latest release. I also get the 3.1.0 release returned for the Azure module as per the release notes at https://github.com/Azure/azure-powershell/releases/tag/v3.1.0-November2016

**Comment by kvaes** [comment] 2016-11-06 15:27
My bad @kilasuit , I should have been more clear, I was talking about the .net core for AzureRM ;  

PS C:\Users\karim> find-module -name AzureRM.NetCore.Preview

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
0.3.4      AzureRM.NetCore.Preview             PSGallery            [PowerShell Core Edition] Azure Resource Manager...

That one has been "stuck" on 0.3.4 for a while now => https://www.powershellgallery.com/packages/AzureRM.NetCore.Preview/0.3.4 

Where the releases on github show a version up to 3.10 => https://github.com/Azure/azure-powershell/releases

**Comment by kvaes** [comment] 2016-11-06 15:28
Maybe I should tag @cormacpayne for this one too, as his user is linked to the latest release. :)

**Comment by cormacpayne** [comment] 2016-11-07 17:29
@kvaes Hey Karim, `AzureRM.NetCore.Preview` is a module for Linux and Mac that contains Profile and ResourceManager cmdlets. The `AzureRM` module released last week as part of our monthly Azure PowerShell release contains _all_ of the service cmdlets.

**Comment by kvaes** [comment] 2016-11-07 20:02
So the AzureRM module is now NetCore based?
The objective is to run all ARM cmdlets from a linux based system...

**Comment by markcowl** [comment] 2016-11-07 21:40
No, the AzureRm.NetCore.Preview module is NetCore-based, and AzureRM depends on .Net desktop CLR.  We currently have separate modules for desktop and netcore versions of PowerShell cmdlets.  The plan is to unify sometime next year.

**Comment by kvaes** [comment] 2016-11-11 07:23
So to circle back to the start of the issue... The netcore.preview is not updated on a regular basis. So if I want to test the new versions, I cannot use the install-module.

**Comment by markcowl** [comment] 2016-11-22 03:13
NetCore.Preview has not been updated recently.  It is planned for next year to produce NetCore and Desktop libraries at the same time.

Closing as duplicate of  #2825

**Closed by markcowl** 2016-11-22 03:13 UTC
