### ISSUE TITLE
Add-AzureRmApplicationGatewayRedirectConfiguration results in 502 error and unusable portal

### ISSUE THREAD

**Issue by CodedBeard** [Azure/azure-powershell#4383] opened 2017-07-28 11:51 UTC
### Cmdlet(s)
Add-AzureRmApplicationGatewayRedirectConfiguration
### PowerShell Version
Name                           Value
----                           -----
PSVersion                      5.1.15063.483
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.483
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Module Version
4.2.1
### OS Version
BuildVersion                   10.0.15063.483
### Description
I've been attempting to review replacing our current external load balancer with application gateway. I successfully setup the gateway, and had the site working correctly. The only thing that was missing from our current load balancer setup, was http > https redirect. So i followed the instructions from [here](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/application-gateway/application-gateway-configure-redirect-powershell.md) to enable the redirect. All of the commands completed without error, but the site was no longer accessible, instead returning a 502 error. When I checked, suddenly the health probes are reporting an error (there isn't one) and attempting to make any changes within the Azure portal to the application gateway, now results in an error "Request Routing Rule <removed>/requestRoutingRules/rule02 must reference a BackendAddressPool.". As I thought maybe the docs had a typo, I went back and attempted to provide a BackendAddressPool via the PowerShell commands, but this returned an error that a redirect cannot have a BackendAddressPool "<removed>/requestRoutingRules/rule02 with RedirectConfiguration cannot reference a BackendAddressPool"
I confirmed that the redirect was working, but it's not much use when it appears to break the site routing, and the azure portal itself. I then disabled the redirect rule, and the 502 error instantly disappeared and the site was accessible again.

### Debug Output
N/A
### Script/Steps for Reproduction
Create a new application gateway via the portal, and configure so that a site can be successfully accessed without redirect.
Follow the instructions from [here](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/application-gateway/application-gateway-configure-redirect-powershell.md) to enable the redirect.
Observe that now, no changes can be made via portal due to error, and that site now cannot be accessed.
Disable rule and Observe that everything starts working again.

**Comment by cormacpayne** [comment] 2017-07-28 16:24
@akshaysngupta Hey Akshay, would you mind taking a look at this issue?

**Comment by fbuser1** [comment] 2018-04-11 12:55
+1

**Comment by EvgenyAgafonchikov** [comment] 2019-02-18 09:42
Checked on the latest Az module version (AzureRm was replaced with Az) and it looks like redirect works as expected: I'm getting Http->Https redirect.

As the documentation link referred by @CodedBeard is no more valid (likely the file was renamed or moved), I used these two articles to setup ApplicationGateway with redirect:
- https://docs.microsoft.com/en-us/azure/application-gateway/quick-create-portal (Replaced `-TypeHandlerVersion 1.4` -> `-TypeHandlerVersion 1.8`)
- https://docs.microsoft.com/en-us/azure/application-gateway/redirect-http-to-https-powershell

@CodedBeard, could you please confirm there is no repro on the latest version? If the issue still could be reproed, please share detailed sequence of PS cmdlets or portal actions so we could try to repro exactly the same thing.

**Comment by CodedBeard** [comment] 2019-02-18 16:37
@EvgenyAgafonchikov No idea. To be honest I had completely forgotten about this, as it hadn't been fixed for ages we eventually just went with not publishing HTTP at all, and relying on users searching for the URL instead, which has worked fine as we have never received any complaints about it, probably because all of our sites use HSTS and so load the HTTPS endpoint from the browser anyways after the first visit.

**Comment by EvgenyAgafonchikov** [comment] 2019-02-19 05:02
@CodedBeard, thanks for updating on this.
As things seem to work now, and I cannot reproduce the same, closing the issue. Feel free to reopen if the repro occurs.

**Closed by EvgenyAgafonchikov** 2019-02-19 05:02 UTC
Labels: Network, Network - Application Gateway, Service Attention
