### ISSUE TITLE
Get-AzureRMResource -ResourceGroupName failing

### ISSUE THREAD

**Issue by MattAllison** [Azure/azure-powershell#3415] opened 2017-01-24 19:18 UTC
### Cmdlet(s)
Get-AzureRMResource

### PowerShell Version
PSVersion                      5.0.10586.117

### Module Version
ModuleType Version    Name
---------- -------    ----
Script     2.5.0      AzureRM.profile
Script     3.5.0      AzureRM.Resources
Script     2.5.0      AzureRM.Storage

### OS Version
BuildVersion                   10.0.10586.117

### Description
Get-AzureRMResource failing when using only the -ResourceGroupName parameter

### Debug Output
PS Scripts:\> Get-AzureRMResource -ResourceGroupName securityData
Get-AzureRmResource : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Get-AzureRMResource -ResourceGroupName securityData
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-AzureRmResource], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.Ge
   tAzureResourceCmdlet

### Script/Steps for Reproduction
run the Get-AzureRMResource command with the -ResourceGroupName parameter.  The error is the same whether the resource group exists or not.

**Comment by cormacpayne** [comment] 2017-03-03 22:20
@MattAllison this looks to be a duplicate of issue https://github.com/Azure/azure-powershell/issues/3539

Closing this issue so that we can track the status on the other.

**Closed by cormacpayne** 2017-03-03 22:20 UTC
