### ISSUE TITLE
Get-AzMaintenanceUpdate returns no data

### ISSUE THREAD

**Issue by ghost** [Azure/azure-powershell#10936] opened 2020-01-20 08:09 UTC
## Description
We didn't got any response when we run Get-AzMaintenanceUpdate. We can get 'impactType: None' if we run az maintenance update list.
Could you please tell us the expected behavior of Get-AzMaintenanceUpdate  when there is no maintenance data.

## Steps to reproduce

```powershell
> Get-AzMaintenanceUpdate `
>>    -ResourceGroupName $strResourceGroup `
>>    -ResourceName $strResource `
>>    -ResourceType hosts `
>>    -ResourceParentName $strResourceParent `
>>    -ResourceParentType hostGroups `
>>    -ProviderName Microsoft.Compute
> az maintenance update list -g $strResourceGroup --resource-name $strResource --resource-type hosts --provider-name Microsoft.Compute --resource-parent-name $strResourceParent --resource-parent-type hostGroups
[
  {
    "impactDurationInSec": 0,
    "impactType": "None",
    "maintenanceScope": "Host",
    "notBefore": "2020-02-13T14:27:54.159038+00:00",
    "resourceId": "/subscriptions/XXXXX/resourcegroups/XXXX/providers/Microsoft.Compute/hostGroups/XXXX/hosts/XXXX",
    "status": "Pending"
  }
]
```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

```

```

**Comment by dingmeng-xue** [comment] 2020-01-23 00:18
It belongs to Maintenance module. We are looking into it.

**Comment by juyama** [comment] 2020-01-31 05:48
@dingmeng-xue could you please tell me any update?

**Comment by juyama** [comment] 2020-02-14 06:32
@dingmeng-xue We have confirmed that Get-AzMaintenanceUpdate returns no response although there is maintenance schedule. We can get the schedule using by "az maintenance" only.

**Comment by dingmeng-xue** [comment] 2020-02-14 07:10
@juyama, thanks for your sharing. If so, it should be an issue. I forward it to Maintenance team.

**Comment by juyama** [comment] 2020-02-17 05:42
This issue happened on 0.1.1-preview, but it seems to be fixed on 0.1.2-preview. Is this known issue?

**Comment by balauppaloori** [comment] 2020-05-11 22:24
In 1.0.0 this is still an issue. I confirmed it in Azure Portal Cloud Shell

**Comment by SatishBoddu-MSFT** [comment] 2021-10-24 00:50
Hello @balauppaloori , @ghost, @dingmeng-xue 
I see that this issue is opened a long time ago and no further activity had taken place. So wanted to check if you are still looking for assistance on this query? Please let us know.

**Closed** 2021-11-17 08:02 UTC
Labels: Service Attention, customer-reported, Maintenance, needs-author-feedback, no-recent-activity
