### ISSUE TITLE
Get-AzureRMResource throws Storage account: xxx not found

### ISSUE THREAD

**Issue by julioct** [Azure/azure-powershell#2895] opened 2016-09-03 15:47 UTC
### Cmdlet(s)
Get-AzureRMResource

### PowerShell Version
5.1.14393.0

### Module Version
1.3.2

### OS Version
10.0.14393.0

### Description
Get-AzureRMResource throws Storage account: <thestorageaccountname> not found. Selected Connection 'ServicePrincipal' supports storage account of Azure Resource Manager type only.

### Debug Output
[DebugOutput.txt](https://github.com/Azure/azure-powershell/files/453458/DebugOutput.txt)

### Script/Steps for Reproduction
1. Install Azure Powershell
2. Register the machine as a VSTS build agent
3. Create a VSTS build definition
4. Add the Azure File Copy task to the build definition
5. Configure the task with:
	Source: <a local directory>
	Azure connection type: Azure Resource Manager
	Azure RM Subscription: an available Azure subscription
	Destination Type: Azure Blob
	RM Storage Account: the storage account name
	Container Name: the container name
	Blob Prefix: some prefix
	Storage Container SAS Token: some name
6. Run the build

EXPECTED: The files in the specified source directory get uploaded to the specified storage container
ACTUAL: You get an error: Storage account: powerappsci not found. Selected Connection 'ServicePrincipal' supports storage account of Azure Resource Manager type only.

The actual call being made by the VSTS task looks like this:
$azureStorageAccountResourceDetails = (Get-AzureRMResource -ErrorAction Stop) | Where-Object { ($_.ResourceType -eq $ARMStorageAccountResourceType) -and ($_.ResourceName -eq $storageAccountName)}

**Comment by julioct** [comment] 2016-09-03 15:50
The actual error that comes from Azure seems to be this:

The api-version '2016-09-01' is invalid. The supported versions are '2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.

**Comment by markcowl** [comment] 2016-09-06 05:19
@julioct I believe this is related to #2891 .  This should have been fixed by a service side deployment, but there is an underlying issue that should eb fixed to prevent a recurrence  Closing as a duplicate of that issue.

If you are still seeing these symptoms, please let us know.

**Closed by markcowl** 2016-09-06 05:19 UTC
