### ISSUE TITLE
Get-AzKeyVaultSecret returns System.ArgumentOutOfRangeException for 

### ISSUE THREAD

**Issue by qinl-li** [Azure/azure-powershell#13469] opened 2020-11-09 21:50 UTC
## Description

Both portal and CLI are able to list the secret

## Steps to reproduce
Create a secret using portal or cli and set the expiration date to be "9999-12-31 23:59:59"

```powershell
then run Get-AzKeyVaultSecret
```

## Environment data

```

```

## Module versions

```powershell
2.2.0      Az.KeyVault
```

## Debug output

```

```
DEBUG: AzureQoSEvent: CommandName - Get-AzKeyVaultSecret; IsSuccess - False; Duration - 00:00:07.4155737;; Exception -
System.ArgumentOutOfRangeException: The added or subtracted value results in an un-representable DateTime.
Parameter name: value
   at Microsoft.Azure.Commands.KeyVault.Models.KeyVaultDataServiceClient.GetSecrets(KeyVaultObjectFilterOptions
options)
   at
Microsoft.Azure.Commands.KeyVault.GetAzureKeyVaultSecret.<>c__DisplayClass39_0.<GetAndWriteSecrets>b__0(KeyVaultObjectF
ilterOptions options)
   at
Microsoft.Azure.Commands.KeyVault.Models.KeyVaultCmdletBase.GetAndWriteObjects[TObject](KeyVaultObjectFilterOptions
options, Func`2 getObjects)
   at Microsoft.Azure.Commands.KeyVault.GetAzureKeyVaultSecret.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 1:22:52 PM - GetAzureKeyVaultSecret end processing.
## Error output

```

```

**Comment by isra-fel** [comment] 2020-11-11 05:15
Cannot reproduce

```powershell
C:\> Get-AzKeyVaultSecret -VaultName yemingkv09

Vault Name   : yemingkv09
Name         : 9999
Version      :
Id           : https://yemingkv09.vault.azure.net:443/secrets/9999
Enabled      : True
Expires      : 9999/12/31 11:59:59 PM
Not Before   :
Created      : 2020/11/11 5:12:20 AM
Updated      : 2020/11/11 5:12:53 AM
Content Type :
Tags         :
```

Please try Az.KeyVault 3.0.0 and paste the full debug output, including the HTTP response.
Thanks

**Comment by isra-fel** [comment] 2020-11-11 05:26
I guess the when you set the expire time, the timezone was not UTC but UTC -x, which made the time LATER than "9999-12-31 23:59:59". Could you confirm it?

**Comment by isra-fel** [comment] 2020-11-13 02:34
Closing the issue as it is working as designed. Thanks

**Closed by isra-fel** 2020-11-13 02:34 UTC
Labels: KeyVault, Service Attention, needs-author-feedback
