### ISSUE TITLE
Access to "resources.azure.com" was denied

### ISSUE THREAD

**Issue by sushilz** [Azure/azure-powershell#20486] opened 2022-12-20 09:47 UTC
### Description

I am unable to login to resource manager as getting  "Access to resources.azure.com was denied", same issue on all browser. so no browser issue.

![image](https://user-images.githubusercontent.com/70128123/208650909-80f00b99-31f5-4f51-8bdd-cec934cab6cb.png)

**Comment by dingmeng-xue** [comment] 2022-12-20 12:27
Hi @sushilz , could you explain how you access that page? Which docs are you referencing?

**Comment by sushilz** [comment] 2022-12-20 12:37
> 

Hello Dingmeng-xue,

I simply goto resources.azure.com to modify our arm template but it kicked me out of it and shows above message mentioned in screenshot.
After clearning cache then it allowed me first time to login but if I select something it throws me out hence I logout myself and tried to login back and I get authentication call too but it did not help me another time.

**Comment by cconkrig** [comment] 2022-12-20 21:16
Same for us. Seems to have started recently.  Thought it was just our tenant/account. I am a Global Admin.

**Comment by dingmeng-xue** [comment] 2022-12-21 03:30
@sushilz and @cconkrig , I can access that website now. Your issue may be due to service outage. If you still have the problem, you have to leverage other channel. Azure PowerShell team doesn't have idea which team is managing it.

**Comment by sushilz** [comment] 2022-12-21 03:41
/unresolve

please can you tag the team who can help us out. I am still having an issue. earlier it used to work.

**Comment by dingmeng-xue** [comment] 2022-12-21 05:01
@sushilz , could you explain which cmdlet needs you access resources.azure.com? The tag is added according to issue cmdlet or module.

**Comment by sushilz** [comment] 2022-12-21 06:28
@dingmeng-xue  I do not use cmdlet to access. I try to open from browser. you can suggest which suitable tag I can mention.

**Comment by dingmeng-xue** [comment] 2022-12-21 06:34
Sorry @sushilz , you reported issue to wrong place. Azure PowerShell repo only supports all cmdlets for Azure service.  `resources.azure.com` is an web application rather than a service. No tag is for that app. We have no idea which team manages that website either. I have to close this issue now. Let me know if you have other question.

**Closed by dingmeng-xue** 2022-12-21 06:34 UTC
Labels: question, customer-reported, needs-team-attention

**Comment by BaMi83** [comment] 2023-01-09 19:02
We have the same issue since a couple of weeks, i think i found the problem but i'm not really sure.
when i login with an account which is a full account in the same tenant i can login to resource.azure.com but when i use my guest account from our other tenant i get this error as well, we have enabled MCAS in that tenant (guest account) i believe the issue is related to MCAS.

Do you have MCAS enabled and using a guest account?
