### ISSUE TITLE
SDK v2.0 : New-AzureRmResourceGroup : Could not load file or assembly 'Microsoft.Rest.ClientRuntime.Azure.Authentication'

### ISSUE THREAD

**Issue by whilke** [Azure/azure-powershell#2747] opened 2016-08-09 00:06 UTC
Looks like a new SDK version just hit, getting this error on several different OS versions:

New-AzureRmResourceGroup : Could not load file or assembly 'Microsoft.Rest.ClientRuntime.Azure.Authentication,
Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation

**Comment by markcowl** [comment] 2016-08-09 00:51
@whilke How did you install the SDK?  This is likely a version mismatch between installed SDK versions, can you execute ```Get-Module -ListAvailable```  when this occurs?

**Comment by whilke** [comment] 2016-08-09 02:47
@markcowl came in via the normal web platform installer channel. Seems to have installed a build that was released just today though it lists an update date of 7/11.

 (Get-Module -ListAvailable | Where-Object{ $_.Name -eq 'Azure' })

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   2.0.0      Azure                               {Get-AzureAutomationCertificate, Get-AzureAutomationConnection, New-AzureAutomationConnection, R...

**Comment by sjkp** [comment] 2016-08-09 08:57
I have the same error. On several machines update through web platform installer, that doesn't list this as a new release
![image](https://cloud.githubusercontent.com/assets/3397744/17510609/ff50da1a-5e1f-11e6-93ac-3c81c0b66537.png)

**Comment by whilke** [comment] 2016-08-09 12:07
Anyone have a link to the 1.6 (previous version) installer? Our deployment system is down currently because of this issue.

**Comment by sjkp** [comment] 2016-08-09 12:08
You can download if from the release page

**Comment by guibirow** [comment] 2016-08-09 12:25
I'm facing the same issue, when I downgrade to version 1.6 it works fine.

**Comment by christofferjerrebo** [comment] 2016-08-09 12:48
I can confirm downgrade to v1.6 works, as commented by @guibirow

**Comment by guibirow** [comment] 2016-08-09 13:25
Just to add an extra information, when updated to V2, the following error happens:

Command
```
Login-AzureRmAccount
Set-AzureRmCurrentStorageAccount -ResourceGroupName $TemplateResourceGroup -Name $TemplateStorageAccount
```
-------------------------------------------------------------------------
Error:
```
Set-AzureRmCurrentStorageAccount : Could not load file or assembly 'Microsoft.Rest.ClientRuntime.Azure.Authentication, Version=2.0.0.0, Culture=neutral, 
PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
At line:70 char:5
+     Set-AzureRmCurrentStorageAccount -ResourceGroupName $TemplateReso ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmCurrentStorageAccount], FileLoadException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Management.Storage.SetAzureRmCurrentStorageAccount
```

**Comment by markcowl** [comment] 2016-08-09 19:34
We have a root cause for the issue.  A hotfix will be forthcoming.

**Comment by markvsql** [comment] 2016-08-09 20:08
Will this hotfix apply to Azure Automation as well? I am getting this error trying to create a Resource Group with a Powershell Workflow runbook after upgrading several Powershell Modules in Azure Automation to their latest version.

**Comment by markcowl** [comment] 2016-08-09 21:28
Yes, we will push out new installers and new modules.

**Comment by markcowl** [comment] 2016-08-09 21:30
Meanwhile, we have delisted the AzureRM and Azure modules and pulled back the msi update.  Individual modules have not been delisted.

**Comment by marckean** [comment] 2016-08-10 02:43
See http://screencast.com/t/dXo7juaBnH can't run Get-AzureRmVM either.

**Comment by jeffpatton1971** [comment] 2016-08-10 17:20
For the record I have a clean install from webpi that I did yesterday on a freshly installed windows laptop, I do not see this issue. is there clarification on what the actual cause might be? Are the folks that are getting this error all upgrading? it seems that way from the handful of comments I read through.

**Comment by edtheshed** [comment] 2016-08-10 17:24
@jeffpatton1971  It would appear I definitely got this error from upgrading. My CI process started to fail after the update to azure powershell 2.0, 2 days ago, and after uninstalling and installing 1.6, it's back to normal.

**Comment by guibirow** [comment] 2016-08-10 18:42
I got this error on a clean install of v2 and also on upgrade from 1.6 to 2. from WebPI and from PS command line, both fails.
When downgraded worked fine.
@jeffpatton1971, yesterday they rolled-back to previous version, see if you installed the V2 or V1.6

**Comment by jeffpatton1971** [comment] 2016-08-10 18:44
Interesting we talked a little about this internally and a couple of us did fresh installs and didn't hit this whereas a few of us did upgrades and did see this issue

Get Outlook for Android<https://aka.ms/ghei36>



On Wed, Aug 10, 2016 at 1:42 PM -0500, "Diego" <notifications@github.com<mailto:notifications@github.com>> wrote:


I got this error on a clean install of v2 and also on upgrade from 1.6 to 2. from WebPI and from PS command line, both fails.
When downgraded worked fine.
@jeffpatton1971<https://github.com/jeffpatton1971>, yesterday they rolled-back to previous version, see if you installed the V2 or V1.6

-

**Comment by jeffpatton1971** [comment] 2016-08-10 18:51
@guibirow just noticed your second comment, to my knowledge i'm running the latest

ModuleType Version    Name
---------- -------    ----
Manifest   2.0.2      AzureRM.Resources

**Comment by marckean** [comment] 2016-08-10 20:19
Could be related or not, @jeffpatton1971 i noticed you did a fresh install of Windows, you would have Windows 10 Anniversary edition I'm assuming. I'm on Windows 10 yet to upgrade to Anniversary edition, i tried upgrading yesterday and had to roll back half way due to my Surface getting stuck on "windows 10 anniversary working on updates 32% don't turn off your pc" didn't progress further than 32% 

So maybe Windows 10 Anniversary edition has other updates that allow the Azure PowerShell module v2.0.0 to function.

**Comment by jeffpatton1971** [comment] 2016-08-10 20:21
I'm on windows 10 enterprise...don't think I'm on the anniversary yet...?

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by markcowl** [comment] 2016-08-10 23:23
This is now resolved.  Hotfixes are on webpi and the gallery.  The root cause was an unsigned assembly in the modules.  It's unclear whether this resulted from a breaking change in how assemblies are loaded in powershell,  as machiens with version 5 rtm and earlier of powershell did not exhibit this isssue.  New build safegaurds should prevent this from recurring.

**Comment by markcowl** [comment] 2016-08-10 23:50
Closing as this is resolved.  Please file an issue if you see a recurrence

**Closed by markcowl** 2016-08-10 23:50 UTC
Labels: Investigate, Team
