### ISSUE TITLE
Get-AzsVolume not reporting correctly when monitoring repair status after node reboots

### ISSUE THREAD

**Issue by asbjorn-wiik** [Azure/azure-powershell#8821] opened 2019-03-21 14:33 UTC
Hi 

I decided to try using Get-AzsVolume 
Get-AzsVolume -ScaleUnit S-Cluster -StorageSubSystem S-Cluster.InternalAzureStackFQDN | Select-Object VolumeLabel, OperationalStatus, HealthStatus, RepairStatus | sort VolumeLabel to monitor status of Azure Stack Volumes when draining and rebooting nodes, instead of using PEP session and running get-virtualdisk -cimsession s-cluster; get-virtualdisk -cimsession s-cluster | get-storagejob.

This was working very well until the get-storagejob in PEP returned all volumes with operational statue OK. When this happen in PEP the Get-AzsVolume seemed to stop updating the return. It was returning repair status 98%.

Hope this is something that will be fixed

**Comment by vladimir-shcherbakov** [comment] 2019-03-22 21:50
@bganapa Could you take a look?

**Comment by bganapa** [comment] 2019-03-22 23:04
Thanks @vladimir-shcherbakov  for looping me in @zyxyoshine Can you please comment and track a bug internally as well?

**Comment by zyxyoshine** [comment] 2019-03-25 05:02
Thanks @bganapa, I've filed a bug to our team.
This inconsistent issue may be caused by the storage controller cache (5 mins life cycle), @asbjorn-wiik Did the Get-AzsVolume always return repair status 98%? (or just in a short time window?)
I will update status here when our team investigate more.

**Comment by asbjorn-wiik** [comment] 2019-03-25 08:43
Hi @zyxyoshine 
There was a delayed response al trough out the volume rebuilds and after I filed the bug I did see the Get-AzsVolume update to a healthy state. I can’t for sure say the time window of the delay

**Comment by zyxyoshine** [comment] 2019-03-27 08:04
Hi @asbjorn-wiik 
My team confirmed it's by design, Get-AzsVolume or get other storage objects will have a delayed update (up to 5mins). We are implementing a new feature which will improve the inconsistent issue and will be released with new admin powershell in the future.
@bganapa I've closed the internally bug, should we close this issue?

**Comment by asbjorn-wiik** [comment] 2019-03-27 08:46
Hi 
Could you change that design?
The utility of adding 5 minutes for each node when needing to power cycle all node will add an hour to the maintenance of a 12 node Azure Stack. 
So, will I choose Get-AzsVolume or will I choose to logon to the PEP and do get-virtualdisk -cimsession s-cluster; get-virtualdisk -cimsession s-cluster | get-storagejob and save an hour.
I was glad when I found the Get-AzsVolume, but now I’m disappointed that I must continue to logon to PEP.
I hope that you can remove the delay entirely.

Sorry, for being blunt

**Comment by zyxyoshine** [comment] 2019-03-27 09:46
@asbjorn-wiik 
We are working on use SDDC Management which will keep consistent with OS portal, I think that will be what you want.

**Comment by bganapa** [comment] 2019-03-27 17:12
@asbjorn-wiik Thanks for the feedback. It seems @zyxyoshine team is working on a solution to this. @zyxyoshine please feel free to elaborate the solution and close this issue

**Closed** 2019-03-28 02:23 UTC
Labels: Azure Stack, Service Attention
