### ISSUE TITLE
Import-AzBlueprintWithArtifact fails when assigning resource group tags with object type parameter 

### ISSUE THREAD

**Issue by JozoSlejko** [Azure/azure-powershell#12472] opened 2020-07-23 21:39 UTC
## Description

Specifying resource group tags as a parameter of type object gives an error.
```powershell
Import-AzBlueprintWithArtifact: Can't deserialize the JSON file '\rg-blueprint\Blueprint.json'.  'Error converting value "[parameters('g_tags')]" to type 'System.Collections.Generic.IDictionary`2[System.String,System.String]'. Path 'tags', line 28, position 40.'
```

[ResourceGroupDefinition ](https://docs.microsoft.com/en-us/rest/api/blueprints/blueprints/createorupdate#resourcegroupdefinition) shows tags as object

Parameter section:
```
    "parameters": {
      "g_tags": {
        "type": "object"
      }
    },
```
Resource group section:
```
"resourceGroups": {
      "testResourceGroup": {
        "name": "rg-bp-testing-01",
        "location": "uksouth",
        "tags": "[parameters('g_tags')]"
      }
    }
```

## Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Steps to reproduce

```powershell
Import-AzBlueprintWithArtifact -Name rg-blueprint-v1 -ManagementGroupId MG01 -InputPath .\rg-blueprint\
```

## Module versions

```powershell
ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     4.4.0                 Az                                  Core,Desk
Script     1.9.1                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollect…
Script     1.1.1                 Az.Advisor                          Core,Desk {Get-AzAdvisorRecommendation, Enable-AzAdvisorRecommendation, Disable-AzAd…
Script     1.1.3                 Az.Aks                              Core,Desk {Get-AzAks, New-AzAks, Remove-AzAks, Import-AzAksCredential…}
Script     1.1.4                 Az.AnalysisServices                 Core,Desk {Resume-AzAnalysisServicesServer, Suspend-AzAnalysisServicesServer, Get-Az…
Script     2.0.1                 Az.ApiManagement                    Core,Desk {Add-AzApiManagementApiToProduct, Add-AzApiManagementProductToGroup, Add-A…
Script     1.1.0                 Az.ApplicationInsights              Core,Desk {Get-AzApplicationInsights, New-AzApplicationInsights, Remove-AzApplicatio…
Script     1.3.7                 Az.Automation                       Core,Desk {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHybridWorkerGroup, …
Script     3.1.0                 Az.Batch                            Core,Desk {Remove-AzBatchAccount, Get-AzBatchAccount, Get-AzBatchAccountKey, New-AzB…
Script     1.0.3                 Az.Billing                          Core,Desk {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzEnrollmentAccount, Get-A…
Script     0.2.13                Az.Blueprint                        Core,Desk {Get-AzBlueprint, Get-AzBlueprintAssignment, New-AzBlueprintAssignment, Re…
Script     1.4.3                 Az.Cdn                              Core,Desk {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-AzCdnProfile, Remove-AzCdnP…
Script     1.5.0                 Az.CognitiveServices                Core,Desk {Get-AzCognitiveServicesAccount, Get-AzCognitiveServicesAccountKey, Get-Az…
Script     4.2.1                 Az.Compute                          Core,Desk {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAvailabilitySet, U…
Script     1.0.3                 Az.ContainerInstance                Core,Desk {New-AzContainerGroup, Get-AzContainerGroup, Remove-AzContainerGroup, Get-…
Script     1.1.1                 Az.ContainerRegistry                Core,Desk {New-AzContainerRegistry, Get-AzContainerRegistry, Update-AzContainerRegis…
Script     1.1.0                 Az.DataBoxEdge                      Core,Desk {Get-AzDataBoxEdgeJob, Get-AzDataBoxEdgeDevice, Invoke-AzDataBoxEdgeDevice…
Script     1.9.0                 Az.DataFactory                      Core,Desk {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get-AzDataFactoryV2, Remove-…
Script     1.0.2                 Az.DataLakeAnalytics                Core,Desk {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeAnalyticsCatalogCredenti…
Script     1.2.8                 Az.DataLakeStore                    Core,Desk {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreTrustedIdProv…
Script     1.0.0                 Az.DataShare                        Core,Desk {New-AzDataShareAccount, Get-AzDataShareAccount, Remove-AzDataShareAccount…
Script     1.1.0                 Az.DeploymentManager                Core,Desk {Get-AzDeploymentManagerArtifactSource, New-AzDeploymentManagerArtifactSou…
Script     1.0.0                 Az.DesktopVirtualization            Core,Desk {Disconnect-AzWvdUserSession, Get-AzWvdApplication, Get-AzWvdApplicationGr…
Script     1.0.2                 Az.DevTestLabs                      Core,Desk {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolicy, Get-AzDtlAuto…
Script     1.1.2                 Az.Dns                              Core,Desk {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remove-AzDnsRecordSet, Set-AzD…
Script     1.3.0                 Az.EventGrid                        Core,Desk {New-AzEventGridTopic, Get-AzEventGridTopic, Set-AzEventGridTopic, New-AzE…
Script     1.5.0                 Az.EventHub                         Core,Desk {New-AzEventHubNamespace, Get-AzEventHubNamespace, Set-AzEventHubNamespace…
Script     1.6.0                 Az.FrontDoor                        Core,Desk {New-AzFrontDoor, Get-AzFrontDoor, Set-AzFrontDoor, Remove-AzFrontDoor…}
Script     1.0.1                 Az.Functions                        Core,Desk {Get-AzFunctionApp, Get-AzFunctionAppAvailableLocation, Get-AzFunctionAppP… 
Script     3.3.1                 Az.HDInsight                        Core,Desk {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefinition, Wait-AzHDInsightJo… 
Script     1.1.0                 Az.HealthcareApis                   Core,Desk {New-AzHealthcareApisService, Remove-AzHealthcareApisService, Set-AzHealth… 
Script     2.5.0                 Az.IotHub                           Core,Desk {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGroup, Get-AzIotHubConnectio…
Script     2.0.0                 Az.KeyVault                         Core,Desk {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertificate, Stop-AzKeyVaultC… 
Script     1.3.2                 Az.LogicApp                         Core,Desk {Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccountAssembly, Get-…
Script     1.1.3                 Az.MachineLearning                  Core,Desk {Move-AzMlCommitmentAssociation, Get-AzMlCommitmentAssociation, Get-AzMlCo…
Script     1.0.0                 Az.Maintenance                      Core,Desk {Get-AzApplyUpdate, Get-AzConfigurationAssignment, Get-AzMaintenanceConfig… 
Script     1.0.2                 Az.ManagedServices                  Core,Desk {Get-AzManagedServicesAssignment, New-AzManagedServicesAssignment, Remove-… 
Script     1.0.2                 Az.MarketplaceOrdering              Core,Desk {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}
Script     1.1.1                 Az.Media                            Core,Desk {Sync-AzMediaServiceStorageKey, Set-AzMediaServiceKey, Get-AzMediaServiceK… 
Script     2.0.2                 Az.Monitor                          Core,Desk {Get-AzMetricDefinition, Get-AzMetric, Remove-AzLogProfile, Get-AzLogProfi…
Script     3.2.0                 Az.Network                          Core,Desk {Add-AzApplicationGatewayAuthenticationCertificate, Get-AzApplicationGatew…
Script     1.1.1                 Az.NotificationHubs                 Core,Desk {Get-AzNotificationHub, Get-AzNotificationHubAuthorizationRule, Get-AzNoti… 
Script     2.2.0                 Az.OperationalInsights              Core,Desk {New-AzOperationalInsightsAzureActivityLogDataSource, New-AzOperationalIns… 
Script     1.3.1                 Az.PolicyInsights                   Core,Desk {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPolicyStateSummary, Get-AzPol… 
Script     1.1.2                 Az.PowerBIEmbedded                  Core,Desk {Remove-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollection, Ge…
Script     1.0.3                 Az.PrivateDns                       Core,Desk {Get-AzPrivateDnsZone, Remove-AzPrivateDnsZone, Set-AzPrivateDnsZone, New-… 
Script     2.11.0                Az.RecoveryServices                 Core,Desk {Get-AzRecoveryServicesBackupProperty, Get-AzRecoveryServicesVault, Get-Az…
Script     1.2.1                 Az.RedisCache                       Core,Desk {Remove-AzRedisCachePatchSchedule, New-AzRedisCacheScheduleEntry, Get-AzRe…
Script     1.0.3                 Az.Relay                            Core,Desk {New-AzRelayNamespace, Get-AzRelayNamespace, Set-AzRelayNamespace, Remove-…
Script     0.7.7                 Az.ResourceGraph                    Core,Desk Search-AzGraph
Script     2.3.0                 Az.Resources                        Core,Desk {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRoleAssignment, N…
Script     0.7.8                 Az.Security                         Core,Desk {Get-AzSecurityAlert, Set-AzSecurityAlert, Get-AzSecurityAutoProvisioningS… 
Script     1.4.1                 Az.ServiceBus                       Core,Desk {New-AzServiceBusNamespace, Get-AzServiceBusNamespace, Set-AzServiceBusNam…
Script     2.1.0                 Az.ServiceFabric                    Core,Desk {Add-AzServiceFabricClientCertificate, Add-AzServiceFabricClusterCertifica…
Script     1.1.1                 Az.SignalR                          Core,Desk {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey, New-AzSignalRKey…}
Script     2.9.0                 Az.Sql                              Core,Desk {Get-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabaseTransparentD…
Script     1.1.0                 Az.SqlVirtualMachine                Core,Desk {New-AzSqlVM, Get-AzSqlVM, Update-AzSqlVM, Remove-AzSqlVM…}
Script     2.3.0                 Az.Storage                          Core,Desk {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStorageAccount, New-…
Script     1.3.0                 Az.StorageSync                      Core,Desk {Invoke-AzStorageSyncCompatibilityCheck, New-AzStorageSyncService, Get-AzS… 
Script     1.0.1                 Az.StreamAnalytics                  Core,Desk {Get-AzStreamAnalyticsFunction, Get-AzStreamAnalyticsDefaultFunctionDefini…
Script     1.0.0                 Az.Support                          Core,Desk {Get-AzSupportService, Get-AzSupportProblemClassification, Get-AzSupportTi… 
Script     1.0.4                 Az.TrafficManager                   Core,Desk {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove-AzTrafficManagerCustom…
Script     1.11.0                Az.Websites                         Core,Desk {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServicePlan, Remove-…
```

## Debug output

```powershell
DEBUG: 22:28:08 - ImportAzureRmBlueprint begin processing with ParameterSet 'ImportBlueprint'.

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/********/providers/Microsoft.Blueprint?api-version=2018-05-01

Headers:
x-ms-client-request-id        : b9d3d64c-be6c-4a1b-9121-21e772b5dd57
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-ratelimit-remaining-subscription-reads: 11999
x-ms-request-id               : 4d0d3f50-9c9b-4485-8e96-793c3ba37c71
x-ms-correlation-request-id   : 4d0d3f50-9c9b-4485-8e96-793c3ba37c71
x-ms-routing-request-id       : UKSOUTH:20200723T212807Z:4d0d3f50-9c9b-4485-8e96-793c3ba37c71
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Thu, 23 Jul 2020 21:28:06 GMT

Body:
{
  "id": "/subscriptions/*************/providers/Microsoft.Blueprint",
  "namespace": "Microsoft.Blueprint",
  "authorizations": [
    {
      "applicationId": "**************************",
      "roleDefinitionId": "cb180127-cf6d-4672-9e75-e29a487f9658"
    }
  ],
  "resourceTypes": [
    {
      "resourceType": "blueprints",
      "locations": [],
      "apiVersions": [
        "2018-11-01-preview",
        "2018-11-01-alpha",
        "2017-11-11-preview",
        "2017-11-11-alpha"
      ],
      "capabilities": "SupportsExtension"
    },
    {
      "resourceType": "blueprints/artifacts",
      "locations": [],
      "apiVersions": [
        "2018-11-01-preview",
        "2018-11-01-alpha",
        "2017-11-11-preview",
        "2017-11-11-alpha"
      ]
    },
    {
      "resourceType": "blueprints/versions",
      "locations": [],
      "apiVersions": [
        "2018-11-01-preview",
        "2018-11-01-alpha",
        "2017-11-11-preview",
        "2017-11-11-alpha"
      ]
    },
    {
      "resourceType": "blueprints/versions/artifacts",
      "locations": [],
      "apiVersions": [
        "2018-11-01-preview",
        "2018-11-01-alpha",
        "2017-11-11-preview",
        "2017-11-11-alpha"
      ]
    },
    {
      "resourceType": "blueprintAssignments",
      "locations": [],
      "apiVersions": [
        "2018-11-01-preview",
        "2018-11-01-alpha",
        "2017-11-11-preview",
        "2017-11-11-alpha"
      ],
      "capabilities": "SystemAssignedResourceIdentity, SupportsExtension"
    },
    {
      "resourceType": "blueprintAssignments/operations",
      "locations": [],
      "apiVersions": [
        "2017-11-11-preview",
        "2017-11-11-alpha"
      ]
    },
    {
      "resourceType": "blueprintAssignments/assignmentOperations",
      "locations": [],
      "apiVersions": [
        "2018-11-01-preview",
        "2018-11-01-alpha"
      ]
    },
    {
      "resourceType": "operations",
      "locations": [],
      "apiVersions": [
        "2018-11-01-preview",
        "2018-11-01-alpha",
        "2017-11-11-preview",
        "2017-11-11-alpha"
      ]
    }
  ],
  "registrationState": "Registered"
}


Import-AzBlueprintWithArtifact: Can't deserialize the JSON file '\rg-blueprint\Blueprint.json'.  'Error converting value "[parameters('g_tags')]" to type 'System.Collections.Generic.IDictionary`2[System.String,System.String]'. Path 'tags', line 28, position 40.'
DEBUG: AzureQoSEvent: CommandName - Import-AzBlueprintWithArtifact; IsSuccess - False; Duration - 00:00:00.7219172;; Exception - System.Exception: Can't deserialize the JSON file '\rg-blueprint\Blueprint.json'.  'Error converting value "[parameters('g_tags')]" to type 'System.Collections.Generic.IDictionary`2[System.String,System.String]'. Path 'tags', line 28, position 40.'
   at Microsoft.Azure.Commands.Blueprint.Cmdlets.BlueprintDefinitionCmdletBase.ImportBlueprint(String blueprintName, String scope, String inputPath, Boolean force)
   at Microsoft.Azure.Commands.Blueprint.Cmdlets.ImportAzureRmBlueprint.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 22:28:09 - ImportAzureRmBlueprint end processing.

```

## Error output

```powershell
Message        : Can't deserialize the JSON file '\rg-blueprint\Blueprint.json'.  'Error converting value
                 "[parameters('g_tags')]" to type 'System.Collections.Generic.IDictionary`2[System.String,System.String]'. Path 'tags', line 28, position  
                 40.'
StackTrace     :    at Microsoft.Azure.Commands.Blueprint.Cmdlets.BlueprintDefinitionCmdletBase.ImportBlueprint(String blueprintName, String scope,        
                 String inputPath, Boolean force)
                    at Microsoft.Azure.Commands.Blueprint.Cmdlets.ImportAzureRmBlueprint.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Exception
InvocationInfo : {Import-AzBlueprintWithArtifact}
Line           : Import-AzBlueprintWithArtifact -Name rg-blueprint-v1 -ManagementGroupId MG01 -InputPath .\rg-blueprint\
Position       : At line:1 char:1
                 + Import-AzBlueprintWithArtifact -Name rg-blueprint-v1 -ManagementGroup …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 57
```

**Comment by dingmeng-xue** [comment] 2020-07-24 02:12
Blueprint team, it seems the format of import json is not correct. But I didn't find sample about how to define tag using parameter. Please provide help.

**Comment by filizt** [comment] 2020-07-24 16:50
@Xynoclafe - could you take a look?

**Comment by Xynoclafe** [comment] 2020-08-03 15:28
This behavior is by design, and as of right now, there are no plans of supporting it in the near future.

**Comment by JozoSlejko** [comment] 2020-08-03 20:21
> This behavior is by design, and as of right now, there are no plans of supporting it in the near future.

Could you please further explain the design decision rationale? 
If the object type is supported for artefacts, why is it different for the resource group tags? 
Where can I find the documentation explaining that the object is in fact not a supported type?

**Comment by Xynoclafe** [comment] 2020-08-04 00:10
> 
> 
> > This behavior is by design, and as of right now, there are no plans of supporting it in the near future.
> 
> Could you please further explain the design decision rationale?
> If the object type is supported for artefacts, why is it different for the resource group tags?
> Where can I find the documentation explaining that the object is in fact not a supported type?

It's not the object type that's the problem, but rather that the powershell cmdlet in question. The cmdlet does not parse parameters for tags, and just matches the given blueprint with a schema. In this case, it notices a string "[parameters('g_tags')]" which is not what is expected by the schema. So, if you want to set tags, you would have to pass the tags like so
```
"tags" : {
   "foo": "bar",
   "tag": "val" 
}
```

**Comment by alex-frankel** [comment] 2020-08-04 00:31
@JozoSlejko -- it is a legitimate issue that we don't support parameters in the `tags` object, but it's currently not a priority to get it resolved.

We are planning to migrate blueprint definitions into template specs, which we showed at [our //build session](https://youtu.be/UaVCNpD3pvg?t=718) in May. We also have [public docs for template specs](https://docs.microsoft.com/azure/azure-resource-manager/templates/template-specs), which is now in private preview. 

This issue will be resolved by migrating to template specs, so that is why we can't justify resolving this. The Blueprint Definition APIs will continue to be supported, but we will only resolve critical/blocking issues.

**Comment by JozoSlejko** [comment] 2020-08-04 08:39
> > > This behavior is by design, and as of right now, there are no plans of supporting it in the near future.
> > 
> > 
> > Could you please further explain the design decision rationale?
> > If the object type is supported for artefacts, why is it different for the resource group tags?
> > Where can I find the documentation explaining that the object is in fact not a supported type?
> 
> It's not the object type that's the problem, but rather that the powershell cmdlet in question. The cmdlet does not parse parameters for tags, and just matches the given blueprint with a schema. In this case, it notices a string "[parameters('g_tags')]" which is not what is expected by the schema. So, if you want to set tags, you would have to pass the tags like so
> 
> ```
> "tags" : {
>    "foo": "bar",
>    "tag": "val" 
> }
> ```

Yes, I'm aware it's a cmdlet which has a problem with using the object type parameter. Obviously, we are on the azure-powershell issues github page. :)
I was just asking why it was a design choice.

**Comment by JozoSlejko** [comment] 2020-08-04 08:40
@alex-frankel thanks for the info.

**Comment by apclouds** [comment] 2020-09-21 16:10
Hello @JozoSlejko just wanted to follow up on this issue, is there any other details you would like before closing this issue?

**Comment by JozoSlejko** [comment] 2020-09-23 19:15
@apclouds Nothing further from me thanks

**Closed** 2020-09-28 14:15 UTC
Labels: Blueprint, Service Attention, customer-reported, question
