### ISSUE TITLE
Get-AzKeyVault - Get all Flag

### ISSUE THREAD

**Issue by tikicoder** [Azure/azure-powershell#12574] opened 2020-08-04 23:10 UTC
## Description of the new feature

When you run the Get-AzKeyVault command with -InRemovedState it only returns deleted KV.  It would be nice if you could get all Key vaults removed and not removed.  This way I can decide if I want to remove the KEy Vault and create a new one or restore it.

## Proposed implementation details (optional)
update the -InRemovedState flag to accept a string all which would show all and without it it would only show deleted.

**Comment by dingmeng-xue** [comment] 2020-08-06 10:21
Thanks for your suggestion. We will discuss it with Keyvault team.

**Comment by ShaneBala-keyvault** [comment] 2020-08-11 23:38
Hi @tikicoder this behavior is by design. 

Running the Get-AzKeyVault command without specifying a specific key vault lists all of the key vaults that are active in your current subscription (not in the soft deleted state). 

Running the Get-AzKeyVault command with the -InRemovedState flag lists all of the key vaults in the soft deleted state in your current subscription. 

There is no single command to list both active and soft-deleted vaults, but you can run these two commands one after the other to view all within your powershell window. 

I hope this helps, I will be closing this issue. 

Thanks, 
Shane Bala
Azure Key Vault Team

**Closed by ShaneBala-keyvault** 2020-08-11 23:38 UTC
Labels: Azure PS Team, KeyVault, Service, feature-request, question
