### ISSUE TITLE
Cannot list all resources under a specified ResourceGroup

### ISSUE THREAD

**Issue by jychunyih** [Azure/azure-powershell#1493] opened 2015-12-15 10:13 UTC
For example, when typing

> Get-AzureRmResource -ResourceGroupName Default-SQL-ChinaNorth

to list all resource instances under this resource group, it will throw below exception:

+ Get-AzureRmResource -ResourceGroupName Default-SQL-ChinaNorth
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-AzureRmResource]，ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.Ge
   tAzureResourceCmdlet

**Comment by jaredmoo** [comment] 2015-12-15 20:47
I hit the same problem. The issue is that there are multiple parameter sets where ResourceGroupName is optional, PowerShell doesn't know which parameter set to choose.

```
Get-Help Get-AzureRmResource

SYNTAX
    Get-AzureRmResource [-ResourceName <String>] [-ResourceType <String>] [-ExtensionResourceName <String>] [-ExtensionResourceType <String>]
    [-ExpandProperties [<SwitchParameter>]] [-IsCollection [<SwitchParameter>]] [-Top <Nullable`1[Int32]>] [-ODataQuery <String>] [-ResourceGroupName
    <String>] [-ApiVersion <String>] [-Pre [<SwitchParameter>]] [-Profile <AzureProfile>] [-InformationAction <ActionPreference>] [-InformationVariable
    <String>] [<CommonParameters>]

    Get-AzureRmResource -ResourceId <String> [-ExpandProperties [<SwitchParameter>]] [-ODataQuery <String>] [-ApiVersion <String>] [-Pre [<SwitchParameter>]]
    [-Profile <AzureProfile>] [-InformationAction <ActionPreference>] [-InformationVariable <String>] [<CommonParameters>]

    Get-AzureRmResource [-ResourceName <String>] [-ResourceType <String>] [-ExtensionResourceName <String>] [-ExtensionResourceType <String>]
    [-ExpandProperties [<SwitchParameter>]] [-IsCollection [<SwitchParameter>]] [-ODataQuery <String>] -TenantLevel [<SwitchParameter>] [-ApiVersion <String>]
    [-Pre [<SwitchParameter>]] [-Profile <AzureProfile>] [-InformationAction <ActionPreference>] [-InformationVariable <String>] [<CommonParameters>]

    Get-AzureRmResource [-ResourceName <String>] [-ResourceType <String>] [-ExtensionResourceName <String>] [-ExtensionResourceType <String>]
    [-ExpandProperties [<SwitchParameter>]] [-IsCollection [<SwitchParameter>]] [-Top <Nullable`1[Int32]>] [-ODataQuery <String>] [-ResourceGroupName
    <String>] [-ApiVersion <String>] [-Pre [<SwitchParameter>]] [-Profile <AzureProfile>] [-InformationAction <ActionPreference>] [-InformationVariable
    <String>] [<CommonParameters>]

    Get-AzureRmResource [-ResourceName <String>] [-ResourceType <String>] [-ParentResource <String>] [-ExtensionResourceName <String>] [-ExtensionResourceType
    <String>] [-ExpandProperties [<SwitchParameter>]] [-IsCollection [<SwitchParameter>]] [-ODataQuery <String>] [-ResourceGroupName <String>] [-ApiVersion
    <String>] [-Pre [<SwitchParameter>]] [-Profile <AzureProfile>] [-InformationAction <ActionPreference>] [-InformationVariable <String>] [<CommonParameters>]

    Get-AzureRmResource [-ResourceName <String>] [-ResourceType <String>] [-ExtensionResourceName <String>] [-ExtensionResourceType <String>]
    [-ExpandProperties [<SwitchParameter>]] [-IsCollection [<SwitchParameter>]] [-Top <Nullable`1[Int32]>] [-ODataQuery <String>] -TenantLevel
    [<SwitchParameter>] [-ApiVersion <String>] [-Pre [<SwitchParameter>]] [-Profile <AzureProfile>] [-InformationAction <ActionPreference>]
    [-InformationVariable <String>] [<CommonParameters>]
```

**Comment by ravbhatnagar** [comment] 2015-12-15 23:10
https://github.com/Azure/azure-powershell/issues/1259

**Comment by pmooij** [comment] 2015-12-16 15:38
same here, was using this cmdlet a lot. 
is there any workarround? looking forward to the fix

**Comment by ravbhatnagar** [comment] 2016-02-03 01:55
This will be fixed in the next release of PS. If you are blocked by this, you can use Find-AzureRmResource.

**Comment by ravbhatnagar** [comment] 2016-03-04 19:33
Fixed - 3/3 PS release

**Closed by ravbhatnagar** 2016-03-04 19:33 UTC
Labels: ResourceManager
