### ISSUE TITLE
Azure PowerShell installer is removing critical PSModulePath value

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#685] opened 2015-08-03 16:10 UTC
**FYI**: This has been a long-running problem. **A fix for this needs to be prioritized.**

# Symptom

After installing the Azure PowerShell module, the `c:\Program Files\WindowsPowerShell\Modules` folder is no longer showing up in the `PSModulePath` environment variable. This is breaking modules in that directly, including the **PSReadline** module, included out-of-box in Windows 10 RTM.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by markcowl** [comment] 2015-08-04 02:17
@pcgeek86 the installer only appends to the existing global environment variable psmodulepath, it does not otherwise change it.  Is there some special property of your psmodulepath variable, for example, is it very, very long?

**Comment by pcgeek86** [comment] 2015-08-04 03:01
@markcowl  Nope, default install of Windows 10 RTM Enterprise Build 10240 off ISO.

**Comment by raandree** [comment] 2015-08-05 18:03
Same here, just installed the July build and the PSModule path is gone. This is not Winodws 10 specific, I did have the same issue on Windows 8 and also with previous versions of the Azure PowerShell cmdlets.

**Comment by devigned** [comment] 2015-08-06 18:12
It sounds like this a reproducible issue. We will get it sorted out.

**Comment by josheinstein** [comment] 2015-08-12 19:55
Running into the same issue. What shows up in the Environment Variables dialog in Windows is a PSModulePath variable at the system level, with a value that appears to be correct. However, if I type echo %psmodulepath% at a cmd.exe prompt, I get what looks to be a truncated version of it. Simply throwing a ; at the end of the variable in the dialog (and closing/reopening command prompt) the environment variable looks fine. Took the semi out, and it's still fine.

Sorry my contribution here is anecdotal and not more scientific but once I accidentally fixed the problem, I couldn't reproduce it. Perhaps there's some hidden char that is causing the string to be terminated early? Whatever the case, rewriting the system-level PSModulePath environment variable in System -> Advanced -> Environment Variables fixed the issue for me.

**Comment by josheinstein** [comment] 2015-08-12 19:59
Here is the system-level PSModulePath environment variable I am currently using, which is working again.

`%SystemRoot%\system32\WindowsPowerShell\v1.0\Modules\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules\;C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement`

**Comment by mrdaemon** [comment] 2015-09-23 19:43
Just thought i'd mention this is still an issue to this day.

**Comment by mrdaemon** [comment] 2015-09-23 20:01
Also, just to confirm, manually setting the PSModulePath environment variable to the following:

```
%SystemRoot%\system32\WindowsPowerShell\v1.0\Modules\;C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement
```

Seems to resolve the issue.

**Comment by markcowl** [comment] 2016-02-18 22:41
@pcgeek86 @josheinstein @mrdaemon A couple of comments.  First, we have a plan for removing reliance on updating the global PSModulePath which should resolve *most* of these issues.

The underlying behavior is caused by two issues : (1) The windows installer does not propagate changes to global environment variables under certain circumstances, such as a pending restart for updates until you actually restart the machine.  (2) WMF 5 also has a bug that will prevent correct calculation ofthe PSModulePath from global and user environment variables under certain circumstances.  This is transient, but often also requires a restart to fix

Luckily, not relying on PSModulePath changes should alleviate both of these issues.  Will keep this thread updated as the plans are solidified, but this should occur in release before or just after the //BUILD timeframe

**Comment by markcowl** [comment] 2016-03-08 17:37
@pcgeek86 @josheinstein @mrdaemon Quick update - this is slated for the release after //BUILD, going out the first week of May

**Comment by MattAllison** [comment] 2016-04-27 21:41
@markcowl I noticed you closed the issue related to duplicate PSModulePath variables as a "duplicate" of this.  I don't believe that is correct, nor do I believe that removing the reliance on PSModulePath is exactly the same thing.

The simple fact is that the Azure module appears to modify the PSModulePath - inserting a duplicate entry for "C:\Program Files\WindowsPowerShell\Modules".   As stated in the closed issue, this breaks PowerShell DSC including the Azure command Publish-AzureVMDscConfiguration.

While I could think of possibly valid reasons to append a needed, but missing, value to the PSModulePath, inserting a duplicate value is a bug.

The impact to us is that we lost a complete day of productivity for an entire development team because we couldn't re-deploy a set of VMs to replace a set that was broken (due to a different Azure problem).

I don't think there's a good excuse for this.

**Comment by markcowl** [comment] 2016-09-28 00:01
This will be covered by #2220 Closing as duplicate

**Closed by markcowl** 2016-09-28 00:01 UTC
Labels: Team
