### ISSUE TITLE
New-AzAdServicePrinctipal fails with NullReferenceException

### ISSUE THREAD

**Issue by sptramer** [Azure/azure-powershell#7707] opened 2018-10-31 00:15 UTC
### Description

`New-AzADServicePrincipal` does not work for valid inputs.

### Script/Steps for Reproduction

```powershell
$securePassword = ConvertTo-SecureString -Force -AsPlainText -String $password
$appId = New-Object System.Guid($appId)
PS C:\Users\sttramer.REDMOND> New-AzADServicePrincipal -ApplicationId $appId -Password $securePassword
New-AzADServicePrincipal : Object reference not set to an instance of an object.
At line:1 char:1
+ New-AzADServicePrincipal -ApplicationId $appId -Password $securePassw ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [New-AzADServicePrincipal], NullReferenceException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.ActiveDirectory.NewAzureADServicePrincipalCommand

PS C:\Users\sttramer.REDMOND> $appId

Guid
----
0ed589c8-7280-40f6-b457-a99e7d8158af


PS C:\Users\sttramer.REDMOND> $securePassword
System.Security.SecureString
```

`$password` was also verified to be a non-null, non-empty value. `$appId` is non-empty. This cmdlet also does not work if `$appId` is of type `String`, rather than type `Guid`.

### Module Version

```powershell
PS C:\Users\sttramer.REDMOND> Get-Module -Name Az

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   0.4.0      Az
```
### Environment Data

```powershell
PS C:\Users\sttramer.REDMOND> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Debug Output

```
PS C:\Users\sttramer.REDMOND> $DebugPreference='Continue'
PS C:\Users\sttramer.REDMOND> New-AzADServicePrincipal -ApplicationId $appId -Password $securePassword
DEBUG: 5:14:32 PM - NewAzureADServicePrincipalCommand begin processing with ParameterSet 'SimpleParameterSet'.
DEBUG: Caught exception, type: System.NullReferenceException
New-AzADServicePrincipal : Object reference not set to an instance of an object.
At line:1 char:1
+ New-AzADServicePrincipal -ApplicationId $appId -Password $securePassw ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [New-AzADServicePrincipal], NullReferenceException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.ActiveDirectory.NewAzureADServicePrincipalCommand

DEBUG: AzureQoSEvent: CommandName - New-AzADServicePrincipal; IsSuccess - False; Duration - 00:00:00.0707002; Exception - System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Graph.RBAC.Version1_6.ActiveDirectory.ActiveDirectoryBaseCmdlet.HandleException(Exception exception)
   at Microsoft.Azure.Graph.RBAC.Version1_6.ActiveDirectory.ActiveDirectoryBaseCmdlet.ExecutionBlock(Action execAction)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 5:14:33 PM - NewAzureADServicePrincipalCommand end processing.
DEBUG: 5:14:33 PM - NewAzureADServicePrincipalCommand end processing.
```

**Comment by deathly809** [comment] 2018-10-31 00:41
Hmm, I think it should have gone into the parameter set "ApplicationWithPasswordPlain" but went into "SimpleParameterSet".  The parameter set "SimpleParameterSet" has mandatory false on all of it's parameters... shouldn't one of those be set to true?

When you run this with -Verbose what does it output?  I see in the code that it writes more output with that than with Debug.

**Comment by sptramer** [comment] 2018-10-31 20:41
Interestingly, after adding `-Verbose` and running today, I get this:

```
PS C:\Users\sttramer> $password = [System.Guid]::NewGuid().ToString()
>> $securePassword = ConvertTo-SecureString -Force -AsPlainText -String $password
>> New-AzADServicePrincipal -ApplicationId $app.ApplicationId -Verbose
VERBOSE: No scope provided - using the default scope '/subscriptions/07a45d58-11b5-4fd3-8cb6-12ac232d1c3f'
VERBOSE: No role provided - using the default role 'Contributor'
VERBOSE: No start date provided - using the current time as default.
VERBOSE: No end date provided - using the default value of one year after the start date.
VERBOSE: No display name provided - using the default display name of 'azure-powershell-10-31-2018-20-40-46'
VERBOSE: Performing the operation "Adding a new service principal to be associated with an application having AppId '0ed589c8-7280-40f6-b457-a99e7d8158af' with no permissions." on target "0ed589c8-7280-40f6-b457-a99e7d8158af".
New-AzADServicePrincipal : Another object with the same value for property servicePrincipalNames already exists.
At line:3 char:1
+ New-AzADServicePrincipal -ApplicationId $app.ApplicationId -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [New-AzADServicePrincipal], Exception
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.ActiveDirectory.NewAzureADServicePrincipalCommand
```

Is creating a service prinicpal now a long-running operation?

**Comment by deathly809** [comment] 2018-10-31 20:57
When you say "identical error" and "same error" which of the two errors are you talking about?

**Comment by sptramer** [comment] 2018-10-31 21:30
Sorry, for clarity, meant this one:

```
+ New-AzADServicePrincipal -ApplicationId $app.ApplicationId -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [New-AzADServicePrincipal], Exception
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.ActiveDirectory.NewAzureADServicePrincipalCommand
```

**Comment by maddieclayton** [comment] 2018-11-06 22:41
@sptramer Can you run 'Get-AzContext' and send us the output? Thanks.

**Comment by maddieclayton** [comment] 2018-11-06 22:42
@deathly809 It is actually by design that you don't need to provide any parameter for the simple parameter set, as it will automatically generate a random password and set defaults for all other parameters.

**Comment by deathly809** [comment] 2018-11-06 23:07
@maddieclayton But she is providing parameters.  Does a parameter set match even if Mandatory=False even though there is another matching parameter set?  Or maybe I missed a parameter.

**Comment by maddieclayton** [comment] 2018-11-06 23:11
@deathly809 You can match a parameter set even if the parameter provided is not mandatory.  As long as the parameter is in the default parameter set, it will default to the default parameter set.

**Comment by markcowl** [comment] 2018-12-14 23:03
Now that supplying Password is no longer allowed, I think we can close this

**Closed by markcowl** 2018-12-14 23:03 UTC
Labels: Investigate :mag:, Resource Authorization

**Comment by zaphodtx** [comment] 2019-04-19 17:17
I am seeing this same error message.

PS C:\WINDOWS\system32> $myAppIDString = '80ad9f13-c920-4243-a11d-123456d9c0aa'

PS C:\WINDOWS\system32> New-AzADServicePrincipal -ApplicationId $myAppIDString
New-AzADServicePrincipal : Object reference not set to an instance of an object.
At line:1 char:1
+ New-AzADServicePrincipal -ApplicationId $myAppIDString
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzADServicePrincipal], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ActiveDirectory.NewAzureADServicePrincipalCommand

I was following the instructions from:
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-rm-rest
