### ISSUE TITLE
webapp:Get-AzureRmWebAppSlot parameter "-WebApp" fails due to type

### ISSUE THREAD

**Issue by jskii** [Azure/azure-powershell#3633] opened 2017-03-14 21:10 UTC
### Cmdlet(s)
Get-AzureRmWebAppSlot
Get-AzureRmWebApp

### PowerShell Version
PSVersion                      5.1.14393.693    

### Module Version
Azure Powershell 3.7.0 release

### OS Version
BuildVersion                   10.0.14393.693

### Description
Attempting to use output object from Get-AzureRmWebApp to direct Get-AzureRmWebAppSlot fails due to a typing issue, although both types appear to be identical.

### Debug Output
Get-AzureRmWebAppSlot : Cannot convert 'Microsoft.Azure.Management.WebSites.Models.Site' to the type 'Microsoft.Azure.Management.WebSites.Models.Site' required by parameter 'WebApp'. Specified method is not supported.
At line:1 char:31
+ Get-AzureRmWebAppSlot -WebApp $sourceWebApp
+                               ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-AzureRmWebAppSlot], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CannotConvertArgument,Microsoft.Azure.Commands.WebApps.Cmdlets.DeploymentSlots.GetAzureWebAppSlotCmdlet

### Script/Steps for Reproduction
1.  Get source web app object:
$sourceWebApp = (Get-AzureRmWebApp -ResourceGroupName $sourceRgName)

2.  Use this object to get information on web app slots:
Get-AzureRmWebAppSlot -WebApp $sourceWebApp

**Comment by cormacpayne** [comment] 2017-03-14 23:53
@Nking92 Hey Nicholas, would you mind taking a look at this issue?

**Comment by jskii** [comment] 2017-03-22 18:19
Note:  This also occurs in other cases I'm finding.

```
$currentWebApp = Get-AzureRmWebApp -ResourceGroupName $rgName
Get-AzureRmWebAppSSLBinding $currentWebApp

Get-AzureRmWebAppSSLBinding : Cannot convert 'Microsoft.Azure.Management.WebSites.Models.Site' to the type 'Microsoft.Azure.Management.WebSites.Models.Site' required by parameter 'WebApp'. 
Specified method is not supported.
```

So looking at this as a problem with the specific case above might be incorrect; something's mishandling the typing of the Get-AzureRmWebApp cmdlet itself somewhere along the way.

**Comment by onionhammer** [comment] 2017-10-17 18:56
This is still definitely an issue.. any progress?

**Comment by auxym** [comment] 2017-11-03 16:08
Also getting this issue with `Get-AzureRmWebAppPublishingProfile`

```powershell
Get-AzureRmWebApp -Name "<sitename>" | Get-AzureRmWebAppPublishingProfile -OutputFile 'foo'
```

Returns:
```
Get-AzureRmWebAppPublishingProfile : Cannot convert 'Microsoft.Azure.Management.WebSites.Models.Site' to the type
'Microsoft.Azure.Management.WebSites.Models.Site' required by parameter 'WebApp'. Specified method is not supported.
At line:1 char:36
+ Get-AzureRmWebAppPublishingProfile $sites -OutputFile 'D:\temp\publis ...
+                                    ~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-AzureRmWebAppPublishingProfile], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgument,Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.GetAzureWebAppPublishingProfileCmdlet
```

**Comment by cormacpayne** [comment] 2017-11-03 17:09
@Nking92 ping

**Comment by Nking92** [comment] 2017-11-03 17:49
I'll check if this still happens with our latest code in the pull request that I opened.

**Comment by Nking92** [comment] 2017-11-07 00:30
The problem was just that we weren't using the enumerateCollection flag when writing out the result to the pipeline. That caused the type returned to be a List<Site> instead of a Site type.

**Comment by jskii** [comment] 2018-02-26 17:49
Hello. Just wanted to update to report that this issue still exists in the newest release version.

**Comment by Anmolgan81** [comment] 2018-03-31 21:53
Please fix this??

**Comment by steve-hawkins** [comment] 2018-04-19 11:55
@Nking92 and @panchagnula I can confirm this is still an issue on PowerShell version:-

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      16299  251

Any further news?

**Comment by panchagnula** [comment] 2018-04-19 15:11
@steve-hawkins websites has a websites-preview module that has the major bug fixes. Please use this module https://github.com/Azure/azure-powershell/releases/tag/v5.0.0-preview-AzureRM.Websites

**Comment by panchagnula** [comment] 2018-05-14 19:49
Our preview version is now released so please update to the latest stable version & let us know if this still occurs. Thank you

**Comment by panchagnula** [comment] 2019-06-21 05:51
Closing this since this should now be fixed.

**Closed by panchagnula** 2019-06-21 05:51 UTC
Labels: App Services, Service Attention
