### ISSUE TITLE
New-AzureRmRoleAssignment doesn't throw an error when subnet doesnt exist. 

### ISSUE THREAD

**Issue by nwarriorch** [Azure/azure-powershell#3771] opened 2017-04-13 21:26 UTC
### Cmdlet(s)
New-AzureRmRoleAssignment

### PowerShell Version
3.0

### Module Version
3.7.0

### OS Version
6.2.9200.16481

### Description
Tried to assign a role to a scope at subnet. When the subnet doesn't exist the role assignment doesn't throw an error. 
### Debug Output
none
### Script/Steps for Reproduction
New-AzureRmRoleAssignment -ServicePrincipalName $applicationname  -RoleDefinitionName  $role.Name  -Scope /$scope -ErrorAction Stop

when $scope is a subnet id that doesn't exist, the role assignment doesn't throw an error.

**Comment by cormacpayne** [comment] 2017-04-14 17:36
@shuagarw Hey Shubham, would you mind taking a look at this issue?

**Comment by shuagarw** [comment] 2017-04-24 18:13
@Rbacask for FYI
We on PAS side don't do resource validation when creating a roleAssignment. ARM does access check and we have reached out to them to confirm if they check for resource existence or not.

**Comment by RBACAsk** [comment] 2017-06-03 16:16
+ pasinc, armhot and Manik

Hi,
Can you share the exact parameters used with the New-AzurermRoleAssignment cmdlet?

The resource validation is done by ARM team. Manik/armhot to look into this.

Thx
Surabhi

**Comment by perseusCode** [comment] 2017-06-06 07:07
This is by design, we don't do validation for existence of proxy resources as we don't have the information with us. We only validate for the existence of resource if it is tracked. I believe the resource type here is Microsoft.Network/virtualNetworks/subnets which is a proxy resource.

**Comment by RBACAsk** [comment] 2017-06-06 07:09
Replied on the forum directly. The resource in question here is proxy only.
We don’t do any validation for existence of proxy resources. This is because we don’t have the information about resource with us.

Thanks
Manik

From: Surabhi Pandey
Sent: Saturday, June 3, 2017 9:16 AM
To: Azure/azure-powershell <reply@reply.github.com>; Azure/azure-powershell <azure-powershell@noreply.github.com>; Policy Administration Service Incidents <pasinc@microsoft.com>; Azure Resource Manager Hot Issues <armhot@microsoft.com>; Manik Sikka <mansikka@microsoft.com>
Cc: RBAC Ask <RBACAsk@microsoft.com>; Mention <mention@noreply.github.com>
Subject: RE: [Azure/azure-powershell] New-AzureRmRoleAssignment doesn't throw an error when subnet doesnt exist. (#3771)
Importance: High

+ pasinc, armhot and Manik

Hi,
Can you share the exact parameters used with the New-AzurermRoleAssignment cmdlet?

The resource validation is done by ARM team. Manik/armhot to look into this.

Thx
Surabhi

**Comment by cormacpayne** [comment] 2018-03-01 21:46
Closing.

**Closed by cormacpayne** 2018-03-01 21:46 UTC
Labels: ResourceAuthorization
