### ISSUE TITLE
Provision to pass Tenant name instead of Tenant Id GUID in  Add-AzureRmAccount 

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#3431] opened 2017-01-26 20:15 UTC
### Cmdlet(s)
Add-AzureRMAccount
### PowerShell Version
powershell v5, 1.2.8 azurestack version

### Module Version
1.0.4.2
### Description
Add-AzureRmAccount is accepting only TenantId as guid.  All the azurestack customers invariably need to pass the TenantId parameter while loggin in. Getting the Tenant ID is convoluted and not easy to remember . This should support passing the tenant name as well.  like 
       Login-AzureRmAccount -TenantId "msazurestack.onmicrosoft.com" -EnvironmentName AzureStack 

or introduce another parameter named TenantName

This would hugely help the azurestack customers since the TenantName is likely part of their login email and easy to remember.

**Comment by bganapa** [comment] 2017-01-26 20:16
@markcowl  to look at this issue, I don't think there is a limitation from ADAL library to accept the tenant name

**Comment by markcowl** [comment] 2017-01-27 22:06
This is a duplicate of https://github.com/Azure/azure-powershell/issues/2693. Closing as duplicate.

The tenantID is part of the authroty string passed to ADAL, ADAL does not recall tokens acquired using the domain name as authority when using the tenant id to retrieve.  The fix requires a change to the data that is stored about a token.

**Closed by markcowl** 2017-01-27 22:06 UTC
