### ISSUE TITLE
Get-AzVMImage for Windows-10 returns empty list and doesn't accept latest version

### ISSUE THREAD

**Issue by thecherrytree** [Azure/azure-powershell#15248] opened 2021-06-10 22:10 UTC
## Description
When attempting to pull the rs4, rs4-pro, rs5, rs5-pro VM images, the Az Module fails with a 400 when using version latest. The returned sku versions are an empty set otherwise. [The available documentation](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/cli-ps-findimage) specifies that using `latest` for versions will pull the latest version. This parameter combination used to work in our pipeline.

## Steps to reproduce

```powershell
Get-AzVmImage -Location "NorthEurope" -PublisherName "MicrosoftWindowsDesktop" -Offer "Windows-10" -Sku "rs5-pro" -Version "latest"
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

## Module versions

```powershell
ModuleType Version    PreRelease Name                                PSEdition
---------- -------    ---------- ----                                ---------
Script     4.7.0                 Az                                  Core,Desk
Script     1.9.4                 Az.Accounts                         Core,Desk
Script     1.1.1                 Az.Advisor                          Core,Desk
Script     1.3.0                 Az.Aks                              Core,Desk
Script     1.1.4                 Az.AnalysisServices                 Core,Desk
Script     2.1.0                 Az.ApiManagement                    Core,Desk
Script     1.1.0                 Az.ApplicationInsights              Core,Desk
Script     1.4.0                 Az.Automation                       Core,Desk
Script     3.1.0                 Az.Batch                            Core,Desk
Script     1.0.3                 Az.Billing                          Core,Desk
Script     1.4.3                 Az.Cdn                              Core,Desk
Script     1.6.0                 Az.CognitiveServices                Core,Desk
Script     4.4.0                 Az.Compute                          Core,Desk
Script     1.0.3                 Az.ContainerInstance                Core,Desk
Script     1.1.1                 Az.ContainerRegistry                Core,Desk
Script     1.1.0                 Az.DataBoxEdge                      Core,Desk
Script     1.10.1                Az.DataFactory                      Core,Desk
Script     1.0.2                 Az.DataLakeAnalytics                Core,Desk
Script     1.2.8                 Az.DataLakeStore                    Core,Desk
Script     1.0.0                 Az.DataShare                        Core,Desk
Script     1.1.0                 Az.DeploymentManager                Core,Desk
Script     1.0.0                 Az.DesktopVirtualization            Core,Desk
Script     1.0.2                 Az.DevTestLabs                      Core,Desk
Script     1.1.2                 Az.Dns                              Core,Desk
Script     1.3.0                 Az.EventGrid                        Core,Desk
Script     1.6.0                 Az.EventHub                         Core,Desk
Script     1.6.1                 Az.FrontDoor                        Core,Desk
Script     1.0.2                 Az.Functions                        Core,Desk
Script     3.6.0                 Az.HDInsight                        Core,Desk
Script     1.1.0                 Az.HealthcareApis                   Core,Desk
Script     2.5.0                 Az.IotHub                           Core,Desk
Script     2.2.0                 Az.KeyVault                         Core,Desk
Script     1.0.0                 Az.Kusto                            Core,Desk
Script     1.3.2                 Az.LogicApp                         Core,Desk
Script     1.1.3                 Az.MachineLearning                  Core,Desk
Script     1.1.0                 Az.Maintenance                      Core,Desk
Script     1.1.0                 Az.ManagedServices                  Core,Desk
Script     1.0.2                 Az.MarketplaceOrdering              Core,Desk
Script     1.1.1                 Az.Media                            Core,Desk
Script     2.1.0                 Az.Monitor                          Core,Desk
Script     3.4.0                 Az.Network                          Core,Desk
Script     1.1.1                 Az.NotificationHubs                 Core,Desk
Script     2.3.0                 Az.OperationalInsights              Core,Desk
Script     1.3.1                 Az.PolicyInsights                   Core,Desk
Script     1.1.2                 Az.PowerBIEmbedded                  Core,Desk
Script     1.0.3                 Az.PrivateDns                       Core,Desk
Script     2.12.1                Az.RecoveryServices                 Core,Desk
Script     1.2.1                 Az.RedisCache                       Core,Desk
Script     1.0.3                 Az.Relay                            Core,Desk
Script     2.5.1                 Az.Resources                        Core,Desk
Script     1.4.1                 Az.ServiceBus                       Core,Desk
Script     2.2.0                 Az.ServiceFabric                    Core,Desk
Script     1.2.0                 Az.SignalR                          Core,Desk
Script     2.10.0                Az.Sql                              Core,Desk
Script     1.1.0                 Az.SqlVirtualMachine                Core,Desk
Script     2.6.0                 Az.Storage                          Core,Desk
Script     1.3.0                 Az.StorageSync                      Core,Desk
Script     1.0.1                 Az.StreamAnalytics                  Core,Desk
Script     1.0.0                 Az.Support                          Core,Desk
Script     1.0.4                 Az.TrafficManager                   Core,Desk
Script     1.11.0                Az.Websites                         Core,Desk
Binary     3000.37.45            DataGateway                         Core     
Binary     3000.37.45            DataGateway.Profile                 Core     

    Directory: /usr/local/share/powershell/Modules

ModuleType Version    PreRelease Name                                PSEdition
---------- -------    ---------- ----                                ---------
Script     1.2.1                 Az                                  Core,Desk
Script     1.9.2                 Az.Accounts                         Core,Desk
Script     1.5.2                 Az.Accounts                         Core,Desk
Script     1.2.1                 Az.Accounts                         Core,Desk
Script     1.0.1                 Az.Aks                              Core,Desk
Script     1.0.1                 Az.AnalysisServices                 Core,Desk
Script     1.0.0                 Az.ApiManagement                    Core,Desk
Script     1.0.0                 Az.ApplicationInsights              Core,Desk
Script     1.1.0                 Az.Automation                       Core,Desk
Script     1.0.0                 Az.Batch                            Core,Desk
Script     1.0.0                 Az.Billing                          Core,Desk
Script     1.0.1                 Az.Cdn                              Core,Desk
Script     1.0.0                 Az.CognitiveServices                Core,Desk
Script     1.2.0                 Az.Compute                          Core,Desk
Script     1.0.0                 Az.ContainerInstance                Core,Desk
Script     1.0.1                 Az.ContainerRegistry                Core,Desk
Script     1.0.1                 Az.DataFactory                      Core,Desk
Script     1.0.0                 Az.DataLakeAnalytics                Core,Desk
Script     1.0.2                 Az.DataLakeStore                    Core,Desk
Script     1.0.0                 Az.DevTestLabs                      Core,Desk
Script     1.0.0                 Az.Dns                              Core,Desk
Script     1.1.0                 Az.EventGrid                        Core,Desk
Script     1.0.0                 Az.EventHub                         Core,Desk
Script     1.0.0                 Az.HDInsight                        Core,Desk
Script     1.0.2                 Az.IotHub                           Core,Desk
Script     1.0.1                 Az.KeyVault                         Core,Desk
Script     1.1.0                 Az.LogicApp                         Core,Desk
Script     1.0.0                 Az.MachineLearning                  Core,Desk
Script     1.0.0                 Az.MarketplaceOrdering              Core,Desk
Script     1.0.0                 Az.Media                            Core,Desk
Script     1.0.0                 Az.Monitor                          Core,Desk
Script     1.1.0                 Az.Network                          Core,Desk
Script     1.0.0                 Az.NotificationHubs                 Core,Desk
Script     1.0.0                 Az.OperationalInsights              Core,Desk
Script     1.0.0                 Az.PolicyInsights                   Core,Desk
Script     1.0.0                 Az.PowerBIEmbedded                  Core,Desk
Script     1.0.1                 Az.RecoveryServices                 Core,Desk
Script     1.0.0                 Az.RedisCache                       Core,Desk
Script     1.0.0                 Az.Relay                            Core,Desk
Script     1.4.0                 Az.Resources                        Core,Desk
Script     1.1.1                 Az.Resources                        Core,Desk
Script     0.8.0                 Az.Security                         Core,Desk
Script     1.0.0                 Az.ServiceBus                       Core,Desk
Script     1.0.1                 Az.ServiceFabric                    Core,Desk
Script     1.0.2                 Az.SignalR                          Core,Desk
Script     1.1.0                 Az.Sql                              Core,Desk
Script     1.0.2                 Az.Storage                          Core,Desk
Script     1.0.0                 Az.StreamAnalytics                  Core,Desk
Script     1.0.1                 Az.TrafficManager                   Core,Desk
Script     1.1.0                 Az.Websites                         Core,Desk
Script     4.8.1                 Pester                              Desk     

    Directory: /usr/local/microsoft/powershell/7/Modules

ModuleType Version    PreRelease Name                                PSEdition
---------- -------    ---------- ----                                ---------
Manifest   1.2.5                 Microsoft.PowerShell.Archive        Desk     
Manifest   7.0.0.0               Microsoft.PowerShell.Host           Core     
Manifest   7.0.0.0               Microsoft.PowerShell.Management     Core     
Manifest   7.0.0.0               Microsoft.PowerShell.Security       Core     
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        Core     
Script     1.4.7                 PackageManagement                   Desk     
Script     2.2.4.1               PowerShellGet                       Desk     
Script     2.0.5                 PSDesiredStateConfiguration         Core     
Script     2.0.2                 PSReadLine                          Desk     
Binary     2.0.3                 ThreadJob                           Desk   
```

## Debug output

```
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-ratelimit-remaining-resource: Microsoft.Compute/GetVMImageFromLocation3Min;12999,Microsoft.Compute/GetVMImageFromLocation30Min;73998
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-served-by                : 0dd6d42f-4571-4310-a86b-4c8d74c6852e_132639744503594232
x-ms-request-id               : 55a6e6f8-3a27-4d00-93b1-5905901cbbb1
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 11999
x-ms-correlation-request-id   : e1a6be38-fb37-4b5b-bd3e-6e4c67c82463
x-ms-routing-request-id       : CANADACENTRAL:20210610T220430Z:e1a6be38-fb37-4b5b-bd3e-6e4c67c82463
X-Content-Type-Options        : nosniff
Date                          : Thu, 10 Jun 2021 22:04:30 GMT

Body:
{
  "error": {
    "code": "InvalidParameter",
    "message": "The value of parameter version is invalid.",
    "target": "version"
  }
}


DEBUG: AzureQoSEvent: CommandName - Get-AzVMImage; IsSuccess - True; Duration - 00:00:01.1692864;
DEBUG: Finish sending metric.
DEBUG: 6:04:32 PM - GetAzureVMImageCommand end processing.
Get-AzVMImage: The value of parameter version is invalid.
ErrorCode: InvalidParameter
ErrorMessage: The value of parameter version is invalid.
ErrorTarget: version
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : 55a6e6f8-3a27-4d00-93b1-5905901cbbb1
DEBUG: AzureQoSEvent: CommandName - Get-AzVMImage; IsSuccess - False; Duration - 00:00:01.1692864;; Exception - Microsoft.Azure.Commands.Compute.Common.ComputeCloudException: The value of parameter version is invalid.
ErrorCode: InvalidParameter
ErrorMessage: The value of parameter version is invalid.
ErrorTarget: version
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : 55a6e6f8-3a27-4d00-93b1-5905901cbbb1
```

## Error output

```
RequestId      : 
Message        : The value of parameter version is invalid.
                 ErrorCode: InvalidParameter
                 ErrorMessage: The value of parameter version is invalid.
                 ErrorTarget: version
                 StatusCode: 400
                 ReasonPhrase: Bad Request
                 OperationID : 55a6e6f8-3a27-4d00-93b1-5905901cbbb1
ServerMessage  : 
ServerResponse : 
RequestMessage : 
InvocationInfo : {Get-AzVMImage}
Line           : Get-AzVmImage -Location NorthEurope -PublisherName 
                 MicrosoftWindowsDesktop -Offer "Windows-10" -Sku "rs5-pro" 
                 -Version "latest"
Position       : At line:1 char:1
                 + Get-AzVmImage -Location NorthEurope -PublisherName 
                 MicrosoftWindowsDe …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 ~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet
                 .ExecuteClientAction(Action action)
                    at Microsoft.Azure.Commands.Compute.GetAzureVMImageCommand.
                 ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletE
                 xtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletE
                 xtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 
                 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletE
                 xtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePS
                 Cmdlet.ProcessRecord()
HistoryId      : 43

```

**Comment by amjads1** [comment] 2021-06-15 00:15
Looking into the issue.

**Comment by amjads1** [comment] 2021-06-22 01:11
Still investigating on this issue and will provide an update soon.

**Comment by amjads1** [comment] 2021-06-30 08:01
Based on the investigation on this issue, the document may be confusing but functionality is working as expected. The "latest" command was never supported for Get-AZVMImage in the past so the 400 response seems expected. Let me know if you have any further questions.

**Comment by thecherrytree** [comment] 2021-06-30 08:32
The documentation is not confusing, it is just wrong.

From the documentation:
You can also use `latest` if you want to use the latest image and not a specific older version.

```
$version = "2016.127.20170406"
Get-AzVMImage -Location $locName -PublisherName $pubName -Offer $offerName -Skus $skuName -Version $version
```
In our ARM template, you have to pass these same data elements, when we pass latest to these skus we got the same breaking error on previously working builds. 

After poking around, the problem is that these specific SKUs rs5-pro and rs4-pro have been sunset for rs5-pro-g2, though I don't use it, I am assuming rs4-pro-2.

**Comment by amjads1** [comment] 2021-07-08 07:40
The documentation is fixed and changes should reflect updated instructions as soon as possible.

With reference to SKUs, you are correct. It's confirmed that SKUs rs5-pro and rs4-pro are not available to use anymore. I will go ahead and close this issue now but feel free to re-open if you need any further help.

**Comment by jaylabell** [comment] 2022-12-15 19:50
@amjads1 Do you have an update on this item?

**Comment by amjads1** [comment] 2022-12-19 20:42
Looking into the issue.

**Comment by ebolton-cyber** [comment] 2023-01-03 19:50
@chrisrot this issue was transferred to me. I followed up on this issue and from my investigation, the SKUs in question- rs4, rs4-pro, rs5, rs5-pro have been deprecated so when you try to pull the latest version you get a 400 error because all existings versions under the SKU are also deprecated as well. We plan to improve the error message in this type of scenarios where a SKU gets deprecated. Let me know if this answers your question.

**Comment by Drewm3** [comment] 2023-02-02 23:12
Closing this issue because it looks like the question has been answered by @ebolton-cyber.

**Comment by thecherrytree** [comment] 2023-02-03 01:19
@Drewm3, this isn't fixed. Either the [documentation](https://learn.microsoft.com/en-us/azure/virtual-machines/windows/cli-ps-findimage) needs to be updated, or the cmdlet needs to be fixed. It was previously stated that the latest flag works, and that it was working on those other skus because they were being deprecated. This is not true, the `latest` flag simply does not work as intended. Please see examples below

 The documentation states:
> _"You can also use `latest` if you want to use the latest image and not a specific older version."_

The cmdlet `Get-AzVMImage` will return an array of images when you do not specify a version, see below. 


## Get-AzVMImage - No Version Specified

### commands
```
(base) PS > $publisher = 'MicrosoftSQLServer'                                                                     
(base) PS > $location = 'eastus'                                                                                  
(base) PS > $publisher = 'MicrosoftSQLServer'
(base) PS > $offer = 'sql2019-ws2019'                                                                             
(base) PS > $sku = 'standard'                                                                                     

(base) PS > Get-AzVMImage -Location "eastus" -PublisherName $publisher -Offer $offer -Sku $sku                  

Version     FilterExpression Skus     Offer          PublisherName      Location Id
-------     ---------------- ----     -----          -------------      -------- --
15.0.220308                  standard sql2019-ws2019 MicrosoftSQLServer eastus   /Subscriptions/4f98af3b-3c96-4578-b164-caa0e5f49807/Providers/Microsoft.Compute/…
15.0.220412                  standard sql2019-ws2019 MicrosoftSQLServer eastus   /Subscriptions/4f98af3b-3c96-4578-b164-caa0e5f49807/Providers/Microsoft.Compute/…
15.0.220510                  standard sql2019-ws2019 MicrosoftSQLServer eastus   /Subscriptions/4f98af3b-3c96-4578-b164-caa0e5f49807/Providers/Microsoft.Compute/…
15.0.220607                  standard sql2019-ws2019 MicrosoftSQLServer eastus   /Subscriptions/4f98af3b-3c96-4578-b164-caa0e5f49807/Providers/Microsoft.Compute/…
15.0.220614                  standard sql2019-ws2019 MicrosoftSQLServer eastus   /Subscriptions/4f98af3b-3c96-4578-b164-caa0e5f49807/Providers/Microsoft.Compute/…
15.0.220712                  standard sql2019-ws2019 MicrosoftSQLServer eastus   /Subscriptions/4f98af3b-3c96-4578-b164-caa0e5f49807/Providers/Microsoft.Compute/…
15.0.220809                  standard sql2019-ws2019 MicrosoftSQLServer eastus   /Subscriptions/4f98af3b-3c96-4578-b164-caa0e5f49807/Providers/Microsoft.Compute/…
15.0.220913                  standard sql2019-ws2019 MicrosoftSQLServer eastus   /Subscriptions/4f98af3b-3c96-4578-b164-caa0e5f49807/Providers/Microsoft.Compute/…
15.0.221011                  standard sql2019-ws2019 MicrosoftSQLServer eastus   /Subscriptions/4f98af3b-3c96-4578-b164-caa0e5f49807/Providers/Microsoft.Compute/…
15.0.221108                  standard sql2019-ws2019 MicrosoftSQLServer eastus   /Subscriptions/4f98af3b-3c96-4578-b164-caa0e5f49807/Providers/Microsoft.Compute/…
15.0.230110                  standard sql2019-ws2019 MicrosoftSQLServer eastus   /Subscriptions/4f98af3b-3c96-4578-b164-caa0e5f49807/Providers/Microsoft.Compute/…
```

However, if you do not know the version and you want the latest version, the cmdlet fails. This problem is actually quite challenging if you want your ARM template or API calls using the `AZ` module  or cli to choose latest image by default. `latest` is an _invalid_ parameter.

## Get-AzVMImage - `latest` Version Specified

```                                                                         
(base) PS > $version = 'latest'
(base) PS > Get-AzVMImage -Location "eastus" -PublisherName $publisher -Offer $offer -Sku $sku -Version $latest
Get-AzVMImage: Cannot validate argument on parameter 'Version'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
(base) PS > Get-AzVMImage -Location "eastus" -PublisherName $publisher -Offer $offer -Sku $sku -Version $version
Get-AzVMImage: The value of parameter version is invalid.
ErrorCode: InvalidParameter
ErrorMessage: The value of parameter version is invalid.
ErrorTarget: version
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : 747620df-2f58-47fc-be6f-8fa7499a382a
```
## Get-AzVmImage - `latest` Version Specified on Actively updated offers

```
(base) PS > $offer = 'sql2022-ws2022'                                                                           
(base) PS > Get-AzVMImage -Location "eastus" -PublisherName $publisher -Offer $offer -Sku $sku -Version $version
Get-AzVMImage: The value of parameter version is invalid.
ErrorCode: InvalidParameter
ErrorMessage: The value of parameter version is invalid.
ErrorTarget: version
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : 6e9f8825-b273-44f3-b669-ded876b40a6e


Please reopen and correct the documentation or correct the bug. None of the actions/comments above did anything to remediate the issue.

**Comment by thecherrytree** [comment] 2023-02-06 01:15
@Drewm3, @ebolton-cyber, @amjads1 - please reopen. This is not resolved, see: https://github.com/Azure/azure-powershell/issues/15248#issuecomment-1414583220

**Comment by ebolton-cyber** [comment] 2023-02-06 19:04
Thanks @thecherrytree for pointing this out. I would look into this again and update back accordingly.

**Comment by Drewm3** [comment] 2023-02-06 19:06
Sorry for closing this early. The focus on the Windows 10 image threw me off. Now, I see that the issue is in the documentation. The [documentation](https://learn.microsoft.com/en-us/azure/virtual-machines/windows/cli-ps-findimage) implies that the Get-AzVMImage cmdlet support "latest". However, in reality, only the New-AzVM cmdlet supports the use of "latest". 

I will reopen this issue, and I will make sure that an issue is opened on the documentation to fix the documentation to no longer imply that latest can be used in Get-AzVMImage.

**Comment by ebolton-cyber** [comment] 2023-02-06 19:07
Adding @Sandido FYI

**Comment by thecherrytree** [comment] 2023-02-06 19:09
Get-AzVmImage should allow you to get the latest image as well, no? Can this be a feature enhancement?

**Comment by Drewm3** [comment] 2023-02-07 00:37
The challenge right now is the underlying REST API does not support 'latest'. There are internal discussions to add support for latest in that API, and if that is done, then it would be supported directly in the cmdlet. If the underlying API is not updated, then we could add support by customizing the cmdlet, but we are likely going to wait until the REST API owner makes a decision for supporting latest.

Note: I do not believe this will give you latest:

`$image = (Get-AzVMImage -Location $location -PublisherName $publisher -Offer $offer -Sku $sku)[0]`

Instead you need to do:
```
$image= Get-AzVMImage -PublisherName $publisher -Location $location -Offer $offer -Skus $sku | sort-object -Descending {[version] $_.Version} |  Select-Object -First 1
```

This is because the versions may not always be published in order.

**Comment by thecherrytree** [comment] 2023-02-07 01:01
@Drewm3, that makes sense to me, just wanted to make sure there was awareness on it. My example there was for illustrative purposes, and agree with your implementation. 

What you've show also better illustrates the need for having support for `'latest'`.

**Comment by Drewm3** [comment] 2023-02-07 07:21
I 100% agree on the niceness of supporting 'latest' across more of the API surfaces. This is something I have spoken to the dev owners about multiple times in the past. The challenge ends up being prioritizing that work above the myriad of other requests on their time. 

We'll share this additional detail with the team and see if we can get something either in the API or at least in PS if we cannot get it into the API.

**Comment by Drewm3** [comment] 2023-03-09 18:34
Support for "latest" will be provided in an upcoming powershell release

**Comment by Drewm3** [comment] 2023-03-23 17:29
This support has been added in the lastest PS release: https://github.com/Azure/azure-powershell/releases/tag/v9.5.0-March2023

**Closed by Drewm3** 2023-03-23 17:29 UTC
Labels: Compute - Images, Service Attention, question, customer-reported
