### ISSUE TITLE
Get-Module -ListAvailable -name AZ - returns nothing, even though it IS installed.

### ISSUE THREAD

**Issue by lukeb1961** [Azure/azure-powershell#7553] opened 2018-10-14 11:05 UTC
Get-Module -ListAvailable  fails to find the AZ module. 

Get-Module -ListAvailable -All     # *does* show Az.aks, etc. but not Az

PS> Get-Module -ListAvailable -name AZ   # nothing returned...

PS> Import-Module -Name AZ
PS> (get-module -Name AZ).ModuleBase
C:\Program Files\WindowsPowerShell\Modules\AZ\0.3.0

PS> Get-Module -ListAvailable -name AZURERM

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    Name                                ExportedCommands                                                               
---------- -------    ----                                ----------------                                                               
Script     6.10.0     AzureRM                                                                                                            

PS> Import-Module -Name AZURERM
PS> (get-module -Name AZURERM).ModuleBase
C:\Program Files\WindowsPowerShell\Modules\AZURERM\6.10.0
PS> 
PS> $PSVersionTable

Name                             Value                                                                                                     
----                                 -----                                                                                                     
PSVersion                       5.1.17763.1                                                                                               
PSEdition                        Desktop                                                                                                   
PSCompatibleVersions   {1.0, 2.0, 3.0, 4.0...}                                                                                   
BuildVersion                   10.0.17763.1                                                                                              
CLRVersion                     4.0.30319.42000                                                                                           
WSManStackVersion      3.0                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                       
SerializationVersion        1.1.0.1

**Comment by MaximoTrinidad** [comment] 2018-10-14 13:07
Workaround!!  The following will display all new Az* modules installed.
```
Get-Module -ListAvailable Az* 
```
![azmodule_issue_00_2018-10-14_9-02-58](https://user-images.githubusercontent.com/19892435/46917048-86e20600-cf90-11e8-9de0-34f982b486df.jpg)

Also, you need to use the "-ListAvailable" parameter and not the '-Name' to display the ModuleBase information.
```
(get-module -ListAvailable Az*).ModuleBase
```
![azmodule_issue_01_2018-10-14_9-02-58](https://user-images.githubusercontent.com/19892435/46916992-07eccd80-cf90-11e8-9bed-0224a6c52a75.jpg)

Now, keep in mind, documentation states that you **can't** have both (old) AzureRM module installed (side-by-side) and the new Az module.

Yes! I don't know why typing the only "Az" is not listing the modules. I should have also reported but know about using the asterisk "*" to display them all.

:)

**Comment by MaximoTrinidad** [comment] 2018-10-15 13:32
Hi @lukeb1961,

First, I'm not missing the point, the last paragraph I was trying to say that you are right.  It's broken! 
I AGREE WITH YOU 100%!

I'll be meeting with the Microsoft PowerShell Team in Singapore this week and will discuss it with them.  They are normally good in responding quick on Github issues but I'm guessing that are traveling.

Both PowerShell Core and Azure will keep suffering changes.  

We appreciate you submitted this issue.

Keep in touch!

**Comment by markcowl** [comment] 2018-10-15 16:49
So, I think the issue is this: #7563 

We will fix this part of the roll-up module definition in the next release, which will hopefully resolve this problem.  If not, we will investigate and fix the underlying issue in the following release.

**Comment by markcowl** [comment] 2018-10-15 16:51
Closing as duplicate of #7563 You can track the fix there.

**Closed by markcowl** 2018-10-15 16:51 UTC

**Comment by MaximoTrinidad** [comment] 2018-10-15 19:08
Thx @markcowl!!

**Comment by MaximoTrinidad** [comment] 2018-10-18 08:19
Copying @SteveL-MSFT  

Steve,
This is the issue I talked you about.

:)

**Comment by woter1832** [comment] 2020-10-19 00:55
Now, 2 years on, almost to the day, this is still an issue for me, yet this issue has been closed. I've been around the houses following all the links above, and I cannot find the solution to why:

`Get-Module -Name Az -ListAvailable` returns `$null`

Perhaps someone would be so kind as to enlighten me to what the solution is.

T.I.A.

**Comment by Micael-stack** [comment] 2021-05-27 12:56
Same here, just stopped working PS 5.1. It was working for at least a couple of months straight. Now if i use get-module like this, it works : 
`Get-Module -ListAvailable -Name Az.*`

**Comment by sharath-sks** [comment] 2021-06-01 10:55
@Micael-stack even I echo you as I'm facing same issue. I installed azureRM module but when I run Get-InstalledModule it's not listing azureRM. I'm wondering what could go wrong. 
Any help from team?

**Comment by Micael-stack** [comment] 2021-06-01 11:00
@sharath-sks having both AzureRM and Az is not compatible. You need to uninstall the other if you want to use Az. 
https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-6.0.0#az-and-azurerm-coexistence

**Comment by sharath-sks** [comment] 2021-06-01 11:17
> @sharath-sks having both AzureRM and Az is not compatible. You need to uninstall the other if you want to use Az.
> https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-6.0.0#az-and-azurerm-coexistence

I updated my comment with a screenshot. I tried to uninstall azureRM and it says no module found. So I installed Az module, no error but when I try to list installed modules it's not showing up in the output. I tried running commands they also failed. It means that package is not installed.

**Comment by Micael-stack** [comment] 2021-06-01 11:19
@sharath-sks got it. Did you try with my workaround to see if it shows? 
`Get-Module -ListAvailable -Name Az.*`

**Comment by sharath-sks** [comment] 2021-06-01 11:26
> @sharath-sks got it. Did you try with my workaround to see if it shows?
> `Get-Module -ListAvailable -Name Az.*`

Yes, but returns nothing.

**Comment by vinoddanekar** [comment] 2021-08-03 17:56
Happened to me too but found solution by installing it.
```
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force
```
Found it in the article below:
https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-6.3.0

After installing, it returns a table with versions.

**Comment by itsamemarkus** [comment] 2022-10-29 10:17
I don't know if this helps anyone after this is closed, but I noticed that all my WinRM modules got installed by Visual Studio Enterprise 2022 Preview -> Azure development and it caused the error `may override the existing commands.` when trying to install Az from gallery.
