### ISSUE TITLE
Remove-AzSynapseTrigger only works on Stopped triggers; the -Force parameter is useless

### ISSUE THREAD

**Issue by daj102** [Azure/azure-powershell#19441] opened 2022-09-08 21:20 UTC
### Description

As confirmed by MSFT folks [here](https://docs.microsoft.com/en-us/answers/questions/603468/removing-az-synpase-trigger.html), Remove-AzSynapseTrigger only works on stopped triggers.  However, there is a -Force parameter that suggests that it will stop and delete the trigger immediately - but all it really does is stop the confirmation question.  At the very least, the documentation page form the API method needs to explain that you need to stop the trigger, but really the -Force parameter should do more than just stop confirmation.

Even worse, if the Remove cmdlet is used with -PassThru, it returns $true - even if the deletion doesn't happen.

### Issue script & Debug output

```PowerShell
# Input parameters
param(
    [string]$SynapseWorkspace = $(throw "SynapseWorkspace parameter is required."),
    [string]$ResourceGroup = $(throw "ResourceGroup parameter is required."),
    [string]$Action = $(throw "Action parameter is required [start|stop|delete]"),
    [string]$NameFilter = "",
    [switch]$WhatIf
    )


# Get the specified workspace
Write-Output ("Getting workspace {0} in resource group {1}" -f $synapseworkspace, $resourcegroup)
$workspace = Get-AzSynapseWorkspace -ResourceGroupName $resourcegroup -Name $synapseworkspace
if (-not($workspace)) { throw "Could not find workspace" }
Write-Output $workspace

# Get the list of triggers if the workspace 
Write-Output "Getting triggers"
$triggers = Get-AzSynapseTrigger -WorkspaceObject $workspace
if ($namefilter -ne '-') { $triggers = $triggers | Where-Object {$_.Name -match $namefilter} } # filter out names if the filter is specified
Write-Output ("Found {0} triggers" -f $triggers.Count)
if (-not($triggers)) { exit }


# Continue only if there are triggers to be found
if ($triggers.Count -gt 0) {
    if ($action -eq "start") {
        # Start triggers
        Write-Output "Looping through triggers that are stopped ..."
        $stoppedtriggers = $triggers | Where-Object { $_.Properties.RuntimeState -eq "Stopped" }
        Write-Output ("Found {0} stopped triggers" -f $stoppedtriggers.Count)

        foreach ($t in $stoppedtriggers) {
            Write-Output ("Starting {0} ..." -f $t.Name);
            try {
                $result = Start-AzSynapseTrigger -WorkspaceName $synapseworkspace -Name $t.name -WhatIf:$WhatIf.IsPresent -PassThru
                Write-Output ("Result of starting trigger {0}: {1}" -f $t.Name, $result)
            }
            catch {
                Write-Output ("Something went wrong with {0}" -f $t.Name)
                Write-Output $_
            }
        }
    }

    if ($action -eq "stop") {
        # Stop the triggers
        Write-Output "Looping through triggers that are started ..."
        $startedtriggers = $triggers | Where-Object { $_.Properties.RuntimeState -eq "Started" }
        Write-Output ("Found {0} started triggers" -f $startedtriggers.Count)

        foreach ($t in $startedtriggers) {
            Write-Output ("Stopping {0} ..." -f $t.Name);
            try {
                $result = Stop-AzSynapseTrigger -WorkspaceName $synapseworkspace -Name $t.name -WhatIf:$WhatIf.IsPresent -PassThru
                Write-Output ("Result of stopping trigger {0}: {1}" -f $t.Name, $result)
            }
            catch {
                Write-Output ("Something went wrong with {0}" -f $t.Name)
                Write-Output $_
            }
        }
    }

    if ($action -eq "delete") {
        # Remove the triggers
        Write-Output "Looping through all triggers to delete them ..."

        foreach ($t in $triggers) {
            Write-Output ("Deleting {0} ..." -f $t.Name);
            try {
                # YOU NEED TO STOP THE TRIGGER FIRST - IF YOU DON'T, THE REMOVE FAILS SILENTLY!!!
                # EVEN WORSE - THE RETURN RESULT IS TRUE
                $result = Stop-AzSynapseTrigger -WorkspaceName $synapseworkspace -Name $t.name -WhatIf:$WhatIf.IsPresent -PassThru
                Write-Output ("Result of stopping trigger {0}: {1}" -f $t.Name, $result)
                $result = Remove-AzSynapseTrigger -WorkspaceName $synapseworkspace -Name $t.name -Force -WhatIf:$WhatIf.IsPresent -PassThru 
                Write-Output ("Result of deleting trigger {0}: {1}" -f $t.Name, $result)
            }
            catch {
                Write-Output ("Something went wrong with {0}" -f $t.Name)
                Write-Output $_
            }
        }
    }

    Write-Output "... done"
}
```

### Environment data

```PowerShell
ame                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}       
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.10.0                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}     
Script     0.19.0                Az.Synapse                          {Add-AzSynapseDataFlowDebugSessionPackage, Add-AzSynapseTriggerSubscripti…
```

**Comment by SaurabhSharma-MSFT** [comment] 2022-09-09 15:32
@daj102 We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment] 2022-09-14 19:56
@daj102 You are right `-Force` doesn't delete a trigger forcefully.  However, the purpose of `-Force` parameter is mentioned in the [documentation ](https://docs.microsoft.com/en-us/powershell/module/az.synapse/remove-azsynapsetrigger?view=azps-8.3.0)that it is only for not displaying the confirmation. 
![image](https://user-images.githubusercontent.com/38112130/190249838-33fd32d3-15bd-4873-968c-02d79a20bf11.png)

**Comment by daj102** [comment] 2022-09-14 20:12
Yes, agreed ... I think that the documentation there is technically
correct, but it could be misinterpreted.  No matter - the real issue with
the method is that there is no way to tell it to really, actually, truly
delete a trigger if it is started.  I think a new switch needs to be added
that stops the trigger first (and you have to specify it for safety), or
the return value should reflect the fact that the trigger was not deleted.
Right now, it returns a happy value, does not throw an exception, and does
not delete the trigger.  I mentioned the Force parameter just to show that
I had tried various options ... ultimately, my issues is that you can call
the method, it returns success - but yet doesn't do the thing it was asked
to do.

**Comment by SaurabhSharma-MSFT** [comment] 2022-09-20 14:36
@daj102 sure. I get your point and redirecting this to services team to check if this can be addressed in any future releases.  Thanks for your feedback.

**Comment by yanjungao718** [comment] 2022-10-17 05:49
@daj102 sorry for late response.
about the -Force parameter, it means to execute the cmdlet without confirmation, and will do nothing to the cmdlet itself on the logical layer(for example, stop an started trigger before deleting)

for deleting started triggers, the cmdlet now gives out detail messages shown below, you need to upgrade your Az.Synapse module version to latest

![image](https://user-images.githubusercontent.com/85206987/196097313-f67acc2f-64ff-46a9-9ab4-e63cc3ebf082.png)
![image](https://user-images.githubusercontent.com/85206987/196098779-55cb9372-a383-4f6d-bcea-1943d520a7bc.png)

**Comment by wonner** [comment] 2022-11-04 07:45
Close as it's by design. Please feel free to reopen it if you have other question. Thanks.

**Closed by wonner** 2022-11-04 07:46 UTC
Labels: feature-request, Service Attention, customer-reported, Synapse
