### ISSUE TITLE
Az Module offline version terminating immediately

### ISSUE THREAD

**Issue by manomar01** [Azure/azure-powershell#11483] opened 2020-04-02 22:34 UTC
When offline Az modules are launched as Admin user or not, it terminates

![az_module_install_error](https://user-images.githubusercontent.com/62667075/78306124-7791a800-74f7-11ea-8023-76748fe8d377.PNG)

**Comment by dingmeng-xue** [comment] 2020-04-03 10:20
@manomar01 , could you share your environment information? What's the version of your OS?

**Comment by dingmeng-xue** [comment] 2020-04-03 10:30
@manomar01 , could you share out put of below command?
```
Dism /online /Get-FeatureInfo:NetFx3
```

**Comment by manomar01** [comment] 2020-04-03 15:07
Here is the info. Server is running Windows Server 2016 DataCenter.

C:\windows\system32>Dism /online /Get-FeatureInfo:NetFx3

Deployment Image Servicing and Management tool
Version: 10.0.14393.3241

Image Version: 10.0.14393.3241

Feature Information:

Feature Name : NetFx3
Display Name : .NET Framework 3.5 (includes .NET 2.0 and 3.0)
Description : .NET Framework 3.5 (includes .NET 2.0 and 3.0)
Restart Required : Possible
State : Disabled with Payload Removed

Custom Properties:

FWLink : http://go.microsoft.com/fwlink/?LinkId=296822
ServerComponent\Description : .NET Framework 3.5 combines the power of the .NET Framework 2.0 APIs with new technologies for building applications that offer appealing user interfaces, protect your customers' personal identity information, enable seamless and secure communication, and provide the ability to model a range of business processes.
ServerComponent\DisplayName : .NET Framework 3.5 (includes .NET 2.0 and 3.0)
ServerComponent\Id : 220
ServerComponent\InstallWithParentByDefault : true
ServerComponent\Parent : NET-Framework-Features
ServerComponent\Type : Feature
ServerComponent\UniqueName : NET-Framework-Core
ServerComponent\Deploys\Update\Name : NetFx3
ServerComponent\Version\Major : 3
ServerComponent\Version\Minor : 5

The operation completed successfully.

C:\windows\system32>ver

Microsoft Windows [Version 10.0.14393]

**Comment by dingmeng-xue** [comment] 2020-04-07 13:23
After the call, the issue is mitigated after copying az modules to Windows PowerShell module folder. One potential issue in user's environment is current user has no enough permission to program folder.

Close this issue and please create a new one if the similar issue shows again.

**Closed by dingmeng-xue** 2020-04-07 13:23 UTC
Labels: Azure PS Team, More Info :label:, customer-reported
