### ISSUE TITLE
Get-AzRecoveryServicesBackupItem not able to show WorkloadType Windows

### ISSUE THREAD

**Issue by peppekerstens** [Azure/azure-powershell#10521] opened 2019-11-12 06:38 UTC
## Scenario
https://docs.microsoft.com/en-us/azure/backup/backup-configure-vault

## Goal
Get a overview of the succeeded/failed backups

## Description
In order to get the information I am using the following example as a code baseline:
https://docs.microsoft.com/en-us/powershell/module/az.recoveryservices/get-azrecoveryservicesbackuprecoverypoint?view=azps-3.0.0#examples

## Steps to reproduce
Create the scenario, ensure that some backups are created.
Try to use the provided code to create an overview via PowerShel.

While you are able to choose the right parameter values for the  Get-AzRecoveryServicesBackupContainer command, you are not able to choose Windows(Server) as a WorkloadType for the Get-AzRecoveryServicesBackupItem.

There have been earlier bug reports on this:
https://github.com/Azure/azure-powershell/issues/6595
https://github.com/Azure/azure-powershell/issues/5704

All closed with no resolution. Time has passed on; we need something workable.

With this bug report I do **not** request the MARS/Windows option to be fully integrated in all AzRecoveryServices commands. I just need to be able to provide a status report; same as the Azure portal GUI is able to produce.

I am working for a service provider, managing many environments at once. Redirecting me to the OB-Powershell module is not an acceptable workaround/solution.

## Environment data

```powershell
$psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.18956.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18956.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

## Module versions

```powershell
get-package az

Name                           Version          Source                           ProviderName
----                           -------          ------                           ------------
Az                             3.0.0            https://www.powershellgallery... PowerShellGet
```

## Debug output

```

```

## Error output

```

```

**Comment by peppekerstens** [comment] 2019-11-12 07:50
This is needed functionality (also able to produce result with this commando);
https://docs.microsoft.com/en-us/rest/api/backup/backupprotecteditems/list

**Comment by pvrk** [comment] 2019-11-25 08:31
@peppekerstens: Thanks for the clarity you provided with the statement:

"I just need to be able to provide a status report; same as the Azure portal GUI is able to produce".

I need more clarification on the command themselves. You gave the command for getting containers but the API listed is protecteditems (get-AzRecoveryServicesBackupItems). So, are you looking for retrieval in both? or for just container command?

**Comment by pvrk** [comment] 2019-11-25 09:54
@peppekerstens: For containers protected using Microsoft Azure Backup agent at least, you can get unblocked by running the command with "-ContainerType Windows"

```powershell

Get-AzRecoveryServicesBackupContainer -ContainerType Windows -BackupManagementType MARS

```

**Comment by pvrk** [comment] 2019-11-25 10:11
@peppekerstens: Apologize. I have gone through the details once again. Looks like you are good with container but require backup item specifically. We acknowledge the request. Please give me few days to update the thread with the plan.

**Comment by brpowershell** [comment] 2020-02-27 18:30
Any update on this? How to get back up items for Windows (ContainerType) and MARS (BackupManagementType) using powershell?

**Comment by pvrk** [comment] 2020-03-10 15:17
@brpowershell : Apologies for the delay. We are still in planning stages. Will get back with the actual PS milestone soon.

**Comment by pvrk** [comment] 2020-09-14 18:35
@brpowershell : With the PS release in August (4.5.0), you should be able to view backup items of type windows and jobs too. This should fulfill the requirement.

**Comment by pvrk** [comment] 2020-09-14 18:43
Closing this issue since the feature request was delivered. Please feel free to re-open if the issue is not solved.

**Closed by pvrk** 2020-09-14 18:43 UTC
Labels: Recovery Services Backup, Service Attention, customer-reported, feature-request

**Comment by Wand3rvogel** [comment] 2021-07-27 16:25
@pvrk 

Is not resolved.
Az.RecoveryServices 4.4.0

Get-AzRecoveryServicesBackupItem
The Parameter WorkloadType has values: AzureFiles, AzureSQLDatabase, AzureVM, FileFolder, MSSQL

Nothing works with MARS/Windows.
Get-AzRecoveryServicesBackupItem : Unsupported WorkloadType: FileFolder

``` Powershell
$servers = Get-AzRecoveryServicesBackupContainer -ContainerType Windows -BackupManagementType MARS -VaultId $vault.ID

foreach ($server in $servers) {
    $items = Get-AzRecoveryServicesBackupItem -Container $server -WorkloadType ??????
    foreach ($item in $items) {
        Disable-AzRecoveryServicesBackupProtection -item $item -RemoveRecoveryPoints -VaultId $vault.ID
    }
    Unregister-AzRecoveryServicesBackupContainer -Container $server -VaultId $vault.ID
}
Remove-AzRecoveryServicesVault -Vault $vault

```

**Comment by pvrk** [comment] 2021-08-02 10:08
@Wand3rvogel : I will try to explain few issues here:

1. If the ultiimate intent is to clear the vault by deleting all MAB backups, then you don't need to disable-protection.
2. You can disable protection from Azure Backup APIs for Azure items such as VM, SQL, HANA, AFS etc. For non-Azure items, you can't disable protection from API, PS, CLI, Portal etc.
3. What you need is "unregister' which is DELETE ALL backup items for that containers. For MAB, this translates to delete all. For others, it works only if you previously deleted backup items.
4. So, for your script, you just need the unregister command in for each loop of server. The for-each loop of backup items is not required.

This feature was introduced to GET ALL data (including MAB) only. Actions are still limited from their current interfaces.

Hope I made sense.

**Comment by Wand3rvogel** [comment] 2021-08-02 12:25
> then you don't need to disable-protection

> you just need the unregister command in for each loop of server

Unregister-AzRecoveryServicesBackupContainer : There are backup items associated with the server. **Stop protection and
delete backups for each of the backup items to delete the server's registration.** If the issue persists, contact
support. Refer to https://aka.ms/DeleteBackupItems for more info.
In Zeile:1 Zeichen:1
+ Unregister-AzRecoveryServicesBackupContainer -Container $servers[0] - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Unregister-AzRe...BackupContainer], CloudException
    + FullyQualifiedErrorId : ServiceContainerNotEmptyWithBackendMessage,Microsoft.Azure.Commands.RecoveryServices.Bac
   kup.Cmdlets.UnregisterAzureRmRecoveryServicesBackupContainer

**Comment by pvrk** [comment] 2021-08-03 17:06
@Wand3rvogel : I just rerun the exact sequence and it worked for me. Surprised as to why this is not working for you. Can you please re-run the command with "-debug" option and share the output?

**Comment by Wand3rvogel** [comment] 2021-08-04 14:29
`Unregister-AzRecoveryServicesBackupContainer -Container $servers[0] -VaultId $vault.ID -Debug`

```
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
DELETE

Absolute Uri:
https://management.azure.com/Subscriptions/<ID>/resourceGroups/<groupName>/providers/Microsoft.
RecoveryServices/vaults/<vault>/registeredIdentities/<serverName>?api-version=2016-06-01

Headers:
x-ms-client-request-id        : 4c0be97e-ea72-4c50-a384-59be5d9fc7ff
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
X-Content-Type-Options        : nosniff
x-ms-request-id               : bc52b6d4-2fdd-486e-a2b1-4eb94a59220e
x-ms-client-request-id        : 4c0be97e-ea72-4c50-a384-59be5d9fc7ff,4c0be97e-ea72-4c50-a384-59be5d9fc7ff
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-deletes: 14999
x-ms-correlation-request-id   : bc52b6d4-2fdd-486e-a2b1-4eb94a59220e
x-ms-routing-request-id       : GERMANYWESTCENTRAL:20210804T141644Z:bc52b6d4-2fdd-486e-a2b1-4eb94a59220e
Cache-Control                 : no-cache
Date                          : Wed, 04 Aug 2021 14:16:43 GMT
Server                        : Microsoft-IIS/10.0

Body:
{
  "error": {
    "code": "ServiceContainerNotEmptyWithBackendMessage",
    "message": "There are backup items associated with the server. Stop protection and delete backups for each of the
backup items to delete the server's registration. If the issue persists, contact support. Refer to
https://aka.ms/DeleteBackupItems for more info. ",
    "target": null,
    "details": null,
    "innerError": null
  }
}
DEBUG: Caught exception, type: System.AggregateException
DEBUG: Handling aggregate exception
DEBUG: Received CloudException, ErrorCode: ServiceContainerNotEmptyWithBackendMessage, Message: There are backup items
associated with the server. Stop protection and delete backups for each of the backup items to delete the server's
registration. If the issue persists, contact support. Refer to https://aka.ms/DeleteBackupItems for more info.
```

**Comment by pvrk** [comment] 2021-08-04 18:44
@Wand3rvogel : Thanks for the details. I can do it from portal and REST API. But Powershell and CLI seems to have some problem. My earlier attempts for powershell were for containers which had 0 backup items and those succeeded. I will investigate internally and come back.
