### ISSUE TITLE
"Request timed out" error while deploying resources from Azure DevOps

### ISSUE THREAD

**Issue by solatwal** [Azure/azure-powershell#10055] opened 2019-09-18 08:42 UTC
## Description
We are deploying multiple Azure resources like – Azure webapps, Azure Databricks, etc. from Azure DevOps (powershell script). 
Although the resource had been successfully deployed in the backend, Azure devops task failed multiple times with error message – request timed out.

The particular call that is failing as per the devops logs is – 

Get-AzPolicyDefinition
2019-07-30T03:13:05.9700762Z ##[debug]+                      ~~~~~~~~~~~~~~~~~~~~~~
2019-07-30T03:13:05.9715900Z ##[debug]    + CategoryInfo          : CloseError: (:) [Get-AzPolicyDefinition], Exception
2019-07-30T03:13:05.9729430Z ##[debug]    + FullyQualifiedErrorId : Operation failed because a request timed out.,Microsoft.Azure.Commands.ResourceManager.C    mdlets.Implementation.GetAzurePolicyDefinitionCmdlet

Since it is a powershell call from Azure DevOps, we suspect it is an issue with the powershell cmdlet. 

We want to know why these deployments are failing. This is happening for multiple resources at multiple times.

**Comment by erich-wang** [comment] 2019-09-19 04:55
@solatwal , could you please provide the info:
-  Get PowerShell version info
  - $PSVersionTable
- The list of modules installed on your machine
  -  Run Get-Module -ListAvailable
- The debug output from running 
  - Set $DebugPreference = "Continue" and then run the commands
- Error info
  - Resolve-AzError

**Comment by erich-wang** [comment] 2019-09-23 15:11
Unfortunately, it is difficult for us to identify what is the root cause without debug info.
Given latest version of Az is 2.6, I suggest you to upgrade your script to use Az 2.6 if possible, maybe the issues has been fixed in latest version.

**Comment by erich-wang** [comment] 2019-10-11 03:47
@solatwal, could you please provide the info I asked? We'll close the issue if we don't hear from you in 5 days.

**Comment by dingmeng-xue** [comment] 2019-10-18 00:51
Close this issue due to inactive. Please create new one if this issue occurs again.

**Closed by dingmeng-xue** 2019-10-18 00:51 UTC
Labels: Azure PS Team, More Info :label:, customer-reported
