### ISSUE TITLE
Storage account named xxx already taken

### ISSUE THREAD

**Issue by aggerritsen** [Azure/azure-powershell#19219] opened 2022-08-12 09:57 UTC
### Description

When trying to create a storage account named hubneloggingnesa I do get a failure that the account name already exits. 

If I run Get-AzStorageAccountNameAvailability -Name hubnwloggingnesa  it returns true. 
When I run Create-AzStorageAccount in debug mode, I notices that the name is available and still the creation fails
When I do try to restore an old version of Storage Account in a different region, but with the same name, the result is succesful

### Issue script & Debug output

```PowerShell
New-AzStorageAccount `
        -AccountName $storageAccountName `
        -ResourceGroupName $resourceGroupName `
        -Location $location `
        -SkuName Standard_LRS `
        -Kind StorageV2 `
        -AccessTier Cool `
        -Tag $tags -debug
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core 
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.8.0                 Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzCo…Script     2.0.1                 Az.Monitor                          {Add-AzAutoscaleSetting, Add-AzLogProfile, Add…Script     4.17.0                Az.Network                          {Add-AzApplicationGatewayAuthenticationCertifi…Script     3.1.0                 Az.OperationalInsights              {Disable-AzOperationalInsightsIISLogCollection…Script     1.0.3                 Az.PrivateDns                       {Add-AzPrivateDnsRecordConfig, Get-AzPrivateDn…Script     6.0.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec…Script     4.6.0                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStor…
```

### Error output

```PowerShell
HistoryId: 19

RequestId      : 58c14e61-53d1-4f69-b2af-8d0dd8e82bf7
Message        : The storage account named hubnwloggingnesa is already taken.
ServerMessage  : StorageAccountAlreadyTaken: The storage account named hubnwloggingnesa is already taken. (System.Collections.Generic.List`1[Microsoft.Rest.Azure.CloudError])
ServerResponse : {Conflict}
RequestMessage : {PUT https://management.azure.com/subscriptions/ae5fee10-f689-4251-aa54-6c4592896873/resourceGroups/berprd-infobjects-eunorth/providers/Microsoft.Storage/storageAccounts/hubnwloggingnesa?api-version=2021-09-01}     
InvocationInfo : {New-AzStorageAccount}
Line           :     $storageAccount = New-AzStorageAccount `

Position       : At line:1 char:23
                 +     $storageAccount = New-AzStorageAccount `
                 +                       ~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Management.Storage.StorageAccountsOperations.BeginCreateWithHttpMessagesAsync(String resourceGroupName, String accountName, StorageAccountCreateParameters parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.Storage.StorageAccountsOperations.CreateWithHttpMessagesAsync(String resourceGroupName, String accountName, StorageAccountCreateParameters parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.Storage.StorageAccountsOperationsExtensions.CreateAsync(IStorageAccountsOperations operations, String resourceGroupName, String accountName, StorageAccountCreateParameters parameters, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.Storage.StorageAccountsOperationsExtensions.Create(IStorageAccountsOperations operations, String resourceGroupName, String accountName, StorageAccountCreateParameters parameters)    
                    at Microsoft.Azure.Commands.Management.Storage.NewAzureStorageAccountCommand.ExecuteCmdlet()    
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 19



Output from debug:

============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://management.azure.com/subscriptions/ae5fee10-f689-4251-aa54-6c4592896873/providers/Microsoft.Storage/checkNameAvailability?api-version=2021-09-01

Headers:
x-ms-client-request-id        : 833b6248-d64b-4fbb-81fd-f847ca59c072
Accept-Language               : en-US

Body:
{
  "name": "hubnwloggingnesa",
  "type": "Microsoft.Storage/storageAccounts"
}


============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-request-id               : fee69f9d-29fe-454d-a26b-1181b760ef97
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Server                        : Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 11998
x-ms-correlation-request-id   : 9ea22ccd-5920-49c6-a848-b321d7af5b24
x-ms-routing-request-id       : WESTEUROPE:20220812T095401Z:9ea22ccd-5920-49c6-a848-b321d7af5b24
X-Content-Type-Options        : nosniff
Date                          : Fri, 12 Aug 2022 09:54:01 GMT

Body:
{
  "nameAvailable": true
}


============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/ae5fee10-f689-4251-aa54-6c4592896873/resourceGroups/berprd-infobjects-eunorth/providers/Microsoft.Storage/storageAccounts/hubnwloggingnesa?api-version=2021-09-01

Headers:
x-ms-client-request-id        : 833b6248-d64b-4fbb-81fd-f847ca59c072
Accept-Language               : en-US

Body:
{
  "sku": {
    "name": "Standard_LRS"
  },
  "kind": "StorageV2",
  "location": "northeurope",
  "tags": {
    "Team": "CloudTeam"
  },
  "properties": {
    "accessTier": "Cool"
  }
}


============================ HTTP RESPONSE ============================

Status Code:
Conflict

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-request-id               : d0c89e44-dc11-4cc7-8215-e6c2ab35ae2d
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Server                        : Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : c9986b8b-dee7-400f-b95a-7b024ed62979
x-ms-routing-request-id       : WESTEUROPE:20220812T095405Z:c9986b8b-dee7-400f-b95a-7b024ed62979
X-Content-Type-Options        : nosniff
Date                          : Fri, 12 Aug 2022 09:54:05 GMT

Body:
{
  "error": {
    "code": "StorageAccountAlreadyTaken",
    "message": "The storage account named hubnwloggingnesa is already taken."
  }
}


11:54:05 - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].

New-AzStorageAccount: The storage account named hubnwloggingnesa is already taken.
11:54:05 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
AzureQoSEvent: Module: Az.Storage:4.6.0; CommandName: New-AzStorageAccount; PSVersion: 7.2.5; IsSuccess: False; Duration: 00:00:04.8194660; Exception: The storage account named hubnwloggingnesa is already taken.;
Finish sending metric.
11:54:05 - NewAzureStorageAccountCommand end processing.
```

**Comment by blueww** [comment] 2022-08-12 10:19
@aggerritsen 
Thanks for reporting this issue!
This is a server issue instead of Azure Powershell issue (we can't fix it by change Azure Powershell code).

I will contact the server team and update you later.

Besides that, I see account "hubnwloggingnesa" already exit. 
Have you created the account successfully after this failure?

And for the failure, have you deleted a storage account with this same name, and create it just after delete?

**Comment by aggerritsen** [comment] 2022-08-12 10:25
Hi Wei Wei

The whole point is that the account not exist as the attached image will show you. Previous versions of the account were deleted this morning after multiple restores and deletions.

Thanks for passing this to the appropriate team.

Kind regards,

Arjen Gerritsen | Cloud Architect/Consultant
T +31 (0) 6 3011 3411 |[Email_handtekening_icoontje-linkedin-klein] https://www.linkedin.com/in/aggerritsen/


Van: Wei Wei ***@***.***>
Verzonden: vrijdag 12 augustus 2022 12:20
Aan: Azure/azure-powershell ***@***.***>
CC: Arjen Gerritsen ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Azure/azure-powershell] Storage account named xxx already taken (Issue #19219)


@aggerritsen<https://github.com/aggerritsen>
Thanks for reporting this issue!
This is a server issue instead of Azure Powershell issue (we can't fix it by change Azure Powershell code).

I will contact the server team and update you later.

Besides that, I see account "hubnwloggingnesa" already exit.
Have you created the account successfully after this failure?

And for the failure, have you deleted a storage account with this same name, and create it just after delete?

**Comment by blueww** [comment] 2022-08-12 10:34
@aggerritsen 

Forget to mention, a better way to contact the server team is file an issue on Azure Portal.

![image](https://user-images.githubusercontent.com/6926193/184337341-64ecf0af-0182-43e8-a466-1757bb618efc.png)

You can add the above https request/responds to the issue, and ask why server says the account  "nameAvailable": true in one request, but return StorageAccountAlreadyTaken in another.
Please also add the info that you have deleted storage account with same name in the same day.

**Comment by navba-MSFT** [comment] 2022-08-16 03:55
@aggerritsen Removing CXP attention label since Service team has been involved already

**Comment by blueww** [comment] 2023-04-25 07:25
@aggerritsen

Per server team, you are trying to create the account with same name in two different subscriptions, and it's by design that server will block that with a 409. 
Server bind a deleted account with its original subscription until the account gets GCed (deletion date + 14 days of retention) to protect customer from dangling subdomain takeover attacks. Please see this link for details on why this protection is in place:  [https://docs.microsoft.com/en-us/azure/security/fundamentals/subdomain-takeover](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fsecurity%2Ffundamentals%2Fsubdomain-takeover&data=05%7C01%7Cweiwei%40microsoft.com%7Cf2ebe962d3524e171e8f08daa3b79a05%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638002306252151957%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9fkLZCYCb2SHeuqnrtUBgZ%2F%2B6sSDJq45RQI9Yss%2FwQo%3D&reserved=0).

I will close this issue as this is not Powershell issue, and it's also by design on server side.
Feel free to contact us if you need any further assistance on Azure Powershell.

**Closed** 2023-04-25 07:27 UTC
Labels: Storage, Service Attention, bug, customer-reported, Service

**Comment by vlardn** [comment] 2024-04-22 15:48
@blueww How long this "cooling off period" could be? Could it be reduced by support request?

**Comment by blueww** [comment] 2024-04-23 02:30
@vlardn 

This is not a PowerShell question, but a question for server behavior.
You can raise a help ticket to get support from server team by:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request#go-to-help--support-from-the-global-header.

Besides that, this link might can help you: https://stackoverflow.com/questions/72867938/storage-account-name-already-taken-after-being-deleted-from-another-tenant
It says: "You can reuse it immediately in the current tenant but must wait up to 14 days (or when the garbage collector finally deletes the storage account and frees up the domain). "
