### ISSUE TITLE
ResourceGroupName parameter should not be mandatory for Get-AzureRmSqlServer

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-powershell#2260] opened 2016-05-13 11:11 UTC
ResourceGroupName parameter should not be mandatory for Get-AzureRmSqlServer

Cheers,
**Trevor Sullivan**
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by markcowl** [comment] 2016-05-16 16:59
@akromm Please route to the appropriate person on the Sql team.  This will soon be a requirement for Get cmdlets for RPs.

**Comment by pcgeek86** [comment] 2016-05-26 17:02
@akromm @markcowl This is still a problem. Has anyone started work on this?

**Comment by akromm** [comment] 2017-06-15 20:26
Closing as duplicate of #635

**Closed by akromm** 2017-06-15 20:26 UTC
Labels: Sql
