### ISSUE TITLE
Set-AzureRmStorageAccount content needs updating

### ISSUE THREAD

**Issue by TaraMeyer** [Azure/azure-powershell#4979] opened 2017-11-13 23:17 UTC
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

Under "-KeyName", what the heck does this mean: "Storage Account encryption keySource KeyVault KeyName" ?
Also, note that "Storage Account" is not a product, and should not be capitalized. Of course if it starts the sentence, it should be "Storage account ... "
Under "-KeyVaultUti", what does "Storage Account encryption keySource KeyVault KeyVaultUri" mean? Same question for "KeyVersion".
Under -Name", why is modify capitalized?
Under "-AccessTier", the link to the hot and cold storage tiers information is messed up.
Under "-DefaultProfile", please capitalize Azure.
Under "-DisableEncryptionService", it's "Storage Service Encryption" -- this is a feature -- and you can remove "on the Storage Service". That's redundant. Also, should be "Azure Blob storage and Azure Files are supported." They rarely refer to them as services, and Files was rebranched at Ignite last September.
Under "-EnableEncryptionService", should be "Storage Service Encryption" and remove "on the Storage Service". Also, "Azure Blob storage and Azure Files are supported."
Under "-EnableHttpsTrafficOnly", lowercase storage account, and it should be "enables", not "enable". And HTTPS.
Under "-Force", the link to hot and cool storage is messed up. Also, lowercase storage account in the last sentence. Also, why does this talk about changing the access tier instead of explaining what Force does?
Under "KeyvaultEncryption", lowercase "storage account encryption". Lowercase storage account. And it should be "whether", not "weather".
Under "-NetworkRuleSet", should be "Storage account NetworkRuleSet". Also, this is a terrible description, and doesn't describe what this is.
Under "-StorageEncryption", "storage account encryption".

Last question: what does this mean: System.Nullable`1[System.Boolean] ? I see it in several places, but don't know what it means.

The information for Tag is now formatted but incorrect, and Kind is completely gone. I assume that's not valid for Set-AzureRmStorageAccount?

Thanks,
@robinsh

**Comment by blueww** [comment] 2017-11-14 02:08
It seems the issue is not for command help in src\ResourceManager\Storage\Commands.Management.Storage\help, but for the on-line help in https://docs.microsoft.com/en-us/powershell/module/azurerm.storage/set-azurermstorageaccount, especially for the -Force parameter.

**Comment by markcowl** [comment] 2017-11-14 18:14
@blueww They are the same. The source for cmdlet help and online help is here: https://github.com/Azure/azure-powershell/tree/preview/src/ResourceManager/Storage/Commands.Management.Storage/help

**Comment by blueww** [comment] 2017-11-15 03:10
@markcowl 
I agree some of the error also exist in  *.md file. But actually, some of them only exist in online doc, such as the -Force problem only exist on-online, not exist in help *.md file. The explain for -Force are totally different on the 2 place. So I think the issue is raised from the online doc.

@robinsh 
For the doc issues above, some of them should be changed from the help *.md file. But I am not sure what the text will be, I need you input here. I will start a mail to discuss the issue with you.

**Comment by TaraMeyer** [comment] 2017-12-01 18:23
@robinsh  and @blueww  - what can I do to help move this forward?

**Comment by blueww** [comment] 2017-12-04 02:59
@TaraMeyer, I have send the mail for this issue to you and @robinsh. Please help to answer all the left questions in the mail. And when we get resolution for all the issues in the mail, I will send a PR to fix the content. (Anyway, the content mismatch for the online doc and help file might can't be fixed in source code, and need other attention.)

**Comment by TaraMeyer** [comment] 2017-12-04 21:34
@blueww - I see the -Force param in the related MD which feed directly into the online help:
https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Storage/Commands.Management.Storage/help/Set-AzureRmStorageAccount.md

What else do you need help with?  Are you asking @robinsh to help you write the content she is asking for, or what is the hold up?

**Comment by blueww** [comment] 2017-12-05 01:58
Besides the mismatch of the online help and help file in Powershell repo (for -Force and -Accesstier, I see it's being discussed in the mail thread), there's still another open item: description of -NetworkRuleSet need review. You can see detail in the mail, and @robinsh still not answer it:
 

> @Robin Shahan, besides the question of difference of help file and online help, would you please also help to see my comments for following parameter, and please recommend a better description for it?
> How about: “Specify the NetworkRuleSet which will be set to the Storage account here. See more details of NetworkRuleSet in https://docs.microsoft.com/en-us/azure/storage/common/storage-network-security.” 
> 
> Under "-NetworkRuleSet", should be "Storage account NetworkRuleSet". Also, this is a terrible description, and doesn't describe what this is.
> [Wei] @Robin Shahan What’s the suggest text here? You can get more detail for the feature from https://docs.microsoft.com/en-us/azure/storage/common/storage-network-security 
> Just call it what it is. “List of configuration rules for firewalls and virtual networks for the storage account.” (I’m guessing, is that right?)
> [Wei] Actually, there are some other configuration in it (besides configuration rules for firewalls and virtual networks), like the Bypass, DefaultAction, and they are called NetworkRuleSet as a whole. So I think the current text which only mention the configuration rules might not be accurate.
>

**Comment by blueww** [comment] 2018-01-04 03:42
Fixed most  issues in https://github.com/Azure/azure-powershell/pull/5157 
There are still some left mismatch between online help doc and help file in source coding, which is following with mail. But all change that can be done in source code is done.

**Closed by blueww** 2018-01-04 03:42 UTC
Labels: Storage
