### ISSUE TITLE
Get-AzRecoveryServicesVault Error -> Could not load file or assembly 'Microsoft.Azure.PowerShell.Authentication

### ISSUE THREAD

**Issue by sambitratha** [Azure/azure-powershell#12230] opened 2020-06-22 08:02 UTC
similar to the bug https://github.com/Azure/azure-powershell/issues/8417

This error was mitigated as described in the above thread. But somehow it's again getting populated. We have had a few CRIs for this and also our internal test automation depending on Powershell module are failing. Can anyone please help? Thanks

**Comment by dingmeng-xue** [comment] 2020-06-23 05:34
Thanks for reporting. Please share installed modules via `Get-Module`.

**Comment by EduBoesveld** [comment] 2020-06-24 08:11
We are experiencing the same using the hosted agents on Azure DevOps.
We are using the windows-2019 agents and Azure PowerShell task version 5.* with the Azure Powershell Version set to Latest Installated Version.

Execution is failing on Get-AzRecoveryServicesVault with error:
```
2020-06-24T08:00:34.9179361Z ##[error]Operation failed.
Could not load file or assembly 'Microsoft.Azure.PowerShell.Authentication, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
```


Here is the output of Get-Module:
```2020-06-24T08:09:01.8167831Z ModuleType Version    Name                                ExportedCommands                                             
2020-06-24T08:09:01.8169612Z ---------- -------    ----                                ----------------                                             
2020-06-24T08:09:01.8170445Z Script     1.8.1      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Conn...
2020-06-24T08:09:01.8188926Z Script     2.8.0      Az.RecoveryServices                 {Add-AzRecoveryServicesAsrReplicationProtectedItemDisk, Ba...
2020-06-24T08:09:01.8214052Z Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Con...
2020-06-24T08:09:01.8239746Z Manifest   3.0.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl...
2020-06-24T08:09:01.8248699Z Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}    
2020-06-24T08:09:01.8272852Z Manifest   3.0.0.0    Microsoft.WSMan.Management          {Connect-WSMan, Disable-WSManCredSSP, Disconnect-WSMan, En...
2020-06-24T08:09:01.8357256Z Script     0.0        VstsAzureHelpers_                   {CmdletHasMember, Disconnect-AzureAndClearContext, Initial...
2020-06-24T08:09:01.8366829Z Script     0.11.0     VstsTaskSdk                         {Assert-VstsAgent, Assert-VstsPath, Find-VstsFiles, Find-V...```

**Comment by jaydubya1** [comment] 2020-06-29 08:11
I'm encountering this issue locally **and** through Azure Pipelines with the same error message - below error with Resolve-AzError -Last output

Get-AzRecoveryServicesVault : Operation failed.
Could not load file or assembly 'Microsoft.Azure.PowerShell.Authentication, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
At line:43 char:10
+ $vault = Get-AzRecoveryServicesVault -ResourceGroupName $ResourceGrou ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzRecoveryServicesVault], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.RecoveryServices.GetAzureRmRecoveryServicesVaults

**Resolve-AzError -Last returns the below**

Message        : Operation failed.
                 Could not load file or assembly 'Microsoft.Azure.PowerShell.Authentication, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file 
                 specified.
StackTrace     :    at Microsoft.Azure.Commands.RecoveryServices.RecoveryServicesCmdletBase.HandleException(Exception ex)
                    at Microsoft.Azure.Commands.RecoveryServices.GetAzureRmRecoveryServicesVaults.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Exception
InvocationInfo : {Get-AzRecoveryServicesVault}
Line           : $vault = Get-AzRecoveryServicesVault -ResourceGroupName $ResourceGroupName -Name $VaultName
                 
Position       : At line:43 char:10
                 + $vault = Get-AzRecoveryServicesVault -ResourceGroupName $ResourceGrou ...
                 +          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 12

Message        : Could not load file or assembly 'Microsoft.Azure.PowerShell.Authentication, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file 
                 specified.
StackTrace     :    at Microsoft.Azure.Commands.RecoveryServices.PSRecoveryServicesClient..ctor(IAzureContext defaultContext)
                    at Microsoft.Azure.Commands.RecoveryServices.RecoveryServicesCmdletBase.get_RecoveryServicesClient()
                    at Microsoft.Azure.Commands.RecoveryServices.GetAzureRmRecoveryServicesVaults.ExecuteCmdlet()
Exception      : System.IO.FileNotFoundException
InvocationInfo : {Get-AzRecoveryServicesVault}
Line           : $vault = Get-AzRecoveryServicesVault -ResourceGroupName $ResourceGroupName -Name $VaultName
                 
Position       : At line:43 char:10
                 + $vault = Get-AzRecoveryServicesVault -ResourceGroupName $ResourceGrou ...
                 +          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 12

**Comment by dingmeng-xue** [comment] 2020-06-29 10:08
@sambitratha , @EduBoesveld , @jaydubya1 , please execute below script in issue environment after you see the problem. It can show loaded assemblies with its location.
```
[System.AppDomain]::CurrentDomain.GetAssemblies() | ForEach-object { if($_.location -like "*Authentication*") {write-host $_.location}}
```

**Comment by sambitratha** [comment] 2020-06-30 10:25
hi @dingmeng-xue 
C:\Modules\az_1.6.0\Az.Accounts\1.8.1\Microsoft.Azure.PowerShell.Authentication.Abstractions.dll C:\Modules\az_1.6.0\Az.Accounts\1.8.1\Microsoft.Azure.PowerShell.Authentication.dll
C:\Modules\az_1.6.0\Az.Accounts\1.8.1\Microsoft.Azure.PowerShell.Authentication.ResourceManager.dll

This is the output that i get when i run the command shared by you .
My understanding is that authentication assembly version was changed and because recoveryservice module has a dependency cmdlets are breaking. 
Can we please add someone from accounts module to look into it?

**Comment by dingmeng-xue** [comment] 2020-06-30 10:59
We need to know which assembly blocks the loading of Authentication.dll. Below is my result on PowerShell Core and PowerShell 7.
```
PS C:\Users\dixue> Import-Module Az.Accounts
PS C:\Users\dixue> Import-Module Az.RecoveryServices
PS C:\Users\dixue> Get-Module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.8.1      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connec…
Script     2.8.0      Az.RecoveryServices                 {Add-AzRecoveryServicesAsrReplicationProtectedItemDisk, Back…
Manifest   6.1.0.0    Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemProperty…}
Manifest   6.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object…}
Script     2.0.0      PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSRe…

```

**Comment by jaydubya1** [comment] 2020-07-01 10:16
running [System.AppDomain]::CurrentDomain.GetAssemblies() | ForEach-object { if($_.location -like "*Authentication*") {write-host $_.location}} i get the below (error persists)

PS H:\> [System.AppDomain]::CurrentDomain.GetAssemblies() | ForEach-object { if($_.location -like "*Authentication*") {write-host $_.location}}
C:\Users\jonw\Documents\WindowsPowerShell\Modules\Az.Accounts\1.9.0\Microsoft.Azure.PowerShell.Authentication.Abstractions.dll
C:\Users\jonw\Documents\WindowsPowerShell\Modules\Az.Accounts\1.9.0\Microsoft.Azure.PowerShell.Authentication.dll
C:\Users\jonw\Documents\WindowsPowerShell\Modules\Az.Accounts\1.9.0\Microsoft.Azure.PowerShell.Authentication.ResourceManager.dll

**Comment by jaydubya1** [comment] 2020-07-01 10:18
running the commands below returns results, as @dingmeng-xue stated this executes without error - but i wouldnt expect an error here. The error still only occurs when running the command Get-AzRecoveryServicesVault

Import-Module Az.Accounts
Import-Module Az.RecoveryServices
Get-Module

ModuleType Version    Name                                ExportedCommands                                                                                                                                                                                       
---------- -------    ----                                ----------------                                                                                                                                                                                       
Script     1.9.0      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount...}                                                                                                                            
Script     2.7.0      Az.RecoveryServices                 {Add-AzRecoveryServicesAsrReplicationProtectedItemDisk, Backup-AzRecoveryServicesBackupItem, Disable-AzRecoveryServicesBackupAutoProtection, Disable-AzRecoveryServicesBackupProtection...}            
Script     2.3.0      Az.Sql                              {Add-AzSqlDatabaseToFailoverGroup, Add-AzSqlElasticJobStep, Add-AzSqlElasticJobTarget, Add-AzSqlInstanceKeyVaultKey...}                                                                                
Script     1.12.0     Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAccountNetworkRule, Close-AzStorageFileHandle...}                                                         
Script     1.0.0.0    ISE                                 {Get-IseSnippet, Import-IseSnippet, New-IseSnippet}                                                                                                                                                    
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}                                                                                                                                     
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl, Get-AuthenticodeSignature...}                                                                                                              
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}                                                                                                                                              
Manifest   3.0.0.0    Microsoft.WSMan.Management          {Connect-WSMan, Disable-WSManCredSSP, Disconnect-WSMan, Enable-WSManCredSSP...}

**Comment by dingmeng-xue** [comment] 2020-07-01 10:51
@jaydubya1 , for your case, you need to upgrade Az.RecoveryServices to 2.10.0 which released with Az.Accounts 1.9.0 together.

**Comment by yogaanand0** [comment] 2020-07-01 12:38
i am getting same error , while running in azure powershell pipeline 

"C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\9863e853-c199-456c-9822-fa4523e0bf9f.ps1'"
Import-Module -Name C:\Modules\az_3.8.0\Az.Accounts\1.8.1\Az.Accounts.psd1 -Global

**Comment by dingmeng-xue** [comment] 2020-07-01 12:45
What's the error message? That's the version of your modules? @yogaanand0

**Comment by yogaanand0** [comment] 2020-07-01 14:10
Error Msg : 
Could not load file or assembly 'Microsoft.Azure.PowerShell.Authentication, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

Import-Module -Name C:\Modules\az_3.8.0\Az.Accounts\1.8.1\Az.Accounts.psd1 -Global -- this is module is loading when running the powershell agent in azure devops pipeline

**Comment by dingmeng-xue** [comment] 2020-07-01 14:18
> Error Msg :
> Could not load file or assembly 'Microsoft.Azure.PowerShell.Authentication, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
> 
> Import-Module -Name C:\Modules\az_3.8.0\Az.Accounts\1.8.1\Az.Accounts.psd1 -Global -- this is module is loading when running the powershell agent in azure devops pipeline

Did you find that issue during Import Az.RecoveryServices? If not, please create a new issue. This thread is just focusing on assembly conflicts between Az.RecoveryServices and Az.Accounts.

**Comment by yogaanand0** [comment] 2020-07-01 14:20
> > Error Msg :
> > Could not load file or assembly 'Microsoft.Azure.PowerShell.Authentication, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
> > Import-Module -Name C:\Modules\az_3.8.0\Az.Accounts\1.8.1\Az.Accounts.psd1 -Global -- this is module is loading when running the powershell agent in azure devops pipeline
> 
> Did you find that issue during Import Az.RecoveryServices? If not, please create a new issue. This thread is just focusing on assembly conflicts between Az.RecoveryServices and Az.Accounts.

yes this for AZ.Recoverysedrvices @dingmeng-xue

**Comment by dingmeng-xue** [comment] 2020-07-01 14:28
I didn't quit understand your case. When did this error show up? before importing Az.Accounts or importing Az.RecoveryServices? Could you explain your case in detail? In addition, you may need to remove AzureRM modules before importing Az.Accounts because AzureRM is pre-loaded in your task.

**Comment by yogaanand0** [comment] 2020-07-01 15:20
I am getting this error after module loads when i am running below script in pipeline 

Get-AzRecoveryServicesVault -ResourceGroupName "xxx" -Name "xxx"

**Comment by jaydubya1** [comment] 2020-07-01 18:24
the error is generated when calling Get-AzRecoveryServicesVault - we use this in a step within a release pipeline, so it was previously working but now is generating the error as described previously.

I ran the command Uninstall-AzureRM and then Get-Module shows as below - running $vault = Get-AzRecoveryServicesVault -ResourceGroupName $ResourceGroupName -Name $VaultName still generates the error "Get-AzRecoveryServicesVault : Operation failed.
Could not load file or assembly 'Microsoft.Azure.PowerShell.Authentication, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified."

ModuleType Version    Name                                ExportedCommands                                                                                                                                                                                       
---------- -------    ----                                ----------------                                                                                                                                                                                       
Script     1.9.0      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount...}                                                                                                                            
Script     2.7.0      Az.RecoveryServices                 {Add-AzRecoveryServicesAsrReplicationProtectedItemDisk, Backup-AzRecoveryServicesBackupItem, Disable-AzRecoveryServicesBackupAutoProtection, Disable-AzRecoveryServicesBackupProtection...}            
Script     1.0.0.0    ISE                                 {Get-IseSnippet, Import-IseSnippet, New-IseSnippet}                                                                                                                                                    
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}                                                                                                                                     
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl, Get-AuthenticodeSignature...}                                                                                                              
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}                                                                                                                                              
Manifest   3.0.0.0    Microsoft.WSMan.Management          {Connect-WSMan, Disable-WSManCredSSP, Disconnect-WSMan, Enable-WSManCredSSP...}                                                                                                                        
Binary     1.0.0.1    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-PackageProvider...}                                                                                                                              
Script     1.0.0.1    PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCapability...}

**Comment by jaydubya1** [comment] 2020-07-02 07:18
trying the command below (as shown through https://docs.microsoft.com/en-us/azure/backup/backup-azure-vms-automation) also reproduces the same error message 
New-AzRecoveryServicesVault -Name "testvault" -ResourceGroupName "rsv-rg" -Location "West Europe"

**Comment by dingmeng-xue** [comment] 2020-07-02 07:29
@jaydubya1 , I can reproduce your issue and see the same error during calling `Get-AzRecoveryServicesVault`. According to your log, Az.Accounts is upgraded to 1.9.0 but Az.RecoveryServices is old one 2.7.0. So, solution as I mentioned is either downgrade Az.Accounts or upgrade Az.RecoveryServices. One verified combination is Az.RecoveryServices 2.10.0 and Az.Accounts 1.9.0.

**Comment by jaydubya1** [comment] 2020-07-02 15:46
to get this working locally i used the below two lines of code, although this doesnt work in the Azure Devops Release Pipelines. I changed the syntax of the powershell in the release pipeline to use AzureRM and the script worked fine so i'm leaving the release pipeline code in this state, so i'm now using Get-AzureRMRecoveryServicesVault which is working fine.

Install-Module -Name Az.RecoveryServices -RequiredVersion 2.10.0 -Force -Scope CurrentUser
Install-Module -Name Az.Accounts -RequiredVersion 1.9.0 -Force -Scope CurrentUser

**Comment by dingmeng-xue** [comment] 2020-07-03 02:57
Thanks @jaydubya1 , we have found the root cause. It is because RecoveryServices module depends on Microsoft.Azure.PowerShell.Authentication, but it should be avoided. We will correct RecoveryServices in upcoming new release.

**Comment by glennsarti** [comment] 2020-07-03 03:39
Hi @dingmeng-xue we got hit by this as well in Azure DevOps.  I don't suppose you have an idea of when the new release is due?

Ping @adzman

**Comment by dingmeng-xue** [comment] 2020-07-03 04:49
I believe user meet this issue just due to module is upgraded. If module can be upgraded in DevOps, the short term solution is to upgraded Az.RecoveryServices to 2.10.0 in DevOps. The next Az.RecoveryServices release will fix it completely. 

 You are right, we have no idea how to force Azure DevOps to upgrade version and when release the new version. Let me figure it out.

**Closed** 2020-07-06 05:57 UTC
Labels: More Info :label:, Recovery Services

**Comment by DanielFrei64** [comment] 2020-07-15 00:31
This has reared itself yet again with the latest update. My pipelines are failing again. Upgrading Az.RecoveryServices to the latest( 2.11.0 ) does not fix it like it has the last two times. Any insight as to what we can to do fix this permanently?

**Comment by dingmeng-xue** [comment] 2020-07-15 04:03
@DanielFrei64 , assembly issue is complex in dotnet. Could you create a new Github issue and provide us your environment, loaded modules and issue scripts? We'd like to track each one respectively. If they are really duplicated, we can link them together.

**Comment by shaisundar** [comment] 2020-07-20 08:21
@dingmeng-xue -
Currently, things are working on VS2017-win2016 MS HOsted image. But failing on win 2019 MS Hosted Image.

We just checked the logs in win2019 image and this is what we found - 

[command]Import-Module -Name C:\Modules\az_4.3.0\Az.Accounts\1.9.1\Az.Accounts.psd1 -Global

 ##[error]Operation failed.
Could not load file or assembly 'Microsoft.Azure.PowerShell.Authentication, Version=1.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

Its failing although it has a later Az.Accounts module,
We suspect Its failing because its somehow trying to look for Microsoft.Azure.PowerShell.Authentication, Version=1.9.0.0.


So we suspect that this issue will resurface even on win 2016 after the next update.

**Comment by dingmeng-xue** [comment] 2020-07-20 09:31
@shaisundar, sorry for the inconvenience. Could you create a new issue? Let's use it for tracking. In the new issue, please list modules using `Get-Module Az*` and `Get-Module Az* -ListAvailable`.
