### ISSUE TITLE
[Storage] Access to Azure Storage Table using AzureAD auth not working

### ISSUE THREAD

**Issue by bernharddick** [Azure/azure-powershell#16861] opened 2022-01-18 15:02 UTC
### Description

Access to an Azure Table in AzureAD access mode with a user that is only allowed to do operations on Table Storage is not possible as the module tries to get a Storage Shared Access Key where the user does not have permission to.

### Issue script & Debug output

```PowerShell
Get-AzStorageTable -Context $storageAccount.Context
DEBUG: 15:55:39 - Init Operation Context for 'GetAzureStorageTableCommand' with client request id  Azure-Storage-PowerShell-UUID. If you want to get more details, please add "-Debug" to your command.
DEBUG: 15:55:39 - GetAzureStorageTableCommand begin processing with ParameterSet 'TableName'.
Get-AzStorageTable: The client 'USER@DOMAIN' with object id 'UUID' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' over scope '/subscriptions/UUID/resourceGroups/RG_NAME/providers/Microsoft.Storage/storageAccounts/STORAGENAME' or the scope is invalid. If access was recently granted, please refresh your credentials.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.0.7
PSEdition                      Core
GitCommitId                    7.0.7
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.7.1                 az.accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     4.1.1                 az.storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAccountNetworkRule, Close…
```

### Error output

```PowerShell
DEBUG: 15:57:48 - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 15:57:48 - using account id 'USER@DOMAIN'...
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.


   HistoryId: 10

RequestId      : 4e4d935d-ea8a-47d0-ba3f-a0ce0916726a
Message        : The client 'USER@DOMAIN' with object id 'UUID' does not have authorization to perform action
                 'Microsoft.Storage/storageAccounts/listKeys/action' over scope
                 '/subscriptions/UUID/resourceGroups/RG_NAME/providers/Microsoft.Storage/storageAccounts/STORAGENAME' or the scope is  
                 invalid. If access was recently granted, please refresh your credentials.
ServerMessage  : AuthorizationFailed: The client 'USER@DOMAIN' with object id 'UUID' does not have authorization to perform action
                 'Microsoft.Storage/storageAccounts/listKeys/action' over scope
                 '/subscriptions/UUID/resourceGroups/RG_NAME/providers/Microsoft.Storage/storageAccounts/STORAGENAME' or the scope is  
                 invalid. If access was recently granted, please refresh your credentials. (System.Collections.Generic.List`1[Microsoft.Rest.Azure.CloudError])
ServerResponse : {Forbidden}
RequestMessage : {POST https://management.azure.com/subscriptions/UUID/resourceGroups/RG_NAME/providers/Microsoft.Storage/storageAccounts/STORAGENAME/listKeys?api-version=2021-06-01}
InvocationInfo : {Get-AzStorageTable}
Line           : Get-AzStorageTable -Context $storageAccount.Context
Position       : At line:1 char:1
                 + Get-AzStorageTable -Context $storageAccount.Context
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Management.Storage.StorageAccountsOperations.ListKeysWithHttpMessagesAsync(String resourceGroupName, String accountName, Nullable`1 expand,
                 Dictionary`2 customHeaders, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.Storage.StorageAccountsOperationsExtensions.ListKeysAsync(IStorageAccountsOperations operations, String resourceGroupName, String
                 accountName, Nullable`1 expand, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.Storage.StorageAccountsOperationsExtensions.ListKeys(IStorageAccountsOperations operations, String resourceGroupName, String accountName,  
                 Nullable`1 expand)
                    at Microsoft.Azure.Commands.Management.Storage.Models.ARMStorageProvider.GetStorageService(String name, String resourceGroupName)
                    at Microsoft.WindowsAzure.Commands.Storage.Adapters.AzureContextAdapterExtensions.GetCloudStorageAccount(IStorageServiceProvider provider, String accountName, String    
                 resourceGroupName)
                    at Microsoft.Azure.Commands.Management.Storage.Models.PSStorageAccount.<>c__DisplayClass159_0.<Create>b__0(String s)
                    at Microsoft.WindowsAzure.Commands.Common.Storage.LazyAzureStorageContext.get_StorageAccount()
                    at Microsoft.WindowsAzure.Commands.Common.Storage.AzureStorageContext.get_ConnectionString()
                    at Microsoft.WindowsAzure.Commands.Storage.Adapters.AzureContextAdapterExtensions.GetCloudStorageAccount(IStorageContext context)
                    at Microsoft.WindowsAzure.Commands.Storage.Common.StorageCloudCmdletBase`1.GetCmdletStorageContext(IStorageContext inContext)
                    at Microsoft.WindowsAzure.Commands.Storage.Common.StorageCloudCmdletBase`1.GetCmdletStorageContext()
                    at Microsoft.WindowsAzure.Commands.Storage.Table.StorageCloudTableCmdletBase.CreateChannel()
                    at Microsoft.WindowsAzure.Commands.Storage.Common.StorageCloudCmdletBase`1.InitChannelCurrentSubscription(Boolean force)
                    at Microsoft.WindowsAzure.Commands.Storage.Common.StorageCloudCmdletBase`1.InitChannelCurrentSubscription()
                    at Microsoft.WindowsAzure.Commands.Storage.Common.StorageCloudCmdletBase`1.ProcessRecord()
                    at System.Management.Automation.Cmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
HistoryId      : 10


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.

DEBUG: AzureQoSEvent: Module: az.accounts:2.7.1; CommandName: Resolve-AzError; PSVersion: 7.0.7; IsSuccess: True; Duration: 00:00:00.0590510
DEBUG: Finish sending metric.
DEBUG: 15:57:49 - ResolveError end processing.
```

**Comment by blueww** [comment] 2022-01-19 02:04
@bernharddick 

The correct way to create oauth storage context and use it in table is:
```powershell
Connect-AzAccount
$ctx = New-AzStorageContext -StorageAccountName $accountName -UseConnectedAccount
Get-AzStorageTable -Context $ctx
```

For the above script you use, it looks you just get storage context from the storage account object, this will by default create a storage account with account key credential.

**Comment by bernharddick** [comment] 2022-01-19 12:42
Thanks, with that Context I'm able to get an Table Object. However it cannot be used to return any values. Digging deeper leeds to all requests ending up with an HTTP404-Response:
```
>$table.CloudTable.Execute([Microsoft.Azure.Cosmos.Table.TableOperation]::Retrieve($partitionKey, $rowKey))

Result         :    
HttpStatusCode : 404
Etag           :    
SessionToken   :    
RequestCharge  :    
ActivityId     :
```
It seems that it is now using Anonymous access for the table content:
```
>$table.CloudTable.ServiceClient.Credentials

SASToken     :
AccountName  :
Key          :
KeyName      :
IsSharedKey  : False
IsAnonymous  : True
IsSAS        : False
SASSignature :
```

**Comment by blueww** [comment] 2022-01-20 02:39
@bernharddick

CloudTable is from old SDK (leave it to avoid breaking),  the old SDK doesn't support oauth.
So please use the `$table.TableClient` insead.
Please note,  `$table.TableClient` is from new SDK, and it has different API design from old SDK. Please refer to [doc ](https://docs.microsoft.com/en-us/dotnet/api/azure.data.tables.tableclient?view=azure-dotnet)for TableClient API.

@PaulCheng 
Do you have any comments for it?

**Comment by navba-MSFT** [comment] 2022-02-02 09:36
@bernharddick Did you get a chance to follow the action plan suggested by @blueww ? Please let us know if you face any issues. Awaiting your reply.

**Comment by blueww** [comment] 2022-03-10 04:16
@PaulCheng
Would you please help to look how to use oauth to query table entities in PSH?

**Comment by PaulCheng** [comment] 2022-03-11 05:33
Most of the TableClient methods are Generic, so you'll need to write a bit more code.
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/src/TableClient.cs

In addition, you will need to implement a small .net standard library defining your derived ITableEntity class.
In this lib, reference azure.data.tables sdk 12.2.0 to match current version az.storage module references.

**Sample Entity c# class:**
namespace DotNetStandardLibrary
{
    public class SmallEntity : ITableEntity
    {
        public SmallEntity()
        {
        }

        public string PartitionKey { get; set; }
        public string RowKey { get; set; }
        public DateTimeOffset? Timestamp { get; set; }
        public ETag ETag { get; set; }

        public int IntCol { get; set; }
    }
}

**Sample PS Script**
$token = [System.Threading.CancellationToken]::None

Add-Type -AssemblyName "... ...\DotNetStandardLibrary.dll" -PassThru
$entity = New-Object -TypeName DotNetStandardLibrary.SmallEntity
$entity.PartitionKey = "pkey"
$entity.RowKey = "rkey"
$entity.IntCol = 1

// insert
$methodAddEntity = [Azure.Data.Tables.TableClient].GetMethods() | Where-Object Name -eq "AddEntity"
$methodAddEntity = $methodAddEntity.MakeGenericMethod([DotNetStandardLibrary.SmallEntity])
$methodAddEntity.Invoke($table.TableClient, @([DotNetStandardLibrary.SmallEntity]$entity, $token))

// retrieve
$methodGetEntity = [Azure.Data.Tables.TableClient].GetMethods() | Where-Object Name -eq "GetEntity"
$methodGetEntity = $methodGetEntity.MakeGenericMethod([DotNetStandardLibrary.SmallEntity])
$entity = $methodGetEntity.Invoke($table.TableClient, @($entity.PartitionKey, $entity.RowKey, $null, $token)).Value

// delete
$table.TableClient.DeleteEntity($entity.PartitionKey, $entity.RowKey, $entity.ETag, $token)

**Comment by obesser** [comment] 2023-03-13 15:39
@bernharddick Did you find a solution for this?
I get the same `System.BinaryData` not found error with the AddEntity method.

@PaulCheng Perhaps you can shed some light on it? I tried Add-Type with the System.Memory.Data.dll, it added the `System.BinaryData` type but I still get the above error.

**Comment by obesser** [comment] 2023-03-13 21:26
Adding 'System.Memory.Data.dll' to the module directory and RequiredAssemblies of Az.Accounts or Az.Storage solves it.
The dll exists in the `Az.Accounts\lib\netstandard2.0` directory, any reason why it isn't loaded by default?

**Comment by blueww** [comment] 2023-03-14 07:48
@isra-fel 

Would you please help to look at this issue? 
It looks related with assembly loading.

I can repro it on PowerShell 7.2.9, but can't repro it in PowerShell 5.1.0.

**Comment by isra-fel** [comment] 2023-03-29 09:28
> Adding 'System.Memory.Data.dll' to the module directory and RequiredAssemblies of Az.Accounts or Az.Storage solves it.
The dll exists in the Az.Accounts\lib\netstandard2.0 directory, any reason why it isn't loaded by default?

It would solve this problem yes but it would cause potential assembly conflict between storage and other modules that use another version of the dll. That's why we imoplemented the AssemblyLoadContext (ALC) solution to isolate the dependency.

The cause of the error is the same as https://github.com/Azure/azure-powershell/issues/21134 which is that PS isn't aware of the assemblies loaded into a custoemr ALC. So even if we load the assembly the script still fails.

Unlike 21134 there is no clear work around because the type isn't used directly in the script. There might be a chance of other ways to call the AddEntity method without referencing the MemoryData type, or explicitly using it.

**Comment by yifanz7** [comment] 2023-08-29 07:24
Closing as resolved

**Closed by yifanz7** 2023-08-29 07:24 UTC
Labels: Storage, Service Attention, bug, question, customer-reported, needs-team-attention

**Comment by sowhat110** [comment] 2024-06-07 22:10
In case anyone still looking how to use TableClient with Powershell
```powershell
# Create TableClient
$ctx = New-AzStorageContext -StorageAccountName "storageaccountname1" -UseConnectedAccount
$table = Get-AzStorageTable -Name "sampletable1" -Context $ctx        
$tableClient = $table.TableClient

# Create table entity
$tableRow = [Azure.Data.Tables.TableEntity]::new("partitionkey1", "rowkey1")
$tableRow.Add("prop1", "propValue1")

# Insert entity into table
$tableClient.AddEntity($tableRow, $null)

# Upsert entity
$tableRow.Add("prop2", "propValue2")
$tableClient.UpsertEntity($tableRow, 1, $null) # 0 = merge, 1 = replace

# Get entity
$table.GetEntity[Azure.Data.Tables.TableEntity]("partition1", "rowkey1").Value

# Query entities
$tableClient.Query[Azure.Data.Tables.TableEntity]("PartitionKey eq 'partition1'")

# Get all entities
$tableClient.Query[Azure.Data.Tables.TableEntity]()
```

**Comment by TheOnlyWei** [comment] 2024-08-03 04:30
@blueww Is there an updated method? This doesn't work on PowerShell 7.4.4. I get this error:

Code
```
$method = [Azure.Data.Tables.TableClient].GetMethods() | Where-Object Name -eq "UpsertEntity"
$method = $method.MakeGenericMethod([Azure.Data.Tables.TableEntity])
$method.Invoke($storageTable.TableClient, @($tableRow, [Azure.Data.Tables.TableUpdateMode]::Merge, $null))
```

Error
```
System.Management.Automation.MethodInvocationException: Exception calling "Invoke" with "2" argument(s): "DateTime 1/1/1970 12:00:00 AM has a Kind of Unspecified. Azure SDK requires it to be UTC. You can call DateTime.SpecifyKind to change Kind property value to DateTimeKind.Utc." ---> System.NotSupportedException: DateTime 1/1/1970 12:00:00 AM has a Kind of Unspecified. Azure SDK requires it to be UTC. You can call DateTime.SpecifyKind to change Kind property value to DateTimeKind.Utc.
   at Azure.Core.TypeFormatters.ToString(DateTime value, String format)
   at Azure.Core.Utf8JsonWriterExtensions.WriteObjectValue(Utf8JsonWriter writer, Object value)
   at Azure.Data.Tables.TableRestClient.CreateMergeEntityRequest(String table, String partitionKey, String rowKey, Nullable`1 timeout, String ifMatch, IDictionary`2 tableEntityProperties, QueryOptions queryOptions)
   at Azure.Data.Tables.TableRestClient.MergeEntity(String table, String partitionKey, String rowKey, Nullable`1 timeout, String ifMatch, IDictionary`2 tableEntityProperties, QueryOptions queryOptions, CancellationToken cancellationToken)
   at Azure.Data.Tables.TableClient.UpsertEntity[T](T entity, TableUpdateMode mode, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at lambda_method(Closure , Object[] , StrongBox`1[] , InterpretedFrame )
```

**Comment by TheOnlyWei** [comment] 2024-08-03 05:35
@sowhat110 How did you get `$tableClient.UpsertEntity($tableRow, 1, $null)` to work? I get this error:
```
$storageTable.TableClient.UpsertEntity($tableRow, [Azure.Data.Tables.TableUpdateMode]::Merge, $null)
MethodException: Cannot find an overload for "UpsertEntity" and the argument count: "3".
```

Had to use what @blueww provided:
```
$method = [Azure.Data.Tables.TableClient].GetMethods() | Where-Object Name -eq "UpsertEntity"
$method = $method.MakeGenericMethod([Azure.Data.Tables.TableEntity])
$method.Invoke($storageTable.TableClient, @($tableRow, [Azure.Data.Tables.TableUpdateMode]::Merge, $null)
```

**Comment by sowhat110** [comment] 2024-08-03 09:21
@TheOnlyWei Try replacing $null with [System.Threading.CancellationToken]::new($false) or simply $false

**Comment by yifanz7** [comment] 2024-09-09 06:17
We just got a customer reported issue again on this. The issue is 

> When i use the Get-AzTableRow -table $cloudTable | ft command i am unable to fetch the values.
But if you use list the table by using the command-  Get-AzStorageTable -Context $ctx | select Name

The root cause was the customer used OAuth context when getting the table object, and OAuth is not supported by Get-AzTableRow.
