### ISSUE TITLE
Get-AzFrontDoor does not return Azure Front Doors with Premium SKU

### ISSUE THREAD

**Issue by illgitthat** [Azure/azure-powershell#17864] opened 2022-04-20 16:59 UTC
### Description

I ran `Get-AzFrontDoor` with no parameters and expected to have a list of front doors available in the subscription. Instead, nothing was returned.

This is reproducible and the desired output is to return the front door.

### Issue script & Debug output

```PowerShell
PS > Get-AzFrontDoor
PS >
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.2.5                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     1.6.0                 Az.Cdn                              {Confirm-AzCdnEndpointProbeURL, Disable-AzCdnCustomDomain, Disable-AzCdnCustomDomainHt… 
Script     1.7.0                 Az.FrontDoor                        {Disable-AzFrontDoorCustomDomainHttps, Enable-AzFrontDoorCustomDomainHttps, Get-AzFron…
```

**Comment by illgitthat** [comment] 2022-04-20 17:09
After posting this, I updated to v1.9 (latest) and the issue persists.

**Comment by SaurabhSharma-MSFT** [comment] 2022-04-20 18:53
@illgitthat We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment] 2022-04-20 21:25
@illgitthat I could see the same behavior and it looks like this cmdlet is only displaying front doors with **Azure Front Door Classic** tier.  I am checking internally and get back to you.  

Thanks
Saurabh

**Comment by SaurabhSharma-MSFT** [comment] 2022-04-21 16:19
@illgitthat As per internal conversation with the products team this is intended behavior of this cmdlet.  PowerShell for AFD Standard and Premium beta version will be released early next week, the stable version will come along in May.  You can try using the latest version of [AFD Profiles - REST API (Azure Front Door Service)](https://docs.microsoft.com/en-us/rest/api/frontdoor/azurefrontdoorstandardpremium/afd-profiles/get) to get a standard or premium version resources.

Thanks
Saurabh

**Comment by SaurabhSharma-MSFT** [comment] 2022-04-22 18:42
@illgitthat Please let me know if you have any questions, else we will proceed with the closure of this issue.

**Comment by illgitthat** [comment] 2022-04-25 03:20
> PowerShell for AFD Standard and Premium beta version will be released early next week and the stable version will come along in May

Thank you for the update! My recommendation would be an update to [the documentation](https://docs.microsoft.com/en-us/powershell/module/az.frontdoor/get-azfrontdoor?view=azps-7.4.0) with this information. Currently, it is confusing since the page does not specify that the module only supports classic tier.

**Closed** 2022-05-12 13:54 UTC
Labels: bug, customer-reported, CXP Attention

**Comment by SaurabhSharma-MSFT** [comment] 2022-05-12 13:58
@illgitthat I have created a pull request to update the documentation which will be merged once approved by the products team.
We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

Thanks
Saurabh

**Comment by Curtmcgirt** [comment] 2023-03-27 20:09
the "merged" "fix" https://github.com/Azure/azure-powershell/pull/18135 doesn't seem to say anything about the 'get-azfrontdoor' cmdlet. i have version 1.10.0 of the az.frontdoor module installed (currently 19days old) and "get-azfrontdoor" still doesn't return anything, and get-help still says "i only care about classic frontdoors"

**Comment by RyanMesser** [comment] 2023-10-13 19:43
I have the same issue. Get-AzFrontDoor doesn't return anything for me.

I have script that use to work off this module and now won't work as they can't find any of the AFD instances we have.

**Comment by t-bzhan** [comment] 2023-11-21 05:28
Hi @RyanMesser , Get-AzFrontDoor under [Az.FrontDoor](https://learn.microsoft.com/en-us/powershell/module/az.frontdoor/?view=azps-10.4.1) is only for Azure Front Door classical Tier, For Azure Front Door Standard/Premium SKU, please use https://learn.microsoft.com/en-us/powershell/module/az.cdn/get-azfrontdoorcdnprofile?view=azps-11.0.0
