### ISSUE TITLE
Set-AzureStorageBlobContent" The remote server returned an error: (409) Conflict. HTTP Status Code: 409 - HTTP Error Message: This operation is not permitted as the blob is immutable due to a policy.

### ISSUE THREAD

**Issue by abatishchev** [Azure/azure-powershell#9195] opened 2019-05-14 00:52 UTC
## Description

Executing the following commands used to work fine just few weeks ago:

```powershell
$containerName = "$Usage-$Stamp-$azureRegionAbbreviation-$Environment-$dt".ToLowerInvariant()
New-AzureRmStorageContainer `
        -ContainerName $containerName `
        -StorageAccount $storageAccount `
        -PublicAccess Container `
        -Verbose

Set-AzureRmStorageContainerImmutabilityPolicy `
        -ResourceGroupName $resourceGroupName `
        -StorageAccountName $storageAccountName `
        -ContainerName $containerName `
        -ImmutabilityPeriod 3 `
        -ErrorAction Continue `
        -Verbose

Set-AzureStorageBlobContent `
        -File $file `
        -Blob $blob `
        -Container $containerName `
        -Context $storageAccount.Context `
        -Force
```

And now it always fails with this error:

>Set-AzureStorageBlobContent : The remote server returned an error: (409) Conflict. HTTP Status Code: 409 - HTTP Error Message: This operation is not
permitted as the blob is immutable due to a policy.

## Steps to reproduce

```powershell

```

## Module versions

```powershell
ModuleType Version    Name                                ExportedCommands            
---------- -------    ----                                ----------------            
Script     5.8.2      AzureRM.profile
Script     6.7.3      AzureRM.Resources
Script     5.2.0      AzureRM.Storage
Script     4.6.1      Azure.Storage
```

## Debug output

```
DEBUG: 17:51:41 - Init Operation Context for 'SetAzureBlobContentCommand' with client request id
Azure-Storage-PowerShell-ee76c923-2482-4007-be43-13df225be153. If you want to get more details, please add "-Debug" to your command.
DEBUG: 17:51:41 - SetAzureBlobContentCommand begin processing with ParameterSet 'SendManual'.
DEBUG: 17:51:41 - Use storage account 'xxx' from storage context.
DEBUG: 17:51:41 - SetAzureBlobContentCommand end processing, Start 212 remote calls. Finish 212 remote calls. Elapsed time 618285596.19 ms. Client operation
id: Azure-Storage-PowerShell-ee76c923-2482-4007-be43-13df225be153.
DEBUG: 17:51:41 - SetAzureBlobContentCommand end processing.
DEBUG: 17:51:41 - Init Operation Context for 'SetAzureBlobContentCommand' with client request id
Azure-Storage-PowerShell-ee76c923-2482-4007-be43-13df225be153. If you want to get more details, please add "-Debug" to your command.
DEBUG: 17:51:41 - SetAzureBlobContentCommand begin processing with ParameterSet 'SendManual'.
DEBUG: 17:51:41 - Use storage account 'xxx' from storage context.
Set-AzureStorageBlobContent : The remote server returned an error: (409) Conflict. HTTP Status Code: 409 - HTTP Error Message: This operation is not
permitted as the blob is immutable due to a policy.
At \src\resources\scripts\New-DataCenter.ps1:164 char:2
+     Set-AzureStorageBlobContent -File $file `
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureStorageBlobContent], StorageException
    + FullyQualifiedErrorId : StorageException,Microsoft.WindowsAzure.Commands.Storage.Blob.SetAzureBlobContentCommand

DEBUG: 17:51:41 - SetAzureBlobContentCommand end processing, Start 212 remote calls. Finish 212 remote calls. Elapsed time 618285661.16 ms. Client operation
id: Azure-Storage-PowerShell-ee76c923-2482-4007-be43-13df225be153.
DEBUG: 17:51:41 - SetAzureBlobContentCommand end processing.
```

## Error output

```
Message        : The remote server returned an error: (409) Conflict. HTTP Status Code: 409 - HTTP Error Message: This operation is not permitted as the
                 blob is immutable due to a policy.
StackTrace     :
Exception      : Microsoft.WindowsAzure.Storage.StorageException
InvocationInfo : {Set-AzureStorageBlobContent}
Line           :        Set-AzureStorageBlobContent -File $file `

Position       : At src\resources\scripts\New-DataCenter.ps1:164 char:2
                 +     Set-AzureStorageBlobContent -File $file `
                 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 31

Message        : The remote server returned an error: (409) Conflict.
StackTrace     :    at Microsoft.WindowsAzure.Commands.Storage.Common.DataMovementTransferHelper.<DoTransfer>d__0.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.WindowsAzure.Commands.Storage.Blob.SetAzureBlobContentCommand.<Upload2Blob>d__45.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.WindowsAzure.Commands.Storage.Common.LimitedConcurrencyTaskScheduler.<RunConcurrentTask>d__26.MoveNext()
Exception      : Microsoft.WindowsAzure.Storage.StorageException
InvocationInfo : {Set-AzureStorageBlobContent}
Line           :        Set-AzureStorageBlobContent -File $file `

Position       : At \src\resources\scripts\New-DataCenter.ps1:164 char:2
                 +     Set-AzureStorageBlobContent -File $file `
                 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 31

Message        : The remote server returned an error: (409) Conflict.
StackTrace     :    at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpResponseParsers.ProcessExpectedStatusCodeNoException[T](HttpStatusCode
                 expectedStatusCode, HttpStatusCode actualStatusCode, T retVal, StorageCommandBase`1 cmd, Exception ex)
                    at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.<>c__DisplayClass57.<PutBlobImpl>b__56(RESTCommand`1 cmd, HttpWebResponse resp,
                 Exception ex, OperationContext ctx)
                    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[T](IAsyncResult getResponseResult)
Exception      : System.Net.WebException
InvocationInfo : {Set-AzureStorageBlobContent}
Line           :        Set-AzureStorageBlobContent -File $file `

Position       : At src\resources\scripts\New-DataCenter.ps1:164 char:2
                 +     Set-AzureStorageBlobContent -File $file `
                 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 31
```

**Comment by blueww** [comment] 2019-05-14 02:23
@abatishchev 
This should caused by the container has enabled Immutability Policy.  See more details in https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-immutable-storage

>all overwrite or delete operations for existing and new objects in the immutable container are not allowed.

You can check if a container has enabled Immutability Policy or LegalHold by check property "HasImmutabilityPolicy" and "HasLegalHold" of output of following command:
```powershell
(Get-AzStorageContainer -Name $containerName -Context $ctx).CloudBlobContainer.Properties
```

or
```powershell
Add-AzAccount
Get-AzRmStorageContainer -ResourceGroupName $rgname -StorageAccountName $accountName -Name $containerName
```

You can see details of the Immutability Policy or LegalHold by ：
```powershell
Get-AzureRmStorageContainerImmutabilityPolicy  -ResourceGroupName $rgname -StorageAccountName $accountName -ContainerName $containerName 
(Get-AzureRmStorageContainer -ResourceGroupName $rgname -StorageAccountName $accountName -Name $containerName).LegalHold.Tags
```

You can remove Immutability Policy (if not Locked) by:
```powershell
$imp = Get-AzureRmStorageContainerImmutabilityPolicy  -ResourceGroupName $rgname -StorageAccountName $accountName -ContainerName $containerName
remove-AzureRmStorageContainerImmutabilityPolicy -ResourceGroupName $rgname -StorageAccountName $accountName -ContainerName $containerName -Etag $imp.Etag
```

**Comment by abatishchev** [comment] 2019-05-14 20:36
I'm deploying ARM template with a number of nested templates. So uploading them to a publicly accessible blob storage and provide a URL to it to PowerShell.
I create a new container on every deployment and never try to delete or overwrite the content.
I think that was an issue with blob storage. Perhaps the cache.
It was gone as soon as I deleted that blob storage account and created another one under slightly different name.
All I want is a retention policy. Is immutability policy the right approach to achieve this?

**Comment by blueww** [comment] 2019-05-15 02:41
@abatishchev
If you are very sure about "I create a new container on every deployment and never try to delete or overwrite the content.", Would you please provide the request activity ID (Or account name and UTC time) when the issue repro again, then we can look further into it.
Please note, create container with "New-AzureRmStorageContainer" on an existing container won't report error with latest PSH (This is by design, and align with [rest API](https://docs.microsoft.com/en-us/rest/api/storagerp/blobcontainers/create#response)) . 

If you just don't want the blob be overwrite/delete after uploaded, immutability policy should be the right way. Anyway, see more in https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-immutable-storage

**Comment by abatishchev** [comment] 2019-05-16 17:50
hi @blueww,
Yes, I just double checked and I'm creating a new container every time I run the script:

1. New-AzureRmStorageContainer
2, Set-AzureRmStorageContainerImmutabilityPolicy
3, Set-AzureStorageBlobContent (in a loop)

If I have 2 then every call of 3 throw the said error (but still sets the content):

```powershell
Set-AzureStorageBlobContent : The remote server returned an error: (409) Conflict. HTTP Status Code: 409 - HTTP Error Message: This operation is not permitted as
the blob is immutable due to a policy.
At \src\resources\scripts\New-ScaleUnit.ps1:163 char:2
+     Set-AzureStorageBlobContent -File $file `
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureStorageBlobContent], StorageException
    + FullyQualifiedErrorId : StorageException,Microsoft.WindowsAzure.Commands.Storage.Blob.SetAzureBlobContentCommand
```

**Comment by blueww** [comment] 2019-05-17 01:19
@abatishchev 

"creating a new container every time" can't gurateen the container not exist before you create it, since as my before reply, create container with "New-AzureRmStorageContainer" on an existing container won't report error with latest PSH (This is by design, and align with rest API) .

You might can add more check here, like try to delete the container, before create it. (Delete will success with a not exist container.)
Remove-AzRmStorageContainer

**Comment by abatishchev** [comment] 2019-05-17 01:40
Here's how I create new container:

```powershell
$dt = $(Get-Date -Format yyyyMMdd-HHmm)
$containerName = "$Usage-$Stamp-$azureRegionAbbreviation-$Environment-$dt".ToLowerInvariant()
New-AzureRmStorageContainer `
        -ContainerName $containerName `
        -StorageAccount $storageAccount `
        -PublicAccess Container `
        -Verbose
```
So basically every minute it's guaranteed to be new and unique. Also I see in the Azure portal it to be created. And I make sure to wait a minute before runs.

**Comment by blueww** [comment] 2019-05-17 01:52
@abatishchev 
From above script, the container should be new.
If so, would you please give the request ID (or at least Storage account name / Time) when the issue happen? (It would be better to if can get a network trace with fiddler.)
Please send that to weiwei@microsoft.com, and hide any credential.

**Comment by blueww** [comment] 2019-05-21 02:16
Will follow up in mail.

**Comment by blueww** [comment] 2019-05-28 09:11
From the network trace, it seems the Blob is updated 2 or more times, so the 2nd/3rd time failed with 409.
Need to check is script has upload blob mutiple times.
As we will follow in mail, close the issue.

**Closed by blueww** 2019-05-28 09:11 UTC
Labels: Service Attention, Storage

**Comment by blueww** [comment] 2019-05-31 01:19
The root cause is found, it was a bug in customer's PowerShell script: getting files recursively included bin and obj folders which contains very old versions of those files. And that what was causing the exception.
