### ISSUE TITLE
 Connect-AzAccount is hanging

### ISSUE THREAD

**Issue by vijosema** [Azure/azure-powershell#13361] opened 2020-10-29 16:46 UTC
## Description
On issuing  Connect-AzAccount, post verification of login, it stays hanging without any progress

## Cost
Node validation is blocked.

**Comment by dingmeng-xue** [comment] 2020-11-01 07:41
@vijosema , thanks for reporting. Please provide detail information from root analysis. 

Which version of Az.Accounts are your using? what authentication type are you using? Please try `$PSVersionTable` to get detail information about system.

**Comment by anthony-schneider** [comment] 2020-11-10 19:55
I too have reported the same issue and have submitted a Microsoft case for this issue.  Here's what I reported in the case.

=================================================================
The issue here is we typically authenticate to Azure using the following:

Connect-AzAccount -Tenant "[tenant]" -Subscription "[subscription]" -Credential (Get-Credential)

When prompted, we enter our AAD UPN and password and successfully connect.

However, when we recently installed the Az 5.0.0 module, this no longer works. If we execute the same line as above in a Powershell window, the error "Process is terminated due to StackOverflowException" is thrown and the Powershell window closes. If we run the same line in a Powershell ISE windows with -debug, the following is displayed:

WARNING: Unable to acquire token for tenant '[tenant name]'

Downgrading the Az.Accounts module from 2.1.0 to 1.9.5 resolves this issue. It appears, in reviewing the release notes for Az 5.0.0 (https://docs.microsoft.com/en-us/powershell/azure/release-notes-azureps?view=azps-5.0.0):

Az.Accounts
Replaced Azure Directory Authentication Library with Microsoft Authentication Library(MSAL).

I suspect this may be the root cause of our issue. Please advise.

=================================================================

Please reach out to me privately to discuss in further detail.

**Comment by dingmeng-xue** [comment] 2020-11-11 02:56
@anthony-schneider , you can find my email address from my profile. Could you share your input value in email, including subscription id and tenant id?

**Comment by anthony-schneider** [comment] 2020-11-11 12:15
@dingmeng-xue - I've sent you a couple emails with the specifics, including the Microsoft case details (notes, screenshots, etc).  Thanks for your help!

**Comment by erich-wang** [comment] 2020-11-12 12:43
@anthony-schneider, could you please share the debug stream by using the following cmdlets:
```powershell
$DebugPreference='Continue'
Connect-AzAccount -Tenant "[tenant]" -Subscription "[subscription]" -Credential (Get-Credential)
```

**Comment by anthony-schneider** [comment] 2020-11-12 16:32
@erich-wang - just sent you an email with the details

**Comment by erich-wang** [comment] 2020-11-18 07:05
The issue is related to ADFS, and it is a bug in MSAL.NET, Bogdan is investigating.

**Comment by erich-wang** [comment] 2020-11-23 08:57
Close this issue as it is duplicate with #13560 which has detail trace. We're working with Identity team to get fix.

**Closed by erich-wang** 2020-11-23 08:57 UTC
Labels: Accounts, customer-reported, needs-author-feedback, question
