### ISSUE TITLE
Azure 0.9.1 on to PS Core 6.0.0 - missing cmdlets

### ISSUE THREAD

**Issue by mhiggins5470** [Azure/azure-powershell#5373] opened 2018-01-26 09:35 UTC
### Cmdlet(s)
New-AzureStorageContext
Remove-AzureStorageBlob
<....others...>

### PowerShell Version
6.0.0.-1 Core on Linux

### Module Version
0.9.1

### OS Version
Linux 4.13.0-1006-azure #8-Ubuntu SMP Fri Jan 12 13:18:04 UTC 2018

### Description
Can;t locate some of the non-RM cmdlets

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

**Comment by markcowl** [comment] 2018-01-29 16:59
Closign as duplicate of #3746 Storage data plane cmdlets have not been moved to NetCore

**Closed by markcowl** 2018-01-29 16:59 UTC
