### ISSUE TITLE
Get-AzureRmContext should show SubscriptionName

### ISSUE THREAD

**Issue by cwe1ss** [Azure/azure-powershell#1639] opened 2016-01-13 07:37 UTC
Right now, Get-AzureRmContext only displays the current SubscriptionId. If you have to deal with multiple subscriptions it would help a lot to also see the name of the subscription. This way we wouldn't have to execute another command like Get-AzureRmSubscription to make sure we are in the correct subscription.

**Comment by markcowl** [comment] 2016-01-14 20:45
@cwe1ss A good suggestion.  You can actually get the subscription name, or select subscriptions by name, but displaying the subscription name would make things easoier in most cases.

**Comment by markcowl** [comment] 2016-05-03 00:40
### Root Cause
get-azureRmSubscription does not display the name in the current display format.  Update the display format to list both the ID and the name for the subscription (in most cases, the name is more useful to the user)

### Proposed Solution
- Display the Subscription Id and Subscription Name in the context
- Ensure that Subscription Name is populated during Add-AzureRmAccount and Set-AzureRmContext cmdlets

### Cost (Work Units): 1

**Comment by hovsepm** [comment] 2016-05-19 21:31
Fixed in dev branch, will be available in June release

**Closed by hovsepm** 2016-05-19 21:31 UTC
Labels: 1 - Ready, P2, Team, Work Units: 0

**Comment by cwe1ss** [comment] 2016-05-20 04:47
Awesome, thank you!
