### ISSUE TITLE
Azure Automation cmdlets allows illegal characters (hypens) in DSC configuration name. GUI prevents deletion of resources with hypens in name.

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-powershell#7738] opened 2018-11-02 22:14 UTC
### Script/Steps for Reproduction

```powershell
Import-AzAutomationDscConfiguration @AAParams -sourcepath configuration-with-hypens.ps1
```

Then try to delete it from the GUI.
![image](https://user-images.githubusercontent.com/15258962/47943136-e9ecfb80-deb1-11e8-81a5-768cae128e7a.png)

### Module Version

0.4.0

### Workaround
Use underscores which are a supported character

### Recommended Fix
Add the input validation to the Azure Automation API backend, don't rely on clients to do the input validation (GUI does it, Az cmdlets don't)

**Comment by JustinGrote** [comment] 2018-11-02 22:16
Workaround is obviously to use underscores which are valid, but still should probably be fixed before it gets someone in trouble, input validation should ideally be added to the AzAutomation backend and not be solely validated by clients (GUI validates it, Az commands don't)

**Comment by maddieclayton** [comment] 2018-11-06 22:51
@vrdmr Can you take a look at this issue?

**Comment by mgreenegit** [comment] 2018-11-08 15:21
This appears to be a duplicate of:
[https://github.com/Azure/azure-powershell/issues/6899](https://github.com/Azure/azure-powershell/issues/6899)

I am tracking this as a bug in Azure DevOps for our team as well.

**Comment by JustinGrote** [comment] 2018-11-08 19:35
Yep it is, it can be closed here and tracked there, once it is fixed there
then it will carry through.

**Closed** 2019-02-20 18:30 UTC
Labels: Automation, Service Attention, automation-dsc
