### ISSUE TITLE
MSI installation kills all PowerShell processes

### ISSUE THREAD

**Issue by ondass** [Azure/azure-powershell#3231] opened 2016-11-30 16:13 UTC
### Module Version
3.1.0 November 2016

### OS Version
any

### Description
the MSI package when run in unattended mode (with -passive or -qn MSIEXEC parrameters) forcibly kills all running powershell processes. What? Are you mad? On a server, many PowerShell tasks may be running during the sole Azure Module installation generally. In my particular case, which I do not consider too much particular anyway, I try to install the Azure module automatically from my automation PowerShell scripts. How am I supposed to do that if the module kills even its own loving parent?

**Comment by markcowl** [comment] 2016-11-30 20:21
This msi behavior has been in effect for about a year.  The issue is that, PowerShell processes may hold dlls that prevent earlier versions of cmdlets in the global mosule location from being removed.

This will be resolved in the msi refactor tracked here:#2220  Closing as a duplicate for that bug.

**Closed by markcowl** 2016-11-30 20:21 UTC
