### ISSUE TITLE
Az.Reservations problems

### ISSUE THREAD

**Issue by ducatijosh** [Azure/azure-powershell#18141] opened 2022-05-12 20:02 UTC
### Description

Hello, We are a service provider looking to get reservation utilization across all customer tenants. We have owner access to all reservations and reservation orders that exist. We've written a PowerShell command to export this data but it randomly works and doesn't work.  This will get all subscriptions my account has access to then one at a time set-azcontext into those subscriptions and pull RI's then go back out and do the next customer subscription. The problem is it will randomly fail on like 1/3 of them with "Operation returned an invalid status code 'Forbidden'" then I'll run the script again and some of the failed ones will pull data while new ones will fail that worked previously. I end up having to run the script like 10 times and compile all the data since it will randomly fail for no reason on Get-AzReservationOrder. Any ideas? It looks like 0.9.0 is still the latest version of Az.Reservations and it hasn't been updated in two years.

### Issue script & Debug output

```PowerShell
Connect-azaccount

$Azsub = Get-AzSubscription

foreach ($Sub in $Azsub) 
{
	Write-Host $Sub.Name
	Set-AzContext -TenantId $Sub.HomeTenantId
	$ReservationOrder = Get-AzReservationorder
		foreach ($r in $ReservationOrder) 
		{
			get-azconsumptionreservationsummary -grain daily -startdate (Get-Date).AddDays(-1) -enddate (Get-Date).AddDays(-1) -reservationorderid $r.name | select-object @{N="Customer";E={($Sub.Name)}},SkuName,ReservationId,ReservationOrderId,AveUtilizationPercentage,MinUtilizationPercentage,MaxUtilizationPercentage,UsageDate,UsedHour,ReservedHour,Id,Name,Tag,Type | export-csv -path “/Users/User/Documents/$((Get-Date).ToString('yyyy_MM_dd'))Reservations.csv" -Encoding ascii -NoTypeInformation -append -verbose
		}

}
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Darwin 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.7.6                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     2.0.0                 Az.Billing                          {Get-AzBillingAccount, Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzBillingProfile…}
Script     0.9.0                 Az.Reservations                     {Get-AzReservation, Get-AzReservationCatalog, Get-AzReservationHistory, Get-AzReservationOrder…}
```

### Error output

```PowerShell
Message        : Operation returned an invalid status code 'Forbidden'
StackTrace     :    at Microsoft.Azure.Management.Reservations.ReservationOrderOperations.ListWithHttpMessagesAsync(Dictionary`2 customHeaders, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.Reservations.ReservationOrderOperationsExtensions.ListAsync(IReservationOrderOperations operations, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.Reservations.ReservationOrderOperationsExtensions.List(IReservationOrderOperations operations)
                    at Microsoft.Azure.Commands.Reservations.Cmdlets.GetReservationOrder.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Azure.Management.Reservations.Models.ErrorException
InvocationInfo : {Get-AzReservationOrder}
Line           : $ReservationOrder = Get-AzReservationorder
                 
Position       : At line:5 char:21
                 + $ReservationOrder = Get-AzReservationorder
                 +                     ~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 24
```

**Comment by dingmeng-xue** [comment] 2022-05-15 14:32
@ducatijosh , according to your description, I suspect it is due to service threshold. Could you turn on debug and look into service response? You can turn on it via `$DebugPreference = "Continue"`

**Comment by navba-MSFT** [comment] 2022-05-17 06:28
@ducatijosh Apologies for the late reply. Thanks for reaching out to us and sharing this feedback. Could you please run the command `$DebugPreference = "Continue"` and then share the debug output of the error ? I understand that the issue is intermittent and getting this details might be hard. But this would definitely help us to understand the cause.

Note: You could remove the sensitive details from the error message before sharing the output here. Awaiting your reply.

**Comment by navba-MSFT** [comment] 2022-05-20 04:17
@ducatijosh I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by ducatijosh** [comment] 2022-05-20 19:51
Here's the output from one that failed, if I rerun the script it will likely succeed, it's random.

DEBUG: AzureQoSEvent: Module: Az.Accounts:2.7.6; CommandName: Set-AzContext; PSVersion: 7.2.2; IsSuccess: True; Duration: 00:00:00.6695628
DEBUG: Finish sending metric.
DEBUG: 2:46:32 PM - SetAzureRMContextCommand end processing.
DEBUG: 2:46:32 PM - GetReservationOrder begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 2:46:32 PM - using account id 'email@address.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'email@address.com', environment: 'AzureCloud', tenant: 'asdfasdfsdf--asdfasdfasdf--asdf'
DEBUG: 2:46:32 PM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'asdfasdfasdf-asdfasdfasfdd-asdfasdf', Scopes:'https://management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'email@address.com'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId: 
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 [05/20/2022 19:46:32 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 [05/20/2022 19:46:32] Found 1 cache accounts and 0 broker accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 [05/20/2022 19:46:32] Returning 1 accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 [05/20/2022 19:46:32 - ] MSAL MSAL.NetCore with assembly version '4.30.1.0'. CorrelationId(0e83ef53-6cf2-49df-a5f9-4ec256198eac)
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 [05/20/2022 19:46:32 - ] === AcquireTokenSilent Parameters ===
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 [05/20/2022 19:46:32 - ] LoginHint provided: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 [05/20/2022 19:46:32 - ] Account provided: True
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 [05/20/2022 19:46:32 - ] ForceRefresh: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 [05/20/2022 19:46:32 - ] 
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 0e83ef53-6cf2-49df-a5f9-4ec256198eac

DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 [05/20/2022 19:46:32 - ] === Token Acquisition (SilentRequest) started:
	
	Authority Host: login.microsoftonline.com
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 [05/20/2022 19:46:32 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 [05/20/2022 19:46:32 - ] Access token is not expired. Returning the found cache entry. [Current time (05/20/2022 19:46:32) - Expiration Time (05/20/2022 20:50:02 +00:00) - Extended Expiration Time (05/20/2022 20:50:02 +00:00)]
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 [05/20/2022 19:46:32 - ] Returning access token found in cache. RefreshOn exists ? False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 [05/20/2022 19:46:32 - ] Fetched access token from host login.microsoftonline.com. 
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 [05/20/2022 19:46:32 - ] === Token Acquisition finished successfully. An access token was returned with Expiration Time: 05/20/2022 20:50:02 +00:00 and Scopes https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2022-05-20T20:50:02.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'sdfasdfasdasf3-asdfasdfasdf-asdf-asdf', UserId: 'email@address.com'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/providers/Microsoft.Capacity/reservationOrders?api-version=2019-04-01

Headers:
x-ms-client-request-id        : 8a4d8a06-8fa3-4f30-99f4-898e2d8bfb1b
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Forbidden

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : 0b2261e6-cf51-4f83-a02d-32ba20d66960
x-ms-correlation-request-id   : 0b2261e6-cf51-4f83-a02d-32ba20d66960
x-ms-routing-request-id       : SOUTHCENTRALUS:20220520T194632Z:0b2261e6-cf51-4f83-a02d-32ba20d66960
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Fri, 20 May 2022 19:46:32 GMT
Connection                    : close

Body:
{
  "error": {
    "code": "AuthorizationFailed",
    "message": "The client 'email@address.com' with object id '' does not have authorization to perform action 'Microsoft.Capacity/reservationOrders/read' over scope '/providers/Microsoft.Capacity' or the scope is invalid. If access was recently granted, please refresh your credentials."
  }
}

Get-AzReservationOrder: 
Line |
   6 |  $ReservationOrder = Get-AzReservationorder
     |                      ~~~~~~~~~~~~~~~~~~~~~~
     | Operation returned an invalid status code 'Forbidden'

**Comment by navba-MSFT** [comment] 2022-05-23 04:59
@ducatijosh Thanks for getting back. The error message you had shared above is self-explanatory.

>"message": "The client '[email@address.com](mailto:email@address.com)' with object id '' does not have authorization to perform action 'Microsoft.Capacity/reservationOrders/read' over scope '/providers/Microsoft.Capacity' or the scope is invalid. If access was recently granted, please refresh your credentials."

Could you confirm if you are assigning the role and immediately performing the Read Reservation Order operation ? If yes, You need to remember that when you assign roles or remove role assignments, it can take up to 30 minutes for changes to take effect. This could explain why it works after some time while you rerun the script.

If you are using the Azure PowerShell you can force a refresh of your role assignment changes by **signing out and signing in**. Like running the [Disconnect-AzAccount ](https://docs.microsoft.com/en-us/powershell/module/az.accounts/disconnect-azaccount?view=azps-7.5.0)and then running [Connect-AzAccount](https://docs.microsoft.com/en-us/powershell/module/az.accounts/connect-azaccount?view=azps-7.5.0). Then set the right subscription context [Select-AzContext](https://docs.microsoft.com/en-us/powershell/module/az.accounts/select-azcontext?view=azps-7.5.0). 

To isolate the issue, you can list all the roles that are assigned to a specified user (mentioned in the error), use [Get-AzRoleAssignment](https://docs.microsoft.com/en-us/powershell/module/az.resources/get-azroleassignment) and check if the `scope` and RoleDefinitionName parameter to check if it has the right permissions.
 
 >Get-AzRoleAssignment -SignInName UserName@company.com | FL DisplayName, RoleDefinitionName, Scope
 
The similar issue is explained [here](https://docs.microsoft.com/en-us/azure/role-based-access-control/troubleshooting#problems-with-azure-role-assignments). Hope this helps.

**Comment by ducatijosh** [comment] 2022-05-23 14:48
Hello, No that is not the case. The owner permissions are static and have been put in place months ago, rerunning the script multiple times nets varying results, I have to rerun it 10+ times to catch results from all our tenants.

**Comment by navba-MSFT** [comment] 2022-05-24 04:49
@ducatijosh Thanks for clarifying. This issue might require a closer look and troubleshooting by checking our backend logs. Could you please let me know, if it is feasible for you to open a support ticket to work on this issue ?

**Comment by navba-MSFT** [comment] 2022-05-26 04:17
@ducatijosh This is a quick follow-up to check on the option of opening a support ticket to troubleshoot this further. Awaiting your reply.

**Comment by navba-MSFT** [comment] 2022-05-30 08:50
@ducatijosh Could you please let us know if you had a chance to open a support ticket to troubleshoot this further ?

**Comment by navba-MSFT** [comment] 2022-06-06 07:20
@ducatijosh We have suggested you to open a Support Ticket to troubleshoot this further. So with that, we will now proceed with closure of this github issue.

**Closed by navba-MSFT** 2022-06-06 07:20 UTC
Labels: Reservations, bug, customer-reported, needs-author-feedback, CXP Attention
