### ISSUE TITLE
Latest docker image "azuresdk/azure-powershell-core" doesn't work as expected

### ISSUE THREAD

**Issue by MoimHossain** [Azure/azure-powershell#8513] opened 2019-02-11 20:28 UTC
### Description

I am using the Docker image "azuresdk/azure-powershell-core:latest".

### Script/Steps for Reproduction

I ran the following command:

```powershell
docker run -i -t -v C:\Git\app:/app/ -w /app/ azuresdk/azure-powershell-core:latest pwsh test.ps1
```

I have the __test.ps1__ file with the following content:

```powershell
Import-Module Az.Profile
```

### Module Version

```powershell

    Directory: /usr/local/share/powershell/Modules


ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Manifest   0.7.0      Az.Aks                              Core,Desk {Get-AzAks, New-AzAks, Remove-AzAks, Import-AzA...
Manifest   0.7.0      Az.AnalysisServices                 Core,Desk {Resume-AzAnalysisServicesServer, Suspend-AzAna...
Manifest   0.7.0      Az.ApiManagement                    Core,Desk {Add-AzApiManagementRegion, Get-AzApiManagement...
Manifest   0.7.0      Az.ApplicationInsights              Core,Desk {Get-AzApplicationInsights, New-AzApplicationIn...
Manifest   0.7.0      Az.Automation                       Core,Desk {Get-AzAutomationHybridWorkerGroup, Remove-AzAu...
Manifest   0.7.0      Az.Batch                            Core,Desk {Remove-AzBatchAccount, Get-AzBatchAccount, Get...
Manifest   0.7.0      Az.Billing                          Core,Desk {Get-AzBillingInvoice, Get-AzBillingPeriod, Get...
Manifest   0.7.0      Az.Cdn                              Core,Desk {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-...
Manifest   0.7.0      Az.CognitiveServices                Core,Desk {Get-AzCognitiveServicesAccount, Get-AzCognitiv...
Manifest   0.7.0      Az.Compute                          Core,Desk {Remove-AzAvailabilitySet, Get-AzAvailabilitySe...
Manifest   0.7.0      Az.Compute.ManagedService           Core,Desk ConvertTo-AzVhd
Manifest   0.7.0      Az.Consumption                      Core,Desk {Get-AzConsumptionBudget, Get-AzConsumptionMark...
Manifest   0.7.0      Az.ContainerInstance                Core,Desk {New-AzContainerGroup, Get-AzContainerGroup, Re...
Manifest   0.7.0      Az.ContainerRegistry                Core,Desk {New-AzContainerRegistry, Get-AzContainerRegist...
Manifest   0.7.0      Az.DataLakeAnalytics                Core,Desk {Get-AzDataLakeAnalyticsDataSource, New-AzDataL...
Manifest   0.7.0      Az.DataLakeStore                    Core,Desk {Get-AzDataLakeStoreTrustedIdProvider, Remove-A...
Manifest   0.7.0      Az.DataMigration                    Core,Desk {New-AzDataMigrationDatabaseInfo, New-AzDataMig...
Manifest   0.7.0      Az.DeviceProvisioningServices       Core,Desk {New-AzIoTDeviceProvisioningService, Get-AzIoTD...
Manifest   0.7.0      Az.DevSpaces                        Core,Desk {Get-AzDevSpacesController, New-AzDevSpacesCont...
Manifest   0.7.0      Az.DevTestLabs                      Core,Desk {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoSh...
Manifest   0.7.0      Az.Dns                              Core,Desk {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Rem...
Manifest   0.7.0      Az.EventGrid                        Core,Desk {New-AzEventGridTopic, Get-AzEventGridTopic, Se...
Manifest   0.7.0      Az.EventHub                         Core,Desk {New-AzEventHubNamespace, Get-AzEventHubNamespa...
Manifest   0.7.0      Az.FrontDoor                        Core,Desk {New-AzFrontDoor, Get-AzFrontDoor, Set-AzFrontD...
Manifest   0.7.0      Az.Insights                         Core,Desk {Get-AzMetricDefinition, Get-AzMetric, Remove-A...
Manifest   0.1.0      Az.IotCentral                       Core,Desk {New-AzIotCentralApp, Get-AzIotCentralApp, Set-...
Manifest   0.7.0      Az.IotHub                           Core,Desk {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerG...
Manifest   0.7.0      Az.KeyVault                         Core,Desk {Add-AzKeyVaultCertificate, Update-AzKeyVaultCe...
Manifest   0.7.0      Az.LogicApp                         Core,Desk {Get-AzIntegrationAccountAgreement, Get-AzInteg...
Manifest   0.7.0      Az.MachineLearning                  Core,Desk {Move-AzMlCommitmentAssociation, Get-AzMlCommit...
Manifest   0.7.0      Az.MachineLearningCompute           Core,Desk {Get-AzMlOpCluster, Get-AzMlOpClusterKey, Test-...
Manifest   0.7.0      Az.ManagedServiceIdentity           Core,Desk {New-AzUserAssignedIdentity, Get-AzUserAssigned...
Manifest   0.7.0      Az.ManagementPartner                Core,Desk {Get-AzManagementPartner, New-AzManagementPartn...
Manifest   0.7.0      Az.Maps                             Core,Desk {Get-AzMapsAccount, New-AzMapsAccount, Remove-A...
Manifest   0.7.0      Az.MarketplaceOrdering              Core,Desk {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}
Manifest   0.7.0      Az.Media                            Core,Desk {Sync-AzMediaServiceStorageKeys, Set-AzMediaSer...
Manifest   0.7.0      Az.Network                          Core,Desk {Add-AzApplicationGatewayAuthenticationCertific...
Manifest   0.7.0      Az.NotificationHubs                 Core,Desk {Get-AzNotificationHub, Get-AzNotificationHubAu...
Manifest   0.7.0      Az.OperationalInsights              Core,Desk {New-AzOperationalInsightsAzureActivityLogDataS...
Manifest   0.7.0      Az.PolicyInsights                   Core,Desk {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPo...
Manifest   0.7.0      Az.PowerBIEmbedded                  Core,Desk {Remove-AzPowerBIWorkspaceCollection, Get-AzPow...
Manifest   0.7.0      Az.Profile                          Core,Desk {Disable-AzDataCollection, Disable-AzContextAut...
Manifest   0.7.0      Az.RecoveryServices                 Core,Desk {Get-AzRecoveryServicesBackupProperty, Get-AzRe...
Manifest   0.7.0      Az.RedisCache                       Core,Desk {Remove-AzRedisCachePatchSchedule, New-AzRedisC...
Manifest   0.7.0      Az.Relay                            Core,Desk {New-AzRelayNamespace, Get-AzRelayNamespace, Se...
Manifest   0.7.0      Az.Reservations                     Core,Desk {Get-AzReservationOrder, Get-AzReservation, Get...
Manifest   0.7.0      Az.ResourceGraph                    Core,Desk Search-AzGraph
Manifest   0.7.0      Az.Resources                        Core,Desk {Get-AzProviderOperation, Remove-AzRoleAssignme...
Manifest   0.7.0      Az.Search                           Core,Desk {New-AzSearchService, Get-AzSearchService, Set-...
Manifest   0.7.0      Az.Security                         Core,Desk {Get-AzSecurityAlert, Set-AzSecurityAlert, Get-...
Manifest   0.7.0      Az.ServiceBus                       Core,Desk {New-AzServiceBusNamespace, Get-AzServiceBusNam...
Manifest   0.7.0      Az.ServiceFabric                    Core,Desk {Add-AzServiceFabricApplicationCertificate, Add...
Manifest   0.7.0      Az.SignalR                          Core,Desk {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey...
Manifest   0.7.0      Az.Sql                              Core,Desk {Get-AzSqlDatabaseTransparentDataEncryption, Ge...
Manifest   0.7.0      Az.Storage                          Core,Desk {Get-AzStorageAccount, Get-AzStorageAccountKey,...
Manifest   0.7.0      Az.StorageSync                      Core,Desk Invoke-AzStorageSyncCompatibilityCheck
Manifest   0.7.0      Az.StreamAnalytics                  Core,Desk {Get-AzStreamAnalyticsFunction, Get-AzStreamAna...
Manifest   0.7.0      Az.Subscription                     Core,Desk New-AzSubscription
Manifest   0.7.0      Az.Tags                             Core,Desk {Remove-AzTag, Get-AzTag, New-AzTag}
Manifest   0.7.0      Az.TrafficManager                   Core,Desk {Add-AzTrafficManagerCustomHeaderToEndpoint, Re...
Manifest   0.7.0      Az.UsageAggregates                  Core,Desk Get-UsageAggregates
Manifest   0.7.0      Az.Websites                         Core,Desk {Get-AzAppServicePlan, Set-AzAppServicePlan, Ne...


    Directory: /opt/microsoft/powershell/6/Modules


ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Manifest   1.2.2.0    Microsoft.PowerShell.Archive        Desk      {Compress-Archive, Expand-Archive}
Manifest   6.1.0.0    Microsoft.PowerShell.Host           Core      {Start-Transcript, Stop-Transcript}
Manifest   6.1.0.0    Microsoft.PowerShell.Management     Core      {Add-Content, Clear-Content, Clear-ItemProperty...
Manifest   6.1.0.0    Microsoft.PowerShell.Security       Core      {Get-Credential, Get-ExecutionPolicy, Set-Execu...
Manifest   6.1.0.0    Microsoft.PowerShell.Utility        Core      {Format-List, Format-Custom, Format-Table, Form...
Script     1.1.7.2    PackageManagement                   Desk      {Find-Package, Get-Package, Get-PackageProvider...
Script     1.6.7      PowerShellGet                       Desk      {Find-Command, Find-DSCResource, Find-Module, F...
Script     0.0        PSDesiredStateConfiguration         Desk      {Generate-VersionInfo, Set-PSMetaConfigDocInsPr...
Script     2.0.0      PSReadLine                          Desk      {Get-PSReadLineKeyHandler, Set-PSReadLineKeyHan...
Binary     1.1.2      ThreadJob                           Desk      Start-ThreadJob
```

### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

I get the following error:

```
Import-Module : Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.14.0.8, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
At /app/security-test.ps1:3 char:1
+ Import-Module Az.Profile
+ ~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
+ FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand

```

Any ideas?

**Comment by markcowl** [comment] 2019-02-11 21:03
Te docker images were never offically supported and ar enon longer being maintained - you can download the moduel to any platform using ```Install-Module Az```.

BTW - we are trying to decide whether creating docker images as part of official builds would be useful to customers - would you consume a docker image in preference to cloudshell / local insallation?  If so, why do you prefer the docker image?  Thanks for any feedback.

**Comment by MoimHossain** [comment] 2019-02-12 06:09
@markcowl thanks for the info. I will go with the ``` Install-Module Az ```.

Can't speak for others, but the scenario I am in, writing some __terraform__ modules in many repositories for an enterprise. Kind of creating a baseline set of blessed modules - that are compliant with the organization policies and security needs. In these modules, I wanted to do some kind of unit tests and sanity checks for these modules. My initial plan (still now it is) to run a container in pipeline of these module repositories that run some test **assertions** in powershell. Doing it docker makes it very easy for large number of contributor in these repositories - so they can run it easily (more so predictably) in their local development machine as well as pipelines.

Hope this makes sense.

**Comment by jsnikhil** [comment] 2019-03-18 15:03
An official docker image per release will be very useful for us. We try to use a consistent environment across our development, production and deployment environments, and docker gives that flexibility quite easily. Having the need to install powershell-core on all diff local platforms MacOS, Linux and Windows and keep it consistent is too much overhead for developers.

Right now we use a tag from the docker repository https://hub.docker.com/r/azuresdk/azure-powershell-core/tags. I am guessing there are community driven, which is not ideal.

**Comment by 8** [comment] 2019-04-24 08:46
Hi, I've got the same problem - the docker image just doesn't work.

Why would you not support the image?
1) The user azuresdk (https://hub.docker.com/u/azuresdk) sure looks official.
2) The documentation doesn't say anything different (https://hub.docker.com/r/azuresdk/azure-powershell-core)
3) The last image was pushed 10 hours ago, so it's even recent.

About the question why we would use it:
Because we need something simple that works in the CI.

Take care,
Martin

**Comment by sean-nixon** [comment] 2019-06-06 17:49
> Would you consume a docker image in preference to cloudshell / local insallation?

Yes, absolutely. 

> If so, why do you prefer the docker image?

Same reason why docker is useful for applications - isolate dependencies and create a consistent environment. Cloudshell is useless for CI/CD. Local installation adds friction and makes it hard to test new versions of Azure PowerShell, either locally or in our CI/CD process. We can't simply upgrade the local installation because that could break existing jobs.

**Comment by skrivopishin** [comment] 2019-06-18 09:27
Add-Type -Path "/usr/local/share/powershell/Modules/Az.Profile/PreloadAssemblies/Microsoft.IdentityModel.Clients.ActiveDirectory.dll"

**Comment by markcowl** [comment] 2019-08-05 04:42
### Description

The signing job should produce a Docker container image with the signed modules installed to the global `$PSModulePath` and post to DockerHub for each successful build.  

Base images with PowerShell installed are here: https://hub.docker.com/_/microsoft-powershell?tab=description

Use the Ubuntu 18.04 latest docker image as a base: https://github.com/PowerShell/PowerShell-Docker/blob/master/release/stable/ubuntu18.04/docker/Dockerfile

- [ ] Create dockerfile for docker image based on latest powershell ubuntu 18.0.4 image
- [ ] Add image creation to signign job in ADO
- [ ] Validate Docker image using the base test script here: "\\aaptfile01\adxsdk\PowerShell\2019_07_30_PowerShell\scripts\RmCoreSmokeTests.ps1" 


I sent the details on our dockerhub account by email

**Comment by xiaohuyyyy-ms** [comment] 2019-08-09 06:25
The new pipeline is in https://dev.azure.com/azure-sdk/internal/_build?definitionId=721&_a=summary. 
And is there any naming rules of the image tag name we should follow? Currently I'm using the build number.

**Comment by sean-nixon** [comment] 2019-08-09 20:06
Not sure the additional level of effort or appetite for this, but we would love it if the docker image tags pushed to Docker Hub were signed using Docker Content Trust. We are trying to enforce signed images within our environment.

**Comment by dolauli** [comment] 2019-08-29 08:24
Build number is internal and could rotate. Suggest using the github commit id as the image tag, which is unique and more meaningful.

**Comment by dolauli** [comment] 2019-08-29 08:33
@markcowl 
We have to do a manual authentication through a URL to run "\\aaptfile01\adxsdk\PowerShell\2019_07_30_PowerShell\scripts\RmCoreSmokeTests.ps1". So does it mean we should run the test manually?

**Comment by markcowl** [comment] 2019-10-28 08:12
@dcaro please add any requirements for adding to an Azure image registry

**Comment by dcaro** [comment] 2019-12-02 20:05
@VeryEarly I have sent you the information over email.

**Comment by dingmeng-xue** [comment] 2019-12-05 15:16
Duplicate of #7302

**Closed by dingmeng-xue** 2019-12-05 15:16 UTC
Labels: Azure PS Team, Ramp Up
