### ISSUE TITLE
Permissions are not inherited properly to Key vault, when a contributor or Owner permission is applied to respective Resource group or even subscription

### ISSUE THREAD

**Issue by RoshanKumarMicrosoft** [Azure/azure-powershell#8416] opened 2019-01-28 13:11 UTC
**Commandlets used** : Set-AzureRmKeyVaultAccessPolicy -VaultName $keyVault.VaultName -ObjectId $storageAccount.Identity.PrincipalId -PermissionsToKeys wrapkey,unwrapkey,get​

**Error getting** : 
System.Data.Services.Client.DataServiceQueryException: An error occurred while processing this request. ---> System.Data.Services.Client.DataServiceClientException: {"odata.error":{"code":"Authorization_RequestDenied","message":{"lang":"en","value":"Insufficient privileges to complete the operation."},"requestId":"d9063637-da8a-4ea1-97ff-1ee8b4505f11","date":"2019-01-15T15:14:58"}}​

After investigating we finded assigning owner permission to subscription or resource group by default will get only write permission on keyvault but not read permission.

**Workaround** : 

1. We should either give read permission to graph API 
2.  By passing -BypassObjectIdValidation key 
Which Enables you to specify an object ID without validating that the object exists in Azure Active Directory. Use this parameter only if you want to grant access to your key vault to an object ID that refers to a delegated security group from another Azure tenant.

**Expectation** : It should also get read permission on keyvault.

**Comment by markcowl** [comment] 2019-01-28 18:57
@RoshanKumarMicrosoft Can you provide the additional data requested in the issue template?  This will help us to pinpooint the issue.  From the description and error I cannot tell if the issue is with permissions in Graph, KeyVault management plane, or KeyVault data plane Authorization.

- Module Layout ```Get-Module -ListAvailable```
- Detailed error information ```Resolve-AzureRmError``` after the error occurs
- Debug stream traces for the failing cmdlet invocation.  Set ```$DebugPreference="Continue"``` then run the failing cmdlet.

**Comment by markcowl** [comment] 2019-02-01 19:22
@RoshanKumarMicrosoft Please provide the requested information.  Otherwise we will have to close this issue as 'No Repro'

**Comment by maddieclayton** [comment] 2019-02-09 19:25
Closing for inactivity. Please reopen when you are able to provide the requested information.

**Comment by markdebruijne** [comment] 2019-04-11 19:27
@maddieclayton I can confirm I face the same issue within the same setup @RoshanKumarMicrosoft is mentioning
- Azure DevOps Release pipeline
  - Service connection based on AAD App Registration with `Azure Active Directory Graph (1)` > `User.Read` API permissions, and `Reader` RBAC role applied to the target resource group the KeyVault is added to. 
- Azure PowerShell task, version `3.x` with inline script and above service connection selected
```
Set-AzureRmKeyVaultAccessPolicy -ResourceGroupName "rg-digital" -VaultName "digital-vault" -ObjectId $(appServiceIdentityPrincipalIdStagingSlot) -PermissionsToSecrets get
```

*StackTrace*
```
##[debug]+ Set-AzureRmKeyVaultAccessPolicy -ResourceGroupName "rg-digitalc ...
##[debug]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : CloseError: (:) [Set-AzureRmKeyVaultAccessPolicy], DataServiceQueryException
##[debug]    + FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.SetAzureKeyVaultAccessPolicy
##[debug] 
##[debug]Script stack trace:
##[debug]at <ScriptBlock>, D:\a\_temp\c860e8c0-8b24-4e6d-8fc3-df21845298a0.ps1: line 2
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, D:\a\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\3.1.23\AzurePowerShell.ps1: line 128
##[debug]at <ScriptBlock>, D:\a\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\3.1.23\AzurePowerShell.ps1: line 124
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.Data.Services.Client.DataServiceQueryException: An error occurred while processing this request. ---> System.Data.Services.Client.DataServiceClientException: {"odata.error":{"code":"Authorization_RequestDenied","message":{"lang":"en","value":"Insufficient privileges to complete the operation."},"requestId":"3408869a-e7f7-4d91-b732-e484059f1b26","date":"2019-04-11T19:11:22"}}
##[debug]   at System.Data.Services.Client.BaseAsyncResult.EndExecute[T](Object source, String method, IAsyncResult asyncResult)
##[debug]   at System.Data.Services.Client.QueryResult.EndExecuteQuery[TElement](Object source, String method, IAsyncResult asyncResult)
##[debug]   --- End of inner exception stack trace ---
##[debug]   at System.Data.Services.Client.QueryResult.EndExecuteQuery[TElement](Object source, String method, IAsyncResult asyncResult)
##[debug]   at System.Data.Services.Client.DataServiceRequest.EndExecute[TElement](Object source, DataServiceContext context, String method, IAsyncResult asyncResult)
##[debug]   at System.Data.Services.Client.DataServiceContext.EndExecute[TElement](IAsyncResult asyncResult)
##[debug]   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
##[debug]--- End of stack trace from previous location where exception was thrown ---
##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
##[debug]   at Microsoft.Azure.ActiveDirectory.GraphClient.Extensions.DataServiceContextWrapper.<ExecuteAsyncInternal>d__59`1.MoveNext()
##[debug]--- End of stack trace from previous location where exception was thrown ---
##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
##[debug]   at Microsoft.Azure.ActiveDirectory.GraphClient.ActiveDirectoryClient.<GetObjectsByObjectIdsAsync>d__5.MoveNext()
##[debug]--- End of stack trace from previous location where exception was thrown ---
##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
##[debug]   at Microsoft.Azure.Commands.KeyVault.KeyVaultManagementCmdletBase.ValidateObjectId(String objId)
##[debug]   at Microsoft.Azure.Commands.KeyVault.KeyVaultManagementCmdletBase.GetObjectId(String objectId, String upn, String email, String spn)
##[debug]   at Microsoft.Azure.Commands.KeyVault.SetAzureKeyVaultAccessPolicy.ExecuteCmdlet()
##[debug]   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
##[error]An error occurred while processing this request.
```

*Module Information*
```
2019-04-11T19:11:03.6043654Z ##[debug]Loading module from path 'C:\Modules\azurerm_6.7.0\AzureRM.KeyVault\5.1.1\AzureRM.KeyVault.psm1'.
2019-04-11T19:11:03.6148544Z ##[debug]Loading module from path 'C:\Modules\azurerm_6.7.0\AzureRM.KeyVault\5.1.1\Microsoft.Azure.Commands.KeyVault.dll'.
```

*Az module*
I tried the version `v4.x preview` and the newer `Set-AzKeyVaultAccessPolicy` commandlet, same error. *Forbidden* on a HTTP POST to Graph method `GetObjectsByObjectIdsWithHttpMessagesAsync` validating the target ObjectId. 
```
2019-04-11T14:29:18.4326260Z ##[debug]Set-AzKeyVaultAccessPolicy : Exception of type 'Microsoft.Rest.Azure.CloudException' was thrown.
2019-04-11T14:29:18.4340460Z ##[debug]At D:\a\_temp\adad55e9-e1d9-4f54-8ee2-87be71716cc0.ps1:2 char:1
2019-04-11T14:29:18.4354813Z ##[debug]+ Set-AzKeyVaultAccessPolicy -ResourceGroupName "rg-digitalc ...
2019-04-11T14:29:18.4368445Z ##[debug]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2019-04-11T14:29:18.4382612Z ##[debug]    + CategoryInfo          : CloseError: (:) [Set-AzKeyVaultAccessPolicy], CloudException
2019-04-11T14:29:18.4404610Z ##[debug]    + FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.SetAzureKeyVaultAccessPolicy
2019-04-11T14:29:18.4419392Z ##[debug] 
2019-04-11T14:29:18.4447779Z ##[debug]Script stack trace:
2019-04-11T14:29:18.4482209Z ##[debug]at <ScriptBlock>, D:\a\_temp\adad55e9-e1d9-4f54-8ee2-87be71716cc0.ps1: line 2
2019-04-11T14:29:18.4496377Z ##[debug]at <ScriptBlock>, <No file>: line 1
2019-04-11T14:29:18.4511553Z ##[debug]at <ScriptBlock>, D:\a\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\4.0.0\azurepowershell.ps1: line 107
2019-04-11T14:29:18.4524869Z ##[debug]at <ScriptBlock>, D:\a\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\4.0.0\azurepowershell.ps1: line 103
2019-04-11T14:29:18.4539925Z ##[debug]at <ScriptBlock>, <No file>: line 1
2019-04-11T14:29:18.4553287Z ##[debug]at <ScriptBlock>, <No file>: line 22
2019-04-11T14:29:18.4566301Z ##[debug]at <ScriptBlock>, <No file>: line 18
2019-04-11T14:29:18.4580067Z ##[debug]at <ScriptBlock>, <No file>: line 1
2019-04-11T14:29:18.4600450Z ##[debug]Exception:
2019-04-11T14:29:18.4650440Z ##[debug]Microsoft.Rest.Azure.CloudException: Exception of type 'Microsoft.Rest.Azure.CloudException' was thrown.
2019-04-11T14:29:18.4663786Z ##[debug]   at Microsoft.Azure.Graph.RBAC.Version1_6.ObjectsOperations.<GetObjectsByObjectIdsWithHttpMessagesAsync>d__6.MoveNext()
2019-04-11T14:29:18.4676048Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2019-04-11T14:29:18.4689324Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-04-11T14:29:18.4703516Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-04-11T14:29:18.4717344Z ##[debug]   at Microsoft.Azure.Graph.RBAC.Version1_6.ObjectsOperationsExtensions.<GetObjectsByObjectIdsAsync>d__3.MoveNext()
2019-04-11T14:29:18.4731776Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2019-04-11T14:29:18.4744550Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-04-11T14:29:18.4756505Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2019-04-11T14:29:18.4770075Z ##[debug]   at Microsoft.Azure.Graph.RBAC.Version1_6.ObjectsOperationsExtensions.GetObjectsByObjectIds(IObjectsOperations operations, GetObjectsParameters parameters)
2019-04-11T14:29:18.4784418Z ##[debug]   at Microsoft.Azure.Graph.RBAC.Version1_6.ActiveDirectory.ActiveDirectoryClient.GetObjectsByObjectId(List`1 objectIds)
2019-04-11T14:29:18.4798992Z ##[debug]   at Microsoft.Azure.Commands.KeyVault.KeyVaultManagementCmdletBase.ValidateObjectId(String objId)
2019-04-11T14:29:18.4813496Z ##[debug]   at Microsoft.Azure.Commands.KeyVault.KeyVaultManagementCmdletBase.GetObjectId(String objectId, String upn, String email, String spn)
2019-04-11T14:29:18.4829305Z ##[debug]   at Microsoft.Azure.Commands.KeyVault.SetAzureKeyVaultAccessPolicy.ExecuteCmdlet()
2019-04-11T14:29:18.4843660Z ##[debug]   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()````

**Comment by markdebruijne** [comment] 2019-04-11 19:30
Might be related to: https://github.com/Azure/azure-powershell/issues/8592

**Comment by maddieclayton** [comment] 2019-04-11 20:24
@markdebruijne Can you try this command again with the most recent version of Az and let me know if you are still seeing this error? I made a fix a little while back that hopefully should at least throw a good error message if not succeed.

**Comment by markdebruijne** [comment] 2019-04-12 12:05
@maddieclayton Do you have a pointer how to enforce the _"the most recent version of Az"_ within the Azure Powershell `v4.x preview` version within an Azure DevOps Release pipeline step/tasks?

**Comment by vany0114** [comment] 2019-04-14 00:54
I'm facing exactly the same issue on my CD pipeline in Azure Devops, I need to grant perms to the slot which I create for deployment in the pipeline, @markdebruijne any luck on that?

**Comment by vany0114** [comment] 2019-04-16 02:40
@maddieclayton can you open the issue again, please? The error is still there.

**Comment by markdebruijne** [comment] 2019-04-17 20:01
> I'm facing exactly the same issue on my CD pipeline in Azure Devops, I need to grant perms to the slot which I create for deployment in the pipeline, @markdebruijne any luck on that?

@vany0114 I've implemented the workaround by using the `-BypassObjectIdValidation` switch
```
Set-AzureRmKeyVaultAccessPolicy -ResourceGroupName "rg-digital" -VaultName "digital-vault" -ObjectId $(appServiceIdentityPrincipalIdStagingSlot) -PermissionsToSecrets get
```

To get the respective ObjectId for the deployment slot, you can use the `Get-AzureRmWebAppSlot -ResourceGroupName "Default-Web-WestUS" -Name "WebAppStandard" -Slot "Slot001"` and then the `.Identity.PrincipalId` property
https://docs.microsoft.com/en-us/powershell/module/AzureRM.Websites/Get-AzureRmWebAppSlot?view=azurermps-6.13.0 and https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.websites.models.managedserviceidentity.principalid?view=azure-dotnet#Microsoft_Azure_Management_WebSites_Models_ManagedServiceIdentity_PrincipalId

**Comment by YvonneArnoldus** [comment] 2019-05-14 09:12
Hi,

I'm facing the same problem. I'm unable to create a policy in the Key Vault for an existing Service Principal.

**Environment**: 
Azure Dev Ops Release Pipeline

**Service connection**: Visual Studio Enterprise
Type: Azure Resource Manager
Created by Yvonne ... 
Connected to service using Service Principal

I created this Service Connection with the Global administrator of the subscription.

**Task**: Azure PowerShell
Version 4.* (Preview)
Azure PowerShell Version: Latest installed version


The script:
```
param (
    [Parameter(Mandatory = $true)]
    [string]
    $KeyVaultName,

    [Parameter(Mandatory = $false)]
    [string]
    $ServicePrincipalObjectId
)
$DebugPreference = "Continue"
Set-AzKeyVaultAccessPolicy -VaultName $KeyVaultName -ServicePrincipalName $ServicePrincipalClientId -PermissionsToSecrets get
```
Gives the error
```
2019-05-14T08:29:34.8681135Z DEBUG: ============================ HTTP RESPONSE ============================
2019-05-14T08:29:34.8682762Z DEBUG: 
2019-05-14T08:29:34.8686396Z DEBUG: Status Code:
2019-05-14T08:29:34.8689304Z DEBUG: Forbidden
2019-05-14T08:29:34.8691822Z DEBUG: 
2019-05-14T08:29:34.8695916Z DEBUG: Headers:
2019-05-14T08:29:34.8701033Z DEBUG: Pragma                        : no-cache
2019-05-14T08:29:34.8705379Z DEBUG: ocp-aad-diagnostics-server-name: 0JGMW8hhbuxvMO3bQViCAw6CFgJ6+/AaTlEXs2nm6yM=
2019-05-14T08:29:34.8709569Z DEBUG: request-id                    : 299de0e4-5592-49ff-8ea8-9afd5bf74772
2019-05-14T08:29:34.8712962Z DEBUG: client-request-id             : 81f4d083-c560-48ee-b28a-b68945e5f70c
2019-05-14T08:29:34.8716996Z DEBUG: x-ms-dirapi-data-contract-version: 1.6
2019-05-14T08:29:34.8719586Z DEBUG: ocp-aad-session-key           : 
2019-05-14T08:29:34.8719866Z *****************
2019-05-14T08:29:34.8722229Z DEBUG: xRjW75Zq1BAjsLPOWdvu-AphMyzQ-B8J6GkBR4l1-.nZ4H-nrtCOAQBxp2wuE2upgDZ1DmdbxN1Q-eN2fYbVs
2019-05-14T08:29:34.8725560Z DEBUG: DataServiceVersion            : 3.0;
2019-05-14T08:29:34.8729327Z DEBUG: Strict-Transport-Security     : max-age=31536000; includeSubDomains
2019-05-14T08:29:34.8732917Z DEBUG: Access-Control-Allow-Origin   : *
2019-05-14T08:29:34.8737285Z DEBUG: Duration                      : 364639
2019-05-14T08:29:34.8741533Z DEBUG: Cache-Control                 : no-cache
2019-05-14T08:29:34.8748784Z DEBUG: Date                          : Tue, 14 May 2019 08:29:34 GMT
2019-05-14T08:29:34.8752943Z DEBUG: X-AspNet-Version              : 4.0.30319
2019-05-14T08:29:34.8758257Z DEBUG: X-Powered-By                  : ASP.NET
2019-05-14T08:29:34.8760800Z DEBUG: 
2019-05-14T08:29:34.8764060Z DEBUG: Body:
2019-05-14T08:29:34.8767111Z DEBUG: {
2019-05-14T08:29:34.8769980Z DEBUG:   "odata.error": {
2019-05-14T08:29:34.8773141Z DEBUG:     "code": "Authorization_RequestDenied",
2019-05-14T08:29:34.8777824Z DEBUG:     "message": {
2019-05-14T08:29:34.8781226Z DEBUG:       "lang": "en",
2019-05-14T08:29:34.8789099Z DEBUG:       "value": "Insufficient privileges to complete the operation."
2019-05-14T08:29:34.8791780Z DEBUG:     },
2019-05-14T08:29:34.8797960Z DEBUG:     "requestId": "299de0e4-5592-49ff-8ea8-9afd5bf74772",
2019-05-14T08:29:34.8801077Z DEBUG:     "date": "2019-05-14T08:29:34"
2019-05-14T08:29:34.8805014Z DEBUG:   }
2019-05-14T08:29:34.8808443Z DEBUG: }
2019-05-14T08:29:34.8810744Z DEBUG: 
2019-05-14T08:29:34.8816433Z DEBUG: 
```

The script:
```
param (
    [Parameter(Mandatory = $true)]
    [string]
    $KeyVaultName,

    [Parameter(Mandatory = $false)]
    [string]
    $ServicePrincipalObjectId
)

$DebugPreference = "Continue"

Set-AzKeyVaultAccessPolicy -VaultName $KeyVaultName -ObjectId $ServicePrincipalObjectId -PermissionsToSecrets get
```

Gives the error:
```
2019-05-14T08:48:10.1626264Z DEBUG: ============================ HTTP RESPONSE ============================
2019-05-14T08:48:10.1632471Z DEBUG: 
2019-05-14T08:48:10.1637391Z DEBUG: Status Code:
2019-05-14T08:48:10.1642986Z DEBUG: Forbidden
2019-05-14T08:48:10.1648150Z DEBUG: 
2019-05-14T08:48:10.1652928Z DEBUG: Headers:
2019-05-14T08:48:10.1659384Z DEBUG: Pragma                        : no-cache
2019-05-14T08:48:10.1664370Z DEBUG: ocp-aad-diagnostics-server-name: OAoPLpWGE/6fa69CGqWU5OSAHY6b1Tp4zRSfAoxx82g=
2019-05-14T08:48:10.1671355Z DEBUG: request-id                    : b13df2bc-3272-4fbe-8d27-e65d9b9bd2c7
2019-05-14T08:48:10.1676647Z DEBUG: client-request-id             : 05a91dad-2f81-4e08-808e-db7bbc5fb1bf
2019-05-14T08:48:10.1682535Z DEBUG: x-ms-dirapi-data-contract-version: 1.6
2019-05-14T08:48:10.1687873Z DEBUG: ocp-aad-session-key           : 
2019-05-14T08:48:10.1688051Z *****
2019-05-14T08:48:10.1693123Z DEBUG: hGNKc2uWF65pvH3229V-FYrzStCdZndsPNQZSMOE3.DkxkSU2N9qBIauVbwNsjJtoWax8phfCXmFUwSOrwTzM
2019-05-14T08:48:10.1700029Z DEBUG: DataServiceVersion            : 3.0;
2019-05-14T08:48:10.1706668Z DEBUG: Strict-Transport-Security     : max-age=31536000; includeSubDomains
2019-05-14T08:48:10.1713422Z DEBUG: Access-Control-Allow-Origin   : *
2019-05-14T08:48:10.1718896Z DEBUG: Duration                      : 752103
2019-05-14T08:48:10.1723477Z DEBUG: Cache-Control                 : no-cache
2019-05-14T08:48:10.1732695Z DEBUG: Date                          : Tue, 14 May 2019 08:48:09 GMT
2019-05-14T08:48:10.1738725Z DEBUG: X-AspNet-Version              : 4.0.30319
2019-05-14T08:48:10.1745941Z DEBUG: X-Powered-By                  : ASP.NET
2019-05-14T08:48:10.1750936Z DEBUG: 
2019-05-14T08:48:10.1754535Z DEBUG: Body:
2019-05-14T08:48:10.1760176Z DEBUG: {
2019-05-14T08:48:10.1766253Z DEBUG:   "odata.error": {
2019-05-14T08:48:10.1770849Z DEBUG:     "code": "Authorization_RequestDenied",
2019-05-14T08:48:10.1776892Z DEBUG:     "message": {
2019-05-14T08:48:10.1781954Z DEBUG:       "lang": "en",
2019-05-14T08:48:10.1802826Z DEBUG:       "value": "Insufficient privileges to complete the operation."
2019-05-14T08:48:10.1810717Z DEBUG:     },
2019-05-14T08:48:10.1824142Z DEBUG:     "requestId": "b13df2bc-3272-4fbe-8d27-e65d9b9bd2c7",
2019-05-14T08:48:10.1829489Z DEBUG:     "date": "2019-05-14T08:48:09"
2019-05-14T08:48:10.1835399Z DEBUG:   }
2019-05-14T08:48:10.1839012Z DEBUG: }
2019-05-14T08:48:10.1844149Z DEBUG: 
2019-05-14T08:48:10.1848577Z DEBUG: 
```

If I add the flag -BypassObjectIdValidation, there is no error but the Service Principal cannot access the secrets.

The Policy is created for the user but when the Service Principal is used to retrieve the secret a Forbidden error is given. 

In the portal I see that I'm missing the word APPLICATION in the Access policies overview. 

When I delete the policy in the portal and recreate it there the word APPLICATION appears and I can retrieve the secret with the Service Principal.

**Comment by vany0114** [comment] 2019-08-31 01:28
@markdebruijne I just saw your response, I ended up leaving this is my low priority tasks, I'm gonna try it, thanks a lot!

**Comment by motowilliams** [comment] 2020-02-25 18:33
February 2020 checking in - we are still having this problem. Any update?

**Comment by dingmeng-xue** [comment] 2020-06-20 11:11
@isra-fel , please check if this issue can be reproduced in the current Az.KeyVault 2.0.0

**Comment by bgawale** [comment] 2021-04-07 12:43
2021 check - any update on this? still same issue even when used with -BypassObjectIdValidation switch. This can easily be seen when Azure DevOps service principal tries to set access policies on the given key vault through Azure PS.

**Comment by isra-fel** [comment] 2021-04-08 07:10
`Set-AzureRmKeyVaultAccessPolicy` calls Azure Active Directory API to validate the object ID (principal ID) user inputs. When the logged in user or service principal does not have `Directory.Read.All` permission, you may get an unauthorized error.

This can be fixed by either adding correct permission to your logged in principal, or to add a `-BypassObjectIdValidation` switch.

If that doesn't help, please share the debug log with us:
```
## Debug output

<!-- Set $DebugPreference='Continue' before running the repro and paste the resulting debug stream in the below code block
     ATTENTION: Be sure to remove any sensitive information that may be in the logs -->

```

```

## Error output

<!-- Please run Resolve-AzError and paste the output in the below code block
     ATTENTION: Be sure to remove any sensitive information that may be in the logs -->
```

**Closed** 2021-05-01 08:01 UTC
Labels: Azure PS Team, KeyVault, customer-reported, needs-author-feedback, no-recent-activity
