### ISSUE TITLE
Import-AzApiManagementApi  

### ISSUE THREAD

**Issue by arpitmishra-eaton** [Azure/azure-powershell#18987] opened 2022-07-20 09:50 UTC
### Description

Import-AzApiManagementApi :
Error Code: ResourceGroupNotFound 

i'm trying to import function app to apim using below script and getting above error. though already set the subscription but still getting it. please help

 Import-AzApiManagementApi -Context $context -SpecificationFormat OpenApi -SpecificationUrl https://xyz.azurewebsites.net/items -Path "dev"

### Issue script & Debug output

```PowerShell
DEBUG: 3:08:56 PM - ImportAzureApiManagementApi begin processing with ParameterSet 'ImportFromUrl'.
DEBUG: 3:08:56 PM - using account id 'ArpitMishra@eaton.com'...
DEBUG: 3:08:56 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: [Common.Authentication]: Authenticating using Account: 'ArpitMishra@eaton.com', environment: 'AzureCloud', tenant: 'd6525c955c5s57cxs7cxs8cs4c5s84c8s'
DEBUG: 3:08:56 PM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'d6525c955c5s57cxs7cxs8cs4c5s84c8s', Scopes:'https://management.core.windows.net//.default',
AuthorityHost:'https://login.microsoftonline.com/', UserId:'ArpitMishra@eaton.com'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [07/20 09:38:56.71 - 8dc02c9d-05d5-48e3-9fe0-24f0cd6ccaf6] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [07/20 09:38:56.71 - 8dc02c9d-05d5-48e3-9fe0-24f0cd6ccaf6] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [07/20 09:38:56.71 - 8dc02c9d-05d5-48e3-9fe0-24f0cd6ccaf6] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [07/20 09:38:56.71 - 8dc02c9d-05d5-48e3-9fe0-24f0cd6ccaf6] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [07/20 09:38:56.71 - 8dc02c9d-05d5-48e3-9fe0-24f0cd6ccaf6] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [07/20 09:38:56.71] Found 1 cache accounts and 0 broker accounts
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [07/20 09:38:56.71] Returning 1 accounts
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [07/20 09:38:56.71 - 22958827-9293-45dd-b8f4-f165bf398174] MSAL MSAL.Desktop with assembly version '4.39.0.0'.
CorrelationId(22958827-9293-45dd-b8f4-f165bf398174)
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [07/20 09:38:56.71 - 22958827-9293-45dd-b8f4-f165bf398174] === AcquireTokenSilent Parameters ===
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [07/20 09:38:56.71 - 22958827-9293-45dd-b8f4-f165bf398174] LoginHint provided: False
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [07/20 09:38:56.71 - 22958827-9293-45dd-b8f4-f165bf398174] Account provided: True
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [07/20 09:38:56.71 - 22958827-9293-45dd-b8f4-f165bf398174] ForceRefresh: False
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [07/20 09:38:56.71 - 22958827-9293-45dd-b8f4-f165bf398174]
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 22958827-9293-45dd-b8f4-f165bf398174
UserAssertion set: False
LongRunningOboCacheKey set: False
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [07/20 09:38:56.71 - 22958827-9293-45dd-b8f4-f165bf398174] === Token Acquisition (SilentRequest) started:
  Scopes: https://management.core.windows.net//.default
 Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [07/20 09:38:56.71 - 22958827-9293-45dd-b8f4-f165bf398174] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [07/20 09:38:56.71 - 22958827-9293-45dd-b8f4-f165bf398174] Access token is not expired. Returning the found cache entry.
[Current time (07/20/2022 09:38:56) - Expiration Time (07/20/2022 10:26:38 +00:00) - Extended Expiration Time (07/20/2022 10:26:38 +00:00)]
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [07/20 09:38:56.71 - 22958827-9293-45dd-b8f4-f165bf398174] Returning access token found in cache. RefreshOn exists ? False
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [07/20 09:38:56.71 - 22958827-9293-45dd-b8f4-f165bf398174] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [07/20 09:38:56.71 - 22958827-9293-45dd-b8f4-f165bf398174] Fetched access token from host login.microsoftonline.com.
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [07/20 09:38:56.71 - 22958827-9293-45dd-b8f4-f165bf398174]
 === Token Acquisition finished successfully:
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [07/20 09:38:56.71 - 22958827-9293-45dd-b8f4-f165bf398174]  AT expiration time: 7/20/2022 10:26:38 AM +00:00, scopes
https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default source Cache from login.microsoftonline.com appHashCode 45000482
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2022-07-20T10:26:38.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'd6525c955c5s57cxs7cxs8cs4c5s84c8s', UserId: 'ArpitMishra@eaton.com'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/dsdsdsd8sdswd8-f-5dd4db96cd6f/resourceGroups/test-rg/providers/Microsoft.ApiManagement/service/apim-test/apis/f
scs5csxcscx4s4b82a07e5b758064a6cb?api-version=2021-08-01

Headers:
x-ms-client-request-id        : fd5d64f6-c0ac-490f-9406-113a9fa8742b
accept-language               : en-US

Body:
{
  "properties": {
    "path": "deploycd",
    "value": "https://ftn-deploycd.azurewebsites.net/items",
    "format": "openapi-link"
  }
}

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : 24c88fae-5066-4744-b2de-cde6d4757532
x-ms-correlation-request-id   : 24c88fae-5066-4744-b2de-cde6d4757532
x-ms-routing-request-id       : SOUTHEASTASIA:20220720T093857Z:24c88fae-5066-4744-b2de-cde6d4757532
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Wed, 20 Jul 2022 09:38:57 GMT

Body:
{
  "error": {
    "code": "ResourceGroupNotFound",
    "message": "Resource group 'rg-test' could not be found."
  }
}

DEBUG: 3:08:57 PM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
Import-AzApiManagementApi :
Error Code: ResourceGroupNotFound
Error Message: Resource group 'rg-test' could not be found.
Request Id: 24c88fae-5066-4744-b2de-cde6d4757532
At line:1 char:1
+ Import-AzApiManagementApi -Context $context -SpecificationFormat Open ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (Microsoft.Azure...ExecuteCmdlet():ErrorResponseException) [Import-AzApiManagementApi], Exception
    + FullyQualifiedErrorId : Operation returned an invalid status code 'NotFound',Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.ImportAzureApiManagementApi

DEBUG: 3:08:57 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent: Module: Az.ApiManagement:3.0.0; CommandName: Import-AzApiManagementApi; PSVersion: 5.1.19041.1682; IsSuccess: False; Duration: 00:00:00.9205475; Exception:
Error Code: ResourceGroupNotFound
Error Message: Resource group 'rg-test' could not be found.
Request Id: 24c88fae-5066-4744-b2de-cde6d4757532
;
DEBUG: Finish sending metric.
DEBUG: 3:08:58 PM - ImportAzureApiManagementApi end processing.
```

### Environment data

```PowerShell
PS C:\Users\E0678235> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
Script     2.9.0      Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault...}
Script     3.0.0      Az.ApiManagement                    {Add-AzApiManagementApiToGateway, Add-AzApiManagementApiToProduct, Add-AzApiManagementProductToGroup, Add-AzApiManagementRegion...}
```

### Error output

```PowerShell
Import-AzApiManagementApi :
Error Code: ResourceGroupNotFound 
Error Message: Resource group 'rg-test' could not be found.
Request Id: 24c88fae-5066-4744-b2de-cde6d4757532
At line:1 char:1
+ Import-AzApiManagementApi -Context $context -SpecificationFormat Open ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (Microsoft.Azure...ExecuteCmdlet():ErrorResponseException) [Import-AzApiManagementApi], Exception
    + FullyQualifiedErrorId : Operation returned an invalid status code 'NotFound',Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.ImportAzureApiManagementApi
```

**Comment by SaurabhSharma-MSFT** [comment] 2022-07-22 16:51
@arpitmishra-eaton  Please use `Connect-AzAccount -Subscription "subscription-id" -Tenant "tenant-id"` to connect first to respective subscription and try above cmdlets again.

**Comment by arpitmishra-eaton** [comment] 2022-08-01 06:59
helped. Thanks!

**Comment by arpitmishra-eaton** [comment] 2022-08-01 07:02
also, i'm trying to import the function app api to apim with below command and getting 401 error. 

Import-AzApiManagementApi -Context $context -SpecificationUrl https://publiclyaccessibleurl.com/test/items -SpecificationFormat OpenApi -Path deployCD

Response status code does not indicate success: 401 (Access
Denied).., Target= representation]
At line:1 char:1
+ Import-AzApiManagementApi -Context $context -SpecificationUrl https:/ ...


**is there any way we can provide the authentication, please:?**  Please help me to understand

**Comment by SaurabhSharma-MSFT** [comment] 2022-08-31 19:40
@arpitmishra-eaton I am not able to reproduce your issue.  Are you passing correct specification url.  Did you generate your specification URL using swagger for the function app?  If so, you need to change your --SpecificationFormat as Swagger. 
Please let me know if you have any other questions.

**Comment by SaurabhSharma-MSFT** [comment] 2022-09-06 21:49
@arpitmishra-eaton Please let me know if you have any questions else, we will proceed with the closure of this issue.

**Comment by SaurabhSharma-MSFT** [comment] 2022-09-12 22:04
@arpitmishra-eaton We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.

**Closed by SaurabhSharma-MSFT** 2022-09-12 22:04 UTC
Labels: API Management, bug, customer-reported, needs-team-attention, needs-author-feedback, CXP Attention
