### ISSUE TITLE
connect-AzAccount popup not working for administrator:powershell 7

### ISSUE THREAD

**Issue by HanWan9** [Azure/azure-powershell#24973] opened 2024-05-22 23:31 UTC
### Description

As title describes,
When I tried to run connect-AzAccount on administrator: power shell 7, it will return an error:
Connect-AzAccount: InteractiveBroswerCredential authentication failed: User canceled authentication. 

both power shell 5 and administrator: powershell 5 are working
powershell 7 also works

Only administrator:powershell 7 doesn't work.

### Issue script & Debug output

```PowerShell
PowerShell 7.4.2
PS C:> connect-AzAccount
Please select the account you want to login with.

WARNING: Unable to acquire token for tenant 'organizations' with error 'InteractiveBrowserCredential authentication failed: User canceled authentication. '
WARNING: Please run 'Connect-AzAccount -DeviceCode' if browser is not supported in this session.
Connect-AzAccount: InteractiveBrowserCredential authentication failed: User canceled authentication.
PS C:>
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
PS C:> Get-Module Az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     3.0.0                 Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzConte…
```

### Error output

```PowerShell
HistoryId: 1

Message        : InteractiveBrowserCredential authentication failed: User canceled authentication.
StackTrace     :    at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage, Boolean
                 isCredentialUnavailable)
                    at Azure.Identity.InteractiveBrowserCredential.AuthenticateImplAsync(Boolean async, TokenRequestContext requestContext,
                 CancellationToken cancellationToken)
                    at Azure.Identity.InteractiveBrowserCredential.AuthenticateAsync(TokenRequestContext requestContext, CancellationToken
                 cancellationToken)
                    at Microsoft.Azure.PowerShell.Authenticators.MsalAccessToken.GetAccessTokenAsync(Task`1 authTask, TokenCredential
                 tokenCredential, TokenRequestContext requestContext, CancellationToken cancellationToken)
                    at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account,
                 IAzureEnvironment environment, String tenant, SecureString password, String promptBehavior, Action`1 promptAction,
                 IAzureTokenCache tokenCache, String resourceId)
                    at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.AcquireAccessToken(IAzureAccount account,
                 IAzureEnvironment environment, String tenantId, SecureString password, String promptBehavior, Action`1 promptAction, String
                 resourceId)
                    at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.ListAccountTenants(IAzureAccount account,
                 IAzureEnvironment environment, SecureString password, String promptBehavior, Action`1 promptAction)
                    at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment
                 environment, String tenantIdOrName, String subscriptionId, String subscriptionName, SecureString password, Boolean
                 skipValidation, IOpenIDConfiguration openIDConfigDoc, Action`1 promptAction, String name, Boolean shouldPopulateContextList,
                 Int32 maxContextPopulation, String authScope, Boolean isInteractiveAuthenticationFlow, Boolean
                 IsInteractiveContextSelectionEnabled)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass134_2.<ExecuteCmdlet>b__7()
                    at System.Threading.Tasks.Task`1.InnerInvoke()
                    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext
                 executionContext, ContextCallback callback, Object state)
                 --- End of stack trace from previous location ---
                    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext
                 executionContext, ContextCallback callback, Object state)
                    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                 --- End of stack trace from previous location ---
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass134_1.<ExecuteCmdlet>b__1(AzureRmProfile
                 localProfile, RMProfileClient profileClient, String name)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass149_0.<SetContextWithOverwritePrompt>b__0(Az
                 ureRmProfile prof, RMProfileClient client)
                    at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1
                 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Azure.Identity.AuthenticationFailedException
InvocationInfo : {Connect-AzAccount}
Line           : connect-AzAccount
Position       : At line:1 char:1
                 + connect-AzAccount
                 + ~~~~~~~~~~~~~~~~~
HistoryId      : 1

Message        : User canceled authentication.
StackTrace     :    at Microsoft.Identity.Client.Platforms.Features.RuntimeBroker.WamAdapters.HandleResponse(AuthResult authResult,
                 AuthenticationRequestParameters authenticationRequestParameters, ILoggerAdapter logger, String errorMessage)
                    at Microsoft.Identity.Client.Platforms.Features.RuntimeBroker.RuntimeBroker.SignInInteractivelyAsync(AuthenticationRequestPara
                 meters authenticationRequestParameters)
                    at Microsoft.Identity.Client.Platforms.Features.RuntimeBroker.RuntimeBroker.AcquireTokenInteractiveAsync(AuthenticationRequest
                 Parameters authenticationRequestParameters, AcquireTokenInteractiveParameters acquireTokenInteractiveParameters)
                    at Microsoft.Identity.Client.Internal.Broker.BrokerInteractiveRequestComponent.FetchTokensAsync(CancellationToken
                 cancellationToken)
                    at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.FetchTokensFromBrokerAsync(String brokerInstallUrl,
                 CancellationToken cancellationToken)
                    at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.GetTokenResponseAsync(CancellationToken cancellationToken)
                    at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync(CancellationToken cancellationToken)
                    at Microsoft.Identity.Client.Internal.Requests.RequestBase.<>c__DisplayClass11_1.<<RunAsync>b__1>d.MoveNext()
                 --- End of stack trace from previous location ---
                    at Microsoft.Identity.Client.Utils.StopwatchService.MeasureCodeBlockAsync(Func`1 codeBlock)
                    at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
                    at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.ExecuteAsync(AcquireTokenCommonParameters
                 commonParameters, AcquireTokenInteractiveParameters interactiveParameters, CancellationToken cancellationToken)
                    at Azure.Identity.AbstractAcquireTokenParameterBuilderExtensions.ExecuteAsync[T](AbstractAcquireTokenParameterBuilder`1
                 builder, Boolean async, CancellationToken cancellationToken)
                    at Azure.Identity.MsalPublicClient.AcquireTokenInteractiveCoreAsync(String[] scopes, String claims, Prompt prompt, String
                 loginHint, String tenantId, Boolean enableCae, BrowserCustomizationOptions browserOptions, Boolean async, CancellationToken
                 cancellationToken)
                    at Azure.Identity.MsalPublicClient.AcquireTokenInteractiveAsync(String[] scopes, String claims, Prompt prompt, String
                 loginHint, String tenantId, Boolean enableCae, BrowserCustomizationOptions browserOptions, Boolean async, CancellationToken
                 cancellationToken)
                    at Azure.Identity.InteractiveBrowserCredential.GetTokenViaBrowserLoginAsync(TokenRequestContext context, Boolean async,
                 CancellationToken cancellationToken)
                    at Azure.Identity.InteractiveBrowserCredential.AuthenticateImplAsync(Boolean async, TokenRequestContext requestContext,
                 CancellationToken cancellationToken)
Exception      : Microsoft.Identity.Client.MsalClientException
InvocationInfo : {Connect-AzAccount}
Line           : connect-AzAccount
Position       : At line:1 char:1
                 + connect-AzAccount
                 + ~~~~~~~~~~~~~~~~~
HistoryId      : 1
```

**Comment by isra-fel** [comment] 2024-05-23 01:34
Thanks for reporting @HanWan9
One quick question: does the window not pop up at all, or does it only pop up **after** the error?

**Comment by Garth-CD** [comment] 2024-05-23 09:00
@isra-fel I've had the same issue, in my experience the window pop up and the error is simultaneous almost. My workaround for this was to disable WAM and NewLoginExperienceV2.

**Comment by invisibleninja06** [comment] 2024-05-23 13:51
Got same issue on windows 11 with windows PowerShell as administrator.
Pop-up and error appear at nearly the same time, like its not waiting for the response and just dies immediately after calling the pop up.

Going to have to disable WAM as workaround.

**Comment by ronhowe** [comment] 2024-05-23 20:00
I feel this pain too.  It actually hangs Windows Terminal.  You have to kill it with Task Manager.

**Comment by shnrr** [comment] 2024-05-24 05:16
I am experiencing the same error.
"Update-AzConfig -EnableLoginByWam $false" disables the use of WAM to avoid the pain.

**Comment by mschtoni** [comment] 2024-05-24 06:27
Same here. Works with unprivileged user but not with powershell run as administrator:
Turn off WAM will help: _update-azconfig -EnableLoginByWam $false_

**Comment by kingweo** [comment] 2024-05-24 07:23
It's been bothering me for **4 days.**
The environmental work that was originally planned to be implemented had to be postponed for **2 days** because of this problem.
Although the real cause of the BUG has not been found, in practical applications, I will share my solutions (avoidance methods) as follows:

option1, downgrade Az.Accounts
1-1, uninstall Az.Accounts 3.0.0
1-2, install Az.Accounts 2.19.0
1-3, then use Connect-Account to log in to Azure

option2, log in to the desktop using another new user of the domain (only for domain users)
2-1, Windows Update to the latest
2-2, use the new domain user to log in to the Windows desktop
2-3, use Connect-Account to log in to Azure

The above method has not been tested on non-Azure virtual machines.

**Comment by Garth-CD** [comment] 2024-05-24 08:47
I can also confirm, the same behaviour is present in the latest version of Azure CLI (2.6.1.0). Disabling WAM with `az config set core.enable_broker_on_windows=false` works around it.

**Comment by isra-fel** [comment] 2024-05-27 00:57
> @mschtoni can this simply be executed after importing the Az.Accounts module & prior to running Connect-AzAccount?

That is correct. Note that import Az.Accounts is optional. Running any cmdlet of the module will trigger an implicit import.

**Comment by isra-fel** [comment] 2024-05-27 01:07
Thanks for all the feedback. We've shared it with the owner of the authentication library. They are looking into this with high priority.

The workaround for now is to disable the WAM feature by `Update-AzConfig -EnableLoginByWam $false`. Not that you need to do this before `Connect-AzAccount`.

I'll close this issue as a duplicate of https://github.com/Azure/azure-powershell/issues/24967 which was opened earlier. Let's continue to discussion there.

**Closed by isra-fel** 2024-05-27 01:07 UTC
Labels: bug
