### ISSUE TITLE
AzureRm.Compute storage assembly incompatibility with AzureRm.Storage

### ISSUE THREAD

**Issue by Kreby** [Azure/azure-powershell#6494] opened 2018-06-20 14:55 UTC
### Description

If the AzureRm.Compute module is loaded before the AzureRM.Storage module certain storage objects are created with the AzureRm.Compute storage assembly and seem to be incompatible with the Azure.RMStorage module.  The example below occurs when trying to use the CreateSnapshot method on a "Microsoft.WindowsAzure.Commands.Common.Storage.ResourceModel.AzureStorageBlob" for the three parameters AccessCondition, BlobRequestOptions, and OperationContext.

Conversely ensuring the AzureRM.Storage module is loaded before the AzureRM.Compute module the storage assembly from the AzureRM.Storage module is used and the objects created will work as expected.

### Script/Steps for Reproduction

This is a condensed version of the script that can be used to recreate the error when provided proper input.  It should completed successfully if the Get-AzureRmVm command is removed.

```powershell

$subscriptionName = ''
$resourceGroupName = ''
$storageAccountName = ''
$blobName = ''
$debugPreference = 'Continue'

# Ensure that the AzureRm.Compute moduel is loaded before the AzureRm.Storage module
# to reproduce the error.  This could just be replaced with an Import-Module AzureRm.Compute
# but usually there is some code to get a list of disks/blobs that need to be snapshot
Get-AzureRmVm | Out-Null

Set-AzureRmContext -SubscriptionName $subscriptionName
$storageAccountKey = (Get-AzureRmStorageAccountKey -ResourceGroupName $resourceGroupName -StorageAccountName $storageAccountName)[0].Value
$storageContext = New-AzureStorageContext -StorageAccountName $storageAccountName -StorageAccountKey $storageAccountKey
$blob = Get-AzureStorageBlob -Blob $blobName -Container 'vhds' -Context $storageContext

$snapshotOption = New-Object Microsoft.WindowsAzure.Storage.Blob.BlobRequestOptions
$snapshotOption.ServerTimeout = New-TimeSpan -Seconds 60
$snapshotOption.RetryPolicy = New-Object Microsoft.WindowsAzure.Storage.RetryPolicies.LinearRetry((New-TimeSpan -Seconds 60),[int] 5)
$accessCondition = New-Object Microsoft.WindowsAzure.Storage.AccessCondition
$accessCondition.IfModifiedSinceTime = New-Object System.DateTimeOffset ((Get-Date).AddHours(-24))
$operationContext = New-Object Microsoft.WindowsAzure.Storage.OperationContext

$snapshot = $blob.ICloudBlob.CreateSnapshot($metadata,$accessCondition,$snapshotOption,$operationContext)

```

The resulting error from the CreateSnapshot method

```powershell

Cannot convert argument "accessCondition", with value: "Microsoft.WindowsAzure.Storage.AccessCondition", for "CreateSnapshot" to type
"Microsoft.WindowsAzure.Storage.AccessCondition": "Cannot convert the "Microsoft.WindowsAzure.Storage.AccessCondition" value of type
"Microsoft.WindowsAzure.Storage.AccessCondition" to type "Microsoft.WindowsAzure.Storage.AccessCondition"."
At line:1 char:1
+ $snapshot = $blob.ICloudBlob.CreateSnapshot($metadata,$accessConditio ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument

```

After a failure the assemblies being used come from the AzureRM.Compute module as opposed to the AzureRm.Storage module.

```powershell

PS {~> $accessCondition.GetType().Assembly | Select-Object FullName,Location | Format-List


FullName : Microsoft.WindowsAzure.Storage, Version=8.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
Location : C:\Users\jeff.kirby\Documents\WindowsPowerShell\Modules\AzureRM.Compute\5.1.0\Microsoft.WindowsAzure.Storage.dll

```

When running the script without having the AzureRm.Compute module loaded the snapshot will complete successfully and the assembly used is from AzureRm.Storage

```powershell

PS {~> $accessCondition.GetType().Assembly | Select-Object FullName,Location | Format-List


FullName : Microsoft.WindowsAzure.Storage, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
Location : C:\Program Files\WindowsPowerShell\Modules\AzureRM.Storage\5.0.0\Microsoft.WindowsAzure.Storage.dll

```

### Module Version

```powershell
PS {~>  Get-Module -ListAvailable | Where-Object { $PSItem.Name -imatch 'Azure' } | Format-Table ModuleType, Version, Name

Directory: C:\Users\test.user\Documents\WindowsPowerShell\Modules

ModuleType Version Name
---------- ------- ----
    Script 0.5.1   Azure.AnalysisServices
    Script 4.3.0   Azure.Storage
    Script 0.1.0   AzureOSD.BlobSnapshot
    Script 6.2.1   AzureRM
    Script 0.6.8   AzureRM.AnalysisServices
    Script 6.1.0   AzureRM.ApiManagement
    Script 0.1.4   AzureRM.ApplicationInsights
    Script 5.0.0   AzureRM.Automation
    Script 4.0.5   AzureRM.Backup
    Script 4.1.0   AzureRM.Batch
    Script 0.14.2  AzureRM.Billing
    Script 5.0.0   AzureRM.Cdn
    Script 0.9.5   AzureRM.CognitiveServices
    Script 5.1.0   AzureRM.Compute
    Script 0.3.3   AzureRM.Consumption
    Script 0.2.6   AzureRM.ContainerInstance
    Script 1.0.5   AzureRM.ContainerRegistry
    Script 5.0.0   AzureRM.DataFactories
    Script 0.5.5   AzureRM.DataFactoryV2
    Script 5.0.0   AzureRM.DataLakeAnalytics
    Script 6.0.1   AzureRM.DataLakeStore
    Script 4.0.5   AzureRM.DevTestLabs
    Script 5.0.0   AzureRM.Dns
    Script 4.0.1   AzureRM.Dns
    Script 0.3.3   AzureRM.EventGrid
    Script 0.6.4   AzureRM.EventHub
    Script 4.1.3   AzureRM.HDInsight
    Script 5.0.0   AzureRM.Insights
    Script 3.1.3   AzureRM.IotHub
    Script 5.0.1   AzureRM.KeyVault
    Script 4.0.4   AzureRM.LogicApp
    Script 0.18.0  AzureRM.MachineLearning
    Script 0.4.3   AzureRM.MachineLearningCompute
    Script 0.2.2   AzureRM.MarketplaceOrdering
    Script 0.10.0  AzureRM.Media
    Script 6.2.0   AzureRM.Network
    Script 5.0.0   AzureRM.NotificationHubs
    Script 5.0.1   AzureRM.OperationalInsights
    Script 4.1.5   AzureRM.PowerBIEmbedded
    Script 5.2.0   AzureRM.profile
    Script 4.1.3   AzureRM.RecoveryServices
    Script 4.1.3   AzureRM.RecoveryServices.Backup
    Script 0.2.5   AzureRM.RecoveryServices.SiteRecovery
    Script 5.0.0   AzureRM.RedisCache
    Script 0.3.4   AzureRM.Relay
    Script 6.1.0   AzureRM.Resources
    Script 0.16.5  AzureRM.Scheduler
    Script 0.6.5   AzureRM.ServiceBus
    Script 0.3.6   AzureRM.ServiceFabric
    Script 4.6.0   AzureRM.Sql
    Script 5.0.0   AzureRM.Storage
    Script 4.0.5   AzureRM.StreamAnalytics
    Script 4.0.2   AzureRM.Tags
    Script 4.0.5   AzureRM.TrafficManager
    Script 4.0.3   AzureRM.UsageAggregates
    Script 5.0.2   AzureRM.Websites

```

### Environment Data

```powershell

PS {~> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.15063.1155
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.1155
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### Debug Output

There is no debug output as the command itself doesn't execute but if necessary can be provided for any of the previous commands in the script used to reproduce the error.

**Comment by blueww** [comment] 2018-06-21 02:03
@Kreby 

The issue is caused by the XSCL (Microsoft.WindowsAzure.Storage ) version is different in Storage module and other feature module (like compute module). 
This is known and by design. Actually even we make them use same version of XSCL, the issue can still repro if you load any PowerShell module which use different XSCL version first.

So there are 2 resolutions:
1. Don't run compute cmdlet first, only run storage cmdlets, before create any XSCL objects (e.g. BlobRequestOptions).
2. Specify the XSCL version when create XSCL objects, and use the version same with object created from the storage cmdlets.


Besides that, compute module also has some cmdlets which deal with snapshot, you might can see if any can match your requirement.
```powershell
$blob = Get-AzureStorageBlob -Blob $blobName -Container 'vhds' -Context $storageContext

$assemblySN = $blob.ICloudBlob.GetType().Assembly.FullName

$snapshotOption = New-Object "Microsoft.WindowsAzure.Storage.Blob.BlobRequestOptions,$assemblySN"
$snapshotOption.ServerTimeout = New-TimeSpan -Seconds 60
$snapshotOption.RetryPolicy = New-Object "Microsoft.WindowsAzure.Storage.RetryPolicies.LinearRetry,$assemblySN" -ArgumentList (New-TimeSpan -Seconds 60),5
$accessCondition = New-Object "Microsoft.WindowsAzure.Storage.AccessCondition,$assemblySN"
$accessCondition.IfModifiedSinceTime = New-Object System.DateTimeOffset ((Get-Date).AddHours(-24))
$operationContext = New-Object "Microsoft.WindowsAzure.Storage.OperationContext,$assemblySN"

$snapshot = $blob.ICloudBlob.CreateSnapshot($metadata,$accessCondition,$snapshotOption,$operationContext)
```

We have a similar issue for Azure.Storage and AzureRm.Storage XSCL version different. This is fixed since they are frequently used together. But you still can find some sample script for how to use the specified XSCL version in create storage objects.https://github.com/Azure/azure-powershell/issues/5030

**Comment by blueww** [comment] 2018-07-27 06:43
@Kreby 

Not sure if you have tried my workaround on this?
Do you mind I close this issue if no other questions?

**Comment by Kreby** [comment] 2018-07-30 14:45
@blueww 

Yes, I was able to use the suggested workaround.   It is still a little bit awkward but it has at least allowed me to continue on.  Please feel free to close out the issue as I don't have any other questions at this time.

Thanks again!

**Closed** 2018-07-31 02:34 UTC
Labels: Storage

**Comment by blueww** [comment] 2018-07-31 02:36
@Kreby 
Good to know the workaround works for you.
Close the issue now
