### ISSUE TITLE
Add-AzureVirtualNetworkSubnetConfig Subnets are missing their IDs

### ISSUE THREAD

**Issue by brharr** [Azure/azure-powershell#653] opened 2015-07-27 20:59 UTC
Here is the exact code that I ran and if you do either a Get on the Vnet or the Subnets, you will notice that none of the Subnets have Ids and this causes a problem when you get to create a Network Interface within one of the Subnets.

$vnet = New-AzureVirtualNetwork -Location $location -Name $vnetName -ResourceGroupName $rgName -AddressPrefix "10.2.0.0/16"
Add-AzureVirtualNetworkSubnetConfig -VirtualNetwork $vnet -Name "Subnet-Web" -AddressPrefix "10.2.1.0/24"
Add-AzureVirtualNetworkSubnetConfig -VirtualNetwork $vnet -Name "Subnet-Api" -AddressPrefix "10.2.2.0/24"
Add-AzureVirtualNetworkSubnetConfig -VirtualNetwork $vnet -Name "Subnet-Data" -AddressPrefix "10.2.3.0/24"
Add-AzureVirtualNetworkSubnetConfig -VirtualNetwork $vnet -Name "Subnet-Shared" -AddressPrefix "10.2.4.0/24"

I have also tried using all of the other availablet Subnet Config based cmdlets and none of them set an Id on the Subnet and that Id is needed as I mentioned in the New-AzureVirtualNetworkInterface cmdlet. I now have a blocker with my code and cannot move forward.

Thanks,
Brian

**Comment by brharr** [comment] 2015-07-27 21:40
The biggest part of this problem is the required Subnet parameter for the New-AzureVirtualNetworkInterface. In an ARM template you are creating the Nic, attaching it to a VM which is part of a Subnet, not making the Nic part of the Subnet before the VM is even created.

**Comment by brharr** [comment] 2015-07-28 16:37
An additional piece of information. If you run the New-AzureVirtualNetworkSubnetConfig cmdlet first and then pass the output to the New-AzureVirtualNetwork, then the Subnet ID gets populated. 

This allows me to create the first subnet within the virtual network successfully, but there is no way for me to add a subnet that will be populated with an Id and I have tried every possibility.

**Comment by DeepakRajendranMsft** [comment] 2015-11-11 19:10
Hi @brharr, Sorry for delayed response. Add-AzureVirtualNetworkSubnetConfig does not create the subnet on the service. It simply creates an in-memory object. To your commands above, please add this at the end. "Set-AzureVirtualNetwork -VirtualNetwork $vnet" this would create all the subnets on the service and then it could be referenced by the nic. Kindly let us know if this works for you.

**Comment by DeepakRajendranMsft** [comment] 2016-03-29 03:55
closing since resolved

**Closed by DeepakRajendranMsft** 2016-03-29 03:55 UTC
Labels: Networking

**Comment by Placid7** [comment] 2019-04-03 18:08
@DeepakRajendranMsft I think this needs to be reopened. I can confirm the same issue and I am using `Set-AzVirtualNetwork -VirtualNetwork $virtualNetwork`....


`    Add-AzVirtualNetworkSubnetConfig -Name $newSubnetName -VirtualNetwork $virtualNetwork -AddressPrefix $resources.SubnetAddressSpace -NetworkSecurityGroup $networkSecurityGroup
Set-AzVirtualNetwork -VirtualNetwork $virtualNetwork`

My resource then looks like the below...

`Name                    : xxxxxxxxxxxxxxxxxxxx
Id                      : 
Etag                    : 
ProvisioningState       : 
AddressPrefix           : {10.0.9.0/26}
IpConfigurations        : null
ResourceNavigationLinks : null
ServiceAssociationLinks : null
NetworkSecurityGroup    : {
                            "Id": "/subscriptions/xxxxxxxxxxxxxxxxxxxxxx/resourceGroups/xxxxxxxxxxxxxxxxxxx/providers/Microsoft.Network/networkSecurityGroups/xxxxxxxxxxxxx"
                          }
RouteTable              : null
ServiceEndpoints        : null
ServiceEndpointPolicies : null
InterfaceEndpoints      : null`
