### ISSUE TITLE
Set-AzureKeyVaultSecret not working in a Script when endpoint is AzureStack

### ISSUE THREAD

**Issue by ChrisLGardner** [Azure/azure-powershell#5596] opened 2018-02-21 21:13 UTC
### Description

When attempting to set the value of a secret in Key Vault on AzureStack from within a pester script I'm getting errors that appear to be caused by ADAL. Running the same command from an interactive prompt doesn't cause these errors. Both methods are logged in with the same user account and has Get/Set/Update permissions on secrets in Key Vault. All the other commands in the script work fine while interacting with AzureStack, like creating storage accounts and doing things with those.

The error is:
```
Set-AzureKeyVaultSecret : user_interaction_required: One of two conditions was encountered: 1. The PromptBehavior.Never flag was passed, but the constraint could not be honored, 
because user interaction was required. 2. An error occurred during a silent web authentication that prevented the http authentication flow from completing in a short enough time 
frame
```

### Script/Steps for Reproduction

Running the following in a pester script.
```powershell
Set-AzureKeyVaultSecret -VaultName $KeyVaultName -Name 'SomeString' -SecretValue $SecureToken
```

### Module Version

AzureRM Version = 1.2.11

Most of the modules appear to be 3.4.1 or similar. This was configured using the AzureStack documentation.

### Environment Data

PSVersion is 5.1 running on Server 2016

**Comment by maddieclayton** [comment] 2018-02-27 22:38
@ChrisLGardner Are any other KeyVault cmdlet that are working for you?  This will help narrow down what the issue is.

**Comment by ChrisLGardner** [comment] 2018-03-01 09:49
@maddieclayton  it also happens with Get-AzureKeyVaultSecret and Get-AzureKeyVaultKey. I'm not sure of a good way to debug this since it's running inside a pester test. I can try setting some breakpoints and running things from within the same scope to see if that's potentially a problem.

I'll do some more digging and get back to you with what I find, if anything.

**Comment by glloyd2010f** [comment] 2018-03-15 14:22
Has there been any update regarding this? I am getting the same error, something to note is that I get it outside of pester.

**Comment by maddieclayton** [comment] 2018-03-15 20:26
@bganapa Can you take a look at this issue?

**Comment by bganapa** [comment] 2018-03-15 21:04
@ChrisLGardner  Is this an ADFS AzureStack environment by any chance?. Can you open a new session and try this?

In AzureStack ADFS environment the refreshToken obtained expires within 8 hours. We have an issue to increase the refresh token expiry.

**Comment by ChrisLGardner** [comment] 2018-03-15 21:26
@bganapa it is an ADFS AzureStack environment.

I have a step in my test script which runs Login-AzureRmAccount before it runs any tests so I can't imagine it's a refreshToken issue, especially as all my other AzureRM cmdlets work fine before and after it.

I'll test again tomorrow when I can access the Stack and update with what I find.

**Comment by bganapa** [comment] 2018-03-15 21:59
It happens like this. You get an AccessToken + RefreshToken when you do a Login-AzureRmAccount initially

Subsequent Login-AzureRmAccount will fetch the AccessToken from the TokenCache as long as it is not expired. If the AccessToken is expired, ADAL is supposed to get a new AcesssToken and RefreshToken.  This happens fine with AAD, with ADFS we are only getting a new AccessToken and not a new RefreshToken. (another issue, we are tracking). So your RefreshToken may have expired even though you have a valid AccessToken.  All these while we are taking about AccessToken targeted towards the ResourceManger Endpoint

With data plane keyvault cmdlets, we need a separate AccessToken targeted towards the vault endpoint. For this purpose,  RefreshToken is being used to get a new AcessToken. At this point we find that RefreshToken is expired and the error is being thrown. This is why only the dataplane cmdlets are the only ones affected by this issue. Hope this makes sense. We are working towards fixing both the issues.

**Comment by ChrisLGardner** [comment] 2018-03-16 11:23
Testing this and it seems to work correctly now.

Is there any way to clear down the TokenCache or is it cleared when closing the PS window?

**Comment by glloyd2010f** [comment] 2018-03-19 16:13
So I was trying to test again today and I am still having issues.

I did some manual walk through and got these results. I did use two separate PowerShell windows for these tests.

Figured I'd mention this before this issue was closed.

**Login-AzureRmAccount Method**
1. Login-AzureRmAccount
2. Set-AzureRmContext -Subscription $subscriptionId
3. $kvName = 'vaultName'
4. $test = (Get-AzureKeyVaultSecret -VaultName $kvName -Name secretName).SecretValueText
5. $test
    CorrectSecretDisplayed

**Import-Context Method**
1. Import-AzureRmContext -Path $pathToFile
2. $kvName = 'vaultName'
3. $test = (Get-AzureKeyVaultSecret -VaultName $kvName -Name secretName).SecretValueText
    Get-AzureKeyVaultSecret : user_interaction_required: One of two conditions was encountered:
    1. The PromptBehavior. Never flag was passed, but the constraint could not be honored, because user interaction was required.
    2. An error occurred during a silent web authentication that prevented the http authentication flow from completing in a short enough time frame
At line:1 char:10
+ $test = (Get-AzureKeyVaultSecret -VaultName $kvName -Name secretName ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : CloseError: (:) [Get-AzureKeyVaultSecret], AdalException
     + FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.GetAzureKeyVaultSecret

**Comment by bganapa** [comment] 2018-03-20 20:10
@glloyd2010f  It could be the case that when you do a Import-AzureRmContext , the loaded file has the  expired RefreshToken. ( I thought of trying out the scenario, but has not got a chance yet)

@ChrisLGardner 
You can do Clear-AzureRmContext  specifying the -Scope. You can look in to the cache by doing [Microsoft.Azure.Commands.Common.Authentication.AzureSession]::Instance.TokenCache.ReadItems()

**Comment by glloyd2010f** [comment] 2018-04-03 16:57
@bganapa Turns out I was being foolish, the account I was leveraging had it's settings changed and the password expired. Once I got that corrected I no longer had issues. Sorry all for the hijacking the thread.

**Comment by bganapa** [comment] 2018-05-10 22:35
Closing this issue

**Closed by bganapa** 2018-05-10 22:35 UTC
Labels: AzureStack

**Comment by lucidqdreams** [comment] 2018-10-17 18:47
I just ran into this issue, is this meant to be fixed in 1808 or is this fix still coming?

**Comment by bganapa** [comment] 2018-10-17 22:03
@lucidqdreams what version of AzureRm and AzureRm.Keyvault are you using?  Is this on ADFS environment?

Can you please do Clear-AzureRmContext -Scope CurrentUser -Force and then open a new session, login and then try? If that works, The issue is likely with the saved azurerm context.

**Comment by bganapa** [comment] 2018-10-26 17:19
Linking to this issue in ADAL https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1299
